Repository arangodb/arangodb, pull requests merged in 2018-10, with the labels that each got.

#6663 Bug fix 3.3/agency update endpoints
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyCommon.h
  arangod/Agency/AgencyStrings.h
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/AgentConfiguration.cpp
  arangod/Agency/AgentConfiguration.h
  arangod/Agency/AgentInterface.h
  arangod/Agency/GossipCallback.cpp
  arangod/Agency/Inception.cpp
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Agency/RestAgencyPrivHandler.cpp
  arangod/Agency/RestAgencyPrivHandler.h
  arangod/Agency/State.cpp
  arangod/Agency/State.h
  arangod/Agency/Store.cpp
  arangod/Agency/Store.h
  js/client/tests/agency/agency-test.js
  tests/Agency/ActiveFailoverTest.cpp
  tests/Agency/AddFollowerTest.cpp
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/FailedFollowerTest.cpp
  tests/Agency/FailedLeaderTest.cpp
  tests/Agency/FailedServerTest.cpp
  tests/Agency/MoveShardTest.cpp
  tests/Agency/RemoveFollowerTest.cpp
Labels: Team Clifton

#6652 Change tests setUp/tearDown to be common
  tests/js/client/resilience/foxxmaster.js
Labels: 3 - Testing, 3 Cluster, 3 Foxx Queues

#6666 Feature 3.4/detailed get maintenance feature
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/DBServerAgencySync.h
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/MaintenanceRestHandler.cpp
  scripts/generateMaintenanceTestData.sh
  tests/Maintenance/Current.json
  tests/Maintenance/DBServer0001.json
  tests/Maintenance/DBServer0002.json
  tests/Maintenance/DBServer0003.json
  tests/Maintenance/MaintenanceTest.cpp
  tests/Maintenance/Plan.json
  tests/Maintenance/Supervision.json
Labels: 2 - Working, Team Clifton

#6668 Feature/detailed get maintenance feature
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/DBServerAgencySync.h
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/MaintenanceRestHandler.cpp
  scripts/generateMaintenanceTestData.sh
  tests/Maintenance/Coordinator0001.json
  tests/Maintenance/Coordinator0002.json
  tests/Maintenance/Current.json
  tests/Maintenance/DBServer0001.json
  tests/Maintenance/DBServer0002.json
  tests/Maintenance/DBServer0003.json
  tests/Maintenance/Plan.json
  tests/Maintenance/Supervision.json
Labels: Team Clifton

#6641 Doc - Improve backup page
  Documentation/Books/Manual/Administration/BackupRestore.md
  Documentation/Books/Manual/Administration/README.md
  Documentation/Books/Manual/BackupRestore/README.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#6664 Increase Plan/Version if follower is removed in MoveShard.
  arangod/Agency/MoveShard.cpp
Labels: 3 - Testing, Team Clifton

#6665 Add more timeout because in Jenkins dbservers can be slow.
  arangod/Cluster/EngineEqualityCheckFeature.cpp
Labels: 3 - Testing, Team Clifton

#6669 Increase Plan/Version if follower is removed in MoveShard.
  arangod/Agency/MoveShard.cpp
Labels: 3 - Testing, Team Clifton

#6667 Add more timeout because in Jenkins dbservers can be slow.
  arangod/Cluster/EngineEqualityCheckFeature.cpp
Labels: 3 - Testing, Team Clifton

#6600 Feature 3.4/windows utf16 fileaccess
  3rdParty/rocksdb/CMakeLists.txt
  3rdParty/rocksdb/v5.16.X/CMakeLists.txt
  3rdParty/rocksdb/v5.16.X/port/win/env_win.cc
  3rdParty/rocksdb/v5.16.X/port/win/port_win.cc
  3rdParty/rocksdb/v5.16.X/port/win/port_win.h
  Installation/Windows/Plugins/Utf8Converter.nsh
  Installation/Windows/Templates/NSIS.template.in
  arangod/Cluster/ServerState.cpp
  arangod/RestServer/InitDatabaseFeature.cpp
  arangod/RestServer/ServerFeature.cpp
  arangod/RestServer/ServerFeature.h
  arangod/RestServer/arangod.cpp
  arangosh/Benchmark/arangobench.cpp
  arangosh/Dump/arangodump.cpp
  arangosh/Export/arangoexport.cpp
  arangosh/Import/arangoimport.cpp
  arangosh/Restore/arangorestore.cpp
  arangosh/Shell/ClientFeature.cpp
  arangosh/Shell/ClientFeature.h
  arangosh/Shell/ConsoleFeature.cpp
  arangosh/Shell/ConsoleFeature.h
  arangosh/Shell/arangosh.cpp
  arangosh/VPack/arangovpack.cpp
  lib/ApplicationFeatures/DaemonFeature.cpp
  lib/ApplicationFeatures/LanguageFeature.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/FileUtils.h
  lib/Basics/files.cpp
  lib/Basics/files.h
  lib/Basics/operating-system.h
  lib/Basics/process-utils.cpp
  lib/Basics/tri-zip.cpp
  lib/Basics/win-utils.cpp
  lib/Logger/LogAppenderFile.cpp
  lib/ProgramOptions/IniFileParser.h
  lib/ProgramOptions/Translator.cpp
  lib/V8/v8-globals.h
  lib/V8/v8-utils.cpp
  lib/Zip/iowin32.cpp
  tests/main.cpp
Labels: 2 - Working

#6662 Mark flaky test nondeterministic for now
  tests/js/server/recovery/view-arangosearch-rename-no-flushthread-nondeterministic.js
Labels: 2 - Working

#6673 Mark flaky test nondeterministic for now
  tests/js/server/recovery/view-arangosearch-rename-no-flushthread-nondeterministic.js
Labels: 2 - Working

#6672 forward-port some RocksDB bugfix
  3rdParty/rocksdb/v5.16.X/db/range_del_aggregator.cc
  3rdParty/rocksdb/v5.16.X/db/range_del_aggregator_test.cc
Labels: 2 - Working

#6671 forward-port some RocksDB bugfix
  3rdParty/rocksdb/v5.16.X/db/range_del_aggregator.cc
  3rdParty/rocksdb/v5.16.X/db/range_del_aggregator_test.cc
Labels: 2 - Working

#6676 added yet another missing RangeDelete implementation
  arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
Labels: 2 - Working

#6677 added yet another missing DeleteRange implementation
  arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
Labels: 2 - Working

#6679 Fix ICU path building, windows codepage correctness
  arangod/RestServer/ServerFeature.cpp
  arangod/RestServer/ServerFeature.h
  arangosh/Shell/ClientFeature.cpp
  lib/ApplicationFeatures/LanguageFeature.cpp
Labels: 2 - Working

#6684 Debug logs for ActiveFailover
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Scheduler/Scheduler.cpp
  tests/js/client/active-failover/basic.js
Labels: 2 - Working

#6680 Documentation/sync 2018 10 02 (rename arangodbjs to arangojs)
  Documentation/Books/Drivers/JS/GettingStarted/README.md
  Documentation/Books/Drivers/JS/README.md
  Documentation/Books/Drivers/JS/Reference/Collection/BulkImport.md
  Documentation/Books/Drivers/JS/Reference/Collection/CollectionManipulation.md
  Documentation/Books/Drivers/JS/Reference/Collection/DocumentCollection.md
  Documentation/Books/Drivers/JS/Reference/Collection/DocumentManipulation.md
  Documentation/Books/Drivers/JS/Reference/Collection/EdgeCollection.md
  Documentation/Books/Drivers/JS/Reference/Collection/Indexes.md
  Documentation/Books/Drivers/JS/Reference/Collection/README.md
  Documentation/Books/Drivers/JS/Reference/Collection/SimpleQueries.md
  Documentation/Books/Drivers/JS/Reference/Cursor.md
  Documentation/Books/Drivers/JS/Reference/Database/AqlUserFunctions.md
  Documentation/Books/Drivers/JS/Reference/Database/CollectionAccess.md
  Documentation/Books/Drivers/JS/Reference/Database/DatabaseManipulation.md
  Documentation/Books/Drivers/JS/Reference/Database/FoxxServices.md
  Documentation/Books/Drivers/JS/Reference/Database/GraphAccess.md
  Documentation/Books/Drivers/JS/Reference/Database/HttpRoutes.md
  Documentation/Books/Drivers/JS/Reference/Database/Queries.md
  Documentation/Books/Drivers/JS/Reference/Database/README.md
  Documentation/Books/Drivers/JS/Reference/Database/Transactions.md
  Documentation/Books/Drivers/JS/Reference/Database/ViewAccess.md
  Documentation/Books/Drivers/JS/Reference/Graph/EdgeCollection.md
  Documentation/Books/Drivers/JS/Reference/Graph/Edges.md
  Documentation/Books/Drivers/JS/Reference/Graph/README.md
  Documentation/Books/Drivers/JS/Reference/Graph/VertexCollection.md
  Documentation/Books/Drivers/JS/Reference/Graph/Vertices.md
  Documentation/Books/Drivers/JS/Reference/README.md
  Documentation/Books/Drivers/JS/Reference/Route.md
  Documentation/Books/Drivers/JS/Reference/ViewManipulation.md
  Documentation/Books/Drivers/SUMMARY.md
  Documentation/Books/Manual/Upgrading/Starter/README.md
  VERSIONS
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#6661 Fix multiple links per collection issue
  arangod/Indexes/Index.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
Labels: 2 - Working

#6675 small issues
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/IndexBlock.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/IResearch/IResearchViewBlock.cpp
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/Sharding/ShardingInfo.cpp
  tests/Futures/Future-test.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.js
Labels: 2 - Working

#6609 Active Failover upgrade guide, missing maintenance API docs
  Documentation/Books/HTTP/Cluster/Maintenance.md
  Documentation/Books/HTTP/Cluster/README.md
  Documentation/Books/HTTP/SUMMARY.md
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Upgrading/Manually/ActiveFailover.md
  Documentation/Books/Manual/Upgrading/Manually/Cluster.md
  Documentation/Books/Manual/Upgrading/Manually/README.md
  Documentation/Books/Manual/Upgrading/Starter/README.md
  Documentation/DocuBlocks/Rest/Cluster/put_cluster_maintenance.md
Labels: 2 - Working, 3 Documentation, 9 WIP

#6682 Bug fix 3.4/fix windows cp defaults
  arangod/RestServer/ServerFeature.cpp
  arangod/RestServer/ServerFeature.h
  arangosh/Shell/ClientFeature.cpp
  lib/ApplicationFeatures/LanguageFeature.cpp
Labels: 2 - Working

#6700 Backport #6630 into 3.4
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
Labels: 2 - Working, 3 ArangoSearch, 3 UI

#6698 backported some fixes from devel
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/IndexBlock.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/IResearch/IResearchViewBlock.cpp
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/Sharding/ShardingInfo.cpp
Labels: 2 - Working

#6691 Bug fix/display sync progress
  arangod/Sharding/ShardDistributionReporter.cpp
  tests/Sharding/ShardDistributionReporterTest.cpp
Labels: 2 - Working

#6692 Bug fix 3.4/display sync progress
  CHANGELOG
  arangod/Sharding/ShardDistributionReporter.cpp
  tests/Sharding/ShardDistributionReporterTest.cpp
Labels: 2 - Working

#6701 Docs: Fresh Swagger file
  js/apps/system/_admin/aardvark/APP/api-docs.json
Labels: 2 - Working, 3 Documentation

#6697 Doc - Backup Improvement
  Documentation/Books/Manual/BackupRestore/README.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation, 9 WIP

#6699 Doc - Backup Improvements
  Documentation/Books/Manual/BackupRestore/README.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation, 9 WIP

#6681 Feature/drop before win7 support in compiler
  CMakeLists.txt
  arangod/Aql/AqlItemBlock.cpp
  arangod/RestServer/InitDatabaseFeature.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/StringUtils.cpp
  lib/Rest/VstRequest.cpp
  tests/V8Server/v8-users-test.cpp
  tests/V8Server/v8-views-test.cpp
Labels: 2 - Working

#6686 Debug logs for ActiveFailover, allow recovery tests on MacOS
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Scheduler/Scheduler.cpp
  lib/Basics/files.cpp
  lib/Basics/operating-system.h
Labels: 2 - Working

#6713 Fix multiple links per collection issue (#6661)
  arangod/Indexes/Index.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
Labels: 2 - Working

#6670 even more LDAP debugging
  Documentation/Books/Manual/Administration/Configuration/Ldap.md
  arangod/Auth/TokenCache.cpp
  arangod/Auth/TokenCache.h
  arangod/Auth/User.cpp
  arangod/Auth/User.h
  arangod/Auth/UserManager.cpp
  arangod/Auth/UserManager.h
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/Statistics/RequestStatistics.cpp
  arangod/VocBase/Methods/Databases.cpp
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
  lib/Logger/LoggerFeature.cpp
  lib/Logger/LoggerFeature.h
Labels: 2 - Working

#6715 Increase plan version when cleaning out a lost collection.
  arangod/Agency/Supervision.cpp
Labels: 2 - Working, Team Clifton

#6712 Feature/improvements 031018
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/MMFiles/MMFilesFulltextIndex.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/ReplicationApplierConfiguration.cpp
  arangod/Replication/ReplicationApplierConfiguration.h
  arangod/Replication/TailingSyncer.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
  arangod/RocksDBEngine/RocksDBRestWalHandler.cpp
  arangod/RocksDBEngine/RocksDBSettingsManager.cpp
  lib/Basics/StringUtils.cpp
  lib/Basics/StringUtils.h
  lib/Basics/Utf8Helper.cpp
  lib/Basics/Utf8Helper.h
  lib/V8/v8-utils.cpp
  tests/Basics/StringUtilsTest.cpp
  tests/Basics/string-utf8-normalize-test.cpp
Labels: 2 - Working

#6720 Bug fix/cleanup lost collection inc plan v
  arangod/Agency/Supervision.cpp
Labels: 2 - Working, Team Clifton

#6703 Document --javascript.copy-installation
  Documentation/Books/Manual/Programs/Arangod/Javascript.md
  arangosh/Shell/V8ShellFeature.cpp
Labels: 2 - Working

#6702 Document --javascript.copy-installation
  Documentation/Books/Manual/Programs/Arangod/Javascript.md
  arangosh/Shell/V8ShellFeature.cpp
Labels: 2 - Working

#6693 properly display shard synchronization progress
  CHANGELOG
  arangod/Cluster/ShardDistributionReporter.cpp
  tests/Cluster/ShardDistributionReporterTest.cpp
Labels: 2 - Working

#6730 on behalf of vasilly: fix cast
  arangod/IResearch/IResearchLinkHelper.cpp
Labels: 2 - Working

#6729 added missing override specifiers
  3rdParty/iresearch/core/analysis/token_attributes.hpp
  3rdParty/iresearch/core/formats/formats_10.cpp
  3rdParty/iresearch/core/formats/formats_10_attributes.hpp
  3rdParty/iresearch/core/formats/formats_burst_trie.cpp
  3rdParty/iresearch/core/index/iterators.cpp
  3rdParty/iresearch/core/index/transaction_store.cpp
  3rdParty/iresearch/core/iql/query_builder.cpp
  3rdParty/iresearch/core/search/bm25.hpp
  3rdParty/iresearch/core/search/boolean_filter.hpp
  3rdParty/iresearch/core/search/tfidf.hpp
  3rdParty/iresearch/core/store/data_input.hpp
  3rdParty/iresearch/core/store/data_output.hpp
  3rdParty/iresearch/core/store/fs_directory.cpp
  3rdParty/iresearch/core/store/mmap_directory.hpp
  3rdParty/iresearch/core/store/store_utils.hpp
  3rdParty/iresearch/core/utils/fst_matcher.hpp
  3rdParty/iresearch/core/utils/iterator.hpp
  3rdParty/iresearch/core/utils/locale_utils.cpp
  3rdParty/iresearch/core/utils/mmap_utils.cpp
Labels: 2 - Working

#6725 Fix foxx test failures
  js/server/modules/@arangodb/foxx/service.js
  tests/js/server/shell/shell-foxx-manifest-spec.js
Labels: 2 - Working

#6724 Fix foxx test failures
  js/server/modules/@arangodb/foxx/service.js
  tests/js/server/shell/shell-foxx-manifest-spec.js
Labels: 2 - Working

#6719 Do not load counters until recovey is done
  arangod/Aql/CollectBlock.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterEngine.h
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/StorageEngine/StorageEngine.h
Labels: 2 - Working

#6723 [3.4]Cleanup Lost Collections test bug fix
  tests/Agency/CleanUpLostCollectionTest.cpp
  tests/Agency/CleanUpLostCollectionTest.json
Labels: 2 - Working, Team Clifton

#6722 Cleanup Lost Collections test bug fix
  tests/Agency/CleanUpLostCollectionTest.cpp
  tests/Agency/CleanUpLostCollectionTest.json
Labels: 2 - Working, Team Clifton

#6732 Disable New View/Service in UI
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/applicationsView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/viewsView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/applicationsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
Labels: 2 - Working

#6734 [3.4] Disable New View/Service in UI
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/applicationsView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/viewsView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/applicationsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
Labels: 2 - Working

#6737 Stop AgencyRequests on Shutdown
  lib/SimpleHttpClient/GeneralClientConnection.cpp
  lib/SimpleHttpClient/SimpleHttpClient.cpp
Labels: 2 - Working, Team Clifton

#6717 Bug fix 3.4/activefail debug
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Scheduler/Scheduler.cpp
  tests/js/client/active-failover/basic.js
Labels: 2 - Working

#6735 Bug fix 3.4/even more ldap debugging
  Documentation/Books/Manual/Programs/Arangod/Ldap.md
  arangod/Agency/Store.cpp
  arangod/Auth/TokenCache.cpp
  arangod/Auth/TokenCache.h
  arangod/Auth/User.cpp
  arangod/Auth/User.h
  arangod/Auth/UserManager.h
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/Statistics/RequestStatistics.cpp
  arangod/VocBase/Methods/Databases.cpp
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
  lib/Logger/LoggerFeature.cpp
  lib/Logger/LoggerFeature.h
Labels: 2 - Working, 9 Ready to Merge

#6745 Active-Failover test: Make assertion clearer
  tests/js/client/active-failover/basic.js
Labels: 2 - Working

#6742 turn off the in-memory cache on agency nodes, as it is not needed there
  CHANGELOG
  arangod/Cache/CacheManagerFeature.cpp
  arangod/Cache/CacheManagerFeature.h
  arangod/Graph/TraverserDocumentCache.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
Labels: 2 - Working

#6740 Bug fix/increase replication timeouts
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/Replication/utilities.h
Labels: 2 - Working

#6741 Bug fix 3.4/increase replication timeouts
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/Replication/utilities.h
Labels: 2 - Working

#6736 Bug fix/even more ldap debugging
  Documentation/Books/Manual/Programs/Arangod/Ldap.md
  arangod/Agency/Store.cpp
  arangod/Auth/TokenCache.cpp
  arangod/Auth/TokenCache.h
  arangod/Auth/User.cpp
  arangod/Auth/User.h
  arangod/Auth/UserManager.h
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/Statistics/RequestStatistics.cpp
  arangod/VocBase/Methods/Databases.cpp
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
  lib/Logger/LoggerFeature.cpp
  lib/Logger/LoggerFeature.h
Labels: 2 - Working

#6739 Backport #6719 to 3.4
  arangod/Aql/CollectBlock.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterEngine.h
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/StorageEngine/StorageEngine.h
Labels: 2 - Working

#6746 Bug fix/internal issue 1983
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
Labels: 2 - Working

#6748 Bug fix 3.4/internal issue 1983
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
Labels: 2 - Working

#6749 Bug fix 3.3/internal issue 1983
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
Labels: 2 - Working

#6752 handle a missing _frontend collection gracefully
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/server/modules/@arangodb/configuration.js
Labels: 2 - Working

#6751 handle a missing _frontend collection gracefully
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/server/modules/@arangodb/configuration.js
Labels: 2 - Working

#6750 handle a missing _frontend collection gracefully
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/server/modules/@arangodb/configuration.js
Labels: 2 - Working

#6754 add script counting network connections
  scripts/analyzeNetworkSocketUsage.sh
Labels: 2 - Working

#6753 [3.4] Stop AgencyRequests on Shutdown
  lib/SimpleHttpClient/GeneralClientConnection.cpp
  lib/SimpleHttpClient/SimpleHttpClient.cpp
Labels: 2 - Working, Team Clifton

#6759 Feature/log timestamp on test start
  js/client/modules/@arangodb/process-utils.js
  js/client/modules/@arangodb/test-utils.js
  js/common/modules/jsunity.js
  js/common/modules/jsunity/jsunity.js
Labels: 2 - Working

#6761 Feature 3.4/log timestamp on test start
  js/client/modules/@arangodb/process-utils.js
  js/client/modules/@arangodb/test-utils.js
  js/common/modules/jsunity.js
  js/common/modules/jsunity/jsunity.js
Labels: 2 - Working

#6758 [3.3] Stop AgencyRequests on Shutdown
  lib/SimpleHttpClient/GeneralClientConnection.cpp
  lib/SimpleHttpClient/SimpleHttpClient.cpp
Labels: 2 - Working, Team Clifton

#6721 Bug fix 3.3/cleanup lost collections
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  tests/Agency/CleanUpLostCollectionTest.cpp
  tests/Agency/CleanUpLostCollectionTest.json
  tests/CMakeLists.txt
Labels: 2 - Working, Team Clifton

#6733 increase the timeouts for replication, in order to increase the chanc…
  CHANGELOG
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/Replication/InitialSyncer.h
  arangod/Replication/Syncer.cpp
Labels: 2 - Working

#6708 Update CHANGELOG
  CHANGELOG
Labels: 2 - Working, 3 Documentation

#6706 Update CHANGELOG
  CHANGELOG
Labels: 2 - Working, 3 Documentation

#6707 Update CHANGELOG
  CHANGELOG
Labels: 2 - Working, 3 Documentation

#6760 Fixed failures during testSetup()
  arangod/Cluster/SynchronizeShard.cpp
  tests/js/server/resilience/moving-shards-with-arangosearch-view-cluster.js
Labels: 2 - Working

#6756 fix variable replacements in view search conditions
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.js
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
  tests/js/server/aql/aql-optimizer-rule-inline-subqueries.js
Labels: 2 - Working

#6755 Bug fix 3.4/fix variable replacement in view search conditions
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.js
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
  tests/js/server/aql/aql-optimizer-rule-inline-subqueries.js
Labels: 2 - Working

#6763 remove undocumented view.toArray() function
  js/client/modules/@arangodb/arango-view.js
Labels: 2 - Working, 9 WIP

#6764 remove undocumented view.toArray() function
  js/client/modules/@arangodb/arango-view.js
Labels: 2 - Working, 9 WIP

#6757 Improve error output in logs when replication fails.
  CHANGELOG
  arangod/MMFiles/MMFilesIncrementalSync.h
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/V8Server/v8-replication.cpp
Labels: 2 - Working

#6689 Remove a relic from early days in /Target/FailedServers.
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/Supervision.cpp
  arangod/Cluster/HeartbeatThread.cpp
  tests/Agency/FailedLeaderTest.cpp
Labels: 2 - Working

#6690 Remove a relic from early days in /Target/FailedServers.
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/Supervision.cpp
  arangod/Cluster/HeartbeatThread.cpp
  tests/Agency/FailedLeaderTest.cpp
Labels: 2 - Working

#6718 This is porting from 3.4 a cleanup in Current (follower removed from plan).
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/UpdateCollection.cpp
  tests/Maintenance/Current.json
  tests/Maintenance/DBServer0001.json
  tests/Maintenance/DBServer0002.json
  tests/Maintenance/DBServer0003.json
  tests/Maintenance/MaintenanceTest.cpp
  tests/Maintenance/Plan.json
  tests/Maintenance/Supervision.json
Labels: 2 - Working, Team Clifton

#6769 print when we mark a build crashy
  UnitTests/unittest.js
  js/client/modules/@arangodb/process-utils.js
  js/client/modules/@arangodb/testing.js
  js/client/modules/@arangodb/testsuites/replication.js
Labels: 2 - Working

#6771 Add a forgotten CHANGELOG entry in 3.3.13.
  CHANGELOG
Labels: 2 - Working

#6743 Feature/arangosearch overhaul
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchQueryAggregate-test.cpp
  tests/IResearch/IResearchQueryAnd-test.cpp
  tests/IResearch/IResearchQueryBooleanTerm-test.cpp
  tests/IResearch/IResearchQueryComplexBoolean-test.cpp
  tests/IResearch/IResearchQueryExists-test.cpp
  tests/IResearch/IResearchQueryIn-test.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/IResearch/IResearchQueryNullTerm-test.cpp
  tests/IResearch/IResearchQueryNumericTerm-test.cpp
  tests/IResearch/IResearchQueryOr-test.cpp
  tests/IResearch/IResearchQueryPhrase-test.cpp
  tests/IResearch/IResearchQuerySelectAll-test.cpp
  tests/IResearch/IResearchQueryStartsWith-test.cpp
  tests/IResearch/IResearchQueryStringTerm-test.cpp
  tests/IResearch/IResearchQueryTokens-test.cpp
  tests/IResearch/IResearchQueryTraversal-test.cpp
  tests/IResearch/IResearchQueryValue-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/IResearch/StorageEngineMock.cpp
  tests/js/server/aql/aql-query-cache-noncluster.js
  tests/js/server/dump/dump-mmfiles-cluster.js
Labels: 2 - Working

#6775 Bugfix devel: dynamic management of libcurl's open connections
  CHANGELOG
  arangod/Aql/SharedQueryState.cpp
  arangod/Cluster/ClusterComm.cpp
  lib/SimpleHttpClient/Communicator.cpp
  lib/SimpleHttpClient/Communicator.h
  tests/SimpleHttpClient/CommunicatorTest.cpp
Labels: 2 - Working

#6711 Bugfix 3.4: dynamic management of libcurl's open connections
  CHANGELOG
  Documentation/man/man1/arangobench.1
  Documentation/man/man1/arangodump.1
  Documentation/man/man1/arangoexport.1
  Documentation/man/man1/arangoimport.1
  Documentation/man/man1/arangorestore.1
  Documentation/man/man1/arangosh.1
  Documentation/man/man8/arango-dfdb.8
  Documentation/man/man8/arangod.8
  Documentation/man/man8/foxx-manager.8
  Documentation/man/man8/rcarangod.8
  arangod/Aql/SharedQueryState.cpp
  arangod/Cluster/ClusterComm.cpp
  lib/SimpleHttpClient/Communicator.cpp
  lib/SimpleHttpClient/Communicator.h
  tests/SimpleHttpClient/CommunicatorTest.cpp
Labels: 2 - Working

#6767 fix arangojs issue 573
  CHANGELOG
  arangod/Cluster/ServerState.cpp
Labels: 2 - Working

#6766 Bug fix 3.4/fix arangojs 573
  CHANGELOG
  arangod/Cluster/ServerState.cpp
Labels: 2 - Working

#6765 fix arangojs issue 573
  CHANGELOG
  arangod/Cluster/ServerState.cpp
Labels: 2 - Working

#6696 UI: Direct links in the support tab to 3.3
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/supportView.ejs
Labels: 2 - Working, 3 Documentation, 3 UI, 9 Ready to Merge

#6694 UI: Add Drivers & Integrations column + fix links for 3.4
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/supportView.ejs
Labels: 2 - Working, 3 Documentation, 3 UI, 9 Ready to Merge

#6779 Fix issue with colleciton/view name conflict checking in cluster.
  arangod/Cluster/ClusterInfo.cpp
  tests/js/common/shell/shell-view-arangosearch-link.js
  tests/js/common/shell/shell-view-arangosearch-noncluster.js
  tests/js/common/shell/shell-view-arangosearch.js
Labels: 2 - Working

#6790 potential fix for release-3.4/#79
  arangod/Auth/UserManager.cpp
Labels: 2 - Working

#6789 potential fix for release-3.4/#79
  arangod/Auth/UserManager.cpp
Labels: 2 - Working

#6794 Feature/update iresearch once again
  3rdParty/iresearch/.travis.yml
  3rdParty/iresearch/CMakeLists.txt
  3rdParty/iresearch/THIRD_PARTY_README.md
  3rdParty/iresearch/appveyor.yml
  3rdParty/iresearch/core/CMakeLists.txt
  3rdParty/iresearch/core/formats/formats_10.cpp
  3rdParty/iresearch/core/index/index_writer.cpp
  3rdParty/iresearch/core/index/index_writer.hpp
  3rdParty/iresearch/core/index/iterators.cpp
  3rdParty/iresearch/core/index/segment_writer.cpp
  3rdParty/iresearch/core/index/segment_writer.hpp
  3rdParty/iresearch/core/shared.hpp
  3rdParty/iresearch/core/store/store_utils.hpp
  3rdParty/iresearch/core/utils/async_utils.hpp
  3rdParty/iresearch/core/utils/block_pool.hpp
  3rdParty/iresearch/core/utils/crc.hpp
  3rdParty/iresearch/core/utils/memory.hpp
  3rdParty/iresearch/core/utils/object_pool.hpp
  3rdParty/iresearch/tests/index/index_tests.cpp
  3rdParty/iresearch/tests/utils/memory_tests.cpp
  3rdParty/iresearch/tests/utils/object_pool_tests.cpp
Labels: 2 - Working

#6788 Fix a bug when getting in sync and old requests are still lingering.
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/SynchronizeShard.cpp
Labels: 2 - Working, Team Clifton

#6602 Make procdump abort on std::bad_cast; kill SUT if it occurs; Make procdump optional.
  js/client/modules/@arangodb/crash-utils.js
  js/client/modules/@arangodb/process-utils.js
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testing.js
Labels: 2 - Working

#6795 Fix a bug when getting in sync and old requests are still lingering. (#6788)
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/SynchronizeShard.cpp
Labels: 2 - Working

#6812 Bug fix/internal issue 2764
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
Labels: 2 - Working

#6813 Bug fix 3.3/internal issue 2764
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
Labels: 2 - Working

#6814 Bug fix 3.4/internal issue 2764
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
Labels: 2 - Working

#6804 Bug fix 3.3/internal issue 2785
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
Labels: 2 - Working

#6803 Bug fix 3.4/internal issue 2785
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
Labels: 2 - Working

#6802 Bug fix/internal issue 2785
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
Labels: 2 - Working

#6797 Add missing CHANGELOG entrys of 3.2
  CHANGELOG
Labels: 2 - Working

#6798 Add missing CHANGELOG entrys of 3.2 + 3.3
  CHANGELOG
Labels: 2 - Working

#6796 Fix issue with colleciton/view name conflict checking in cluster.
  arangod/Cluster/ClusterInfo.cpp
  tests/js/common/shell/shell-view-arangosearch-link.js
  tests/js/common/shell/shell-view-arangosearch-noncluster.js
  tests/js/common/shell/shell-view-arangosearch.js
Labels: 2 - Working

#6787 suppress some of these dreaded error messages
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/v8-cluster.cpp
Labels: 2 - Working

#6786 suppress some of these dreaded error messages
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/v8-cluster.cpp
Labels: 2 - Working

#6785 Bug fix 3.4/views in aql collections (#6714)
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/EngineInfoContainerDBServer.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesReplaceFunctions.cpp
  arangod/Aql/Query.h
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.y
  arangod/IResearch/IResearchViewNode.cpp
  arangod/IResearch/IResearchViewOptimizerRules.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalDataSource.cpp
  arangod/VocBase/LogicalDataSource.h
  arangod/VocBase/LogicalView.cpp
  arangod/VocBase/LogicalView.h
  arangod/VocBase/vocbase.cpp
  tests/IResearch/IResearchViewNode-test.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.js
Labels: 2 - Working

#6820 Bug fix 3.4/internal issue 2688
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 2 - Working

#6816 fix internal issue #2957
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
Labels: 2 - Working

#6817 fix internal issue #2957
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
Labels: 2 - Working

#6818 Bug fix/internal issue 2688
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 2 - Working

#6819 Bug fix 3.3/internal issue 2688
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 2 - Working

#6808 fixed a caching bug in IE11
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDatabase.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
Labels: 2 - Working

#6809 fixed a caching bug in IE11
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDatabase.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
Labels: 2 - Working

#6805 Bug fix/internal issue 2035
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
Labels: 2 - Working

#6806 Bug fix 3.3/internal issue 2035
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
Labels: 2 - Working

#6807 Bug fix 3.4/internal issue 2035
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
Labels: 2 - Working

#6822 Bug fix/internal issue 2770
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 2 - Working

#6823 Bug fix 3.3/internal issue 2770
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 2 - Working

#6824 Bug fix 3.4/internal issue 2770
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 2 - Working

#6833 fix windows path escaping in testcase
  tests/js/client/shell/shell-require-canceled.js
Labels: 2 - Working

#6839 fix windows path escaping in testcase
  tests/js/client/shell/shell-require-canceled.js
Labels: 2 - Working

#6846 properly reset errno
  lib/Basics/conversions.cpp
Labels: 2 - Working

#6778 Bug fix 3.3/hyperventilating inception
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/AgentConfiguration.cpp
  arangod/Agency/AgentConfiguration.h
Labels: 2 - Working

#6851 Do not ignore document revision on updates
  arangod/RestHandler/RestDocumentHandler.cpp
Labels: 2 - Working

#6852 do not ignore document revision
  arangod/RestHandler/RestDocumentHandler.cpp
Labels: 2 - Working

#6854 Do not ignore document revision
  arangod/RestHandler/RestDocumentHandler.cpp
Labels: 2 - Working

#6856 cppcheck
  arangod/Agency/FailedServer.cpp
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ModificationBlocks.cpp
  arangod/Pregel/GraphStore.cpp
Labels: 2 - Working

#6850 velocypack library update
  3rdParty/velocypack/include/velocypack/Buffer.h
  3rdParty/velocypack/include/velocypack/Builder.h
  3rdParty/velocypack/include/velocypack/Slice.h
  3rdParty/velocypack/include/velocypack/StringRef.h
  3rdParty/velocypack/include/velocypack/velocypack-common.h
  3rdParty/velocypack/include/velocypack/velocypack-version-number.h
  3rdParty/velocypack/src/Builder.cpp
  3rdParty/velocypack/src/Slice.cpp
  3rdParty/velocypack/src/StringRef.cpp
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/VocBase/Methods/Databases.cpp
  lib/CMakeLists.txt
  tests/IResearch/common.cpp
Labels: 2 - Working

#6853 Bug fix/fixes 121018
  arangod/V8Server/V8DealerFeature.cpp
  arangosh/Dump/DumpFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
  lib/ApplicationFeatures/MaxMapCountFeature.cpp
  lib/ApplicationFeatures/MaxMapCountFeature.h
Labels: 2 - Working

#6845 Bug fix 3.4/fixes 110918 2
  arangod/Cluster/ClusterComm.cpp
  arangod/Cluster/ClusterComm.h
  arangod/Replication/ReplicationApplierConfiguration.cpp
  arangod/Replication/ReplicationApplierConfiguration.h
  arangod/Replication/utilities.cpp
Labels: 2 - Working

#6844 Bug fix 3.4/fixes 111018
  arangod/Aql/AstNode.h
  js/common/modules/jsunity.js
  lib/Basics/conversions.cpp
Labels: 2 - Working

#6843 Bug fix/fixes 111018
  arangod/Aql/AstNode.h
  js/common/modules/jsunity.js
  lib/Basics/conversions.cpp
Labels: 2 - Working

#6848 Bug fix/fixes 110918 2
  arangod/Cluster/ClusterComm.cpp
  arangod/Cluster/ClusterComm.h
  arangod/Replication/ReplicationApplierConfiguration.cpp
  arangod/Replication/ReplicationApplierConfiguration.h
  arangod/Replication/utilities.cpp
Labels: 2 - Working

#6855 slightly refactor the handling of optimizer rules
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/OptimizerRulesFeature.h
Labels: 2 - Working

#6800 Allow WAL logger to split up transactions
  3rdParty/rocksdb/v5.16.X/db/write_batch.cc
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_logger_follow.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/MMFiles/MMFilesWalAccess.cpp
  arangod/MMFiles/MMFilesWalAccess.h
  arangod/Replication/GlobalInitialSyncer.cpp
  arangod/Replication/Syncer.cpp
  arangod/Replication/Syncer.h
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/TailingSyncer.h
  arangod/Replication/utilities.cpp
  arangod/Replication/utilities.h
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.h
  arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBSettingsManager.cpp
  arangod/RocksDBEngine/RocksDBWalAccess.cpp
  arangod/RocksDBEngine/RocksDBWalAccess.h
  arangod/StorageEngine/WalAccess.h
  lib/Rest/GeneralRequest.cpp
  lib/SimpleHttpClient/SimpleHttpClient.cpp
  tests/js/client/active-failover/basic.js
  tests/js/client/active-failover/readonly.js
  tests/js/server/replication/replication-ongoing-global.js
  tests/rb/HttpReplication/api-replication-global-spec.rb
Labels: 2 - Working

#6862 [3.4] Remove nondeterministic edge index test
  tests/js/server/aql/aql-optimizer-edge-index.js
Labels: 2 - Working

#6863 Remove nondeterministic edge index test
  tests/js/server/aql/aql-optimizer-edge-index.js
Labels: 2 - Working

#6860 tobiasle
  arangod/RestServer/ConsoleThread.cpp
Labels: 2 - Working

#6861 tobiasle
  arangod/RestServer/ConsoleThread.cpp
Labels: 2 - Working

#6829 Bug fix 3.4: libcurl threading changes
  CHANGELOG
  arangod/Cluster/ClusterComm.cpp
  arangod/Cluster/ClusterComm.h
  arangod/Scheduler/Scheduler.cpp
  arangod/Scheduler/Scheduler.h
  arangod/Scheduler/SchedulerFeature.cpp
  lib/SimpleHttpClient/Callbacks.h
  lib/SimpleHttpClient/Communicator.cpp
  lib/SimpleHttpClient/Communicator.h
Labels: 2 - Working

#6777 fixed hyperventing agent 3.4
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/AgentConfiguration.cpp
  arangod/Agency/AgentConfiguration.h
Labels: 2 - Working, Team Clifton

#6776 fixed hyperventing agent
  arangod/Agency/Agent.cpp
  arangod/Agency/AgentConfiguration.cpp
  arangod/Agency/AgentConfiguration.h
Labels: 2 - Working, Team Clifton

#6781 added several query optimizations
  CHANGELOG
  Documentation/Books/AQL/ExecutionAndPerformance/Optimizer.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/Expression.h
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/SubqueryBlock.cpp
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/server/aql/aql-optimizer-rule-fuse-filters.js
  tests/js/server/aql/aql-optimizer-rule-move-calculations-down.js
  tests/js/server/aql/aql-optimizer-rule-simplify-conditions.js
  tests/js/server/aql/aql-queries-optimizer-limit-cluster.js
Labels: 2 - Working

#6868 add wait for estimator
  tests/js/server/aql/aql-optimizer-edge-index.js
Labels: 2 - Working
