Repository arangodb/arangodb, pull requests merged in 2018-11, with the labels that each got.

#7166 issue 496.3: move more coordinator-related logic out of TRI_vocbase_t, rename some arangosearch view configuration parameters, remove some consolidation policies, update iresearch to revision 6fd9760d81b136f769e277ea5b8f53996ed7a1ca
  3rdParty/iresearch/core/formats/formats_10.cpp
  3rdParty/iresearch/core/index/index_writer.cpp
  3rdParty/iresearch/core/utils/ref_counter.hpp
  3rdParty/iresearch/tests/index/consolidation_policy_tests.cpp
  3rdParty/iresearch/tests/search/boolean_filter_tests.cpp
  3rdParty/iresearch/tests/search/phrase_filter_tests.cpp
  Documentation/Books/Manual/Views/ArangoSearch/DetailedOverview.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/IResearchViewDBServer.cpp
  arangod/IResearch/IResearchViewDBServer.h
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewMeta.h
  arangod/MMFiles/MMFilesWalRecoverState.cpp
  arangod/Replication/Syncer.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestViewHandler.cpp
  arangod/V8Server/v8-views.cpp
  arangod/VocBase/LogicalView.cpp
  arangod/VocBase/LogicalView.h
  arangod/VocBase/vocbase.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/IResearch/IResearchViewMeta-test.cpp
  tests/RestHandler/RestViewHandler-test.cpp
  tests/V8Server/v8-views-test.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
  tests/js/server/recovery/view-arangosearch-modify-properties.js
Labels: 2 - Working

#7189 remove OpenFilesTracker
  arangod/MMFiles/MMFilesDatafile.cpp
  arangod/Pregel/TypedBuffer.h
  arangod/RestServer/FileDescriptorsFeature.cpp
  arangosh/Dump/DumpFeature.cpp
  arangosh/Export/ExportFeature.cpp
  arangosh/Import/ImportHelper.cpp
  arangosh/Utils/ManagedDirectory.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/OpenFilesTracker.cpp
  lib/Basics/OpenFilesTracker.h
  lib/Basics/VelocyPackHelper.cpp
  lib/Basics/files.cpp
  lib/Basics/voc-errors.h
  lib/CMakeLists.txt
  lib/Logger/LogAppenderFile.cpp
  lib/Random/RandomGenerator.cpp
  lib/V8/v8-shell.cpp
  lib/V8/v8-utils.cpp
Labels: 2 - Working

#7187 fix premature replicatin context deletion in case the context has no …
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
Labels: 2 - Working

#7188 fix premature replicatin context deletion in case the context has no …
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
Labels: 2 - Working

#7185 don't spawn additional arangosh processes to run the tests
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testsuites/aql.js
  js/client/modules/@arangodb/testsuites/endpoints.js
Labels: 2 - Working

#7168 calculate SHA1 sum for JS files on installation
  Installation/release.sh
Labels: 2 - Working

#7170 Bug fix 3.3/calculate js sha1 sum
  Installation/release.sh
  cmake/ArangoDBInstall.cmake
  cmake/InstallArangoDBJSClient.cmake
  js/JS_SHA1SUM.txt
Labels: 2 - Working

#7201 smaller changes for replication
  arangod/Replication/InitialSyncer.cpp
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RocksDBEngine/RocksDBWalAccess.cpp
  tests/js/server/replication/replication-ongoing.js
Labels: 2 - Working

#7186 Server stream cursor
  arangod/Aql/QueryCursor.cpp
  arangod/Aql/QueryCursor.h
  arangod/MMFiles/MMFilesExportCursor.cpp
  arangod/Replication/InitialSyncer.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/Transaction/V8Context.cpp
  arangod/Utils/Cursor.h
  arangod/Utils/CursorRepository.cpp
  arangod/Utils/CursorRepository.h
  arangod/V8Server/V8DealerFeature.cpp
  arangod/V8Server/v8-users.cpp
  arangod/V8Server/v8-voccursor.cpp
  arangod/VocBase/Methods/Transactions.cpp
  js/server/bootstrap/modules/internal.js
  js/server/modules/@arangodb/arango-statement.js
  lib/V8/v8-globals.cpp
  lib/V8/v8-globals.h
  tests/js/common/shell/shell-query-stream-timecritical-spec.js
  tests/js/common/shell/shell-query-stream.js
  tests/js/common/shell/shell-transactions.js
Labels: 2 - Working

#7197 Bug fix/refactor find emplace
  arangod/Aql/Condition.cpp
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/ExecutionStats.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/IndexBlock.cpp
  arangod/Aql/PlanCache.cpp
  arangod/Aql/QueryCache.cpp
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryRegistry.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeoIndex/Near.cpp
  arangod/Graph/Graph.cpp
  arangod/Graph/GraphCache.cpp
  arangod/Indexes/SkiplistIndexAttributeMatcher.cpp
  arangod/MMFiles/MMFilesCollectorCache.h
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/Pregel/AggregatorHandler.cpp
  arangod/Pregel/Algos/SLPA.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: 2 - Working

#7200 smaller changes for replication
  arangod/Replication/InitialSyncer.cpp
  arangod/RestHandler/RestWalAccessHandler.cpp
  tests/js/server/replication/replication-ongoing.js
Labels: 2 - Working

#7198 fix issues found by codescan
  arangod/Aql/ClusterBlocks.cpp
  arangod/Aql/QueryCache.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewCoordinator.cpp
  lib/Basics/Endian.h
  lib/SimpleHttpClient/Communicator.cpp
Labels: 2 - Working

#7195 fix some issues reported by codescan
  arangod/Aql/ClusterBlocks.cpp
  arangod/Aql/QueryCache.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/RestHandler/RestImportHandler.cpp
  lib/Basics/Endian.h
  lib/SimpleHttpClient/Communicator.cpp
Labels: 2 - Working

#7205 add ge goodbye
  lib/Basics/messages.h
Labels: 2 - Working

#7210 Server stream cursor (#7186)
  arangod/Aql/QueryCursor.cpp
  arangod/Aql/QueryCursor.h
  arangod/MMFiles/MMFilesExportCursor.cpp
  arangod/Replication/InitialSyncer.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/Transaction/V8Context.cpp
  arangod/Utils/Cursor.h
  arangod/Utils/CursorRepository.cpp
  arangod/Utils/CursorRepository.h
  arangod/V8Server/V8DealerFeature.cpp
  arangod/V8Server/v8-users.cpp
  arangod/V8Server/v8-voccursor.cpp
  arangod/VocBase/Methods/Transactions.cpp
  js/server/bootstrap/modules/internal.js
  js/server/modules/@arangodb/arango-statement.js
  lib/V8/v8-globals.cpp
  lib/V8/v8-globals.h
  tests/js/common/shell/shell-query-stream-timecritical-spec.js
  tests/js/common/shell/shell-query-stream.js
  tests/js/common/shell/shell-transactions.js
Labels: 2 - Working

#7207 Fix a crash in DBServerAgencySync
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Transaction/Methods.cpp
Labels: 2 - Working

#7204 Fix a crash in DBServerAgencySync
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Transaction/Methods.cpp
Labels: 2 - Working

#7208 Bugfix 3.4: Revert accidental checkin of change to scheduler constant
  arangod/Scheduler/Scheduler.cpp
Labels: 2 - Working

#7217 issue 496.5: backport 3.4: minor API cleanup and error reportin enhancements, update iresearch to commit d69f7bd184e009da7bf0a478efd34a0c85b74291
  3rdParty/iresearch/core/formats/formats_10.cpp
  3rdParty/iresearch/core/index/index_writer.cpp
  3rdParty/iresearch/core/index/index_writer.hpp
  3rdParty/iresearch/core/index/merge_writer.cpp
  3rdParty/iresearch/core/index/merge_writer.hpp
  3rdParty/iresearch/tests/index/doc_generator.cpp
  3rdParty/iresearch/tests/index/doc_generator.hpp
  3rdParty/iresearch/tests/index/index_profile_tests.cpp
  3rdParty/iresearch/tests/index/index_tests.cpp
  3rdParty/iresearch/tests/index/merge_writer_tests.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchMMFilesLink.h
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/MMFiles/MMFilesWalRecoverState.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
Labels: 2 - Working

#7228 Bug fix/refactor query optimizer
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/Optimizer.cpp
  arangod/Aql/Optimizer.h
  arangod/Aql/Query.cpp
  lib/Basics/RollingVector.h
  tests/IResearch/common.cpp
Labels: 2 - Working

#7220 Use shared_ptr for LogicalCollection
  arangod/ClusterEngine/ClusterTransactionCollection.cpp
  arangod/ClusterEngine/ClusterTransactionCollection.h
  arangod/MMFiles/MMFilesTransactionCollection.cpp
  arangod/MMFiles/MMFilesWalRecoverState.cpp
  arangod/MMFiles/MMFilesWalRecoverState.h
  arangod/Replication/Syncer.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/StorageEngine/TransactionCollection.h
  arangod/Utils/CollectionGuard.h
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  tests/IResearch/StorageEngineMock.cpp
Labels: 2 - Working

#7214 Bugfix: backport defensive Communicator change and revert constant change in Scheduler
  arangod/Scheduler/Scheduler.cpp
  lib/SimpleHttpClient/Communicator.cpp
  lib/SimpleHttpClient/Communicator.h
Labels: 2 - Working

#7232 Bug fix 3.4: verify communication thread has fully stopped in ClusterComm
  arangod/Cluster/ClusterComm.cpp
  arangod/Cluster/ClusterComm.h
Labels: 2 - Working

#7133 [3.4] Upgrade old MMFiles collections for compatibility with ArangoSearch
  .gitignore
  arangod/ClusterEngine/ClusterCollection.h
  arangod/IResearch/IResearchMMFilesLink.cpp
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/MMFiles/MMFilesCollectorThread.cpp
  arangod/MMFiles/MMFilesCompactorThread.cpp
  arangod/MMFiles/MMFilesDatafile.cpp
  arangod/MMFiles/MMFilesDatafile.h
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/MMFiles/MMFilesEngine.h
  arangod/MMFiles/MMFilesLogfileManager.cpp
  arangod/MMFiles/MMFilesWalMarker.h
  arangod/MMFiles/MMFilesWalRecoverState.cpp
  arangod/MMFiles/MMFilesWalRecoverState.h
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/VocBase/LocalDocumentId.h
  arangod/VocBase/Methods/Upgrade.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  arangod/VocBase/Methods/UpgradeTasks.h
  js/client/modules/@arangodb/testing.js
  js/client/modules/@arangodb/testsuites/upgrade-data.js
  lib/Basics/win-utils.cpp
  lib/Basics/win-utils.h
  scripts/cluster-run-common.sh
  scripts/startLocalCluster.sh
  tests/IResearch/StorageEngineMock.cpp
  tests/IResearch/StorageEngineMock.h
  tests/js/server/recovery/view-arangosearch-link-populate-persistentids-mmfiles.js
  tests/js/server/upgrade-data/upgrade-data-basics-msv3.2.1.js
  tests/js/server/upgrade-data/upgrade-data-views-msv3.2.1.js
Labels: 2 - Working

#7222 Restore dbserver view api to its previous behaviour
  arangod/VocBase/LogicalView.cpp
Labels: 2 - Working

#7221 [3.4] Restore dbserver view api to its previous behaviour
  arangod/VocBase/LogicalView.cpp
Labels: 2 - Working, 9 Ready to Merge

#7216 issue 496.5: minor API cleanup and error reportin enhancements, update iresearch to commit d69f7bd184e009da7bf0a478efd34a0c85b74291
  3rdParty/iresearch/core/formats/formats_10.cpp
  3rdParty/iresearch/core/index/index_writer.cpp
  3rdParty/iresearch/core/index/index_writer.hpp
  3rdParty/iresearch/core/index/merge_writer.cpp
  3rdParty/iresearch/core/index/merge_writer.hpp
  3rdParty/iresearch/tests/index/doc_generator.cpp
  3rdParty/iresearch/tests/index/doc_generator.hpp
  3rdParty/iresearch/tests/index/index_profile_tests.cpp
  3rdParty/iresearch/tests/index/index_tests.cpp
  3rdParty/iresearch/tests/index/merge_writer_tests.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchMMFilesLink.h
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/MMFiles/MMFilesWalRecoverState.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
Labels: 2 - Working

#7219 Improve test teardown and reporting
  tests/js/server/resilience/moving-shards-with-arangosearch-view-cluster.js
Labels: 2 - Working, 9 Ready to Merge

#7218 [3.4] Improve test teardown and reporting
  tests/js/server/resilience/moving-shards-with-arangosearch-view-cluster.js
Labels: 2 - Working, 9 Ready to Merge

#7238 Fix "Duplicate testsuite" error
  tests/js/server/resilience/moving-shards-with-arangosearch-view-cluster.js
Labels: 2 - Working, 9 Ready to Merge

#7240 [3.4] Fix query profiling discrepancy in console.
  js/common/modules/@arangodb/aql/explainer.js
Labels: 2 - Working

#7241 Fix query profiling discrepancy in console.
  js/common/modules/@arangodb/aql/explainer.js
Labels: 2 - Working

#7230 Add view profiling tests (3.4)
  js/server/modules/@arangodb/aql-profiler-test-helper.js
  tests/js/server/aql/aql-profiler-noncluster.js
Labels: 3 - Testing, 3 ArangoSearch

#7229 Add view profiling tests
  js/server/modules/@arangodb/aql-profiler-test-helper.js
  tests/js/server/aql/aql-profiler-noncluster.js
Labels: 3 - Testing, 3 ArangoSearch

#7226 try not to throw so many exceptions from Supervision
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/Supervision.cpp
Labels: 2 - Working

#7239 Bugfix 3.4: revert recently added condition variable in ClusterCommThread stop
  arangod/Cluster/ClusterComm.cpp
  arangod/Cluster/ClusterComm.h
Labels: 2 - Working

#7245 Fix update-view-arangosearch-spec tests
  tests/js/client/authentication/user-access-right-task-update-view-arangosearch-spec.js
  tests/js/client/authentication/user-access-right-update-view-arangosearch-spec.js
Labels: 3 - Testing, 3 ArangoSearch

#7246 Fix update-view-arangosearch-spec tests (3.4)
  tests/js/client/authentication/user-access-right-task-update-view-arangosearch-spec.js
  tests/js/client/authentication/user-access-right-update-view-arangosearch-spec.js
Labels: 3 - Testing, 3 ArangoSearch

#7243 Simplify dropDatabaseCoordinator & fix some bugs (#7211)
  arangod/Cluster/ClusterInfo.cpp
  arangod/Sharding/ShardingInfo.cpp
  tests/IResearch/IResearchLinkCoordinator-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
Labels: 2 - Working

#7244 Use shared_ptr for LogicalCollection (#7220)
  arangod/ClusterEngine/ClusterTransactionCollection.cpp
  arangod/ClusterEngine/ClusterTransactionCollection.h
  arangod/MMFiles/MMFilesTransactionCollection.cpp
  arangod/MMFiles/MMFilesWalRecoverState.cpp
  arangod/MMFiles/MMFilesWalRecoverState.h
  arangod/Replication/Syncer.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/StorageEngine/TransactionCollection.h
  arangod/Utils/CollectionGuard.h
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  tests/IResearch/StorageEngineMock.cpp
Labels: 2 - Working

#7237 turn off warnings about `overcommit_memory` settings
  CHANGELOG
  lib/ApplicationFeatures/EnvironmentFeature.cpp
  lib/ApplicationFeatures/EnvironmentFeature.h
Labels: 2 - Working

#7236 turn off warnings about `overcommit_memory` settings
  CHANGELOG
  lib/ApplicationFeatures/EnvironmentFeature.cpp
  lib/ApplicationFeatures/EnvironmentFeature.h
Labels: 2 - Working

#7235 turn off warnings about `overcommit_memory` settings
  CHANGELOG
  lib/ApplicationFeatures/EnvironmentFeature.cpp
  lib/ApplicationFeatures/EnvironmentFeature.h
Labels: 2 - Working

#7234 turn off warnings about `overcommit_memory` settings
  lib/ApplicationFeatures/EnvironmentFeature.cpp
  lib/ApplicationFeatures/EnvironmentFeature.h
Labels: 2 - Working

#7249 bug-fix/internal-issue-#6289
  arangod/CMakeLists.txt
  arangod/IResearch/ExpressionFilter.cpp
  arangod/IResearch/ExpressionFilter.h
  arangod/IResearch/IResearchExpressionContext.cpp
  arangod/IResearch/IResearchExpressionContext.h
  arangod/IResearch/IResearchViewBlock.cpp
  arangod/IResearch/IResearchViewBlock.h
  tests/IResearch/ExpressionContextMock.cpp
  tests/IResearch/ExpressionContextMock.h
  tests/IResearch/IResearchQueryJoin-test.cpp
Labels: 2 - Working

#7250 Bug fix 3.4/internal issue #6289
  arangod/CMakeLists.txt
  arangod/IResearch/ExpressionFilter.cpp
  arangod/IResearch/ExpressionFilter.h
  arangod/IResearch/IResearchExpressionContext.cpp
  arangod/IResearch/IResearchExpressionContext.h
  arangod/IResearch/IResearchViewBlock.cpp
  arangod/IResearch/IResearchViewBlock.h
  tests/IResearch/ExpressionContextMock.h
  tests/IResearch/IResearchQueryJoin-test.cpp
Labels: 2 - Working

#7227 try not to throw so many exceptions from Supervision
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/Supervision.cpp
Labels: 2 - Working

#7248 Upgrade old MMFiles collections for compatibility with ArangoSearch.
  .gitignore
  arangod/ClusterEngine/ClusterCollection.h
  arangod/IResearch/IResearchMMFilesLink.cpp
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/MMFiles/MMFilesCompactorThread.cpp
  arangod/MMFiles/MMFilesDatafile.cpp
  arangod/MMFiles/MMFilesDatafile.h
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/MMFiles/MMFilesEngine.h
  arangod/MMFiles/MMFilesLogfileManager.cpp
  arangod/MMFiles/MMFilesWalMarker.h
  arangod/MMFiles/MMFilesWalRecoverState.cpp
  arangod/MMFiles/MMFilesWalRecoverState.h
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/VocBase/LocalDocumentId.h
  arangod/VocBase/Methods/Upgrade.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  arangod/VocBase/Methods/UpgradeTasks.h
  js/client/modules/@arangodb/testing.js
  js/client/modules/@arangodb/testsuites/upgrade-data.js
  lib/Basics/win-utils.cpp
  lib/Basics/win-utils.h
  scripts/cluster-run-common.sh
  scripts/startLocalCluster.sh
  tests/IResearch/StorageEngineMock.cpp
  tests/IResearch/StorageEngineMock.h
  tests/js/server/recovery/view-arangosearch-link-populate-persistentids-mmfiles.js
  tests/js/server/upgrade-data/upgrade-data-basics-msv3.2.1.js
  tests/js/server/upgrade-data/upgrade-data-views-msv3.2.1.js
Labels: 2 - Working, 9 WIP

#7256 Bugfix 3.4/fix typo in endpoints test
  js/client/modules/@arangodb/testsuites/endpoints.js
Labels: 2 - Working

#7254 fix typo
  js/client/modules/@arangodb/testsuites/endpoints.js
Labels: 2 - Working

#7252 make ArangoSearch error messages more descriptive
  arangod/IResearch/IResearchFeature.cpp
Labels: 2 - Working

#7257 [3.4] make ArangoSearch error messages more descriptive
  arangod/IResearch/IResearchFeature.cpp
Labels: 2 - Working

#7253 Port bug fix 3.4/cluster comm threads start stop (#6939) to devel.
  arangod/Cluster/ClusterFeature.cpp
Labels: 2 - Working

#7259 Feature-3.4/whiteblacklist
  UnitTests/unittest.js
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testing.js
  js/client/modules/@arangodb/testsuites/config.js
  js/client/modules/@arangodb/testsuites/fail.js
  js/client/modules/@arangodb/testsuites/resilience.js
Labels: 2 - Working

#7265 add more information when timeout failing the index creation tests
  tests/js/common/shell/shell-index.js
Labels: 2 - Working

#7267 [3.4] Fix nullptr dereference in SynchronizeShard.
  arangod/Cluster/SynchronizeShard.cpp
Labels: 2 - Working

#7268 Fix nullptr dereference in SynchronizeShard.
  arangod/Cluster/SynchronizeShard.cpp
Labels: 2 - Working

#7280 Feature/arangosearch optimize documents reading
  3rdParty/iresearch/core/formats/formats_10.cpp
  3rdParty/iresearch/core/index/composite_reader_impl.hpp
  3rdParty/iresearch/core/index/directory_reader.cpp
  3rdParty/iresearch/core/index/directory_reader.hpp
  3rdParty/iresearch/core/index/index_reader.cpp
  3rdParty/iresearch/core/index/index_reader.hpp
  3rdParty/iresearch/core/index/merge_writer.cpp
  3rdParty/iresearch/core/index/segment_reader.cpp
  3rdParty/iresearch/core/index/segment_reader.hpp
  3rdParty/iresearch/core/index/transaction_store.cpp
  3rdParty/iresearch/core/index/transaction_store.hpp
  3rdParty/iresearch/core/utils/async_utils.cpp
  3rdParty/iresearch/core/utils/iterator.hpp
  3rdParty/iresearch/tests/formats/formats_10_tests.cpp
  3rdParty/iresearch/tests/formats/formats_test_case_base.hpp
  3rdParty/iresearch/tests/index/consolidation_policy_tests.cpp
  3rdParty/iresearch/tests/index/index_tests.cpp
  3rdParty/iresearch/tests/index/transaction_store_tests.cpp
  3rdParty/iresearch/tests/search/bitset_doc_iterator_test.cpp
  3rdParty/iresearch/tests/search/boolean_filter_tests.cpp
  3rdParty/iresearch/tests/search/filter_test_case_base.hpp
  3rdParty/iresearch/tests/search/granular_range_filter_tests.cpp
  3rdParty/iresearch/tests/search/phrase_filter_tests.cpp
  3rdParty/iresearch/tests/search/prefix_filter_test.cpp
  3rdParty/iresearch/tests/search/range_filter_test.cpp
  3rdParty/iresearch/tests/search/same_position_filter_tests.cpp
  3rdParty/iresearch/tests/search/term_filter_tests.cpp
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewBlock.cpp
  arangod/IResearch/IResearchViewBlock.h
  arangod/IResearch/IResearchViewDBServer.cpp
  arangod/IResearch/IResearchViewDBServer.h
  arangod/IResearch/IResearchViewNode.cpp
Labels: 2 - Working

#7284 Feature/arangosearch optimize documents reading (#7280)
  3rdParty/iresearch/core/formats/formats_10.cpp
  3rdParty/iresearch/core/index/composite_reader_impl.hpp
  3rdParty/iresearch/core/index/directory_reader.cpp
  3rdParty/iresearch/core/index/directory_reader.hpp
  3rdParty/iresearch/core/index/index_reader.cpp
  3rdParty/iresearch/core/index/index_reader.hpp
  3rdParty/iresearch/core/index/merge_writer.cpp
  3rdParty/iresearch/core/index/segment_reader.cpp
  3rdParty/iresearch/core/index/segment_reader.hpp
  3rdParty/iresearch/core/index/transaction_store.cpp
  3rdParty/iresearch/core/index/transaction_store.hpp
  3rdParty/iresearch/core/utils/async_utils.cpp
  3rdParty/iresearch/core/utils/iterator.hpp
  3rdParty/iresearch/tests/formats/formats_10_tests.cpp
  3rdParty/iresearch/tests/formats/formats_test_case_base.hpp
  3rdParty/iresearch/tests/index/consolidation_policy_tests.cpp
  3rdParty/iresearch/tests/index/index_tests.cpp
  3rdParty/iresearch/tests/index/transaction_store_tests.cpp
  3rdParty/iresearch/tests/search/bitset_doc_iterator_test.cpp
  3rdParty/iresearch/tests/search/boolean_filter_tests.cpp
  3rdParty/iresearch/tests/search/filter_test_case_base.hpp
  3rdParty/iresearch/tests/search/granular_range_filter_tests.cpp
  3rdParty/iresearch/tests/search/phrase_filter_tests.cpp
  3rdParty/iresearch/tests/search/prefix_filter_test.cpp
  3rdParty/iresearch/tests/search/range_filter_test.cpp
  3rdParty/iresearch/tests/search/same_position_filter_tests.cpp
  3rdParty/iresearch/tests/search/term_filter_tests.cpp
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewBlock.cpp
  arangod/IResearch/IResearchViewBlock.h
  arangod/IResearch/IResearchViewDBServer.cpp
  arangod/IResearch/IResearchViewDBServer.h
  arangod/IResearch/IResearchViewNode.cpp
Labels: 2 - Working

#7065 Try to fix timeout in drop collection.
  arangod/Cluster/ClusterInfo.cpp
Labels: 2 - Working

#7223 Fix Foxx Queues infinite maxFailures
  CHANGELOG
  js/server/modules/@arangodb/foxx/queues/worker.js
  tests/js/server/shell/shell-foxx-queues.js
Labels: 1 Bug, 2 - Working, 3 Foxx Queues, 9 Ready to Merge

#7224 Fix Foxx Queues infinite maxFailures (3.4)
  CHANGELOG
  js/server/modules/@arangodb/foxx/queues/worker.js
  tests/js/server/shell/shell-foxx-queues.js
Labels: 1 Bug, 2 - Working, 3 Foxx Queues, 9 Ready to Merge

#7295 fix failing non-deterministic query-stream test
  Documentation/Books/Manual/Appendix/JavaScriptModules/Queries.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/V8Server/v8-vocbase.cpp
  tests/js/common/shell/shell-query-stream-timecritical-spec.js
Labels: 2 - Working

#7296 fix failing non-deterministic query-stream test
  Documentation/Books/Manual/Appendix/JavaScriptModules/Queries.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/V8Server/v8-vocbase.cpp
  tests/js/common/shell/shell-query-stream-timecritical-spec.js
Labels: 2 - Working

#7294 added missing change to clusterinfo
  arangod/Cluster/ClusterInfo.cpp
Labels: 2 - Working

#7291 do not create _modules collection for new databases/installations
  CHANGELOG
  arangod/VocBase/Methods/AqlUserFunctions.cpp
  arangod/VocBase/Methods/Upgrade.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  arangod/VocBase/Methods/UpgradeTasks.h
  js/common/bootstrap/modules.js
  js/common/modules/@arangodb/common.js
  js/server/bootstrap/modules/internal.js
  tests/rb/HttpInterface/api-http-spec.rb
Labels: 2 - Working

#7287 Bug fix/aql micro optimizations
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  arangod/Aql/Ast.cpp
  arangod/Aql/AstNode.cpp
  arangod/Aql/BaseExpressionContext.cpp
  arangod/Aql/BaseExpressionContext.h
  arangod/Aql/EnumerateListBlock.cpp
  arangod/Aql/EnumerateListBlock.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  arangod/Aql/WalkerWorker.h
  arangod/IResearch/IResearchFeature.cpp
Labels: 2 - Working

#7286 Bug fix 3.4/aql micro optimizations
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  arangod/Aql/Ast.cpp
  arangod/Aql/AstNode.cpp
  arangod/Aql/BaseExpressionContext.cpp
  arangod/Aql/BaseExpressionContext.h
  arangod/Aql/EnumerateListBlock.cpp
  arangod/Aql/EnumerateListBlock.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  arangod/Aql/WalkerWorker.h
  arangod/IResearch/IResearchFeature.cpp
Labels: 2 - Working

#7302 fix buffer overrun, remove unused variable
  arangod/Cluster/ClusterFeature.cpp
  lib/Basics/win-utils.cpp
Labels: 2 - Working

#7306 Feature/arangosearch pk endianness
  3rdParty/CMakeLists.txt
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchFilterFactory.h
  arangod/IResearch/IResearchPrimaryKeyFilter.cpp
  arangod/IResearch/IResearchPrimaryKeyFilter.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewBlock.cpp
  arangod/IResearch/IResearchViewBlock.h
  tests/IResearch/IResearchDocument-test.cpp
Labels: 2 - Working

#7300 Fix loophole.
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Cluster/ClusterInfo.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  tests/js/client/agency/agency-test.js
Labels: 2 - Working

#7307 Port bug-fix-3.4/timeout-create-coll to devel
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Cluster/ClusterInfo.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  tests/js/client/agency/agency-test.js
Labels: 9 CLA available

#7314 Fix pathForTesting -> startupPath
  js/server/tests/shell/shell-foxx-queues.js
Labels: 1 Bug, 2 - Working, 9 Review Required

#7308 Port timeout in cluster operation fixes from 3.4 to 3.3.
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Cluster/ClusterInfo.cpp
  js/client/tests/agency/agency-test.js
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
Labels: 2 - Working

#7312 [3.4] Feature/arangosearch pk endianness (#7306)
  3rdParty/CMakeLists.txt
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchFilterFactory.h
  arangod/IResearch/IResearchPrimaryKeyFilter.cpp
  arangod/IResearch/IResearchPrimaryKeyFilter.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewBlock.cpp
  arangod/IResearch/IResearchViewBlock.h
  tests/IResearch/IResearchDocument-test.cpp
Labels: 2 - Working

#7328 Bug fix/fix vs15.9 codecvt macro
  3rdParty/iresearch/core/shared.hpp
  3rdParty/iresearch/core/utils/locale_utils.cpp
  3rdParty/iresearch/core/utils/locale_utils.hpp
Labels: 2 - Working, 3 Search, 4 Windows

#7331 Bug fix/fix vs15.9 codecvt macro (3.4)
  3rdParty/iresearch/core/shared.hpp
  3rdParty/iresearch/core/utils/locale_utils.cpp
  3rdParty/iresearch/core/utils/locale_utils.hpp
Labels: 2 - Working, 3 Search, 4 Windows

#7319 print "401 unauthorized" message again
  arangosh/Shell/V8ClientConnection.cpp
Labels: 2 - Working

#7318 print "401 unauthorized" message again
  arangosh/Shell/V8ClientConnection.cpp
Labels: 2 - Working

#7042 UI: rename danger button
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/modalView.js
Labels: 2 - Working, 3 UI, 9 Ready to Merge

#7333 fix queries that refer to COLLECT variables from inside COLLECT
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-optimizer-collect-aggregate.js
  tests/js/server/aql/aql-optimizer-collect-into.js
Labels: 2 - Working

#7332 fix queries that refer to COLLECT variables from inside COLLECT
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-optimizer-collect-aggregate.js
  tests/js/server/aql/aql-optimizer-collect-into.js
Labels: 2 - Working

#7337 Bug fix/refactor query optimizer part2
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Optimizer.cpp
  arangod/Aql/Optimizer.h
  arangod/Aql/OptimizerRules.cpp
  arangod/IResearch/IResearchViewOptimizerRules.cpp
Labels: 2 - Working

#7345 Endpoints via _system
  arangod/GeneralServer/GeneralCommTask.cpp
Labels: 2 - Working

#7344 [3.4] Endpoints via _system
  arangod/GeneralServer/GeneralCommTask.cpp
Labels: 2 - Working

#7342 [3.3] Endpoints via _system
  arangod/GeneralServer/GeneralCommTask.cpp
Labels: 2 - Working

#7338 [3.3] ActiveFailover Follower DB Not Found bug
  arangod/GeneralServer/GeneralCommTask.cpp
Labels: 2 - Working

#7353 [3.2] Endpoints via _system
  arangod/GeneralServer/GeneralCommTask.cpp
Labels: 2 - Working

#7285 Bugfix 3.4: Null pointer defense in Scheduler::post(callback)
  arangod/Scheduler/Scheduler.cpp
  arangod/Scheduler/Scheduler.h
Labels: 2 - Working

#7360 Update messages.h
  lib/Basics/messages.h
Labels: 1 Feature, 3 Arangosh, 9 CLA available

#7260 [3.4] Updates to collection versioning.
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/VocBase/LogicalCollection.h
  js/common/modules/@arangodb/aql/explainer.js
Labels: 2 - Working

#7261 Updates to collection versioning.
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/VocBase/LogicalCollection.h
Labels: 2 - Working

#7361 Documentation/fix symsrv doc
  README_maintainers.md
Labels: 2 - Working

#7350 Another place with a resigned leader.
  tests/js/server/resilience/shard-distribution-spec.js
Labels: 2 - Working

#7351 Another place with a resigned leader.
  js/server/tests/resilience/shard-distribution-spec.js
Labels: 2 - Working

#7352 Another place with a resigned leader.
  js/server/tests/resilience/shard-distribution-spec.js
Labels: 2 - Working

#7349 Another place with a resigned leader.
  tests/js/server/resilience/shard-distribution-spec.js
Labels: 2 - Working

#7298 [3.4] MMFiles replication: get followers under lock
  arangod/Cluster/ResignShardLeadership.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/ClusterEngine/ClusterTransactionCollection.cpp
  arangod/ClusterEngine/ClusterTransactionCollection.h
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/MMFiles/MMFilesTransactionCollection.cpp
  arangod/MMFiles/MMFilesTransactionCollection.h
  arangod/RestServer/arangod.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/RocksDBTransactionCollection.h
  arangod/StorageEngine/EngineSelectorFeature.cpp
  arangod/StorageEngine/EngineSelectorFeature.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/StorageEngine/TransactionCollection.cpp
  arangod/StorageEngine/TransactionCollection.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/VocBase/AccessMode.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/IResearch/StorageEngineMock.cpp
  tests/IResearch/StorageEngineMock.h
Labels: 1 Bug, 2 - Working, 3 Cluster

#7363 Fix typos in README_maintainers.md
  README_maintainers.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7343 MMFiles-replication-get-followers-under-lock (forward-port)
  arangod/Cluster/ResignShardLeadership.cpp
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/ClusterEngine/ClusterTransactionCollection.cpp
  arangod/ClusterEngine/ClusterTransactionCollection.h
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/MMFiles/MMFilesTransactionCollection.cpp
  arangod/MMFiles/MMFilesTransactionCollection.h
  arangod/RestServer/arangod.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/RocksDBTransactionCollection.h
  arangod/StorageEngine/EngineSelectorFeature.cpp
  arangod/StorageEngine/EngineSelectorFeature.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/StorageEngine/TransactionCollection.cpp
  arangod/StorageEngine/TransactionCollection.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/VocBase/AccessMode.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/IResearch/StorageEngineMock.cpp
  tests/IResearch/StorageEngineMock.h
Labels: 1 Bug, 2 - Working, 3 Cluster

#7321 fix a small regex issue, upgrade joi to newer version
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/GruntFile.js
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/joi-browser.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/joi.browser.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/foxxInstallView.js
Labels: 2 - Working, 3 UI, 9 Ready to Merge

#7322 Feature 3.4/joi ui upgrade
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/GruntFile.js
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/joi-browser.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/joi.browser.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/foxxInstallView.js
Labels: 2 - Working, 3 UI, 9 Ready to Merge

#7324 Feature/joi ui upgrade
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/GruntFile.js
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/joi-browser.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/joi.browser.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/foxxInstallView.js
Labels: 2 - Working, 3 UI, 9 Ready to Merge

#7283 when checking for test leftovers catch dead server connections and abort tests cleanly
  js/client/modules/@arangodb/test-utils.js
Labels: 2 - Working

#7373 AuthenticationFeature::isEnabled() is not doing what is expected
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestHandler/RestShutdownHandler.cpp
Labels: 2 - Working

#7372 AuthenticationFeature::isEnabled() is not doing what is expected
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestHandler/RestShutdownHandler.cpp
Labels: 2 - Working

#7190 opts.repeatTimes incorrect value types corrected
  Documentation/Books/Manual/Foxx/Scripts.md
Labels: 1 Bug, 3 Documentation, 3 Foxx Queues, 9 CLA available, 9 Ready to Merge

#7043 UI: rename danger button
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/modalView.js
Labels: 2 - Working, 3 UI, 9 Ready to Merge

#7301 added ":true" to "X-Arango-Allow-Dirty-Read" header
  Documentation/Books/Manual/Administration/ActiveFailover/README.md
  Documentation/Books/Manual/Architecture/DeploymentModes/ActiveFailover/Architecture.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#7277 added ":true" to "X-Arango-Allow-Dirty-Read" header
  Documentation/Books/Manual/Administration/ActiveFailover/README.md
  Documentation/Books/Manual/Architecture/DeploymentModes/ActiveFailover/Architecture.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#7304 Fix Foxx complaining about valid manifest.json $schema value (3.4)
  CHANGELOG
  js/server/modules/@arangodb/foxx/manifest.js
Labels: 1 Bug, 2 - Working, 3 Foxx, 9 Review Required

#7348 Faster index creation
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBCommon.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBMethods.cpp
  arangod/RocksDBEngine/RocksDBMethods.h
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/RocksDBEngine/RocksDBWalAccess.cpp
  tests/js/server/replication/replication-ongoing-32.js
  tests/js/server/replication/replication-ongoing-global-spec.js
  tests/js/server/replication/replication-ongoing-global.js
  tests/js/server/replication/replication-ongoing.js
Labels: 2 - Working

#7369 make method MMFiles-only
  arangod/ClusterEngine/ClusterCollection.h
  arangod/IResearch/IResearchMMFilesLink.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  tests/IResearch/StorageEngineMock.cpp
  tests/IResearch/StorageEngineMock.h
Labels: 2 - Working

#7327 Teach Foxx req.makeAbsolute about unix sockets
  CHANGELOG
  arangod/V8Server/v8-actions.cpp
  js/common/modules/@arangodb/request.js
  js/server/modules/@arangodb/foxx/router/request.js
  js/server/modules/@arangodb/foxx/test-utils.js
  tests/js/server/shell/shell-foxx-request-spec.js
Labels: 1 Feature, 2 - Working, 3 Foxx, 9 Ready to Merge

#7303 Fix Foxx complaining about valid manifest.json $schema value
  CHANGELOG
  js/server/modules/@arangodb/foxx/manifest.js
Labels: 1 Bug, 2 - Working, 3 Foxx, 9 Ready to Merge

#7362 Feature/disable indexing
  arangod/Aql/Query.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBMethods.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/Transaction/Hints.h
  arangod/Transaction/Methods.h
Labels: 2 - Working, 3 RocksDB, performance

#7339 add alternative to ClusterInfo::getCollection() that doesn't throw
  arangod/Aql/Ast.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/v8-cluster.cpp
  arangod/ClusterEngine/ClusterTransactionCollection.cpp
  arangod/ClusterEngine/MMFilesMethods.cpp
  arangod/ClusterEngine/RocksDBMethods.cpp
  arangod/Graph/GraphManager.cpp
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RestHandler/RestIndexHandler.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Transaction/Methods.cpp
  arangod/Utils/CollectionNameResolver.cpp
  arangod/V8Server/v8-collection.cpp
  arangod/V8Server/v8-vocbase.cpp
  arangod/VocBase/Methods/Collections.cpp
Labels: 2 - Working

#7379 Bug fix/aql speedup
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/Expression.cpp
  arangod/Aql/IndexBlock.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/MMFiles/MMFilesHashIndex.cpp
  arangod/MMFiles/MMFilesPrimaryIndex.cpp
  arangod/MMFiles/MMFilesPrimaryIndex.h
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.h
  lib/Basics/StringBuffer.h
Labels: 2 - Working

#7378 Bug fix 3.4/aql speedup
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/Expression.cpp
  arangod/Aql/IndexBlock.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/MMFiles/MMFilesHashIndex.cpp
  arangod/MMFiles/MMFilesPrimaryIndex.cpp
  arangod/MMFiles/MMFilesPrimaryIndex.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.h
  arangod/VocBase/ManagedDocumentResult.cpp
  arangod/VocBase/ManagedDocumentResult.h
  lib/ApplicationFeatures/GreetingsFeature.cpp
  lib/Basics/StringBuffer.h
  lib/Basics/debugging.cpp
Labels: 2 - Working

#7381 dont update lastProcessedTick too early
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/TailingSyncer.h
Labels: 2 - Working

#7380 dont update lastProcessedTick too early
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/TailingSyncer.h
Labels: 2 - Working

#7209 Hide internal link properties
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
Labels: 2 - Working

#7384 do not update lastProcessedTick too early
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/TailingSyncer.h
Labels: 2 - Working

#7390 fix assertion failures for MMFiles operationsQueue state on shutdown
  arangod/MMFiles/MMFilesCollectorThread.cpp
  arangod/MMFiles/MMFilesCollectorThread.h
Labels: 2 - Working

#7389 fix assertion failures for MMFiles operationsQueue state on shutdown
  arangod/MMFiles/MMFilesCollectorThread.cpp
  arangod/MMFiles/MMFilesCollectorThread.h
Labels: 2 - Working

#7386 Hide internal link properties
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
Labels: 2 - Working

#7383 Faster index creation (#7348)
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBCommon.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBMethods.cpp
  arangod/RocksDBEngine/RocksDBMethods.h
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/RocksDBEngine/RocksDBWalAccess.cpp
  tests/js/server/replication/replication-ongoing-32.js
  tests/js/server/replication/replication-ongoing-global-spec.js
  tests/js/server/replication/replication-ongoing-global.js
  tests/js/server/replication/replication-ongoing.js
Labels: 2 - Working

#7394 Changed Link to Design Objectives
  README.md
Labels: 2 - Working

#7385 Bug fix/less exceptions
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/AqlFunctionFeature.h
  arangod/Cluster/ServerState.cpp
  arangod/IResearch/ApplicationServerHelper.cpp
Labels: 2 - Working

#7398 add timeout
  js/client/modules/@arangodb/testsuites/readOnly.js
Labels: 2 - Working

#7397 add timeout
  js/client/modules/@arangodb/testsuites/readOnly.js
Labels: 2 - Working

#6768 Bug fix 3.3/index readiness
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/AgencyCommon.h
  arangod/Agency/Node.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/MMFiles/MMFilesHashIndex.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/VocBase/Methods/Indexes.cpp
  lib/Basics/StringUtils.cpp
Labels: 2 - Working, Team Clifton

#6716 Bug fix 3.4/index readiness
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/AgencyCommon.h
  arangod/Agency/Node.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/ClusterEngine/ClusterIndexFactory.cpp
  lib/Basics/StringUtils.cpp
Labels: 2 - Working, Team Clifton

#6541 Bug fix/index readiness
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/AgencyCommon.h
  arangod/Agency/Node.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterRepairDistributeShardsLike.cpp
  arangod/ClusterEngine/ClusterIndexFactory.cpp
  arangod/MMFiles/MMFilesHashIndex.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  lib/Basics/StringUtils.cpp
  tests/rb/HttpInterface/api-index-geo-spec.rb
Labels: 2 - Working, 9 WIP

#7393 disable RocksDB indexing for some secondary index operations
  arangod/Aql/Query.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBMethods.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/Transaction/Hints.h
  arangod/Transaction/Methods.h
Labels: 2 - Working

#7403 make our tools output their log messages
  js/client/modules/@arangodb/process-utils.js
Labels: 2 - Working

#7404 make our tools output their log messages
  js/client/modules/@arangodb/process-utils.js
Labels: 2 - Working

#7400 yet more micro optimizations
  arangod/Aql/QueryResources.cpp
  arangod/CMakeLists.txt
  arangod/MMFiles/CMakeLists.txt
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/MMFiles/MMFilesEdgeIndex.cpp
  arangod/MMFiles/MMFilesEdgeIndex.h
  arangod/MMFiles/MMFilesHashIndex.cpp
  arangod/MMFiles/MMFilesHashIndex.h
  arangod/MMFiles/MMFilesIndexElement.cpp
  arangod/MMFiles/MMFilesIndexElement.h
  arangod/MMFiles/MMFilesIndexLookupContext.cpp
  arangod/MMFiles/MMFilesIndexLookupContext.h
  arangod/MMFiles/MMFilesPersistentIndex.cpp
  arangod/MMFiles/MMFilesPrimaryIndex.cpp
  arangod/MMFiles/MMFilesPrimaryIndex.h
  arangod/MMFiles/MMFilesSkiplistIndex.cpp
  arangod/MMFiles/MMFilesSkiplistIndex.h
  arangod/Transaction/Context.cpp
  lib/Basics/debugging.cpp
Labels: 2 - Working

#7406 make our tools output their log messages
  js/client/modules/@arangodb/process-utils.js
Labels: 2 - Working

#7370 issue 153: ensure views are dropped in Agency when database is dropped in cluster, minor fixes
  3rdParty/iresearch/core/search/filter.cpp
  3rdParty/iresearch/core/shared.hpp
  3rdParty/iresearch/core/utils/locale_utils.cpp
  3rdParty/iresearch/core/utils/locale_utils.hpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/IResearch/IResearchPrimaryKeyFilter.cpp
  arangod/IResearch/IResearchPrimaryKeyFilter.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewDBServer.cpp
  arangod/VocBase/LogicalView.cpp
  tests/CMakeLists.txt
  tests/Cluster/ClusterInfo-test.cpp
  tests/IResearch/IResearchDocument-test.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
Labels: 2 - Working

#7391 Documentation/actions examples to text
  Documentation/Books/HTTP/Views/README.md
  Documentation/Books/Manual/Appendix/Deprecated/Actions/HtmlExample.md
  Documentation/Books/Manual/Appendix/Deprecated/Actions/JsonExample.md
  Documentation/Books/Manual/Appendix/Deprecated/Actions/Modifying.md
  Documentation/Books/Manual/Appendix/Deprecated/Actions/README.md
  Documentation/Books/Manual/Appendix/Deprecated/README.md
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Examples/HTML_01_routingCreateHtml.generated
  Documentation/Examples/HTML_02_routingReload.generated
  Documentation/Examples/HTML_03_routingCurlHtml.generated
  Documentation/Examples/HTML_04_routingCreateMultiPath.generated
  Documentation/Examples/HTML_05_routingGetMultiPath.generated
  Documentation/Examples/JSON_01_routingCreateJsonHelloWorld.generated
  Documentation/Examples/JSON_02_routingCurlJsonHelloWorld.generated
  Documentation/Examples/JSON_03_routingCleanupJsonHelloWorld.generated
  Documentation/Examples/JSON_05a_routingCreateContentTypeHelloWorld.generated
  Documentation/Examples/JSON_05b_routingCurlContentTypeHelloWorld.generated
  Documentation/Examples/JSON_05c_routingCleanupContentTypeHelloWorld.generated
  Documentation/Examples/JSON_06_routingCreateHelloEcho.generated
  Documentation/Examples/JSON_07_fetchroutingCreateHelloEcho.generated
  Documentation/Examples/JSON_08_routingCleanupHelloEcho.generated
  Documentation/Examples/JSON_09_routingCreateEchoController.generated
  Documentation/Examples/JSON_10_fetchroutingCreateEchoController.generated
  Documentation/Examples/JSON_11_routingCleanupEchoController.generated
  Documentation/Examples/JSON_12a_routingCreateEchoFunction.generated
  Documentation/Examples/JSON_12b_fetchroutingEchoFunction.generated
  Documentation/Examples/JSON_13_routingCreateEchoAction.generated
  Documentation/Examples/JSON_14_fetchroutingRequestHelloEcho.generated
  Documentation/Examples/JSON_15_routingCreateEchoRequestOptions.generated
  Documentation/Examples/JSON_16_fetchroutingEchoRequestOptions.generated
  Documentation/Examples/MOD_01a_routingCreateOwnTest.generated
  Documentation/Examples/MOD_01b_routingEnableOwnTest.generated
  Documentation/Examples/MOD_01c_routingCurlOwnTest.generated
  Documentation/Examples/MOD_05_routingModifyReload.generated
  Documentation/Examples/MOD_06a_routingRedirect.generated
  Documentation/Examples/MOD_06b_routingCurlRedirect.generated
  Documentation/Examples/MOD_07a_routingMulti.generated
  Documentation/Examples/MOD_07b_routingCurlMulti.generated
  Documentation/Examples/MOD_07c_routingMulti.generated
  Documentation/Examples/MOD_07d_routingCurlMulti.generated
  Documentation/Examples/MOD_08a_routingCreateOwnConsoleLog.generated
  Documentation/Examples/MOD_08b_routingCreateRouteToOwnConsoleLog.generated
  Documentation/Examples/MOD_08c_routingCreateRouteToOwnConsoleLog.generated
  Documentation/Examples/MOD_08d_routingCurlToOwnConsoleLog.generated
  Documentation/Examples/MOD_09_routingReload.generated
  Documentation/Examples/MOD_09a_routingSpecifyMethods.generated
  Documentation/Examples/MOD_09b_routingCurlSpecifyMethods.generated
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7402 remove some unused StringUtils functions
  lib/Basics/StringUtils.cpp
  lib/Basics/StringUtils.h
  lib/Ssl/SslInterface.cpp
  lib/Ssl/SslInterface.h
  tests/Basics/StringUtilsTest.cpp
Labels: 2 - Working

#7396 Bugfix/fix recovery testsuite
  js/client/modules/@arangodb/process-utils.js
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testing.js
  js/client/modules/@arangodb/testsuites/recovery.js
Labels: 2 - Working

#7354 use of job api for patching and removing views
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoViews.js
  js/apps/system/_admin/aardvark/APP/frontend/js/models/arangoViewModel.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/viewView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
Labels: 2 - Working, 3 UI, 9 Ready to Merge

#7420 use of job api for patching and removing views #7354
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoViews.js
  js/apps/system/_admin/aardvark/APP/frontend/js/models/arangoViewModel.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/viewView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
Labels: 2 - Working, 3 UI, 9 Ready to Merge

#7423 refresh properties after switching back to edit mode
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
Labels: 2 - Working, 9 Ready to Merge

#7422 refresh properties after switching back to edit mode
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
Labels: 2 - Working

#7416 add some more intermediate commit tests
  tests/js/server/shell/shell-collection-rocksdb-failures-noncluster.js
Labels: 2 - Working

#7388 Bug fix/remove shutdown assertion
  arangod/Aql/QueryString.h
  arangod/Scheduler/JobGuard.h
  arangod/Scheduler/Scheduler.cpp
  arangod/Scheduler/Scheduler.h
  lib/Basics/LocalTaskQueue.cpp
Labels: 2 - Working

#7387 Bug fix 3.4/remove shutdown assertion
  arangod/Aql/QueryString.h
  arangod/Scheduler/JobGuard.h
  arangod/Scheduler/Scheduler.cpp
  arangod/Scheduler/Scheduler.h
  lib/Basics/LocalTaskQueue.cpp
Labels: 2 - Working
