Repository arangodb/arangodb, pull requests merged in 2018-12, with the labels that each got.

#7579 Do nothing in phaseTwo if leader has not been touched.
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Transaction/Methods.cpp
Labels: 2 - Working

#7578 treat all iresearch scores as float_t for 3.4 (#7573)
  arangod/Aql/ClusterBlocks.cpp
  arangod/Aql/SortBlock.cpp
  arangod/Aql/SortRegister.cpp
  arangod/Aql/SortRegister.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchViewBlock.cpp
Labels: 2 - Working

#7581 re-enable arangosearch scoring tests in cluster
  tests/js/common/aql/aql-view-arangosearch-cluster.js
  tests/js/common/aql/aql-view-arangosearch-nondeterministic-cluster.js
Labels: 2 - Working

#7576 Doc - 3.3 known issues
  Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
  Documentation/Books/Manual/ReleaseNotes/README.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#7585 [devel] Bug fix/bad leader report current
  arangod/Agency/CleanOutServer.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/Maintenance.cpp
  arangod/Transaction/Methods.cpp
Labels: 2 - Working

#7583 Doc - 3.3 Known Issues
  Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
  Documentation/Books/Manual/ReleaseNotes/README.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#7575 Doc - 3.3 known issues page
  Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
  Documentation/Books/Manual/ReleaseNotes/README.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#7592 Doc - Known Issues 33 - forward port simran's feedback
  Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
Labels: 2 - Working, 3 Documentation

#7541 Wait for 5 dbservers before starting resilience tests.
  tests/js/server/resilience/moving-shards-cluster.js
  tests/js/server/resilience/moving-shards-with-arangosearch-view-cluster.js
  tests/js/server/resilience/resilience-synchronous-repl-cluster.js
  tests/js/server/resilience/resilience-synchronous-repl-failureAt-cluster.js
  tests/js/server/resilience/resilience-synchronous-repl-with-arangosearch-view-cluster.js
Labels: 2 - Working

#7542 Wait for 5 dbservers before starting resilience tests.
  tests/js/server/resilience/moving-shards-cluster.js
  tests/js/server/resilience/moving-shards-with-arangosearch-view-cluster.js
  tests/js/server/resilience/resilience-synchronous-repl-cluster.js
  tests/js/server/resilience/resilience-synchronous-repl-failureAt-cluster.js
  tests/js/server/resilience/resilience-synchronous-repl-with-arangosearch-view-cluster.js
Labels: 2 - Working

#7600 Documentation 3.4/update known issues (arangosearch)
  Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
Labels: 2 - Working

#7597 cleanup
  lib/Basics/Exceptions.cpp
  lib/Basics/Exceptions.h
  lib/Maskings/Maskings.cpp
  lib/Maskings/Maskings.h
Labels: 2 - Working

#7598 Bug fix/dont fail when restoring cluster dump into single server
  arangod/Indexes/IndexFactory.cpp
Labels: 2 - Working

#7596 dont fail when restoring a cluster dump into a single server
  arangod/Indexes/IndexFactory.cpp
Labels: 2 - Working

#7599 Documentation/34 known issues
  Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
Labels: 2 - Working, 3 Documentation

#7595 dont fail when restoring a cluster dump into a single server
  arangod/Indexes/IndexFactory.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: 2 - Working

#7545 Wait for 5 dbservers in resilience tests.
  js/server/tests/resilience/moving-shards-cluster.js
  js/server/tests/resilience/resilience-synchronous-repl-cluster.js
  js/server/tests/resilience/resilience-synchronous-repl-failureAt-cluster.js
Labels: 2 - Working

#7594 Call license key check.
  CHANGELOG
  arangod/RestServer/arangod.cpp
Labels: 2 - Working

#7619 dont keep JS module directory
  arangod/V8Server/V8DealerFeature.cpp
Labels: 2 - Working

#7609 Doc - Known Issues 3.4
  Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
Labels: 2 - Working, 3 Documentation

#7608 dont use version number in JavaScript install path
  CMakeLists.txt
Labels: 2 - Working

#7606 dont use version number in JavaScript install path
  CMakeLists.txt
Labels: 2 - Working

#7621 Docs: Remove _getConnectingEdges() as it's not implemented
  Documentation/Books/Manual/Graphs/GeneralGraphs/Management.md
  Documentation/Examples/generalGraphModuleConnectingEdges1.generated
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7622 Docs: Remove _getConnectingEdges() as it's not implemented
  Documentation/Books/Manual/Graphs/GeneralGraphs/Management.md
  Documentation/Examples/generalGraphModuleConnectingEdges1.generated
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#7623 Docs: Remove _getConnectingEdges() as it's not implemented
  Documentation/Books/Manual/Graphs/GeneralGraphs/Management.md
  Documentation/Examples/generalGraphModuleConnectingEdges1.generated
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#7624 Docs: Remove _getConnectingEdges() as it's not implemented
  Documentation/Books/Manual/Graphs/GeneralGraphs/Management.md
  Documentation/Examples/generalGraphModuleConnectingEdges1.generated
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#7612 Disable warning about persistent IDs during upgrade procedure.
  arangod/MMFiles/MMFilesCollection.cpp
Labels: 2 - Working

#7611 [3.4] Disable warning about persistent IDs during upgrade procedure.
  arangod/MMFiles/MMFilesCollection.cpp
Labels: 2 - Working

#7590 Feature 3.4/kill em all
  UnitTests/unittest.js
  js/common/bootstrap/modules/internal.js
  lib/Basics/process-utils.cpp
  lib/Basics/process-utils.h
  lib/V8/v8-utils.cpp
Labels: 2 - Working

#7591 Feature 3.3/kill em all
  UnitTests/unittest.js
  js/common/bootstrap/modules/internal.js
  lib/Basics/process-utils.cpp
  lib/Basics/process-utils.h
  lib/V8/v8-utils.cpp
Labels: 2 - Working

#7620 fix symbol path, add more cdb hints
  README_maintainers.md
Labels: 2 - Working

#7626 spotlight ui router was missing
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
Labels: 2 - Working

#7627 spotlight ui router was missing
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
Labels: 2 - Working

#7629 License key documentation in starter.
  Documentation/Books/Manual/Deployment/ActiveFailover/UsingTheStarter.md
  Documentation/Books/Manual/Deployment/Cluster/UsingTheStarter.md
  Documentation/Books/Manual/Deployment/SingleInstance/UsingTheStarter.md
Labels: 2 - Working

#7633 added MultiPolygon GeoJSON constructor function
  Documentation/Books/AQL/Functions/Geo.md
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
Labels: 2 - Working

#7614 try again in case of a conflict when updating users
  arangod/Auth/UserManager.cpp
  arangod/VocBase/Methods/Collections.cpp
Labels: 2 - Working

#7634 added MultiPolygon GeoJSON constructor function
  Documentation/Books/AQL/Functions/Geo.md
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
Labels: 2 - Working

#7641 Documentation 3.4/add known issue for parallel collection creation
  Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
  Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
Labels: 2 - Working, 3 Documentation

#7640 add known issue
  Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
Labels: 2 - Working, 3 Documentation

#7642 Documentation/add known issue for parallel collection creation
  Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
  Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
Labels: 2 - Working, 3 Documentation

#7652 parse version fix
  arangod/VocBase/Methods/Version.cpp
Labels: 2 - Working

#7653 parse version fix
  arangod/VocBase/Methods/Version.cpp
Labels: 2 - Working

#7645 add changes to documentation
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
Labels: 2 - Working, 3 Documentation

#7646 add changes to documentation
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
Labels: 2 - Working, 3 Documentation

#7651 Docs: Mention GEO_MULTIPOLYGON() in 3.4 release notes
  Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7654 Documentation 3.4/geo multipolygon
  Documentation/Books/AQL/Functions/Geo.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#7516 Doc - Create MonetaryDataWithoutPrecisionLoss.md (#7149)
  Documentation/Books/Cookbook/SUMMARY.md
  Documentation/Books/Cookbook/UseCases/MonetaryDataWithoutPrecisionLoss.md
  Documentation/Books/Cookbook/UseCases/README.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7647 Bug fix/aql allow floating point values without leading zero
  CHANGELOG
  arangod/Aql/tokens.cpp
  arangod/Aql/tokens.ll
  tests/js/server/aql/aql-parse.js
Labels: 2 - Working

#7656 Fix super user JWT token behaviour with non-ex. db.
  arangod/GeneralServer/GeneralCommTask.cpp
  tests/js/client/authentication/auth.js
Labels: 2 - Working

#7655 Doc: change replica amount
  Documentation/Books/Manual/Administration/Cluster/README.md
Labels: 2 - Working, 3 Documentation

#7658 add more tests and improve queries a bit for single remote AQL operat…
  arangod/Aql/ClusterBlocks.cpp
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesCluster.cpp
  tests/js/server/aql/aql-optimizer-optimize-cluster-single-document-operations.js
Labels: 2 - Working

#7660 nicer log messages with stringified status value
  arangod/Cluster/SynchronizeShard.cpp
Labels: 2 - Working

#7659 fix test failures
  tests/js/common/aql/aql-view-arangosearch-nondeterministic-cluster.js
Labels: 2 - Working

#7616 Doc: sync external repositories
  Documentation/Books/Drivers/JS/Reference/Collection/BulkImport.md
  Documentation/Books/Drivers/JS/Reference/Collection/DocumentCollection.md
  Documentation/Books/Drivers/JS/Reference/Collection/EdgeCollection.md
  Documentation/Books/Drivers/JS/Reference/Database/FoxxServices.md
  Documentation/Books/Drivers/JS/Reference/Database/Queries.md
  Documentation/Books/Drivers/JS/Reference/Database/README.md
  Documentation/Books/Drivers/JS/Reference/Graph/EdgeCollection.md
  Documentation/Books/Drivers/JS/Reference/Graph/VertexCollection.md
  Documentation/Books/Drivers/Java/GettingStarted/README.md
  Documentation/Books/Drivers/Java/Reference/Collection/BulkImport.md
  Documentation/Books/Drivers/Java/Reference/Collection/CollectionManipulation.md
  Documentation/Books/Drivers/Java/Reference/Collection/DocumentManipulation.md
  Documentation/Books/Drivers/Java/Reference/Collection/Indexes.md
  Documentation/Books/Drivers/Java/Reference/Collection/README.md
  Documentation/Books/Drivers/Java/Reference/Cursor.md
  Documentation/Books/Drivers/Java/Reference/Database/AqlUserFunctions.md
  Documentation/Books/Drivers/Java/Reference/Database/CollectionAccess.md
  Documentation/Books/Drivers/Java/Reference/Database/DatabaseManipulation.md
  Documentation/Books/Drivers/Java/Reference/Database/GraphAccess.md
  Documentation/Books/Drivers/Java/Reference/Database/HttpRoutes.md
  Documentation/Books/Drivers/Java/Reference/Database/Queries.md
  Documentation/Books/Drivers/Java/Reference/Database/README.md
  Documentation/Books/Drivers/Java/Reference/Database/Transactions.md
  Documentation/Books/Drivers/Java/Reference/Database/ViewAccess.md
  Documentation/Books/Drivers/Java/Reference/Graph/EdgeCollection.md
  Documentation/Books/Drivers/Java/Reference/Graph/Edges.md
  Documentation/Books/Drivers/Java/Reference/Graph/README.md
  Documentation/Books/Drivers/Java/Reference/Graph/VertexCollection.md
  Documentation/Books/Drivers/Java/Reference/Graph/Vertices.md
  Documentation/Books/Drivers/Java/Reference/Route.md
  Documentation/Books/Drivers/Java/Reference/Serialization.md
  Documentation/Books/Drivers/Java/Reference/Setup.md
  Documentation/Books/Drivers/Java/Reference/View/ArangoSearch.md
  Documentation/Books/Drivers/Java/Reference/View/README.md
  Documentation/Books/Drivers/Java/Reference/View/ViewManipulation.md
  Documentation/Books/Drivers/SparkConnector/GettingStarted/README.md
  Documentation/Books/Drivers/SparkConnector/Reference/Java.md
  Documentation/Books/Manual/Deployment/ActiveFailover/UsingTheStarter.md
  Documentation/Books/Manual/Deployment/Cluster/UsingTheStarter.md
  Documentation/Books/Manual/Deployment/Kubernetes/DeploymentResource.md
  Documentation/Books/Manual/Deployment/Kubernetes/ServicesAndLoadBalancer.md
  Documentation/Books/Manual/Deployment/Kubernetes/Usage.md
  Documentation/Books/Manual/Deployment/SingleInstance/UsingTheStarter.md
  Documentation/Books/Manual/Programs/FoxxCLI/README.md
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Tutorials/Kubernetes/AKS.md
  Documentation/Books/Manual/Tutorials/Kubernetes/EKS.md
  Documentation/Books/Manual/Tutorials/Kubernetes/GKE.md
  Documentation/Books/Manual/Tutorials/Kubernetes/README.md
  Documentation/Books/Manual/Tutorials/Kubernetes/aks-create-auth.png
  Documentation/Books/Manual/Tutorials/Kubernetes/aks-create-basics.png
  Documentation/Books/Manual/Tutorials/Kubernetes/aks-create-valid.png
  Documentation/Books/Manual/Tutorials/Kubernetes/eks-cluster-active.png
  Documentation/Books/Manual/Tutorials/Kubernetes/eks-clusters.png
  Documentation/Books/Manual/Tutorials/Kubernetes/eks-create-review.png
  Documentation/Books/Manual/Tutorials/Kubernetes/eks-create-template.png
  Documentation/Books/Manual/Tutorials/Kubernetes/eks-stack-ready.png
  Documentation/Books/Manual/Tutorials/Kubernetes/eks-stack.png
  Documentation/Books/Manual/Tutorials/Starter/README.md
Labels: 2 - Working, 3 Documentation

#7662 Docs: Add missing example file for GEO_MULTIPOLYGON()
  Documentation/Examples/aqlGeoMultiPolygon_1.generated
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7664 Use program option JSON files generated with Enterprise Edition
  Documentation/Examples/arangod.json
  Documentation/Examples/arangodump.json
  Documentation/Examples/arangoexport.json
  Documentation/Examples/arangorestore.json
  Documentation/Examples/arangosh.json
Labels: 1 Bug, 2 - Working, 3 Documentation, 9 Ready to Merge

#7663 3.3 to 3.4 starter upgrades - additional info
  Documentation/Books/Manual/Upgrading/GeneralInfo/README.md
Labels: 2 - Working, 3 Documentation

#7667 3.3 to 3.4 starter update - info + added "highly"
  Documentation/Books/Manual/Upgrading/GeneralInfo/README.md
Labels: 2 - Working, 3 Documentation

#7657 Documentation/deprecate simple all keys
  Documentation/Books/HTTP/Indexes/Fulltext.md
  Documentation/Books/HTTP/Indexes/Hash.md
  Documentation/Books/HTTP/Indexes/Persistent.md
  Documentation/Books/HTTP/Indexes/Skiplist.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures26.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges26.md
  Documentation/DocuBlocks/Rest/Documents/put_read_all_documents.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_all.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_by_example.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_fulltext.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_near.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_range.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_within.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_within_rectangle.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7665 Documentation 3.4/deprecate simple all keys
  Documentation/Books/HTTP/Indexes/Fulltext.md
  Documentation/Books/HTTP/Indexes/Hash.md
  Documentation/Books/HTTP/Indexes/Persistent.md
  Documentation/Books/HTTP/Indexes/Skiplist.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures26.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges26.md
  Documentation/DocuBlocks/Rest/Documents/put_read_all_documents.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_all.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_by_example.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_fulltext.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_near.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_range.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_within.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_within_rectangle.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7673 Docs: new page for Uninstallation (Split PR #5830)
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Uninstallation/README.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#7668 Doc - Community to Enterprise Upgrade
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Upgrading/CommunityToEnterprise.md
  Documentation/Books/Manual/Upgrading/README.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#7675 Doc - cite the tar.gz in what's new
  Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#7674 Doc - Scripts to Optimize OS
  Documentation/Books/Manual/Installation/LinuxOSConfiguration.md
  Documentation/Books/Manual/Installation/LinuxOSTuningScripts.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#7669 Docs: Installation refactor Windows (Split PR #5830)
  Documentation/Books/Cookbook/Administration/README.md
  Documentation/Books/Cookbook/Administration/XCopyInstallWindows.md
  Documentation/Books/Cookbook/SUMMARY.md
  Documentation/Books/Manual/Installation/Windows.md
Labels: 2 - Working, 3 Documentation, 9 Review Required, 9 Waiting for Jenkins

#7672 Docs: Installation refactor MacOSX (Split PR #5830)
  Documentation/Books/Manual/Installation/MacOSX.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#7666 Docs: Rewrite Configuration page, restore old file structure
  Documentation/Books/Manual/Administration/Configuration.md
  Documentation/Books/Manual/Administration/Configuration/README.md
  Documentation/Books/Manual/Programs/Arangod/Log.md
  Documentation/Books/Manual/Programs/Arangod/Options.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7628 Doc - restore conf link
  Documentation/Books/Manual/Administration/Configuration.md
  Documentation/Books/Manual/Administration/Configuration/README.md
  Documentation/Books/Manual/Programs/Arangod/Log.md
  Documentation/Books/Manual/Programs/Arangod/Options.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7582 Doc - Production Checklist
  Documentation/Books/Manual/Deployment/ProductionChecklist.md
  Documentation/Books/Manual/Deployment/README.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation, 9 Review Required, 9 Waiting for Jenkins

#7681 Doc - Installation improvements
  Documentation/Books/Manual/Installation/MacOSX.md
  Documentation/Books/Manual/Installation/README.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#6071 Bug fix 3.3/nsis improvements
  CHANGELOG
  Installation/Windows/Plugins/AddToPath.nsh
  Installation/Windows/Plugins/exitcodes.nsh
  Installation/Windows/Plugins/xcopy.nsh
  Installation/Windows/Templates/NSIS.template.in
  Installation/Windows/client/Templates/NSIS.template.in
  arangod/RestServer/InitDatabaseFeature.cpp
  cmake/packages/nsis.cmake
  lib/ApplicationFeatures/WindowsServiceFeature.cpp
  lib/ApplicationFeatures/WindowsServiceFeature.h
  lib/Basics/exitcodes.cpp
  lib/Basics/exitcodes.dat
  lib/Basics/exitcodes.h
  lib/Basics/win-utils.cpp
  lib/Basics/win-utils.h
  utils/generateExitCodesFiles.py
Labels: 2 - Working

#7686 Docs: Placeholder pages for 3.5 Release Notes
  Documentation/Books/Manual/ReleaseNotes/35.md
  Documentation/Books/Manual/ReleaseNotes/KnownIssues35.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges35.md
Labels: 2 - Working, 3 Documentation

#7586 fixed query result not being displayed if active view was running or …
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 2 - Working, 9 Ready to Merge

#7588 fixed query result not being displayed if active view was running or …
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 2 - Working, 9 Ready to Merge

#7677 try checking whether _admin/shutdown is received, print sockstats of arangod processes
  arangod/RestHandler/RestShutdownHandler.cpp
  js/client/modules/@arangodb/process-utils.js
  js/client/modules/@arangodb/testing.js
  lib/V8/v8-utils.cpp
Labels: 2 - Working

#7683 Feature/internal 3306
  CHANGELOG
  arangod/Actions/ActionFeature.cpp
  arangod/Agency/AgencyFeature.cpp
  arangod/Cluster/ClusterComm.cpp
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/ReplicationTimeoutFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/MMFiles/MMFilesLogfileManager.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/RestServer/BootstrapFeature.cpp
  arangod/RestServer/CheckVersionFeature.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/EndpointFeature.cpp
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/FortuneFeature.cpp
  arangod/RestServer/FrontendFeature.cpp
  arangod/RestServer/InitDatabaseFeature.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/ServerFeature.cpp
  arangod/RestServer/UpgradeFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/Scheduler/SchedulerFeature.cpp
  arangod/Statistics/StatisticsFeature.cpp
  arangod/V8Server/V8DealerFeature.cpp
  arangosh/Shell/ClientFeature.cpp
  arangosh/Shell/ConsoleFeature.cpp
  arangosh/Shell/V8ShellFeature.cpp
  lib/ApplicationFeatures/ApplicationServer.cpp
  lib/ApplicationFeatures/ConfigFeature.cpp
  lib/ApplicationFeatures/DaemonFeature.cpp
  lib/ApplicationFeatures/LanguageFeature.cpp
  lib/ApplicationFeatures/MaxMapCountFeature.cpp
  lib/ApplicationFeatures/PrivilegeFeature.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.cpp
  lib/ApplicationFeatures/SupervisorFeature.cpp
  lib/ApplicationFeatures/V8PlatformFeature.cpp
  lib/ApplicationFeatures/VersionFeature.cpp
  lib/ApplicationFeatures/WindowsServiceFeature.cpp
  lib/Logger/LoggerFeature.cpp
  lib/ProgramOptions/ArgumentParser.h
  lib/ProgramOptions/Option.cpp
  lib/ProgramOptions/Option.h
  lib/ProgramOptions/ProgramOptions.cpp
  lib/ProgramOptions/ProgramOptions.h
  lib/ProgramOptions/Section.cpp
  lib/Random/RandomFeature.cpp
  lib/Ssl/SslServerFeature.cpp
Labels: 2 - Working

#7615 try again in case of a conflict when updating users
  arangod/Auth/UserManager.cpp
  arangod/VocBase/Methods/Collections.cpp
Labels: 2 - Working

#7688 Feature/internal 3306 (#7683)
  CHANGELOG
  arangod/Actions/ActionFeature.cpp
  arangod/Agency/AgencyFeature.cpp
  arangod/Cluster/ClusterComm.cpp
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/ReplicationTimeoutFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/MMFiles/MMFilesLogfileManager.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/RestServer/BootstrapFeature.cpp
  arangod/RestServer/CheckVersionFeature.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/EndpointFeature.cpp
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/FortuneFeature.cpp
  arangod/RestServer/FrontendFeature.cpp
  arangod/RestServer/InitDatabaseFeature.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/ServerFeature.cpp
  arangod/RestServer/UpgradeFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/Scheduler/SchedulerFeature.cpp
  arangod/Statistics/StatisticsFeature.cpp
  arangod/V8Server/V8DealerFeature.cpp
  arangosh/Shell/ClientFeature.cpp
  arangosh/Shell/ConsoleFeature.cpp
  arangosh/Shell/V8ShellFeature.cpp
  lib/ApplicationFeatures/ApplicationServer.cpp
  lib/ApplicationFeatures/ConfigFeature.cpp
  lib/ApplicationFeatures/DaemonFeature.cpp
  lib/ApplicationFeatures/LanguageFeature.cpp
  lib/ApplicationFeatures/MaxMapCountFeature.cpp
  lib/ApplicationFeatures/PrivilegeFeature.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.cpp
  lib/ApplicationFeatures/SupervisorFeature.cpp
  lib/ApplicationFeatures/V8PlatformFeature.cpp
  lib/ApplicationFeatures/VersionFeature.cpp
  lib/ApplicationFeatures/WindowsServiceFeature.cpp
  lib/Logger/LoggerFeature.cpp
  lib/ProgramOptions/ArgumentParser.h
  lib/ProgramOptions/Option.cpp
  lib/ProgramOptions/Option.h
  lib/ProgramOptions/ProgramOptions.cpp
  lib/ProgramOptions/ProgramOptions.h
  lib/ProgramOptions/Section.cpp
  lib/Random/RandomFeature.cpp
  lib/Ssl/SslServerFeature.cpp
Labels: 2 - Working

#7638 speed up remove ops for RocksDB engine
  arangod/Aql/ClusterBlocks.cpp
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ClusterNodes.h
  arangod/Aql/ModificationNodes.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesCluster.cpp
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  tests/js/server/aql/aql-multi-modify.js
  tests/js/server/aql/aql-optimizer-optimize-cluster-single-document-operations.js
  tests/js/server/aql/aql-optimizer-rule-distribute-in-cluster.js
  tests/js/server/aql/aql-optimizer-rule-patch-update-statements-rocksdb.js
  tests/js/server/aql/aql-optimizer-rule-patch-update-statements.js
Labels: 2 - Working

#7689 minor fixes
  arangod/Cache/CacheManagerFeature.cpp
  arangod/VocBase/LogicalCollection.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.cpp
Labels: 2 - Working

#7691 minor fixes
  arangod/Cache/CacheManagerFeature.cpp
  arangod/VocBase/LogicalCollection.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.cpp
Labels: 2 - Working

#7704 Call license key check. (#7594)
  CHANGELOG
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/RestServer/arangod.cpp
  tests/js/client/authentication/auth.js
Labels: 2 - Working

#7699 improve error message for dump & restore
  arangosh/Dump/DumpFeature.cpp
Labels: 2 - Working

#7698 improve error messages
  arangosh/Dump/DumpFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
Labels: 2 - Working

#7697 improve error messages
  arangosh/Dump/DumpFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
Labels: 2 - Working

#7604 Fix TypeError for invalid manifests (3.3)
  CHANGELOG
  js/server/modules/@arangodb/foxx/manifest.js
Labels: 1 Bug, 2 - Working, 3 Foxx, 9 Review Required

#7605 Fix TypeError for invalid manifests (3.2)
  CHANGELOG
  js/server/modules/@arangodb/foxx/manifest.js
Labels: 1 Bug, 2 - Working, 3 Foxx, 9 Review Required

#7695 issue 511.1: move iresearch data-store from IResearchView to IResearchLink
  3rdParty/CMakeLists.txt
  arangod/IResearch/Containers.h
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchLinkCoordinator.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchLinkHelper.h
  arangod/IResearch/IResearchMMFilesLink.cpp
  arangod/IResearch/IResearchMMFilesLink.h
  arangod/IResearch/IResearchRocksDBLink.cpp
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/IResearchViewDBServer.cpp
  arangod/IResearch/IResearchViewDBServer.h
  arangod/IResearch/VelocyPackHelper.cpp
  arangod/IResearch/VelocyPackHelper.h
  arangod/Indexes/Index.h
  arangod/MMFiles/MMFilesPersistentIndex.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  tests/Cluster/ClusterInfo-test.cpp
  tests/IResearch/ExpressionFilter-test.cpp
  tests/IResearch/IResearchDocument-test.cpp
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchLinkCoordinator-test.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/IResearch/IResearchQueryOr-test.cpp
  tests/IResearch/IResearchQueryStartsWith-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/IResearch/IResearchViewMeta-test.cpp
  tests/IResearch/StorageEngineMock.cpp
  tests/IResearch/StorageEngineMock.h
Labels: 2 - Working

#7534 [3.3] Reload Foxx routes during startup
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
  js/server/modules/@arangodb/foxx/manager.js
Labels: 1 Bug, 2 - Working

#7533 Reload Foxx routes during startup
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
  arangod/RestServer/BootstrapFeature.cpp
  js/server/modules/@arangodb/foxx/manager.js
Labels: 1 Bug, 2 - Working

#7539 Fix minor test lapses
  js/client/modules/@arangodb/testsuites/catch.js
  js/client/modules/@arangodb/testsuites/recovery.js
Labels: 2 - Working, 9 Ready to Merge

#7472 [3.3] Fix minor test lapses
  js/client/modules/@arangodb/testsuites/catch.js
  js/client/modules/@arangodb/testsuites/recovery.js
Labels: 2 - Working

#7676 [3.4] Added tests for Version parser
  arangod/VocBase/Methods/Version.cpp
  arangod/VocBase/Methods/Version.h
  tests/CMakeLists.txt
  tests/VocBase/VersionTest.cpp
Labels: 2 - Working

#7707 increase timeout for Foxx proxying
  js/actions/_admin/foxx/app.js
Labels: 2 - Working

#7706 Bug fix/forward port missing changes
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testsuites/ldap.js
  lib/Basics/debugging.cpp
  lib/Basics/win-utils.cpp
Labels: 2 - Working

#7485 Update upgrade data tests for compatibility with Oskar.
  js/client/modules/@arangodb/testsuites/upgrade-data.js
Labels: 2 - Working

#7589 [3.4] Early sort out system collections for maintenance
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/Maintenance.cpp
  tests/Maintenance/Current.json
  tests/Maintenance/DBServer0001.json
  tests/Maintenance/DBServer0002.json
  tests/Maintenance/DBServer0003.json
  tests/Maintenance/Plan.json
  tests/Maintenance/Supervision.json
Labels: 2 - Working, Team Clifton

#7684 Agency not starting in log level trace
  arangod/Agency/Agent.cpp
  tests/IResearch/StorageEngineMock.h
Labels: 1 Bug, 2 - Working, Team Clifton

#7687 [3.4] agency not starting in log level trace
  arangod/Agency/Agent.cpp
  tests/IResearch/StorageEngineMock.h
Labels: 1 Bug, 2 - Working, Team Clifton

#7536 Fix windows test for Foxx socket request URL
  js/server/modules/@arangodb/foxx/router/request.js
  tests/js/server/shell/shell-foxx-request-spec.js
Labels: 1 Bug, 2 - Working, 3 Foxx, 4 Windows, 9 Review Required

#7602 Fix TypeError for invalid manifests
  CHANGELOG
  js/server/modules/@arangodb/foxx/manifest.js
Labels: 1 Bug, 2 - Working, 3 Foxx, 9 Review Required

#7603 Fix TypeError for invalid manifests (3.4)
  CHANGELOG
  js/server/modules/@arangodb/foxx/manifest.js
Labels: 1 Bug, 2 - Working, 3 Foxx, 9 Review Required

#7593 Improved stability of dump restore test
  js/client/modules/@arangodb/testsuites/recovery.js
  tests/js/server/dump/dump-mmfiles-cluster.js
  tests/js/server/dump/dump-rocksdb-cluster.js
Labels: 2 - Working, 9 Waiting for Jenkins

#7714 [3.4] Fix variable access
  js/client/modules/@arangodb/testsuites/recovery.js
Labels: 1 Bug, 2 - Working

#7716 [3.4] LastAcked(Time)
  arangod/Agency/Supervision.cpp
Labels: 2 - Working

#7484 [3.4] Update upgrade data tests for compatibility with Oskar.
  js/client/modules/@arangodb/testsuites/upgrade-data.js
Labels: 2 - Working

#7717 backport missing changes to 3.4
  arangod/Cluster/SynchronizeShard.cpp
  arangod/MMFiles/MMFilesTransactionCollection.cpp
  arangod/Pregel/Worker.cpp
Labels: 2 - Working

#7719 fix forwarding of coordinator requests via /_api/job
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
  arangod/RestHandler/RestJobHandler.cpp
  arangod/RestHandler/RestJobHandler.h
Labels: 2 - Working

#7723 [3.4] Ignore invaild geo coordinates when indexing.
  CHANGELOG
  arangod/GeoIndex/Index.cpp
Labels: 2 - Working

#7721 Bugfix: port 3.4 change to stopBackgroundThreads.
  arangod/Cluster/ClusterComm.cpp
Labels: 2 - Working

#7725 issue 511.2.1: use references instead of raw pointers for Index operations to avoid null pointer access
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/ClusterEngine/ClusterIndex.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkCoordinator.h
  arangod/IResearch/IResearchMMFilesLink.h
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/MMFiles/MMFilesDocumentOperation.cpp
  arangod/MMFiles/MMFilesEdgeIndex.cpp
  arangod/MMFiles/MMFilesEdgeIndex.h
  arangod/MMFiles/MMFilesFulltextIndex.cpp
  arangod/MMFiles/MMFilesFulltextIndex.h
  arangod/MMFiles/MMFilesGeoIndex.cpp
  arangod/MMFiles/MMFilesGeoIndex.h
  arangod/MMFiles/MMFilesHashIndex.cpp
  arangod/MMFiles/MMFilesHashIndex.h
  arangod/MMFiles/MMFilesPersistentIndex.cpp
  arangod/MMFiles/MMFilesPersistentIndex.h
  arangod/MMFiles/MMFilesPrimaryIndex.cpp
  arangod/MMFiles/MMFilesPrimaryIndex.h
  arangod/MMFiles/MMFilesSkiplistIndex.cpp
  arangod/MMFiles/MMFilesSkiplistIndex.h
  arangod/MMFiles/MMFilesWalRecoverState.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
  arangod/RocksDBEngine/RocksDBFulltextIndex.h
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.h
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.h
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/Transaction/Methods.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/IResearch/StorageEngineMock.cpp
  tests/IResearch/StorageEngineMock.h
Labels: 2 - Working

#7690 Docs: 3.4 Custom Search IDs (CSE)
  VERSIONS
Labels: 2 - Working, 3 Documentation

#7741 Doc: fix build - add missing SUMMARY entries
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#7729 Bug fix 3.4/fix thread shutdown
  CHANGELOG
  lib/Basics/threads-win32.cpp
Labels: 2 - Working

#7727 fix thread shutdown on _WIN32
  CHANGELOG
  lib/Basics/threads-win32.cpp
Labels: 2 - Working

#7728 Bug fix/fix thread shutdown
  CHANGELOG
  lib/Basics/threads-win32.cpp
Labels: 2 - Working

#7732 Bug fix 3.2/fix thread shutdown
  CHANGELOG
  lib/Basics/threads-win32.cpp
Labels: 2 - Working

#7740 fix async job ids when forwarding requests
  arangod/GeneralServer/AsyncJobManager.cpp
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/GeneralServer/RestHandler.h
  js/client/modules/@arangodb/testsuites/loadBalancing.js
  js/client/tests/load-balancing/load-balancing-async-auth-cluster.js
  js/client/tests/load-balancing/load-balancing-async-noauth-cluster.js
  js/client/tests/load-balancing/load-balancing-cursor-sync-noauth-cluster.js
Labels: 2 - Working

#7747 fixed item 3 of issue #7009
  arangod/Aql/OptimizerRulesReplaceFunctions.cpp
Labels: 2 - Working

#7746 fixed item 3 of issue #7009
  arangod/Aql/OptimizerRulesReplaceFunctions.cpp
Labels: 2 - Working

#7734 fix invalid handling of `_lastValue` in case of multiple coordinators
  arangod/VocBase/KeyGenerator.cpp
  arangod/VocBase/KeyGenerator.h
  arangod/VocBase/LogicalCollection.h
  tests/js/common/shell/shell-keygen.js
Labels: 2 - Working

#7735 fix invalid handling of `_lastValue` in case of multiple coordinators
  arangod/VocBase/KeyGenerator.cpp
  arangod/VocBase/KeyGenerator.h
  arangod/VocBase/LogicalCollection.h
  tests/js/common/shell/shell-keygen.js
Labels: 2 - Working

#7731 wait for procdump to exit too.
  UnitTests/unittest.js
  js/client/modules/@arangodb/crash-utils.js
  js/client/modules/@arangodb/process-utils.js
  lib/Basics/process-utils.cpp
  lib/Basics/process-utils.h
  lib/V8/v8-utils.cpp
Labels: 2 - Working

#7753 Bug fix 3.4/wait for procdump
  UnitTests/unittest.js
  js/client/modules/@arangodb/crash-utils.js
  js/client/modules/@arangodb/process-utils.js
  lib/Basics/process-utils.cpp
  lib/Basics/process-utils.h
  lib/V8/v8-utils.cpp
Labels: 2 - Working

#7758 Bug fix 3.4/fix tombstones
  CHANGELOG
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: 1 Bug, 2 - Working

#7750 Feature3.4/improve edgeindex covered
  arangod/Aql/IndexNode.cpp
  arangod/Aql/Query.cpp
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndex.h
  arangod/Indexes/Index.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  tests/js/server/aql/aql-optimizer-index-only-rocksdb.js
Labels: 1 Feature, 2 - Working

#7759 Fix a rare deadlock situation in Replication sync phase
  CHANGELOG
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: 1 Bug, 2 - Working

#7774 fix cmake parameters coincidence
  3rdParty/iresearch/CMakeLists.txt
  3rdParty/iresearch/core/CMakeLists.txt
  3rdParty/iresearch/tests/CMakeLists.txt
Labels: 2 - Working

#7754 [3.4] equalising devel and 34
  arangod/Agency/AgentCallback.cpp
  arangod/Cluster/AgencyCallback.cpp
Labels: 2 - Working, Team Clifton

#7755 equalising devel and 3.4 in agency/cluster
  arangod/Cluster/SynchronizeShard.cpp
Labels: 2 - Working, Team Clifton

#7779 Adjust two error codes (TRI_ERROR_SHUTTING_DOWN).
  arangod/Cluster/SynchronizeShard.cpp
Labels: 2 - Working

#7770 Fix S2 for aarch64.
  3rdParty/s2geometry/dfefe0c/src/s2/third_party/absl/base/internal/unaligned_access.h
Labels: 2 - Working

#7736 [3.4] allow for quicker start of actions when previusly completed
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/ActionBase.h
  arangod/Cluster/ActionDescription.h
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/CreateCollection.h
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/DropCollection.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/Maintenance.h
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/SynchronizeShard.h
  tests/Maintenance/MaintenanceFeatureMock.h
  tests/Maintenance/MaintenanceFeatureTest.cpp
  tests/Maintenance/MaintenanceTest.cpp
Labels: 2 - Working

#7751 Feature/drop before win7 support in compiler (#6681)
  CMakeLists.txt
  arangod/Aql/AqlItemBlock.cpp
  arangod/RestServer/InitDatabaseFeature.cpp
  lib/Basics/StringUtils.cpp
  lib/Rest/VstRequest.cpp
  tests/V8Server/v8-users-test.cpp
  tests/V8Server/v8-views-test.cpp
Labels: 2 - Working

#7748 issue 511.3: remove IResearchViewDBServer and use the IResearchView directly on db-server
  arangod/CMakeLists.txt
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterEngine.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchRocksDBLink.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/IResearchViewDBServer.cpp
  arangod/IResearch/IResearchViewDBServer.h
  arangod/IResearch/IResearchViewNode.cpp
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/MMFiles/MMFilesEngine.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/StorageEngine/StorageEngine.h
  arangod/VocBase/LogicalView.cpp
  arangod/VocBase/LogicalView.h
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  tests/Cluster/ClusterInfo-test.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/IResearch/StorageEngineMock.cpp
  tests/IResearch/StorageEngineMock.h
  tests/RestHandler/RestUsersHandler-test.cpp
  tests/RestHandler/RestViewHandler-test.cpp
  tests/Utils/CollectionNameResolver-test.cpp
  tests/V8Server/v8-users-test.cpp
  tests/V8Server/v8-views-test.cpp
  tests/VocBase/LogicalDataSource-test.cpp
  tests/VocBase/vocbase-test.cpp
Labels: 2 - Working

#7128 tools are now looking into the build to find the file
  CMakeLists.txt
Labels: 2 - Working

#7790 [3.4] fix issue #7777
  arangod/IResearch/IResearchViewBlock.cpp
  tests/IResearch/IResearchQueryStartsWith-test.cpp
Labels: 2 - Working

#7786 issue 511.4: ensure IResearchLink can be initialized without view as required for db-server, minor code fixes and cleanup
  3rdParty/iresearch/core/index/index_writer.hpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchLinkCoordinator.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchMMFilesLink.cpp
  arangod/IResearch/IResearchMMFilesLink.h
  arangod/IResearch/IResearchRocksDBLink.cpp
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/VocBase/vocbase.cpp
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchLinkCoordinator-test.cpp
  tests/IResearch/IResearchView-test.cpp
Labels: 2 - Working

#7793 fixed issue #7763
  CHANGELOG
  arangod/Aql/ModificationBlocks.cpp
  arangod/Aql/ModificationBlocks.h
  tests/js/server/aql/aql-modify-subqueries.js
Labels: 2 - Working

#7794 issue #7749
  CHANGELOG
  arangod/Aql/CollectBlock.cpp
  tests/js/server/aql/aql-optimizer-collect-into.js
Labels: 2 - Working

#7795 improve error handling in case query cannot be found
  arangod/RestHandler/RestQueryHandler.cpp
Labels: 2 - Working

#7780 fix issue #7743: properly invalidate variables after COLLECT statemen…
  CHANGELOG
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges35.md
  arangod/Aql/Scopes.cpp
  arangod/Aql/Scopes.h
  tests/js/server/aql/aql-variables.js
Labels: 2 - Working

#7801 update ArangoSearch consolidation policy
  3rdParty/iresearch/core/utils/attributes.hpp
  3rdParty/iresearch/core/utils/file_utils.cpp
  3rdParty/iresearch/core/utils/index_utils.cpp
  3rdParty/iresearch/core/utils/index_utils.hpp
  3rdParty/iresearch/core/utils/ref_counter.hpp
  3rdParty/iresearch/core/utils/text_format.hpp
  arangod/IResearch/IResearchViewMeta.cpp
Labels: 2 - Working

#7802 update ArangoSearch consolidation policy (#7801)
  3rdParty/iresearch/core/utils/attributes.hpp
  3rdParty/iresearch/core/utils/file_utils.cpp
  3rdParty/iresearch/core/utils/index_utils.cpp
  3rdParty/iresearch/core/utils/index_utils.hpp
  3rdParty/iresearch/core/utils/ref_counter.hpp
  3rdParty/iresearch/core/utils/text_format.hpp
  arangod/IResearch/IResearchViewMeta.cpp
Labels: 2 - Working

#7796 fixed issue #7763
  CHANGELOG
  arangod/Aql/ModificationBlocks.cpp
  arangod/Aql/ModificationBlocks.h
  tests/js/server/aql/aql-modify-subqueries.js
Labels: 2 - Working

#7800 do not use an internal error for JSON parse errors
  arangod/GeneralServer/RestHandler.cpp
Labels: 2 - Working

#7799 do not use an internal error for JSON parse errors
  arangod/GeneralServer/RestHandler.cpp
Labels: 2 - Working

#7798 do not use an internal error for JSON parse errors
  arangod/GeneralServer/RestHandler.cpp
  lib/Rest/GeneralResponse.cpp
Labels: 2 - Working

#7784 ensure all system attributes are properly indexed by ArangoSearch view
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/VelocyPackHelper.h
  tests/IResearch/IResearchDocument-test.cpp
  tests/IResearch/IResearchQueryStringTerm-test.cpp
  tests/IResearch/IResearchQueryTraversal-test.cpp
  tests/IResearch/StorageEngineMock.cpp
Labels: 2 - Working

#7761 Doc - Fresh Swagger including all-keys deprecation edits
  js/apps/system/_admin/aardvark/APP/api-docs.json
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge
