Repository arangodb/arangodb, pull requests merged in 2018-03, with the labels that each got.

#4706 Bug fix/issue 4657
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
Labels: 9 Ready to Merge

#4700 Bug fix/issue 4698
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/loginView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userPermissions.js
Labels: 9 Ready to Merge

#4730 Bug fix 3.3/fix ui
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
Labels: 9 Ready to Merge

#4731 fix UI in non-authenticated mode
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
Labels: 9 Ready to Merge

#4717 Doc - Replication Refactor - Part 2
  Documentation/Books/Manual/Administration/ActiveFailover/README.md
  Documentation/Books/Manual/Administration/MasterSlave/SettingUp.md
  Documentation/Books/Manual/Architecture/Replication/README.md
  Documentation/Books/Manual/Architecture/WriteAheadLog.md
  Documentation/Books/Manual/Deployment/ActiveFailover/ManualStart.md
  Documentation/Books/Manual/Deployment/ActiveFailover/README.md
  Documentation/Books/Manual/Deployment/ActiveFailover/UsingTheStarter.md
  Documentation/Books/Manual/Deployment/Cluster/README.md
  Documentation/Books/Manual/Deployment/MasterSlave/ManualStart.md
  Documentation/Books/Manual/Deployment/MasterSlave/README.md
  Documentation/Books/Manual/GettingStarted/README.md
  Documentation/Books/Manual/Programs/README.md
  Documentation/Books/Manual/Scalability/ActiveFailover/Architecture.md
  Documentation/Books/Manual/Scalability/ActiveFailover/README.md
  Documentation/Books/Manual/Scalability/MasterSlave/Architecture.md
  Documentation/Books/stash/ServerModes.md
Labels: 9 Ready to Merge

#4715 Active-Failover VelocyStream Fixes
  arangod/GeneralServer/VstCommTask.cpp
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/Statistics/Descriptions.cpp
Labels: 9 WIP

#4752 Bug fix devel/bfs filter vertices
  arangod/Cluster/ClusterTraverser.cpp
  arangod/Graph/BreadthFirstEnumerator.cpp
  arangod/Graph/NeighborsEnumerator.cpp
  arangod/Graph/SingleServerTraverser.cpp
  arangod/Graph/Traverser.cpp
  arangod/Graph/Traverser.h
  js/server/tests/aql/aql-graph.js
Labels: 9 Review Required, 9 Waiting for Jenkins

#4811 Fix spelling, improve anchor links
  Documentation/Books/Manual/Administration/Configuration/Ldap.md
Labels: 9 WIP

#4816 Move execution of codeBlockReader.py to build-book()
  Documentation/Books/build.sh
Labels: 9 Ready to Merge

#4817 Move execution of codeBlockReader.py to build-book()
  Documentation/Books/build.sh
Labels: 9 Ready to Merge

#4818 Move execution of codeBlockReader.py to build-book()
  Documentation/Books/build.sh
Labels: 9 Ready to Merge

#4819 [3.1] Move execution of codeBlockReader.py to build-book()
  Documentation/Books/build.sh
Labels: 9 Ready to Merge

#4820 [3.0] Move execution of codeBlockReader.py to build-book()
  Documentation/Books/build.sh
Labels: 9 Ready to Merge

#4856 Add cluster upgrade procedure
  Documentation/Books/Manual/Upgrading/Cluster.md
Labels: 3 Documentation

#4873 Update MacOSX.md
  Documentation/Books/Manual/Installation/MacOSX.md
Labels: 9 Ready to Merge

#4872 Doc - Fixes issue #4868
  Documentation/DocuBlocks/Rest/Administration/JSF_get_admin_server_id.md
Labels: 3 Documentation

#4871 Doc - Fixes issue #4868
  Documentation/DocuBlocks/Rest/Administration/get_admin_server_id.md
Labels: 3 Documentation

#4891 Doc - Fix for Issue #4881
  Documentation/Books/AQL/Operations/Insert.md
Labels: 3 Documentation

#4890 Doc - Fix for Issue #4881
  Documentation/Books/AQL/Operations/Insert.md
Labels: 3 Documentation

#4783 Feature/aql server based locking
  CHANGELOG
  CMakeLists.txt
  arangod/Aql/AqlResult.cpp
  arangod/Aql/AqlResult.h
  arangod/Aql/AqlTransaction.cpp
  arangod/Aql/AqlTransaction.h
  arangod/Aql/ClusterBlocks.cpp
  arangod/Aql/EngineInfoContainerCoordinator.cpp
  arangod/Aql/EngineInfoContainerCoordinator.h
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/EngineInfoContainerDBServer.h
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionEngine.h
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/Aql/RestAqlHandler.cpp
  arangod/Aql/RestAqlHandler.h
  arangod/CMakeLists.txt
  arangod/Cluster/ClusterComm.cpp
  arangod/Cluster/ClusterComm.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/Cluster/TraverserEngine.cpp
  arangod/Cluster/TraverserEngine.h
  arangod/Cluster/TraverserEngineRegistry.cpp
  arangod/Cluster/TraverserEngineRegistry.h
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.h
  arangod/InternalRestHandler/InternalRestTraverserHandler.cpp
  arangod/Replication/Syncer.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestServer/VocbaseContext.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/AccessMode.h
  arangod/VocBase/vocbase.h
  js/server/tests/aql/aql-functions-misc.js
  js/server/tests/aql/aql-subqueries-cluster.js
  lib/Logger/LogTopic.cpp
  lib/Logger/Logger.h
  lib/Rest/GeneralRequest.h
  tests/Aql/EngineInfoContainerCoordinatorTest.cpp
  tests/Aql/RestAqlHandlerTest.cpp
  tests/CMakeLists.txt
Labels: 9 Review Required

#4909 Removed fakeit namespace. Kills windows
  tests/Aql/EngineInfoContainerCoordinatorTest.cpp
Labels: 9 Ready to Merge

#4910 Fixed catch test for EngineInfoContainerCoordinator.
  tests/Aql/EngineInfoContainerCoordinatorTest.cpp
Labels: 9 Ready to Merge

#4926 Bugfix / Supervision: removeFollower should remove the last follower(s) first
  CHANGELOG
  arangod/Agency/RemoveFollower.cpp
  tests/Agency/RemoveFollowerTest.cpp
  tests/Agency/RemoveFollowerTestLarge.json
Labels: 1 Bug, 3 Cluster, 3 ResilientServer

#4923 Bugfix / Supervision: removeFollower should remove the last follower(s) first
  CHANGELOG
  arangod/Agency/RemoveFollower.cpp
  tests/Agency/RemoveFollowerTest.cpp
  tests/Agency/RemoveFollowerTestLarge.json
Labels: 1 Bug, 3 Cluster, 3 ResilientServer

#4941 [3.3] Split large string literal in parts <16k for MSVC++
  tests/Agency/RemoveFollowerTest.cpp
  tests/Agency/RemoveFollowerTestLarge.json
Labels: 1 Bug, 3 Build, 9 Ready to Merge

#4949 fixed issue #4934: Wrong used GeoIndex depending on FILTER order
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  js/server/tests/aql/aql-optimizer-geoindex.js
Labels: 9 Ready to Merge

#4948 fixed issue #4934: Wrong used GeoIndex depending on FILTER order
  arangod/Aql/OptimizerRules.cpp
  js/server/tests/aql/aql-optimizer-geoindex.js
Labels: 9 Ready to Merge

#4947 fixed issue #4934: Wrong used GeoIndex depending on FILTER order
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  js/server/tests/aql/aql-optimizer-geoindex.js
Labels: 9 Ready to Merge

#4927 Bugfix / Supervision: removeFollower should remove the last follower(s) first
  CHANGELOG
  arangod/Agency/RemoveFollower.cpp
  tests/Agency/RemoveFollowerTest.cpp
  tests/Agency/RemoveFollowerTestLarge.json
Labels: 1 Bug, 3 Cluster, 3 ResilientServer, 9 Ready to Merge

#4964 Fixed uninitialized value in date subtract/add function.
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
Labels: 9 Ready to Merge

#4901 Doc - Add some missing db and collection methods
  Documentation/Books/AQL/Invocation/WithArangosh.md
  Documentation/Books/Manual/Appendix/References/CollectionObject.md
  Documentation/Books/Manual/Appendix/References/DBObject.md
  Documentation/Books/Manual/DataModeling/Collections/README.md
  Documentation/Books/Manual/DataModeling/Databases/WorkingWith.md
  js/client/modules/@arangodb/arango-collection.js
  js/client/modules/@arangodb/arango-database.js
Labels: 9 Ready to Merge

#4903 Doc - Fix typos (#4553)
  Documentation/Books/Manual/GettingStarted/ComingFromSql.md
  Documentation/Books/Manual/GettingStarted/README.md
  Documentation/Books/Manual/README.md
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Scalability/Architecture.md
Labels: 9 Ready to Merge

#4905 Doc - Fix typos
  Documentation/Books/Manual/GettingStarted/ComingFromSql.md
  Documentation/Books/Manual/GettingStarted/README.md
  Documentation/Books/Manual/Graphs/README.md
  Documentation/Books/Manual/README.md
  Documentation/Books/Manual/ReleaseNotes/KnownIssues32.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures24.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures26.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges27.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges30.md
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Scalability/Architecture.md
Labels: 9 Ready to Merge

#4904 Docs - Use relative links for cross references
  Documentation/Books/Manual/Graphs/README.md
  Documentation/Books/Manual/README.md
  Documentation/Books/Manual/ReleaseNotes/KnownIssues32.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures24.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures26.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges27.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges30.md
Labels: 9 Ready to Merge

#4982 Documentation/fix query parse example
  Documentation/Books/AQL/Invocation/WithArangosh.md
  Documentation/Books/Manual/DataModeling/Databases/WorkingWith.md
  Documentation/Examples/06_workWithAQL_statements13.generated
Labels: 3 Documentation, 9 Ready to Merge
