Repository arangodb/arangodb, pull requests merged in 2019-10, with the labels that each got.

#10115 [3.5] unitended multiple unlocks
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
Labels: Team Clifton

#10117 Port backup size to 3.5.
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_download.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_upload.md
  arangod/Cluster/ClusterMethods.cpp
  arangod/StorageEngine/HotBackupCommon.h
  arangod/Utils/ExecContext.h
  arangosh/Backup/BackupFeature.cpp
Labels: 1 Feature

#10114 unitended multiple unlocks
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
Labels: 1 Bug, Team Clifton

#10109 Bug fix/speedup tests
  tests/js/client/authentication/user-access-right-task-update-view-arangosearch.js
  tests/js/client/authentication/user-access-right-update-view-arangosearch.js
  tests/js/server/aql/aql-failures-noncluster.js
  tests/js/server/aql/aql-gather-block-cluster.js
  tests/js/server/aql/aql-modify-cluster.js
  tests/js/server/aql/aql-optimizer-collect-aggregate.js
  tests/js/server/aql/aql-optimizer-edge-index.js
  tests/js/server/aql/aql-optimizer-geoindex.js
  tests/js/server/aql/aql-optimizer-indexes-multi.js
  tests/js/server/aql/aql-optimizer-indexes-sort.js
  tests/js/server/aql/aql-optimizer-indexes.js
  tests/js/server/aql/aql-optimizer-rule-remove-unnecessary-remote-scatter-cluster.js
  tests/js/server/aql/aql-optimizer-rule-replace-or-with-in.js
  tests/js/server/aql/aql-optimizer-rule-undistribute-remove-after-enum-coll-cluster.js
  tests/js/server/aql/aql-optimizer-rule-use-index-for-sort-cluster.js
  tests/js/server/aql/aql-optimizer-rule-use-index-for-sort.js
  tests/js/server/aql/aql-primary-index-cluster.js
  tests/js/server/aql/aql-queries-collection.js
  tests/js/server/aql/aql-queries-document.js
  tests/js/server/aql/aql-queries-fulltext.js
  tests/js/server/aql/aql-queries-geo.js
  tests/js/server/aql/aql-queries-optimizer-in-cluster.js
  tests/js/server/aql/aql-queries-optimizer-limit-cluster.js
  tests/js/server/aql/aql-queries-optimizer-ref-cluster.js
  tests/js/server/aql/aql-queries-optimizer-sort-cluster.js
  tests/js/server/aql/aql-queries-optimizer-sort-limit.js
  tests/js/server/aql/aql-refaccess-attribute.js
  tests/js/server/aql/aql-regex.js
  tests/js/server/aql/aql-shardids-cluster.js
  tests/js/server/aql/aql-skiplist-cluster.js
  tests/js/server/aql/aql-skiplist.js
  tests/js/server/aql/aql-skipping.js
  tests/js/server/aql/aql-sort.js
  tests/js/server/aql/aql-sparse.js
  tests/js/server/aql/aql-upsert-cluster.js
  tests/js/server/aql/aql-vpack-externals.js
  tests/js/server/aql/aql-within-rectangle.js
  tests/js/server/shell/shell-pregel.js
  tests/js/server/shell/shell-transactions.js
Labels: 9 Ready to Merge

#10119 use malloc/realloc/free in velocypack::Buffer
  3rdParty/velocypack/include/velocypack/Buffer.h
Labels: 9 Ready to Merge

#10136 honor restrictions when creating graphs
  arangod/Graph/GraphManager.cpp
  arangod/Sharding/ShardingInfo.cpp
  tests/js/server/shell/shell-general-graph-creation-cluster.js
Labels: 9 Ready to Merge

#10113 add repository address normalisation
  CHANGELOG
  arangod/GeneralServer/AcceptorTcp.cpp
  js/client/modules/@arangodb/testsuites/dump.js
  lib/Basics/StringUtils.cpp
  tests/CMakeLists.txt
  tests/HotBackup/HotBackupCoordinatorTest.cpp
  tests/HotBackup/HotBackupTest.json
Labels: 9 WIP, Team Clifton

#10139 rclone path normalization (port from devel to 3.5).
  js/client/modules/@arangodb/testsuites/dump.js
  lib/Basics/StringUtils.cpp
  tests/HotBackup/HotBackupCoordinatorTest.cpp
  tests/HotBackup/HotBackupTest.json
Labels: 9 Ready to Merge

#10143 [3.5] hotbackup path normalisation and list documentation updates
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_create.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_download.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_list.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_restore.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_upload.md
Labels: 3 Documentation, 9 WIP

#10156 Bug fix 3.5/fix parsing unterminated strings
  CHANGELOG
  arangod/Aql/tokens.cpp
  arangod/Aql/tokens.ll
  tests/js/server/aql/aql-parse.js
Labels: 9 Ready to Merge

#10169 Fix hotbackup restore example snippet for devel.
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_restore.md
Labels: 1 Bug

#10168 Replace union by separate members
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
Labels: 9 Ready to Merge

#10165 Implement copying/moving constructors of InputAqlItemRow
  arangod/Aql/InputAqlItemRow.cpp
  arangod/Aql/InputAqlItemRow.h
Labels: 3 AQL, performance

#10164 Fixed repeatable seek to the same document
  3rdParty/iresearch/core/search/conjunction.hpp
  3rdParty/iresearch/core/search/phrase_iterator.hpp
Labels: 1 Bug

#10132 Add a way to avoid core-dumps on death tests
  tests/Aql/SubqueryEndExecutorTest.cpp
  tests/Mocks/Death_Test.h
Labels: 1 Bug

#9932 Docs: Dump program options of arangobackup as well
  utils/generateExamples.sh
Labels: 3 Documentation, 3 ImportExport

#9934 Docs: Add which option is used by which ArangoBackup operation
  arangosh/Backup/BackupFeature.cpp
Labels: 3 Documentation, 3 ImportExport

#10079 Feature/aql subquery all rows fetcher shadow rows
  arangod/Aql/AllRowsFetcher.cpp
  arangod/Aql/AllRowsFetcher.h
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlItemBlock.h
  arangod/Aql/AqlItemMatrix.cpp
  arangod/Aql/AqlItemMatrix.h
  tests/Aql/AllRowsFetcherTest.cpp
  tests/Aql/AqlItemBlockTest.cpp
  tests/Aql/FetcherTestHelper.h
  tests/Aql/SingleRowFetcherTest.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
Labels: 1 Feature

#9821 ArangoSearch refactor (part 2)
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
Labels: 3 Documentation, 9 Ready to Merge

#10175 Feature/aql subquery single input tests
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/Query.h
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
Labels: 1 Feature

#10006 Bug fix/internal issue #600 - Late document materialization
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/IResearchViewOptimizerRules.h
  arangod/Aql/LimitExecutor.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/RegisterPlan.cpp
  arangod/CMakeLists.txt
  js/common/modules/@arangodb/aql/explainer.js
  tests/Aql/SortExecutorTest.cpp
  tests/Aql/SortLimit-test.cpp
  tests/IResearch/IResearchViewNode-test.cpp
  tests/js/server/aql/aql-optimizer-late-document-materialization.js
Labels: 9 WIP

#10190 Bugfix for recurring Jenkins error in api-simple-modify-example-cluster-spec.rb
  arangod/Aql/DependencyProxy.cpp
Labels: 1 Bug, 3 AQL

#10163 fixed issue #10158
  CHANGELOG
  arangod/Aql/KShortestPathsExecutor.cpp
  arangod/Aql/KShortestPathsNode.cpp
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/TraversalExecutor.cpp
  arangod/Graph/KShortestPathsFinder.cpp
  tests/js/server/aql/aql-graph-traverser.js
Labels: 9 Ready to Merge

#10187 fixed issue #10183: Arangoimport imports on _system when you try to create a new database
  CHANGELOG
  arangosh/Import/ImportFeature.cpp
Labels: 9 Ready to Merge

#10192 remove debug logging
  CHANGELOG
  arangod/GeneralServer/GeneralServer.cpp
Labels: 9 Ready to Merge

#10194 Bug fix 3.5/issue 10193
  CHANGELOG
  arangosh/Export/ExportFeature.cpp
  arangosh/Export/ExportFeature.h
  js/client/modules/@arangodb/testsuites/export.js
  lib/Basics/files.cpp
  tests/js/server/export/export-setup-cluster.js
  tests/js/server/export/export-setup.js
Labels: 9 Ready to Merge

#10197 fix random willi bug
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestEdgesHandler.cpp
  arangod/RestHandler/RestGraphHandler.cpp
  arangod/RestHandler/RestImportHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  arangod/Transaction/Methods.cpp
Labels: 9 Ready to Merge

#10122 Port latest shutdown hanger bug to 3.4.
  arangod/Utils/CollectionKeysRepository.cpp
  arangod/Utils/CollectionKeysRepository.h
  arangod/VocBase/vocbase.cpp
Labels: 1 Bug

#10157 Bug fix 3.4/fix parsing unterminated strings
  CHANGELOG
  arangod/Aql/tokens.cpp
  arangod/Aql/tokens.ll
  tests/js/server/aql/aql-parse.js
Labels: 9 Ready to Merge

#10196 fixed issue #10193
  CHANGELOG
  arangosh/Export/ExportFeature.cpp
  arangosh/Export/ExportFeature.h
  js/client/modules/@arangodb/testsuites/export.js
  lib/Basics/files.cpp
  tests/js/server/export/export-setup-cluster.js
  tests/js/server/export/export-setup.js
Labels: 9 Ready to Merge

#10203 Add tests for issue #10090
  tests/js/common/aql/aql-view-arangosearch-cluster.inc
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
Labels: 3 - Testing

#10174 Bug fix 3.5/issue #10090
  3rdParty/iresearch/core/search/conjunction.hpp
  3rdParty/iresearch/core/search/phrase_iterator.hpp
  CHANGELOG
  tests/js/common/aql/aql-view-arangosearch-cluster.inc
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
Labels: 9 Ready to Merge

#9654 Deprecate rocksdb.max-write-buffer-number startup option
  arangod/StorageEngine/RocksDBOptionFeature.cpp
Labels: 3 Documentation

#10206 Bug fix/fix remote executor races
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/RemoteExecutor.h
  arangod/Aql/SharedQueryState.cpp
  arangod/Aql/SharedQueryState.h
Labels: 1 Bug, 9 Ready to Merge

#10101 AQL Subquery: MultiDependencyRowFetcher
  arangod/Aql/CollectNode.cpp
  arangod/Aql/DependencyProxy.h
  arangod/Aql/DistributeConsumerNode.cpp
  arangod/Aql/DistributeExecutor.cpp
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/HashedCollectExecutor.cpp
  arangod/Aql/IndexNode.cpp
  arangod/Aql/InputAqlItemRow.cpp
  arangod/Aql/InputAqlItemRow.h
  arangod/Aql/KShortestPathsExecutor.cpp
  arangod/Aql/KShortestPathsNode.cpp
  arangod/Aql/ModificationExecutor.h
  arangod/Aql/MultiDependencySingleRowFetcher.cpp
  arangod/Aql/MultiDependencySingleRowFetcher.h
  arangod/Aql/ShadowAqlItemRow.cpp
  arangod/Aql/ShadowAqlItemRow.h
  arangod/Aql/SharedAqlItemBlockPtr.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/SingleRowFetcher.cpp
  arangod/Aql/SortNode.cpp
  arangod/Aql/SortedCollectExecutor.cpp
  arangod/Aql/SubqueryEndExecutionNode.cpp
  arangod/Aql/SubqueryStartExecutionNode.cpp
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/CMakeLists.txt
  tests/Aql/AqlItemRowPrinter.cpp
  tests/Aql/AqlItemRowPrinter.h
  tests/Aql/AqlItemRowTest.cpp
  tests/Aql/DependencyProxyMock.cpp
  tests/Aql/DependencyProxyMock.h
  tests/Aql/MultiDepFetcherHelper.cpp
  tests/Aql/MultiDepFetcherHelper.h
  tests/Aql/MultiDependencySingleRowFetcherTest.cpp
  tests/Aql/SortedCollectExecutorTest.cpp
  tests/Aql/TraversalExecutorTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-profiler.js
Labels: 1 Feature, 3 AQL

#10216 [devel] Fix document search (Ctrl+F/Cmd+F)
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/manifest.json
Labels: 1 Bug, 3 UI, 9 Ready to Merge

#9719 fixed ui behaviour when replacing a foxx app
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/foxxes.js
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/foxxCollection.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/foxxInstallView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/foxxRepoView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installGitHubServiceView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installNewServiceView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installUploadServiceView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installUrlServiceView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/storeDetailView.js
Labels: 9 Review Required

#10213 Bug fix/fix simple example dep proxy skip some regression test
  CHANGELOG
  tests/js/server/aql/aql-skipping-cluster.js
Labels: 3 - Testing, 9 Ready to Merge

#10198 fix it!
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/Transaction/Methods.cpp
Labels: 9 Ready to Merge

#10207 Doc - Added "log-output" example
  lib/Logger/LoggerFeature.cpp
Labels: 3 Documentation

#10199 [3.5] Fix AQL skip in cluster sometimes causing documents to be forgotten
  arangod/Aql/DependencyProxy.cpp
  tests/js/server/aql/aql-skipping-cluster.js
Labels: 1 Bug, 3 AQL, 9 Ready to Merge

#10223 Doc - Added "log-output" example
  lib/Logger/LoggerFeature.cpp
Labels: 3 Documentation, 9 Ready to Merge

#10186 Fix hotbackup locking.
  arangod/Cluster/ClusterMethods.cpp
Labels: 9 Ready to Merge

#10215 [3.5] Fix document search (Ctrl+F/Cmd+F)
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/manifest.json
Labels: 1 Bug, 3 UI, 9 Ready to Merge

#10222 Improved performance of some agency helper functions.
  CHANGELOG
  arangod/Agency/Store.cpp
  arangod/Agency/Store.h
  tests/Agency/StoreTest.cpp
Labels: 9 Ready to Merge

#10245 fix leak in hot backup tests
  tests/RocksDBEngine/ShaEventListener.cpp
Labels: 9 Ready to Merge

#10242 [3.5] yet another agency ttl bug
  CHANGELOG
  arangod/Agency/AgencyCommon.h
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/State.cpp
Labels: 1 Bug, 9 WIP, Team Clifton

#10258 Merge changes related to VS2019 support from IResearch upstream
  3rdParty/iresearch/appveyor.yml
  3rdParty/iresearch/core/shared.hpp
  3rdParty/iresearch/core/utils/attributes.hpp
  3rdParty/iresearch/core/utils/block_pool.hpp
  3rdParty/iresearch/tests/index/consolidation_policy_tests.cpp
  3rdParty/iresearch/tests/index/index_tests.cpp
  3rdParty/iresearch/tests/utils/async_utils_tests.cpp
  3rdParty/iresearch/tests/utils/object_pool_tests.cpp
Labels: 3 Search

#10231 disallow subqueries in AQL traversal PRUNE conditions
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AstNode.h
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-graph-traverser.js
Labels: 9 Ready to Merge

#10259 Feature 3.5/convert gharial test to arangoclient
  CHANGELOG
  arangod/RestHandler/RestGraphHandler.cpp
  arangod/RestHandler/RestGraphHandler.h
  lib/Rest/GeneralResponse.h
  lib/Rest/HttpResponse.h
  lib/Rest/VstResponse.h
  tests/IResearch/RestHandlerMock.h
  tests/js/client/http/api-gharial-spec.js
  tests/rb/HttpInterface/api-general-graph-spec.rb
Labels: 9 Ready to Merge

#10026 Make scheduler enforce queue limits
  CHANGELOG
  arangod/GeneralServer/RequestLane.h
  arangod/Scheduler/SchedulerFeature.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
Labels: 9 Waiting for Jenkins

#10266 Bug fix 3.4/disallow subqueries in prune
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AstNode.h
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-graph-traverser.js
Labels: 9 Waiting for Jenkins

#10098 [3.5] Fix constrained sort in the cluster
  CHANGELOG
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ClusterNodes.h
  arangod/Aql/DependencyProxy.cpp
  arangod/Aql/DependencyProxy.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/MultiDependencySingleRowFetcher.cpp
  arangod/Aql/MultiDependencySingleRowFetcher.h
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/SortNode.h
  arangod/Aql/SortingGatherExecutor.cpp
  arangod/Aql/SortingGatherExecutor.h
  tests/js/server/aql/aql-queries-optimizer-sort-limit-cluster.js
  tests/js/server/aql/aql-queries-optimizer-sort-limit.js
Labels: 1 Bug, 9 Waiting for Jenkins

#10254 fix docublocks parameter naming
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_fulltext.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_hash.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_persistent.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_skiplist.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_ttl.md
Labels: 3 Documentation

#10218 use the default arangosh client connection instead of the simple http client to test the gharial API
  CHANGELOG
  arangod/RestHandler/RestGraphHandler.cpp
  arangod/RestHandler/RestGraphHandler.h
  lib/Rest/GeneralResponse.h
  lib/Rest/HttpResponse.h
  lib/Rest/VstResponse.cpp
  lib/Rest/VstResponse.h
  tests/IResearch/RestHandlerMock.h
  tests/js/client/http/api-gharial-spec.js
  tests/rb/HttpInterface/api-general-graph-spec.rb
Labels: 9 Ready to Merge

#10275 Avoid a race and a use-after-free bug in the RemoteExecutor
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/SharedQueryState.cpp
  arangod/Aql/SharedQueryState.h
Labels: 1 Bug

#10277 Try to use gcc 9.2.0
  VERSIONS
Labels: 3 Build, 4 Linux

#10272 fixed issue #10270
  CHANGELOG
  arangod/Aql/EnumerateListExecutor.cpp
  tests/js/server/aql/aql-queries-simple.js
Labels: 9 Ready to Merge

#9961 [3.3] Bug fix 3.3/allow agency ops in active failover
  CHANGELOG
  arangod/Cluster/v8-cluster.cpp
  js/client/tests/active-failover/basic.js
Labels: 1 Bug, 9 Ready to Merge

#10289 Allow to ignore superuser traffic with an option.
  CHANGELOG
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/RestHandler/RestAdminStatisticsHandler.cpp
  arangod/Statistics/Descriptions.cpp
  arangod/Statistics/Descriptions.h
  arangod/Statistics/RequestStatistics.cpp
  arangod/Statistics/RequestStatistics.h
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  arangod/Statistics/StatisticsWorker.cpp
  arangod/Statistics/figures.h
  arangod/V8Server/v8-statistics.cpp
  lib/Rest/VstMessage.h
Labels: 9 WIP

#10315 Bug fix 3.5/wait until we appear in supervision health
  CHANGELOG
  arangod/RestServer/BootstrapFeature.cpp
Labels: 9 Ready to Merge

#10290 Feature/aql modificators cpp test
  tests/Aql/InsertExecutorTest.cpp
  tests/Aql/QueryHelper.cpp
  tests/Aql/QueryHelper.h
  tests/Aql/RemoveExecutorTest.cpp
  tests/Aql/ReplaceExecutorTest.cpp
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
  tests/Aql/UpdateExecutorTest.cpp
  tests/Aql/UpsertExecutorTest.cpp
  tests/CMakeLists.txt
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/Transaction/Context-test.cpp
Labels: 3 - Testing

#10327 Enable OpenSSL strict version to separate ArangoDB and build it in os…
  CMakeLists.txt
  VERSIONS
  cmake/custom/ArangoDB_FindOpenSSL_WIN32.cmake
Labels: OpenSSL

#10326 Enable OpenSSL strict version to separate ArangoDB and build it in os…
  CMakeLists.txt
  VERSIONS
  cmake/custom/ArangoDB_FindOpenSSL_WIN32.cmake
Labels: OpenSSL

#10325 Bug fix/separate openssl with oskar
  CMakeLists.txt
  VERSIONS
  cmake/custom/ArangoDB_FindOpenSSL_WIN32.cmake
Labels: OpenSSL

#10313 Added overload template
  lib/Basics/overload.h
  tests/Basics/overload-test.cpp
  tests/CMakeLists.txt
Labels: 1 Feature

#10309 smart join views
  .editorconfig
  CHANGELOG
  arangod/Aql/OptimizerRulesFeature.cpp
Labels: 1 Feature, 3 Cluster

#10267 Enable AQL subquery optimization (only on getSome)
  arangod/Aql/AllRowsFetcher.cpp
  arangod/Aql/AllRowsFetcher.h
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlItemBlock.h
  arangod/Aql/CalculationExecutor.cpp
  arangod/Aql/CalculationExecutor.h
  arangod/Aql/ConstFetcher.cpp
  arangod/Aql/ConstFetcher.h
  arangod/Aql/DependencyProxy.h
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/FilterExecutor.h
  arangod/Aql/IdExecutor.cpp
  arangod/Aql/IdExecutor.h
  arangod/Aql/InputAqlItemRow.cpp
  arangod/Aql/InputAqlItemRow.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/RemoteExecutor.h
  arangod/Aql/SingleBlockFetcher.h
  arangod/Aql/SingleRowFetcher.cpp
  arangod/Aql/SingleRowFetcher.h
  arangod/Aql/SubqueryEndExecutionNode.cpp
  arangod/Aql/SubqueryEndExecutionNode.h
  arangod/Aql/SubqueryEndExecutor.cpp
  arangod/Aql/SubqueryEndExecutor.h
  arangod/Aql/SubqueryExecutor.cpp
  arangod/Aql/SubqueryExecutor.h
  arangod/Aql/SubqueryStartExecutor.cpp
  lib/Logger/LoggerStream.h
  tests/Aql/AqlItemRowTest.cpp
  tests/Aql/ExecutionNodeTest.cpp
  tests/Aql/MultiDepFetcherHelper.cpp
  tests/Aql/MultiDependencySingleRowFetcherTest.cpp
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
  tests/Aql/SubqueryEndExecutorTest.cpp
  tests/Graph/GraphTestTools.h
  tests/js/server/aql/aql-failures-noncluster.js
  tests/js/server/aql/aql-optimizer-indexes.js
  tests/js/server/aql/aql-optimizer-rule-use-index-for-sort.js
  tests/js/server/aql/aql-optimizer-stats-noncluster.js
  tests/js/server/aql/aql-subquery.js
Labels: 1 Feature, 3 AQL

#10344 fix cleanupEngines, add another sanity check
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Cluster/ClusterTrxMethods.cpp
Labels: 9 Ready to Merge
