Repository arangodb/arangodb, pull requests merged in 2019-05, with the labels that each got.

#8866 Fixed a warning and avoid an accidental copy
  arangod/Aql/DocumentProducingHelper.h
Labels: performance

#8873 Improve performance when writing a row
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
Labels: performance

#7329 Arangosh: server.endpoint must start with http+ssl:// if server uses SSL
  Documentation/Books/Manual/Programs/Arangod/Server.md
  Documentation/Books/Manual/Programs/Arangosh/Examples.md
  Documentation/Examples/arangosh.json
  arangosh/Shell/ClientFeature.cpp
Labels: 2 - Working, 3 Documentation

#7964 Doc - macOS - Remove Graphical App, improve CLI install steps
  Documentation/Books/Manual/Installation/MacOSX.md
Labels: 2 - Working, 3 Documentation, 4 MacOSX

#8095 Doc - Arangorestore - Number-of-shards and replication-factor…
  Documentation/Books/Manual/Programs/Arangorestore/Examples.md
Labels: 2 - Working, 3 Documentation, 3 ImportExport

#8299 Doc - Correct AQL function examples
  Documentation/Books/AQL/Functions/Document.md
  Documentation/Books/AQL/Functions/Numeric.md
  Documentation/Books/AQL/Functions/String.md
Labels: 2 - Working, 3 Documentation

#8742 Change standalone agency doc
  Documentation/Books/Manual/Deployment/StandaloneAgency/README.md
Labels: 3 Documentation

#8744 Fix cleanout server
  Documentation/Books/Manual/Administration/Cluster/README.md
Labels: 3 Documentation

#8835 Small typo
  Documentation/Books/HTTP/General/README.md
Labels: 3 Documentation, 9 CLA available

#8859 Doc - DC2DC: DirectMQ vs. Kafka
  Documentation/Books/Manual/Architecture/DeploymentModes/DC2DC/Introduction.md
  Documentation/Books/Manual/Deployment/DC2DC/KafkaZookeeper.md
Labels: 3 Documentation

#8836 Add documentation for k Shortest Paths
  Documentation/Books/AQL/Graphs/KShortestPaths.md
  Documentation/Books/AQL/Graphs/train_map.png
  Documentation/Books/AQL/SUMMARY.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
  Documentation/Examples/GRAPHKSP_01_create_graph.generated
  Documentation/Examples/GRAPHKSP_02_Aberdeen_to_London.generated
  Documentation/Examples/GRAPHKSP_03_Aberdeen_to_London.generated
  Documentation/Examples/GRAPHKSP_04_Aberdeen_to_Toronto.generated
  Documentation/Examples/GRAPHKSP_05_StAndrews_to_Cologne.generated
  Documentation/Examples/GRAPHKSP_99_drop_graph.generated
  js/common/modules/@arangodb/graph-examples/example-graph.js
Labels: 3 Documentation

#8900 Doc - DC2DC: DirectMQ vs. Kafka (#8859)
  Documentation/Books/Manual/Architecture/DeploymentModes/DC2DC/Introduction.md
  Documentation/Books/Manual/Deployment/DC2DC/KafkaZookeeper.md
Labels: 3 Documentation

#8901 Doc - Fix cleanout server example (#8744)
  Documentation/Books/Manual/Administration/Cluster/README.md
Labels: 3 Documentation

#8902 Doc - Changes to standalone agency example (#8742)
  Documentation/Books/Manual/Deployment/StandaloneAgency/README.md
Labels: 3 Documentation

#8903 Doc - Small typos (#8835)
  Documentation/Books/HTTP/General/README.md
Labels: 3 Documentation

#8904 Doc - Correct AQL function examples (#8299)
  Documentation/Books/AQL/Functions/Document.md
  Documentation/Books/AQL/Functions/Numeric.md
  Documentation/Books/AQL/Functions/String.md
Labels: 3 Documentation

#8905 Doc - Arangorestore - Number-of-shards and replication-factor (#8095)
  Documentation/Books/Manual/Programs/Arangorestore/Examples.md
Labels: 3 Documentation

#8906 Doc - macOS - Remove Graphical App, improve CLI install steps, Starter inclusion
  Documentation/Books/Manual/Installation/MacOSX.md
Labels: 3 Documentation

#8907 Doc - Arangosh: server.endpoint must start with http+ssl:// if server uses SSL
  Documentation/Books/Manual/Programs/Arangod/Server.md
  Documentation/Books/Manual/Programs/Arangosh/Examples.md
  Documentation/Examples/arangosh.json
  arangosh/Shell/ClientFeature.cpp
Labels: 3 Documentation

#8910 Doc - SmartGraphs formatting (#6486)
  Documentation/Books/Manual/Graphs/SmartGraphs/README.md
Labels: 3 Documentation

#8911 Doc - Fix Views markup
  Documentation/Books/Manual/Views/ArangoSearch/DetailedOverview.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
Labels: 3 Documentation

#8889 Improve k Shortest Paths performance
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
Labels: 9 Waiting for Jenkins, performance

#8914 Avoid occasional query id not found errors
  arangod/Aql/RemoteExecutor.cpp
Labels: 1 Bug

#8895 Add K_SHORTEST_PATHS handling to optimizer and executor
  arangod/Aql/CollectNode.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/TraversalConditionFinder.cpp
Labels: 1 Bug, 9 Waiting for Jenkins

#8853 Bug fix/collect aggregate undefined
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
  arangod/Aql/SortedCollectExecutor.cpp
  arangod/Aql/SortedCollectExecutor.h
  tests/js/server/aql/aql-optimizer-collect-count.js
Labels: 9 Review Required

#8874 Improve document callback performance
  arangod/Aql/DocumentProducingHelper.h
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  arangod/Aql/Stats.h
Labels: performance

#8934 fix sortedness of sorted results returned by RETURN DISTINCT
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-collect-in-cluster.js
Labels: 9 Ready to Merge

#8957 Use ArangoDB Starter 0.14.3
  CHANGELOG
  VERSIONS
Labels: 3 Starter

#8956 Use ArangoDB Starter 0.14.3
  CHANGELOG
  VERSIONS
Labels: 3 Starter

#8955 Use ArangoDB Starter 0.14.3
  CHANGELOG
  VERSIONS
Labels: 3 Starter

#8959 fix some issues found by cppcheck
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/Agent.cpp
  lib/ProgramOptions/IniFileParser.cpp
Labels: 9 Ready to Merge

#8979 Bug fix/issue 8841
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphSettingsView.js
Labels: 9 Ready to Merge

#8980 Bug fix 3.4/issue 8841
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphSettingsView.js
Labels: 9 Ready to Merge

#8967 fixing issue #7011
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
Labels: 9 Ready to Merge

#8968 Bug fix 3.4/issue 7011
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
Labels: 9 Ready to Merge

#8978 Bugfix: Do not call getSome on remote after DONE
  arangod/Aql/MultiDependencySingleRowFetcher.cpp
  arangod/Aql/MultiDependencySingleRowFetcher.h
  js/server/modules/@arangodb/aql-profiler-test-helper.js
  tests/js/server/aql/aql-profiler-cluster.js
  tests/js/server/aql/aql-profiler.js
Labels: 1 Bug

#8946 Let only on shard per collection, not per DBServer, be responsible for initialize cursor (and shutdown)
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/EngineInfoContainerDBServer.h
Labels: 1 Bug, 3 AQL, 3 Cluster

#8952 [3.4] Let only on shard per collection, not per DBServer, be responsible for initialize cursor (and shutdown)
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/EngineInfoContainerDBServer.h
Labels: 1 Bug, 3 AQL, 3 Cluster

#8935 fix sort order in distributed RETURN DISTINCT
  arangod/Aql/OptimizerRules.cpp
Labels: 9 Ready to Merge

#9008 we now support umlaut temp dirs; create multi-layer temp-dirs; add tests
  js/client/modules/@arangodb/testsuites/arangosh.js
  js/client/modules/@arangodb/testsuites/paths_server.js
  lib/Basics/files.cpp
Labels: 9 Ready to Merge

#8851 Improve calculation executor performance
  arangod/Aql/CalculationExecutor.h
  arangod/Aql/InputAqlItemRow.h
  arangod/Aql/OutputAqlItemRow.h
Labels: performance

#8985 Fix a crash in ShortestPathExecutor
  arangod/Aql/ShortestPathExecutor.cpp
  tests/Aql/ShortestPathExecutorTest.cpp
Labels: 1 Bug, 9 Waiting for Jenkins

#9020 Fix Foxx security
  js/actions/_admin/foxx/app.js
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/foxxes.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/extra-minified.css
  js/apps/system/_admin/aardvark/APP/frontend/build/extra-minified.css.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/libs.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/libs.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/style-minified.css
  js/apps/system/_admin/aardvark/APP/frontend/build/style-minified.css.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/style.css.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installServiceView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
  js/apps/system/_admin/aardvark/APP/frontend/src/ace.min.js
  js/apps/system/_admin/aardvark/APP/index.js
  js/apps/system/_api/foxx/APP/index.js
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
Labels: 1 Bug, 3 Foxx, 3 UI, 9 Review Required

#9043 remove http so https arangos will work
  utils/generateSwagger.py
Labels: 3 Documentation, 3 Swagger

#9042 Bug fix/unbreak foxx security
  js/actions/_admin/foxx/app.js
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/foxxes.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/extra-minified.css
  js/apps/system/_admin/aardvark/APP/frontend/build/extra-minified.css.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/libs.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/libs.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/style-minified.css
  js/apps/system/_admin/aardvark/APP/frontend/build/style-minified.css.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/style.css.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installServiceView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
  js/apps/system/_admin/aardvark/APP/frontend/src/ace.min.js
  js/apps/system/_admin/aardvark/APP/index.js
  js/apps/system/_api/foxx/APP/index.js
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  tests/js/server/permissions/test-foxx-apis-off.js
Labels: 1 Bug, 3 Foxx

#9061 Bug fix/internal issue #570
  arangod/IResearch/IResearchLink.cpp
Labels: 1 Bug, 3 ArangoSearch

#9071 Bug fix/internal issue #572
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
Labels: 1 Bug, 3 ArangoSearch, 3 Cluster

#8791 [3.4] clean up container madness
  lib/Basics/debugging.cpp
  lib/Basics/debugging.h
Labels: 2 - Working, 9 WIP

#9082 Add ArangoSearch notice and minor fix to v3.4.6
  CHANGELOG
Labels: 3 ArangoSearch, 3 Documentation

#9089 add missing examples
  Documentation/Examples/RestTransactionBeginAbort.generated
  Documentation/Examples/RestTransactionBeginCommit.generated
  Documentation/Examples/RestTransactionBeginNonExisting.generated
  Documentation/Examples/RestTransactionBeginSingle.generated
  Documentation/Examples/RestTransactionGet.generated
Labels: 3 Documentation

#9047 Bug fix/greylist timecritical and nondeterministic
  tests/Greylist.txt
  tests/js/common/shell/shell-collection-cache-rocksdb-noncluster-nondeterministic-grey.js
  tests/js/common/shell/shell-deadlocks-timecritical-noncluster-mmfiles-grey.js
  tests/js/common/shell/shell-query-stream-timecritical-spec-grey.js
  tests/js/common/shell/shell-query-timecritical-spec-grey.js
  tests/js/common/shell/shell-tasks-timecritical-grey.js
  tests/js/server/shell/shell-any-nondeterministic-noncluster-grey.js
  tests/js/server/shell/shell-collection-not-loaded-mmfiles-timecritical-noncluster-grey.js
  tests/js/server/shell/shell-compaction-mmfiles-noncluster-timecritical-grey.js
  tests/js/server/shell/shell-compaction-seq-mmfiles-noncluster-timecritical-grey.js
  tests/js/server/shell/shell-datafile-mmfiles-timecritical-noncluster-grey.js
  tests/js/server/shell/shell-skiplist-rm-performance-timecritical-noncluster-grey.js
  tests/rb/HttpInterface/api-async-spec-timecritical-grey.rb
  tests/rb/HttpInterface/api-export-spec-timecritical-noncluster-grey.rb
  tests/rb/HttpInterface/api-query-analysis-spec-timecritical-grey.rb
Labels: 3 - Testing

#9048 Mark all timecritical and nondeterministic as greylisted (3.4)
  tests/Greylist.txt
  tests/js/client/authentication/user-access-right-task-drop-view-arangosearch-spec-nondeterministic-grey.js
  tests/js/common/aql/aql-view-arangosearch-nondeterministic-cluster-grey.js
  tests/js/common/shell/shell-collection-cache-rocksdb-noncluster-nondeterministic-grey.js
  tests/js/common/shell/shell-deadlocks-timecritical-noncluster-mmfiles-grey.js
  tests/js/common/shell/shell-query-stream-timecritical-spec-grey.js
  tests/js/common/shell/shell-query-timecritical-spec-grey.js
  tests/js/common/shell/shell-tasks-timecritical-grey.js
  tests/js/server/recovery/view-arangosearch-rename-no-flushthread-nondeterministic-grey.js
  tests/js/server/recovery/view-arangosearch-rename-query-nondeterministic-grey.js
  tests/js/server/shell/shell-any-nondeterministic-noncluster-grey.js
  tests/js/server/shell/shell-collection-not-loaded-mmfiles-timecritical-noncluster-grey.js
  tests/js/server/shell/shell-compaction-mmfiles-noncluster-timecritical-grey.js
  tests/js/server/shell/shell-compaction-seq-mmfiles-noncluster-timecritical-grey.js
  tests/js/server/shell/shell-datafile-mmfiles-timecritical-noncluster-grey.js
  tests/js/server/shell/shell-skiplist-rm-performance-timecritical-noncluster-grey.js
  tests/rb/HttpInterface/api-async-spec-timecritical-grey.rb
  tests/rb/HttpInterface/api-export-spec-timecritical-noncluster-grey.rb
  tests/rb/HttpInterface/api-query-analysis-spec-timecritical-grey.rb
Labels: 3 - Testing

#9097 Fix white swagger code
  js/server/assets/swagger/index.html
Labels: 1 Bug, 3 Swagger, 3 UI, 9 Ready to Merge

#9094 Added filtering analyzers before adding them to view link - duplica…
  arangod/IResearch/IResearchLinkMeta.cpp
  tests/IResearch/IResearchLinkMeta-test.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
Labels: 1 Bug, 3 ArangoSearch

#9041 Bugfix of DFS path uniqueness implementation
  CHANGELOG
  js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/aql-graph-traversal-generic-tests.js
  tests/js/server/aql/aql-graph-traversal-generic-cluster.js
  tests/js/server/aql/aql-graph-traversal-generic-noncluster.js
  tests/js/server/dump/dump-mmfiles-cluster.js
  tests/js/server/dump/dump-rocksdb-cluster.js
  tests/js/server/dump/dump-setup-cluster.js
Labels: 1 Bug

#9098 [3.4] Bugfix of DFS path uniqueness implementation
  CHANGELOG
  js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/aql-graph-traversal-generic-tests.js
  tests/js/server/aql/aql-graph-traversal-generic-cluster.js
  tests/js/server/aql/aql-graph-traversal-generic-noncluster.js
  tests/js/server/dump/dump-mmfiles-cluster.js
  tests/js/server/dump/dump-rocksdb-cluster.js
  tests/js/server/dump/dump-setup-cluster.js
Labels: 1 Bug, 9 Ready to Merge

#9110 Bug fix/internal issue #572
  3rdParty/iresearch/core/utils/file_utils.cpp
Labels: 1 Bug, 3 ArangoSearch

#9111 Fixed UBSan error in the scheduler
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
Labels: 1 Bug

#9119 Add USE_CLCACHE_MODE to have specific build options
  CMakeLists.txt
Labels: 3 Build, 4 Windows

#9127 Add /Z7 switch to V8 gyp
  3rdParty/V8/CMakeLists.txt
  3rdParty/V8/v7.1.302.28/gypfiles/standalone.gypi
Labels: 3 Build, 4 Windows

#9126 Round estimatedCost in some tests
  tests/js/server/aql/aql-graph-traverser.js
Labels: 1 Bug, 3 - Testing, 9 Waiting for Jenkins

#9080 (K_)SHORTEST PATHS: Display correct directions in explainer/profiler
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  js/common/modules/@arangodb/aql/explainer.js
Labels: 3 UI, 9 Review Required

#9011 Collect all tests that are skipped due to a previous crash
  js/client/modules/@arangodb/test-utils.js
Labels: 3 - Testing

#9067 [3.3] fix client lookup table
  CHANGELOG
  arangod/Agency/State.cpp
  arangod/Agency/State.h
  js/client/tests/agency/agency-test.js
Labels: Team Clifton

#9065 [3.4] fix clientid register in state
  CHANGELOG
  arangod/Agency/AgencyCommon.h
  arangod/Agency/State.cpp
  arangod/Agency/State.h
  tests/js/client/agency/agency-test.js
Labels: Team Clifton

#9066 [devel] fix state clientlookuptable
  CHANGELOG
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/State.cpp
  arangod/Agency/State.h
  arangod/Agency/Supervision.cpp
  tests/Agency/MoveShardTest.cpp
  tests/js/client/agency/agency-test.js
Labels: Team Clifton

#9141 Fix some uses of atomics
  arangod/ClusterEngine/ClusterSelectivityEstimates.cpp
  arangosh/Shell/V8ClientConnection.cpp
Labels: 1 Bug, 9 Review Required, 9 Waiting for Jenkins

#9144 Remove std::move as it prevents copy elision
  lib/Futures/Future.h
Labels: 9 Waiting for Jenkins

#9086 bug-fix/internal-issue-#549
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/ServerState.h
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  arangod/VocBase/Methods/UpgradeTasks.cpp
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchOrder-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/RestHandler/RestAnalyzerHandler-test.cpp
  tests/V8Server/v8-analyzers-test.cpp
Labels: 3 ArangoSearch, 9 WIP

#9151 Wait for replication before inserting documents
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/V8Server/v8-replication.cpp
  lib/Basics/Exceptions.h
  tests/Greylist.txt
  tests/js/server/resilience/repair/repair-distribute-shards-like-spec.js
Labels: 9 Ready to Merge

#8876 Reimplement ReturnExecutor with a simple pass-through
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/IdExecutor.cpp
  arangod/Aql/IdExecutor.h
  arangod/Aql/ReturnExecutor.cpp
  arangod/Aql/ReturnExecutor.h
  tests/Aql/ReturnExecutorTest.cpp
Labels: performance

#9017 Bug fix 3.3/supervision fixes4
  CHANGELOG
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Supervision.cpp
Labels: Team Clifton

#9016 Bug fix/supervision fixes4
  CHANGELOG
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Supervision.cpp
Labels: Team Clifton

#9153 [3.4] Wait for replication before inserting
  tests/Greylist.txt
  tests/js/server/resilience/repair/repair-distribute-shards-like-spec.js
Labels: 3 - Testing
