Repository arangodb/arangodb, pull requests merged in 2019-03, with the labels that each got.

#8149 Doc - Update Azure.md
  Documentation/Books/Manual/Deployment/Cloud/Azure.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#8293 Doc - Add missing deprecation note for traversal module
  Documentation/Books/Manual/Graphs/Traversals/UsingTraversalObjects.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#8234 Make coordinator short ID transient
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ServerState.cpp
Labels: 2 - Working

#8302 Documentation/add gdb requirements
  README_maintainers.md
Labels: 2 - Working

#8276 Fix Pregel nullptr checks
  CHANGELOG
  arangod/Pregel/PregelFeature.cpp
  arangod/V8Server/v8-collection.cpp
Labels: 2 - Working

#8279 issue 525.1: backport 3.4: ensure RocksDB CreateIndex/DropIndex WAL markers are properly written during recovery
  arangod/IResearch/IResearchRocksDBLink.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
Labels: 2 - Working

#8282 issue 525.1: ensure RocksDB CreateIndex/DropIndex WAL markers are properly written during recovery
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
Labels: 2 - Working

#8303 add default values and documentation missing for this parameter
  js/client/modules/@arangodb/testing.js
Labels: 2 - Working

#8305 fix test in active failover mode
  arangod/Cluster/HeartbeatThread.cpp
  arangod/RestServer/TtlFeature.cpp
  arangod/RestServer/TtlFeature.h
Labels: 2 - Working

#8229 Bug fix/small issues 21022019
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  arangod/RocksDBEngine/RocksDBIndex.h
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  tests/js/common/shell/shell-explain-cluster.js
  tests/js/common/shell/shell-explain-noncluster.js
  tests/js/server/aql/aql-optimizer-indexes-in-or.js
  tests/js/server/aql/aql-optimizer-indexes-sort.js
  tests/js/server/aql/aql-optimizer-indexes.js
  tests/js/server/aql/aql-optimizer-rule-distribute-in-cluster.js
  tests/js/server/aql/aql-queries-array-nested.js
  tests/js/server/aql/aql-sparse.js
Labels: 2 - Working

#8212 Prefetch in Filter Executor
  arangod/Aql/AllRowsFetcher.cpp
  arangod/Aql/AllRowsFetcher.h
  arangod/Aql/CalculationExecutor.h
  arangod/Aql/ConstFetcher.h
  arangod/Aql/ConstrainedSortExecutor.h
  arangod/Aql/CountCollectExecutor.h
  arangod/Aql/DistinctCollectExecutor.h
  arangod/Aql/EnumerateCollectionExecutor.h
  arangod/Aql/EnumerateListExecutor.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/FilterExecutor.h
  arangod/Aql/IdExecutor.h
  arangod/Aql/IndexExecutor.h
  arangod/Aql/LimitExecutor.h
  arangod/Aql/NoResultsExecutor.h
  arangod/Aql/ReturnExecutor.h
  arangod/Aql/ShortestPathExecutor.h
  arangod/Aql/SingleRowFetcher.cpp
  arangod/Aql/SingleRowFetcher.h
  arangod/Aql/SortExecutor.h
  arangod/Aql/TraversalExecutor.h
  tests/Aql/TestEmptyExecutorHelper.h
  tests/Aql/TestExecutorHelper.h
Labels: 1 Bug, 2 - Working

#8259 Further supervision fixes.
  CHANGELOG
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Agency/ActiveFailoverJob.h
  arangod/Agency/AddFollower.cpp
  arangod/Agency/AddFollower.h
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/CleanOutServer.h
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedFollower.h
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedLeader.h
  arangod/Agency/FailedServer.cpp
  arangod/Agency/FailedServer.h
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/JobContext.cpp
  arangod/Agency/JobContext.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/MoveShard.h
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/RemoveFollower.h
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Agency/State.cpp
  arangod/Agency/State.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/RestClusterHandler.cpp
  arangod/Cluster/RestClusterHandler.h
  js/actions/api-cluster.js
  lib/Rest/GeneralResponse.cpp
  tests/Agency/ActiveFailoverTest.cpp
  tests/Agency/AddFollowerTest.cpp
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/FailedFollowerTest.cpp
  tests/Agency/FailedLeaderTest.cpp
  tests/Agency/FailedServerTest.cpp
  tests/Agency/MoveShardTest.cpp
  tests/Agency/RemoveFollowerTest.cpp
  tests/js/server/resilience/moving-shards-cluster.js
  tests/js/server/resilience/moving-shards-with-arangosearch-view-grey-cluster.js
Labels: 1 Bug, 2 - Working, Team Clifton

#8309 always abort ongoing transactions
  CHANGELOG
  arangod/Replication/TailingSyncer.cpp
Labels: 2 - Working

#8307 fix test
  tests/js/server/shell/shell-readonly-mode-spec.js
Labels: 2 - Working

#8317 Doc - Update Kubernetes (Tutorial/Drain) (#8295)
  Documentation/Books/Manual/Deployment/Kubernetes/Drain.md
  Documentation/Books/Manual/Tutorials/Kubernetes/README.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8287 Doc - Rework AQL Data Types page
  Documentation/Books/AQL/Fundamentals/DataTypes.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8288 Doc - Rework AQL Data Types page (3.4)
  Documentation/Books/AQL/Fundamentals/DataTypes.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8316 Doc - Add missing deprecation note for traversal module (#8293)
  Documentation/Books/Manual/Graphs/Traversals/UsingTraversalObjects.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8315 Doc - Azure Deployment: Make statement clearer (#8149)
  Documentation/Books/Manual/Deployment/Cloud/Azure.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8314 [devel] supervision bug fix backports
  CHANGELOG
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Agency/ActiveFailoverJob.h
  arangod/Agency/AddFollower.cpp
  arangod/Agency/AddFollower.h
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/CleanOutServer.h
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedFollower.h
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedLeader.h
  arangod/Agency/FailedServer.cpp
  arangod/Agency/FailedServer.h
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/JobContext.cpp
  arangod/Agency/JobContext.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/MoveShard.h
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/RemoveFollower.h
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Agency/State.cpp
  arangod/Agency/State.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/RestClusterHandler.cpp
  arangod/Cluster/RestClusterHandler.h
  js/actions/api-cluster.js
  lib/Basics/StringUtils.h
  lib/Rest/GeneralResponse.cpp
  tests/Agency/ActiveFailoverTest.cpp
  tests/Agency/AddFollowerTest.cpp
  tests/Agency/AddFollowerTest.json
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/CleanOutServerTest.json
  tests/Agency/FailedFollowerTest.cpp
  tests/Agency/FailedLeaderTest.cpp
  tests/Agency/FailedLeaderTest.json
  tests/Agency/FailedServerTest.cpp
  tests/Agency/MoveShardTest.cpp
  tests/Agency/RemoveFollowerTest.cpp
  tests/js/server/resilience/moving-shards-cluster.js
  tests/js/server/resilience/moving-shards-with-arangosearch-view-grey-cluster.js
Labels: 1 Bug, 2 - Working, Team Clifton

#8306 when in activefailover mode detect leader changes, and abort tests
  js/client/modules/@arangodb/process-utils.js
Labels: 2 - Working

#8313 issue 520.1.1: decrease link commit interval to 1 second, add workaround for MMFiles not recovering document insertions via WAL
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/FlushFeature.h
  js/apps/system/_admin/aardvark/APP/api-docs.json
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchViewMeta-test.cpp
  tests/RestServer/FlushFeature-test.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
Labels: 2 - Working

#8318 backport some replication improvements from 3.4 and devel
  CHANGELOG
  arangod/Replication/ReplicationApplierState.cpp
  arangod/Replication/ReplicationTransaction.h
  arangod/Replication/Syncer.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/TailingSyncer.h
  arangod/RocksDBEngine/RocksDBWalAccess.cpp
  js/server/tests/replication/replication-ongoing.js
Labels: 2 - Working

#8323 [3.4] failed follower needs reporting aborts too
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/Supervision.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8324 oversight
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/Supervision.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8326 expect leader to have disappeared
  js/client/modules/@arangodb/process-utils.js
Labels: 2 - Working

#8319 issue 526.1: initial support for vocbase-prefixed analyzer names
  arangod/ClusterEngine/ClusterIndexFactory.cpp
  arangod/ClusterEngine/ClusterIndexFactory.h
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchAnalyzerFeature.h
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchLinkHelper.h
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/IResearchMMFilesLink.cpp
  arangod/IResearch/IResearchRocksDBLink.cpp
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewMeta.h
  arangod/Indexes/IndexFactory.cpp
  arangod/Indexes/IndexFactory.h
  arangod/MMFiles/MMFilesIndexFactory.cpp
  arangod/RestHandler/RestViewHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  arangod/RocksDBEngine/RocksDBIndexFactory.cpp
  arangod/V8Server/v8-views.cpp
  arangod/VocBase/LogicalView.cpp
  arangod/VocBase/LogicalView.h
  arangod/VocBase/Methods/Indexes.cpp
  tests/CMakeLists.txt
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchLinkMeta-test.cpp
  tests/IResearch/IResearchQueryTokens-test.cpp
  tests/IResearch/IResearchViewMeta-test.cpp
  tests/VocBase/LogicalView-test.cpp
Labels: 2 - Working

#8330 use the specified python interpreter here too
  3rdParty/V8/v7.1.302.28/gypfiles/standalone.gypi
  3rdParty/V8/v7.1.302.28/gypfiles/toolchain.gypi
  3rdParty/V8/v7.1.302.28/tools/gyp/pylib/gyp/generator/xcode.py
Labels: 2 - Working

#8327 add option `--console.history` to arangosh
  CHANGELOG
  Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
  arangod/RestHandler/RestVersionHandler.cpp
  arangosh/Shell/ConsoleFeature.cpp
  arangosh/Shell/ConsoleFeature.h
  arangosh/Shell/V8ClientConnection.cpp
  arangosh/Shell/V8ClientConnection.h
  arangosh/Shell/V8ShellFeature.cpp
  lib/Utilities/LinenoiseShell.cpp
  lib/Utilities/ShellBase.cpp
Labels: 2 - Working

#8328 added option `--console.history` to arangosh
  CHANGELOG
  Documentation/Books/Manual/ReleaseNotes/NewFeatures34.md
  arangod/RestHandler/RestVersionHandler.cpp
  arangosh/Shell/ConsoleFeature.cpp
  arangosh/Shell/ConsoleFeature.h
  arangosh/Shell/V8ClientConnection.cpp
  arangosh/Shell/V8ClientConnection.h
  arangosh/Shell/V8ShellFeature.cpp
  lib/Utilities/LinenoiseShell.cpp
  lib/Utilities/ShellBase.cpp
Labels: 2 - Working

#8333 fix an assertion failure when plans are shut down in an invalid state
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/Optimizer.cpp
Labels: 2 - Working

#8334 fix an assertion failure when plans are shut down in an invalid state
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/Optimizer.cpp
Labels: 2 - Working

#8339 Bug fix/allow creating foxx queues inside transactions
  arangod/V8Server/v8-dispatcher.cpp
  arangod/V8Server/v8-replication.cpp
  tests/js/server/shell/shell-foxx-queues.js
Labels: 2 - Working

#8342 where did the % go?
  3rdParty/V8/v7.1.302.28/tools/gyp/pylib/gyp/generator/xcode.py
Labels: 2 - Working

#8286 PRUNE in AQL Traversal
  CHANGELOG
  Documentation/Books/AQL/Graphs/Traversals.md
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/InAndOutRowExpressionContext.cpp
  arangod/Aql/InAndOutRowExpressionContext.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/PruneExpressionEvaluator.cpp
  arangod/Aql/PruneExpressionEvaluator.h
  arangod/Aql/TraversalBlock.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraversalNode.h
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.y
  arangod/CMakeLists.txt
  arangod/Graph/BaseOptions.h
  arangod/Graph/BreadthFirstEnumerator.cpp
  arangod/Graph/BreadthFirstEnumerator.h
  arangod/Graph/NeighborsEnumerator.cpp
  arangod/Graph/NeighborsEnumerator.h
  arangod/Graph/PathEnumerator.cpp
  arangod/Graph/PathEnumerator.h
  arangod/Graph/Traverser.cpp
  arangod/Graph/Traverser.h
  arangod/Graph/TraverserOptions.cpp
  arangod/Graph/TraverserOptions.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/server/aql/aql-graph-traverser.js
Labels: 1 Feature, 2 - Working

#8344 Bug fix 3.4/agency compaction overwrite
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Compactor.cpp
  arangod/Agency/State.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8345 [devel] clear compilation warnings
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Supervision.cpp
  arangod/Aql/ShortestPathExecutor.h
  arangod/GeneralServer/SocketUnixDomain.h
  arangod/Replication/TailingSyncer.cpp
  arangod/Scheduler/SupervisedScheduler.h
  tests/IResearch/IResearchFeature-test.cpp
Labels: 2 - Working

#8331 [3.3] fix agency compaction index mismatch insertion bug
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Compactor.cpp
  arangod/Agency/State.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8348 [devel] fix compaction behaviour of followers
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Compactor.cpp
  arangod/Agency/State.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8350 remove some unused stuff
  arangod/Cluster/HeartbeatThread.cpp
  arangod/MMFiles/MMFilesPrimaryIndex.cpp
  lib/Basics/AssocMulti.h
  lib/Basics/AssocMultiHelpers.h
  lib/Basics/AssocUnique.h
  lib/Basics/AssocUniqueHelpers.h
  lib/Basics/IndexBucket.h
Labels: 2 - Working

#8351 document `includeFoxxQueues` attribute and persist it
  Documentation/Books/Manual/Administration/MasterSlave/DatabaseSetup.md
  Documentation/Books/Manual/Administration/MasterSlave/ReplicationApplier.md
  Documentation/Books/Manual/Administration/MasterSlave/ServerLevelSetup.md
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/GlobalInitialSyncer.cpp
  arangod/Replication/ReplicationApplierConfiguration.cpp
  arangod/Replication/ReplicationApplierConfiguration.h
  js/server/server.js
Labels: 2 - Working

#8304 Bug fix/prune neighbors and explain
  arangod/Graph/NeighborsEnumerator.cpp
  js/common/modules/@arangodb/aql/explainer.js
Labels: 2 - Working

#8353 make geo-index-optimizer rule work with multiple loops
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-geoindex.js
Labels: 2 - Working

#8352 code now fits to the documentation of the arangoUser object inside th…
  js/server/modules/@arangodb/foxx/router/request.js
  tests/js/client/authentication/foxx-arango-auth-spec.js
Labels: 2 - Working, 9 Review Required

#8300 various replication improvements
  CHANGELOG
  Documentation/Books/Manual/Architecture/DeploymentModes/MasterSlave/Architecture.md
  Documentation/Books/Manual/Programs/Arangod/Rocksdb.md
  arangod/Cluster/HeartbeatThread.cpp
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/MMFiles/MMFilesWalAccess.cpp
  arangod/MMFiles/MMFilesWalAccess.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/DatabaseTailingSyncer.cpp
  arangod/Replication/ReplicationApplier.cpp
  arangod/Replication/ReplicationApplier.h
  arangod/Replication/ReplicationApplierState.cpp
  arangod/Replication/ReplicationApplierState.h
  arangod/Replication/Syncer.cpp
  arangod/Replication/Syncer.h
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/TailingSyncer.h
  arangod/Replication/common-defines.cpp
  arangod/Replication/common-defines.h
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBWalAccess.cpp
  arangod/RocksDBEngine/RocksDBWalAccess.h
  arangod/StorageEngine/WalAccess.h
  tests/js/common/replication/replication.js
  tests/js/server/replication/replication-fuzz-global.js
  tests/js/server/replication/replication-fuzz.js
  tests/js/server/replication/replication-ongoing-global.js
  tests/js/server/replication/replication-ongoing.js
  tests/rb/HttpReplication/api-replication-global-spec.rb
Labels: 2 - Working

#8308 port of replication improvements from 3.4
  Documentation/Books/Manual/Architecture/DeploymentModes/MasterSlave/Architecture.md
  Documentation/Books/Manual/Programs/Arangod/Rocksdb.md
  arangod/Aql/SortExecutor.cpp
  arangod/Aql/SortRegister.h
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/MMFiles/MMFilesWalAccess.cpp
  arangod/MMFiles/MMFilesWalAccess.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/DatabaseReplicationApplier.cpp
  arangod/Replication/DatabaseTailingSyncer.cpp
  arangod/Replication/ReplicationApplier.cpp
  arangod/Replication/ReplicationApplier.h
  arangod/Replication/ReplicationApplierState.cpp
  arangod/Replication/ReplicationApplierState.h
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/Syncer.cpp
  arangod/Replication/Syncer.h
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/TailingSyncer.h
  arangod/Replication/common-defines.cpp
  arangod/Replication/common-defines.h
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBWalAccess.cpp
  arangod/RocksDBEngine/RocksDBWalAccess.h
  arangod/StorageEngine/WalAccess.h
  tests/js/common/replication/replication.js
  tests/js/server/replication/replication-fuzz-global.js
  tests/js/server/replication/replication-fuzz.js
  tests/js/server/replication/replication-ongoing-global-spec.js
  tests/js/server/replication/replication-ongoing-global.js
  tests/js/server/replication/replication-ongoing.js
  tests/rb/HttpReplication/api-replication-global-spec.rb
Labels: 2 - Working

#8367 simplify internal struct for edge index lookups
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
Labels: 2 - Working

#8372 Doc - Fix ReplicationApplier.md hint box
  Documentation/Books/Manual/Administration/MasterSlave/DatabaseSetup.md
  Documentation/Books/Manual/Administration/MasterSlave/ReplicationApplier.md
  Documentation/Books/Manual/Administration/MasterSlave/ServerLevelSetup.md
Labels: 2 - Working

#8371 issue 527.1: ensure the cause of the failure is reported to the user
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 2 - Working

#8356 [3.4] Agency Failed leader crash
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
Labels: 2 - Working

#8322 [3.3] supervision fixes backported from 3.4
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Agency/ActiveFailoverJob.h
  arangod/Agency/AddFollower.cpp
  arangod/Agency/AddFollower.h
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/CleanOutServer.h
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedFollower.h
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedLeader.h
  arangod/Agency/FailedServer.cpp
  arangod/Agency/FailedServer.h
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/JobContext.cpp
  arangod/Agency/JobContext.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/MoveShard.h
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/RemoveFollower.h
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Agency/State.cpp
  arangod/Agency/State.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/RestClusterHandler.cpp
  arangod/Cluster/RestClusterHandler.h
  js/actions/api-cluster.js
  lib/Basics/StringUtils.h
  lib/Rest/GeneralResponse.cpp
  tests/Agency/ActiveFailoverTest.cpp
  tests/Agency/AddFollowerTest.cpp
  tests/Agency/AddFollowerTest.json
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/CleanOutServerTest.json
  tests/Agency/FailedFollowerTest.cpp
  tests/Agency/FailedLeaderTest.cpp
  tests/Agency/FailedLeaderTest.json
  tests/Agency/FailedServerTest.cpp
  tests/Agency/MoveShardTest.cpp
  tests/Agency/RemoveFollowerTest.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8375 fix connection shutdown in arangosh
  arangosh/Shell/V8ClientConnection.cpp
  arangosh/Shell/V8ClientConnection.h
  tests/rb/HttpReplication/api-replication-global-spec.rb
Labels: 2 - Working

#8374 fix connection shutdown in arangosh
  arangosh/Shell/V8ClientConnection.cpp
  arangosh/Shell/V8ClientConnection.h
  tests/rb/HttpReplication/api-replication-global-spec.rb
Labels: 2 - Working

#8244 BugFix 3.3: Correct RocksDB NowNano() for overflow
  3rdParty/rocksdb/v5.6.X/port/win/env_win.cc
Labels: 2 - Working

#8377 Some more agency fixes.
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/Supervision.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  tests/Agency/RemoveFollowerTest.cpp
  tests/Agency/RemoveFollowerTest.json
Labels: 2 - Working

#8382 Various agency fixes.
  CHANGELOG
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/Supervision.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  tests/Agency/RemoveFollowerTest.cpp
  tests/Agency/RemoveFollowerTest.json
Labels: 2 - Working

#8383 Port agency crash fixes to 3.3.
  CHANGELOG
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
Labels: 2 - Working

#8381 Fix an agency crash.
  CHANGELOG
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
Labels: 2 - Working

#8380 Various agency improvements.
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/Supervision.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  tests/Agency/RemoveFollowerTest.cpp
  tests/Agency/RemoveFollowerTest.json
Labels: 2 - Working

#8364 try an incremental sync when restarting a follower in active failover…
  CHANGELOG
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/GlobalInitialSyncer.cpp
  js/server/server.js
Labels: 2 - Working

#8320 Feature-3.4: Hotbackup restore supporting Max new restartAction.
  arangod/RestHandler/RestHotBackupHandler.cpp
  arangod/RocksDBEngine/RocksDBHotBackup.cpp
  arangod/RocksDBEngine/RocksDBHotBackup.h
  tests/RocksDBEngine/HotBackupTest.cpp
Labels: 2 - Working

#8311 Feature-3.4: Hot backup rest handler for community edition
  arangod/CMakeLists.txt
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/RestHandler/RestHotBackupHandler.cpp
  arangod/RestHandler/RestHotBackupHandler.h
  arangod/RocksDBEngine/CMakeLists.txt
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBEventListener.cpp
  arangod/RocksDBEngine/RocksDBEventListener.h
  arangod/RocksDBEngine/RocksDBHotBackup.cpp
  arangod/RocksDBEngine/RocksDBHotBackup.h
  arangod/RocksDBEngine/RocksDBHotBackupCoord.h
  js/common/bootstrap/errors.js
  lib/Basics/FileUtils.cpp
  lib/Basics/FileUtils.h
  lib/Basics/errors.dat
  lib/Basics/files.cpp
  lib/Basics/files.h
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  tests/Basics/files-test.cpp
  tests/CMakeLists.txt
  tests/Maintenance/MaintenanceFeatureTest.cpp
  tests/Maintenance/MaintenanceRestHandlerTest.cpp
  tests/RocksDBEngine/HotBackupTest.cpp
  tests/RocksDBEngine/ShaEventListener.cpp
Labels: 2 - Working

#8379 Doc - AQL UDFs: Manage on coordinator, improve warning (#8340)
  Documentation/Books/AQL/Extending/Functions.md
  Documentation/Books/AQL/Extending/README.md
Labels: 2 - Working, 3 Documentation

#8242 Doc - Add cross-refs & better AQL function descriptions
  Documentation/Books/AQL/Functions/Array.md
  Documentation/Books/AQL/Functions/Document.md
  Documentation/Books/AQL/Functions/Miscellaneous.md
  Documentation/Books/AQL/Functions/Numeric.md
  Documentation/Books/AQL/Functions/String.md
  Documentation/Books/AQL/Functions/TypeCast.md
  Documentation/Books/AQL/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#7730 Doc - EOL Note for 3.2
  Documentation/Books/AQL/book.json
  Documentation/Books/Cookbook/book.json
  Documentation/Books/HTTP/book.json
  Documentation/Books/Manual/book.json
Labels: 2 - Working, 3 Documentation

#8393 avoid a few dynamic memory allocations in the optimizer
  arangod/Aql/ConditionFinder.cpp
  arangod/Aql/OptimizerRules.cpp
Labels: 2 - Working

#8401 supervision must check for leadership, when waiting for progess
  arangod/Agency/Supervision.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8397 emit a warning when connecting with the client tools to a DBSERVER
  CHANGELOG
  Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
  arangosh/Dump/DumpFeature.cpp
  arangosh/Import/ImportFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Shell/V8ShellFeature.cpp
  arangosh/Utils/ClientManager.cpp
  arangosh/Utils/ClientManager.h
Labels: 2 - Working

#8403 Supervision must not waitfor if no longer leading
  arangod/Agency/Supervision.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8360 make geo-index-optimizer rule work with multiple loops (#8353)
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-geoindex.js
Labels: 2 - Working

#8395 Doc - Add cross-refs & better AQL function descriptions (#8242)
  Documentation/Books/AQL/Functions/Array.md
  Documentation/Books/AQL/Functions/Document.md
  Documentation/Books/AQL/Functions/Miscellaneous.md
  Documentation/Books/AQL/Functions/Numeric.md
  Documentation/Books/AQL/Functions/String.md
  Documentation/Books/AQL/Functions/TypeCast.md
  Documentation/Books/AQL/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#8399 use requireFromPresent and barriers in more cases
  js/client/modules/@arangodb/testsuites/replication.js
  tests/js/server/replication/replication-aql.js
  tests/js/server/replication/replication-fuzz.js
  tests/js/server/replication/replication-ongoing-global.js
  tests/js/server/replication/replication-ongoing.js
  tests/js/server/replication/replication-random.js
  tests/js/server/replication/replication-static.js
Labels: 2 - Working

#8402 fix test
  arangod/Cluster/ClusterEdgeCursor.cpp
  arangod/Cluster/ClusterEdgeCursor.h
  arangod/Graph/EdgeCursor.h
  arangod/Graph/SingleServerEdgeCursor.cpp
  arangod/Graph/SingleServerEdgeCursor.h
  arangod/Indexes/IndexIterator.cpp
  arangod/Indexes/IndexIterator.h
  arangod/Pregel/GraphStore.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/Utils/OperationCursor.h
Labels: 2 - Working

#8409 Doc - Set EoL date for 3.2
  Documentation/Books/AQL/book.json
  Documentation/Books/Cookbook/book.json
  Documentation/Books/HTTP/book.json
  Documentation/Books/Manual/book.json
Labels: 2 - Working, 3 Documentation

#8370 Named indices
  CHANGELOG
  Documentation/Books/Drivers/JS/Reference/Collection/Indexes.md
  Documentation/Books/Manual/Indexing/WorkingWithIndexes.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges35.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index.md
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndexFactory.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/Indexes/IndexFactory.cpp
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesEdgeIndex.cpp
  arangod/MMFiles/MMFilesIndex.h
  arangod/MMFiles/MMFilesPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.h
  arangod/RocksDBEngine/RocksDBIndexFactory.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/StorageEngine/PhysicalCollection.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Indexes.cpp
  arangod/VocBase/Methods/Upgrade.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  arangod/VocBase/Methods/UpgradeTasks.h
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/indicesView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
  js/client/modules/@arangodb/arango-collection.js
  js/server/modules/@arangodb/arango-collection.js
  js/server/modules/@arangodb/arango-database.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Mocks/StorageEngineMock.cpp
  tests/js/common/shell/shell-index-ensure.js
  tests/js/common/shell/shell-index.js
Labels: 2 - Working

#8405 Doc - Sync external repos 2019-03-13 (devel)
  Documentation/Books/Drivers/JS/Reference/Collection/DocumentCollection.md
  Documentation/Books/Drivers/JS/Reference/Collection/EdgeCollection.md
  Documentation/Books/Drivers/SparkConnector/Reference/Java.md
  Documentation/Books/Manual/Programs/Starter/Options.md
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Tutorials/Kubernetes/EKS.md
Labels: 2 - Working, 3 Documentation

#8415 Doc - Sync external repos 2019-03-13 (3.4)
  Documentation/Books/Drivers/JS/Reference/Collection/DocumentCollection.md
  Documentation/Books/Drivers/JS/Reference/Collection/EdgeCollection.md
  Documentation/Books/Drivers/SparkConnector/Reference/Java.md
  Documentation/Books/Manual/Programs/Starter/Options.md
  Documentation/Books/Manual/Tutorials/Kubernetes/EKS.md
Labels: 2 - Working, 3 Documentation

#8400 Doc - Add some known issues
  Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
Labels: 2 - Working, 3 Documentation

#8416 Doc - Add v3.4 Active Failover known issues (#8400)
  Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
Labels: 2 - Working, 3 Documentation

#8418 remove log compaction test in agency from main line. test needs fixing.
  tests/js/client/agency/agency-test.js
Labels: 2 - Working, Team Clifton

#8410 expose ARANGODB_USE_CATCH_TESTS define, make TEST_VIRTUAL be based on it
  CMakeLists.txt
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/FlushFeature.h
  lib/Basics/Common.h
Labels: 2 - Working

#8420 when filtering for tests and matching nothing output the non matching tests
  js/common/modules/jsunity.js
Labels: 2 - Working

#8404 When updating documents with array indices and unique values we mustn't disable indexing in rocksdb
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBMethods.cpp
  arangod/RocksDBEngine/RocksDBMethods.h
  tests/js/common/shell/shell-index-ensure.js
Labels: 2 - Working

#8423 [devel] log compaction excluded for now
  tests/js/client/agency/agency-test.js
Labels: 3 - Testing, Team Clifton

#8422 Bug fix 3.4/arrayindex unique update
  CHANGELOG
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBMethods.cpp
  arangod/RocksDBEngine/RocksDBMethods.h
  tests/js/common/shell/shell-index-ensure.js
Labels: 2 - Working

#8349 Aql by line mixed fixes
  arangod/Aql/AqlResult.h
  arangod/Aql/CountCollectExecutor.cpp
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/EnumerateListExecutor.cpp
  arangod/Aql/EnumerateListExecutor.h
  arangod/Aql/ExecutorInfos.cpp
  arangod/Aql/FilterExecutor.cpp
  arangod/Aql/IdExecutor.cpp
  arangod/Aql/InAndOutRowExpressionContext.cpp
  arangod/Aql/InAndOutRowExpressionContext.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  arangod/Aql/InputAqlItemRow.h
  arangod/Aql/LimitExecutor.cpp
  arangod/Aql/PruneExpressionEvaluator.h
  arangod/Aql/ReturnExecutor.h
  arangod/Aql/ShortestPathExecutor.cpp
  arangod/Aql/ShortestPathExecutor.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/SortExecutor.cpp
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalExecutor.h
  arangod/Graph/BreadthFirstEnumerator.cpp
  arangod/Graph/BreadthFirstEnumerator.h
  arangod/Graph/PathEnumerator.cpp
  arangod/Graph/PathEnumerator.h
Labels: 2 - Working

#8223 fixed some escpaing issues, removed dead code, eslint
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocument.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/nodeInfoView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsItemView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/nodeInfoView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/replicationView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userPermissions.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
Labels: 2 - Working, 9 Review Required

#8385 StorageEngineMock: Prevent deadlock
  tests/Mocks/StorageEngineMock.cpp
Labels: 2 - Working, 9 Review Required, 9 Waiting for Jenkins

#8428 [3.4] bug-fix/internal-issue-#528
  3rdParty/iresearch/core/formats/formats_burst_trie.cpp
Labels: 2 - Working

#8426 Add Catch tests for ConstantWeightShortestPathFinder
  tests/CMakeLists.txt
  tests/Graph/ConstantWeightShortestPathFinder.cpp
Labels: 1 Feature, 2 - Working, 9 Review Required

#8435 [devel] also compaction step size test grey listed
  tests/js/client/agency/agency-test.js
Labels: 3 - Testing, Team Clifton

#8434 [3.4] also compaction step size test grey listed
  tests/js/client/agency/agency-test.js
Labels: 3 - Testing, Team Clifton

#8442 abort testing if we fail to get the currently available collections during server startup
  js/client/modules/@arangodb/test-utils.js
Labels: 2 - Working

#8394 arangodump & arangorestore all databases
  CHANGELOG
  Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
  arangosh/Dump/DumpFeature.cpp
  arangosh/Dump/DumpFeature.h
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Restore/RestoreFeature.h
Labels: 2 - Working

#8432 fix some memleaks
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlItemBlock.h
  arangod/Aql/AqlItemBlockShell.h
  arangod/Aql/BlockFetcher.cpp
  arangod/Aql/DistinctCollectExecutor.cpp
  arangod/Aql/DistinctCollectExecutor.h
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutorExpressionContext.h
  arangod/Aql/FilterExecutor.cpp
  arangod/Aql/FilterExecutor.h
  arangod/Aql/InputAqlItemRow.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
  arangod/Aql/ShortestPathExecutor.cpp
  arangod/Graph/Traverser.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
Labels: 2 - Working

#8443 revert a previous change that caused existing system collections on a…
  arangod/Replication/DatabaseInitialSyncer.cpp
Labels: 2 - Working

#8417 issue 526.2.1: add upgrade step for legacy static analyzers
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/DropCollection.cpp
  arangod/Cluster/UpdateCollection.cpp
  arangod/Graph/GraphManager.cpp
  arangod/Graph/GraphOperations.cpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchAnalyzerFeature.h
  arangod/IResearch/IResearchView.h
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/Statistics/StatisticsWorker.cpp
  arangod/V8Server/v8-collection.cpp
  arangod/V8Server/v8-vocindex.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  arangod/VocBase/Methods/UpgradeTasks.cpp
  tests/CMakeLists.txt
  tests/IResearch/ClusterCommMock.cpp
  tests/IResearch/ClusterCommMock.h
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchLinkMeta-test.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/IResearch/IResearchQueryTokens-test.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/js/server/shell/shell-collection-properties-cluster-spec.js
Labels: 2 - Working

#8449 added options log.file-mode and log.file-group
  CHANGELOG
  Documentation/Books/Manual/Programs/Arangod/Log.md
  lib/Logger/LogAppenderFile.cpp
  lib/Logger/LogAppenderFile.h
  lib/Logger/LoggerFeature.cpp
  lib/Logger/LoggerFeature.h
Labels: 2 - Working

#8431 Index hints
  CHANGELOG
  Documentation/Books/AQL/Operations/For.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
  arangod/Aql/Condition.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/IndexHint.cpp
  arangod/Aql/IndexHint.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesReplaceFunctions.cpp
  arangod/CMakeLists.txt
  arangod/Cluster/ClusterMethods.cpp
  arangod/Graph/BaseOptions.cpp
  arangod/Graph/EdgeCollectionInfo.cpp
  arangod/RestHandler/RestEdgesHandler.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  js/common/bootstrap/errors.js
  js/common/modules/@arangodb/aql/explainer.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  tests/js/server/aql/aql-index-hints.js
Labels: 2 - Working

#8455 Rebuild frontend after XSS fixes
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/src/ace.min.js
Labels: 1 Bug, 3 UI

#8447 Rebuild frontend (3.4) after XSS fixes
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
Labels: 1 Bug, 3 UI

#8454 Rebuild frontend (3.3) after XSS fixes
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/extra-minified.css
  js/apps/system/_admin/aardvark/APP/frontend/build/extra-minified.css.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/style-minified.css
  js/apps/system/_admin/aardvark/APP/frontend/build/style-minified.css.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
Labels: 1 Bug, 2 - Working, 3 UI

#8433 micro improvements for rocksdb options
  CHANGELOG
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges35.md
  arangod/RocksDBEngine/RocksDBEngine.cpp
  lib/ApplicationFeatures/ApplicationServer.h
  lib/ApplicationFeatures/RocksDBOptionFeature.cpp
Labels: 2 - Working

#8463 Doc - Fix Client Tools section in NewFeatures35.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#8462 Doc - Make cleanOutServer step mandatory in drain documentation
  Documentation/Books/Manual/Administration/Cluster/README.md
  Documentation/Books/Manual/Deployment/Kubernetes/Drain.md
  Documentation/DocuBlocks/Rest/Cluster/get_cluster_health.md
Labels: 2 - Working, 3 Documentation

#8461 Doc - Add log level description under Monitoring
  Documentation/Books/Manual/Monitoring/LogLevels.md
  Documentation/Books/Manual/Monitoring/README.md
  Documentation/Books/Manual/Programs/Arangod/Log.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#8465 Add log level description under Monitoring (#8461)
  Documentation/Books/Manual/Monitoring/LogLevels.md
  Documentation/Books/Manual/Monitoring/README.md
  Documentation/Books/Manual/Programs/Arangod/Log.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#8207 Add testTemplateStringBuilderEmptyInlines test for https://github.com/arangodb/arangodb/pull/8142
  tests/js/common/shell/shell-statement.js
Labels: 3 - Testing

#8460 Fix upgrade_data tests (3.4)
  js/client/modules/@arangodb/testsuites/upgrade-data.js
Labels: 1 Bug, 3 - Testing

#8459 Fix upgrade_data tests
  js/client/modules/@arangodb/testsuites/upgrade-data.js
Labels: 1 Bug, 3 - Testing

#8467 Fix crash in test for ConstantWeightShortestPathFinder
  tests/Graph/ConstantWeightShortestPathFinder.cpp
Labels: 2 - Working, 9 Review Required, 9 Waiting for Jenkins

#8439 agency compaction tests unreliable
  js/client/tests/agency/agency-test.js
Labels: 3 - Testing, Team Clifton

#8466 Doc - Make cleanOutServer step mandatory in drain documentation (#8462)
  Documentation/Books/Manual/Administration/Cluster/README.md
  Documentation/Books/Manual/Deployment/Kubernetes/Drain.md
  Documentation/DocuBlocks/Rest/Cluster/get_cluster_health.md
Labels: 2 - Working, 3 Documentation

#8343 [3.4] address compile warnings
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Supervision.cpp
Labels: 2 - Working

#8444 [3.4] leader check needs to sit inside waitfor loop
  CHANGELOG
  arangod/Agency/Supervision.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8446 [3.3] followers can get stuck in supervision runs
  CHANGELOG
  arangod/Agency/Supervision.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8292 Implement ScatterExecutor and DistributeExecutor
  arangod/Aql/ClusterBlocks.cpp
  arangod/Aql/ClusterBlocks.h
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ClusterNodes.h
  arangod/Aql/DistributeExecutor.cpp
  arangod/Aql/DistributeExecutor.h
  arangod/Aql/RemoteExecutor.h
  arangod/Aql/ScatterExecutor.cpp
  arangod/Aql/ScatterExecutor.h
  arangod/CMakeLists.txt
Labels: 2 - Working

#7976 Bug fix/jwt secret file logging
  arangod/GeneralServer/AuthenticationFeature.cpp
Labels: 2 - Working

#8357 Abort the process if a stopped thread does not terminate within 5min.
  lib/Basics/Thread.cpp
  lib/Basics/Thread.h
  lib/Basics/threads-posix.cpp
  lib/Basics/threads-posix.h
  lib/Basics/threads-win32.cpp
  lib/Basics/threads.h
Labels: 2 - Working

#8450 added --log.file-mode and --log.file-group
  Documentation/Books/Manual/Programs/Arangod/Log.md
  lib/Logger/LogAppenderFile.cpp
  lib/Logger/LogAppenderFile.h
  lib/Logger/LoggerFeature.cpp
  lib/Logger/LoggerFeature.h
Labels: 2 - Working

#8480 Initialize alternativeRegId
  arangod/Aql/ClusterNodes.cpp
Labels: 1 Bug, 2 - Working

#8473 Add bucket number info to testfailures output (3.4)
  js/client/modules/@arangodb/testing.js
  tests/OskarTestSuitesBlackList
Labels: 3 - Testing

#8206 Add testTemplateStringBuilderEmptyInlines test for https://github.com/arangodb/arangodb/pull/8141
  tests/js/common/shell/shell-statement.js
Labels: 3 - Testing

#8470 Add bucket number info to testfailures output
  js/client/modules/@arangodb/testing.js
Labels: 3 - Testing

#8468 don't run compact() on a collection after a truncate() was done in th…
  Documentation/Books/Manual/Appendix/References/CollectionObject.md
  Documentation/Books/Manual/DataModeling/Collections/CollectionMethods.md
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  js/client/modules/@arangodb/arango-collection.js
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
Labels: 2 - Working

#8445 leader check needs to sit inside waitfor loop
  CHANGELOG
  arangod/Agency/Supervision.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8482 Doc - Re-add EE options, new log file options (3.4)
  Documentation/Examples/arangobench.json
  Documentation/Examples/arangod.json
  Documentation/Examples/arangodump.json
  Documentation/Examples/arangoexport.json
  Documentation/Examples/arangoimport.json
  Documentation/Examples/arangoinspect.json
  Documentation/Examples/arangorestore.json
  Documentation/Examples/arangosh.json
  Documentation/Examples/listCurrentConfigOpts.generated
Labels: 2 - Working, 3 Documentation

#8476 don't attempt to remove non-existing WAL files, because such attempt …
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 2 - Working

#8406 [3.4] job must not copy snapshots
  CHANGELOG
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/Supervision.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8425 supervision must not copy snapshots into jobs
  CHANGELOG
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/Supervision.cpp
  tests/js/client/agency/agency-test.js
Labels: 2 - Working

#8483 Deblacklist ldap tests
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#8471 don't run compact() on a collection after a truncate() was done in th…
  CHANGELOG
  Documentation/Books/Manual/Appendix/References/CollectionObject.md
  Documentation/Books/Manual/DataModeling/Collections/CollectionMethods.md
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesCollection.h
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  js/client/modules/@arangodb/arango-collection.js
  tests/IResearch/StorageEngineMock.cpp
  tests/IResearch/StorageEngineMock.h
Labels: 2 - Working

#8475 don't attempt to remove non-existing WAL files, because such attempt …
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 2 - Working

#8474 dont attempt to remove non-existing WAL files
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 2 - Working

#8337 Feature/aql hashed collect
  arangod/Aql/CollectBlock.cpp
  arangod/Aql/CollectNode.cpp
  arangod/Aql/CollectNode.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/HashedCollectExecutor.cpp
  arangod/Aql/HashedCollectExecutor.h
  arangod/CMakeLists.txt
  tests/Aql/HashedCollectExecutorTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-failures-noncluster.js
  tests/js/server/aql/aql-profiler.js
Labels: 2 - Working, 9 Review Required, 9 WIP

#8479 [3.3] job must not copy snapshots
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/Supervision.cpp
Labels: 2 - Working

#8478 [devel]agency appends entries with leaders timestamp
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/State.cpp
  arangod/Agency/State.h
Labels: 1 Feature, 2 - Working, Team Clifton

#8484 some very small optimizations
  arangod/Aql/AqlTransaction.cpp
  arangod/Aql/AqlTransaction.h
  arangod/Aql/GraphNode.cpp
  arangod/Cluster/TraverserEngine.cpp
  arangod/Utils/CollectionNameResolver.h
Labels: 2 - Working

#8464 Doc - Dump program options only if on Enterprise Edition
  utils/generateExamples.sh
Labels: 2 - Working, 3 Documentation, 9 Review Required

#8492 add RocksDB options `--rocksdb.allow-fallocate` and `--rocksdb.limit-…
  CHANGELOG
  Documentation/Books/Manual/Programs/Arangod/Rocksdb.md
  arangod/RocksDBEngine/RocksDBEngine.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.h
Labels: 2 - Working

#8452 issue 526.3: update analyzer feature to store analyzer definitions in per-vocbase system collections
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchAnalyzerFeature.h
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchLinkCoordinator.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchLinkHelper.h
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/IResearchMMFilesLink.cpp
  arangod/IResearch/IResearchMMFilesLink.h
  arangod/IResearch/IResearchRocksDBLink.cpp
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewOptimizerRules.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/VocBase/Methods/Upgrade.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  arangod/VocBase/Methods/UpgradeTasks.h
  tests/IResearch/ExecutionBlockMock-test.cpp
  tests/IResearch/ExpressionFilter-test.cpp
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchDocument-test.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchFilter-test.cpp
  tests/IResearch/IResearchFilterBoolean-test.cpp
  tests/IResearch/IResearchFilterCompare-test.cpp
  tests/IResearch/IResearchFilterFunction-test.cpp
  tests/IResearch/IResearchFilterIn-test.cpp
  tests/IResearch/IResearchIndex-test.cpp
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchLinkHelper-test.cpp
  tests/IResearch/IResearchLinkMeta-test.cpp
  tests/IResearch/IResearchQuery-test.cpp
  tests/IResearch/IResearchQueryAggregate-test.cpp
  tests/IResearch/IResearchQueryAnd-test.cpp
  tests/IResearch/IResearchQueryBooleanTerm-test.cpp
  tests/IResearch/IResearchQueryComplexBoolean-test.cpp
  tests/IResearch/IResearchQueryExists-test.cpp
  tests/IResearch/IResearchQueryIn-test.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/IResearch/IResearchQueryNullTerm-test.cpp
  tests/IResearch/IResearchQueryNumericTerm-test.cpp
  tests/IResearch/IResearchQueryOptions-test.cpp
  tests/IResearch/IResearchQueryOr-test.cpp
  tests/IResearch/IResearchQueryPhrase-test.cpp
  tests/IResearch/IResearchQueryScorer-test.cpp
  tests/IResearch/IResearchQuerySelectAll-test.cpp
  tests/IResearch/IResearchQueryStartsWith-test.cpp
  tests/IResearch/IResearchQueryStringTerm-test.cpp
  tests/IResearch/IResearchQueryTokens-test.cpp
  tests/IResearch/IResearchQueryTraversal-test.cpp
  tests/IResearch/IResearchQueryValue-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
Labels: 2 - Working

#8504 Doc - Dump program options only if on Enterprise Edition (3.4)
  utils/generateExamples.sh
Labels: 3 Documentation

#8495 don't check for version upgrades in enterprise edition when firing up…
  js/common/modules/@arangodb/common.js
Labels: 2 - Working

#8493 add RocksDB options `--rocksdb.allow-fallocate` and `--rocksdb.limit-…
  Documentation/Books/Manual/Programs/Arangod/Rocksdb.md
  arangod/RocksDBEngine/RocksDBEngine.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.h
Labels: 2 - Working

#8246 3.3: Add rocksdb clock fix to known issues
  Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
Labels: 2 - Working, 3 Documentation

#8441 Feature 3.4/ncc1701
  3rdParty/velocypack/include/velocypack/StringRef.h
  Documentation/Books/Manual/DataModeling/Collections/DatabaseMethods.md
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Satellites.md
  Documentation/Books/Manual/SmartJoins.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  arangod/Aql/Collection.cpp
  arangod/Aql/Collection.h
  arangod/Aql/CollectionAccessingNode.cpp
  arangod/Aql/CollectionAccessingNode.h
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Upgrade.cpp
  etc/jenkins/arangod-common.conf
  etc/testing/arangod-common.conf
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoCollections.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalCollectionInfo.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/client/modules/@arangodb/arango-collection.js
  js/client/modules/@arangodb/arango-database.js
  js/common/bootstrap/errors.js
  js/common/modules/@arangodb/aql/explainer.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
Labels: 2 - Working

#8496 don't check for version upgrades in enterprise edition when firing up…
  CHANGELOG
  js/common/modules/@arangodb/common.js
Labels: 2 - Working

#8131 Feature 3.4/coordinator do full agency dumps
  CHANGELOG
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Agency/State.cpp
  arangod/Cluster/RestClusterHandler.cpp
Labels: 1 Feature, 2 - Working

#8497 attempt to make replication fuzz tests more stable
  tests/js/server/replication/replication-aql.js
  tests/js/server/replication/replication-fuzz-global.js
  tests/js/server/replication/replication-fuzz.js
  tests/js/server/replication/replication-ongoing-frompresent-32.js
  tests/js/server/replication/replication-ongoing-frompresent.js
  tests/js/server/replication/replication-ongoing-global.js
  tests/js/server/replication/replication-ongoing.js
  tests/js/server/replication/replication-random.js
Labels: 2 - Working

#8440 Feature/ncc1701
  Documentation/Books/Manual/DataModeling/Collections/DatabaseMethods.md
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Satellites.md
  Documentation/Books/Manual/SmartJoins.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  arangod/Aql/Collection.cpp
  arangod/Aql/Collection.h
  arangod/Aql/CollectionAccessingNode.cpp
  arangod/Aql/CollectionAccessingNode.h
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Upgrade.cpp
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoCollections.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalCollectionInfo.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/client/modules/@arangodb/arango-collection.js
  js/client/modules/@arangodb/arango-database.js
  js/common/bootstrap/errors.js
  js/common/modules/@arangodb/aql/explainer.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
Labels: 2 - Working
