Repository arangodb/arangodb, pull requests merged in 2019-11, with the labels that each got.

#10347 bug-fix/internal-issue-#652
  arangod/Aql/QueryString.h
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchAnalyzerFeature.h
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
Labels: 9 WIP

#10355 always create `_analyzers` collection if missing
  arangod/CMakeLists.txt
  arangod/IResearch/IResearchAnalyzerCollectionFeature.cpp
  arangod/IResearch/IResearchAnalyzerCollectionFeature.h
  arangod/RestServer/arangod.cpp
Labels: 1 Bug, 3 ArangoSearch, 9 Ready to Merge

#10356 Bug fix 3.5/always create analyzers collection 35
  arangod/CMakeLists.txt
  arangod/IResearch/IResearchAnalyzerCollectionFeature.cpp
  arangod/IResearch/IResearchAnalyzerCollectionFeature.h
  arangod/RestServer/arangod.cpp
Labels: 9 Ready to Merge

#10354 Bug fix 3.5/timestamp assert compatibility
  CHANGELOG
  arangod/Agency/State.cpp
Labels: 1 Bug, 9 Ready to Merge

#10365 Fix immediate shutdown after startup failure.
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  lib/ApplicationFeatures/ApplicationServer.cpp
Labels: 9 Ready to Merge

#10370 Fix ArangoSearch consolidation results commit (3.5 backport)
  3rdParty/iresearch/core/index/index_writer.cpp
  CHANGELOG
Labels: 9 Ready to Merge

#10360 better killability of cluster AQL queries
  CHANGELOG
  arangod/Aql/DistributeExecutor.cpp
  arangod/Aql/DistributeExecutor.h
  arangod/Aql/EngineInfoContainerCoordinator.cpp
  arangod/Aql/EngineInfoContainerCoordinator.h
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionEngine.h
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryExecutionState.cpp
  arangod/Aql/QueryExecutionState.h
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryList.h
  arangod/Aql/QueryProfile.cpp
  arangod/Aql/QueryProfile.h
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Aql/RestAqlHandler.h
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestQueryHandler.h
  arangod/RestServer/BootstrapFeature.cpp
  arangod/Transaction/Manager.cpp
  arangod/V8Server/v8-vocbase.cpp
  tests/Aql/EngineInfoContainerCoordinatorTest.cpp
  tests/js/client/shell/shell-aql-kill.js
  tests/js/server/aql/aql-failures-cluster.js
Labels: 9 Ready to Merge

#10361 Store a removed server with date in the agency.
  js/actions/api-cluster.js
Labels: 9 Ready to Merge

#10389 Bug fix for K_SHORTEST_PATHS
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  tests/Graph/GraphTestTools.h
  tests/Graph/KShortestPathsFinder.cpp
Labels: 1 Bug, 3 Graph, 9 Review Required, 9 Waiting for Jenkins

#10390 Bug fix 3.5/k shortest paths
  CHANGELOG
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  tests/Graph/GraphTestTools.h
  tests/Graph/KShortestPathsFinder.cpp
Labels: 9 Ready to Merge

#10378 Remove code which puts system services to _app.
  CHANGELOG
  js/server/modules/@arangodb/foxx/manager.js
Labels: 1 Bug, 9 Ready to Merge

#10374 Fixed wrong permissions for rebalanceShards.
  js/actions/api-cluster.js
Labels: 9 Ready to Merge, 9 WIP

#10403 Improve syncer error message
  arangod/Replication/utilities.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
Labels: 9 Ready to Merge

#10388 Bug fix 3.5/internal issue #651
  CHANGELOG
  arangod/Aql/QueryString.h
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchAnalyzerFeature.h
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchKludge.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/VocBase/vocbase.cpp
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchDocument-test.cpp
  tests/IResearch/IResearchFilterBoolean-test.cpp
  tests/IResearch/IResearchFilterCompare-test.cpp
  tests/IResearch/IResearchFilterFunction-test.cpp
  tests/IResearch/IResearchFilterIn-test.cpp
  tests/IResearch/IResearchLinkHelper-test.cpp
  tests/IResearch/IResearchLinkMeta-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/common.cpp
  tests/V8Server/v8-analyzers-test.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
  tests/js/common/aql/aql-view-arangosearch-feature.js
  tests/js/server/dump/dump-mmfiles-cluster.js
  tests/js/server/dump/dump-mmfiles.js
  tests/js/server/dump/dump-rocksdb.js
  tests/js/server/dump/dump-setup-cluster.js
  tests/js/server/dump/dump-setup.js
  tests/js/server/replication/sync/replication-sync.js
Labels: 9 Ready to Merge

#10402 3.5 -- DEVSUP-492
  CHANGELOG
  arangod/Aql/Ast.cpp
  tests/js/server/aql/aql-modify.js
Labels: 9 Ready to Merge

#10404 Improve syncer error message
  arangod/Replication/utilities.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
Labels: 9 Ready to Merge

#10422 no coordinators left behind
  CHANGELOG
  js/actions/api-cluster.js
Labels: 1 Bug, Team Clifton

#10420 [3.5] no coordinators left behind
  CHANGELOG
  js/actions/api-cluster.js
Labels: 1 Bug, Team Clifton

#10416 Remove as now unused SingleBlockFetcher
  arangod/Aql/SingleBlockFetcher.h
Labels: 9 Ready to Merge

#10341 Feature/aql subquery splicing with gather
  arangod/Aql/Aggregator.cpp
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlItemBlock.h
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  arangod/Aql/AqlValueMaterializer.cpp
  arangod/Aql/AqlValueMaterializer.h
  arangod/Aql/Ast.cpp
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ConstrainedSortExecutor.cpp
  arangod/Aql/DependencyProxy.cpp
  arangod/Aql/DependencyProxy.h
  arangod/Aql/DistributeExecutor.cpp
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/IdExecutor.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/InputAqlItemRow.cpp
  arangod/Aql/InputAqlItemRow.h
  arangod/Aql/ModificationExecutor.cpp
  arangod/Aql/MultiDependencySingleRowFetcher.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
  arangod/Aql/QuerySnippet.cpp
  arangod/Aql/RegexCache.cpp
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Aql/ShadowAqlItemRow.cpp
  arangod/Aql/ShadowAqlItemRow.h
  arangod/Aql/SortExecutor.cpp
  arangod/Aql/SortExecutor.h
  arangod/Aql/SortNode.cpp
  arangod/Aql/SubqueryEndExecutionNode.cpp
  arangod/Aql/SubqueryEndExecutor.cpp
  arangod/Aql/SubqueryEndExecutor.h
  arangod/Aql/UnsortingGatherExecutor.cpp
  arangod/Aql/UnsortingGatherExecutor.h
  arangod/CMakeLists.txt
  arangod/IResearch/AqlHelper.h
  tests/Aql/AqlItemRowTest.cpp
  tests/Aql/DependencyProxyMock.cpp
  tests/Aql/ExecutionBlockImplTest.cpp
  tests/Aql/MultiDepFetcherHelper.cpp
  tests/Aql/SortExecutorTest.cpp
  tests/Geo/GeoConstructorTest.cpp
  tests/Geo/GeoFunctionsTest.cpp
  tests/js/server/aql/aql-gather-block-cluster.js
  tests/js/server/aql/aql-optimizer-indexes.js
  tests/js/server/aql/aql-optimizer-rule-use-index-for-sort.js
  tests/js/server/aql/aql-profiler-cluster.js
  tests/js/server/aql/aql-subquery.js
Labels: 1 Feature, 3 AQL, 3 Optimizer

#10471 add timeout to docublock
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
Labels: 9 Ready to Merge

#10473 make replication timeouts configurable via startup options
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Replication/ReplicationApplierConfiguration.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
Labels: 9 Ready to Merge

#10478 improve error message
  arangosh/Restore/RestoreFeature.cpp
Labels: 9 Ready to Merge

#10443 fixed issue #10440: Incorrect sorting with sort criteria partially covered by index
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/SortCondition.cpp
  tests/js/server/aql/aql-optimizer-rule-use-index-for-sort.js
Labels: 9 Ready to Merge

#10485 Fix bug in SubqueryEndExecutor
  arangod/Aql/SubqueryEndExecutor.cpp
  tests/Aql/SubqueryEndExecutorTest.cpp
Labels: 1 Bug

#10483 Catch exceptions in noexcept methods
  arangod/Aql/RestAqlHandler.cpp
Labels: 1 Bug

#10488 Fix SubqueryStartExecutor
  arangod/Aql/SubqueryStartExecutor.cpp
Labels: 1 Bug

#10484 Actually use the given format to execute a query
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionEngine.h
  arangod/Aql/Query.cpp
  arangod/Aql/RestAqlHandler.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
Labels: 1 Bug

#9308 Fix potential segfault
  arangod/Utils/CollectionNameResolver.cpp
Labels: 1 Bug

#10495 add tests for inventory (#10464)
  tests/js/client/shell/shell-inventory-cluster.js
  tests/js/client/shell/shell-inventory-noncluster.js
Labels: 9 Ready to Merge

#10423 feature/metrics
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/CMakeLists.txt
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/MMFiles/MMFilesTransactionState.cpp
  arangod/RestHandler/RestMetricsHandler.cpp
  arangod/RestHandler/RestMetricsHandler.h
  arangod/RestServer/Metrics.cpp
  arangod/RestServer/Metrics.h
  arangod/RestServer/MetricsFeature.cpp
  arangod/RestServer/MetricsFeature.h
  arangod/RestServer/arangod.cpp
  arangod/RestServer/counter.h
  arangod/RestServer/dynarray.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/Statistics/Descriptions.cpp
  arangod/Statistics/ServerStatistics.cpp
  arangod/Statistics/ServerStatistics.h
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  arangod/Statistics/StatisticsWorker.cpp
  arangod/Statistics/StatisticsWorker.h
  arangod/StorageEngine/StorageEngine.h
  arangod/V8Server/v8-statistics.cpp
  lib/ApplicationFeatures/GreetingsFeaturePhase.cpp
Labels: 1 Feature, 9 WIP

#10502 Bug fix/input row serialization
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlItemBlock.h
  arangod/Aql/InputAqlItemRow.cpp
  arangod/Aql/InputAqlItemRow.h
  arangod/Aql/RemoteExecutor.cpp
  tests/Aql/AqlItemBlockTest.cpp
Labels: 1 Bug

#10514 metrics feature cleanup in unprepare
  arangod/RestServer/MetricsFeature.cpp
  arangod/RestServer/MetricsFeature.h
Labels: 1 Bug

#10513 Set internal state to DONE when upstream is DONE
  arangod/Aql/ExecutionBlockImpl.cpp
Labels: 1 Bug, 9 Ready to Merge

#10518 fix segfault and try to avoid oom
  arangod/MMFiles/MMFilesHashIndex.cpp
  arangod/MMFiles/MMFilesHashIndex.h
  arangod/MMFiles/MMFilesPrimaryIndex.cpp
Labels: 9 Ready to Merge

#10520 Make some changes to Comm Tasks
  arangod/Cluster/ClusterComm.h
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/HttpCommTask.h
  arangod/GeneralServer/VstCommTask.cpp
  js/server/modules/@arangodb/cluster.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Rest/HttpRequest.cpp
  lib/Rest/HttpRequest.h
Labels: 9 Ready to Merge

#10526 Bug fix 3.4/little weekend fix
  arangod/MMFiles/MMFilesHashIndex.cpp
  arangod/MMFiles/MMFilesHashIndex.h
  arangod/MMFiles/MMFilesPrimaryIndex.cpp
Labels: 9 Ready to Merge

#10532 Updated arangosync to 0.7.0
  CHANGELOG
  VERSIONS
Labels: 3 Packaging

#10535 Updated arangosync to 0.7.0
  CHANGELOG
  VERSIONS
Labels: 3 Packaging

#10537 Bug fix/gharial return name
  CHANGELOG
  arangod/Graph/GraphManager.cpp
  tests/js/client/http/api-gharial-spec.js
Labels: 1 Bug

#10543 Allow the optimizer to use indexes
  CHANGELOG
  arangod/Indexes/Index.cpp
  tests/js/server/aql/aql-optimizer-indexes.js
Labels: 9 Ready to Merge

#10529 add minReplicationFactor to http documentation
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Database/get_api_database_current.md
  Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
Labels: 9 Ready to Merge

#10547 obsolete option `--vst.maxsize` requires a value if specified
  arangod/RestServer/ServerFeature.cpp
Labels: 9 Ready to Merge

#10538 Bug fix 3.5/fix internal issue 4451
  CHANGELOG
  arangod/Auth/UserManager.cpp
  arangod/Auth/UserManager.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangosh/Restore/RestoreFeature.cpp
  js/client/modules/@arangodb/testsuites/dump.js
  tests/js/server/dump/cleanup-alter-user.js
  tests/js/server/dump/dump-authentication.js
Labels: 9 Waiting for Jenkins

#10545 Cherry picked bug-fix for GharialAPI to return name in LIST
  CHANGELOG
  arangod/Graph/GraphManager.cpp
  tests/js/client/http/api-gharial-spec.js
Labels: 1 Bug, 9 Waiting for Jenkins

#7860 Missing post failure on readlock in SynchronizeShard
  CHANGELOG
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/CMakeLists.txt
  arangod/Cluster/CallbackGuard.cpp
  arangod/Cluster/CallbackGuard.h
  arangod/Cluster/RebootTracker.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  tests/Aql/EngineInfoContainerCoordinatorTest.cpp
Labels: 1 Bug, 9 WIP, Team Clifton

#10552 rename timeout to maxRuntime
  CHANGELOG
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryOptions.cpp
  arangod/Aql/QueryOptions.h
  tests/js/server/aql/aql-options.js
Labels: 9 Ready to Merge

#10541 Allow the optimizer to use indexes
  arangod/Indexes/Index.cpp
  tests/js/server/aql/aql-optimizer-indexes.js
Labels: 9 Ready to Merge

#10553 ungreylist the test
  tests/rb/HttpInterface/api-query-analysis-spec.rb
Labels: 9 Ready to Merge

#10512 check before foxx-heal
  arangod/RestHandler/RestStatusHandler.cpp
  arangosh/Restore/RestoreFeature.cpp
  tests/js/client/server_permissions/test-hardened-rest-apis.js
Labels: 9 Ready to Merge

#10551 attempt to make shell-query-spec test deterministic
  tests/js/common/shell/shell-query-spec.js
Labels: 9 Ready to Merge

#10503 Parallelize certain AQL write operations
  CHANGELOG
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ClusterNodes.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/OptimizerRulesFeature.h
  arangod/Statistics/StatisticsWorker.cpp
  tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Labels: 9 Ready to Merge

#10557 Bug fix/test shell skiplist rm performance
  tests/js/server/shell/shell-skiplist-rm-performance-timecritical-noncluster-grey.js
Labels: 9 Ready to Merge

#10560 use isDirect for slightly different cases
  arangod/RestHandler/RestDocumentHandler.cpp
Labels: 9 Ready to Merge

#10530 Try to fix keep alive 0
  3rdParty/fuerte/src/HttpConnection.cpp
  3rdParty/fuerte/src/VstConnection.cpp
  3rdParty/fuerte/src/helper.cpp
  arangosh/Shell/V8ClientConnection.cpp
Labels: 9 Ready to Merge

#10562 only anounce coordinator readiness once the agency is convinced we are
  arangod/RestServer/BootstrapFeature.cpp
  tests/js/common/shell/01_shell-database.js
Labels: 9 Ready to Merge

#10548 Fix and un-grey any iterator tests.
  tests/js/server/shell/shell-any-noncluster.js
  tests/js/server/shell/shell-any-nondeterministic-noncluster-grey.js
Labels: 9 Ready to Merge

#10568 Rename minReplicationFactor to writeConcern
  CHANGELOG
  Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/collectionProperties.md
  arangod/Cluster/AgencyPaths.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/DropCollection.cpp
  arangod/Cluster/TakeoverShardLeadership.cpp
  arangod/Cluster/UpdateCollection.cpp
  arangod/Graph/Graph.cpp
  arangod/Graph/GraphManager.cpp
  arangod/Graph/GraphOperations.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestCollectionHandler.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Transaction/Methods.cpp
  arangod/V8Server/v8-collection.cpp
  arangod/V8Server/v8-vocindex.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  arangod/VocBase/Methods/UpgradeTasks.cpp
  arangod/VocBase/VocbaseInfo.cpp
  arangosh/Restore/RestoreFeature.cpp
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/client/modules/@arangodb/arango-collection.js
  js/client/modules/@arangodb/arango-database.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Cluster/AgencyPathsTest.cpp
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchDocument-test.cpp
  tests/IResearch/IResearchFilterArrayIn-test.cpp
  tests/IResearch/IResearchFilterArrayInterval-test.cpp
  tests/IResearch/IResearchFilterBoolean-test.cpp
  tests/IResearch/IResearchFilterCompare-test.cpp
  tests/IResearch/IResearchFilterFunction-test.cpp
  tests/IResearch/IResearchFilterIn-test.cpp
  tests/IResearch/IResearchIndex-test.cpp
  tests/IResearch/IResearchLinkHelper-test.cpp
  tests/IResearch/IResearchLinkMeta-test.cpp
  tests/IResearch/IResearchQueryCommon.h
  tests/RestHandler/RestAnalyzerHandler-test.cpp
  tests/V8Server/v8-analyzers-test.cpp
  tests/js/client/http/api-gharial-spec.js
  tests/js/client/shell/shell-inventory-cluster.js
  tests/js/client/shell/shell-inventory-noncluster.js
  tests/js/common/shell/shell-cluster-collection.js
  tests/js/common/shell/shell-one-shard.js
  tests/js/server/dump/dump-rocksdb-cluster.js
  tests/js/server/dump/dump-setup-cluster.js
  tests/js/server/shell/shell-general-graph-creation-cluster.js
Labels: 9 Ready to Merge

#10581 Replication: New startup options available from v3.5.3 on, not v3.5.4
  arangod/Replication/ReplicationFeature.cpp
Labels: 1 Bug, 3 Documentation, 9 Ready to Merge
