Repository arangodb/arangodb, pull requests merged in 2019-02, with the labels that each got.

#8087 Add missing documentation and CHANGELOG entries for sort-limit optimization
  CHANGELOG
  Documentation/Books/AQL/ExecutionAndPerformance/Optimizer.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
Labels: 2 - Working

#8028 Feature/aql enumeratecollection executor
  arangod/Aql/DocumentProducingHelper.h
  arangod/Aql/EnumerateCollectionBlock.cpp
  arangod/Aql/EnumerateCollectionBlock.h
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/EnumerateCollectionExecutor.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/SingleRowFetcher.h
  arangod/Aql/Stats.h
  arangod/CMakeLists.txt
  arangod/Utils/OperationCursor.h
  tests/Aql/EnumerateCollectionExecutorTest.cpp
  tests/CMakeLists.txt
Labels: 2 - Working, 9 Review Required

#8082 some more debug logging for replication
  arangod/MMFiles/mmfiles-replication-dump.cpp
  arangod/Replication/TailingSyncer.cpp
  tests/js/server/replication/replication-ongoing-32.js
  tests/js/server/replication/replication-ongoing-global.js
Labels: 2 - Working

#8059 issue 466.4: implement persistence of IResearchLink WAL flush marker
  3rdParty/iresearch/core/index/directory_reader.cpp
  3rdParty/iresearch/core/index/directory_reader.hpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/MMFiles/MMFilesWalRecoverState.cpp
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/FlushFeature.h
  tests/CMakeLists.txt
  tests/Cluster/ClusterInfo-test.cpp
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/IResearch/StorageEngineMock.cpp
  tests/IResearch/StorageEngineMock.h
  tests/RestServer/FlushFeature-test.cpp
Labels: 2 - Working

#8051 Check authentication for cluster APIs
  arangod/V8Server/v8-actions.cpp
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/Methods/Upgrade.cpp
  js/actions/api-cluster.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/nodesView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/shardsView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/scaleView.js
  lib/V8/v8-globals.cpp
  lib/V8/v8-globals.h
  tests/js/server/resilience/moving-shards-cluster.js
Labels: 2 - Working

#8038 Sorted COLLECT: avoid nullptr deref when skipping and fix non-invalidated input variables
  CHANGELOG
  arangod/Aql/CollectBlock.cpp
  arangod/Aql/CollectBlock.h
  tests/js/server/aql/aql-optimizer-rule-remove-redundant-sorts.js
Labels: 1 Bug, 2 - Working, 3 AQL

#8037 [3.4] Sorted COLLECT: avoid nullptr deref when skipping and fix non-invalidated input variables
  CHANGELOG
  arangod/Aql/CollectBlock.cpp
  arangod/Aql/CollectBlock.h
  tests/js/server/aql/aql-optimizer-rule-remove-redundant-sorts.js
Labels: 1 Bug, 2 - Working, 3 AQL

#8101 yet some more replication tests adjustments
  arangod/Replication/TailingSyncer.cpp
  tests/js/server/replication/replication-fuzz-global.js
  tests/js/server/replication/replication-fuzz.js
  tests/js/server/replication/replication-ongoing-32.js
  tests/js/server/replication/replication-ongoing-frompresent-32.js
  tests/js/server/replication/replication-ongoing-frompresent.js
  tests/js/server/replication/replication-ongoing-global-spec.js
  tests/js/server/replication/replication-ongoing-global.js
  tests/js/server/replication/replication-ongoing.js
  tests/js/server/replication/replication-random.js
Labels: 2 - Working

#8097 more mmfiles replication tests changes
  tests/js/server/replication/replication-fuzz-global.js
  tests/js/server/replication/replication-fuzz.js
  tests/js/server/replication/replication-ongoing-32.js
  tests/js/server/replication/replication-ongoing-frompresent-32.js
  tests/js/server/replication/replication-ongoing-frompresent.js
  tests/js/server/replication/replication-ongoing-global-spec.js
  tests/js/server/replication/replication-ongoing-global.js
  tests/js/server/replication/replication-ongoing.js
  tests/js/server/replication/replication-random.js
Labels: 2 - Working

#7988 Doc - More downgrade options (solving challenging situations)
  Documentation/Books/Manual/Downgrading/README.md
Labels: 2 - Working, 3 Documentation

#8098 use PutUntracked to insert entries into non-unique indexes
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBKey.cpp
  arangod/RocksDBEngine/RocksDBKey.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
Labels: 2 - Working

#8104 fix error handling in V8Cursor::New
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/V8Server/v8-voccursor.cpp
Labels: 2 - Working

#8103 test for broken indexes
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  tests/js/server/recovery/indexes-inbackground-rocksdb.js
Labels: 2 - Working

#8106 Doc - Fixes link
  Documentation/Books/Manual/DataModeling/Concepts.md
Labels: 2 - Working, 3 Documentation

#8107 Doc - More downgrade options (solving challenging situations)
  Documentation/Books/Manual/Downgrading/README.md
Labels: 2 - Working, 3 Documentation

#8089 fixing failedserver/leader/follower chain for mishap
  CHANGELOG
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedServer.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8096 Failed servers now transactionally adds along the leader/follower jobs
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedServer.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8109 Bug fix: do not mutate the offset in the LimitExecutor
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/LimitExecutor.cpp
  arangod/Aql/LimitExecutor.h
  tests/Aql/LimitExecutorTest.cpp
  tests/js/server/aql/aql-subquery.js
Labels: 1 Bug, 2 - Working

#8111 fixed issue #8108
  CHANGELOG
  arangod/Aql/Expression.h
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-simplify-conditions.js
Labels: 2 - Working

#8110 Doc - Production Checklist Improvements
  Documentation/Books/Manual/Deployment/ProductionChecklist.md
Labels: 2 - Working, 3 Documentation

#8100 [3.4] Note that ArangoSearch views cannot be used as edge collections in traversals
  Documentation/Books/AQL/Graphs/Traversals.md
  Documentation/Books/AQL/Views/ArangoSearch/README.md
Labels: 2 - Working, 3 Documentation

#8099 Note that ArangoSearch views cannot be used as edge collections in traversals
  Documentation/Books/AQL/Graphs/Traversals.md
  Documentation/Books/AQL/Views/ArangoSearch/README.md
Labels: 2 - Working, 3 Documentation

#8117 Fix shutdown race in supervised scheduler
  arangod/Scheduler/SchedulerFeature.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
Labels: 2 - Working

#8102 [3.3] failed servers now transactionally adds along the leader/follower jobs
  CHANGELOG
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedServer.cpp
Labels: 1 Bug, 2 - Working, Team Clifton

#8116 added a warning if compiled in maintainer mode
  CHANGELOG
  lib/ApplicationFeatures/GreetingsFeature.cpp
Labels: 2 - Working

#8122 fix issue #8108
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-simplify-conditions.js
Labels: 2 - Working

#8123 Bug fix/m0ppers fix warnings
  arangod/RestHandler/RestRepairHandler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  arangod/VocBase/Methods/Databases.cpp
Labels: 2 - Working

#8118 Make single server key generators lockfree.
  arangod/VocBase/KeyGenerator.cpp
Labels: 2 - Working

#8045 Feature 3.4: Ability to hold and release new transactions
  arangod/RocksDBEngine/RocksDBTransactionManager.h
  arangod/StorageEngine/TransactionManager.h
  lib/Basics/ReadWriteLock.cpp
  lib/Basics/ReadWriteLock.h
  tests/CMakeLists.txt
  tests/RocksDBEngine/TransactionManagerTest.cpp
Labels: 2 - Working

#8124 issue 466.5: switch to using WAL markers instead of FlushThread for recovery
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/FlushFeature.h
  arangod/Utils/FlushThread.cpp
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchView-test.cpp
Labels: 2 - Working

#8121 added run-time openssl version
  CHANGELOG
  lib/Rest/Version.cpp
  lib/Rest/Version.h
Labels: 2 - Working

#8130 issue 466.6: remove unused code, remove hardcoded view meta values
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewMeta.h
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/FlushFeature.h
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchQueryAggregate-test.cpp
  tests/IResearch/IResearchQueryAnd-test.cpp
  tests/IResearch/IResearchQueryBooleanTerm-test.cpp
  tests/IResearch/IResearchQueryComplexBoolean-test.cpp
  tests/IResearch/IResearchQueryExists-test.cpp
  tests/IResearch/IResearchQueryIn-test.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/IResearch/IResearchQueryNullTerm-test.cpp
  tests/IResearch/IResearchQueryNumericTerm-test.cpp
  tests/IResearch/IResearchQueryOptions-test.cpp
  tests/IResearch/IResearchQueryOr-test.cpp
  tests/IResearch/IResearchQueryPhrase-test.cpp
  tests/IResearch/IResearchQueryScorer-test.cpp
  tests/IResearch/IResearchQuerySelectAll-test.cpp
  tests/IResearch/IResearchQueryStartsWith-test.cpp
  tests/IResearch/IResearchQueryStringTerm-test.cpp
  tests/IResearch/IResearchQueryTokens-test.cpp
  tests/IResearch/IResearchQueryTraversal-test.cpp
  tests/IResearch/IResearchQueryValue-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/IResearch/IResearchViewMeta-test.cpp
  tests/IResearch/IResearchViewNode-test.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
  tests/js/server/recovery/view-arangosearch-modify-properties.js
Labels: 2 - Working

#8140 issue #8137: NULL input field generates U_ILLEGAL_ARGUMENT_ERROR
  arangod/Aql/Functions.cpp
  tests/js/server/aql/aql-functions-string.js
Labels: 2 - Working

#8139 issue #8137: NULL input field generates U_ILLEGAL_ARGUMENT_ERROR
  CHANGELOG
  arangod/Aql/Functions.cpp
  tests/js/server/aql/aql-functions-string.js
Labels: 2 - Working

#8153 fix while loop in in-iterator
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
Labels: 2 - Working

#8151 Properly translate cluster comm errors
  arangod/Cluster/ClusterMethods.cpp
Labels: 2 - Working

#8152 Properly translate cluster comm errors
  arangod/Cluster/ClusterMethods.cpp
Labels: 2 - Working

#8141 Fix isAqlQuery with empty query
  CHANGELOG
  js/common/modules/@arangodb/common.js
Labels: 1 Bug, 2 - Working, 9 Review Required

#8142 Fix isAqlQuery with empty query (3.4)
  CHANGELOG
  js/common/modules/@arangodb/common.js
Labels: 1 Bug, 2 - Working, 9 Review Required

#8133 Doc - Cites Kubernetes in the upgrade guide
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Upgrading/Kubernetes/README.md
  Documentation/Books/Manual/Upgrading/README.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#8148 Doc - Added default ttl for cursor
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
Labels: 2 - Working, 3 Documentation

#8158 Doc - Added default ttl for cursor (3.4)
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
Labels: 2 - Working, 3 Documentation

#8160 Doc - Cites Kubernetes in the upgrade guide
  Documentation/Books/Manual/SUMMARY.md
  Documentation/Books/Manual/Upgrading/Kubernetes/README.md
  Documentation/Books/Manual/Upgrading/README.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8126 use PutUntracked
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBMethods.cpp
  arangod/RocksDBEngine/RocksDBMethods.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
Labels: 2 - Working

#8156 micro optimizations
  3rdParty/velocypack/include/velocypack/Iterator.h
  3rdParty/velocypack/include/velocypack/Slice.h
  arangod/Aql/Condition.cpp
  arangod/Aql/Condition.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Functions.cpp
  arangod/Graph/BaseOptions.cpp
  arangod/Indexes/SkiplistIndexAttributeMatcher.cpp
  arangod/Indexes/SkiplistIndexAttributeMatcher.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBComparator.cpp
  arangod/RocksDBEngine/RocksDBComparator.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/RocksDBEngine/RocksDBValue.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/Transaction/Helpers.cpp
  lib/Basics/Utf8Helper.cpp
  lib/Basics/VelocyPackHelper.cpp
  lib/Basics/VelocyPackHelper.h
Labels: 2 - Working

#8042 Feature/shortest path executor
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ShortestPathBlock.cpp
  arangod/Aql/ShortestPathBlock.h
  arangod/Aql/ShortestPathExecutor.cpp
  arangod/Aql/ShortestPathExecutor.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/ShortestPathNode.h
  arangod/Aql/TraversalExecutor.h
  arangod/Aql/TraversalNode.cpp
  arangod/CMakeLists.txt
  arangod/Graph/AttributeWeightShortestPathFinder.cpp
  arangod/Graph/AttributeWeightShortestPathFinder.h
  arangod/Graph/BaseOptions.cpp
  arangod/Graph/BaseOptions.h
  arangod/Graph/ConstantWeightShortestPathFinder.cpp
  arangod/Graph/ConstantWeightShortestPathFinder.h
  arangod/Graph/ShortestPathFinder.cpp
  arangod/Graph/ShortestPathFinder.h
  arangod/Graph/ShortestPathOptions.h
  arangod/Graph/ShortestPathResult.cpp
  arangod/Graph/ShortestPathResult.h
  tests/Aql/ShortestPathExecutorTest.cpp
  tests/Aql/TraversalExecutorTest.cpp
  tests/CMakeLists.txt
Labels: 2 - Working, 9 Review Required

#8150 Switch to thread-local RandomDevice instances.
  lib/Basics/operating-system.h
  lib/Random/RandomGenerator.cpp
  lib/Random/RandomGenerator.h
Labels: 2 - Working

#8164 Clear registers per block, not per row
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
Labels: 2 - Working

#7193 [3.4] Resilience tests with data
  tests/js/server/resilience/moving-shards-cluster.js
  tests/js/server/resilience/moving-shards-with-arangosearch-view-grey-cluster.js
  tests/js/server/resilience/repair-distribute-shards-like-spec.js
Labels: 2 - Working

#7497 Resilience tests with data
  tests/js/server/resilience/moving-shards-cluster.js
  tests/js/server/resilience/moving-shards-with-arangosearch-view-cluster.js
  tests/js/server/resilience/repair-distribute-shards-like-spec.js
Labels: 2 - Working

#8168 Keep "registers to keep" to the necessary minimum
  arangod/Aql/AqlItemBlock.h
  arangod/Aql/CalculationExecutor.cpp
  arangod/Aql/CalculationExecutor.h
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/EnumerateCollectionExecutor.h
  arangod/Aql/EnumerateListExecutor.cpp
  arangod/Aql/EnumerateListExecutor.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutorInfos.cpp
  arangod/Aql/ExecutorInfos.h
  arangod/Aql/FilterExecutor.cpp
  arangod/Aql/FilterExecutor.h
  arangod/Aql/InputAqlItemRow.h
  arangod/Aql/LimitExecutor.cpp
  arangod/Aql/LimitExecutor.h
  arangod/Aql/ShortestPathExecutor.cpp
  arangod/Aql/ShortestPathExecutor.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/SortExecutor.cpp
  arangod/Aql/SortExecutor.h
  arangod/Aql/SortNode.cpp
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalExecutor.h
  arangod/Aql/TraversalNode.cpp
  arangod/IResearch/IResearchViewNode.cpp
  tests/Aql/AqlItemRowTest.cpp
  tests/Aql/CalculationExecutorTest.cpp
  tests/Aql/EnumerateCollectionExecutorTest.cpp
  tests/Aql/EnumerateListExecutorTest.cpp
  tests/Aql/ExecutionBlockImplTest.cpp
  tests/Aql/FilterExecutorTest.cpp
  tests/Aql/LimitExecutorTest.cpp
  tests/Aql/NoResultsExecutorTest.cpp
  tests/Aql/ShortestPathExecutorTest.cpp
  tests/Aql/SortExecutorTest.cpp
  tests/Aql/TestEmptyExecutorHelper.cpp
  tests/Aql/TestEmptyExecutorHelper.h
  tests/Aql/TestExecutorHelper.cpp
  tests/Aql/TestExecutorHelper.h
  tests/Aql/TraversalExecutorTest.cpp
Labels: 2 - Working

#8170 Inline Return and CalculationExecutor. Also avoid an unnecessary copy.
  arangod/Aql/CalculationExecutor.cpp
  arangod/Aql/CalculationExecutor.h
  arangod/Aql/ReturnExecutor.cpp
  arangod/Aql/ReturnExecutor.h
  tests/Aql/ReturnExecutorTest.cpp
Labels: 2 - Working

#8157 Make Result final
  arangod/Aql/AqlResult.cpp
  arangod/Aql/AqlResult.h
  arangod/Auth/Handler.h
  arangod/Cluster/ClusterRepairDistributeShardsLike.cpp
  arangod/Cluster/ResultT.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Graph/Graph.cpp
  arangod/Graph/GraphManager.cpp
  arangod/Graph/GraphOperations.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestControlPregelHandler.cpp
  arangod/RestHandler/RestGraphHandler.cpp
  arangod/RestHandler/RestRepairHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestTestHandler.cpp
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RestServer/BootstrapFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBReplicationCommon.cpp
  arangod/RocksDBEngine/RocksDBReplicationCommon.h
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBWalAccess.cpp
  arangod/StorageEngine/WalAccess.h
  arangod/V8Server/v8-query.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/Methods/Upgrade.h
  lib/Basics/FileResult.h
  lib/Basics/FileResultString.h
  lib/Basics/Result.cpp
  lib/Basics/Result.h
  tests/Cluster/ClusterRepairsTest.cpp
Labels: 2 - Working

#8033 Added .insert part for document insertion
  Documentation/Books/Manual/Appendix/References/CollectionObject.md
  Documentation/Books/Manual/DataModeling/Documents/DocumentMethods.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#8003 Doc - Improve description of CHECK_DOCUMENT() AQL function
  Documentation/Books/AQL/Functions/Miscellaneous.md
Labels: 2 - Working, 3 AQL, 3 Documentation, 9 Ready to Merge

#8173 Make result errorMessage generation lazier
  lib/Basics/Result.cpp
Labels: 2 - Working

#8185 when creating a new database with an initial user, set the database p…
  CHANGELOG
  arangod/VocBase/Methods/UpgradeTasks.cpp
  tests/js/common/shell/shell-database.js
Labels: 2 - Working

#8184 when creating a new database with an initial user, set the database p…
  arangod/VocBase/Methods/UpgradeTasks.cpp
  tests/js/common/shell/shell-database.js
Labels: 2 - Working

#8186 add test
  js/common/tests/shell/shell-database.js
Labels: 2 - Working

#8044 Doc - _rev warning
  Documentation/Books/Manual/Appendix/Glossary.md
  Documentation/Books/Manual/DataModeling/Documents/DocumentAddress.md
  Documentation/Books/stash/DocumentRevisionMVCC.md
  Documentation/DocuBlocks/documentRevision.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7972 Doc - Complete the highlights page
  Documentation/Books/AQL/ExecutionAndPerformance/ExplainingQueries.md
  Documentation/Books/AQL/Operators.md
  Documentation/Books/Manual/Highlights.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#7368 [3.4] Forbid ambiguous casts to and from ResultT
  arangod/Cluster/ResultT.h
  arangod/RestHandler/RestRepairHandler.cpp
Labels: 2 - Working

#8147 Forbid ambiguous casts to and from ResultT
  arangod/Cluster/ResultT.h
  arangod/RestHandler/RestRepairHandler.cpp
Labels: 2 - Working

#8192 SortExecutor optimization for few lines from upstream
  arangod/Aql/AllRowsFetcher.cpp
  arangod/Aql/AllRowsFetcher.h
  arangod/Aql/ConstFetcher.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/SingleRowFetcher.h
  tests/Aql/AllRowsFetcherTest.cpp
Labels: 1 Bug, 2 - Working

#8195 fixed issue #8165
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-geoindex.js
Labels: 2 - Working

#8194 fixed issue #8165
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-geoindex.js
Labels: 2 - Working

#8201 when we DO_NOTHING tell the implementer he may stop invoking us
  3rdParty/V8/v7.1.302.28/src/heap/heap.cc
Labels: 2 - Working

#8191 Bug fix/clustercomm queue cleanup
  arangod/Cluster/ClusterComm.cpp
  arangod/Cluster/ClusterComm.h
  tests/Cluster/ClusterCommTest.cpp
Labels: 2 - Working

#8181 Feature/aql distinct collect executor
  arangod/Aql/CollectBlock.cpp
  arangod/Aql/CollectNode.cpp
  arangod/Aql/DistinctCollectExecutor.cpp
  arangod/Aql/DistinctCollectExecutor.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/CMakeLists.txt
  tests/Aql/DistinctCollectExecutorTest.cpp
  tests/CMakeLists.txt
Labels: 2 - Working, 9 Ready to Merge

#8198 do not allow edge definitions with empty from or to arrays, added als…
  arangod/Graph/Graph.cpp
  tests/js/common/shell/shell-general-graph.js
Labels: 2 - Working

#8200 do not allow edge definitions with empty from or to arrays, added als…
  arangod/Graph/Graph.cpp
  tests/js/common/shell/shell-general-graph.js
Labels: 2 - Working

#8210 improve error messages when restoring from invalid JSON data
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: 2 - Working

#8211 improve error messages when restoring from invalid JSON data
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: 2 - Working

#8209 improve error messages
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: 2 - Working

#8190 fix shutdown of query cache
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryCache.cpp
  arangod/Aql/QueryCache.h
  arangod/RestServer/DatabaseFeature.cpp
Labels: 2 - Working

#8146 Feature/aql index executor
  arangod/Aql/DocumentProducingHelper.h
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/EnumerateCollectionExecutor.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutorExpressionContext.cpp
  arangod/Aql/IndexBlock.cpp
  arangod/Aql/IndexBlock.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  arangod/Aql/Stats.h
  arangod/CMakeLists.txt
  tests/Aql/EnumerateCollectionExecutorTest.cpp
Labels: 2 - Working, 9 Review Required

#8182 feature/aql count collect executor
  arangod/Aql/CollectBlock.cpp
  arangod/Aql/CollectNode.cpp
  arangod/Aql/CountCollectExecutor.cpp
  arangod/Aql/CountCollectExecutor.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
  arangod/CMakeLists.txt
  tests/Aql/CountCollectExecutorTest.cpp
  tests/CMakeLists.txt
Labels: 2 - Working, 9 Review Required

#8218 Bug fix/small issues 21022019
  arangod/Aql/QueryCache.cpp
  arangod/Indexes/Index.cpp
Labels: 2 - Working

#8227 Greylist ./tests/js/server/resilience/moving-shards-with-arangosearch-view-grey-cluster.js
  tests/Greylist.txt
  tests/js/server/resilience/moving-shards-with-arangosearch-view-grey-cluster.js
Labels: 3 - Testing

#8228 Doc - New k8 drain page
  Documentation/Books/Manual/Deployment/Kubernetes/Drain.md
  Documentation/Books/Manual/Deployment/Kubernetes/HealthyCluster.png
  Documentation/Books/Manual/Deployment/Kubernetes/ShardsInSync.png
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8231 Doc - New k8 drain page
  Documentation/Books/Manual/Deployment/Kubernetes/Drain.md
  Documentation/Books/Manual/Deployment/Kubernetes/HealthyCluster.png
  Documentation/Books/Manual/Deployment/Kubernetes/ShardsInSync.png
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#8203 Add TTL to query options to standardize usage across components.
  CHANGELOG
  Documentation/Examples/arangod.json
  arangod/Aql/EngineInfoContainerCoordinator.cpp
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/QueryOptions.cpp
  arangod/Aql/QueryOptions.h
  arangod/Aql/RestAqlHandler.cpp
  arangod/Aql/RestAqlHandler.h
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
  tests/Aql/EngineInfoContainerCoordinatorTest.cpp
  tests/rb/HttpInterface/api-cursor-spec.rb
Labels: 2 - Working

#8193 issue 523.1: address build issues, ensure FlushFeature subscriptions are cleared during stop(), assert that they are deallocated
  arangod/Aql/ShortestPathExecutor.cpp
  arangod/Aql/ShortestPathExecutor.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalExecutor.h
  arangod/Aql/TraversalNode.cpp
  arangod/RestServer/FlushFeature.cpp
  tests/Aql/ShortestPathExecutorTest.cpp
  tests/Aql/TraversalExecutorTest.cpp
Labels: 2 - Working

#8215 Doc - Complete the highlights page (#7972)
  Documentation/Books/AQL/ExecutionAndPerformance/ExplainingQueries.md
  Documentation/Books/AQL/Operators.md
  Documentation/Books/Manual/Highlights.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#8205 Doc - Added .insert part for document insertion (#8033)
  Documentation/Books/Manual/Appendix/References/CollectionObject.md
  Documentation/Books/Manual/DataModeling/Documents/DocumentMethods.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#8204 Doc - _rev warning (#8044)
  Documentation/Books/Manual/Appendix/Glossary.md
  Documentation/Books/Manual/DataModeling/Documents/DocumentAddress.md
  Documentation/Books/stash/DocumentRevisionMVCC.md
  Documentation/DocuBlocks/documentRevision.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#8232 Doc - Windows Installation - Use code tags and env vars
  Documentation/Books/Manual/Installation/Windows.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#8187 Bug fix 3.4/fix for windows nanos
  3rdParty/rocksdb/v5.16.X/port/win/env_win.cc
  CHANGELOG
Labels: 2 - Working

#8020 WIP - improve auto-resync
  arangod/Replication/DatabaseTailingSyncer.cpp
  arangod/Replication/GlobalTailingSyncer.cpp
  arangod/Replication/ReplicationApplier.cpp
  arangod/Replication/ReplicationApplier.h
  arangod/Replication/ReplicationApplierState.cpp
  arangod/Replication/ReplicationApplierState.h
  arangod/Replication/TailingSyncer.cpp
Labels: 2 - Working, 9 Review Required

#8241 Doc - Improve hint boxes on page MigratingSingleInstanceCluster.md
  Documentation/Books/Manual/Deployment/MigratingSingleInstanceCluster.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#8240 Doc - Windows Installation - Use code tags and env vars (#8232)
  Documentation/Books/Manual/Installation/Windows.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#8189 3.4: Add rocksdb clock fix to known issues
  Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
  Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8247 devel: Add rocksdb clock fix to known issues
  Documentation/Books/Manual/ReleaseNotes/KnownIssues33.md
  Documentation/Books/Manual/ReleaseNotes/KnownIssues34.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8014 Doc - Use proper terms for editions (esp. shardingStrategy)
  Documentation/Books/Manual/Administration/Cluster/README.md
  Documentation/Books/Manual/DataModeling/Collections/DatabaseMethods.md
  Documentation/Books/Manual/Graphs/Pregel/README.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures31.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures32.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Graph/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#8238 upgraded to 4.17.11 because of CVE-2018-16487
  CHANGELOG
  js/node/package.json
Labels: 2 - Working

#8235 issue 521.1: do not mark loadPlan as valid unless all instances were created successfully
  arangod/Cluster/ClusterInfo.cpp
Labels: 2 - Working

#8243 The big supervision fix.
  CHANGELOG
  arangod/Agency/AddFollower.cpp
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/Supervision.cpp
  arangod/Cluster/DBServerAgencySync.cpp
  lib/Basics/StringUtils.h
  tests/Agency/AddFollowerTest.json
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/CleanOutServerTest.json
  tests/Agency/FailedLeaderTest.json
  tests/Agency/MoveShardTest.cpp
Labels: 2 - Working

#8248 issue 519.1: fix typo, add tests, supress extraneous test log output
  arangod/IResearch/IResearchLinkHelper.cpp
  tests/CMakeLists.txt
  tests/IResearch/IResearchIndex-test.cpp
  tests/IResearch/IResearchLinkHelper-test.cpp
  tests/IResearch/IResearchQueryAnd-test.cpp
  tests/IResearch/IResearchQueryBooleanTerm-test.cpp
  tests/IResearch/IResearchQueryComplexBoolean-test.cpp
  tests/IResearch/IResearchQueryExists-test.cpp
  tests/IResearch/IResearchQueryIn-test.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/IResearch/IResearchQueryNullTerm-test.cpp
  tests/IResearch/IResearchQueryNumericTerm-test.cpp
  tests/IResearch/IResearchQueryOr-test.cpp
  tests/IResearch/IResearchQueryPhrase-test.cpp
  tests/IResearch/IResearchQueryTraversal-test.cpp
Labels: 2 - Working

#8250 Sync Foxx Queues
  arangod/Cluster/HeartbeatThread.cpp
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/MMFiles/MMFilesWalAccess.cpp
  arangod/MMFiles/mmfiles-replication-dump.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/GlobalInitialSyncer.cpp
  arangod/Replication/ReplicationApplierConfiguration.cpp
  arangod/Replication/ReplicationApplierConfiguration.h
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/common-defines.cpp
  arangod/Replication/common-defines.h
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/StorageEngine/WalAccess.cpp
  arangod/StorageEngine/WalAccess.h
  js/server/modules/@arangodb/foxx/queues/manager.js
Labels: 2 - Working

#8254 Sync Foxx Queues
  arangod/Cluster/HeartbeatThread.cpp
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/MMFiles/MMFilesWalAccess.cpp
  arangod/MMFiles/mmfiles-replication-dump.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/GlobalInitialSyncer.cpp
  arangod/Replication/ReplicationApplierConfiguration.cpp
  arangod/Replication/ReplicationApplierConfiguration.h
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/common-defines.cpp
  arangod/Replication/common-defines.h
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationTailing.cpp
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/StorageEngine/WalAccess.cpp
  arangod/StorageEngine/WalAccess.h
  js/server/modules/@arangodb/foxx/queues/manager.js
Labels: 2 - Working

#8263 Pregel Nullptr checks
  CHANGELOG
  arangod/Pregel/PregelFeature.cpp
  arangod/V8Server/v8-collection.cpp
Labels: 2 - Working

#8260 Bug fix 3.4/fix reconnect with jwt
  CHANGELOG
  arangosh/Shell/V8ClientConnection.cpp
Labels: 2 - Working

#8270 fix reconnect with jwt (#8260)
  CHANGELOG
  arangosh/Shell/V8ClientConnection.cpp
Labels: 2 - Working

#8262 Fix bug #8213
  arangod/IResearch/IResearchViewNode.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.js
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
Labels: 2 - Working

#8274 cleanup
  etc/relative/arangod.conf
Labels: 2 - Working

#8269 remove unused includes
  arangod/Auth/TokenCache.cpp
  arangod/Auth/UserManager.cpp
  arangod/GeneralServer/VstCommTask.cpp
Labels: 2 - Working

#8273 backport: Fix bug #8213
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewNode.cpp
  tests/IResearch/IResearchQueryJoin-test.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
Labels: 2 - Working

#7637 Bug fix/geo optimization cleanup
  Documentation/Books/AQL/Functions/Geo.md
  arangod/Aql/Functions.cpp
Labels: 2 - Working

#8222 fixed some escpaing issues, removed dead code, eslint
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocument.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/nodeInfoView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsItemView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/nodeInfoView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/replicationView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userPermissions.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewsView.js
Labels: 2 - Working, 9 Review Required

#8224 fixed some escpaing issues, removed dead code, eslint
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocument.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/nodeInfoView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsItemView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/nodeInfoView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/replicationView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userPermissions.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userView.js
Labels: 2 - Working, 9 Review Required

#8225 fixed the graph editing modal, ordering of edge definitions was false
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/versionCheck.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsItemView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/dashboardView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/loginView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/spotlightView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userManagementView.js
Labels: 2 - Working, 9 Review Required

#8253 Doc - Improve hint boxes on page MigratingSingleInstanceCluster.md
  Documentation/Books/Manual/Deployment/MigratingSingleInstanceCluster.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8252 Doc - Use proper terms for editions (esp. shardingStrategy) (#8014)
  Documentation/Books/Manual/Administration/Cluster/README.md
  Documentation/Books/Manual/DataModeling/Collections/DatabaseMethods.md
  Documentation/Books/Manual/Graphs/Pregel/README.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures31.md
  Documentation/Books/Manual/ReleaseNotes/NewFeatures32.md
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges34.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Graph/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
Labels: 2 - Working, 3 Documentation, 9 Waiting for Jenkins

#8255 Feature/aql traversal prune
  CHANGELOG
  Documentation/Books/AQL/Graphs/Traversals.md
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/InAndOutRowExpressionContext.cpp
  arangod/Aql/InAndOutRowExpressionContext.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/PruneExpressionEvaluator.cpp
  arangod/Aql/PruneExpressionEvaluator.h
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraversalNode.h
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  arangod/CMakeLists.txt
  arangod/Graph/BaseOptions.h
  arangod/Graph/BreadthFirstEnumerator.cpp
  arangod/Graph/BreadthFirstEnumerator.h
  arangod/Graph/NeighborsEnumerator.cpp
  arangod/Graph/NeighborsEnumerator.h
  arangod/Graph/PathEnumerator.cpp
  arangod/Graph/PathEnumerator.h
  arangod/Graph/Traverser.cpp
  arangod/Graph/Traverser.h
  arangod/Graph/TraverserOptions.cpp
  arangod/Graph/TraverserOptions.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/server/aql/aql-graph-traverser.js
Labels: 2 - Working

#8237 Doc - AF improvements
  Documentation/Books/Manual/Architecture/DeploymentModes/ActiveFailover/Architecture.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#8281 Doc - AF improvements
  Documentation/Books/Manual/Architecture/DeploymentModes/ActiveFailover/Architecture.md
Labels: 2 - Working, 3 Documentation

#7992 Doc - Cluster Architecture Improvements
  Documentation/Books/Manual/Architecture/DeploymentModes/Cluster/Architecture.md
  Documentation/Books/stash/ClusterArchitecture.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#7756 Doc - Fast Cluster Restore Procedure
  Documentation/Books/Manual/BackupRestore/README.md
  Documentation/Books/Manual/Programs/Arangodump/Examples.md
  Documentation/Books/Manual/Programs/Arangorestore/Examples.md
  Documentation/Books/Manual/Programs/Arangorestore/FastClusterRestore.md
  Documentation/Books/Manual/Programs/Arangorestore/README.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation, 9 Review Required

#8285 Doc - Cluster Architecture Improvements
  Documentation/Books/Manual/Architecture/DeploymentModes/Cluster/Architecture.md
  Documentation/Books/stash/ClusterArchitecture.md
Labels: 2 - Working, 3 Documentation

#8289 Doc - Fast Cluster Restore Procedure
  Documentation/Books/Manual/BackupRestore/README.md
  Documentation/Books/Manual/Programs/Arangodump/Examples.md
  Documentation/Books/Manual/Programs/Arangorestore/Examples.md
  Documentation/Books/Manual/Programs/Arangorestore/FastClusterRestore.md
  Documentation/Books/Manual/Programs/Arangorestore/README.md
  Documentation/Books/Manual/SUMMARY.md
Labels: 2 - Working, 3 Documentation

#8188 fix buffer overflow
  3rdParty/rocksdb/v5.18.X/port/win/env_win.cc
  CHANGELOG
Labels: 2 - Working

#8277 Bug fix 3.4/clustercomm queue cleanup
  arangod/Cluster/ClusterComm.cpp
  arangod/Cluster/ClusterComm.h
  tests/Cluster/ClusterCommTest.cpp
Labels: 2 - Working

#8278 [3.4] start local cluster with new jwt secret file option
  scripts/startLocalCluster.sh
Labels: 2 - Working, Team Clifton

#8283 Set thread's state to `STOPPED` when the thread function finishes.
  lib/Basics/Thread.cpp
Labels: 2 - Working

#8275 improve replication speed - port from 3.4
  arangod/Replication/DatabaseTailingSyncer.cpp
  arangod/Replication/Syncer.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/TailingSyncer.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  lib/Basics/VelocyPackHelper.cpp
Labels: 2 - Working

#8291 abort ongoing transactions in all cases
  arangod/Replication/TailingSyncer.cpp
Labels: 2 - Working

#8268 Feature 3.4/improve replication speed
  arangod/Replication/DatabaseTailingSyncer.cpp
  arangod/Replication/Syncer.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication/TailingSyncer.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  lib/Basics/VelocyPackHelper.cpp
Labels: 2 - Working

#8290 abort ongoing transactions in all cases
  arangod/Replication/TailingSyncer.cpp
Labels: 2 - Working

#8284 Bug fix/stronger testing certificate
  UnitTests/server.pem
Labels: 2 - Working

#8295 Doc - Update Kubernetes (Tutorial/Drain)
  Documentation/Books/Manual/Deployment/Kubernetes/Drain.md
  Documentation/Books/Manual/Tutorials/Kubernetes/README.md
Labels: 2 - Working, 3 Documentation, 9 Ready to Merge

#8298 Restart action feature for something to be executed just before main …
  arangod/RestServer/arangod.cpp
  tests/main.cpp
Labels: 2 - Working
