Repository arangodb/arangodb, pull requests merged in 2019-12, with the labels that each got.

#10584 fix UUID - devel
  CHANGELOG
  CMakeLists.txt
Labels: 9 Review Required

#10612 Bug fix/lol jenkins branch names
  3rdParty/iresearch/core/utils/log.hpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
Labels: 9 Ready to Merge

#10613 remove invalid noexcept declarations
  arangod/IResearch/IResearchAnalyzerFeature.cpp
Labels: 9 Ready to Merge

#10620 tag dynamic options with Dynamic flags attribute
  arangosh/Shell/ConsoleFeature.cpp
  lib/Logger/LoggerFeature.cpp
  lib/ProgramOptions/Option.cpp
  lib/ProgramOptions/ProgramOptions.cpp
Labels: 3 Documentation, 9 Ready to Merge

#10602 Fix Foxx Failover + Ungreylist foxx failover test
  js/server/modules/@arangodb/foxx/manager.js
  js/server/modules/@arangodb/foxx/queues/manager.js
  tests/js/client/resilience/foxxmaster-grey.js
Labels: 3.6.0

#10580 wait for suicide to actually take place before we fail this
  lib/Basics/debugging.cpp
Labels: 3.6.0, 9 Ready to Merge

#10607 wait for suicide to actually take place before we fail this
  js/client/modules/@arangodb/process-utils.js
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testing.js
  js/client/modules/@arangodb/testsuites/audit.js
  js/client/modules/@arangodb/testsuites/config.js
  js/client/modules/@arangodb/testsuites/dfdb.js
  js/client/modules/@arangodb/testsuites/export.js
  js/client/modules/@arangodb/testsuites/gtest.js
  js/client/modules/@arangodb/testsuites/recovery.js
  js/client/modules/@arangodb/testsuites/upgrade.js
  js/client/modules/@arangodb/testsuites/version.js
  lib/Basics/debugging.cpp
  tests/js/server/aql/aql-query-cache-noncluster.js
  tests/js/server/replication/ongoing/replication-ongoing.js
  tests/js/server/replication/static/replication-static.js
  tests/js/server/replication/sync/replication-sync.js
  tests/rb/HttpInterface/api-view-arangosearch-spec-noncluster.rb
Labels: 9 Ready to Merge

#10577 Fix smart BFS stack
  CHANGELOG
  arangod/Aql/OptimizerRulesCluster.cpp
Labels: 1 Bug, 3 Graph, 3.6.0

#10592 Finalize documentation of --force flag for hotbackup.
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_create.md
  arangosh/Backup/BackupFeature.cpp
Labels: 3 Documentation, 3.6.0

#10631 Explain now prints the RETURN of a spliced subquery again
  js/common/modules/@arangodb/aql/explainer.js
Labels: 1 Bug, 3.6.0

#10629 Bug fix/ui library cleanup
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/backbone-min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/d3.fisheye.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/d3.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/d3.v3.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/jquery.contextmenu.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/jquery.form.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/jquery.hotkeys.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/jquery.noty.packaged.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/jquery.textfill.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/jsoneditor-min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/marked.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/md5.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/nv.d3.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/popper.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/strftime-min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/supervisor.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/tippy.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/typeahead.bundle.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/underscore-min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/worker.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userView.js
  js/apps/system/_admin/aardvark/APP/manifest.json
  js/apps/system/_admin/aardvark/APP/react/package-lock.json
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/src/App.js
Labels: 3.6.0

#10539 Bug fix 3.4/fix internal issue 4451
  CHANGELOG
  arangod/Auth/UserManager.cpp
  arangod/Auth/UserManager.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangosh/Restore/RestoreFeature.cpp
  js/client/modules/@arangodb/testsuites/dump.js
  tests/js/server/dump/cleanup-alter-user.js
  tests/js/server/dump/cleanup-nothing.js
  tests/js/server/dump/dump-authentication.js
Labels: 9 Ready to Merge, for 3.4.9

#10636 already reap lock bugfix
  arangod/RocksDBEngine/RocksDBCollection.cpp
Labels: 3.6.0, 9 Ready to Merge

#10637 @Simran-B
  arangosh/Import/ImportFeature.cpp
Labels: 1 Bug, 3 Documentation, 3.6.0, 9 Ready to Merge

#10632 fix/cppcheck
  arangod/Actions/actions.cpp
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Agency/AddFollower.cpp
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/Agent.h
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Aql/Aggregator.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/Aql/ResourceUsage.h
  arangod/Cache/FrequencyBuffer.h
  arangod/Cluster/ActionDescription.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/IResearch/AqlHelper.cpp
  arangod/MMFiles/MMFilesFulltextIndex.cpp
  arangod/Pregel/TypedBuffer.h
  arangod/RestHandler/RestUploadHandler.cpp
  arangod/RestServer/counter.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBIterators.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/V8Server/v8-actions.cpp
  arangod/V8Server/v8-user-structures.cpp
  arangosh/Restore/RestoreFeature.cpp
  lib/ApplicationFeatures/ShellColorsFeature.h
  lib/Basics/system-functions.cpp
  lib/Containers/details/short_alloc.h
  lib/Endpoint/EndpointIp.h
  lib/Endpoint/EndpointUnixDomain.h
  lib/Futures/Future.h
  lib/Futures/SharedState.h
  lib/Futures/Try.h
  lib/Futures/backports.h
  lib/ProgramOptions/Parameters.h
  lib/V8/v8-buffer.h
  tests/Futures/Future-test.cpp
  tests/Futures/Try-test.cpp
  utils/cppcheck.sh
Labels: 3.6.0

#10630 Show MMFiles deprecation warning
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterEngine.h
  arangod/MMFiles/MMFilesEngine.cpp
Labels: 1 Feature, 3.6.0, 9 Ready to Merge

#10449 Docs: Update README.md
  README.md
Labels: 3 Documentation, 9 Ready to Merge

#10643 fix startup when using multiple coordinators.
  arangod/Auth/UserManager.cpp
Labels: 3.6.0

#10642 try to make shell-ttl less time-dependent
  tests/js/common/shell/shell-ttl.js
Labels: 9 Ready to Merge

#9292 Fix _admin/cluster/removeServer error message
  js/actions/api-cluster.js
Labels: 1 Bug, 3 API, 9 Review Required

#10654 Bug fix 3.6/always create fishbowl collections
  arangod/VocBase/Methods/UpgradeTasks.cpp
Labels: 3.6.0

#10657 [3.6] admin statistics uptime broken
  arangod/RestServer/MetricsFeature.cpp
  tests/rb/HttpInterface/api-statistics-spec.rb
Labels: 1 Bug, 3.6.0, Team Clifton

#10656 add validation for database replication factor and write concern
  arangod/Graph/GraphManager.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingInfo.h
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Databases.cpp
  js/server/modules/@arangodb/foxx/queues/manager.js
  tests/js/client/server_permissions/test-sharding-restrictions-cluster.js
  tests/js/common/shell/shell-cluster-collection.js
  tests/js/common/shell/shell-one-shard.js
  tests/js/server/shell/shell-collection-properties-cluster-spec.js
  tests/js/server/shell/shell-general-graph-creation-cluster.js
Labels: 9 Ready to Merge

#10658 admin statistics uptime broken
  CHANGELOG
  arangod/RestServer/MetricsFeature.cpp
  tests/rb/HttpInterface/api-statistics-spec.rb
Labels: 1 Bug, Team Clifton

#10621 avoid modifying `_indexes` vector without acquiring its write-lock
  3rdParty/rocksdb/6.2/db/wal_manager.cc
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBMetadata.h
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBSettingsManager.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/vocbase.cpp
Labels: 3.6.0, 9 WIP

#10304 Bug fix/dont create dangling branches
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Optimizer.cpp
  arangod/Aql/OptimizerRulesCluster.cpp
  tests/Graph/GraphTestTools.h
  tests/js/server/aql/aql-modify-subqueries.js
Labels: 1 Bug, 9 Ready to Merge

#10649 Call it identifiers consistently (rename handle -> id)
  CHANGELOG
  Documentation/DocuBlocks/IndexHandle.md
  Documentation/DocuBlocks/InsertEdgeCol.md
  Documentation/DocuBlocks/Rest/Bulk/import_document.md
  Documentation/DocuBlocks/Rest/Bulk/import_json.md
  Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
  Documentation/DocuBlocks/Rest/Documents/delete_remove_document.md
  Documentation/DocuBlocks/Rest/Documents/get_read_document.md
  Documentation/DocuBlocks/Rest/Documents/get_read_multiple_documents.md
  Documentation/DocuBlocks/Rest/Documents/patch_update_document.md
  Documentation/DocuBlocks/Rest/Documents/patch_update_multiple_documents.md
  Documentation/DocuBlocks/Rest/Documents/post_create_document.md
  Documentation/DocuBlocks/Rest/Documents/post_create_multiple_document.md
  Documentation/DocuBlocks/Rest/Documents/put_replace_document.md
  Documentation/DocuBlocks/Rest/Documents/put_replace_multiple_documents.md
  Documentation/DocuBlocks/Rest/Graph Edges/get_read_in_out_edges.md
  Documentation/DocuBlocks/Rest/Indexes/get_api_reads_index.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_delete.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_fulltext.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_hash.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_ttl.md
  Documentation/DocuBlocks/col_dropIndex.md
  Documentation/DocuBlocks/documentsCollectionExists.md
  Documentation/DocuBlocks/documentsCollectionInsert.md
  Documentation/DocuBlocks/documentsCollectionName.md
  Documentation/DocuBlocks/documentsCollectionRemove.md
  Documentation/DocuBlocks/documentsCollectionReplace.md
  Documentation/DocuBlocks/documentsCollectionUpdate.md
  Documentation/DocuBlocks/documentsDocumentExists.md
  Documentation/DocuBlocks/documentsDocumentName.md
  Documentation/DocuBlocks/documentsDocumentReplace.md
  Documentation/DocuBlocks/documentsDocumentUpdate.md
  Documentation/DocuBlocks/dropIndex.md
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestEdgesHandler.cpp
  arangod/V8Server/v8-collection.cpp
  arangod/V8Server/v8-query.cpp
  arangod/V8Server/v8-vocindex.cpp
  js/server/modules/@arangodb/arango-collection.js
  lib/Basics/errors.dat
  tests/rb/HttpInterface/api-document-delete-spec.rb
  tests/rb/HttpInterface/api-document-read-spec.rb
  tests/rb/HttpInterface/api-document-update-spec.rb
  tests/rb/HttpInterface/api-edges-spec.rb
Labels: 3 Documentation, 3.6.0, 9 Ready to Merge

#10500 Marked some unlock functions noexcept
  arangod/Cache/Cache.cpp
  arangod/Cache/Cache.h
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/Cache/ManagerTasks.cpp
  arangod/Cache/Metadata.cpp
  arangod/Cache/Metadata.h
  arangod/Cache/Table.cpp
  arangod/Cache/Table.h
  arangod/Cache/TransactionManager.cpp
  arangod/Cache/TransactionManager.h
  arangod/GeneralServer/VstCommTask.cpp
  arangod/Network/ConnectionPool.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  lib/Basics/ReadWriteLock.cpp
  lib/Basics/ReadWriteLock.h
  lib/Basics/ReadWriteSpinLock.cpp
  lib/Basics/ReadWriteSpinLock.h
  lib/Basics/WriteLocker.h
  lib/Basics/cpu-relax.h
  lib/CMakeLists.txt
Labels: 9 Ready to Merge

#10655 add validation for database replication factor and write concern
  arangod/Graph/GraphManager.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingInfo.h
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Databases.cpp
  js/server/modules/@arangodb/foxx/queues/manager.js
  tests/js/client/server_permissions/test-sharding-restrictions-cluster.js
  tests/js/common/shell/shell-cluster-collection.js
  tests/js/common/shell/shell-one-shard.js
  tests/js/server/shell/shell-collection-properties-cluster-spec.js
  tests/js/server/shell/shell-general-graph-creation-cluster.js
Labels: 3.6.0, 9 Ready to Merge

#10659 undefined behaviour on node delete
  CHANGELOG
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/Store.cpp
  tests/Agency/NodeTest.cpp
  tests/CMakeLists.txt
Labels: 1 Bug, Team Clifton

#10684 Bug fix 3.6/round costs to remove costs
  js/server/modules/@arangodb/aql-helper.js
  tests/js/server/aql/aql-graph-traverser.js
Labels: 3.6.0, 9 Waiting for Jenkins

#10679 [3.6] Bug fix/dont create dangling branches
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Optimizer.cpp
  arangod/Aql/OptimizerRulesCluster.cpp
  tests/Graph/GraphTestTools.h
  tests/js/server/aql/aql-modify-subqueries.js
Labels: 9 Ready to Merge

#10675 [3.6] avoid modifying vector without acquiring its write-lock
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBMetadata.h
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBSettingsManager.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/vocbase.cpp
Labels: 3.6.0, 9 Ready to Merge

#10664 Bug fix/small issues 10122019
  CHANGELOG
  arangod/Cluster/RestClusterHandler.cpp
  arangod/GeoIndex/Near.cpp
  arangod/GeoIndex/Near.h
  arangod/RestServer/InitDatabaseFeature.cpp
  lib/Geo/GeoJson.cpp
Labels: 9 Ready to Merge

#10685 [3.6] agency node delete undefined
  CHANGELOG
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/Store.cpp
  tests/Agency/NodeTest.cpp
  tests/CMakeLists.txt
Labels: 1 Bug, 9 WIP, Team Clifton

#10688 Bug fix/fix undeterministic traversal test
  tests/js/server/aql/aql-graph-traverser.js
Labels: 9 Ready to Merge

#10691 bug-fix 3.6 single-edge-definition-editing
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  tests/js/common/shell/shell-general-graph.js
Labels: 3.6.0

#10694 [3.6] Bug fix/fix undeterministic traversal test
  tests/js/server/aql/aql-graph-traverser.js
Labels: 9 Ready to Merge

#10699 fix some UI issues for database defaults
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
Labels: 9 Ready to Merge

#10698 fix some UI issues for database defaults
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
Labels: 9 Ready to Merge

#10704 add test (#10702)
  tests/js/common/aql/aql-view-arangosearch-feature.js
Labels: 3.6.0, 9 Ready to Merge

#10673 covering index wins late materialization
  arangod/Aql/CalculationNodeVarFinder.cpp
  arangod/Aql/CalculationNodeVarFinder.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  arangod/Aql/IndexNodeOptimizerRules.cpp
  arangod/CMakeLists.txt
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-2.js
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-rocksdb.js
Labels: 3.6.0, 9 Ready to Merge

#10633 Feature/wer crashdump analysis
  js/client/modules/@arangodb/crash-utils.js
  js/client/modules/@arangodb/process-utils.js
  js/client/modules/@arangodb/result-processing.js
  js/client/modules/@arangodb/testing.js
Labels: 3.6.1

#10618 Improve scheduler latency.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterRepairOperations.cpp
  arangod/Cluster/RebootTracker.cpp
  arangod/Cluster/RebootTracker.h
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
  arangod/GeneralServer/HttpCommTask.h
  arangod/GeneralServer/VstCommTask.h
  arangod/Pregel/Algos/SCC.cpp
  arangod/Scheduler/Scheduler.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  tests/Mocks/Servers.cpp
Labels: 1 Bug

#10693 subquery uses document in not calc nodes
  arangod/Aql/CalculationNodeVarFinder.cpp
  arangod/Aql/CalculationNodeVarFinder.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/IndexNodeOptimizerRules.cpp
  arangod/CMakeLists.txt
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-2.js
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-rocksdb.js
Labels: 9 Ready to Merge

#10705 Port scheduler latency improvements to 3.6.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterRepairOperations.cpp
  arangod/Cluster/RebootTracker.cpp
  arangod/Cluster/RebootTracker.h
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
  arangod/GeneralServer/HttpCommTask.h
  arangod/GeneralServer/VstCommTask.h
  arangod/Pregel/Algos/SCC.cpp
  arangod/Scheduler/Scheduler.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  tests/Mocks/Servers.cpp
Labels: 1 Bug, 9 Ready to Merge

#10616 Fix shell-compaction-mmfiles-noncluster-timecritical and ungreylist
  tests/js/server/shell/shell-compaction-mmfiles-noncluster.js
Labels: 9 Ready to Merge

#10615 Ungreylist shell-compaction-seq-mmfiles-noncluster-timecritical
  tests/js/server/shell/shell-compaction-seq-mmfiles-noncluster.js
Labels: 9 Ready to Merge

#10714 Optimized AstNode members removals while condition optimizing
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/Condition.cpp
  arangod/Transaction/Methods.cpp
Labels: 9 WIP

#10712 restrict database length to 64 characters again
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/VocbaseInfo.cpp
  tests/js/common/shell/01_shell-database.js
Labels: 3.6.0

#10718 Fix disabling of optimizer rules.
  arangod/Aql/OptimizerRulesFeature.cpp
Labels: 3.6.0

#10723 css issue
  js/apps/system/_admin/aardvark/APP/frontend/scss/_queryView.scss
Labels: 3.6.0

#10716 fix context.incrScanned
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/IndexExecutor.cpp
Labels: 3.6.0

#10731 Bug fix/agency ttl handle
  3rdParty/iresearch/core/search/tfidf.cpp
  CHANGELOG
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  tests/js/client/agency/agency-test.js
Labels: 1 Bug, 9 WIP, Team Clifton

#10729 [3.6] - Add rocksdb.exclusive-write tests
  tests/js/client/server_permissions/exclusive-collections-off-noncluster-rocksdb.js
  tests/js/client/server_permissions/exclusive-collections-off-rocksdb.js
  tests/js/client/server_permissions/exclusive-collections-on-noncluster-rocksdb.js
  tests/js/client/server_permissions/exclusive-collections-on-rocksdb.js
Labels: 3.6.0, 9 Ready to Merge

#10738 [devel] - Add rocksdb.exclusive-write tests
  tests/js/client/server_permissions/exclusive-collections-off-noncluster-rocksdb.js
  tests/js/client/server_permissions/exclusive-collections-off-rocksdb.js
  tests/js/client/server_permissions/exclusive-collections-on-noncluster-rocksdb.js
  tests/js/client/server_permissions/exclusive-collections-on-rocksdb.js
Labels: 9 Ready to Merge

#10737 Bug fix 3.6/backup timeout trx abort+docu
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_create.md
  arangod/Cluster/ClusterMethods.cpp
Labels: 3.6.0, 9 Review Required, 9 Waiting for Jenkins

#10743 fix a misleading message during maintenance
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
Labels: 3.6.0, 9 Review Required

#10748 potential formatting fix for explainer
  arangod/Aql/CollectionAccessingNode.h
  arangod/Aql/Query.cpp
  js/common/modules/@arangodb/aql/explainer.js
Labels: 9 Ready to Merge

#10751 Bug fix 3.6/issue 10725
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
Labels: 9 Ready to Merge

#10647 Call it identifiers consistently (rename handle -> id)
  CHANGELOG
  Documentation/DocuBlocks/IndexHandle.md
  Documentation/DocuBlocks/InsertEdgeCol.md
  Documentation/DocuBlocks/Rest/Bulk/import_document.md
  Documentation/DocuBlocks/Rest/Bulk/import_json.md
  Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
  Documentation/DocuBlocks/Rest/Documents/delete_remove_document.md
  Documentation/DocuBlocks/Rest/Documents/get_read_document.md
  Documentation/DocuBlocks/Rest/Documents/get_read_multiple_documents.md
  Documentation/DocuBlocks/Rest/Documents/patch_update_document.md
  Documentation/DocuBlocks/Rest/Documents/patch_update_multiple_documents.md
  Documentation/DocuBlocks/Rest/Documents/post_create_document.md
  Documentation/DocuBlocks/Rest/Documents/post_create_multiple_document.md
  Documentation/DocuBlocks/Rest/Documents/put_replace_document.md
  Documentation/DocuBlocks/Rest/Documents/put_replace_multiple_documents.md
  Documentation/DocuBlocks/Rest/Graph Edges/get_read_in_out_edges.md
  Documentation/DocuBlocks/Rest/Indexes/get_api_reads_index.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_delete.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_fulltext.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_hash.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_ttl.md
  Documentation/DocuBlocks/col_dropIndex.md
  Documentation/DocuBlocks/documentsCollectionExists.md
  Documentation/DocuBlocks/documentsCollectionInsert.md
  Documentation/DocuBlocks/documentsCollectionName.md
  Documentation/DocuBlocks/documentsCollectionRemove.md
  Documentation/DocuBlocks/documentsCollectionReplace.md
  Documentation/DocuBlocks/documentsCollectionUpdate.md
  Documentation/DocuBlocks/documentsDocumentExists.md
  Documentation/DocuBlocks/documentsDocumentName.md
  Documentation/DocuBlocks/documentsDocumentReplace.md
  Documentation/DocuBlocks/documentsDocumentUpdate.md
  Documentation/DocuBlocks/dropIndex.md
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestEdgesHandler.cpp
  arangod/V8Server/v8-collection.cpp
  arangod/V8Server/v8-query.cpp
  arangod/V8Server/v8-vocindex.cpp
  js/server/modules/@arangodb/arango-collection.js
  lib/Basics/errors.dat
  tests/rb/HttpInterface/api-document-delete-spec.rb
  tests/rb/HttpInterface/api-document-read-spec.rb
  tests/rb/HttpInterface/api-document-update-spec.rb
  tests/rb/HttpInterface/api-edges-spec.rb
Labels: 3 Documentation, 3.6.0, 9 Ready to Merge

#10761 a few usability fixes for minReplicationFactor/writeConcern
  arangod/Sharding/ShardingInfo.cpp
  arangod/VocBase/Methods/Collections.cpp
  tests/js/common/shell/shell-one-shard.js
Labels: 3.6.0, 9 Ready to Merge

#10765 [3.6] Bug fix/collection create failure cleanup
  arangod/Cluster/ClusterInfo.cpp
  tests/js/common/shell/shell-cluster-collection.js
Labels: 1 Bug, 3 Cluster

#10763 Docs: More fixes for write concern (#10663)
  Documentation/DocuBlocks/Rest/Administration/get_admin_metrics.md
  Documentation/DocuBlocks/Rest/Administration/get_api_cluster_endpoints.md
  Documentation/DocuBlocks/Rest/Analyzers/delete_api_analyzer.md
  Documentation/DocuBlocks/Rest/Analyzers/get_api_analyzer.md
  Documentation/DocuBlocks/Rest/Analyzers/get_api_analyzers.md
  Documentation/DocuBlocks/Rest/Analyzers/post_api_analyzer.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_download.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_upload.md
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Database/get_api_database_current.md
  Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
  Documentation/DocuBlocks/Rest/Graph/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
  Documentation/DocuBlocks/collectionProperties.md
  Documentation/DocuBlocks/serverSSLProtocol.md
  Documentation/Scripts/codeBlockReader.py
  README_maintainers.md
  arangod/MMFiles/MMFilesCompactionFeature.cpp
Labels: 3 Documentation, 3.6.0, 9 Ready to Merge

#10399 auto-flush more exotic column families from time to time
  CHANGELOG
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBBackgroundThread.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
Labels: 3.5.4, 9 Ready to Merge

#10417 Heartbeat Agency Endpoint Update
  arangod/Cluster/HeartbeatThread.cpp
Labels: 3.5.4, 9 Ready to Merge

#10531 [3.5] Bug fix/dont create dangling branches
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Optimizer.cpp
  arangod/Aql/OptimizerRulesCluster.cpp
  tests/Graph/GraphTestTools.h
  tests/js/server/aql/aql-modify-subqueries.js
Labels: 1 Bug, 3.5.4, 9 Ready to Merge

#10556 check before foxx-heal
  arangod/RestHandler/RestStatusHandler.cpp
  arangosh/Restore/RestoreFeature.cpp
  tests/js/client/server_permissions/test-hardened-rest-apis.js
Labels: 9 Ready to Merge

#10405 3.5 -- kill AQL query after timeout (#10363)
  CHANGELOG
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryOptions.cpp
  arangod/Aql/QueryOptions.h
  tests/js/server/aql/aql-options.js
Labels: 3.5.4, 9 Waiting for Jenkins

#10603 Bug fix 3.5/restore feature perms
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
Labels: 3.5.4, 9 Ready to Merge

#10591 Remove broken option save-current.
  arangosh/Backup/BackupFeature.cpp
  arangosh/Backup/BackupFeature.h
Labels: 1 Bug, 3.5.4, 9 Waiting for Jenkins

#10622 avoid modifying `_indexes` vector without acquiring its write-lock
  CHANGELOG
  arangod/RocksDBEngine/RocksDBCollection.cpp
Labels: 3.5.4, 9 Ready to Merge

#10628 Bug fix 3.5/ungreylist foxx test
  js/server/modules/@arangodb/foxx/queues/manager.js
  tests/js/client/resilience/foxxmaster-grey.js
Labels: 3 - Testing, 3.5.4, 9 Waiting for Jenkins

#10644 speculative fix for multi-coordinator bootstrap
  arangod/Auth/UserManager.cpp
Labels: 9 Ready to Merge

#10665 slightly speedup geo functionality
  arangod/GeoIndex/Near.cpp
  arangod/GeoIndex/Near.h
  lib/Basics/StringUtils.h
  lib/Geo/GeoJson.cpp
Labels: 3.5.4, 9 Ready to Merge

#10676 [3.5] avoid modifying vector without acquiring its write-lock
  arangod/MMFiles/MMFilesCollection.cpp
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollectionMeta.cpp
  arangod/RocksDBEngine/RocksDBCollectionMeta.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBSettingsManager.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/vocbase.cpp
Labels: 3.5.4, 9 Waiting for Jenkins

#10681 [3.5] Bug fix/smart bfs stack size
  CHANGELOG
Labels: 1 Bug, 3.5.4, 9 Ready to Merge

#10692 Bug fix 3.5/single edge definition editing
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  tests/js/common/shell/shell-general-graph.js
Labels: 3.5.4, 9 Ready to Merge

#10695 [3.5] Bug fix/fix undeterministic traversal test
  tests/js/server/aql/aql-graph-traverser.js
Labels: 3.5.4, 9 Waiting for Jenkins

#10771 Added masking outdated segments while completing consolidation
  3rdParty/iresearch/core/index/index_writer.cpp
  CHANGELOG
Labels: 3.5.4, 9 Ready to Merge

#10703 properly set database context
  CHANGELOG
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  tests/js/common/aql/aql-view-arangosearch-feature.js
Labels: 3.5.4, 9 Waiting for Jenkins

#10707 Port scheduler latency fixes to 3.5.
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/GeneralCommTask.h
  arangod/GeneralServer/HttpCommTask.h
  arangod/GeneralServer/VstCommTask.h
  arangod/Scheduler/Scheduler.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
Labels: 3.5.4, 9 Waiting for Jenkins

#10752 fixed issue 10725
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
  js/apps/system/_admin/aardvark/APP/frontend/src/ace.min.js
Labels: 3.5.4, 9 Ready to Merge

#10686 [3.5] agency fixes for node delete from devel
  CHANGELOG
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/Store.cpp
  tests/Agency/NodeTest.cpp
  tests/CMakeLists.txt
Labels: 1 Bug, 3.5.4, 9 Waiting for Jenkins, Team Clifton

#10418 Fixing heartbeat agency update.
  arangod/Cluster/HeartbeatThread.cpp
Labels: 9 Waiting for Jenkins, for 3.4.9

#10398 auto-flush more exotic column families from time to time
  CHANGELOG
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBBackgroundThread.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
Labels: for 3.4.9

#10437 Improve syncer error message (#10404)
  arangod/Replication/utilities.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
Labels: for 3.4.9

#10401 3.4 -- DEVSUP-492 (fix upsert with empty objects)
  CHANGELOG
  arangod/Aql/Ast.cpp
  tests/js/server/aql/aql-modify.js
  tests/rb/HttpInterface/api-collection-rocksdb-spec.rb
Labels: for 3.4.9

#10444 fixed issue #10440: Incorrect sorting with sort criteria partially covered by index
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/SortCondition.cpp
  tests/js/server/aql/aql-optimizer-rule-use-index-for-sort.js
Labels: 9 Ready to Merge, for 3.4.9

#10542 Allow the optimizer to use indexes
  CHANGELOG
  arangod/Indexes/Index.cpp
  tests/js/server/aql/aql-optimizer-indexes.js
Labels: 9 Ready to Merge

#10604 Bug fix 3.4/restore feature perms
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/Utils/ExecContext.h
Labels: 9 Waiting for Jenkins, for 3.4.9

#10550 Cherry picked bug-fix for GharialAPI to return name in LIST
  CHANGELOG
  arangod/Graph/GraphManager.cpp
  tests/js/client/http/api-gharial-spec.js
Labels: 1 Bug, 9 Waiting for Jenkins, for 3.4.9

#10777 [3.6] reboot tracking for empty rebootid
  CHANGELOG
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: 1 Bug, 3.6.0, 9 Waiting for Jenkins

#10586 [3.4] Bug fix/dont create dangling branches
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/OptimizerRulesCluster.cpp
  tests/js/server/aql/aql-modify-subqueries.js
Labels: 1 Bug, 9 Waiting for Jenkins, for 3.4.9

#10333 [3.5] Missing post failure on readlock in SynchronizeShard & RebootTracker
  CHANGELOG
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/CMakeLists.txt
  arangod/Cluster/CallbackGuard.cpp
  arangod/Cluster/CallbackGuard.h
  arangod/Cluster/RebootTracker.cpp
  arangod/Cluster/RebootTracker.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  tests/Aql/EngineInfoContainerCoordinatorTest.cpp
Labels: 3.5.4, 9 WIP

#10682 [3.4] Bug fix/smart bfs stack size
  CHANGELOG
Labels: 1 Bug, 9 Waiting for Jenkins, for 3.4.9

#10696 [3.4] Bug fix/fix undeterministic traversal test
  tests/js/server/aql/aql-graph-traverser.js
Labels: 9 Waiting for Jenkins, for 3.4.9

#10697 bug-fix 3.4 single-edge-definition-editing
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  tests/js/common/shell/shell-general-graph.js
Labels: 9 Waiting for Jenkins, for 3.4.9

#10753 fixed issue 10725
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
Labels: 9 Ready to Merge, 9 Waiting for Jenkins

#10774 Fixed removing outdated readers from cache
  3rdParty/iresearch/core/index/index_writer.cpp
  CHANGELOG
Labels: for 3.4.9

#10627 Bug fix 3.4/ungreylist foxx test
  js/server/modules/@arangodb/foxx/queues/manager.js
  tests/js/client/resilience/foxxmaster-grey.js
Labels: for 3.4.9
