Repository arangodb/arangodb, pull requests merged in 2019-08, with the labels that each got.

#9610 fix typo
  README_maintainers.md
Labels: 3 Documentation

#9611 upgrade Starter 0.14.11
  CHANGELOG
  CMakeLists.txt
  VERSION
  VERSIONS
Labels: 3 Build, 3 Starter

#9608 Fast Controlled Leaderchange
  CHANGELOG
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/ResignShardLeadership.cpp
  arangod/Cluster/ResignShardLeadership.h
  arangod/Cluster/UpdateCollection.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
Labels: 9 WIP

#9602 Bug fix/fix swagger datatype (#9045)
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
  js/apps/system/_admin/aardvark/APP/api-docs.json
  utils/generateSwagger.py
Labels: 1 Bug, 3 Documentation, 3 Swagger, 9 Ready to Merge

#9557 Documentation 3.4/example generation improvements
  Documentation/DocuBlocks/Rest/Administration/get_engine.md
  Documentation/DocuBlocks/Rest/Bulk/batch_processing.md
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_figures.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_rotate.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_dump.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_range.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_inventory.md
  Documentation/DocuBlocks/Rest/wal/get_admin_wal_properties.md
  Documentation/DocuBlocks/Rest/wal/get_admin_wal_transactions.md
  Documentation/DocuBlocks/Rest/wal/put_admin_wal_properties.md
  Documentation/DocuBlocks/collectionFigures.md
  Documentation/DocuBlocks/ensureUniqueSkiplist.md
  Documentation/DocuBlocks/walPropertiesGet.md
  Documentation/DocuBlocks/walPropertiesSet.md
  Documentation/Examples/RestBatchImplicitBoundary.generated
  Documentation/Examples/RestBatchMultipartHeader.generated
  Documentation/Examples/RestCollectionGetCollectionFigures_mmfiles.generated
  Documentation/Examples/RestCollectionGetCollectionFigures_rocksdb.generated
  Documentation/Examples/RestCollectionRotateNoJournal_mmfiles.generated
  Documentation/Examples/RestCollectionRotate_mmfiles.generated
  Documentation/Examples/RestEngine_mmfiles.generated
  Documentation/Examples/RestEngine_rocksdb.generated
  Documentation/Examples/RestReplicationDumpEmpty_mmfiles.generated
  Documentation/Examples/RestReplicationDump_mmfiles.generated
  Documentation/Examples/RestReplicationInventoryIndexes_mmfiles.generated
  Documentation/Examples/RestReplicationInventory_mmfiles.generated
  Documentation/Examples/RestWalPropertiesGet_mmfiles.generated
  Documentation/Examples/RestWalPropertiesPut_mmfiles.generated
  Documentation/Examples/RestWalTransactionsGet_mmfiles.generated
  Documentation/Examples/WalPropertiesGet_mmfiles.generated
  Documentation/Examples/WalPropertiesSet_mmfiles.generated
  Documentation/Examples/collectionFigures_mmfiles.generated
  Documentation/README_maintainers.md
  Documentation/Scripts/exampleHeader.js
  js/apps/system/_admin/aardvark/APP/api-docs.json
  js/client/bootstrap/modules/internal.js
  utils/generateExamples.js
  utils/generateExamples.py
Labels: 3 Documentation

#9491 Aardvark: Add k Shortest Paths example graph to UI
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalGraphTable.ejs
  js/common/modules/@arangodb/examples/examples.js
  js/common/modules/@arangodb/graph-examples/example-graph.js
Labels: 1 Feature, 3 Graph, 3 UI

#9653 Create TakeoverShardLeader job.
  arangod/CMakeLists.txt
  arangod/Cluster/Action.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/TakeoverShardLeadership.cpp
  arangod/Cluster/TakeoverShardLeadership.h
  arangod/Cluster/UpdateCollection.cpp
  tests/Maintenance/MaintenanceTest.cpp
Labels: 1 Bug

#9613 add the ability to have cluster special examples
  utils/generateExamples.js
  utils/generateExamples.py
  utils/generateExamples.sh
Labels: 3 Documentation, 9 Review Required

#9646 Set jsunity output to gtest style
  UnitTests/unittest.js
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testing.js
  js/common/modules/jsunity.js
  js/common/modules/jsunity/jsunity.js
Labels: 3 - Testing

#9642 [3.4] Fast Leader Change
  CHANGELOG
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/ResignShardLeadership.cpp
  arangod/Cluster/ResignShardLeadership.h
  arangod/Cluster/UpdateCollection.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
Labels: 9 WIP

#9661 Aardvark: Add k Shortest Paths example graph to UI (#9491)
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalGraphTable.ejs
  js/common/modules/@arangodb/examples/examples.js
  js/common/modules/@arangodb/graph-examples/example-graph.js
Labels: 1 Feature, 3 Graph, 3 UI

#9663 add the ability to have cluster special examples
  utils/generateExamples.js
  utils/generateExamples.py
  utils/generateExamples.sh
Labels: 3 Documentation, 9 Ready to Merge

#9523 Feature/rebootid notice changes
  arangod/CMakeLists.txt
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterTypes.cpp
  arangod/Cluster/ClusterTypes.h
  arangod/Cluster/RebootTracker.cpp
  arangod/Cluster/RebootTracker.h
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
  js/actions/api-cluster.js
  js/common/bootstrap/errors.js
  lib/ApplicationFeatures/ApplicationServer.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  tests/CMakeLists.txt
  tests/Cluster/RebootTrackerTest.cpp
  tests/IResearch/AgencyMock.cpp
  tests/Mocks/Servers.cpp
  tests/Mocks/Servers.h
  tests/V8Server/v8-users-test.cpp
Labels: 9 Ready to Merge

#9686 Fixed error code to not re-use an old one
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
Labels: 1 Bug

#9698 [3.5] agency node fixes
  CHANGELOG
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/Store.cpp
  tests/Cluster/ClusterInfo-test.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchLinkCoordinator-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/js/client/agency/agency-test.js
Labels: Team Clifton

#9708 Bugfix 3.3: Correct calculation of rocksdb statistics to be sum of column families
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBThrottle.h
Labels: 1 Bug, 2 Fixed

#9700 back ported node corrections from 3.4
  CHANGELOG
  Documentation/Scripts/man.sed
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/Store.cpp
  tests/Cluster/ClusterInfo-test.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchLinkCoordinator-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/js/client/agency/agency-test.js
Labels: 9 WIP, Team Clifton

#9304 Fix some CMake warnings related to set() + docstrings
  3rdParty/CMakeLists.txt
  3rdParty/s2geometry/CMakeLists.txt
  CMakeLists.txt
Labels: 1 Bug, 3 Build, 9 Review Required

#9718 Fix agency bugs.
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/State.cpp
  arangod/Cluster/TakeoverShardLeadership.cpp
  tests/js/client/agency/agency-test.js
Labels: 1 Bug

#9729 Fix an agency bug found in Windows tests.
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/State.cpp
  tests/js/client/agency/agency-test.js
Labels: 1 Bug

#9728 Fix an agency bug found in Windows tests.
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/State.cpp
  arangod/Cluster/TakeoverShardLeadership.cpp
  tests/js/client/agency/agency-test.js
Labels: 1 Bug

#9680 Changelog 3.4.8
  CHANGELOG
Labels: 3 Documentation

#9752 issue #9654
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  lib/ApplicationFeatures/ApplicationServer.h
  lib/ApplicationFeatures/RocksDBOptionFeature.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.h
Labels: 9 Ready to Merge

#9751 issue #9654: make `--rocksdb.max-write-buffer-number` work
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.cpp
  lib/ApplicationFeatures/RocksDBOptionFeature.h
Labels: 9 Ready to Merge

#9773 port change from devel by @danielhlarkin
  arangod/Pregel/Conductor.cpp
Labels: 9 Ready to Merge

#9777 fix potential spurious wakeups in scheduler code
  CHANGELOG
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
Labels: 9 Ready to Merge

#9763 Bug fix/implement windows maintenance tests
  tests/CMakeLists.txt
  tests/Maintenance/MaintenanceTest.cpp
  tests/Maintenance/generateRcFile.sh
  tests/Maintenance/json.rc
  tests/Maintenance/jsonresource.h
Labels: 9 Ready to Merge

#9772 Bug fix 3.5/mark fulltext near etc as cacheable
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
Labels: 9 Ready to Merge

#9768 show query string length and cacheability in explain output
  CHANGELOG
  js/common/modules/@arangodb/aql/explainer.js
Labels: 9 Ready to Merge

#9769 show query string length and cacheability in explain output
  CHANGELOG
  js/common/modules/@arangodb/aql/explainer.js
Labels: 9 Ready to Merge

#9722 [3.5] clean up your crap, dbservers. alright, i'll do it.
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/Store.cpp
  arangod/Agency/StoreCallback.cpp
  arangod/Agency/StoreCallback.h
Labels: 1 Bug, 9 WIP, Team Clifton

#9723 [3.4] back port of agency call back cleanup
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/Store.cpp
  arangod/Agency/StoreCallback.cpp
  arangod/Agency/StoreCallback.h
Labels: 1 Bug, 9 WIP, Team Clifton

#9709 remove 404-ed callbacks from agency
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/Store.cpp
  arangod/Agency/StoreCallback.cpp
  arangod/Agency/StoreCallback.h
Labels: 9 WIP, Team Clifton

#9791 Bug fix 3.4/multi bugs
  CHANGELOG
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/SynchronizeShard.cpp
Labels: 9 Ready to Merge

#9792 Bug fix 3.5/multi bugs
  CHANGELOG
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
Labels: 9 Ready to Merge

#9780 3.5 -- intermediate commit stats
  CHANGELOG
  Documentation/DocuBlocks/Rest/Administration/get_admin_statistics.md
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/MMFiles/MMFilesTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/Statistics/Descriptions.cpp
  arangod/Statistics/ServerStatistics.cpp
  arangod/Statistics/ServerStatistics.h
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsWorker.cpp
  arangod/V8Server/v8-statistics.cpp
  js/client/bootstrap/modules/internal.js
  js/server/bootstrap/modules/internal.js
  tests/js/client/shell/shell-transaction.js
  tests/js/common/shell/shell-statistics.js
Labels: 1 Feature, 9 Ready to Merge

#9812 use LDAP_PATH instead of fixed one
  arangod/CMakeLists.txt
Labels: 3 Build

#9556 Changelog 3408
  CHANGELOG
Labels: 3 Documentation

#9815 adjust log level for "closing stream" message
  CHANGELOG
  arangod/GeneralServer/SocketTask.cpp
Labels: 9 Ready to Merge

#9827 iterate through all vertexCollections of a graph to find a vertex to …
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
Labels: 3 UI

#9814 Bug fix 3.5/fix in not in workaround
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  arangod/Aql/tokens.cpp
  arangod/Aql/tokens.ll
  tests/js/server/aql/aql-parse.js
Labels: 9 Ready to Merge

#9818 Feature 3.5/enable tlsv13
  CHANGELOG
  lib/SimpleHttpClient/SslClientConnection.cpp
  lib/Ssl/ssl-helper.cpp
  lib/Ssl/ssl-helper.h
Labels: 9 Ready to Merge

#9810 [3.5] Minimize unnecessary dropping of followers due to poorly set synchronous replication timeouts
  CHANGELOG
  arangod/Cluster/ReplicationTimeoutFeature.cpp
  arangod/Cluster/ReplicationTimeoutFeature.h
  arangod/ClusterEngine/ClusterEngine.h
  arangod/MMFiles/MMFilesEngine.h
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/StorageEngine/StorageEngine.h
  tests/Mocks/StorageEngineMock.h
Labels: 9 Ready to Merge

#9832 Bug fix 3.5/ui optimize graph load
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
Labels: 9 Ready to Merge

#9838 Improve error messages for loop validation
  CHANGELOG
  lib/Geo/GeoJson.cpp
Labels: 9 Ready to Merge

#9846 [3.5] agency lockup when removing 404ed callbacks and leadership preparation
  arangod/Agency/Agent.cpp
Labels: 1 Bug, Team Clifton

#9833 added ensureCollections to orphan create method
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
Labels: 9 Ready to Merge

#9853 This fixes an earlier oversight.
  arangod/Agency/Agent.cpp
Labels: 1 Bug

#9858 fix return value when reboot id cannot be retrieved
  arangod/Cluster/ServerState.cpp
Labels: 9 Ready to Merge

#9829 cover more cases of "unique constraint violated" issues during replication
  arangod/Agency/Supervision.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/Syncer.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  tests/js/server/replication/sync/replication-sync.js
Labels: 9 Ready to Merge

#9842 Bug fix 3.5/graph create orphan collection properly
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
Labels: 9 Ready to Merge

#9647 Feature/resource usage
  README_maintainers.md
  UnitTests/unittest.js
  arangod/RestHandler/RestStatusHandler.cpp
  js/client/modules/@arangodb/clusterstats.js
  js/client/modules/@arangodb/process-utils.js
  js/client/modules/@arangodb/result-processing.js
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testing.js
  js/client/modules/@arangodb/testsuites/agency.js
  js/client/modules/@arangodb/testsuites/audit.js
  js/client/modules/@arangodb/testsuites/config.js
  js/client/modules/@arangodb/testsuites/fail.js
  js/common/bootstrap/modules/internal.js
  lib/Basics/process-utils.cpp
  lib/Basics/threads-posix.h
  lib/Basics/threads-win32.h
  lib/V8/v8-utils.cpp
  scripts/examine_results.js
Labels: 1 - Ready

#9745 Bug fix 3.3/fix arangosh documentation paste
  CHANGELOG
  lib/Utilities/ShellBase.cpp
Labels: 1 - Ready

#9867 Bug fix/curb aardvark foxx cthulhu
  js/apps/system/_admin/aardvark/APP/foxxes.js
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/foxxCollection.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/foxxRepoView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installGitHubServiceView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installNewServiceView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installUploadServiceView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installUrlServiceView.js
Labels: 3 UI

#9865 fixed issue #9862
  CHANGELOG
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  tests/js/server/aql/aql-primary-index-noncluster.js
Labels: 9 Ready to Merge
