Repository arangodb/arangodb, pull requests merged in 2019-07, with the labels that each got.

#9374 Fix authentication and catch tests in devel
  tests/Mocks/StorageEngineMock.cpp
  tests/js/client/authentication/auth-analyzer.js
Labels: 3 - Testing, 3 ArangoSearch

#9386 add initializeCursor back to DistinctCollectExecutor
  arangod/Aql/DistinctCollectExecutor.cpp
  arangod/Aql/DistinctCollectExecutor.h
  arangod/Aql/ExecutionBlockImpl.cpp
Labels: 9 Ready to Merge

#9382 use logical comparisons instead of binary ones
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Store.cpp
  arangod/Agency/Supervision.cpp
  arangod/Aql/Functions.cpp
  arangod/Cluster/AgencyCallback.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/RestServer/BootstrapFeature.cpp
Labels: 9 Ready to Merge

#9410 Leader updates Current precondition fixes.
  CHANGELOG
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/DBServerAgencySync.h
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Transaction/Methods.cpp
  tests/Agency/FailedLeaderTest.cpp
  tests/Agency/FailedServerTest.cpp
  tests/Agency/RemoveFollowerTest.cpp
Labels: 1 Bug, 3 Cluster

#9402 remove several outdated error codes
  js/common/bootstrap/errors.js
  js/server/modules/@arangodb/actions.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  lib/Rest/GeneralResponse.cpp
Labels: 9 Ready to Merge

#9398 Various error reporting fixes plus Maintenance Current fix.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/DBServerAgencySync.h
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Transaction/Methods.cpp
  tests/Agency/FailedLeaderTest.cpp
  tests/Agency/FailedServerTest.cpp
  tests/Agency/RemoveFollowerTest.cpp
Labels: 1 Bug, 3 Cluster

#9413 Bug fix/internal issue #606
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/js/client/shell/shell-analyzer-rest-api.js
  tests/js/common/aql/aql-view-arangosearch-feature.js
Labels: 1 Bug, 3 ArangoSearch

#9366 Bug fix/add shard id to replication client identifier
  CHANGELOG
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges35.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_logger_return_state.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  arangod/CMakeLists.txt
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/MMFiles/MMFilesIncrementalSync.h
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/DatabaseInitialSyncer.h
  arangod/Replication/GlobalInitialSyncer.cpp
  arangod/Replication/InitialSyncer.cpp
  arangod/Replication/ReplicationClients.cpp
  arangod/Replication/ReplicationClients.h
  arangod/Replication/Syncer.cpp
  arangod/Replication/Syncer.h
  arangod/Replication/SyncerId.cpp
  arangod/Replication/SyncerId.h
  arangod/Replication/utilities.cpp
  arangod/Replication/utilities.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/FlushFeature.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/replicationView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/replicationView.js
  tests/CMakeLists.txt
  tests/Replication/ReplicationClientsProgressTrackerTest.cpp
  tests/js/server/replication/static/replication-static.js
Labels: 1 Bug, 9 Ready to Merge

#9416 Bug fix/fix snippet responsibility for views
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/EngineInfoContainerDBServer.h
  tests/Agency/MoveShardTest.cpp
Labels: 1 Bug

#9436 Bug fix/internal issue #524
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-rocksdb.js
Labels: 3 ArangoSearch

#9443 Temporarily suppress failure
  tests/js/server/recovery/view-arangosearch-link-populate.js
Labels: 3 - Testing, 3 ArangoSearch

#9373 Bug fix/replication fast lane
  CHANGELOG
  arangod/RestHandler/RestDocumentHandler.h
  arangod/Transaction/Methods.cpp
  tests/CMakeLists.txt
  tests/Mocks/Servers.cpp
  tests/Mocks/Servers.h
  tests/RestHandler/RestDocumentHandler-test.cpp
Labels: 1 Bug

#9470 Revert macOS package naming
  cmake/packages/packages.cmake
Labels: 3 Build, 4 MacOSX

#9469 Revert macOS package naming
  cmake/packages/packages.cmake
Labels: 3 Build, 4 MacOSX

#9478 Documentation/switch example generation to rocksdb
  Documentation/DocuBlocks/Rest/Administration/get_engine.md
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_figures.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_rotate.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_dump.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_inventory.md
  Documentation/DocuBlocks/Rest/wal/get_admin_wal_properties.md
  Documentation/DocuBlocks/Rest/wal/get_admin_wal_transactions.md
  Documentation/DocuBlocks/Rest/wal/put_admin_wal_properties.md
  Documentation/DocuBlocks/collectionFigures.md
  Documentation/DocuBlocks/ensureUniqueSkiplist.md
  Documentation/DocuBlocks/walPropertiesGet.md
  Documentation/DocuBlocks/walPropertiesSet.md
  Documentation/Examples/RestCollectionGetCollectionFigures_mmfiles.generated
  Documentation/Examples/RestCollectionGetCollectionFigures_rocksdb.generated
  Documentation/Examples/RestCollectionRotateNoJournal_mmfiles.generated
  Documentation/Examples/RestCollectionRotate_mmfiles.generated
  Documentation/Examples/RestEngine_mmfiles.generated
  Documentation/Examples/RestEngine_rocksdb.generated
  Documentation/Examples/RestReplicationDumpEmpty_mmfiles.generated
  Documentation/Examples/RestReplicationDump_mmfiles.generated
  Documentation/Examples/RestReplicationInventoryIndexes_mmfiles.generated
  Documentation/Examples/RestReplicationInventory_mmfiles.generated
  Documentation/Examples/RestWalPropertiesGet_mmfiles.generated
  Documentation/Examples/RestWalPropertiesPut_mmfiles.generated
  Documentation/Examples/RestWalTransactionsGet_mmfiles.generated
  Documentation/Examples/WalPropertiesGet.generated
  Documentation/Examples/WalPropertiesGet_mmfiles.generated
  Documentation/Examples/WalPropertiesSet.generated
  Documentation/Examples/WalPropertiesSet_mmfiles.generated
  Documentation/Examples/collectionFigures_mmfiles.generated
  Documentation/README_maintainers.md
  utils/generateExamples.js
  utils/generateExamples.py
Labels: 3 Documentation

#9489 improve the formatting of the batch request documentation
  Documentation/DocuBlocks/Rest/Bulk/batch_processing.md
  Documentation/Examples/RestBatchImplicitBoundary.generated
  Documentation/Examples/RestBatchMultipartHeader.generated
  Documentation/Scripts/exampleHeader.js
  js/client/bootstrap/modules/internal.js
Labels: 3 Documentation

#9460 [3.4] Fix query snippet responsibility for views
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServer.cpp
  arangod/Aql/EngineInfoContainerDBServer.h
Labels: 1 Bug, 9 Ready to Merge

#9498 Documentation 3.5/example generation improvements
  Documentation/DocuBlocks/Rest/Administration/get_engine.md
  Documentation/DocuBlocks/Rest/Bulk/batch_processing.md
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_figures.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_rotate.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_dump.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_range.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_inventory.md
  Documentation/DocuBlocks/Rest/wal/get_admin_wal_properties.md
  Documentation/DocuBlocks/Rest/wal/get_admin_wal_transactions.md
  Documentation/DocuBlocks/Rest/wal/put_admin_wal_properties.md
  Documentation/DocuBlocks/collectionFigures.md
  Documentation/DocuBlocks/ensureUniqueSkiplist.md
  Documentation/DocuBlocks/walPropertiesGet.md
  Documentation/DocuBlocks/walPropertiesSet.md
  Documentation/Examples/RestBatchImplicitBoundary.generated
  Documentation/Examples/RestBatchMultipartHeader.generated
  Documentation/Examples/RestCollectionGetCollectionFigures_mmfiles.generated
  Documentation/Examples/RestCollectionGetCollectionFigures_rocksdb.generated
  Documentation/Examples/RestCollectionRotateNoJournal_mmfiles.generated
  Documentation/Examples/RestCollectionRotate_mmfiles.generated
  Documentation/Examples/RestEngine_mmfiles.generated
  Documentation/Examples/RestEngine_rocksdb.generated
  Documentation/Examples/RestReplicationDumpEmpty_mmfiles.generated
  Documentation/Examples/RestReplicationDump_mmfiles.generated
  Documentation/Examples/RestReplicationInventoryIndexes_mmfiles.generated
  Documentation/Examples/RestReplicationInventory_mmfiles.generated
  Documentation/Examples/RestWalPropertiesGet_mmfiles.generated
  Documentation/Examples/RestWalPropertiesPut_mmfiles.generated
  Documentation/Examples/RestWalTransactionsGet_mmfiles.generated
  Documentation/Examples/WalPropertiesGet.generated
  Documentation/Examples/WalPropertiesGet_mmfiles.generated
  Documentation/Examples/WalPropertiesSet.generated
  Documentation/Examples/WalPropertiesSet_mmfiles.generated
  Documentation/Examples/collectionFigures_mmfiles.generated
  Documentation/README_maintainers.md
  Documentation/Scripts/exampleHeader.js
  js/client/bootstrap/modules/internal.js
  utils/generateExamples.js
  utils/generateExamples.py
Labels: 3 Documentation, 9 Review Required

#9475 Add updated JS deps to changelog (#8773)
  CHANGELOG
Labels: 1 Bug, 9 Review Required

#9447 Feature/refactor maintainers readme
  README_maintainers.md
Labels: 1 Feature, 3 Documentation, 9 Ready to Merge

#9438 migrate mochaGrep into --testCase parametrizing
  README_maintainers.md
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testing.js
  js/common/modules/@arangodb/testrunner.js
Labels: 9 Ready to Merge

#9503 Bug fix 3.5/clean replication api wal tracking
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges35.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  arangod/CMakeLists.txt
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/SynchronizeShard.h
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/Replication/ReplicationApplierConfiguration.h
  arangod/Replication/ReplicationClients.cpp
  arangod/Replication/ReplicationClients.h
  arangod/Replication/Syncer.cpp
  arangod/Replication/Syncer.h
  arangod/Replication/utilities.cpp
  arangod/Replication/utilities.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/Utils/UrlHelper.cpp
  arangod/Utils/UrlHelper.h
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/replicationView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/replicationView.js
  tests/Replication/ReplicationClientsProgressTrackerTest.cpp
Labels: 1 Bug

#9512 Bug fix 3.5/count collect should skip
  CHANGELOG
  arangod/Aql/CountCollectExecutor.h
  arangod/Aql/OutputAqlItemRow.h
  tests/Aql/CountCollectExecutorTest.cpp
  tests/Aql/RowFetcherHelper.cpp
  tests/Aql/RowFetcherHelper.h
  tests/js/server/aql/aql-optimizer-collect-count.js
Labels: 1 Bug

#9511 Bug fix/count collect should skip
  CHANGELOG
  arangod/Aql/CountCollectExecutor.h
  arangod/Aql/OutputAqlItemRow.h
  tests/Aql/CountCollectExecutorTest.cpp
  tests/Aql/RowFetcherHelper.cpp
  tests/Aql/RowFetcherHelper.h
  tests/js/server/aql/aql-optimizer-collect-count.js
Labels: 1 Bug, 9 Ready to Merge

#9513 Documentation 3.5/backport maintainers2
  README_maintainers.md
Labels: 3 Documentation

#9433 Feature/min replication factor
  CHANGELOG
  Documentation/Books/Manual/ReleaseNotes/NewFeatures35.md
  arangod/Cluster/ClusterCollectionCreationInfo.cpp
  arangod/Cluster/ClusterCollectionCreationInfo.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/Maintenance.cpp
  arangod/ClusterEngine/ClusterRestReplicationHandler.h
  arangod/GeneralServer/RequestLane.h
  arangod/Graph/Graph.cpp
  arangod/Graph/Graph.h
  arangod/MMFiles/MMFilesRestReplicationHandler.h
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingInfo.h
  arangod/Transaction/Methods.cpp
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Collections.cpp
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoCollections.js
  js/apps/system/_admin/aardvark/APP/frontend/js/models/arangoCollectionModel.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
  js/client/modules/@arangodb/arango-collection.js
  js/client/modules/@arangodb/arango-database.js
  js/common/modules/@arangodb/test-helper.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchLinkCoordinator-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/js/common/http/api-gharial-creation-cluster-spec.js
  tests/js/common/shell/shell-cluster-collection.js
  tests/js/common/shell/shell-collection-mmfiles.js
  tests/js/common/shell/shell-collection-rocksdb.js
  tests/js/common/shell/shell-collection.js
  tests/js/server/shell/shell-collection-properties-cluster-spec.js
Labels: 1 Feature

#9445 All hail to the SI
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyFeature.cpp
  arangod/Agency/Agent.cpp
  arangod/Agency/Inception.cpp
  arangod/Aql/Functions.cpp
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/MMFiles/MMFilesCleanupThread.cpp
  arangod/MMFiles/MMFilesCollectorThread.cpp
  arangod/MMFiles/MMFilesCompactorThread.cpp
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/MMFiles/MMFilesLogfileManager.cpp
  arangod/MMFiles/MMFilesWalSlots.cpp
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Recovery.cpp
  arangod/Pregel/Worker.cpp
  arangod/Replication/ReplicationApplier.cpp
  arangod/Replication/Syncer.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestServer/ConsoleFeature.cpp
  arangod/RestServer/ConsoleThread.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/ServerFeature.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
  arangod/Statistics/RequestStatistics.cpp
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsWorker.cpp
  arangod/Utils/CollectionKeysRepository.cpp
  arangod/V8Server/V8DealerFeature.cpp
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/Methods/Tasks.cpp
  arangod/VocBase/vocbase.cpp
  arangosh/Benchmark/BenchFeature.cpp
  arangosh/Import/AutoTuneThread.cpp
  arangosh/Import/ImportHelper.cpp
  lib/ApplicationFeatures/DaemonFeature.cpp
  lib/Logger/Logger.cpp
  lib/SimpleHttpClient/SimpleHttpClient.cpp
  lib/V8/v8-utils.cpp
  tests/Cache/Rebalancer.cpp
Labels: 9 Ready to Merge

#9486 Bug fix/failover with min replication factor
  Documentation/Books/Manual/Architecture/Replication/README.md
  Documentation/Books/Manual/DataModeling/Collections/DatabaseMethods.md
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/collectionProperties.md
  arangod/Agency/Job.cpp
  arangod/Aql/RestAqlHandler.h
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/UpdateCollection.cpp
  arangod/GeneralServer/RequestLane.h
  arangod/InternalRestHandler/InternalRestTraverserHandler.h
  arangod/Pregel/Conductor.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Transaction/Methods.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/IResearch/IResearchQueryOptimization-test.cpp
Labels: 1 Feature

#9473 Bug fix/clean replication api wal tracking
  Documentation/Books/Manual/ReleaseNotes/UpgradingChanges35.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  arangod/CMakeLists.txt
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/SynchronizeShard.h
  arangod/MMFiles/MMFilesRestReplicationHandler.cpp
  arangod/Replication/ReplicationApplierConfiguration.h
  arangod/Replication/ReplicationClients.cpp
  arangod/Replication/ReplicationClients.h
  arangod/Replication/Syncer.cpp
  arangod/Replication/Syncer.h
  arangod/Replication/utilities.cpp
  arangod/Replication/utilities.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/Utils/UrlHelper.cpp
  arangod/Utils/UrlHelper.h
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/replicationView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/replicationView.js
  tests/Replication/ReplicationClientsProgressTrackerTest.cpp
Labels: 1 Bug, 9 Ready to Merge

#9539 release version 3.5.0-rc.5
  CMakeLists.txt
  VERSION
Labels: 3 Build

#9544 Forward Port of changes in 3.5 review
  CHANGELOG
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/collectionProperties.md
  arangod/Agency/Job.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/Scheduler/SupervisedScheduler.h
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
Labels: 1 Bug

#9554 Backport of MACOSX_DEPLOYMENT_TARGET from devel
  CMakeLists.txt
Labels: 3 Build, 4 MacOSX

#9555 Backport of MACOSX_DEPLOYMENT_TARGET from devel
  CMakeLists.txt
Labels: 3 Build, 4 MacOSX

#9574 Fix MACOSX_DEPLOYMENT_TARGET absence case
  CMakeLists.txt
Labels: 3 Build, 4 MacOSX

#9573 Fix MACOSX_DEPLOYMENT_TARGET absence case
  CMakeLists.txt
Labels: 3 Build, 4 MacOSX

#9572 Fix MACOSX_DEPLOYMENT_TARGET absence case
  CMakeLists.txt
Labels: 3 Build, 4 MacOSX

#9584 Upgrade arangosync 0.6.5
  VERSIONS
Labels: 3 Build

#9585 release version 3.5.0-rc.5
  CMakeLists.txt
  VERSION
Labels: 1 - Ready, 3 Build

#9599 Bug fix 3.5/fix view creation errors
  arangod/RestHandler/RestViewHandler.cpp
  arangod/RestServer/ViewTypesFeature.cpp
Labels: 3 API, 3 ArangoSearch, 3 Documentation, 3 Swagger

#9598 Fix ArangoSearch view creation errors
  arangod/RestHandler/RestViewHandler.cpp
  arangod/RestServer/ViewTypesFeature.cpp
Labels: 3 API, 3 ArangoSearch, 3 Documentation, 3 Swagger

#9600 Fix ArangoSearch view creation errors
  arangod/RestHandler/RestViewHandler.cpp
  arangod/RestServer/ViewTypesFeature.cpp
Labels: 3 API, 3 ArangoSearch, 3 Documentation, 3 Swagger

#9045 Bug fix/fix swagger datatype
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
  js/apps/system/_admin/aardvark/APP/api-docs.json
  utils/generateSwagger.py
Labels: 3 Documentation, 3 Swagger

#9603 Bug fix/fix swagger datatype (#9045)
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_iresearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_iresearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_iresearch.md
  js/apps/system/_admin/aardvark/APP/api-docs.json
  utils/generateSwagger.py
Labels: 1 Bug, 3 Documentation, 3 Swagger, 9 Ready to Merge
