Repository arangodb/arangodb, pull requests merged in 2020-06, with the labels that each got.

#11723 catch agency callback exeptions
  CHANGELOG
  arangod/Agency/Store.cpp
Labels: 1 Bug

#11726 Bug fix/skip and hard limit in modification
  CHANGELOG
  arangod/Aql/AqlItemBlockInputMatrix.cpp
  arangod/Aql/AqlItemMatrix.cpp
  arangod/Aql/AqlItemMatrix.h
  arangod/Aql/ModificationExecutor.cpp
  tests/js/server/aql/aql-modify.js
Labels: 1 Bug

#11692 enforcing std=c++17 everywhere
  CMakeLists.txt
Labels: 3 Build, 9 Ready to Merge

#11695 don't exclude requests to `/_admin/aardvark` from requests statistics
  CHANGELOG
  arangod/Actions/RestActionHandler.cpp
Labels: 9 Ready to Merge

#11706 Fix drop follower behaviour.
  CHANGELOG
  arangod/Network/Methods.cpp
  arangod/Utils/CollectionNameResolver.cpp
Labels: 1 Bug

#11709 Documentation 3.6/gtest
  README_maintainers.md
Labels: 3 Documentation, 9 Ready to Merge

#11711 Bug fix 3.6/bts 57
  CHANGELOG
  arangod/Aql/RestAqlHandler.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestGraphHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  arangod/Transaction/Manager.cpp
  tests/js/client/shell/shell-transaction.js
Labels: 9 Ready to Merge

#11714 Make test not loose failed leaders/followers
  tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster-grey.js
Labels: 3 - Testing, 3 Cluster, 9 Ready to Merge

#11717 Usability improvements for arangodump and arangorestore
  CHANGELOG
  arangosh/Dump/DumpFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Shell/V8ShellFeature.cpp
  arangosh/Utils/ManagedDirectory.cpp
Labels: 9 Ready to Merge

#11720 [3.6] catch agency callback send exceptions
  CHANGELOG
  arangod/Agency/Store.cpp
Labels: 1 Bug

#11734 Ported fix for issue #11104
  3rdParty/iresearch/core/search/boolean_filter.cpp
  3rdParty/iresearch/core/search/boolean_filter.hpp
  3rdParty/iresearch/tests/search/boolean_filter_tests.cpp
  CHANGELOG
  tests/js/common/aql/aql-view-arangosearch-feature.js
Labels: 3 ArangoSearch

#11705 add new method to base class (ES-600)
  CHANGELOG
  arangod/Auth/Handler.h
Labels: 3 UserManagement

#11687 Bug fix 3.5/restart follower no leader set
  3rdParty/fuerte/src/types.cpp
  CHANGELOG
  CMakeLists.txt
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/Transaction/Methods.cpp
Labels: 3 Cluster

#11710 Documentation 3.5/gtest
  README_maintainers.md
Labels: 3 Documentation, 9 Ready to Merge

#11733 Bug fix 3.5/issue #11104
  3rdParty/iresearch/core/search/boolean_filter.cpp
  3rdParty/iresearch/core/search/boolean_filter.hpp
  CHANGELOG
  tests/js/common/aql/aql-view-arangosearch-feature.js
Labels: 3 ArangoSearch

#11732 Bug fix 3.4/issue #11104
  3rdParty/iresearch/core/search/boolean_filter.cpp
  3rdParty/iresearch/core/search/boolean_filter.hpp
  3rdParty/iresearch/tests/search/boolean_filter_tests.cpp
  CHANGELOG
  tests/js/common/aql/aql-view-arangosearch-feature.js
Labels: 3 ArangoSearch

#11746 Added test for AqlItemMatrix, fixed minor glitch
  arangod/Aql/AqlItemMatrix.cpp
  tests/Aql/AqlItemMatrixTest.cpp
  tests/CMakeLists.txt
Labels: 9 Ready to Merge

#11745 pimped up network send request robustness
  CHANGELOG
  arangod/Network/Methods.cpp
  arangod/Network/Methods.h
Labels: 1 Bug

#11742 make arangodump/restore fail with invalid collection names
  CHANGELOG
  arangosh/Dump/DumpFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
  tests/js/client/shell/shell-dump-integration.js
Labels: 3 ImportExport

#11736 Removed noexcept specifier on defaulted constructors etc.
  arangod/Agency/TransactionBuilder.h
  arangod/Aql/AqlValue.h
  arangod/Aql/BlocksWithClients.h
  arangod/Aql/KShortestPathsExecutor.h
  arangod/Aql/MaterializeExecutor.h
  arangod/Aql/ScatterExecutor.h
  arangod/Aql/SortedCollectExecutor.h
  arangod/Aql/SortingGatherExecutor.h
  arangod/Aql/SubqueryEndExecutor.h
  arangod/Aql/SubqueryExecutor.h
  lib/Containers/Enumerate.h
  tests/Cache/Rebalancer.cpp
  tests/Containers/EnumerateTest.cpp
Labels: 9 Ready to Merge

#11708 fix shards view due to disjoint smart graph integration
  js/apps/system/_admin/aardvark/APP/frontend/js/views/shardsView.js
Labels: 9 Waiting for Jenkins

#11698 remove external library loading
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/jquery.form.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/jquery.uploadfile.min.js
  js/apps/system/_admin/aardvark/APP/react/src/App.js
Labels: 3 UI

#11739 Bug fix/ui satellite collection properties
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
Labels: 3 UI

#11629 Don't allow empty _key to percolate too far
  arangod/Transaction/Methods.cpp
Labels: DO_NOT_MERGE

#11743 Docs: Add missing isSmart and smartJoinAttribute options
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
Labels: 1 Bug, 3 Documentation, 3 Swagger, 9 Ready to Merge

#11744 [3.6] pimped up network send request robustness
  CHANGELOG
  arangod/Network/Methods.cpp
  arangod/Network/Methods.h
Labels: 1 Bug

#11753 Docs: Add missing isSmart and smartJoinAttribute options
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  js/apps/system/_admin/aardvark/APP/api-docs.json
Labels: 1 Bug, 3 Documentation, 3 Swagger, 9 Ready to Merge

#6463 Improve Windows installer texts and backup creation
  Installation/Windows/client/Templates/NSIS.template.in
  Installation/Windows/client/Templates/arango-packer-template.nsi
Labels: 2 - Working, 3 Packaging, 9 WIP

#11751 TakeoverLeadership wait for ClusterInfo Current cache.
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/Maintenance.h
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/TakeoverShardLeadership.cpp
  tests/Maintenance/MaintenanceTest.cpp
Labels: 1 Bug

#11750 Bug fix 3.4/ui view editor ro
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
Labels: 3 UI

#11749 Bug fix 3.5/ui view editor ro
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/views/viewView.js
Labels: 3 UI

#11754 Fix fast forwarding for SubqueryExecutor
  CHANGELOG
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/SubqueryExecutor.h
  tests/js/server/aql/aql-modify-subqueries.js
Labels: 9 Ready to Merge

#11763 Bug fix/recalculate count (#11759)
  CHANGELOG
  arangod/Network/Methods.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  tests/js/server/recovery/recalculate-count-incremental-rocksdb.js
  tests/js/server/recovery/recalculate-count-rocksdb.js
Labels: 1 Bug

#11761 Docs: Add missing isSmart and smartJoinAttribute options
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  js/apps/system/_admin/aardvark/APP/api-docs.json
Labels: 1 Bug, 3 Documentation, 3 Swagger

#11767 Docs: Fix data type of satelliteWaitSync option
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  js/apps/system/_admin/aardvark/APP/api-docs.json
Labels: 1 Bug, 3 Documentation, 9 Ready to Merge

#11768 Docs: Fix data type of satelliteWaitSync option
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  js/apps/system/_admin/aardvark/APP/api-docs.json
Labels: 1 Bug, 3 Documentation, 9 Ready to Merge

#10348 Fix idiomatic Foxx testing reports
  CHANGELOG
  js/apps/system/_api/foxx/APP/index.js
  js/apps/system/_api/foxx/APP/schemas.js
  tests/js/client/shell/shell-foxx-api-spec.js
Labels: 1 Bug, 3 API, 3 Foxx

#11770 Fix idiomatic Foxx testing reports for 3.6
  CHANGELOG
  js/apps/system/_api/foxx/APP/index.js
  js/apps/system/_api/foxx/APP/schemas.js
  tests/js/client/shell/shell-foxx-api-spec.js
Labels: 1 Bug, 3 - Testing, 3 API, 3 Foxx

#11771 properly name metrics
  arangod/Agency/Constituent.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Statistics/StatisticsWorker.cpp
Labels: 9 Ready to Merge

#11766 Bug fix/fix alignment of skipped and calls
  CHANGELOG
  arangod/Aql/AqlCallStack.cpp
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/SkipResult.cpp
  tests/js/server/aql/aql-modify-subqueries.js
Labels: 1 Bug, 9 Ready to Merge

#11756 db servers restart with views / links
  CHANGELOG
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchFeature-test.cpp
Labels: 1 Bug

#11774 Fix a spuriously occurring shutdown deadlock in the AgencyCallbackRegistry
  CHANGELOG
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  arangod/Cluster/AgencyCallbackRegistry.cpp
  arangod/Cluster/AgencyCallbackRegistry.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Network/ConnectionPool.h
Labels: 3 Cluster

#11735 Bug fix/fix resilience tests
  arangod/RestHandler/RestAdminClusterHandler.cpp
Labels: 3 - Testing

#11785 make agency test less sensitive to timing
  tests/js/client/agency/agency-test.js
Labels: 9 Ready to Merge

#11760 Some more fixes for serializing revision trees
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.h
  tests/js/server/recovery/revision-trees-no-sync.js
  tests/js/server/recovery/revision-trees-partial-sync.js
Labels: 9 Ready to Merge

#11781 when producing documents and using projections, recycle a velocypack::Builder
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/DocumentProducingHelper.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
Labels: 9 Ready to Merge

#11779 improve shadow row handling
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlItemBlockInputRange.cpp
  arangod/Aql/AqlItemMatrix.cpp
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionBlockImpl.h
Labels: 9 Ready to Merge

#11783 drop collection off fast track
  CHANGELOG
  arangod/Cluster/DropCollection.cpp
Labels: 1 Bug, 3 Cluster

#11794 don't force plan reload for analyzer revisions
  arangod/ClusterEngine/ClusterTransactionState.cpp
Labels: 9 Ready to Merge

#11802 Remove old code for rolling upgrades. Fixes BTS-87.
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug

#11793 explicitly define section "server" where it is needed.
  arangod/Scheduler/SchedulerFeature.cpp
Labels: 1 Bug

#11815 fix the creation of edges in the web UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocument.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
Labels: 9 Ready to Merge

#11817 disable extraneous logging in web UI in cluster mode
  js/apps/system/_admin/aardvark/APP/react/src/store/logging/middleware.tsx
Labels: 9 Ready to Merge

#11820 pick up write concern from UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoCollections.js
Labels: 9 Ready to Merge

#11821 fixed "Create Debug Package" in web UI in cluster mode
  CHANGELOG
  js/common/modules/@arangodb/aql/explainer.js
Labels: 9 Ready to Merge

#11822 Bug fix/augment nodes view
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/nodesView.ejs
Labels: 9 Ready to Merge

#11823 don't mangle AQL errors in web UI graph viewer
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
Labels: 9 Ready to Merge

#11824 allow specifying arbitrary attributes when adding a new vertex via the graph viewer
  CHANGELOG
  arangod/RestHandler/RestGraphHandler.cpp
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 9 Ready to Merge

#11825 add geoJson flag in web UI index overview
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
Labels: 9 Ready to Merge

#11826 fix typos
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 9 Ready to Merge

#11827 attempt to fix spuriously failing test about edge cache
  tests/js/common/shell/shell-collection-noncluster.js
Labels: 9 Ready to Merge

#11801 ASAN fixes
  3rdParty/snowball/compiler/driver.c
  lsan_arangodb_suppressions.txt
Labels: 9 Ready to Merge

#11811 remove remainders of libcurl
  lsan_arangodb_suppressions.txt
Labels: 9 Ready to Merge

#11849 elevate permissions for analyzers
  CHANGELOG
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchAnalyzerFeature.h
  tests/js/client/authentication/auth-analyzer-view-integration.js
Labels: 1 Bug, 3 ArangoSearch

#11845 clean up several small things in CMakeLists.txt
  CMakeLists.txt
Labels: 3 Build

#11862 Bug fix 3.7/smarter ui default value for replication factor
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
Labels: 3 UI

#11773 Added missing mutex acquisition to ConnectionPool::cancelConnections().
  CHANGELOG
  arangod/Network/ConnectionPool.cpp
Labels: 9 Ready to Merge

#11784 [3.6] drop collection off fast track
  CHANGELOG
  arangod/Cluster/DropCollection.cpp
Labels: 1 Bug, 3 Cluster, 9 Ready to Merge

#11792 Handle missing "shardingStrategy" in Plan agency entries for collections
  CHANGELOG
  arangod/Sharding/ShardingFeature.cpp
Labels: 9 Ready to Merge

#11806 [3.6] correct validation of keys in velocypack
  3rdParty/velocypack/src/Validator.cpp
  CHANGELOG
Labels: 1 Bug, 9 Ready to Merge, velocypack

#11812 [3.6] Remove old code for rolling upgrades. Fixes BTS-87.
  arangod/Cluster/ClusterInfo.cpp
Labels: 3 Kubernetes

#11835 ungreylist test for 3.6
  tests/Greylist.txt
  tests/js/server/resilience/failover/resilience-synchronous-repl-cluster.js
Labels: 3 - Testing, 9 Ready to Merge

#11836 handle and pass resthandler exceptions properly
  CHANGELOG
  arangod/GeneralServer/RestHandler.h
Labels: 1 Bug, 9 Review Required

#11837 Bug fix 3.6/rest handler handle exceptions
  CHANGELOG
  arangod/GeneralServer/RestHandler.h
Labels: 1 Bug, 9 Review Required

#11840 Reboot tracker catches removed and failed servers.
  CHANGELOG
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/RebootTracker.cpp
Labels: 1 Bug

#11829 fix creation of edges in web UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocument.js
Labels: 9 Ready to Merge

#11833 pick up selected write concern value from UI correctly
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoCollections.js
Labels: 9 Ready to Merge

#11834 remove extraneous logging in web UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/store/logging/middleware.tsx
Labels: 3 UI, 9 Ready to Merge

#11813 [3.5] Remove old code for rolling upgrades. Fixes BTS-87.
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug, 3 Kubernetes

#11830 fix creation of edges in web UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocument.js
Labels: 1 Bug, 3 UI, 9 Ready to Merge

#11847 Pass through AQL query errors to UI graph viewer without turning them into "Internal Server Error"s.
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
Labels: 1 Bug, 3 Graph Visualization, 3 UI

#11850 Use smarter default value preset in web UI for replication factor
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
Labels: 9 Ready to Merge

#11855 a bit less work for AqlItemBlock processing
  arangod/Aql/AqlItemBlock.cpp
Labels: 9 Ready to Merge

#11831 fix creation of edges in web UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocument.js
Labels: 1 Bug, 3 UI, 9 Ready to Merge

#11848 Pass through AQL query errors to UI graph viewer without turning them into "Internal Server Error"s.
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
Labels: 1 Bug, 3 Graph Visualization, 3 UI

#11797 fix potential hangers in AQL queries on server shutdown
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/Aql/SharedQueryState.cpp
Labels: 9 Ready to Merge

#11867 Bug fix 3.7/rest handler handle exceptions
  CHANGELOG
  arangod/GeneralServer/RestHandler.h
Labels: 1 Bug

#11868 fixed a missing escape, removed unused file (#11866)
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/applicationDetailView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalTable.ejs
Labels: 3 UI

#11871 fix a memleak that only happens in tests due to mocking
  arangod/Transaction/Context.cpp
  arangod/Transaction/Context.h
  tests/Aql/LevenshteinMatchFunctionTest.cpp
Labels: 9 Ready to Merge

#11872 fix potential hangers in AQL queries on server shutdown
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/Aql/SharedQueryState.cpp
Labels: 3 AQL, 9 Ready to Merge

#11865 fix invalid access to `AgencyCommResult::slice()`.
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Cluster/ClusterInfo.cpp
Labels: 3 Cluster

#11875 fix internal test helper function `removeCost`
  CHANGELOG
  js/server/modules/@arangodb/aql-helper.js
Labels: 9 Ready to Merge

#11876 fix internal test helper function `removeCost`
  CHANGELOG
  js/server/modules/@arangodb/aql-helper.js
Labels: 3 - Testing

#11856 Move ResultT.h from arangod/Cluster to lib/Basics
  arangod/Agency/AsyncAgencyComm.h
  arangod/Agency/Node.h
  arangod/Aql/AqlCall.h
  arangod/Aql/AqlCallStack.h
  arangod/Aql/AqlExecuteResult.cpp
  arangod/Aql/DistributeExecutor.h
  arangod/Aql/QueryRegistry.h
  arangod/Aql/QuerySnippet.h
  arangod/Aql/SkipResult.cpp
  arangod/Cluster/ClusterRepairDistributeShardsLike.h
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
  arangod/Cluster/SynchronizeShard.h
  arangod/GeneralServer/RestHandler.h
  arangod/Graph/Graph.h
  arangod/Graph/GraphManager.h
  arangod/Graph/GraphOperations.h
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestRepairHandler.h
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RestHandler/RestSupervisionStateHandler.cpp
  arangod/RestHandler/RestTestHandler.cpp
  arangod/RestHandler/RestTestHandler.h
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.h
  arangod/StorageEngine/HotBackupCommon.h
  lib/Basics/ResultT.h
  tests/Aql/SkipResultTest.cpp
  tests/Cluster/ClusterRepairsTest.cpp
Labels: 9 Ready to Merge

#11869 fixed a missing escape, removed unused file (#11866)
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/applicationDetailView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalTable.ejs
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.177e3a8aa790cfdb2d067ba4f815795c.js
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.177e3a8aa790cfdb2d067ba4f815795c.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.c673e902624398d91ab118940d9401a1.js
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.c673e902624398d91ab118940d9401a1.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.c4efa8e5.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.c4efa8e5.chunk.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.c4efa8e5.chunk.js.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.eb9b5434.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.eb9b5434.chunk.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.eb9b5434.chunk.js.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.cdf17846.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.cdf17846.chunk.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.cdf17846.chunk.js.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.f1c56cb8.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.f1c56cb8.chunk.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.f1c56cb8.chunk.js.map.gz
Labels: 3 UI

#11841 Port reboot tracker catching failed and removed servers to 3.5.
  CHANGELOG
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/RebootTracker.cpp
Labels: 1 Bug

#11884 Hot-Backup encryption support (#11803)
  Documentation/DocuBlocks/Rest/Administration/get_admin_server_tls.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_list.md
  README
  arangod/Cluster/ClusterMethods.cpp
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/SslServerFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/StorageEngine/HotBackupCommon.h
  arangosh/Backup/BackupFeature.cpp
  js/client/modules/@arangodb/testsuites/dump.js
  tests/js/client/server_secrets/tls-rotation.js
Labels: 3 ImportExport

#11881 Fix restoring old arangodumps from ArangoDB 3.3
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Indexes/IndexFactory.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangosh/Restore/RestoreFeature.cpp
  tests/js/client/shell/shell-restore-integration.js
  tests/js/common/shell/shell-index-geo.js
Labels: 3 ImportExport

#11843 fix for BTS-84
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Indexes/IndexFactory.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangosh/Restore/RestoreFeature.cpp
  tests/js/client/shell/shell-restore-integration.js
  tests/js/common/shell/shell-index-geo.js
Labels: 3 ImportExport

#11885 ported fix for internal issue #701
  3rdParty/iresearch/core/index/index_writer.cpp
  3rdParty/iresearch/core/index/index_writer.hpp
  3rdParty/iresearch/core/utils/noncopyable.hpp
  CHANGELOG
Labels: 3 ArangoSearch

#11886 allow queries on DB-Servers
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryCursor.cpp
  arangod/Aql/SharedQueryState.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  js/client/modules/@arangodb/test-utils.js
  tests/js/client/shell/shell-query-dbserver-cluster.js
Labels: 9 Ready to Merge

#11807 Fix BTS-88 and replication overlap issue
  CHANGELOG
  arangod/Network/ConnectionPool.cpp
  arangod/Network/ConnectionPool.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/GlobalInitialSyncer.cpp
  arangod/Replication/Syncer.cpp
  arangod/Replication/utilities.cpp
  arangod/Replication/utilities.h
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  tests/IResearch/AgencyMock.cpp
  tests/IResearch/AgencyMock.h
Labels: 9 Ready to Merge

#11889 Allow AQL queries on DB-Servers again
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryCursor.cpp
  arangod/Aql/SharedQueryState.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  js/client/modules/@arangodb/test-utils.js
  tests/js/client/shell/shell-query-dbserver-cluster.js
Labels: 3 AQL, 9 Ready to Merge

#11890 Multiple fixes backported from devel
  CHANGELOG
  arangod/Network/ConnectionPool.cpp
  arangod/Network/ConnectionPool.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/GlobalInitialSyncer.cpp
  arangod/Replication/Syncer.cpp
  arangod/Replication/utilities.cpp
  arangod/Replication/utilities.h
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  tests/IResearch/AgencyMock.cpp
  tests/IResearch/AgencyMock.h
Labels: 9 Ready to Merge

#11891 Bug fix 3.6/fuerte connection pool reuse
  CHANGELOG
  arangod/Network/ConnectionPool.cpp
  arangod/Network/ConnectionPool.h
  tests/Network/ConnectionPoolTest.cpp
Labels: 9 Ready to Merge

#11879 Bug fix 3.4/ui permission display fix
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/userPermissionView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userPermissions.js
Labels: 1 Bug, 3 UI

#11897 fixed non-determinstic test failure in Pregel WCC test
  CHANGELOG
  tests/js/server/shell/shell-pregel.js
Labels: 9 Ready to Merge

#11896 add recovery test
  CHANGELOG
  tests/js/server/recovery/check-warnings.js
Labels: 3 - Testing, 9 Ready to Merge

#11900 fix a few useless warnings
  tests/Mocks/Servers.cpp
Labels: 3 - Testing, 9 Ready to Merge

#11898 fixed non-determinstic test failure in Pregel WCC test
  CHANGELOG
  tests/js/server/shell/shell-pregel.js
Labels: 3 - Testing, 3 Pregel, 9 Ready to Merge

#11894 [3.5] correct validation of keys in velocypack
  3rdParty/velocypack/src/Validator.cpp
  CHANGELOG
Labels: 1 Bug, velocypack

#11895 [3.4] correct validation of keys in velocypack
  3rdParty/velocypack/src/Validator.cpp
  CHANGELOG
Labels: 1 Bug, velocypack

#11878 Bug fix 3.5/ui permission display fix
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/templates.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/userPermissionView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userPermissions.js
Labels: 1 Bug, 3 UI

#11893 Leave isBuilding collections alone in the Supervision
  arangod/Agency/Supervision.cpp
Labels: 9 Ready to Merge

#11906 use "steady_clock" for profiling and not "system_clock" (#11904)
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/QueryCache.cpp
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryProfile.cpp
  arangod/Aql/Timing.cpp
  arangod/Aql/Timing.h
  arangod/CMakeLists.txt
Labels: 9 Ready to Merge

#11880 Do not translate Fuerte's Canceled into TRI_ERROR_REQUEST_CANCELED
  arangod/Network/Utils.cpp
Labels: 9 Ready to Merge

#11882 Do not abuse TRI_ERROR_REQUEST_CANCELED in Cluster code
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  lib/Rest/GeneralResponse.cpp
Labels: 9 Ready to Merge

#11818 Bug fix/assert on passthrough indexes
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/InputAqlItemRow.cpp
  arangod/Aql/InputAqlItemRow.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/ShadowAqlItemRow.cpp
  arangod/Aql/ShadowAqlItemRow.h
Labels: 9 Ready to Merge

#11859 Bug fix/improve replication logging
  3rdParty/fuerte/include/fuerte/message.h
  3rdParty/fuerte/include/fuerte/types.h
  3rdParty/fuerte/src/types.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Network/Methods.cpp
  arangod/Network/Methods.h
  arangod/Network/Utils.cpp
  arangod/Network/Utils.h
Labels: 9 Ready to Merge

#11903 better errors for failing arangorestore file ops
  arangosh/Restore/RestoreFeature.cpp
Labels: 9 Ready to Merge

#11665 Feature/register plan explainer
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/PlanCache.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/QueryOptions.cpp
  arangod/Aql/QueryOptions.h
  arangod/Aql/RegisterInfos.cpp
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/RegisterPlan.h
  arangod/Aql/types.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/Aql/RegisterPlanTest.cpp
Labels: 1 Feature, 9 Ready to Merge

#11907 [3.7] Leave isBuilding collections alone in the Supervision
  arangod/Agency/Supervision.cpp
Labels: 9 Ready to Merge

#11908 [3.7] Bug fix/add precondition for distribute shards like prototype
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/AgencyPaths.cpp
  arangod/Agency/AgencyPaths.h
  arangod/Agency/AsyncAgencyComm.h
  arangod/Agency/PathComponent.cpp
  arangod/Agency/PathComponent.h
  arangod/Agency/Supervision.cpp
  arangod/CMakeLists.txt
  arangod/Cluster/ClusterInfo.cpp
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestSupervisionStateHandler.cpp
  tests/AsyncAgencyComm/AsyncAgencyCommTest.cpp
  tests/Cluster/AgencyPathsTest.cpp
Labels: 9 Ready to Merge

#11913 Do not abuse TRI_ERROR_REQUEST_CANCELED in Cluster code (#11882)
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  lib/Rest/GeneralResponse.cpp
Labels: 3 Cluster, 9 Ready to Merge

#11915 fixed one more display permission issue
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userPermissions.js
Labels: 1 Bug, 3 UI

#11918 fix and test encryption rotation
  js/client/modules/@arangodb/testsuites/recovery.js
Labels: 9 Ready to Merge

#11919 Bug fix/assert on passthrough indexes (#11818)
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/InputAqlItemRow.cpp
  arangod/Aql/InputAqlItemRow.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/ShadowAqlItemRow.cpp
  arangod/Aql/ShadowAqlItemRow.h
Labels: 9 Ready to Merge

#11923 potential shutdown speedup (#11902)
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/AsyncAgencyComm.cpp
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
Labels: 3 Cluster

#11857 Use ResultT for looking up graphs
  arangod/Aql/Ast.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/QueryContext.cpp
  arangod/Aql/QueryContext.h
Labels: 9 Ready to Merge

#11934 [3.7] Disable new storage format
  CHANGELOG
  arangod/VocBase/LogicalCollection.h
  tests/js/common/shell/shell-collection.js
  tests/js/server/recovery/revision-trees-disabled.js
  tests/js/server/recovery/revision-trees-no-sync-disabled.js
  tests/js/server/recovery/revision-trees-partial-sync-disabled.js
Labels: 9 Ready to Merge

#11936 could do better breaking
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
Labels: 1 Bug

#11887 Feature/log json
  CHANGELOG
  arangod/IResearch/IResearchFeature.cpp
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/loggerView.js
  lib/Logger/LogBufferFeature.cpp
  lib/Logger/LogBufferFeature.h
  lib/Logger/LogMacros.h
  lib/Logger/LogTimeFormat.cpp
  lib/Logger/LogTimeFormat.h
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
  lib/Logger/LoggerFeature.cpp
  lib/Logger/LoggerFeature.h
  lib/Logger/LoggerStream.cpp
  lib/Logger/LoggerStream.h
Labels: 9 Ready to Merge

#11935 remove now-unneeded files
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_list.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_revisions_tree.md
  Documentation/DocuBlocks/Rest/Replication/post_api_replication_revisions_tree.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_revisions_documents.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_revisions_ranges.md
Labels: 3 Documentation

#11938 fix condition where empty ID is ok
  arangod/Cluster/ClusterMethods.cpp
Labels: 9 Ready to Merge

#11931 [3.7] Use ResultT for looking up graphs
  arangod/Aql/Ast.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/QueryContext.cpp
  arangod/Aql/QueryContext.h
Labels: 3 Graph

#11942 Add CHANGELOG entry for failover graph not found error
  CHANGELOG
Labels: 3 Documentation

#11926 Bug fix/make aql fast again 8
  arangod/Aql/AqlCallStack.cpp
  arangod/Aql/AqlCallStack.h
  arangod/Aql/AqlExecuteResult.cpp
  arangod/Aql/AqlItemBlockInputMatrix.cpp
  arangod/Aql/AqlItemBlockInputMatrix.h
  arangod/Aql/AqlItemBlockInputRange.cpp
  arangod/Aql/AqlItemBlockInputRange.h
  arangod/Aql/DependencyProxy.cpp
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/MultiAqlItemBlockInputRange.cpp
  arangod/Aql/MultiAqlItemBlockInputRange.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/SkipResult.cpp
  arangod/Aql/SkipResult.h
Labels: 9 Ready to Merge

#11944 Bug fix 3.7/fix condition where empty list is ok
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
Labels: 3 ImportExport

#11948 Fix hotbackup agency lock cleanup routine.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug

#11928 fixed overlapping shard syncs
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
Labels: 1 Bug

#11892 Bug fix/fix agency comm result swallowing errors
  3rdParty/velocypack/include/velocypack/Value.h
  3rdParty/velocypack/src/Builder.cpp
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/AgencyPaths.h
  arangod/Agency/AsyncAgencyComm.h
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/v8-cluster.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/GeneralServer/RestHandler.h
  lib/Basics/Result.cpp
  lib/Basics/Result.h
  lib/Basics/ResultT.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/V8/v8-globals.h
  tests/Cluster/AgencyPathsTest.cpp
Labels: 9 Ready to Merge

#11947 Fix hotbackup agency lock cleanup procedure.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug, 9 Ready to Merge

#11965 Fix query profile with parallel traversals
  arangod/Aql/Query.cpp
Labels: 9 Ready to Merge

#11959 adjust schema validation error message
  arangod/VocBase/LogicalCollection.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
Labels: 9 Ready to Merge

#11968 Bug fix 3.7/tryagain admin server whitelist
  arangod/GeneralServer/CommTask.cpp
Labels: 9 Ready to Merge

#11969 Fix query profile traversals
  arangod/Aql/Query.cpp
Labels: 9 Ready to Merge

#11974 [3.7] Cleanup after disabling new format
  arangod/Cluster/ClusterInfo.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Collections.cpp
  arangosh/Restore/RestoreFeature.h
  tests/js/server/upgrade-data/upgrade-data-collection-upgrade-msv3.6.0-disabled.js
Labels: 9 Ready to Merge

#11954 Bug fix/ui always refetch replication state
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/replicationView.js
Labels: 9 Ready to Merge

#11950 refresh user icon directly after changed
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/models/arangoUsers.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userView.js
Labels: 9 Ready to Merge

#11958 adjust schema validation error message
  arangod/VocBase/LogicalCollection.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
Labels: 9 Ready to Merge
