Repository arangodb/arangodb, pull requests merged in 2020-03, with the labels that each got.

#11208 avoid call to backtrace_symbols because it may malloc
  lib/Basics/CrashHandler.cpp
Labels: 9 Ready to Merge

#11207 simplify the register planning code a bit
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/RegisterPlan.h
Labels: 9 Ready to Merge

#11193 Stricter Foxx HTTP status handling
  CHANGELOG
  js/server/modules/@arangodb/foxx/router/response.js
  js/server/modules/@arangodb/foxx/service.js
Labels: 3 Foxx

#11217 Set 1800s timeout for resilience modules tests
  js/client/modules/@arangodb/testsuites/resilience.js
Labels: 3 - Testing

#11226 produce smaller output arrays when calculating the intersection of two IN lists
  arangod/Aql/Ast.cpp
Labels: 9 Ready to Merge

#11227 Use plain JSON Schema.
  arangod/VocBase/Validators.cpp
  tests/js/common/shell/shell-validation-rocksdb.js
Labels: 9 Review Required

#11222 remove the need to call stealComputedValue for AstNodes
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Graph/TraverserOptions.cpp
Labels: 9 Ready to Merge

#11224 fix usage of AQL functions CALL and APPLY from arangosh/client drivers
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Ast.cpp
  arangod/Aql/AstNode.cpp
  tests/js/client/shell/shell-aql-v8.js
  tests/js/client/shell/shell-statement.js
Labels: 9 Ready to Merge

#11211 fix nullptr dereference
  CHANGELOG
  arangod/Aql/DocumentProducingHelper.cpp
Labels: 9 Ready to Merge

#11216 Set 1800s timeout for resilience modules tests
  js/client/modules/@arangodb/testsuites/resilience.js
Labels: 3 - Testing, 9 Ready to Merge

#11218 Bug fix 3.6/foxx allow post body on delete request 2
  arangod/V8Server/v8-actions.cpp
  arangosh/Shell/V8ClientConnection.cpp
  lib/Rest/GeneralResponse.cpp
  lib/Rest/GeneralResponse.h
  lib/Rest/HttpResponse.h
  lib/Rest/VstResponse.cpp
  tests/js/client/shell/shell-foxx-interface.js
  tests/js/common/test-data/apps/interface/index.js
  tests/js/common/test-data/apps/interface/manifest.json
Labels: 9 Ready to Merge

#11219 fix performance of very resource intensive test (#11204)
  tests/js/server/shell/shell-index-rocksdb.js
Labels: 9 Ready to Merge

#11225 Fix the usage of the AQL functions `CALL` and `APPLY` for calling user-defined AQL functions
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Ast.cpp
  arangod/Aql/AstNode.cpp
  tests/js/client/shell/shell-aql-v8.js
  tests/js/client/shell/shell-statement.js
Labels: 9 Ready to Merge

#11237 legancy behaviour in maintenance mode
  CHANGELOG
  arangod/Agency/Supervision.cpp
Labels: 1 Bug

#11220 fix performance of very resource intensive test (#11204)
  tests/js/server/shell/shell-index-rocksdb.js
Labels: 9 Ready to Merge

#11238 [3.5] supervision maintenance legacy mode
  CHANGELOG
  arangod/Agency/Supervision.cpp
Labels: 1 Bug

#11102 SNI.
  CHANGELOG
  Documentation/DocuBlocks/Rest/Administration/get_admin_server_tls.md
  UnitTests/tls-ca.crt
  UnitTests/tls-ca.key
  UnitTests/tls.keyfile
  arangod/GeneralServer/AcceptorTcp.cpp
  arangod/GeneralServer/AsioSocket.h
  arangod/GeneralServer/GeneralServer.cpp
  arangod/GeneralServer/GeneralServer.h
  arangod/GeneralServer/SslServerFeature.cpp
  arangod/GeneralServer/SslServerFeature.h
  js/client/modules/@arangodb/testsuites/server_permissions.js
  lib/Ssl/ssl-helper.cpp
  lib/Ssl/ssl-helper.h
Labels: DO_NOT_MERGE

#10236 yet another agency ttl bug
  CHANGELOG
  arangod/Agency/AgencyCommon.h
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/State.cpp
Labels: 1 Bug, 9 WIP, Team Clifton

#10793 unttled supervision maintenance
  CHANGELOG
  arangod/Agency/AgencyStrings.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.h
Labels: 1 Bug

#11254 Wrong assertion
  arangod/Agency/Supervision.cpp
Labels: 1 Bug

#11209 Bug fix/fixes 03032020
  3rdParty/fuerte/include/fuerte/helper.h
  3rdParty/fuerte/src/H1Connection.cpp
  3rdParty/fuerte/src/H2Connection.cpp
  3rdParty/fuerte/src/helper.cpp
  3rdParty/fuerte/src/jwt.cpp
  arangod/Aql/Functions.cpp
  lib/Ssl/SslInterface.cpp
  lib/Ssl/SslInterface.h
Labels: 9 Ready to Merge

#11232 Mark --javascript.* options as Coordinator only
  CHANGELOG
  arangod/Cluster/ClusterFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/GeneralServer/ServerSecurityFeature.cpp
  arangod/RestServer/FrontendFeature.cpp
  arangod/V8Server/FoxxQueuesFeature.cpp
  arangod/V8Server/V8DealerFeature.cpp
  lib/ApplicationFeatures/V8SecurityFeature.cpp
Labels: 1 Bug, 3 Foxx, 3 JS API, 9 Waiting for Jenkins

#11261 fix SORT RAND() LIMIT 1 optimizer rule
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-remove-sort-rand-limit-rocksdb.js
Labels: 9 Ready to Merge

#11262 fix SORT RAND() LIMIT 1 optimizer rule
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-remove-sort-rand-limit-rocksdb.js
Labels: 9 Ready to Merge

#11259 Add docublocks for Merkle tree-based replication APIs
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_revisions_tree.md
  Documentation/DocuBlocks/Rest/Replication/post_api_replication_revisions_tree.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_revisions_documents.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_revisions_ranges.md
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Containers/MerkleTree.cpp
Labels: 9 Ready to Merge

#11187 Bug fix/supervision server cleanup
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/Store.cpp
  arangod/Agency/Store.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
Labels: 1 Feature

#10625 missing metrics
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
  arangod/RestServer/Metrics.cpp
  arangod/RestServer/Metrics.h
  arangod/RestServer/MetricsFeature.cpp
  arangod/RestServer/MetricsFeature.h
  arangod/Statistics/StatisticsFeature.h
  arangod/Statistics/StatisticsWorker.cpp
  tests/CMakeLists.txt
  tests/Metrics/MetricsFeatureTest.cpp
  tests/Metrics/MetricsTest.cpp
Labels: 9 WIP

#11080 Encryption key rotation
  Documentation/DocuBlocks/Rest/Administration/post_admin_server_encryption.md
  arangod/Aql/Expression.cpp
  arangod/GeneralServer/H2CommTask.cpp
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestHandler/RestAdminServerHandler.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBKeyBounds.cpp
  arangod/V8Server/v8-vocbase.cpp
  js/client/modules/@arangodb/testsuites/recovery.js
  js/common/bootstrap/modules/internal.js
  lib/Basics/FileUtils.cpp
  lib/Basics/FileUtils.h
  lib/Basics/StringUtils.h
  lib/Basics/VelocyPackHelper.cpp
  lib/Basics/conversions.cpp
  lib/Basics/datetime.cpp
  lib/V8/v8-utils.cpp
Labels: 9 Ready to Merge

#11269 fix newly created supervision bug with incremental updates
  arangod/Agency/Supervision.cpp
Labels: 1 Bug

#11015 Feature/satellite graphs
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/EngineInfoContainerDBServerServerBased.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/KShortestPathsNode.cpp
  arangod/Aql/KShortestPathsNode.h
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/QuerySnippet.cpp
  arangod/Aql/RegisterPlan.h
  arangod/Aql/ShardLocking.cpp
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/ShortestPathNode.h
  arangod/Aql/TraversalConditionFinder.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraversalNode.h
  arangod/Graph/BaseOptions.cpp
  arangod/Graph/BaseOptions.h
  arangod/Graph/Graph.cpp
  arangod/Graph/Graph.h
  arangod/Graph/GraphManager.cpp
  arangod/Graph/GraphManager.h
  arangod/Graph/ShortestPathOptions.cpp
  arangod/Graph/ShortestPathOptions.h
  arangod/Graph/TraverserOptions.cpp
  arangod/Graph/TraverserOptions.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/VocBase/Methods/Collections.cpp
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/graphManagementView.html
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalGraphTable.html
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/common/modules/@arangodb/general-graph-common.js
  js/common/modules/@arangodb/graph/helpers.js
  js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/general-graph.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/TypeTraits.h
  tests/js/client/http/api-gharial-spec.js
  tests/js/server/aql/aql-traversal-restrict-edge-collections.js
Labels: 1 Feature, DO_NOT_MERGE

#11234 Cluster Metrics
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Agent.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Agency/TimeString.h
  arangod/Aql/QueryList.cpp
  arangod/Cluster/Action.h
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/ActionBase.h
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/HeartbeatThread.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/Maintenance.h
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/MaintenanceWorker.cpp
  arangod/Cluster/MaintenanceWorker.h
  arangod/RestServer/AqlFeature.cpp
  arangod/RestServer/MetricsFeature.cpp
  arangod/RestServer/MetricsFeature.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Graph/GraphTestTools.h
  tests/IResearch/ExpressionFilter-test.cpp
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchOrder-test.cpp
  tests/Maintenance/MaintenanceFeatureMock.h
  tests/Maintenance/MaintenanceFeatureTest.cpp
  tests/Maintenance/MaintenanceTest.cpp
  tests/Mocks/Servers.cpp
  tests/RestServer/FlushFeature-test.cpp
  tests/js/client/http/cluster-metrics-cluster-spec.js
Labels: 9 Waiting for Jenkins

#11273 Fixed production check, removed assertion
  arangod/Graph/Graph.cpp
  arangod/Graph/Graph.h
  lib/Basics/Exceptions.h
Labels: 9 Ready to Merge

#11228 Docs: Add DocuBlocks for document validation.
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
  Documentation/DocuBlocks/collectionDatabaseCreate.md
  Documentation/DocuBlocks/collectionProperties.md
Labels: 1 Feature, 9 Review Required

#11287 Bug fix/fix temp file usage
  CHANGELOG
  lib/ApplicationFeatures/TempFeature.cpp
  lib/Basics/CrashHandler.cpp
  lib/Basics/CrashHandler.h
Labels: 9 Ready to Merge

#11264 improve validation
  3rdParty/json-schema-validation/include/validation/events_from_slice.hpp
  3rdParty/json-schema-validation/include/validation/types.hpp
  3rdParty/json-schema-validation/include/validation/validation.hpp
  3rdParty/json-schema-validation/src/validation.cpp
  3rdParty/taocpp-json.version
  3rdParty/taocpp-json/include/tao/json/binary_view.hpp
  3rdParty/taocpp-json/include/tao/json/contrib/schema.hpp
  3rdParty/taocpp-json/include/tao/json/events/compare.hpp
  3rdParty/taocpp-json/include/tao/json/span.hpp
  arangod/RestHandler/RestImportHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Validators.cpp
  arangod/VocBase/Validators.h
  arangosh/Import/ImportFeature.cpp
  arangosh/Import/ImportFeature.h
  arangosh/Import/ImportHelper.cpp
  arangosh/Import/ImportHelper.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/js/common/shell/shell-validation-rocksdb.js
Labels: 1 Bug, 9 Ready to Merge

#11280 Port memory detection override to 3.6.
  CHANGELOG
  lib/ApplicationFeatures/EnvironmentFeature.cpp
  lib/Basics/process-utils.cpp
  lib/Basics/process-utils.h
  lib/Logger/LogTopic.cpp
Labels: 1 Feature

#11294 Ungrey a failover test.
  CHANGELOG
  arangod/Cluster/FollowerInfo.cpp
Labels: 1 Bug

#11295 Fix an endless loop in FolloweInfo::persistInAgency.
  CHANGELOG
  arangod/Cluster/FollowerInfo.cpp
Labels: 1 Bug

#11296 Fix an endless loop in FollowerInfo::persistInAgency.
  CHANGELOG
  arangod/Cluster/FollowerInfo.cpp
Labels: 1 Bug

#10975 Documentation/typos 2020 01 24
  Documentation/DocuBlocks/Rest/Administration/JSF_get_admin_status.md
  Documentation/DocuBlocks/Rest/Administration/get_admin_server_role.md
  Documentation/DocuBlocks/Rest/Administration/get_admin_statistics.md
  Documentation/DocuBlocks/Rest/Administration/get_api_cluster_endpoints.md
  Documentation/DocuBlocks/Rest/Bulk/post_api_export.md
  Documentation/DocuBlocks/Rest/Cluster/get_cluster_health.md
  Documentation/DocuBlocks/Rest/Cluster/get_cluster_statistics.md
  Documentation/DocuBlocks/Rest/Cluster/put_cluster_maintenance.md
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_getResponsibleShard.md
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_shards.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
  Documentation/DocuBlocks/Rest/Foxx/api_foxx_commit.md
  Documentation/DocuBlocks/Rest/Foxx/api_foxx_development_disable.md
  Documentation/DocuBlocks/Rest/Foxx/api_foxx_development_enable.md
  Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_install.md
  Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_replace.md
  Documentation/DocuBlocks/Rest/Foxx/api_foxx_service_upgrade.md
  Documentation/DocuBlocks/Rest/Graph/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
  Documentation/DocuBlocks/Rest/Replication/delete_batch_replication.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_cluster_inventory.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_logger_first_tick.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_logger_follow.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_logger_tick_ranges.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_last_tick.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_range.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  Documentation/DocuBlocks/Rest/Replication/post_batch_replication.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_inventory.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_makeSlave.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_synchronize.md
  Documentation/DocuBlocks/Rest/Replication/put_batch_replication.md
  Documentation/DocuBlocks/Rest/Transactions/get_api_transactions.md
  Documentation/DocuBlocks/clusterAgencyEndpoint.md
  Documentation/DocuBlocks/clusterAgencyPrefix.md
  Documentation/DocuBlocks/clusterMyAddress.md
  Documentation/DocuBlocks/clusterPassword.md
  Documentation/DocuBlocks/clusterUsername.md
  Documentation/DocuBlocks/collectionFigures.md
  Documentation/DocuBlocks/collectionProperties.md
  README_maintainers.md
  arangod/Pregel/README.md
  arangod/VocBase/Methods/Databases.cpp
Labels: 3 Documentation

#10173 Fix some typos
  arangod/Cluster/ClusterInfo.cpp
  arangod/IResearch/Containers.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangosh/Backup/BackupFeature.cpp
  tests/IResearch/IResearchFeature-test.cpp
Labels: 9 Review Required

#11299 Bug fix/issue 11275
  CHANGELOG
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/common/shell/shell-hash-index.js
Labels: 9 Ready to Merge

#11245 Add DTRACE points to measure request timings.
  CHANGELOG
  CMakeLists.txt
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/GeneralServer/SslServerFeature.cpp
  arangod/GeneralServer/SslServerFeature.h
  arangod/GeneralServer/VstCommTask.cpp
  lib/Basics/dtrace-wrapper.h
  lib/Basics/sdt.h
  scripts/exampleMeasureMethod.bt
  scripts/measureRequestLife.bt
  scripts/showRequestLife.bt
Labels: 1 Feature, DO_NOT_MERGE

#11316 compilation fixes for clang-10s more strict checking
  CHANGELOG
  arangod/Agency/FailedLeader.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Pregel/Algos/DMID/DMID.cpp
  arangod/Pregel/Algos/DMID/VertexSumAggregator.h
  arangod/Pregel/Algos/SLPA.cpp
  arangod/RestServer/Metrics.cpp
  arangod/RestServer/Metrics.h
  arangod/RestServer/counter.h
  arangod/Statistics/StatisticsWorker.cpp
  arangod/Statistics/StatisticsWorker.h
  tests/Aql/EnumerateCollectionExecutorTest.cpp
  tests/Aql/ExecutorTestHelper.h
Labels: 1 Bug

#11323 fix "fix" for collection figures
  arangod/Cluster/ClusterMethods.cpp
  tests/rb/HttpInterface/api-collection-rocksdb-spec.rb
Labels: 9 Ready to Merge

#11319 Bug fix/fixes 20200318
  arangod/Agency/MoveShard.cpp
  arangod/Aql/AqlCall.h
  arangod/Aql/LimitStats.cpp
  arangod/Cache/CachedValue.cpp
  arangod/Graph/AttributeWeightShortestPathFinder.cpp
  arangod/Graph/ConstantWeightShortestPathFinder.cpp
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Pregel/OutgoingCache.cpp
  arangod/Utils/ExecContext.cpp
  arangod/Utils/ExecContext.h
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
Labels: 9 Ready to Merge

#11322 fix "fix" for collection figures
  arangod/Cluster/ClusterMethods.cpp
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.0c6816311ecba44ddcade5abdeaa3535.js
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.0c6816311ecba44ddcade5abdeaa3535.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.748966b23ba8bc398359b4637e978078.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js.gz
  tests/rb/HttpInterface/api-collection-rocksdb-spec.rb
Labels: 9 Ready to Merge

#11328 [3.6] Bug fix/fix one shard satellite access
  CHANGELOG
Labels: 9 Ready to Merge

#11326 Fix isAdminUser.
  arangod/Actions/RestActionHandler.cpp
  arangod/Auth/User.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/Replication/GlobalInitialSyncer.cpp
  arangod/Replication/GlobalTailingSyncer.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/SystemDatabaseFeature.cpp
  arangod/RestServer/VocbaseContext.cpp
  arangod/RestServer/VocbaseContext.h
  arangod/Utils/ExecContext.cpp
  arangod/Utils/ExecContext.h
  arangod/V8Server/v8-vocbase.cpp
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/RestHandler/RestAnalyzerHandler-test.cpp
  tests/RestHandler/RestUsersHandler-test.cpp
  tests/RestHandler/RestViewHandler-test.cpp
  tests/Transaction/Manager-test.cpp
  tests/Transaction/RestTransactionHandler-test.cpp
  tests/V8Server/v8-analyzers-test.cpp
  tests/V8Server/v8-users-test.cpp
  tests/V8Server/v8-views-test.cpp
  tests/VocBase/LogicalView-test.cpp
  tests/js/client/authentication/admin-cluster-apis.js
  tests/js/server/shell/shell-readonly-mode-spec.js
Labels: 1 Bug

#11320 remove unused header files
  lib/Basics/SameThreadAsserter.h
  lib/SimpleHttpClient/Callbacks.h
Labels: 9 Ready to Merge

#11331 revert HTTP return code change for user API, add tests
  arangod/GeneralServer/CommTask.cpp
  tests/js/client/authentication/auth.js
Labels: 9 Ready to Merge

#11341 Bug fix/schema validation return code
  arangod/VocBase/Validators.cpp
  lib/ApplicationFeatures/EnvironmentFeature.cpp
  lib/Rest/GeneralResponse.cpp
  tests/rb/HttpInterface/api-collection-rocksdb-spec.rb
Labels: 9 Ready to Merge

#11346 Allow easier removal of validation rules.
  arangod/VocBase/LogicalCollection.cpp
Labels: 3 Core

#11052 Bug fix/fix msvc2019 build
  3rdParty/V8/v7.9.317/src/codegen/source-position.h
  VERSIONS
  arangod/Aql/AqlItemMatrix.cpp
  arangod/Pregel/GraphStore.h
Labels: 3 Build, 4 Windows
