Repository arangodb/arangodb, pull requests merged in 2020-11, with the labels that each got.

#12950 added memory profiles, fixed memory leak
  3rdParty/CMakeLists.txt
  3rdParty/fuerte/src/AsioSockets.h
  3rdParty/jemalloc/CMakeLists.txt
  CHANGELOG
  CMakeLists.txt
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/HeartbeatThread.h
  arangod/RestHandler/RestStatusHandler.cpp
  arangod/RestHandler/RestStatusHandler.h
Labels: 3 Kubernetes

#12960 3.5 backport fix BTS-233
  CHANGELOG
  arangod/IResearch/IResearchRocksDBRecoveryHelper.h
  tests/CMakeLists.txt
  tests/IResearch/IResearchRocksDBRecoveryHelper-test.cpp
  tests/js/server/recovery/view-arangosearch-link-populate.js
Labels: 3 ArangoSearch

#12959 3.6 backport fix BTS-233
  CHANGELOG
  arangod/IResearch/IResearchRocksDBRecoveryHelper.h
  tests/CMakeLists.txt
  tests/IResearch/IResearchRocksDBRecoveryHelper-test.cpp
  tests/js/server/recovery/view-arangosearch-link-populate.js
Labels: 3 ArangoSearch

#12925 Feature 3.7/jeprof
  3rdParty/CMakeLists.txt
  3rdParty/fuerte/src/AsioSockets.h
  3rdParty/jemalloc/CMakeLists.txt
  CHANGELOG
  CMakeLists.txt
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/HeartbeatThread.h
  arangod/RestHandler/RestStatusHandler.cpp
  arangod/RestHandler/RestStatusHandler.h
Labels: 1 Bug

#12958 fix potential deadlock in cluster transactions
  CHANGELOG
  arangod/Transaction/Manager.cpp
  js/client/modules/@arangodb/test-utils.js
  tests/js/client/shell/shell-transaction-intermediate-commit-cluster-rocksdb.js
Labels: 1 - Ready, 3 Cluster

#12957 fix potential deadlock in cluster transactions
  CHANGELOG
  arangod/Transaction/Manager.cpp
  js/client/modules/@arangodb/test-utils.js
  tests/js/client/shell/shell-transaction-intermediate-commit-cluster-rocksdb.js
Labels: 9 Ready to Merge

#12956 fix potential deadlock in cluster transactions
  CHANGELOG
  arangod/Transaction/Manager.cpp
  tests/js/client/shell/shell-transaction-intermediate-commit-cluster.js
Labels: 9 Ready to Merge

#12969 catch exceptions in supervision and heartbeat thread
  CHANGELOG
  arangod/Agency/Supervision.cpp
  arangod/Cluster/HeartbeatThread.cpp
Labels: 9 Ready to Merge

#12968 added missing exception handling to supervision and heartbeat threads
  CHANGELOG
  arangod/Agency/Supervision.cpp
  arangod/Cluster/HeartbeatThread.cpp
Labels: 9 Ready to Merge

#12932 Fix #12778: Typo in special property string for schema validation
  3rdParty/json-schema-validation/src/validation.cpp
  CHANGELOG
  tests/js/common/shell/shell-validation.js
Labels: 1 Bug, 3 Graph, 3 Schema Validation, 9 Ready to Merge

#12903 Docs: Remove indexBuckets, journalSize, doCompact, isVolatile from docs
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
  Documentation/DocuBlocks/collectionCreateEdgeCollection.md
  Documentation/DocuBlocks/collectionDatabaseCreate.md
  Documentation/DocuBlocks/collectionProperties.md
Labels: 3 Documentation, 3 MMFiles

#12967 Fix #12778: Typo in special property string for schema validation
  3rdParty/json-schema-validation/src/validation.cpp
  CHANGELOG
  tests/js/common/shell/shell-validation.js
Labels: 1 Bug, 3 Graph, 3 Schema Validation, 9 Ready to Merge

#12978 Fix REST API endpoint PUT `/_api/collection/<collection>/recalculateCount
  CHANGELOG
  arangod/ClusterEngine/RocksDBMethods.cpp
  tests/js/client/shell/shell-recalculate-count-cluster.js
  tests/js/client/shell/shell-recalculate-count-noncluster.js
Labels: 9 Ready to Merge

#12979 Fix REST API endpoint PUT `/_api/collection/<collection>/recalculateCount
  CHANGELOG
  arangod/ClusterEngine/RocksDBMethods.cpp
  tests/js/client/shell/shell-recalculate-count-cluster-rocksdb.js
  tests/js/client/shell/shell-recalculate-count-noncluster-rocksdb.js
Labels: 9 Ready to Merge

#12977 Fix deadlocks between write transactions and hotbackup, take 2
  CHANGELOG
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  arangod/Transaction/Options.cpp
  arangod/Transaction/Options.h
  tests/Transaction/Manager-test.cpp
Labels: 3 ImportExport

#12999 Feature 3.6/arangobench by duration
  CHANGELOG
  arangosh/Benchmark/BenchFeature.cpp
  arangosh/Benchmark/BenchFeature.h
  arangosh/Benchmark/BenchmarkCounter.h
  arangosh/Benchmark/BenchmarkThread.h
  js/client/modules/@arangodb/testsuites/arangobench.js
Labels: 3 Benchmark, performance

#13005 Fix deadlocks between write transactions and hotbackup, take 2
  CHANGELOG
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  arangod/Transaction/Options.cpp
  arangod/Transaction/Options.h
  arangod/V8Server/v8-actions.cpp
  js/server/bootstrap/modules/internal.js
  lib/Maskings/AttributeMasking.cpp
  lib/Maskings/Collection.cpp
  tests/Transaction/Manager-test.cpp
  tests/js/client/shell/shell-deadlock-trx-hotbackup-cluster.js
Labels: 3 Cluster, 3 ImportExport

#12994 basic support for DOCUMENT function on DB servers in OneShard setups
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/AqlFunctionFeature.h
  arangod/Aql/Ast.cpp
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  arangod/Aql/Function.cpp
  arangod/Aql/Function.h
  arangod/Aql/Functions.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Transaction/Methods.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  tests/IResearch/ExpressionFilter-test.cpp
  tests/IResearch/IResearchFilterArrayIn-test.cpp
  tests/IResearch/IResearchFilterArrayInterval-test.cpp
  tests/IResearch/IResearchFilterBoolean-test.cpp
  tests/IResearch/IResearchFilterCompare-test.cpp
  tests/IResearch/IResearchFilterFunction-test.cpp
  tests/IResearch/IResearchFilterIn-test.cpp
  tests/IResearch/IResearchOrder-test.cpp
  tests/IResearch/IResearchQueryCommon.h
  tests/IResearch/IResearchViewSorted-test.cpp
  tests/js/server/aql/aql-modify-noncluster.js
Labels: 9 Ready to Merge

#13004 Fix deadlocks between write transactions and hotbackup, take 2
  CHANGELOG
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  arangod/Transaction/Options.cpp
  arangod/Transaction/Options.h
  arangod/V8Server/v8-actions.cpp
  js/server/bootstrap/modules/internal.js
  lib/Maskings/AttributeMasking.cpp
  lib/Maskings/Collection.cpp
  lib/Maskings/Maskings.cpp
  tests/Transaction/Manager-test.cpp
  tests/js/client/shell/shell-deadlock-trx-hotbackup-cluster.js
Labels: 3 Cluster

#12998 Feature 3.7/arangobench by duration
  CHANGELOG
  arangosh/Benchmark/BenchFeature.cpp
  arangosh/Benchmark/BenchFeature.h
  arangosh/Benchmark/BenchmarkCounter.h
  js/client/modules/@arangodb/testsuites/arangobench.js
Labels: 3 - Testing, 3 Benchmark

#13024 Bug fix 3.5/clang 12
  CMakeLists.txt
Labels: 3 Build, 4 MacOSX

#13022 Bug fix 3.7/prune one shard
  CHANGELOG
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/ShortestPathNode.h
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraversalNode.h
  js/server/modules/@arangodb/aql-graph-traversal-generic-tests.js
Labels: 1 Bug, 3 AQL, 3 Cluster, 3 Graph

#13029 Disable warning for clang-12 on macOS
  CMakeLists.txt
Labels: 3 Build, 4 MacOSX

#13027 [3.7] smartgraph view no duplicate data
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  tests/js/server/dump/dump-cluster.js
Labels: 1 Bug

#13030 Disable warning for clang-12 on macOS
  CMakeLists.txt
Labels: 3 Build, 4 MacOSX

#13053 Fix internal issue #777 for 3.7
  CHANGELOG
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  tests/IResearch/IResearchQueryNoMaterialization-test.cpp
  tests/js/server/aql/aql-optimizer-rule-no-document-materialization-arangosearch.js
Labels: 1 Bug, 3 ArangoSearch

#13045 Feature 3.7/arangobench add json report check2
  arangosh/Benchmark/BenchFeature.cpp
  js/client/modules/@arangodb/testsuites/arangobench.js
Labels: 3 - Testing

#13050 Make the number of network I/O threads configurable
  CHANGELOG
  arangod/Network/NetworkFeature.cpp
Labels: 9 Ready to Merge

#13067 Bug fix 3.6.9/fuerte shutdown fix
  3rdParty/fuerte/src/AsioSockets.h
  3rdParty/fuerte/src/GeneralConnection.cpp
  3rdParty/fuerte/src/HttpConnection.cpp
  3rdParty/jemalloc/CMakeLists.txt
  CHANGELOG
  CMakeLists.txt
  arangod/RestHandler/RestStatusHandler.cpp
  arangod/RestHandler/RestStatusHandler.h
Labels: 3 Cluster

#13074 make sure we catch syntax error while eval'ing in runInLocalArangosh
  js/client/modules/@arangodb/testutils/test-utils.js
Labels: 3 - Testing

#13078 3.7: make sure we catch syntax error while eval'ing in runInLocalArangosh …
  js/client/modules/@arangodb/test-utils.js
Labels: 3 - Testing

#13071 Update OpenSSL to 1.1.1h (3.7)
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#13072 Update OpenSSL to 1.1.1h (3.6)
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#13073 Update OpenSSL to 1.1.1h (3.5)
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#13070 Update OpenSSL to 1.1.1h
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#13083 added load-balancing support for several query-related APIs
  CHANGELOG
  Documentation/DocuBlocks/Rest/AQL/DeleteApiQueryKill.md
  Documentation/DocuBlocks/Rest/AQL/DeleteApiQuerySlow.md
  Documentation/DocuBlocks/Rest/AQL/GetApiQueryCurrent.md
  Documentation/DocuBlocks/Rest/AQL/GetApiQuerySlow.md
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryList.h
  arangod/CMakeLists.txt
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestQueryHandler.h
  arangod/V8Server/v8-vocbase.cpp
  arangod/VocBase/Methods/Queries.cpp
  arangod/VocBase/Methods/Queries.h
  js/client/modules/@arangodb/aql/queries.js
  js/server/modules/@arangodb/aql/queries.js
  tests/js/client/load-balancing/load-balancing-queries-noauth-cluster.js
  tests/js/client/server_permissions/test-queries-all-databases.js
  tests/js/client/shell/shell-queries-all-databases.js
Labels: 9 Ready to Merge

#13082 backported additional AQL query metrics to 3.6
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/RestServer/Metrics.h
  arangod/RestServer/MetricsFeature.h
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
  tests/Metrics/MetricsTest.cpp
Labels: 9 Ready to Merge

#13086 Make cancelation of asynchronoulsly started JS transactions safe
  CHANGELOG
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestTransactionHandler.h
Labels: 9 Ready to Merge

#13042 Bug fix/fuerte return full status header (#13038)
  3rdParty/fuerte/src/HttpConnection.cpp
  CHANGELOG
  arangosh/Shell/V8ClientConnection.cpp
  arangosh/Shell/V8ClientConnection.h
  tests/js/client/shell/shell-fuerte-response.js
Labels: 9 Ready to Merge

#13062 Docs: Check protocol(), throw if not http/1.1, don't filter common headers
  js/client/bootstrap/modules/internal.js
Labels: 3 API, 3 Documentation, 3 JS API

#13105 Bug fix 3.7/executionblockimpl hasmore assertion
  arangod/Aql/AqlExecuteResult.cpp
  arangod/Aql/ExecutionBlockImpl.cpp
  tests/js/server/aql/aql-shadowrow-block-return-regression.js
Labels: 1 Bug, 9 Ready to Merge

#13101 fix initial population of AgencyCache
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
Labels: 3 Cluster

#13085 Make cancelation of asynchronoulsly started JS transactions safe
  CHANGELOG
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestTransactionHandler.h
Labels: 9 Ready to Merge

#13090 fix activation of maintenance via REST API `/_admin/cluster/maintenance`
  CHANGELOG
  arangod/Agency/Supervision.h
  arangod/RestHandler/RestAdminClusterHandler.cpp
Labels: 9 Ready to Merge

#13096 Fix zero distance geo NN search
  CHANGELOG
  arangod/GeoIndex/Index.cpp
  arangod/GeoIndex/Near.cpp
  lib/Geo/GeoParams.h
  tests/js/server/aql/aql-queries-geo.js
Labels: 3 Geo, 9 Ready to Merge

#13055 [3.7] fix gauge assignment operators
  CHANGELOG
  arangod/RestServer/Metrics.h
  tests/Metrics/MetricsTest.cpp
Labels: 1 Bug

#13111 3.7: forward headers that are treated special into foxx as well. (#13068)
  3rdParty/fuerte/include/fuerte/message.h
  3rdParty/fuerte/include/fuerte/types.h
  3rdParty/fuerte/src/message.cpp
  3rdParty/fuerte/src/types.cpp
  CHANGELOG
  arangod/V8Server/v8-actions.cpp
  arangosh/Shell/V8ClientConnection.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Rest/GeneralRequest.h
  lib/Rest/HttpRequest.cpp
  lib/Rest/VstRequest.cpp
  tests/js/client/shell/shell-foxx-api-spec.js
  tests/js/common/test-data/apps/headers/index.js
Labels: 3 Foxx

#13113 fix status reporting of skipped endpoint tests
  js/client/modules/@arangodb/testsuites/endpoints.js
Labels: 3 - Testing
