Repository arangodb/arangodb, pull requests merged in 2020-01, with the labels that each got.

#10782 Add ID (Bahasa Indonesia) translation for "Bye bye!" on arangosh exit
  lib/Basics/messages.h
Labels: 9 CLA available

#10796 Bug fix 3.5/hot backup maintenance mode with ttl
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  js/actions/api-cluster.js
Labels: 1 Bug, 3.5.4

#10811 fix creating of logfiles (#10708)
  CHANGELOG
  Installation/Windows/Templates/NSIS.template.in
Labels: 3 Packaging, 3.6.1

#10798 Updated arangosync to 0.7.2
  CHANGELOG
  VERSIONS
Labels: 3.6.1, 9 Waiting for Jenkins

#10767 try to make test more robust
  tests/js/client/shell/shell-transaction.js
Labels: 3 - Testing, 3.6.1, 9 Ready to Merge

#10772 Fixed removing outdated readers from cache
  3rdParty/iresearch/core/index/index_writer.cpp
  CHANGELOG
Labels: 1 Bug, 3.6.1, 9 Ready to Merge

#10830 Docs: Add missing orphanCollections property
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Labels: 1 Bug, 3 Documentation

#10807 Add missing orphanCollections property
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Labels: 1 Bug, 3 Documentation, 3.6.1

#10809 disable parallel AQL when there are traversals or shortest paths queries
  CHANGELOG
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Labels: 3.6.1

#10756 Bug fix/collection create failure cleanup
  arangod/Cluster/ClusterInfo.cpp
  tests/js/common/shell/shell-cluster-collection.js
Labels: 1 Bug, 3 Cluster

#10833 hide swagger list by default
  CHANGELOG
  js/server/assets/swagger/index.html
Labels: 1 Feature, 3 Swagger, 3 UI

#10834 Fix returning blocks with shadow rows to the AqlItemBlockManager
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlItemBlockManager.cpp
  tests/js/server/aql/aql-shadowrow-block-return-regression.js
Labels: 1 Bug, 3 AQL

#10814 Feature 3.5/start sut only once if needed Blacklist here
  UnitTests/OskarTestSuitesBlackList
Labels: 3.5.4, 9 Ready to Merge

#10815 blacklist non existing suite
  UnitTests/OskarTestSuitesBlackList
Labels: 9 Ready to Merge, for 3.4.9

#10826 3.4: propagate js version variable into the client package
  CHANGELOG
  cmake/packages/client/nsis.txt
Labels: 9 Ready to Merge, for 3.4.9

#10813 Feature 3.6/start sut only once if needed - blacklist here
  UnitTests/OskarTestSuitesBlackList
Labels: 3.6.1, 9 Ready to Merge

#10859 3.6: Ship arangoinspect with Windows client package and DDLs only once (#10835)
  CHANGELOG
  arangosh/install.cmake
  cmake/ArangoDBInstall.cmake
  cmake/InstallMacros.cmake
  cmake/packages/client/nsis.txt
Labels: 3.6.1, 9 Ready to Merge

#10750 fixed issue 10725
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
Labels: 9 Ready to Merge

#10862 Ship arangoinspect with Windows client package and DDLs only once (#10835
  CHANGELOG
  arangosh/install.cmake
  cmake/ArangoDBInstall.cmake
  cmake/InstallMacros.cmake
  cmake/packages/client/nsis.txt
Labels: 3.3.25, 9 Ready to Merge

#10864 switch log-file location depending on all/user installation, remove on uninstallation (#10832)
  CHANGELOG
  Installation/Windows/Plugins/BaseDir.nsh
  Installation/Windows/Templates/NSIS.template.in
Labels: 3.6.1, 9 Ready to Merge

#10790 Update README.md
  README.md
Labels: 3 Documentation, 9 CLA available

#10837 Fix string comparison for AstNodes
  CHANGELOG
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/TraversalConditionFinder.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
Labels: 1 Bug, 3 AQL

#10856 Bug fix 3.6/traversal cache
  CHANGELOG
  arangod/Aql/TraversalExecutor.cpp
  arangod/Cluster/ClusterTraverser.cpp
  arangod/Cluster/ClusterTraverser.h
  arangod/Graph/SingleServerTraverser.cpp
  arangod/Graph/SingleServerTraverser.h
  arangod/Graph/Traverser.h
  tests/Aql/TraversalExecutorTest.cpp
Labels: 3.6.1

#9943 naively implement timeout for waitpid
  lib/Basics/process-utils.cpp
  lib/V8/v8-utils.cpp
Labels: 9 Waiting for Jenkins

#10836 Bug fix 3.6/reset shadowrows block on return
  CHANGELOG
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlItemBlockManager.cpp
  tests/js/server/aql/aql-shadowrow-block-return-regression.js
Labels: 1 Bug, 3 AQL, 3.6.1, 9 Ready to Merge

#10875 Bug fix 3.6/ast node string compare
  CHANGELOG
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/TraversalConditionFinder.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
Labels: 3.6.1

#10889 [3.6] Bug fix/issue 10852
  CHANGELOG
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/InputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/SingleRowFetcher.cpp
  arangod/Aql/SingleRowFetcher.h
  arangod/Aql/SubqueryEndExecutor.cpp
  arangod/Aql/SubqueryEndExecutor.h
  arangod/Aql/SubqueryStartExecutor.cpp
  arangod/Aql/SubqueryStartExecutor.h
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
Labels: 1 Bug, 3 AQL, 3.6.1

#10802 Bug fix 3.6/traversal collection detection fix
  CHANGELOG
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  tests/js/server/aql/aql-graph-traverser.js
Labels: 3.6.1, 9 Ready to Merge

#10865 Bug fix/issue 10852
  CHANGELOG
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/InputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/SingleRowFetcher.cpp
  arangod/Aql/SingleRowFetcher.h
  arangod/Aql/SubqueryEndExecutor.cpp
  arangod/Aql/SubqueryEndExecutor.h
  arangod/Aql/SubqueryStartExecutor.cpp
  arangod/Aql/SubqueryStartExecutor.h
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
Labels: 1 Bug, 3 AQL

#10876 try to make shell-ttl less time-dependent
  tests/js/common/shell/shell-ttl.js
Labels: 3.5.4, 9 Waiting for Jenkins

#10857 Bug fix 3.5/traversal cache
  CHANGELOG
  arangod/Aql/TraversalExecutor.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/Cluster/ClusterTraverser.cpp
  arangod/Cluster/ClusterTraverser.h
  arangod/Graph/ShortestPathOptions.cpp
  arangod/Graph/SingleServerTraverser.cpp
  arangod/Graph/SingleServerTraverser.h
  arangod/Graph/Traverser.h
  tests/Aql/TraversalExecutorTest.cpp
Labels: 3.5.4, 9 Ready to Merge

#10858 Bug fix 3.4/traversal cache
  CHANGELOG
  arangod/Aql/TraversalBlock.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/Cluster/ClusterTraverser.cpp
  arangod/Cluster/ClusterTraverser.h
  arangod/Graph/ShortestPathOptions.cpp
  arangod/Graph/SingleServerTraverser.cpp
  arangod/Graph/SingleServerTraverser.h
  arangod/Graph/Traverser.h
  arangod/Graph/TraverserCache.cpp
  arangod/Graph/TraverserCache.h
  lib/Basics/StringHeap.cpp
  lib/Basics/StringHeap.h
Labels: 9 Ready to Merge, for 3.4.9

#10801 Bug fix/traversal collection detection fix
  CHANGELOG
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  tests/js/server/aql/aql-graph-traverser.js
Labels: 9 Ready to Merge

#10887 Documentation 3.5/graph orphan collections
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_create.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_download.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_upload.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_hash.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_skiplist.md
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
  Documentation/DocuBlocks/Rest/User Management/README.md
Labels: 1 Bug, 3 Documentation, 3.5.4, 9 Waiting for Jenkins

#10888 Documentation 3.4/graph orphan collections
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_hash.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_skiplist.md
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
  Documentation/DocuBlocks/Rest/User Management/README.md
Labels: 1 Bug, 3 Documentation, 9 Waiting for Jenkins, for 3.4.9

#10881 Bug fix 3.4/windows exe product info
  CHANGELOG
  arangod/CMakeLists.txt
Labels: 1 Bug, 3 Packaging, 4 Windows, 9 Waiting for Jenkins, for 3.4.9

#10880 Bug fix 3.5/windows exe product info
  CHANGELOG
  arangod/CMakeLists.txt
Labels: 1 Bug, 3 Packaging, 3.5.4, 4 Windows

#10869 Bug fix/windows exe product info
  CHANGELOG
  arangod/CMakeLists.txt
Labels: 1 Bug, 3 Packaging, 4 Windows, 9 Waiting for Jenkins

#10861 3.4: Ship arangoinspect with Windows client package and DDLs only once (#10835
  CHANGELOG
  arangosh/install.cmake
  cmake/ArangoDBInstall.cmake
  cmake/InstallMacros.cmake
  cmake/packages/client/nsis.txt
Labels: 9 Waiting for Jenkins, for 3.4.9

#10868 Bug fix 3.6/windows exe product info
  CHANGELOG
  arangod/CMakeLists.txt
Labels: 1 Bug, 3 Packaging, 3.6.1, 4 Windows, 9 Waiting for Jenkins

#10892 [3.5] moveshard checks _to in sync for shard group
  CHANGELOG
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
Labels: 1 Bug, 3.5.4

#10894 [3.4] moveshard checks _to in sync for shard group
  CHANGELOG
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
Labels: 1 Bug, 3 Cluster, for 3.4.9

#10901 fix edge case with padding in VelocyPack arrays
  3rdParty/velocypack/include/velocypack/Slice.h
  3rdParty/velocypack/src/Builder.cpp
Labels: 9 Ready to Merge

#10873 [3.4] AstNode stringEquals rewrite
  CHANGELOG
  arangod/Aql/AstNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/TraversalConditionFinder.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/js/server/aql/aql-traversal-graph-object-regression.js
Labels: for 3.4.9

#10874 [3.5] AstNode stringEquals rewrite
  CHANGELOG
  arangod/Aql/AstNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/TraversalConditionFinder.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/js/server/aql/aql-traversal-graph-object-regression.js
Labels: 3.5.4

#10820 3.5 Bug-Fix and Refactoring work on resetDeadJobs
  CHANGELOG
  js/server/modules/@arangodb/foxx/queues/manager.js
Labels: 3.5.4, 9 Ready to Merge

#10906 [3.5] moveshard insync follower part 2
  arangod/Agency/MoveShard.cpp
Labels: 3.5.4

#10905 Bug fix/issue 10852 part2
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/SubqueryStartExecutor.cpp
  arangod/Aql/SubqueryStartExecutor.h
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
Labels: 1 Bug, 3 AQL, 9 Ready to Merge

#10819 3.4 Bug-Fix and Refactoring work on resetDeadJobs
  CHANGELOG
  js/server/modules/@arangodb/foxx/queues/manager.js
Labels: 9 Ready to Merge, for 3.4.9

#10917 Bug fix 3.4/restore feature collection order
  arangosh/Restore/RestoreFeature.cpp
Labels: 9 Waiting for Jenkins, for 3.4.9

#10646 Parallel Move Shard
  CHANGELOG
  arangod/Agency/AgencyStrings.h
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/MoveShard.h
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/State.cpp
  arangod/Agency/Store.cpp
  arangod/Agency/Supervision.cpp
  arangod/Cluster/TakeoverShardLeadership.cpp
  tests/Agency/FailedFollowerTest.cpp
  tests/Agency/MoveShardTest.cpp
  tests/Agency/NodeTest.cpp
Labels: 9 Ready to Merge

#10893 [3.6] moveshard checks _to in sync for shard group
  CHANGELOG
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
Labels: 1 Bug, 3 Cluster, 3.6.1

#10902 don't use alignas for these shared_ptrs, as it confuses Valgrind and is not necessary
  CHANGELOG
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
Labels: 9 Ready to Merge

#10821 3.6 Bug-Fix and Refactoring work on resetDeadJobs
  CHANGELOG
  js/server/modules/@arangodb/foxx/queues/manager.js
Labels: 3.6.1, 9 Ready to Merge

#10883 [3.6] Add regression test for AstNode string comparison fix
  tests/js/server/aql/aql-traversal-graph-object-regression.js
Labels: 3.6.1

#10904 fix edge case with padding in VelocyPack arrays
  3rdParty/velocypack/include/velocypack/Slice.h
  3rdParty/velocypack/src/Builder.cpp
  CHANGELOG
Labels: 9 Ready to Merge

#10930 add support for trailing commas in AQL
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-parse.js
Labels: 9 Ready to Merge

#10932 send ints to short statistics route instead of doubles
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/dashboardView.js
Labels: 9 Ready to Merge

#10923 bugfix for https://github.com/arangodb/arangodb/issues/10845#issuecomment-575723029
  CHANGELOG
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/IndexNodeOptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.js
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-rocksdb.js
  tests/js/server/aql/aql-view-arangosearch-server.js
Labels: 9 Ready to Merge

#10151 make V8 gyp issue testTrackFileAccess, flush our Oskar cache
  3rdParty/V8/CMakeLists.txt
  3rdParty/V8/v7.1.302.28/tools/gyp/pylib/gyp/generator/msvs.py
Labels: 9 WIP

#10927 Fix for #10897
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-collect-subquery-scope-regression.js
Labels: 1 Bug

#10941 [3.6] Fix scoping error when COLLECT is used in a subquery
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-collect-subquery-scope-regression.js
Labels: 3.6.1, 9 Ready to Merge

#10945 Bug fix/issue 10896
  3rdParty/velocypack/include/velocypack/Iterator.h
  CHANGELOG
  arangod/Aql/CollectNode.cpp
  tests/Aql/QueryHelper.cpp
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
  tests/js/server/aql/aql-optimizer-collect-into.js
  tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Labels: 1 Bug, 3 AQL

#10909 [3.6] Bug fix/issue 10852 part2
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/SubqueryStartExecutor.cpp
  arangod/Aql/SubqueryStartExecutor.h
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
Labels: 1 Bug, 3 AQL, 3.6.1, 9 Ready to Merge

#10929 [3.6] server side system report
  CHANGELOG
  arangod/Aql/ResourceUsage.h
  arangod/CMakeLists.txt
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/RestHandler/RestMetricsHandler.cpp
  arangod/RestHandler/RestSystemReportHandler.cpp
  arangod/RestHandler/RestSystemReportHandler.h
  js/client/modules/@arangodb/inspector.js
  tests/js/client/server_permissions/test-hardened-rest-apis.js
Labels: 9 Ready to Merge

#10663 Docs: More fixes for write concern
  Documentation/DocuBlocks/Rest/Administration/get_admin_metrics.md
  Documentation/DocuBlocks/Rest/Administration/get_api_cluster_endpoints.md
  Documentation/DocuBlocks/Rest/Analyzers/delete_api_analyzer.md
  Documentation/DocuBlocks/Rest/Analyzers/get_api_analyzer.md
  Documentation/DocuBlocks/Rest/Analyzers/get_api_analyzers.md
  Documentation/DocuBlocks/Rest/Analyzers/post_api_analyzer.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_download.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_upload.md
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Database/get_api_database_current.md
  Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
  Documentation/DocuBlocks/Rest/Graph/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
  Documentation/DocuBlocks/collectionProperties.md
  Documentation/DocuBlocks/serverSSLProtocol.md
  Documentation/Scripts/codeBlockReader.py
  README_maintainers.md
  arangod/MMFiles/MMFilesCompactionFeature.cpp
Labels: 3 Documentation, 9 Ready to Merge

#10959 [3.6] Bug fix/issue 10896
  3rdParty/velocypack/include/velocypack/Iterator.h
  CHANGELOG
  arangod/Aql/CollectNode.cpp
  tests/Aql/QueryHelper.cpp
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
  tests/js/server/aql/aql-optimizer-collect-into.js
  tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Labels: 1 Bug, 3 AQL, 9 Ready to Merge

#10933 Bug fix 3.6/statistics short parameter only use ints
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/dashboardView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.5d3ced01c47ef818526dd96fd7f726a0.js
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.5d3ced01c47ef818526dd96fd7f726a0.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.872b3e80f4ea8ca44ac980f8e075b7c9.js
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.872b3e80f4ea8ca44ac980f8e075b7c9.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/1.56c5474e.chunk.css.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/1.56c5474e.chunk.css.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.4567622b.chunk.css
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.4567622b.chunk.css.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.4567622b.chunk.css.map
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.4567622b.chunk.css.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.60461391.chunk.css
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.60461391.chunk.css.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.60461391.chunk.css.map
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.60461391.chunk.css.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.15ce0f54.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.15ce0f54.chunk.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.15ce0f54.chunk.js.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.a1b17cee.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.a1b17cee.chunk.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/1.a1b17cee.chunk.js.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1f695169.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1f695169.chunk.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1f695169.chunk.js.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.45e12c80.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.45e12c80.chunk.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.45e12c80.chunk.js.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/runtime~main.54148531.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/runtime~main.54148531.js.map.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.1edaa6e5.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.634f53eb.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.88f29ea5.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.f1d811cd.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.7f57c4c0.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.ad97d029.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.38861cba.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.3d3a5358.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-edition-optimized.1a30ee99.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb.90160575.eot.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/cpu.be6a1f63.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.1dc35d25.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.d7c63908.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/jsoneditor-icons.d961fdfa.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/ram.75050f7e.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/requests.fd159a14.svg.gz
Labels: 9 Ready to Merge

#10938 fix spurious "substr index out of bounds" errors
  3rdParty/velocypack/src/StringRef.cpp
  CHANGELOG
Labels: 9 Ready to Merge

#10939 fix spurious "substr index out of bounds" VelocyPack errors
  3rdParty/velocypack/include/velocypack/StringRef.h
  CHANGELOG
Labels: 9 Ready to Merge

#10795 [3.5] supervision maintenance unttled
  CHANGELOG
  arangod/Agency/AgencyStrings.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  js/actions/api-cluster.js
Labels: 1 Bug, 3.5.5, 9 WIP

#10963 Changelog: Fix issue number
  CHANGELOG
Labels: 9 Ready to Merge

#10969 Bug fix/js cleanup
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/versionCheck.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/common/modules/@arangodb/common.js
Labels: 9 Ready to Merge

#10964 Fix issue #10949
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  tests/js/server/aql/aql-graph-k-shortest-path-0-weight-regression.js
Labels: 1 Bug

#10979 add new test suite to blacklist
  UnitTests/OskarTestSuitesBlackList
Labels: 9 Ready to Merge

#10982 blacklist new test suite
  UnitTests/OskarTestSuitesBlackList
Labels: 9 Ready to Merge

#10981 blacklist new test suite
  UnitTests/OskarTestSuitesBlackList
Labels: 9 Ready to Merge

#10968 include collections "_queues" and "_jobs" in dumps taken by arangodump
  CHANGELOG
  arangosh/Dump/DumpFeature.cpp
  tests/js/server/dump/dump-rocksdb-cluster.js
  tests/js/server/dump/dump-rocksdb.js
  tests/js/server/dump/dump-setup-cluster.js
  tests/js/server/dump/dump-setup.js
Labels: 9 Ready to Merge

#10958 Add audit log events for hotbackup.
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  arangod/StorageEngine/HotBackup.cpp
  arangod/Utils/Events.cpp
  arangod/Utils/Events.h
  lib/Logger/LogTopic.cpp
Labels: 9 Ready to Merge

#10989 fix spurious test failure re "deallocated1"
  tests/IResearch/IResearchFeature-test.cpp
Labels: 9 Ready to Merge

#10995 Make active failover test more stable.
  tests/js/client/active-failover/basic.js
  tests/js/client/active-failover/readonly.js
Labels: 9 Ready to Merge

#10996 remove some now-unused internal APIs
  CHANGELOG
  arangod/CMakeLists.txt
  arangod/Cluster/v8-cluster.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/RestHandler/RestAqlReloadHandler.cpp
  arangod/RestHandler/RestAqlReloadHandler.h
  js/client/bootstrap/modules/internal.js
  js/server/modules/@arangodb/foxx/manager.js
Labels: 9 Ready to Merge

#10997 added load-balancing support for several query-related APIs
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryList.h
  arangod/CMakeLists.txt
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestExplainHandler.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestQueryHandler.h
  arangod/RestHandler/RestRedirectHandler.cpp
  arangod/VocBase/Methods/Queries.cpp
  arangod/VocBase/Methods/Queries.h
  tests/js/client/load-balancing/load-balancing-queries-noauth-cluster.js
Labels: 9 Ready to Merge

#11012 Sort shard name lists numerically.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingInfo.h
Labels: 1 Bug

#11013 Port numerical sorting of shard lists from devel.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingInfo.h
Labels: 1 Bug

#11018 Fix collection creation with distributeShardsLike.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingInfo.h
Labels: 1 Bug

#10980 blacklist new test suite
  UnitTests/OskarTestSuitesBlackList
Labels: 9 Ready to Merge

#10998 Bug fix 3.6/include jobs and queues collections in dump
  CHANGELOG
  arangosh/Dump/DumpFeature.cpp
  tests/js/server/dump/dump-rocksdb-cluster.js
  tests/js/server/dump/dump-rocksdb.js
  tests/js/server/dump/dump-setup-cluster.js
  tests/js/server/dump/dump-setup.js
Labels: 9 Ready to Merge

#10992 fix undefined pointer
  arangod/Aql/ExecutionBlockImpl.cpp
Labels: 9 Ready to Merge

#11000 Bug fix 3.6/k shortest paths kaputt
  CHANGELOG
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  tests/js/server/aql/aql-graph-k-shortest-path-0-weight-regression.js
Labels: 1 Bug, 9 Ready to Merge

#10934 Bug fix 3.5/statistics short parameter only use ints
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/views/dashboardView.js
Labels: 9 Ready to Merge

#10936 Bug fix 3.4/statistics short parameter only use ints
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js
  js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js.gz
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html
  js/apps/system/_admin/aardvark/APP/frontend/build/index-min.html.gz
  js/apps/system/_admin/aardvark/APP/frontend/js/views/dashboardView.js
Labels: 9 Ready to Merge

#8803 Query helper should support options
  CHANGELOG
  js/common/modules/@arangodb/common.js
  tests/js/common/shell/01_shell-database.js
Labels: 1 Feature, 3 Foxx, 3 JS API

#10942 [3.5] Fix scoping error when COLLECT is used in a subquery
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-collect-subquery-scope-regression.js
Labels: 3.5.5, 9 Ready to Merge

#11001 Bug fix 3.5/k shortest paths kaputt
  CHANGELOG
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  tests/js/server/aql/aql-graph-k-shortest-path-0-weight-regression.js
Labels: 1 Bug, 9 Ready to Merge

#10943 [3.4] Fix scoping error when COLLECT is used in a subquery
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-collect-subquery-scope-regression.js
Labels: 9 Ready to Merge

#10528 test case for splice-subquery and single shard db
  tests/js/server/aql/aql-subquery.js
Labels: 9 Ready to Merge

#10993 [3.6] cleanout server preconditions plan version unchanged for start
  CHANGELOG
  arangod/Agency/CleanOutServer.cpp
  tests/Agency/CleanOutServerTest.json
Labels: 1 Bug

#6873 Feature/server side system report
  CHANGELOG
  arangod/Agency/AgencyStrings.h
  arangod/Aql/ResourceUsage.h
  arangod/CMakeLists.txt
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/RestHandler/RestMetricsHandler.cpp
  arangod/RestHandler/RestSystemReportHandler.cpp
  arangod/RestHandler/RestSystemReportHandler.h
  js/client/modules/@arangodb/inspector.js
  tests/js/client/server_permissions/test-hardened-rest-apis.js
Labels: 2 - Working, 9 WIP, Team Clifton

#10799 [3.6] supervision maintenance unttled
  CHANGELOG
  arangod/Agency/AgencyStrings.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  js/actions/api-cluster.js
Labels: 1 Bug

#11033 Fix uninitialized value _requestTimeout in V8ClientConnection.
  arangosh/Shell/V8ClientConnection.cpp
Labels: 1 Bug

#11020 Feature/aql subquery execution block impl execute implementation sorted collect
  arangod/Aql/AqlCall.h
  arangod/Aql/AqlItemBlockInputRange.cpp
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
  arangod/Aql/SortedCollectExecutor.cpp
  arangod/Aql/SortedCollectExecutor.h
  tests/Aql/ExecutorTestHelper.h
  tests/Aql/SortedCollectExecutorTest.cpp
Labels: 9 WIP

#11003 [3.6] create collections aware of server cleaning
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Store.cpp
  arangod/Cluster/ClusterInfo.cpp
  tests/js/client/agency/agency-test.js
Labels: 1 Bug

#11009 [3.5] create collections aware of server cleaning
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Store.cpp
  arangod/Cluster/ClusterInfo.cpp
  tests/js/client/agency/agency-test.js
Labels: 1 Bug

#11016 [3.5] servers only to start cleaning out, when plan version unchanged
  CHANGELOG
  arangod/Agency/CleanOutServer.cpp
  tests/Agency/CleanOutServerTest.json
Labels: 1 Bug

#10745 [3.6] stop single host agency from logging too early
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/AgentInterface.h
Labels: 1 Bug, Team Clifton

#10744 [devel] single host agency can be logging too early
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/AgentInterface.h
  arangod/Agency/Node.cpp
  arangod/Agency/State.cpp
Labels: 1 Bug, Team Clifton
