Repository arangodb/arangodb, pull requests merged in 2020-12, with the labels that each got.

#13088 provide a cross-database list of current/slow queries
  CHANGELOG
  Documentation/DocuBlocks/Rest/AQL/DeleteApiQueryKill.md
  Documentation/DocuBlocks/Rest/AQL/DeleteApiQuerySlow.md
  Documentation/DocuBlocks/Rest/AQL/GetApiQueryCurrent.md
  Documentation/DocuBlocks/Rest/AQL/GetApiQuerySlow.md
  arangod/Aql/QueryList.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestQueryHandler.h
  arangod/V8Server/v8-vocbase.cpp
  arangod/VocBase/Methods/Queries.cpp
  arangod/VocBase/Methods/Queries.h
  js/client/modules/@arangodb/aql/queries.js
  js/server/modules/@arangodb/aql/queries.js
  tests/js/client/server_permissions/test-queries-all-databases.js
  tests/js/client/shell/shell-queries-all-databases.js
Labels: 9 Ready to Merge

#13127 Bug fix 3.7/fix endpoints status reporting 2
  js/client/modules/@arangodb/testsuites/endpoints.js
Labels: 3 - Testing

#13126 Bug fix 3.7/arangobench
  arangosh/Benchmark/BenchFeature.cpp
  arangosh/Benchmark/BenchFeature.h
  arangosh/Benchmark/BenchmarkThread.h
Labels: 3 - Testing

#13129 Fix issue with ApplicationFeature registration and startup order
  lib/ApplicationFeatures/ApplicationFeature.cpp
  lib/ApplicationFeatures/ApplicationFeature.h
  lib/ApplicationFeatures/ApplicationServer.cpp
  lib/ApplicationFeatures/ApplicationServer.h
Labels: 9 Ready to Merge

#13133 Bug fix 3.6/arangobench
  arangosh/Benchmark/BenchFeature.cpp
  arangosh/Benchmark/BenchFeature.h
  arangosh/Benchmark/BenchmarkCounter.h
  arangosh/Benchmark/BenchmarkOperation.h
  arangosh/Benchmark/BenchmarkThread.h
  arangosh/Benchmark/arangobench.cpp
  arangosh/Benchmark/test-cases.h
  js/client/modules/@arangodb/testsuites/arangobench.js
Labels: 3 - Testing

#13132 Bug fix /arangobench (#13126)
  arangosh/Benchmark/BenchFeature.cpp
  arangosh/Benchmark/BenchFeature.h
  arangosh/Benchmark/BenchmarkThread.h
Labels: 3 - Testing

#13028 [3.6] smartgraph view no duplicate data
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/IResearch/IResearchViewCoordinator.cpp
Labels: 3 ArangoSearch, 3 Graph

#13025 Add deadlock test for hotbackup
  arangod/V8Server/v8-actions.cpp
  js/server/bootstrap/modules/internal.js
  tests/js/client/shell/shell-deadlock-trx-hotbackup-cluster.js
Labels: 3 - Testing, 3 ImportExport

#13123 Feature 3.6/reimplement coordshort
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/clusterView.js
  js/apps/system/_admin/aardvark/APP/statistics.js
  js/server/modules/@arangodb/statistics-helper.js
  tests/js/server/shell/shell-statistics-helper.js
Labels: 9 Ready to Merge

#13064 Docs: Check protocol(), throw if not http/1.1, don't filter common headers
  js/client/bootstrap/modules/internal.js
  tests/js/server/dump/dump-rocksdb-cluster.js
Labels: 3 API, 3 Documentation, 3 JS API

#13135 fix agency poll api redirects
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Cluster/AgencyCache.cpp
Labels: 1 Bug, DO_NOT_MERGE

#13142 Bug fix/reduce allocations in hashed collect executor
  arangod/Aql/Aggregator.cpp
  arangod/Aql/Aggregator.h
  arangod/Aql/HashedCollectExecutor.cpp
  arangod/Aql/HashedCollectExecutor.h
  arangod/Aql/WindowExecutor.cpp
Labels: 9 Ready to Merge

#13151 Add kill-check during early pruning
  CHANGELOG
  arangod/Aql/DocumentProducingHelper.cpp
Labels: 1 Bug

#13140 update velocypack library
  3rdParty/velocypack/include/velocypack/Buffer.h
  3rdParty/velocypack/include/velocypack/Builder.h
  3rdParty/velocypack/include/velocypack/Exception.h
  3rdParty/velocypack/include/velocypack/HashedStringRef.h
  3rdParty/velocypack/include/velocypack/Slice.h
  3rdParty/velocypack/include/velocypack/SmallVector.h
  3rdParty/velocypack/include/velocypack/StringRef.h
  3rdParty/velocypack/include/velocypack/Value.h
  3rdParty/velocypack/include/velocypack/velocypack-version-number.h
  3rdParty/velocypack/src/Builder.cpp
  3rdParty/velocypack/src/Compare.cpp
  3rdParty/velocypack/src/Exception.cpp
  3rdParty/velocypack/src/HashedStringRef.cpp
  3rdParty/velocypack/src/Parser.cpp
  3rdParty/velocypack/src/Slice.cpp
  3rdParty/velocypack/src/StringRef.cpp
  3rdParty/velocypack/src/Value.cpp
Labels: 9 Ready to Merge

#13186 bug-fix-3.7/internal-issue-#775
  3rdParty/iresearch/core/utils/async_utils.cpp
Labels: 3 ArangoSearch, ASan

#13119 Fix AQL cost estimate for spliced subqueries
  CHANGELOG
  arangod/Aql/CostEstimate.cpp
  arangod/Aql/CostEstimate.h
  arangod/Aql/SubqueryEndExecutionNode.cpp
  arangod/Aql/SubqueryStartExecutionNode.cpp
  tests/js/server/aql/aql-optimizer-costs.js
Labels: 1 Bug

#13167 Fix introduced/deprecated in versions for --arangosearch.*threads* startup option
  arangod/IResearch/IResearchFeature.cpp
Labels: 1 Bug, 3 Documentation, 3 Search, 9 Ready to Merge

#12738 now escaping the result of a foxx services setup script
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/applicationDetailView.js
Labels: 3 UI

#12988 Bug fix/smartgraph view no duplicate data
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  tests/js/server/dump/dump-cluster.js
Labels: 3 ArangoSearch, 3 Graph

#12796 Cleanup of EnumerateList produceRows
  arangod/Aql/EnumerateListExecutor.cpp
Labels: 9 Ready to Merge

#13196 Fixed AR-113 and added regression tests
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/Cluster/RestClusterHandler.cpp
  arangod/GeoIndex/Index.cpp
  tests/js/server/aql/aql-optimizer-geoindex.js
Labels: 1 Bug, 3 AQL, 3 Geo, 3 Optimizer

#13097 [3.7] cleanup change set map
  CHANGELOG
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/Maintenance.cpp
Labels: 3 Cluster

#13181 [3.7] Fix a potential nullptr access in AsyncAgencyComm
  CHANGELOG
  arangod/Agency/AsyncAgencyComm.cpp
Labels: 9 Ready to Merge

#13209 Fix introduced/deprecated in versions for --arangosearch.*threads* startup option
  arangod/IResearch/IResearchFeature.cpp
Labels: 1 Bug, 3 Documentation, 3 Search

#13178 two small unrelated fixes
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  lib/Basics/NumberUtils.h
Labels: 9 Ready to Merge

#13065 Docs: Check protocol(), throw if not http/1.1, don't filter common headers
  js/client/bootstrap/modules/internal.js
Labels: 3 API, 3 Documentation, 3 JS API

#12987 Feature 3.7/add locking instrumentation
  CHANGELOG
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/ClusterEngine/ClusterTransactionState.h
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/Sharding/ShardingInfo.cpp
  arangod/Statistics/ServerStatistics.cpp
  arangod/Statistics/ServerStatistics.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  arangod/Transaction/Methods.cpp
  js/client/modules/@arangodb/arango-transaction.js
  js/client/modules/@arangodb/testsuites/aql.js
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  lib/Rest/GeneralResponse.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/Transaction/Manager-test.cpp
  tests/js/client/shell/shell-collection-counts-cluster.js
  tests/js/client/shell/shell-transaction-dropped-followers-cluster.js
  tests/js/client/shell/shell-transaction-intermediate-commit-cluster.js
  tests/js/common/shell/shell-aqlfunctions.js
  tests/js/common/shell/shell-cluster-collection.js
Labels: 9 Ready to Merge

#13130 [3.7] Fix issue with ApplicationFeature registration and startup order
  lib/ApplicationFeatures/ApplicationFeature.cpp
  lib/ApplicationFeatures/ApplicationFeature.h
  lib/ApplicationFeatures/ApplicationServer.cpp
  lib/ApplicationFeatures/ApplicationServer.h
Labels: 9 Ready to Merge

#13081 add more metrics for AQL query execution times
  CHANGELOG
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
Labels: 3 AQL

#13170 tell users they must not use arangosh to invoke these (#13013)
  arangosh/Shell/V8ShellFeature.cpp
  js/client/modules/@arangodb/crash-utils.js
  lib/CMakeLists.txt
  lib/Utilities/IsArangoExecutable.cpp
  lib/Utilities/IsArangoExecutable.h
Labels: 3 Arangosh

#13160 fix make directory windows error handling (#13157)
  CHANGELOG
  lib/Basics/files.cpp
  lib/Basics/operating-system.h
Labels: 4 Windows, 9 Ready to Merge

#13152 [3.7] Add kill-check during early pruning
  CHANGELOG
  arangod/Aql/DocumentProducingHelper.cpp
Labels: 1 Bug, 9 Ready to Merge

#13121 [3.7] Fix AQL cost estimate for spliced subqueries
  CHANGELOG
  arangod/Aql/CostEstimate.cpp
  arangod/Aql/CostEstimate.h
  arangod/Aql/SubqueryEndExecutionNode.cpp
  arangod/Aql/SubqueryStartExecutionNode.cpp
  tests/js/server/aql/aql-optimizer-costs.js
Labels: 1 Bug

#13190 Ignore not-yet created databases on other coordinators
  CHANGELOG
  arangod/VocBase/Methods/Queries.cpp
Labels: 3 Cluster

#13118 Reimplement coordshort request handler.
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/clusterView.js
  js/apps/system/_admin/aardvark/APP/statistics.js
  js/server/modules/@arangodb/statistics-helper.js
  tests/js/server/shell/shell-statistics-helper.js
Labels: 3 Cluster, 9 Ready to Merge

#13221 more effective test for parallel traversals
  arangod/Aql/MutexExecutor.cpp
  arangod/V8Server/v8-actions.cpp
Labels: 3 Graph

#13009 [3.7] Pregel improvements
  CHANGELOG
  arangod/IResearch/IResearchLink.h
  arangod/Pregel/Algos/AsyncSCC.cpp
  arangod/Pregel/Algos/ConnectedComponents.cpp
  arangod/Pregel/Algos/DMID/DMID.cpp
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.cpp
  arangod/Pregel/Algos/HITS.cpp
  arangod/Pregel/Algos/LabelPropagation.cpp
  arangod/Pregel/Algos/PageRank.cpp
  arangod/Pregel/Algos/SCC.cpp
  arangod/Pregel/Algos/SLPA.cpp
  arangod/Pregel/Algos/SSSP.cpp
  arangod/Pregel/Algos/ShortestPath.cpp
  arangod/Pregel/Algos/WCC.cpp
  arangod/Pregel/CommonFormats.h
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  arangod/Pregel/Graph.h
  arangod/Pregel/GraphFormat.h
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/GraphStore.h
  arangod/Pregel/IndexHelpers.cpp
  arangod/Pregel/IndexHelpers.h
  arangod/Pregel/Iterators.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/OutgoingCache.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/TypedBuffer.h
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/VertexComputation.h
  arangod/Pregel/Worker.cpp
  arangod/Pregel/WorkerConfig.cpp
  arangod/Pregel/WorkerConfig.h
  arangod/RestHandler/RestControlPregelHandler.cpp
  arangod/RestHandler/RestPregelHandler.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/Methods/Collections.cpp
  js/client/modules/@arangodb/pregel.js
  js/server/modules/@arangodb/pregel.js
  lib/Basics/LocalTaskQueue.cpp
  lib/Basics/LocalTaskQueue.h
  tests/Mocks/IResearchLinkMock.h
  tests/Mocks/StorageEngineMock.cpp
  tests/js/common/shell/shell-pregel.js
Labels: 3 Pregel, 9 Ready to Merge

#13203 Fix cluster-internal replication of documents with special keys
  CHANGELOG
  arangod/Transaction/Methods.cpp
  lib/Basics/StringUtils.cpp
  lib/Basics/StringUtils.h
  tests/Basics/StringUtilsTest.cpp
Labels: 9 Ready to Merge

#13229 Feature 3.7/more agency metrics
  CHANGELOG
  arangod/Agency/State.cpp
  arangod/Agency/State.h
  arangod/Agency/Store.h
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  arangod/Cluster/AgencyCallbackRegistry.cpp
  arangod/Cluster/AgencyCallbackRegistry.h
  arangod/RestServer/MetricsFeature.cpp
Labels: 9 Ready to Merge

#13234 work around a potential issue found in `restart` test suite
  tests/js/client/restart/test-foxx-selfheal-cluster.js
Labels: 3 - Testing

#13228 fix mismatching compaction, log in agency startup
  CHANGELOG
  arangod/Agency/State.cpp
  arangod/Agency/State.h
Labels: 1 Bug

#13252 collection.checksum() supported in cluster now
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_checksum.md
  Documentation/DocuBlocks/collectionChecksum.md
Labels: 1 Feature, 3 Documentation

#13243 Bug fix 3.7/ssl sni
  3rdParty/fuerte/src/AsioSockets.h
  CHANGELOG
Labels: 3 Arangosh, 3 SSL

#13249 Features 3.7/error levels
  ERROR_LEVELS.md
Labels: 3 Build

#13240 [3.7] Fixed AR-113 and added regression tests
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/Cluster/RestClusterHandler.cpp
  arangod/GeoIndex/Index.cpp
  tests/js/server/aql/aql-optimizer-geoindex.js
Labels: 3 AQL, 3 Geo

#13270 3.5: backport windows python detection
  cmake/FindPythonInterp.cmake
Labels: 3 Build

#13241 [3.5] Fixed AR-113 and added regression tests
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/GeoIndex/Index.cpp
  tests/js/server/aql/aql-optimizer-geoindex.js
Labels: 3 AQL, 3 Geo, 3 Optimizer

#13276 added agency-restart tests to the blocklist
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#13266 Bug fix 3.7/internal issue #772
  3rdParty/iresearch/cmake/FindBoostLocal.cmake
  3rdParty/iresearch/core/analysis/text_token_normalizing_stream.cpp
  3rdParty/iresearch/core/analysis/text_token_stemming_stream.cpp
  3rdParty/iresearch/core/analysis/text_token_stream.cpp
  3rdParty/iresearch/core/formats/formats_10.cpp
  3rdParty/iresearch/core/formats/formats_burst_trie.cpp
  3rdParty/iresearch/core/index/heap_iterator.hpp
  3rdParty/iresearch/core/index/segment_reader.cpp
  3rdParty/iresearch/core/index/segment_writer.cpp
  3rdParty/iresearch/core/search/all_iterator.hpp
  3rdParty/iresearch/core/search/bitset_doc_iterator.cpp
  3rdParty/iresearch/core/search/bitset_doc_iterator.hpp
  3rdParty/iresearch/core/search/limited_sample_collector.hpp
  3rdParty/iresearch/core/search/multiterm_query.cpp
  3rdParty/iresearch/core/search/multiterm_query.hpp
  3rdParty/iresearch/core/search/ngram_similarity_filter.cpp
  3rdParty/iresearch/core/search/phrase_filter.cpp
  3rdParty/iresearch/core/store/data_input.cpp
  3rdParty/iresearch/core/store/data_input.hpp
  3rdParty/iresearch/core/store/data_output.cpp
  3rdParty/iresearch/core/store/data_output.hpp
  3rdParty/iresearch/core/store/fs_directory.cpp
  3rdParty/iresearch/core/utils/bitset.hpp
  3rdParty/iresearch/core/utils/encryption.cpp
  3rdParty/iresearch/core/utils/encryption.hpp
  3rdParty/iresearch/core/utils/locale_utils.cpp
  3rdParty/iresearch/core/utils/thread_utils.cpp
  3rdParty/iresearch/external/snowball/CMakeLists.txt
  3rdParty/iresearch/tests/index/index_tests.cpp
  3rdParty/iresearch/tests/iql/query_builder_test.cpp
  3rdParty/iresearch/tests/resources/simple_two_column.csv
  3rdParty/iresearch/tests/search/bitset_doc_iterator_test.cpp
  3rdParty/iresearch/tests/search/filter_test_case_base.hpp
  3rdParty/iresearch/tests/search/index_reader_test.cpp
  3rdParty/iresearch/tests/store/directory_test_case.cpp
  3rdParty/iresearch/tests/utils/encryption_test.cpp
  3rdParty/iresearch/tests/utils/locale_utils_tests.cpp
  3rdParty/iresearch/utils/index-put.cpp
  3rdParty/snowball/algorithms/yiddish.sbl
  CHANGELOG
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/OptimizerRules.cpp
  js/common/modules/@arangodb/aql/explainer.js
  tests/IResearch/CMakeLists.txt
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchViewCountApproximate-test.cpp
  tests/IResearch/IResearchViewNode-test.cpp
  tests/IResearch/common.cpp
  tests/js/server/aql/aql-arangosearch-count-optimization.js
  tests/js/server/aql/aql-optimizer-rule-collect-in-cluster.js
Labels: 3 ArangoSearch, 4 Windows

#13261 Add query execution time and query id to audit log query messages.
  CHANGELOG
  arangod/Aql/QueryList.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestCursorHandler.h
  arangod/Utils/Events.cpp
  arangod/Utils/Events.h
  arangod/V8Server/v8-vocbase.cpp
Labels: 9 Ready to Merge

#13263 Added "startupTime", "computationTime" and "storageTime" to Pregel result statistics
  CHANGELOG
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  tests/js/common/shell/shell-pregel.js
Labels: 9 Ready to Merge

#13255 do not kill thread in case of exception
  arangod/GeneralServer/GeneralServer.cpp
  arangod/GeoIndex/Index.cpp
Labels: 3 SSL

#13269 do not kill thread in case of exception
  arangod/GeneralServer/IoContext.cpp
Labels: 3 SSL

#13279 Prevent write during RocksDB recovery
  arangod/RocksDBEngine/RocksDBUpgrade.cpp
Labels: 9 Ready to Merge

#13274 add agency-restart tests to the blocklist
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing, 9 Ready to Merge

#13277 fix reloading "clientId" values from persistence
  CHANGELOG
  arangod/Agency/State.cpp
Labels: 9 Ready to Merge

#13280 Prevent write during RocksDB recovery
  CHANGELOG
  arangod/RocksDBEngine/RocksDBUpgrade.cpp
Labels: 3 RocksDB, 9 Ready to Merge

#13284 Remove HTTP "Connection" header when forwarding requests
  CHANGELOG
  arangod/GeneralServer/RestHandler.cpp
  tests/js/client/load-balancing/response-header-noauth-cluster.js
Labels: 3 Cluster, 9 Ready to Merge

#13291 Make internal ClusterInfo::getPlan() wait for initial plan load from agency
  CHANGELOG
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/DBServerAgencySync.cpp
  tests/Mocks/Servers.cpp
Labels: 3 Cluster

#13122 [3.6] Fix AQL cost estimate for spliced subqueries
  CHANGELOG
  arangod/Aql/CostEstimate.cpp
  arangod/Aql/CostEstimate.h
  arangod/Aql/SubqueryEndExecutionNode.cpp
  arangod/Aql/SubqueryStartExecutionNode.cpp
  tests/js/server/aql/aql-optimizer-costs.js
Labels: 1 Bug

#13139 Less dropped followers
  CHANGELOG
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/ClusterEngine/ClusterTransactionState.h
  arangod/MMFiles/MMFilesTransactionState.cpp
  arangod/MMFiles/MMFilesTransactionState.h
  arangod/Replication/ReplicationTransaction.h
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/Statistics/ServerStatistics.cpp
  arangod/Statistics/ServerStatistics.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Options.cpp
  arangod/Transaction/Options.h
  js/client/modules/@arangodb/arango-transaction.js
  js/client/modules/@arangodb/testsuites/aql.js
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  lib/Rest/GeneralResponse.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/Transaction/Manager-test.cpp
  tests/js/client/shell/shell-collection-counts-cluster-rocksdb.js
  tests/js/client/shell/shell-transaction-dropped-followers-cluster-rocksdb.js
  tests/js/client/shell/shell-transaction-intermediate-commit-cluster-rocksdb.js
  tests/js/common/shell/shell-aqlfunctions.js
  tests/js/common/shell/shell-cluster-collection.js
Labels: 3 Cluster

#13153 [3.6] Add kill-check during early pruning
  CHANGELOG
  arangod/Aql/DocumentProducingHelper.cpp
Labels: 1 Bug, 9 Ready to Merge

#13161 fix make directory windows error handling (#13157)
  CHANGELOG
  lib/Basics/files.cpp
  lib/Basics/operating-system.h
Labels: 4 Windows, 9 Ready to Merge

#13162 fix assertion failure when database is specified without URL path
  lib/Rest/HttpRequest.cpp
Labels: 9 Ready to Merge

#13171 3.6: tell users they must not use arangosh to invoke these (#13013)
  arangosh/Shell/V8ShellFeature.cpp
  lib/CMakeLists.txt
  lib/Utilities/IsArangoExecutable.cpp
  lib/Utilities/IsArangoExecutable.h
Labels: 9 Ready to Merge

#13179 two small unrelated fixes
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  lib/Basics/NumberUtils.h
Labels: 9 Ready to Merge

#13201 change "term" from double to integer value
  CHANGELOG
  arangod/Agency/State.cpp
Labels: 9 Ready to Merge

#13204 Fix cluster-internal replication of documents with special keys
  CHANGELOG
  arangod/Transaction/Methods.cpp
  lib/Basics/StringUtils.cpp
  lib/Basics/StringUtils.h
  tests/Basics/StringUtilsTest.cpp
Labels: 9 Ready to Merge

#13216 fixed jemalloc heap profiler build
  3rdParty/CMakeLists.txt
  CMakeLists.txt
Labels: 3 - Testing, 3 Build

#13231 Bug fix 3.6/ssl sni
  3rdParty/fuerte/src/AsioSockets.h
  CHANGELOG
Labels: 3 SSL

#13235 add more agency metrics
  CHANGELOG
  arangod/Agency/State.cpp
  arangod/Agency/State.h
  arangod/Cluster/AgencyCallbackRegistry.cpp
  arangod/Cluster/AgencyCallbackRegistry.h
  arangod/Cluster/ClusterFeature.cpp
Labels: 9 Ready to Merge

#13236 work around a potential issue found in `restart` test suite (#13234)
  tests/js/client/restart/test-foxx-selfheal-cluster.js
Labels: 3 - Testing, 9 Ready to Merge

#13250 added error level description
  ERROR_LEVELS.md
Labels: 3 Build, 3 Documentation

#13242 [3.6] Fixed AR-113 and added regression tests
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/GeoIndex/Index.cpp
  tests/js/server/aql/aql-optimizer-geoindex.js
Labels: 1 Bug, 3 AQL, 3 Geo, 3 Optimizer

#13275 add agency-restart tests to the blocklist
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing, 9 Ready to Merge

#13264 Add query execution time and query id to audit log query messages.
  CHANGELOG
  arangod/Aql/QueryList.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestCursorHandler.h
  arangod/Utils/Events.cpp
  arangod/Utils/Events.h
  arangod/V8Server/v8-vocbase.cpp
Labels: 9 Ready to Merge

#13268 do not kill thread in case of exception
  arangod/GeneralServer/IoContext.cpp
Labels: 3 Cluster

#13278 fix reloading "clientId" values from persistence
  CHANGELOG
  arangod/Agency/State.cpp
Labels: 9 Ready to Merge

#13281 Prevent write during RocksDB recovery
  CHANGELOG
  arangod/RocksDBEngine/RocksDBUpgrade.cpp
Labels: 9 Ready to Merge

#13286 Remove HTTP "Connection" header when forwarding requests
  CHANGELOG
  arangod/GeneralServer/RestHandler.cpp
  tests/js/client/load-balancing/response-header-noauth-cluster.js
Labels: 9 Ready to Merge

#13166 Endless loop on create database rollback
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug, 3 Cluster

#13176 Fix loop.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 3 Cluster

#13309 Stabilize Foxx cleanup test
  tests/js/server/shell/shell-foxx-cleanup-spec.js
Labels: 3 - Testing
