Repository arangodb/arangodb, pull requests merged in 2020-04, with the labels that each got.

#11351 Check MSVC_VERSION instead of CMAKE_GENERATOR
  cmake/custom/ArangoDB_FindOpenSSL_WIN32.cmake
Labels: DO_NOT_MERGE

#11300 Feature/satellite graphs extend graphsuite k shortest path
  js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/aql-graph-traversal-generic-tests.js
Labels: 9 Review Required, 9 WIP

#11355 Fix a bug in server state detection after leader change.
  CHANGELOG
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Supervision.cpp
  tests/Agency/FailedFollowerTest.cpp
Labels: 1 Bug

#11332 Feature/satellite graphs 2 modification creation tests
  arangod/Graph/Graph.cpp
  arangod/Graph/Graph.h
  arangod/Graph/GraphManager.cpp
  arangod/Graph/GraphManager.h
  arangod/Graph/GraphOperations.cpp
  arangod/Graph/GraphOperations.h
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  tests/js/client/http/api-gharial-spec.js
Labels: DO_NOT_MERGE

#11373 Changelog entry for enterprise only bug fix
  CHANGELOG
Labels: 1 Bug, 9 Ready to Merge

#11374 [3.6] Bug fix/fix one shard traversal instantiation
  CHANGELOG
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/KShortestPathsNode.cpp
  arangod/Aql/KShortestPathsNode.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/ShortestPathNode.h
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraversalNode.h
Labels: 1 Bug, 9 Ready to Merge

#11345 GraphNodes now copy the graph when cloned
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/KShortestPathsNode.cpp
  arangod/Aql/KShortestPathsNode.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/ShortestPathNode.h
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraversalNode.h
Labels: 9 Ready to Merge

#11375 Improve behaviour under high load.
  CHANGELOG
  arangod/Aql/SharedQueryState.cpp
Labels: 1 Bug

#11392 Feature 3.6/add authentication test
  tests/js/client/authentication/auth.js
Labels: 9 Ready to Merge

#11393 don't perform unnecessary document lookups in incremental sync
  CHANGELOG
  arangod/RocksDBEngine/RocksDBCollection.cpp
Labels: 9 Ready to Merge

#11399 don't compact after collection truncation
  CHANGELOG
  arangod/RestHandler/RestCollectionHandler.cpp
Labels: 9 Ready to Merge

#11402 don't relay HTTP/1.1 response headers
  CHANGELOG
  arangod/GeneralServer/RestHandler.cpp
  tests/js/client/load-balancing/response-header.js
Labels: 9 Ready to Merge

#11398 don't run compact after collection truncation
  CHANGELOG
  arangod/RestHandler/RestCollectionHandler.cpp
Labels: 9 Ready to Merge

#11403 add tests to make sure that HTTP/1.1 headers are not relayed
  tests/js/client/load-balancing/response-header.js
Labels: 9 Ready to Merge

#10678 shellcheck and name limitations
  utils/jslint.sh
Labels: 3 - Testing, 9 Review Required

#11407 Improve AQL behaviour under high load.
  CHANGELOG
  arangod/Aql/SharedQueryState.cpp
Labels: 1 Bug

#11410 remove now-unused CursorType
  arangod/Aql/QueryCursor.h
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/Utils/Cursor.h
  arangod/Utils/CursorRepository.cpp
  arangod/Utils/CursorRepository.h
  arangod/V8Server/v8-voccursor.cpp
Labels: 9 Ready to Merge

#11309 Docs: Graph replicationFactor: "satellite" & isSatellite property
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
  Documentation/DocuBlocks/Rest/Graph/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_list_http_examples.md
  Documentation/DocuBlocks/collectionProperties.md
Labels: 3 Documentation

#11334 validation web-ui
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/models/arangoCollectionModel.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/validationView.html
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/validationView.js
Labels: 3 UI, 9 Review Required

#11408 Fix a bug that occurred if a dbserver was unluckily.
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
Labels: 1 Bug

#11426 Fix a maintenance bug.
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
Labels: 1 Bug

#11413 Fix QueryTimeWatcher to check >=, not >
  tests/js/client/http/cluster-metrics-cluster-spec.js
Labels: 9 Ready to Merge

#11412 Force upstream call to be forwarded in NoResultsExecutor
  arangod/Aql/NoResultsExecutor.cpp
Labels: 1 Bug, 9 Ready to Merge

#11421 OpenSSL 1.1.1f for devel
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#11422 OpenSSL 1.1.1f for 3.6
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#11423 OpenSSL 1.1.1f for 3.5
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#11414 [3.6] Exclude IResearch views from subquery splicing
  CHANGELOG
  arangod/Aql/NoResultsExecutor.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-subquery.js
Labels: 1 Bug, 9 Ready to Merge

#11425 Port maintenance bug fix to 3.6.
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
Labels: 1 Bug

#11335 Enable utf-8 string validation.
  3rdParty/velocypack/src/Validator.cpp
  CHANGELOG
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/ReplicationFeature.h
  arangod/Replication/Syncer.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestServer/ServerFeature.cpp
  arangod/RestServer/ServerFeature.h
  lib/Basics/VelocyPackHelper.cpp
  lib/Basics/VelocyPackHelper.h
  lib/Rest/GeneralRequest.h
  lib/Rest/HttpRequest.cpp
  lib/Rest/HttpRequest.h
  lib/Rest/VstRequest.cpp
  tests/rb/HttpInterface/api-document-create-spec.rb
  tests/rb/HttpInterface/api-document-replication-spec.rb
  tests/rb/HttpInterface/api-document-update-spec.rb
Labels: 3 Core, 9 Review Required

#11432 added disjoint smart graphs to ui
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/graphManagementView.html
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
Labels: 9 Review Required

#11411 reduce space waste
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
Labels: 9 Ready to Merge

#11451 Fix for 'docs out of order' error (internal issue #686)
  3rdParty/iresearch/core/index/merge_writer.cpp
  CHANGELOG
Labels: 3 ArangoSearch

#11450 Feature/disjoint smart graphs class is disjoint
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  js/common/bootstrap/errors.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
Labels: 9 Review Required

#11340 Satellite-Graphs / Broken Sorted Gather
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/VocBase/LogicalCollection.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/server/aql/aql-optimizer-rule-decay-unnecessary-sorted-gather-cluster.js
Labels: 1 Bug, 9 Waiting for Jenkins

#11428 Bug fix/traversal estimates
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Graph/BaseOptions.h
  arangod/Graph/ShortestPathOptions.cpp
  arangod/Graph/ShortestPathOptions.h
  arangod/Graph/TraverserOptions.cpp
  arangod/Graph/TraverserOptions.h
Labels: 1 Bug

#11429 Feature/validation various changes
  CHANGELOG
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
  Documentation/DocuBlocks/collectionDatabaseCreate.md
  Documentation/DocuBlocks/collectionProperties.md
  arangod/Aql/Functions.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/Utils/Events.cpp
  arangod/Utils/Events.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Validators.cpp
  arangod/VocBase/Validators.h
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/models/arangoCollectionModel.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/validationView.html
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/validationView.js
  js/client/modules/@arangodb/arango-collection.js
  js/client/modules/@arangodb/arango-database.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/js/common/shell/shell-validation.js
  tests/rb/HttpInterface/api-collection-spec.rb
Labels: 9 Review Required

#11463 MMFiles: Remove (obsolete info from) DocuBlocks
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_figures.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_rotate.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_dump.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_inventory.md
  Documentation/DocuBlocks/Rest/wal/get_admin_wal_properties.md
  Documentation/DocuBlocks/Rest/wal/get_admin_wal_transactions.md
  Documentation/DocuBlocks/Rest/wal/put_admin_wal_flush.md
  Documentation/DocuBlocks/Rest/wal/put_admin_wal_properties.md
  Documentation/DocuBlocks/WalLogfileAllowOversizeEntries.md
  Documentation/DocuBlocks/WalLogfileDirectory.md
  Documentation/DocuBlocks/WalLogfileFlushTimeout.md
  Documentation/DocuBlocks/WalLogfileHistoricLogfiles.md
  Documentation/DocuBlocks/WalLogfileIgnoreLogfileErrors.md
  Documentation/DocuBlocks/WalLogfileIgnoreRecoveryErrors.md
  Documentation/DocuBlocks/WalLogfileReserveLogfiles.md
  Documentation/DocuBlocks/WalLogfileSize.md
  Documentation/DocuBlocks/WalLogfileSlots.md
  Documentation/DocuBlocks/WalLogfileSyncInterval.md
  Documentation/DocuBlocks/WalLogfileThrottling.md
  Documentation/DocuBlocks/collectionFigures.md
  Documentation/DocuBlocks/walFlush.md
  Documentation/DocuBlocks/walPropertiesGet.md
  Documentation/DocuBlocks/walPropertiesSet.md
Labels: 3 Documentation

#11468 issue #11447: expose `--rocksdb.target-file-size-base` and `--rocksdb.target-file-size-multiplier`
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/StorageEngine/RocksDBOptionFeature.cpp
  arangod/StorageEngine/RocksDBOptionFeature.h
Labels: 9 Ready to Merge

#11449 Refactored RegisterPlan.
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ClusterNodes.h
  arangod/Aql/CollectNode.cpp
  arangod/Aql/CollectNode.h
  arangod/Aql/DistributeConsumerNode.cpp
  arangod/Aql/DistributeConsumerNode.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  arangod/Aql/ModificationNodes.cpp
  arangod/Aql/ModificationNodes.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/RegisterPlan.h
  arangod/Aql/SortNode.cpp
  arangod/Aql/SortNode.h
  arangod/Aql/SubqueryEndExecutionNode.cpp
  arangod/Aql/SubqueryEndExecutionNode.h
  arangod/Aql/SubqueryStartExecutionNode.cpp
  arangod/Aql/SubqueryStartExecutionNode.h
  tests/Aql/MockTypedNode.cpp
  tests/Aql/MockTypedNode.h
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-2.js
Labels: 9 Ready to Merge

#11400 initial work for BTS-35
  CHANGELOG
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ClusterNodes.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  lib/Containers/SmallUnorderedMap.h
Labels: 9 Ready to Merge

#11472 Bug fix/heavy nested subquery nr2
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/LimitExecutor.cpp
  tests/js/server/aql/aql-shadowrow-block-return-regression.js
Labels: 1 Bug

#11272 Feature/satellite graphs
  CHANGELOG
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/EnumerateCollectionExecutor.h
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionEngine.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexNode.cpp
  arangod/Aql/KShortestPathsNode.cpp
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/CMakeLists.txt
  arangod/Cluster/ServerDefaults.cpp
  arangod/Cluster/ServerDefaults.h
  arangod/Graph/Graph.cpp
  arangod/Graph/Graph.h
  arangod/Graph/GraphManager.cpp
  arangod/Graph/GraphManager.h
  arangod/Graph/GraphOperations.cpp
  arangod/Graph/GraphOperations.h
  arangod/Sharding/ShardingInfo.cpp
  arangod/VocBase/LogicalCollection.h
  js/common/bootstrap/errors.js
  js/common/modules/@arangodb/aql/explainer.js
  js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/aql-graph-traversal-generic-tests.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  tests/js/client/http/api-gharial-spec.js
  tests/js/server/aql/aql-optimizer-rule-decay-unnecessary-sorted-gather-cluster.js
  tests/js/server/dump/dump-cluster.js
  tests/js/server/dump/dump-setup-cluster.js
Labels: DO_NOT_MERGE

#11476 Enable GCC 9.3.0
  VERSIONS
Labels: 3 Build

#11479 added disjoint smart graphs to traversal test suite
  js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
Labels: 9 WIP

#11483 fix typos
  CHANGELOG
Labels: 9 Ready to Merge

#11487 fix example graph creation with `--cluster.min-replication-factor` set
  CHANGELOG
  arangod/Graph/Graph.cpp
  arangod/Graph/Graph.h
  arangod/Graph/GraphManager.cpp
  js/common/modules/@arangodb/general-graph-common.js
  tests/js/client/server_permissions/test-sharding-restrictions-cluster.js
Labels: 3 Cluster, 3 Graph, 9 Ready to Merge

#11464 Docs: Add missing log topics
  Documentation/DocuBlocks/Rest/Administration/get_admin_modules_flush.md
Labels: 3 Documentation, 9 Ready to Merge

#11470 Feature 3.6/aql micro optimizations
  arangod/Aql/AqlValue.cpp
  arangod/Aql/SubqueryEndExecutor.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
Labels: 9 Ready to Merge

#11465 Docs: Add missing log levels
  Documentation/DocuBlocks/Rest/Administration/get_admin_modules_flush.md
Labels: 3 Documentation, 9 Ready to Merge

#11486 Fix uninitialized value in HttpRequest
  3rdParty/rocksdb/6.8/db/wal_manager.cc.orig
  3rdParty/rocksdb/6.8/db/wal_manager.cc.rej
  lib/Rest/HttpRequest.cpp
  lib/Rest/HttpRequest.h
Labels: 9 Ready to Merge

#11496 Update OpenSSL to 1.1.1g
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#11495 Update OpenSSL to 1.1.1g
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#11494 Update OpenSSL to 1.1.1g
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#11466 Docs: Add missing log levels
  Documentation/DocuBlocks/Rest/Administration/get_admin_modules_flush.md
Labels: 3 Documentation, 9 Ready to Merge

#11497 Feature/cleanup collect node registers
  arangod/Aql/CollectNode.cpp
  arangod/Aql/CollectNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-keep.js
Labels: 9 Ready to Merge

#11503 Instead of just closing stdin, open "/dev/null"
  lib/Basics/process-utils.cpp
Labels: 9 Ready to Merge

#11511 make the agency tests less sensitive to timing problems
  tests/js/client/agency/agency-test.js
Labels: 9 Ready to Merge

#11509 fix spurious bugs in resilience_move tests
  CHANGELOG
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterEngine.h
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.h
  arangod/StorageEngine/StorageEngine.h
  arangod/VocBase/vocbase.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
Labels: 9 Ready to Merge

#11482 promises must be a multimap to allow emplacements with identical time
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
Labels: 1 Bug

#11515 fix potential undefined behavior
  CHANGELOG
  arangod/ClusterEngine/ClusterRestCollectionHandler.cpp
  arangod/ClusterEngine/ClusterRestCollectionHandler.h
  arangod/MMFiles/MMFilesRestCollectionHandler.cpp
  arangod/MMFiles/MMFilesRestCollectionHandler.h
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestCollectionHandler.h
  arangod/RocksDBEngine/RocksDBRestCollectionHandler.cpp
  arangod/RocksDBEngine/RocksDBRestCollectionHandler.h
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
Labels: 3 Cluster

#11516 Bug fix/fix potential ub in rest collection handler
  CHANGELOG
  arangod/ClusterEngine/ClusterRestCollectionHandler.cpp
  arangod/ClusterEngine/ClusterRestCollectionHandler.h
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestCollectionHandler.h
  arangod/RocksDBEngine/RocksDBRestCollectionHandler.cpp
  arangod/RocksDBEngine/RocksDBRestCollectionHandler.h
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
Labels: 3 Cluster, 3 Driver
