Repository arangodb/arangodb, pull requests merged in 2020-02, with the labels that each got.

#11037 disable warning about `--server.jwt-secret`
  arangod/GeneralServer/AuthenticationFeature.cpp
Labels: 9 Ready to Merge

#11036 attempt to ungreylist test
  tests/rb/HttpInterface/api-async-spec.rb
Labels: 9 Ready to Merge

#10994 Bug fix/deprecate mmfiles engine
  arangod/MMFiles/MMFilesCompactionFeature.cpp
  arangod/MMFiles/MMFilesDatafile.cpp
  arangod/MMFiles/MMFilesEngine.cpp
  arangod/MMFiles/MMFilesLogfileManager.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/StorageEngine/EngineSelectorFeature.cpp
  arangod/StorageEngine/EngineSelectorFeature.h
  etc/arangodb3/arangod.conf.in
  etc/testing/arangod-common.conf
  js/client/modules/@arangodb/testsuites/dfdb.js
  js/client/modules/@arangodb/testsuites/version.js
Labels: 9 Ready to Merge

#10634 Feature/improve ternary operator evaluation
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AstNode.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/server/aql/aql-ternary.js
Labels: 9 Ready to Merge

#11008 create collections aware of server cleaning
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Store.cpp
  arangod/Cluster/ClusterInfo.cpp
  tests/js/client/agency/agency-test.js
Labels: 1 Bug

#11028 Bug fix/tests cleanup
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/EnumerateCollectionExecutor.h
  arangod/Aql/ExecutionNode.cpp
  arangosh/CMakeLists.txt
  js/client/modules/@arangodb/result-processing.js
  js/client/modules/@arangodb/testing.js
  tests/Aql/EnumerateCollectionExecutorTest.cpp
  tests/rb/HttpReplication/api-replication-global-spec.rb
  tests/rb/HttpReplication/api-replication-mmfiles-spec.rb
  tests/rb/HttpReplication/api-replication-rocksdb-spec.rb
Labels: 9 Ready to Merge

#11042 REPLACE_NTH(): add option to start replacing from right
  arangod/Aql/Functions.cpp
  tests/js/server/aql/aql-functions.js
Labels: 1 Feature

#11063 fix log muell
  arangod/Agency/Agent.cpp
Labels: 9 Ready to Merge

#11066 Bug fix/fix msvc2019 build 2017
  3rdParty/V8/CMakeLists.txt
  3rdParty/V8/v7.9.317/src/base/platform/platform-win32.cc
  3rdParty/V8/v7.9.317/src/codegen/source-position.h
  3rdParty/fuerte/src/H2Connection.cpp
  3rdParty/fuerte/src/types.cpp
  3rdParty/iresearch/core/search/sort.cpp
  3rdParty/iresearch/core/search/sort.hpp
  3rdParty/iresearch/core/utils/arena_allocator.hpp
  3rdParty/iresearch/core/utils/levenshtein_utils.cpp
  lib/ProgramOptions/Parameters.h
  lib/Rest/Version.h
  tests/IResearch/ExpressionFilter-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/common.cpp
Labels: 4 Windows

#11060 fix console.log() not logging in arangosh
  CHANGELOG
  js/client/client.js
Labels: 9 Ready to Merge

#11061 Bug fix 3.5/fix console log
  CHANGELOG
  js/client/client.js
Labels: 9 Ready to Merge

#11064 fixed issue #11051
  CHANGELOG
  arangod/Aql/DocumentProducingNode.h
  arangod/Aql/IndexNodeOptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-move-filters-into-enumerate.js
Labels: 9 Ready to Merge

#11068 plan change removes local hot backups
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
Labels: 1 Bug, 9 Ready to Merge, 9 Review Required

#11057 switch internal documents count type from int64_t to uint64_t, just in case
  arangod/Transaction/CountCache.cpp
  arangod/Transaction/CountCache.h
  arangod/Transaction/Helpers.cpp
  arangod/Transaction/Helpers.h
  arangod/Transaction/Methods.cpp
  arangod/VocBase/LogicalCollection.cpp
Labels: 9 Ready to Merge

#11072 removing misleading upgrade instructions
  CHANGELOG
  arangod/RestHandler/RestPleaseUpgradeHandler.cpp
  arangod/VocBase/Methods/Upgrade.cpp
Labels: 9 Ready to Merge

#11048 Use vst in cluster
  3rdParty/fuerte/include/fuerte/helper.h
  3rdParty/fuerte/src/GeneralConnection.cpp
  3rdParty/fuerte/src/H1Connection.cpp
  3rdParty/fuerte/src/H1Connection.h
  3rdParty/fuerte/src/H2Connection.cpp
  3rdParty/fuerte/src/VstConnection.cpp
  3rdParty/fuerte/src/VstConnection.h
  3rdParty/fuerte/src/helper.cpp
  3rdParty/nghttp2/CMakeLists.txt
  arangod/Agency/Agent.cpp
  arangod/Agency/Constituent.cpp
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/TraverserEngineRegistry.cpp
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/GeneralCommTask.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/GeneralServer/VstCommTask.h
  arangod/Indexes/Index.cpp
  arangod/Network/ConnectionPool.cpp
  arangod/Network/Methods.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/RestHandler/RestAuthHandler.cpp
  arangod/RestHandler/RestBaseHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/V8Server/v8-actions.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangosh/Dump/DumpFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
  lib/Basics/StringUtils.cpp
  lib/Rest/CommonDefines.cpp
  lib/Rest/CommonDefines.h
  lib/Rest/GeneralResponse.h
  lib/Rest/HttpRequest.cpp
  lib/Rest/HttpResponse.h
  lib/Rest/VstRequest.cpp
  lib/Rest/VstResponse.cpp
Labels: 9 Ready to Merge

#11047 remove storage engine selection
  Installation/MacOSX/Bundle/arangodb-cli.sh.in
  Installation/Windows/Templates/NSIS.template.in
  Installation/debian/config.in
  Installation/debian/postinst.in
  Installation/debian/templates.in
  Installation/rpm/arangodb.spec.in
  etc/arangodb3/arangod.conf.in
Labels: DO_NOT_MERGE

#11084 Bug fix 3.6/arangorestore fix create database
  CHANGELOG
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Shell/ClientFeature.cpp
Labels: 9 Ready to Merge

#11083 fix error message when database creation fails for `--create-database` option
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Shell/ClientFeature.cpp
Labels: 9 Ready to Merge

#11089 fix handling of `geometry` attributes
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 9 Ready to Merge

#11091 fixed DEVSUP-554 and disabled "collect-in-cluster" when a LIMIT is found
  CHANGELOG
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-collect-count.js
Labels: 9 Ready to Merge

#10952 Feature/admin status
  arangod/RestHandler/RestStatusHandler.cpp
  arangod/RestHandler/RestStatusHandler.h
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/versionCheck.js
  js/common/modules/@arangodb/common.js
  js/server/bootstrap/coordinator.js
  js/server/server.js
Labels: 9 WIP

#11067 Document Validation - Phase 1 - Basic Machinery
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ModificationExecutorHelpers.cpp
  arangod/Aql/ModificationOptions.cpp
  arangod/Aql/ModificationOptions.h
  arangod/CMakeLists.txt
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/Utils/OperationOptions.h
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Validators.cpp
  arangod/VocBase/Validators.h
  arangod/VocBase/vocbase.cpp
  js/client/modules/@arangodb/arango-collection.js
  js/client/modules/@arangodb/arango-database.js
  js/common/bootstrap/errors.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  lib/V8/v8-globals.cpp
  lib/V8/v8-globals.h
  tests/js/common/shell/shell-validation-rocksdb.js
Labels: 1 Feature

#11100 fix optimizer rule "move-filters-into-enumerate"
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-move-filters-into-enumerate.js
Labels: 9 Ready to Merge

#11117 [3.6] Guard AqlValues properly in ModificationExecutor
  CHANGELOG
  arangod/Aql/ModificationExecutor.cpp
  arangod/Aql/ModificationExecutor.h
Labels: 9 Ready to Merge

#10988 Feature/aql subquery operations stack enumerate list
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/EnumerateListExecutor.cpp
  arangod/Aql/EnumerateListExecutor.h
  arangod/Aql/ExecutionBlockImpl.cpp
  etc/testing/arangod-common.conf
  tests/Aql/EnumerateListExecutorTest.cpp
  tests/js/common/shell/shell-statement-encoding-noncluster.js
Labels: 1 Feature, 9 Review Required

#11120 Documentation/rotate jwt docublocks
  Documentation/DocuBlocks/Rest/Administration/get_admin_server_jwt.md
  Documentation/DocuBlocks/Rest/Administration/post_admin_server_jwt.md
  Documentation/DocuBlocks/Rest/Administration/put_admin_server_mode.md
Labels: 3 Documentation

#11132 Update OskarTestSuitesBlackList
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#11129 Update OskarTestSuitesBlackList
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#11131 Update OskarTestSuitesBlackList
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#11130 Update OskarTestSuitesBlackList
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#11128 Update OskarTestSuitesBlackList
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#11121 fix shrink method in aqlitemblock
  arangod/Aql/AqlItemBlock.cpp
Labels: 9 Ready to Merge

#11125 fix collect-in-cluster rule with limit
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-collect-count.js
Labels: 9 Ready to Merge

#11098 Feature/aql subquery operations stack calculation exec enumerate exec
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/CalculationExecutor.cpp
  arangod/Aql/CalculationExecutor.h
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/EnumerateCollectionExecutor.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/FilterExecutor.cpp
  arangod/Utils/OperationCursor.cpp
  arangod/Utils/OperationCursor.h
  tests/Aql/CalculationExecutorTest.cpp
  tests/Aql/EnumerateCollectionExecutorTest.cpp
  tests/Aql/ExecutorTestHelper.h
  tests/Mocks/Servers.cpp
  tests/Mocks/Servers.h
Labels: 1 Feature, 9 Review Required

#11145 honor cacheEnabled attribute in collection properties update in coordinator case
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/ResignShardLeadership.cpp
Labels: 9 Ready to Merge

#11139 Docs: Remove misleading statement
  Documentation/DocuBlocks/Rest/Database/get_api_database_current.md
Labels: 3 Documentation, 9 Ready to Merge

#11147 Honor `cacheEnabled` attribute when updating the properties of a collection in case of the cluster
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/ResignShardLeadership.cpp
Labels: 9 Ready to Merge

#11146 Honor `cacheEnabled` attribute when updating the properties of a collection in case of the cluster
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceStrings.h
Labels: 9 Ready to Merge

#11153 Bug fix/fix jwt option
  CHANGELOG
  arangod/GeneralServer/AuthenticationFeature.cpp
Labels: 9 Ready to Merge

#11152 Feature/improve block prefetching in collect
  CHANGELOG
  arangod/Aql/HashedCollectExecutor.cpp
  arangod/Aql/SortedCollectExecutor.cpp
  tests/js/server/aql/aql-profiler-noncluster.js
Labels: 9 Waiting for Jenkins

#11156 fix some test memleaks, slightly optimize LEVENSHTEIN_DISTANCE function
  arangod/Aql/Functions.cpp
  arangod/Transaction/Context.cpp
  arangod/Transaction/Context.h
  lib/Basics/StringUtils.cpp
  lib/Basics/StringUtils.h
  tests/Aql/JaccardFunctionTest.cpp
Labels: 9 Ready to Merge

#11070 [3.5] plan change removed local hot backups
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
Labels: 1 Bug, 9 WIP

#11160 Feature/aql performance improvements
  CHANGELOG
  arangod/Aql/AqlItemBlockManager.cpp
  arangod/Aql/AqlItemBlockManager.h
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/RegisterPlan.h
  arangod/Graph/BaseOptions.h
  arangod/Graph/TraverserOptions.cpp
  arangod/Graph/TraverserOptions.h
  js/common/modules/@arangodb/aql/explainer.js
  lib/Basics/NumberUtils.cpp
  lib/Basics/NumberUtils.h
  lib/CMakeLists.txt
  tests/Aql/AqlItemBlockTest.cpp
  tests/js/server/aql/aql-optimizer-rule-optimize-traversals-spec.js
  tests/js/server/aql/aql-traversal-restrict-edge-collections.js
  tests/js/server/aql/aql-traversal-restrict-vertex-collections.js
Labels: 9 Ready to Merge

#10320 Docs: Make scripts compatible with Python 3
  Documentation/Scripts/codeBlockReader.py
  utils/checkLogIds.py
  utils/generateErrorfile.py
  utils/generateExamples.py
  utils/generateExitCodesFiles.py
  utils/generateSwagger.py
Labels: 3 Documentation, 9 Ready to Merge

#11174 Bug fix 3.6/fix invalid array handling in traverser
  arangod/Cluster/TraverserEngine.cpp
Labels: 9 Ready to Merge

#11185 [3.6] maintenance mode detection unlocking agency hot backups
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug

#11186 fix supervision mode detection when unlocking agency in hot backup
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug

#11190 Fix supervision mode detection when unlocking agency in hot backup
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Feature

#11165 Move ModificationExecutors to new interface
  arangod/Aql/AqlItemBlockInputMatrix.cpp
  arangod/Aql/AqlItemBlockInputMatrix.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ModificationExecutor.cpp
  arangod/Aql/ModificationExecutor.h
Labels: 9 Waiting for Jenkins

#11192 Feature/aql subquery operations stack materialize executor
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/FilterExecutor.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
  arangod/Aql/RemoteExecutor.cpp
Labels: 9 Review Required
