Repository arangodb/arangodb, pull requests merged in 2020-05, with the labels that each got.

#11537 Feature 3.6/rocksdb disable edge cache
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  tests/js/common/shell/shell-edge-index.js
Labels: 9 Ready to Merge

#11512 fix disjoints in query snippet
  arangod/Aql/GraphNode.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/QuerySnippet.cpp
  arangod/Aql/QuerySnippet.h
  js/server/modules/@arangodb/aql-graph-traversal-generic-graphs.js
Labels: 9 Review Required

#11552 fix an unstable test that depended on timing
  tests/js/server/recovery/foxx-directories.js
Labels: 9 Ready to Merge

#11551 internal cleanup
  arangod/Aql/AllRowsFetcher.cpp
  arangod/Aql/AllRowsFetcher.h
  arangod/Aql/Query.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Graph/ShortestPathPriorityQueue.h
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/VocbaseContext.h
  lib/Rest/GeneralRequest.h
Labels: 9 Ready to Merge

#11550 next attempt at un-greylisting a test
  tests/Greylist.txt
  tests/js/common/shell/shell-query-stream-timecritical-spec.js
Labels: 9 Ready to Merge

#11507 Fix invalid value of isSystem attribute for non-system databases.
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/VocbaseInfo.cpp
  arangod/VocBase/VocbaseInfo.h
  tests/Aql/IndexNodeTest.cpp
  tests/IResearch/common.cpp
  tests/js/common/shell/01_shell-database.js
Labels: 9 Ready to Merge

#11529 fix spurious test failures in resilience_move tests
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.h
  arangod/StorageEngine/StorageEngine.h
  arangod/VocBase/vocbase.cpp
Labels: 9 Ready to Merge

#11544 Fix dead-lock in hot-backup
  CHANGELOG
Labels: 1 Bug, 9 Ready to Merge

#11567 Solve a deadlock problem in the cluster.
  CHANGELOG
  arangod/Transaction/ManagerFeature.cpp
Labels: 1 Bug

#11568 Fix a deadlock in the cluster.
  CHANGELOG
  arangod/Transaction/ManagerFeature.cpp
Labels: 1 Bug, 9 Ready to Merge

#11536 Bug fix 3.5/fix issue 11303
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  tests/js/common/shell/shell-edge-index.js
Labels: 9 Ready to Merge

#11579 Bug fix/optional docs collapse
  3rdParty/README_maintainers.md
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.html
  js/apps/system/_admin/aardvark/APP/frontend/js/views/supportView.js
  js/server/assets/swagger/index.html
Labels: 1 Feature, 3 Foxx, 3 Swagger, 3 UI

#11583 Added isDisjoint and isSmart to serialization of GraphNodes
  arangod/Aql/GraphNode.cpp
Labels: 1 Bug

#11560 Feature/improve registerplanning regs to keep planning
  CHANGELOG
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/RegisterPlan.h
  tests/Aql/ExecutionNodeTest.cpp
  tests/Aql/IndexNodeTest.cpp
  tests/Aql/RegisterPlanTest.cpp
  tests/IResearch/IResearchViewNode-test.cpp
Labels: 9 External Review, 9 Review Required

#11587 Docs: Delete multiple documents with HTTP API
  Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
  Documentation/DocuBlocks/Rest/Documents/post_create_document.md
  Documentation/DocuBlocks/Rest/Documents/post_create_multiple_document.md
Labels: 1 Bug, 3 Documentation

#11596 fixed issue #11590
  CHANGELOG
  arangod/Aql/SingleRemoteModificationExecutor.cpp
  tests/js/server/aql/aql-optimizer-optimize-cluster-single-document-operations.js
Labels: 9 Ready to Merge

#11594 fixed issue #11590
  CHANGELOG
  arangod/Aql/SingleRemoteModificationExecutor.cpp
  tests/js/server/aql/aql-optimizer-optimize-cluster-single-document-operations.js
Labels: 9 Ready to Merge

#11588 first index for poll must be calculated correctly
  CHANGELOG
  arangod/Agency/RestAgencyHandler.cpp
Labels: 1 Bug

#11519 Update README_maintainers.md
  README_maintainers.md
Labels: 3 Documentation

#11578 first step member threads calling loadPlan / loadCurrent
  CHANGELOG
  arangod/Agency/AsyncAgencyComm.h
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/HeartbeatThread.h
  arangod/Cluster/RestClusterHandler.cpp
  arangod/RestHandler/RestRepairHandler.cpp
Labels: 1 Feature

#11611 [3.5] Forward requests to correct coordinator based on transaction header
  CHANGELOG
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestTasksHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
Labels: 3 Cluster

#11610 [3.6] Forward requests to correct coordinator based on transaction header
  CHANGELOG
  arangod/RestHandler/RestControlPregelHandler.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestTasksHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
Labels: 3 Cluster

#11622 Fix drop collection hangers.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/v8-cluster.cpp
  arangod/VocBase/Methods/Databases.cpp
Labels: 1 Bug

#11616 Fix issues with arangodump encryption and compression
  CHANGELOG
  arangosh/Dump/DumpFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Utils/ManagedDirectory.cpp
  arangosh/Utils/ManagedDirectory.h
  js/client/modules/@arangodb/testsuites/dump.js
Labels: 3 ImportExport

#11621 [3.5] Fix issues with arangodump encryption and compression
  CHANGELOG
  arangosh/Dump/DumpFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Utils/ManagedDirectory.cpp
  arangosh/Utils/ManagedDirectory.h
  js/client/modules/@arangodb/testsuites/dump.js
Labels: 3 ImportExport

#11608 Port bugfix from 3.6 to 3.4.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug

#11592 Do not always loadPlan on ClusterInfo::getCollections.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug, 3 Cluster

#11609 Added a forgotten Plan/Version increment.
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug, 3 Cluster

#11619 [3.6] Fix issues with arangodump encryption and compression
  CHANGELOG
  arangosh/Dump/DumpFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Utils/ManagedDirectory.cpp
  arangosh/Utils/ManagedDirectory.h
  js/client/modules/@arangodb/testsuites/dump.js
Labels: 3 ImportExport

#11600 Feature/distribute snipper joiner
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
Labels: 9 Review Required, 9 Waiting for Jenkins

#11606 [3.5] Fix bug where early abort condition aborts too early
  CHANGELOG
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  tests/js/server/aql/aql-graph-k-shortest-path-early-abort-regression.js
Labels: 3 Graph

#11605 [3.6] Fix bug where early abort condition aborts too early
  CHANGELOG
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  tests/js/server/aql/aql-graph-k-shortest-path-early-abort-regression.js
Labels: 3 Graph

#11607 Port bug fix to 3.5
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 1 Bug

#11627 Fixed ordering of includes in varusage finder.
  arangod/Aql/VarUsageFinder.cpp
  arangod/Aql/VarUsageFinder.h
Labels: 1 Bug, 9 Ready to Merge

#11602 Fix bug where early abort condition aborts too early
  CHANGELOG
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  tests/js/server/aql/aql-graph-k-shortest-path-early-abort-regression.js
Labels: 3 Graph

#11603 Feature/improve registerplanning reduce depth
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/RegisterInfos.cpp
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/RegisterPlan.h
  tests/Aql/RegisterPlanTest.cpp
Labels: 9 Waiting for Jenkins

#11593 Feature/update register planning comments
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
Labels: 9 Ready to Merge

#11639 Bug fix 3.6/arangosync 0.7.5
  CHANGELOG
  VERSIONS
Labels: 3 Cluster

#11641 disable building rocksdb tools when building arangodb
  3rdParty/rocksdb/CMakeLists.txt
Labels: 9 Ready to Merge

#11630 [3.4] Fix issues with arangodump encryption and compression
  CHANGELOG
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Utils/ManagedDirectory.cpp
  arangosh/Utils/ManagedDirectory.h
  js/client/modules/@arangodb/testsuites/dump.js
Labels: 3 ImportExport, 9 Ready to Merge

#11640 Fix an arangod configuration bug (#11632)
  lib/ApplicationFeatures/ConfigFeature.cpp
Labels: 9 Ready to Merge

#11637 Fix an arangod configuration bug (#11632)
  lib/ApplicationFeatures/ConfigFeature.cpp
Labels: 9 Ready to Merge

#11597 Docs: Delete multiple documents with HTTP API (#11587)
  Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
Labels: 1 Bug, 3 Documentation

#11638 Fix an arangod configuration bug (#11632)
  lib/ApplicationFeatures/ConfigFeature.cpp
Labels: 9 Ready to Merge

#11586 Bug fix/cleanup aql collection handling
  arangod/Aql/AqlTransaction.cpp
  arangod/Aql/Ast.cpp
  arangod/Aql/Collection.cpp
  arangod/Aql/Collection.h
  arangod/Aql/CollectionAccessingNode.cpp
  arangod/Aql/Collections.cpp
  arangod/Aql/Collections.h
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesReplaceFunctions.cpp
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/TraverserEngine.cpp
  arangod/RestServer/TtlFeature.cpp
  tests/Aql/EnumerateCollectionExecutorTest.cpp
  tests/Graph/GraphTestTools.h
  tests/IResearch/IResearchViewNode-test.cpp
  tests/js/server/aql/aql-skipping.js
Labels: 9 Ready to Merge

#11654 remove obsolete options from recovery test
  js/client/modules/@arangodb/testsuites/recovery.js
Labels: 9 Ready to Merge

#11658 Fix edge cases in RocksDB primary index range lookups for operators >= and <.
  CHANGELOG
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  tests/js/server/aql/aql-optimizer-primary-index-ranges-rocksdb.js
Labels: 9 Ready to Merge

#11657 fix primary key range lookup edge cases for operators >= and <
  CHANGELOG
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  tests/js/server/aql/aql-optimizer-primary-index-ranges-rocksdb.js
Labels: 9 Ready to Merge

#11664 [3.6] Also throw if result is not ok()
  CHANGELOG
  arangod/Aql/ModificationExecutorHelpers.cpp
  arangod/Aql/ModificationExecutorHelpers.h
Labels: 9 Ready to Merge

#11473 Analyzer revision
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/AgencyComm.h
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryContext.h
  arangod/Aql/QueryExpressionContext.h
  arangod/Aql/RestAqlHandler.cpp
  arangod/CMakeLists.txt
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterTypes.cpp
  arangod/Cluster/ClusterTypes.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/v8-cluster.cpp
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/IResearch/AqlHelper.h
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchAnalyzerFeature.h
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/RestHandler/RestAnalyzerHandler.cpp
  arangod/RestHandler/RestAnalyzerHandler.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/V8Server/v8-analyzers.cpp
  arangod/V8Server/v8-vocbase.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/VocbaseInfo.cpp
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  js/client/modules/@arangodb/testsuites/resilience.js
  js/common/bootstrap/errors.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchDocument-test.cpp
  tests/IResearch/IResearchLinkHelper-test.cpp
  tests/IResearch/IResearchLinkMeta-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/RestHandler/RestAnalyzerHandler-test.cpp
  tests/V8Server/v8-analyzers-test.cpp
  tests/js/common/aql/aql-view-arangosearch-feature.js
  tests/js/server/resilience/analyzers/analyzers-revision-cluster.js
  tests/js/server/resilience/analyzers/repair-analyzers-revision-cluster.js
Labels: 3 ArangoSearch

#11676 fixed issue #11652: Error: AQL: missing variable #2 (1) for node #6 (FilterNode) while planning registers
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-move-filters-into-enumerate.js
Labels: 3 AQL, 9 Ready to Merge

#11667 Fix a truncate hanger after a quick dbserver restart.
  CHANGELOG
  arangod/Agency/AgencyFeature.cpp
  arangod/Transaction/Methods.cpp
  js/common/bootstrap/errors.js
Labels: 1 Bug, 3 Cluster

#11675 fixed issue #11652: Error: AQL: missing variable #2 (1) for node #6 (FilterNode) while planning registers
  CHANGELOG
  arangod/Aql/Expression.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-move-filters-into-enumerate.js
Labels: 9 Ready to Merge

#11677 add caching for validation
  arangod/Aql/AqlFunctionsInternalCache.cpp
  arangod/Aql/AqlFunctionsInternalCache.h
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/CalculationExecutor.cpp
  arangod/Aql/CalculationExecutor.h
  arangod/Aql/DocumentExpressionContext.cpp
  arangod/Aql/DocumentExpressionContext.h
  arangod/Aql/DocumentIndexExpressionContext.cpp
  arangod/Aql/DocumentIndexExpressionContext.h
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/DocumentProducingHelper.h
  arangod/Aql/ExecutorExpressionContext.cpp
  arangod/Aql/ExecutorExpressionContext.h
  arangod/Aql/ExpressionContext.h
  arangod/Aql/FixedVarExpressionContext.cpp
  arangod/Aql/FixedVarExpressionContext.h
  arangod/Aql/Functions.cpp
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/InAndOutRowExpressionContext.cpp
  arangod/Aql/InAndOutRowExpressionContext.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/PruneExpressionEvaluator.cpp
  arangod/Aql/PruneExpressionEvaluator.h
  arangod/Aql/QueryExpressionContext.cpp
  arangod/Aql/QueryExpressionContext.h
  arangod/Aql/TraversalConditionFinder.cpp
  arangod/CMakeLists.txt
  arangod/Graph/BaseOptions.cpp
  arangod/Graph/BaseOptions.h
  arangod/Graph/TraverserOptions.cpp
  arangod/IResearch/IResearchExpressionContext.cpp
  arangod/IResearch/IResearchExpressionContext.h
  arangod/VocBase/Validators.h
  tests/IResearch/ExpressionContextMock.h
Labels: 3 Core, performance

#11669 Bug fix 3.6/restart follower no leader set
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/TakeoverShardLeadership.cpp
  arangod/Transaction/Methods.cpp
Labels: 3 Cluster

#11674 Bug fix/restart follower no leader set
  CHANGELOG
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/TakeoverShardLeadership.cpp
  arangod/Transaction/Methods.cpp
Labels: 3 Cluster

#11613 Mention arangodbtests (gtest) in README_maintainers.md
  README_maintainers.md
Labels: 3 Build, 3 Documentation

#11693 c++-17 flag for visual studio
  CHANGELOG
  CMakeLists.txt
Labels: 9 Ready to Merge

#9936 Bugfix: Add object counts to arangoimport latency
  arangosh/Import/ImportHelper.cpp
  arangosh/Import/QuickHistogram.h
  arangosh/Import/SenderThread.cpp
Labels: 9 Review Required

#11662 Bug fix/scatter in fully skipped spliced subquery
  CHANGELOG
  arangod/Aql/BlocksWithClients.cpp
  arangod/Aql/DistributeClientBlock.cpp
  arangod/Aql/DistributeClientBlock.h
  arangod/Aql/DistributeExecutor.cpp
  arangod/Aql/DistributeExecutor.h
  arangod/Aql/MutexExecutor.cpp
  arangod/Aql/MutexExecutor.h
  arangod/Aql/ScatterExecutor.cpp
  arangod/CMakeLists.txt
  tests/js/server/aql/aql-shadowrow-block-return-regression.js
Labels: 1 Bug, 9 Ready to Merge

#11648 Bug fix/keep mindepth on undecided condition
  CHANGELOG
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/Graphs.cpp
  arangod/Aql/Graphs.h
  arangod/Aql/TraversalConditionFinder.cpp
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/Cluster/ClusterEdgeCursor.cpp
  arangod/Cluster/ClusterEdgeCursor.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/Cluster/TraverserEngine.cpp
  arangod/Cluster/TraverserEngine.h
  arangod/InternalRestHandler/InternalRestTraverserHandler.cpp
  js/server/modules/@arangodb/aql-graph-traversal-generic-tests.js
  tests/js/server/aql/aql-graph-traverser.js
Labels: 1 Bug, 9 Ready to Merge

#9432 Issue #8941
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoQueries.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoUsers.js
Labels: 9 CLA available, 9 Ready to Merge

#11712 Make test not loose failed leaders/followers
  tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster.js
Labels: 3 - Testing, 3 Cluster

#11666 fix BTS-57
  arangod/Aql/GraphNode.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestGraphHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  arangod/Transaction/Manager.cpp
  tests/js/client/shell/shell-transaction.js
Labels: 9 Ready to Merge

#11703 Improve behaviour on dropping followers.
  3rdParty/fuerte/src/H1Connection.cpp
  3rdParty/fuerte/src/H1Connection.h
  CHANGELOG
  arangod/Network/Methods.cpp
  arangod/Utils/CollectionNameResolver.cpp
Labels: 1 Bug

#11713 Make test not loose failed leaders/followers
  tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster-grey.js
Labels: 3 - Testing, 3 Cluster
