Repository arangodb/arangodb, pull requests merged in 2021-02, with the labels that each got.

#13447 RFC: Small Result with external error
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/Syncer.cpp
  arangod/Replication/Syncer.h
  arangod/Replication/TailingSyncer.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  lib/Basics/Result.cpp
  lib/Basics/Result.h
  lib/Basics/ResultError.cpp
  lib/Basics/ResultError.h
  lib/CMakeLists.txt
Labels: 9 Review Required

#12694 Correctly handle development flag in upgrade
  CHANGELOG
  js/apps/system/_api/foxx/APP/index.js
  js/server/modules/@arangodb/foxx/manager.js
  tests/js/client/shell/shell-foxx-api-spec.js
Labels: 3 Foxx, 9 Ready to Merge

#12728 Discard unused Foxx config when saving config in production
  CHANGELOG
  js/apps/system/_api/foxx/APP/index.js
  js/server/modules/@arangodb/foxx/service.js
  tests/js/client/shell/shell-foxx-api-spec.js
  tests/js/common/test-data/apps/with-configuration2/manifest.json
Labels: 3 Foxx, 9 Ready to Merge

#13244 Quiet suggest-override warnings and build failures
  3rdParty/iresearch/core/analysis/token_streams.hpp
  3rdParty/iresearch/core/formats/formats_burst_trie.cpp
  3rdParty/iresearch/core/index/iterators.cpp
  3rdParty/iresearch/core/search/sort.hpp
  3rdParty/iresearch/core/store/data_input.hpp
  3rdParty/iresearch/core/store/store_utils.hpp
  3rdParty/iresearch/core/utils/frozen_attributes.hpp
  3rdParty/iresearch/core/utils/fstext/fst_table_matcher.hpp
  3rdParty/iresearch/external/openfst/fst/lookahead-matcher.h
  3rdParty/iresearch/external/openfst/fst/matcher.h
  3rdParty/iresearch/external/openfst/fst/vector-fst.h
  CHANGELOG
  arangod/Agency/AgencyPaths.h
  arangod/Agency/PathComponent.h
  arangod/Aql/ClusterNodes.h
  arangod/Aql/CollectNode.h
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/IndexNode.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/QuerySnippet.cpp
  arangod/Aql/RegisterPlan.h
  arangod/Aql/SubqueryEndExecutionNode.h
  arangod/Aql/VarUsageFinder.h
  arangod/Aql/WindowNode.h
  arangod/IResearch/GeoAnalyzer.h
  arangod/IResearch/IResearchLink.cpp
  arangod/RestHandler/RestAdminClusterHandler.h
  tests/Aql/MockTypedNode.h
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
Labels: 9 CLA available

#13477 Bug fix 3.7/bts 284
  CHANGELOG
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/VocBase/Methods/Upgrade.cpp
  arangod/VocBase/Methods/Upgrade.h
  tests/IResearch/IResearchFeature-test.cpp
Labels: 3 ArangoSearch, 3 Upgrade

#13474 Correctly handle development flag in upgrade (3.7)
  CHANGELOG
  js/apps/system/_api/foxx/APP/index.js
  js/server/modules/@arangodb/foxx/manager.js
  tests/js/client/shell/shell-foxx-api-spec.js
Labels: 3 Foxx, 9 Ready to Merge

#13475 Discard unused Foxx config when saving config in production (3.7)
  CHANGELOG
  js/apps/system/_api/foxx/APP/index.js
  js/server/modules/@arangodb/foxx/service.js
  tests/js/client/shell/shell-foxx-api-spec.js
  tests/js/common/test-data/apps/with-configuration2/manifest.json
Labels: 3 Foxx, 9 Ready to Merge

#13473 Feature 3.7/memprof testingjs dumper2
  README_maintainers.md
  js/client/modules/@arangodb/process-utils.js
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testing.js
  tests/js/common/shell/shell-sleep-grey.js
Labels: 3 - Testing, 3 Build, 9 Ready to Merge

#13383 add read/write metrics
  CHANGELOG
  arangod/GeneralServer/GeneralCommTask.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/H2CommTask.h
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/HttpCommTask.h
  arangod/GeneralServer/VstCommTask.cpp
  arangod/GeneralServer/VstCommTask.h
  arangod/RestServer/Metrics.h
  arangod/RestServer/MetricsFeature.cpp
  arangod/RestServer/MetricsFeature.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/Statistics/RequestStatistics.h
  arangod/Statistics/ServerStatistics.cpp
  arangod/Statistics/ServerStatistics.h
  tests/Metrics/MetricsTest.cpp
  tests/js/client/server_parameters/test-export-document-metrics-off-noncluster.js
  tests/js/client/server_parameters/test-export-document-metrics-on-noncluster.js
Labels: 9 Ready to Merge

#13498 force DATABASE_UPGRADE flag on upgrade
  arangod/VocBase/Methods/Upgrade.cpp
  tests/IResearch/IResearchFeature-test.cpp
Labels: 3 ArangoSearch, 3 Upgrade

#13514 Bug fix/check for kill more consistently
  CHANGELOG
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/DocumentProducingHelper.h
Labels: 1 Bug

#13495 don't use an exclusive transaction on _fishbowl collection (#13491)
  CHANGELOG
  js/common/modules/@arangodb/foxx/store.js
Labels: 3 Foxx, 9 Ready to Merge

#13531 fix reloading of TLS certificates error reporting
  CHANGELOG
  arangod/GeneralServer/GeneralServerFeature.h
Labels: 1 Bug, 3 SSL

#13500 improvements for logging
  CHANGELOG
  arangod/RestHandler/RestAdminLogHandler.cpp
  arangod/RestHandler/RestAdminLogHandler.h
  lib/Logger/LogBufferFeature.cpp
  lib/Logger/LogBufferFeature.h
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
  lib/Logger/LoggerFeature.cpp
  lib/Logger/LoggerFeature.h
  lib/V8/v8-utils.cpp
  tests/js/client/server_parameters/log-max-length-default.js
  tests/js/client/server_parameters/log-max-length-large.js
  tests/js/client/server_parameters/log-max-length-small.js
  tests/js/client/server_parameters/test-log-api-enabled-false.js
  tests/js/client/server_parameters/test-log-api-enabled-true.js
  tests/js/client/server_parameters/test-log-in-memory-level-err.js
  tests/js/client/server_parameters/test-log-in-memory-level-fatal.js
  tests/js/client/server_parameters/test-log-in-memory-level-info.js
  tests/js/client/server_parameters/test-log-in-memory-level-warn.js
Labels: 9 Ready to Merge

#13517 Do not create index estimator objects for proxy collection objects
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
Labels: 9 Ready to Merge

#13518 prepare explainer code for 3.8 DistributeNode output
  js/common/modules/@arangodb/aql/explainer.js
Labels: 9 Ready to Merge

#13527 [3.7] Bug fix/check for kill more consistently
  CHANGELOG
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/DocumentProducingHelper.h
Labels: 1 Bug, 9 Ready to Merge

#13496 Use frozen::unordered_map for ErrorMessages
  CMakeLists.txt
  lib/Basics/error-registry.h
  lib/Basics/error.cpp
  lib/Basics/voc-errors.h
  lib/CMakeLists.txt
  utils/generateErrorfile.py
Labels: 9 Review Required

#13526 Small refactoring, clarifying intent
  arangod/GeneralServer/GeneralServer.cpp
Labels: 9 CLA available

#13455 Feature/error messages as string views
  CMakeLists.txt
  arangod/Aql/Ast.cpp
  arangod/Aql/EnumerateListExecutor.cpp
  arangod/Aql/Parser.cpp
  arangod/Aql/Parser.h
  arangod/Aql/Query.cpp
  arangod/Aql/QueryCursor.cpp
  arangod/Aql/QueryWarnings.cpp
  arangod/Aql/QueryWarnings.h
  arangod/Aql/WindowNode.cpp
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
  arangod/GeneralServer/RestHandler.cpp
  arangod/Graph/ShortestPathFinder.cpp
  arangod/Graph/TraverserCache.cpp
  arangod/Network/Utils.cpp
  arangod/Pregel/TypedBuffer.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/ReplicationApplier.cpp
  arangod/RestHandler/RestImportHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangosh/Import/ImportHelper.cpp
  lib/Basics/ArangoGlobalContext.cpp
  lib/Basics/Exceptions.cpp
  lib/Basics/Exceptions.h
  lib/Basics/FileUtils.cpp
  lib/Basics/error.cpp
  lib/Basics/error.h
  lib/Basics/exitcodes.cpp
  lib/Basics/exitcodes.h
  lib/Basics/files.cpp
  lib/Basics/voc-errors.cpp
  lib/CMakeLists.txt
  lib/V8/v8-globals.cpp
  lib/V8/v8-globals.h
  lib/V8/v8-utils.cpp
  tests/Cluster/ClusterRepairsTest.cpp
  utils/generateErrorfile.py
  utils/generateExitCodesFiles.py
Labels: 9 Ready to Merge

#13520 backport some changes from https://github.com/arangodb/arangodb/pull/13507
  3rdParty/rocksdb/6.8/util/heap.h
  CHANGELOG
  arangod/IResearch/IResearchFeature.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/StorageEngine/TransactionState.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Options.cpp
  arangod/Transaction/Options.h
  lib/Basics/StringUtils.h
Labels: 3 Build, 3 RocksDB, 9 Ready to Merge

#13521 Fix potential undefined behavior
  CHANGELOG
  arangod/Aql/ExecutionNode.cpp
Labels: 9 Ready to Merge

#13524 Improve incremental sync replication
  CHANGELOG
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterTransactionCollection.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/RocksDBEngine/CMakeLists.txt
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.h
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBMethods.cpp
  arangod/RocksDBEngine/RocksDBMethods.h
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.h
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBSavePoint.cpp
  arangod/RocksDBEngine/RocksDBSavePoint.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  arangod/Utils/OperationOptions.h
  tests/js/server/replication/sync/replication-sync-malarkey.js
Labels: 9 Ready to Merge

#13532 Improvements for dropping indexes
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/StorageEngine/PhysicalCollection.h
  arangod/VocBase/Methods/Indexes.cpp
  tests/js/server/shell/shell-index-parallel-drop-create.js
Labels: 9 Ready to Merge

#13549 Bug-fix-3.7/es-784
  CHANGELOG
  arangod/IResearch/IResearchRocksDBLink.cpp
Labels: 3 Arangojs

#13546 improve wording for database sharding options in UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
Labels: 3 UI, 9 Ready to Merge

#13522 Fix potential undefined behavior
  CHANGELOG
  arangod/Aql/ExecutionNode.cpp
Labels: 9 Ready to Merge

#13528 [3.6] Bug fix/check for kill more consistently
  CHANGELOG
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/DocumentProducingHelper.h
Labels: 1 Bug, 9 Ready to Merge

#13533 Improvements for dropping indexes
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/StorageEngine/PhysicalCollection.h
  arangod/VocBase/Methods/Indexes.cpp
  tests/js/server/shell/shell-index-parallel-drop-create-rocksdb.js
Labels: 9 Ready to Merge

#13541 Fix profiling of streaming AQL queries
  CHANGELOG
  arangod/Aql/QueryCursor.cpp
  arangod/Utils/Cursor.h
  tests/js/common/shell/shell-statement.js
Labels: 9 Ready to Merge

#13554 Fixed a count collect bug
  CHANGELOG
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  tests/js/server/aql/aql-queries-optimizer-count.js
Labels: 3 AQL

#13553 Fixed a count collect bug
  CHANGELOG
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  tests/js/server/aql/aql-queries-optimizer-count.js
Labels: 9 Ready to Merge

#13486 try to stabilize a flaky foxx test
  CHANGELOG
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/RestServer/BootstrapFeature.cpp
  arangod/RestServer/BootstrapFeature.h
Labels: 3 Foxx, 9 Ready to Merge

#13555 Fixed a count collect bug
  CHANGELOG
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  tests/js/server/aql/aql-queries-optimizer-count.js
Labels: 3 AQL, 9 Ready to Merge

#13567 Fixed issue BTS-268: fix a flaky Foxx test.
  CHANGELOG
  arangod/RestServer/BootstrapFeature.cpp
  arangod/RestServer/BootstrapFeature.h
Labels: 3 Foxx

#13573 Remove outdated compile definitions for MSVC/Boost
  CHANGELOG
  CMakeLists.txt
Labels: 9 Ready to Merge

#13577 fix version number for options additions
  arangod/RestServer/MetricsFeature.cpp
  lib/Logger/LoggerFeature.cpp
Labels: 3 Documentation

#13580 fix a potential wrong length calculation after log messages were shrunk
  lib/Logger/LogBufferFeature.cpp
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
Labels: ASan

#13587 add dump_jwt test to blocklist
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#13568 increase the timeout if we're runnig in asan / code coverage
  tests/js/client/communication/test-kill.js
Labels: 3 - Testing

#13590 [3.7] Disabled test dump_with_crashes.
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#13605 3.7: added elapsed time logging
  CHANGELOG
  arangod/IResearch/IResearchLink.cpp
Labels: 3 - Testing

#10760 Docs: Update Gharial error codes (DocuBlocks)
  Documentation/DocuBlocks/Rest/AQL/post_api_explain.md
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Database/get_api_database_list.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_edge_create_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_edge_definition_modify_http_examples.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_logger_follow.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_all.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_by_example.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_first_example.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_fulltext.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_near.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_range.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_within.md
  Documentation/DocuBlocks/Rest/Simple Queries/put_api_simple_within_rectangle.md
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
Labels: 3 Documentation

#13586 add dump_jwt test to blocklist
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#13589 [3.6] Disable dump_with_crashes.
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing

#13608 Docs: Don't list implied introducedIn versions
  arangod/Replication/ReplicationFeature.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  arangosh/Dump/DumpFeature.cpp
  arangosh/Shell/ConsoleFeature.cpp
  lib/Logger/LogBufferFeature.cpp
  lib/Logger/LoggerFeature.cpp
Labels: 3 Documentation

#13617 Cleanup hotbackup transfer jobs in agency
  CHANGELOG
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  tests/Agency/SupervisionTest.cpp
Labels: 3 ImportExport, 9 Ready to Merge

#13609 Cleanup hotbackup transfer jobs in agency
  CHANGELOG
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  tests/Agency/SupervisionTest.cpp
Labels: 3 ImportExport, 9 Ready to Merge

#13622 Update OpenSSL to 1.1.1j and OpenLDAP to 2.4.57
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#13623 Update OpenSSL to 1.1.1j and OpenLDAP to 2.4.57
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#13624 Update OpenSSL to 1.1.1j and OpenLDAP to 2.4.57
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#13627 make hot backup test clean up all its temp backups and stop as soon as possible
  tests/js/client/shell/shell-deadlock-trx-hotbackup-cluster.js
Labels: 3 - Testing, 3 ImportExport, 9 Ready to Merge
