Repository arangodb/arangodb, pull requests merged in 2021-07, with the labels that each got.

#14444 Search 161 3.7
  3rdParty/iresearch/core/search/levenshtein_filter.cpp
  3rdParty/iresearch/core/search/levenshtein_filter.hpp
  3rdParty/iresearch/core/search/phrase_filter.cpp
  3rdParty/iresearch/core/utils/levenshtein_utils.cpp
  3rdParty/iresearch/core/utils/levenshtein_utils.hpp
  ARANGO-VERSION
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchFilterFunction-test.cpp
  tests/IResearch/IResearchQueryCommon.h
  tests/IResearch/IResearchQueryLevenshteinMatch-test.cpp
  tests/IResearch/IResearchQueryPhrase-test.cpp
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
Labels: 1 Bug, 3 ArangoSearch

#14398 Fixes for shard synchronization
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/EngineInfoContainerDBServerServerBased.h
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryContext.cpp
  arangod/Aql/QueryContext.h
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/DatabaseInitialSyncer.h
  arangod/Replication/TailingSyncer.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/V8Server/v8-vocbase.cpp
  js/client/modules/@arangodb/test-helper.js
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testsuites/chaos.js
  js/common/modules/@arangodb/replication-common.js
  js/common/modules/@arangodb/test-helper-common.js
  js/common/modules/jsunity.js
  js/common/modules/jsunity/jsunity.js
  js/server/modules/@arangodb/test-helper.js
  tests/js/client/chaos/test-chaos-load-common.inc
  tests/js/client/chaos/test-module-chaos-load-cluster-nightly.js
  tests/js/client/chaos/test-module-chaos-load-cluster.js
  tests/js/client/shell/shell-aql-query-setup-timeout.js
  tests/js/client/shell/shell-dropped-followers-elcheapo-commit-cluster.js
  tests/js/server/aql/aql-modify-noncluster.js
  tests/js/server/shell/shell-collection-failures-noncluster.js
Labels: 3 Cluster

#14422 fix index selection with prefix indexes
  CHANGELOG
  arangod/Aql/OptimizerUtils.cpp
  arangod/Indexes/SortedIndexAttributeMatcher.cpp
  tests/js/server/aql/aql-index-choice.js
Labels: 3 Index, 3 Optimizer

#14434 Soft coordinator shutdown documentation
  Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
  Documentation/DocuBlocks/Rest/Administration/get_api_shutdown.md
Labels: 3 Cluster, 3 Documentation

#14437 [BTS-491][3.7] ArangoRestore connect Retry
  CHANGELOG
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Restore/RestoreFeature.h
Labels: 3 ImportExport

#14459 Fix potential segfault in tcp/ssl socket handling.
  CHANGELOG
  arangod/GeneralServer/AcceptorTcp.cpp
  arangod/GeneralServer/AcceptorTcp.h
Labels: 1 Bug

#14424 fix index selection with prefix indexes
  CHANGELOG
  arangod/Aql/OptimizerUtils.cpp
  arangod/Indexes/SortedIndexAttributeMatcher.cpp
  tests/js/server/aql/aql-index-choice.js
Labels: 9 Ready to Merge

#14451 enable process metrics on agents
  CHANGELOG
  arangod/Statistics/StatisticsFeature.cpp
  scripts/startLocalCluster.sh
  tests/js/client/shell/shell-process-metrics-cluster.js
Labels: 3 Cluster, 3 Metrics, 9 Ready to Merge

#14462 Following term id for 3.7
  CHANGELOG
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/SynchronizeShard.h
  arangod/Cluster/TakeoverShardLeadership.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Maintenance/MaintenanceTest.cpp
  tests/js/client/shell/shell-following-term-id-cluster.js
Labels: 3 Cluster

#14469 Added (gauge) metric "rocksdb_read_only"
  CHANGELOG
  arangod/RocksDBEngine/RocksDBBackgroundErrorListener.cpp
  arangod/RocksDBEngine/RocksDBBackgroundErrorListener.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
Labels: 3 Metrics

#14473 [3.7] Fixed a velocypack type error in maintenance::reportInCurrent
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
Labels: 3 Cluster, velocypack

#14479 Fix handling of empty WAL files with encryption at rest
  3rdParty/rocksdb/6.8/env/env_encryption.cc
  CHANGELOG
  tests/js/server/recovery/empty-journal.js
Labels: 1 Bug, 3 RocksDB

#14487 improve shell-aql-query-setup-timeout test
  tests/js/client/shell/shell-aql-query-setup-timeout.js
Labels: 3 - Testing, 4 Windows

#14474 Feature/hybrid smart graph additional steptype
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/KShortestPathsExecutor.cpp
  arangod/Aql/KShortestPathsNode.cpp
  arangod/CMakeLists.txt
  arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
  arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.h
  arangod/Graph/Enumerators/OneSidedEnumerator.cpp
  arangod/Graph/Enumerators/TwoSidedEnumerator.cpp
  arangod/Graph/PathManagement/PathResult.cpp
  arangod/Graph/PathManagement/PathStore.cpp
  arangod/Graph/PathManagement/PathStoreTracer.cpp
  arangod/Graph/PathManagement/PathValidator.cpp
  arangod/Graph/PathManagement/SingleProviderPathResult.cpp
  arangod/Graph/Providers/ClusterProvider.h
  arangod/Graph/Providers/ProviderTracer.cpp
  arangod/Graph/Providers/SingleServerProvider.cpp
  arangod/Graph/Providers/SingleServerProvider.h
  arangod/Graph/Queues/QueueTracer.cpp
  arangod/Graph/Steps/SingleServerProviderStep.cpp
  arangod/Graph/Steps/SingleServerProviderStep.h
  tests/Graph/GenericGraphProviderTest.cpp
  tests/Graph/SingleServerProviderTest.cpp
Labels: 9 Review Required

#13996 Feature/guarded mutex
  lib/Basics/Guarded.h
  lib/Basics/Mutex.cpp
  lib/Basics/Mutex.h
  lib/Basics/MutexLocker.h
  tests/Basics/GuardedTest.cpp
  tests/CMakeLists.txt
Labels: 9 Ready to Merge

#14417 Add new chaos test suite.
  js/client/modules/@arangodb/testsuites/chaos.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/common/modules/@arangodb/replication-common.js
  js/common/modules/jsunity.js
  tests/js/client/chaos/test-chaos-load-common.inc
  tests/js/client/chaos/test-module-chaos-load-cluster-nightly.js
  tests/js/client/chaos/test-module-chaos-load-cluster.js
Labels: 3 - Testing, 3 Cluster

#14498 Fix invalid assertion and always remove blocker object on replication failure
  CHANGELOG
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: 1 Bug, 3 - Testing, 3 Cluster

#14512 Improve startup file copying of JavaScript files
  CHANGELOG
  arangod/V8Server/V8DealerFeature.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/files.cpp
  lib/Basics/files.h
  lib/Basics/operating-system.h
  tests/js/client/server_parameters/test-copy-installation.js
Labels: 3 Build, 3 JS API

#14530 fix potential coordinator miss on existing databases
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterMethods.cpp
Labels: 3 Cluster, 3 ImportExport

#14541 Code cleanup (linting, formatting, deduping, and minor refactoring.
  .gitignore
  js/.eslintignore
  js/.eslintrc
  js/apps/system/_admin/aardvark/APP/frontend/css/select2.css
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/react/config/env.js
  js/apps/system/_admin/aardvark/APP/react/config/jest/cssTransform.js
  js/apps/system/_admin/aardvark/APP/react/config/jest/fileTransform.js
  js/apps/system/_admin/aardvark/APP/react/config/paths.js
  js/apps/system/_admin/aardvark/APP/react/config/webpack.config.dev.js
  js/apps/system/_admin/aardvark/APP/react/config/webpack.config.prod.js
  js/apps/system/_admin/aardvark/APP/react/config/webpack.config.resolve.js
  js/apps/system/_admin/aardvark/APP/react/config/webpackDevServer.config.js
  js/apps/system/_admin/aardvark/APP/react/non_ts_libs.d.ts
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/scripts/build.js
  js/apps/system/_admin/aardvark/APP/react/scripts/start.js
  js/apps/system/_admin/aardvark/APP/react/scripts/test.js
  js/apps/system/_admin/aardvark/APP/react/src/App.js
  js/apps/system/_admin/aardvark/APP/react/src/actions/arangodb.tsx
  js/apps/system/_admin/aardvark/APP/react/src/actions/taskRepeater.tsx
  js/apps/system/_admin/aardvark/APP/react/src/configureStore.tsx
  js/apps/system/_admin/aardvark/APP/react/src/index.tsx
  js/apps/system/_admin/aardvark/APP/react/src/serviceWorker.js
  js/apps/system/_admin/aardvark/APP/react/src/setupProxy.js
  js/apps/system/_admin/aardvark/APP/react/src/store/cluster/actions.tsx
  js/apps/system/_admin/aardvark/APP/react/src/store/cluster/middleware.tsx
  js/apps/system/_admin/aardvark/APP/react/src/store/cluster/reducer.tsx
  js/apps/system/_admin/aardvark/APP/react/src/store/cluster/types.tsx
  js/apps/system/_admin/aardvark/APP/react/src/store/index.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/ShardsReactView.js
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/moveShard.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/overview.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/shardInfoRow.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/specifics.tsx
  js/apps/system/_admin/aardvark/APP/react/tsconfig.json
  js/apps/system/_admin/aardvark/APP/react/yarn.lock
Labels: 3 UI

#14516 [3.6] Disable replication2_client test in oskar.
  UnitTests/OskarTestSuitesBlockList
Labels: 3 - Testing

#14515 [3.7] Disable replication2_client test in oskar.
  UnitTests/OskarTestSuitesBlockList
Labels: 3 - Testing

#14547 Improving the router initialization checking logic: polling --> evented
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
Labels: 3 UI

#14256 Add `fillBlockCache` option to bypass RocksDB block cache (#14234)
  CHANGELOG
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  arangod/RocksDBEngine/RocksDBCommon.h
  arangod/RocksDBEngine/RocksDBIterators.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/Transaction/Methods.h
  arangod/Transaction/Options.cpp
  arangod/Transaction/Options.h
  js/client/modules/@arangodb/testutils/block-cache-test-helper.js
  tests/js/client/server_parameters/fill-block-cache-off-noncluster.js
  tests/js/client/server_parameters/fill-block-cache-on-http-noncluster.js
  tests/js/client/server_parameters/fill-block-cache-on-noncluster.js
Labels: 3 RocksDB, 9 Ready to Merge

#14273 remember exception in ExecutionBlock
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionBlockImpl.h
  tests/Aql/ExecutionBlockImplTest.cpp
Labels: 3 Optimizer, 9 Ready to Merge

#14275 potential bugfix for BTS-451
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  tests/Maintenance/MaintenanceFeatureTest.cpp
Labels: 9 Ready to Merge

#14279 Bug fix 3.8/file descriptors on macos
  CHANGELOG
  arangod/RestServer/FileDescriptorsFeature.cpp
Labels: 4 MacOSX, 9 Ready to Merge

#14295 fixed BTS-398
  CHANGELOG
  arangod/Aql/OptimizerUtils.cpp
  tests/js/server/aql/aql-index-hints.js
Labels: 3 Optimizer, 9 Ready to Merge

#14330 Soft coordinator shutdown
  CHANGELOG
  arangod/Aql/QueryOptions.cpp
  arangod/CMakeLists.txt
  arangod/FeaturePhases/FinalFeaturePhase.cpp
  arangod/GeneralServer/AsyncJobManager.cpp
  arangod/GeneralServer/AsyncJobManager.h
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestShutdownHandler.cpp
  arangod/RestServer/SoftShutdownFeature.cpp
  arangod/RestServer/SoftShutdownFeature.h
  arangod/RestServer/arangod.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  arangod/Transaction/ManagerFeature.cpp
  arangod/Transaction/ManagerFeature.h
  arangod/Utils/CursorRepository.cpp
  arangod/Utils/CursorRepository.h
  arangod/V8Server/v8-voccursor.cpp
  lib/ApplicationFeatures/ApplicationFeature.cpp
  lib/ApplicationFeatures/ApplicationFeature.h
  lib/ApplicationFeatures/ApplicationServer.cpp
  lib/ApplicationFeatures/ApplicationServer.h
  tests/js/client/restart/test-restart-cluster.js
  tests/js/client/restart/test-soft-shutdown-cluster.js
Labels: 3 Cluster

#14348 Allow active failover failover
  CHANGELOG
  arangod/Replication/DatabaseInitialSyncer.cpp
Labels: 3 ActiveFailover

#14353 backport free disk space bugfix from upstream rocksdb
  3rdParty/rocksdb/6.8/env/fs_posix.cc
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  lib/Basics/files.cpp
Labels: 3 RocksDB, 9 Ready to Merge

#14355 only build actually used attributes of the path
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/Graph/BreadthFirstEnumerator.cpp
  arangod/Graph/BreadthFirstEnumerator.h
  arangod/Graph/PathEnumerator.cpp
  arangod/Graph/PathEnumerator.h
  arangod/Graph/Traverser.h
  arangod/Graph/TraverserOptions.cpp
  arangod/Graph/TraverserOptions.h
  arangod/Graph/WeightedEnumerator.cpp
  arangod/Graph/WeightedEnumerator.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/server/aql/aql-optimizer-rule-decay-unnecessary-sorted-gather-cluster.js
  tests/js/server/aql/aql-optimizer-rule-use-index-for-sort-cluster.js
  tests/js/server/aql/aql-profiler-cluster.js
  tests/js/server/aql/aql-queries-optimizer-sort-limit-cluster.js
  tests/js/server/aql/aql-traversal-paths-optimization.js
Labels: 9 Ready to Merge

#14280 [3.8] BTS-446 Cluster machines fail to integrate on OSX jenkins runs
  CHANGELOG
  arangod/Cluster/ServerState.cpp
Labels: 3 Cluster, 4 MacOSX

#14391 Bug fix/user manager version race (#14382)
  CHANGELOG
  arangod/Auth/UserManager.cpp
  arangod/Auth/UserManager.h
  tests/Auth/UserManagerClusterTest.cpp
  tests/CMakeLists.txt
Labels: 1 Bug, 3 UserManagement

#14399 Improve usability of hidden options: (#14393)
  CHANGELOG
  lib/ProgramOptions/ProgramOptions.cpp
Labels: 9 Ready to Merge

#14400 Fix DEVSUP-799
  CHANGELOG
  arangod/Cluster/ClusterTraverser.cpp
  arangod/Graph/SingleServerTraverser.cpp
  arangod/Graph/Traverser.cpp
  arangod/Graph/Traverser.h
  arangod/Graph/TraverserCache.cpp
  tests/js/server/aql/aql-graph-traverser.js
Labels: 1 Bug, 3 Graph, 4 Windows, 9 Ready to Merge

#14416 Add Comet lake support. Enforce minimum required architecture: westmere.
  cmake/OptimizeForArchitecture.cmake
Labels: 3 Build, 9 Ready to Merge

#14423 fix index selection with prefix indexes
  CHANGELOG
  arangod/Aql/OptimizerUtils.cpp
  arangod/Indexes/SortedIndexAttributeMatcher.cpp
  tests/js/server/aql/aql-index-choice.js
Labels: 3 Optimizer, 9 Ready to Merge

#14433 Fix serialization of query shutdown error code
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
Labels: 9 Ready to Merge

#14436 Bug fix/presupp 358 (#14404)
  CHANGELOG
  arangod/Pregel/Algos/WCC.cpp
  arangod/Pregel/Algos/WCC.h
  arangod/Pregel/CommonFormats.h
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/Worker-templates-algorithms.cpp
  arangod/Pregel/Worker.cpp
  tests/js/common/shell/shell-pregel-components.js
  tests/js/common/shell/shell-pregel-mulicollection-edgecol.js
Labels: 1 Bug, 3 Graph, 3 Pregel

#14445 Search-161-3.8
  3rdParty/iresearch/core/search/levenshtein_filter.cpp
  3rdParty/iresearch/core/search/levenshtein_filter.hpp
  3rdParty/iresearch/core/search/phrase_filter.cpp
  3rdParty/iresearch/core/utils/levenshtein_utils.cpp
  3rdParty/iresearch/core/utils/levenshtein_utils.hpp
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchFilterFunction-test.cpp
  tests/IResearch/IResearchQueryCommon.h
  tests/IResearch/IResearchQueryLevenshteinMatch-test.cpp
  tests/IResearch/IResearchQueryPhrase-test.cpp
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
Labels: 3 ArangoSearch

#14447 enable assertion in QueryContext::collections()
  arangod/Aql/Query.cpp
  arangod/Aql/QueryContext.cpp
  arangod/Aql/QueryContext.h
  tests/main.cpp
Labels: 3 - Testing, 9 Ready to Merge

#14452 enable process metrics on agents
  CHANGELOG
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsWorker.cpp
  scripts/startLocalCluster.sh
  tests/js/client/shell/shell-process-metrics-cluster.js
Labels: 3 Metrics, 9 Ready to Merge

#14435 Soft coordinator shutdown documentation
  Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
  Documentation/DocuBlocks/Rest/Administration/get_api_shutdown.md
Labels: 3 Documentation

#14458 Following term id for 3.8
  CHANGELOG
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/SynchronizeShard.h
  arangod/Cluster/TakeoverShardLeadership.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Maintenance/MaintenanceTest.cpp
  tests/js/client/shell/shell-following-term-id-cluster.js
Labels: 3 Cluster

#14460 [BTS-491][3.8] ArangoRestore connect Retry
  CHANGELOG
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Restore/RestoreFeature.h
Labels: 3 ImportExport

#14465 Fix numeric overflow in WINDOW cost estimation
  CHANGELOG
  arangod/Aql/WindowNode.cpp
Labels: 3 AQL, 9 Ready to Merge

#14468 Added (gauge) metric "rocksdb_read_only"
  CHANGELOG
  Documentation/Metrics/rocksdb_read_only.yaml
  arangod/RocksDBEngine/Listeners/RocksDBBackgroundErrorListener.cpp
  arangod/RocksDBEngine/Listeners/RocksDBBackgroundErrorListener.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 3 Metrics, 9 Ready to Merge

#14472 [3.8] Fixed a velocypack type error in maintenance::reportInCurrent
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
Labels: 3 Cluster

#14478 Fix handling of empty WAL files with encryption at rest
  3rdParty/rocksdb/6.8/env/env_encryption.cc
  CHANGELOG
  tests/js/server/recovery/empty-journal.js
Labels: 3 RocksDB

#14483 3.8 Fix Asan build
  3rdParty/iresearch/external/absl/absl/base/dynamic_annotations.h
Labels: 3 ArangoSearch, ASan

#14514 [3.8] Disable replication2_client test in oskar.
  UnitTests/OskarTestSuitesBlockList
Labels: 3 - Testing

#14518 Fixed BTS-408
  CHANGELOG
  arangod/Aql/Ast.h
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  arangod/IResearch/IResearchFilterFactory.cpp
  tests/IResearch/IResearchFilterFunction-test.cpp
  tests/js/server/aql/aql-parse.js
Labels: 3 AQL, 3 Optimizer

#14523 [3.8] Fix duplicate log id in ExecutionBlockImpl
  arangod/Aql/ExecutionBlockImpl.cpp
  utils/checkLogIds.py
Labels: 3 - Testing, 3 Build

#14380 [3.8] lower takeover leadership current log level
  CHANGELOG
  arangod/Cluster/FollowerInfo.cpp
Labels: 3 Cluster

#14534 Improve query memory usage tracking for graph operations
  CHANGELOG
  arangod/Graph/AttributeWeightShortestPathFinder.cpp
  arangod/Graph/AttributeWeightShortestPathFinder.h
  arangod/Graph/Cache/RefactoredClusterTraverserCache.cpp
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
  arangod/Graph/ConstantWeightShortestPathFinder.cpp
  arangod/Graph/ConstantWeightShortestPathFinder.h
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  arangod/Graph/PathManagement/PathStore.cpp
  arangod/Graph/Providers/SingleServerProvider.cpp
  arangod/Graph/ShortestPathResult.h
  tests/js/server/aql/aql-memory-limit.js
Labels: 3 AQL, 3 Graph, 9 Ready to Merge

#14537 [3.8] Fix BTS-527
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
Labels: 1 Bug, 3 Cluster, Team Clifton

#14526 Improve startup file copying of JavaScript files
  CHANGELOG
  arangod/V8Server/V8DealerFeature.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/files.cpp
  lib/Basics/files.h
  lib/Basics/operating-system.h
  tests/js/client/server_parameters/test-copy-installation.js
Labels: 3 Packaging, 9 Ready to Merge

#14553 attempt to pacify clang-1100
  arangod/Graph/Enumerators/TwoSidedEnumerator.h
Labels: 3 Build, 3 Packaging, 4 MacOSX

#14558 CHANGELOG entry
  CHANGELOG
Labels: 3 Documentation

#14557 do not use -n on echo, this might not be supported and is not necessary
  CHANGELOG
Labels: 1 Bug, 3 ImportExport, 4 MacOSX

#14561 do not use -n on echo, this might not be supported and is not necessary (3.6)
  CHANGELOG
Labels: 1 Bug, 3 ImportExport, 4 MacOSX

#14562 do not use -n on echo, this might not be supported and is not necessary (3.7)
  CHANGELOG
Labels: 1 Bug, 3 ImportExport, 4 MacOSX

#14524 [3.7] Fix duplicate log id in ExecutionBlockImpl
  arangod/Aql/ExecutionBlockImpl.cpp
  utils/checkLogIds.py
Labels: 3 - Testing, 3 Build

#14536 [3.7] Fix BTS-527
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
Labels: 1 Bug, 3 Cluster, Team Clifton

#14528 Improve startup file copying of JavaScript files
  CHANGELOG
  arangod/V8Server/V8DealerFeature.cpp
  tests/js/client/server_permissions/test-copy-installation.js
Labels: 9 Ready to Merge

#14527 Improve startup file copying of JavaScript files
  CHANGELOG
  arangod/V8Server/V8DealerFeature.cpp
  tests/js/client/server_parameters/test-copy-installation.js
Labels: 3 Packaging, 9 Ready to Merge

#14559 CHANGELOG entry
  CHANGELOG
Labels: 3 Documentation

#14569 timely update of database servers in cluster cache
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
Labels: 1 Bug, 3 Cluster

#14570 [3.8] timely update of database servers in cluster cache
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
Labels: 1 Bug, 3 Cluster

#14454 Add test cases for _admin/metrics/v2 endpoint in cluster mode (3.8)
  README_maintainers.md
  js/client/modules/@arangodb/testsuites/aql.js
  tests/js/client/shell/shell-promtool-cluster.js
Labels: 3 - Testing, 3 Metrics, DO_NOT_MERGE

#14446 Add test cases for _admin/metrics/v2 endpoint in cluster mode
  README_maintainers.md
  js/client/modules/@arangodb/testsuites/aql.js
  tests/js/client/shell/shell-promtool-cluster.js
Labels: 3 - Testing, 3 Metrics
