Repository arangodb/arangodb, pull requests merged in 2021-09, with the labels that each got.

#14709 Fix a rare shutdown race in RocksDBShaCalculatorThread
  CHANGELOG
  arangod/RocksDBEngine/Listeners/RocksDBShaCalculator.cpp
  arangod/RocksDBEngine/Listeners/RocksDBShaCalculator.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 3 RocksDB

#14715 Bug fix 3.8/fix typed analyzer pooling
  CHANGELOG
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  tests/IResearch/IResearchDocument-test.cpp
Labels: 3 ArangoSearch

#14724 Bug fix 3.8/search 238 late materialization with constrained heap (#14722)
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
  tests/js/server/aql/aql-queries-optimizer-limit-cluster.js
Labels: 3 ArangoSearch

#14732 Bug fix 3.8/mac 10 4
  arangod/Graph/ConstantWeightShortestPathFinder.h
  lib/Basics/operating-system.h
Labels: 3 Build, 4 MacOSX, 3 Packaging

#14733 fix for old clang
  arangod/Graph/ConstantWeightShortestPathFinder.h
  lib/Basics/operating-system.h
Labels: 3 Build, 4 MacOSX, 3 Packaging

#14707 protoype for forceOneShardAttributeValue
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/QueryOptions.cpp
  arangod/Aql/QueryOptions.h
  arangod/Aql/ShardLocking.cpp
Labels: 3 Cluster, 3 Optimizer, 9 Ready to Merge

#14712 workaround for assertion failure
  arangod/RocksDBEngine/RocksDBWalAccess.cpp
  arangod/RocksDBEngine/RocksDBWalAccess.h
  tests/js/server/replication/static/replication-static.js
Labels: 3 ImportExport

#14719 [3.7] move shards with no time limit instead cancellation
  CHANGELOG
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminClusterHandler.h
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/MoveShardTest.cpp
  tests/js/server/resilience/move/moving-shards-cluster.js
Labels: 3 Cluster, 9 Ready to Merge

#14671 [3.7] BTS-356 cluster internal errors
  3rdParty/fuerte/include/fuerte/types.h
  arangod/Agency/AsyncAgencyComm.cpp
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterTraverser.cpp
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/ClusterEngine/RocksDBMethods.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/Graph/ShortestPathFinder.cpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/Network/Methods.cpp
  arangod/Network/Methods.h
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Worker.cpp
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/RestHandler/RestImportHandler.cpp
  arangod/Sharding/ShardDistributionReporter.cpp
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  arangod/V8Server/v8-actions.cpp
  arangod/VocBase/Methods/Queries.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Basics/voc-errors.cpp
  lib/Basics/voc-errors.h
  lib/Rest/CommonDefines.h
  lib/Rest/GeneralResponse.cpp
  tests/AsyncAgencyComm/AsyncAgencyCommTest.cpp
  tests/Network/MethodsTest.cpp
  tests/js/client/server_parameters/exclusive-collections-on.js
  tests/js/client/shell/shell-document-api-internal-http-return-codes-cluster.js
Labels: 3 Cluster

#14735 Bug-Fix 3.7: EE only. Cluster One Shard rule did not handle Satellite collections on views
  CHANGELOG
Labels: 1 Bug, 3 Cluster, 3 ArangoSearch

#14742 Bug fix 3.8/allow for long supervision job runtimes
  CHANGELOG
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminClusterHandler.h
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/MoveShardTest.cpp
  tests/js/server/resilience/move/moving-shards-cluster.js
Labels: 3 Cluster

#14768 Update OpenSSL to 1.1.1l and OpenLDAP to 2.4.59
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#14769 Update OpenSSL to 1.1.1l and OpenLDAP to 2.4.59
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#14770 Update OpenSSL to 1.1.1l and OpenLDAP to 2.4.59
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#14772 Fixed issue #14720
  CHANGELOG
  arangod/RestHandler/RestImportHandler.cpp
  tests/rb/HttpInterface/api-import-spec.rb
Labels: 3 API, 3 ImportExport

#14778 Reduce nr of combinations and runtime of nightly chaos load tests.
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: 9 Ready to Merge, 3 - Testing

#14791 Avoid acquisition of recursive read lock on server shutdown
  CHANGELOG
  arangod/Replication/GlobalInitialSyncer.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
Labels: 9 Ready to Merge

#14794 fix logId check
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/Worker.cpp
  utils/checkLogIds.py
Labels: 9 Ready to Merge, 3 - Testing

#14797 add missing initialization to OperationOptions flag
  arangod/Utils/OperationOptions.cpp
Labels: 3 AQL, 9 Ready to Merge

#14799 prevent stealing of values from Aql const registers
  CHANGELOG
  arangod/Aql/InputAqlItemRow.cpp
  tests/js/client/shell/shell-query-dbserver-cluster.js
Labels: 3 Optimizer, 9 Ready to Merge

#14801 Fixed BTS-562
  CHANGELOG
  arangod/Aql/AttributeNamePath.cpp
  tests/js/server/aql/aql-optimizer-rule-reduce-extraction-to-projection.js
Labels: 3 Optimizer, 9 Ready to Merge

#14809 Stabilize Hybrid Smart Graph Test [EE only]
  js/server/modules/@arangodb/test-helper.js
Labels: 1 Bug

#14780 Fix BTS-548 array index wrong optimization
  CHANGELOG
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/server/shell/shell-array-index-noncluster.js
Labels: 3 Optimizer

#14810 Make all synchronous transaction methods set skipScheduler for network requests
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/Cluster/ClusterTrxMethods.h
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/Transaction/MethodsApi.h
Labels: 9 Ready to Merge

#14789 fixed TRI_ASSERT warnings
  arangod/Aql/CostEstimate.cpp
  arangod/Replication2/Streams/StreamInformationBlock.tpp
  lib/Basics/ReadWriteSpinLock.cpp
Labels: 3 Build

#14824 Fix crash in optimizer rule remove-collect-variables
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AstHelper.cpp
  arangod/Aql/AstHelper.h
  arangod/Aql/CollectNode.cpp
  arangod/Aql/CollectNode.h
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Labels: 1 Bug, 3 AQL, 3 Optimizer

#14813 [3.8] Make all synchronous transaction methods set skipScheduler for network requests
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/Cluster/ClusterTrxMethods.h
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/Transaction/MethodsApi.h
Labels: 3 API, 9 Ready to Merge, 3 Transaction

#14825 [3.8] Fix crash in optimizer rule remove-collect-variables
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Labels: 1 Bug, 3 AQL, 3 Optimizer, 9 Ready to Merge

#14753 enterprise license support
  CHANGELOG
  Documentation/Metrics/arangodb_license_expires.yaml
  arangod/Agency/Node.cpp
  arangod/Agency/Store.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
  arangod/GeneralServer/GeneralServerFeature.cpp
  js/client/modules/@arangodb/arango-database.js
  js/client/modules/@arangodb/testsuites/license.js
  js/common/bootstrap/errors.js
  lib/Basics/error-registry.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.h
  lib/Logger/LogTopic.cpp
  lib/Logger/Logger.h
  tests/Auth/UserManagerClusterTest.cpp
  tests/Auth/UserManagerTest.cpp
  tests/Graph/FifoQueueTest.cpp
  tests/Graph/LifoQueueTest.cpp
  tests/Graph/WeightedQueueTest.cpp
  tests/Mocks/Servers.cpp
  utils/generateAllMetricsDocumentation.py
Labels: 9 Ready to Merge

#14826 [3.7] Fix crash in optimizer rule remove-collect-variables
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Labels: 1 Bug, 3 AQL, 3 Optimizer, 9 Ready to Merge

#14831 fixed issue #14819
  CHANGELOG
  arangod/Aql/DocumentProducingNode.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  arangod/Aql/LateMaterializedOptimizerRulesCommon.h
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
Labels: 1 Bug, 3 AQL, 3 Optimizer, 9 Ready to Merge

#14832 fixed issue #14819
  CHANGELOG
  arangod/Aql/DocumentProducingNode.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
Labels: 1 Bug, 3 AQL, 3 Optimizer, 9 Ready to Merge

#14731 attempt to first uninstall the old service on silent upgrade as well
  CHANGELOG
  Installation/Windows/Templates/NSIS.template.in
  cmake/packages/client/nsis.txt
Labels: 4 Windows, 3 Packaging

#14838 Bug fix/dont start license feature in upgrade
  CHANGELOG
  arangod/RestServer/UpgradeFeature.h
Labels: 1 Bug, 3 Upgrade, License

#14840 3.7: attempt to first uninstall the old service on silent upgrade as well
  CHANGELOG
  Installation/Windows/Templates/NSIS.template.in
  cmake/packages/client/nsis.txt
Labels: 4 Windows, 3 Packaging

#14839 3.8: attempt to first uninstall the old service on silent upgrade as well
  CHANGELOG
  Installation/Windows/Templates/NSIS.template.in
  cmake/packages/client/nsis.txt
Labels: 4 Windows, 3 Packaging
