Repository arangodb/arangodb, pull requests merged in 2021-01, with the labels that each got.

#13107 clean up callbacks and empty promises in single host agency
  CHANGELOG
  arangod/Agency/Agent.cpp
Labels: DO_NOT_MERGE

#13320 tzdata 2020f + DATE_TIMEZONE(S)
  3rdParty/CMakeLists.txt
  3rdParty/tzdata/Makefile
  3rdParty/tzdata/NEWS
  3rdParty/tzdata/README
  3rdParty/tzdata/africa
  3rdParty/tzdata/antarctica
  3rdParty/tzdata/asia
  3rdParty/tzdata/australasia
  3rdParty/tzdata/backward
  3rdParty/tzdata/backzone
  3rdParty/tzdata/etcetera
  3rdParty/tzdata/europe
  3rdParty/tzdata/leap-seconds.list
  3rdParty/tzdata/leapseconds
  3rdParty/tzdata/leapseconds.awk
  3rdParty/tzdata/northamerica
  3rdParty/tzdata/pacificnew
  3rdParty/tzdata/southamerica
  3rdParty/tzdata/systemv
  3rdParty/tzdata/theory.html
  3rdParty/tzdata/version
  3rdParty/tzdata/windowsZones.xml
  3rdParty/tzdata/yearistype.sh
  3rdParty/tzdata/ziguard.awk
  3rdParty/tzdata/zishrink.awk
  3rdParty/tzdata/zone.tab
  3rdParty/tzdata/zone1970.tab
  3rdParty/tzdata/zoneinfo2tdf.pl
  CHANGELOG
  LICENSES-OTHER-COMPONENTS.md
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  js/apps/system/_admin/aardvark/APP/react/public/assets/src/mode-aql.js
  tests/js/server/aql/aql-functions-date.js
Labels: 9 Ready to Merge

#13317 Update OpenSSL to 1.1.1i and OpenLDAP to 2.4.56
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#13319 Update OpenSSL to 1.1.1i and OpenLDAP to 2.4.56 (3.7)
  CHANGELOG
  CMakeLists.txt
  VERSIONS
Labels: OpenSSL

#13318 Update OpenSSL to 1.1.1i and OpenLDAP to 2.4.56 (3.6)
  CHANGELOG
  CMakeLists.txt
  VERSIONS
Labels: OpenSSL

#13302 Port minichaos agency restart fix to 3.6
  CHANGELOG
  arangod/Agency/State.cpp
  arangod/Agency/State.h
Labels: 3 Cluster

#13325 store sharding attribute for databases on db servers
  arangod/Cluster/Maintenance.cpp
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/VocbaseInfo.cpp
  arangod/VocBase/VocbaseInfo.h
  tests/js/common/shell/shell-one-shard.js
Labels: 9 Ready to Merge

#13345 UnpackTuple VPack
  3rdParty/velocypack/include/velocypack/Exception.h
  3rdParty/velocypack/include/velocypack/Iterator.h
  3rdParty/velocypack/include/velocypack/Slice.h
  3rdParty/velocypack/src/Exception.cpp
  lib/Basics/VelocyPackHelper.h
Labels: 9 Ready to Merge

#13343 fix spurious error in shell-pregel.js test suite
  tests/js/common/shell/shell-pregel.js
Labels: 9 Ready to Merge

#13308 Bug fix/issue 13099
  CHANGELOG
  arangod/Aql/AqlCallStack.h
  arangod/Aql/AqlItemBlockInputMatrix.cpp
  arangod/Aql/AqlItemBlockInputMatrix.h
  arangod/Aql/AqlItemBlockInputRange.cpp
  arangod/Aql/AqlItemBlockInputRange.h
  arangod/Aql/AqlItemMatrix.cpp
  arangod/Aql/AqlItemMatrix.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/MultiAqlItemBlockInputRange.cpp
  arangod/Aql/MultiAqlItemBlockInputRange.h
  arangod/Aql/MultiDependencySingleRowFetcher.cpp
  arangod/Aql/MultiDependencySingleRowFetcher.h
  arangod/Cluster/ClusterInfo.cpp
  tests/Aql/AqlSharedExecutionBlockImplTest.cpp
  tests/Aql/ExecutionBlockImplTest.cpp
  tests/CMakeLists.txt
  tests/Mocks/Servers.cpp
  tests/Mocks/Servers.h
  tests/js/server/aql/aql-subquery-splicing-regression.js
  tests/js/server/aql/aql-subquery.js
Labels: 1 Bug

#13324 Fixed DOCUMENT method in one-shard database
  CHANGELOG
  arangod/Transaction/Methods.cpp
Labels: 1 Bug

#13327 (3.7) Only run Test in Enterprise mode
  tests/js/client/communication/test-communication.js
Labels: 3 - Testing

#13328 store sharding attribute for databases on db servers
  arangod/Cluster/Maintenance.cpp
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/VocbaseInfo.h
  tests/js/common/shell/shell-one-shard.js
Labels: 9 Ready to Merge

#13344 fix spurious error in shell-pregel.js test suite
  tests/js/common/shell/shell-pregel.js
Labels: 3 - Testing, 9 Ready to Merge

#13346 more granular error reporting in Maintenance
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/SynchronizeShard.cpp
Labels: 9 Ready to Merge

#13380 fix a memleak that only happened during gtest execution
  tests/Network/ConnectionPoolTest.cpp
Labels: 3 - Testing, ASan

#13382 fix potential invalid derefence on audit log shutdown
  CHANGELOG
  lib/Logger/LogAppenderFile.cpp
Labels: ASan

#13388 Bug fix 3.6.11/fix potential leak in ast node repurposing
  CHANGELOG
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
Labels: ASan

#13404 arangodump: Shard-parallelism and smaller dumps
  CHANGELOG
  arangod/Graph/Enumerators/TwoSidedEnumerator.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangosh/Dump/DumpFeature.cpp
  arangosh/Dump/DumpFeature.h
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Restore/RestoreFeature.h
  arangosh/Utils/ClientTaskQueue.h
  arangosh/Utils/ManagedDirectory.cpp
  arangosh/Utils/ManagedDirectory.h
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testutils/process-utils.js
  tests/js/client/shell/shell-dump-integration.js
  tests/js/client/shell/shell-restore-integration.js
  tests/js/server/dump/dump-check-dump-files-uncompressed-no-envelopes.js
Labels: 9 Ready to Merge

#13363 fix shutdown deadlock
  CHANGELOG
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/CreateDatabase.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/Mocks/Servers.cpp
  tests/Mocks/Servers.h
  tests/js/client/shell/shell-create-database-failure-cluster.js
Labels: 9 Ready to Merge

#13366 print client/server version mismatch in arangosh
  CHANGELOG
  js/client/client.js
Labels: 3 Arangosh, 9 Ready to Merge

#13395 add missing sentence to documentation
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
Labels: 3 Documentation, 9 Ready to Merge

#13399 add AQL bit handling functions (#13332)
  CHANGELOG
  arangod/Aql/Aggregator.cpp
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  arangod/Aql/tokens.cpp
  arangod/Aql/tokens.ll
  arangod/Transaction/Context.h
  arangod/Transaction/Methods.h
  js/apps/system/_admin/aardvark/APP/react/build/assets/src/mode-aql.js
  tests/Aql/BitFunctionsTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-extended-numeric-literals.js
  tests/js/server/aql/aql-optimizer-collect-aggregate.js
Labels: 3 AQL, 3 Optimizer

#13403 blocklist a new test for devel
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing, 9 Ready to Merge

#13402 blocklist a new test for devel
  UnitTests/OskarTestSuitesBlackList
Labels: 3 - Testing, 9 Ready to Merge

#13412 Fix some issues with key generators not properly taking into account …
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  arangod/VocBase/KeyGenerator.cpp
  arangod/VocBase/KeyGenerator.h
  tests/js/common/shell/shell-keygen.js
Labels: 9 Ready to Merge

#13413 Fix some issues with key generators not properly taking into account …
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  arangod/VocBase/KeyGenerator.cpp
  arangod/VocBase/KeyGenerator.h
  tests/js/common/shell/shell-keygen.js
Labels: 9 Ready to Merge

#13313 Bug fix 3.7/oasis 409
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/IResearch/IResearchCommon.cpp
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchLinkHelper.h
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/IResearchRocksDBLink.cpp
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/RestHandler/RestDebugHandler.cpp
  arangod/RestServer/ScriptFeature.cpp
  arangosh/Shell/ShellFeature.cpp
  arangosh/Shell/ShellFeature.h
  arangosh/Shell/V8ShellFeature.cpp
  arangosh/Shell/V8ShellFeature.h
  js/client/bootstrap/modules/internal.js
  js/client/modules/@arangodb/test-utils.js
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  tests/IResearch/IResearchDocument-test.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchLinkMeta-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/Mocks/IResearchLinkMock.cpp
  tests/Mocks/Servers.cpp
  tests/Mocks/Servers.h
  tests/js/server/recovery/view-arangosearch-link-populate.js
  tests/js/server/recovery/view-arangosearch-link-rename-collection-no-flushthread-noncluster.js
  tests/js/server/recovery/view-arangosearch-link-rename-collection-noncluster.js
  tests/js/server/recovery/view-arangosearch-rename-no-flushthread-noncluster.js
  tests/js/server/recovery/view-arangosearch-rename-noncluster.js
  tests/js/server/recovery/view-arangosearch-rename-query-noncluster.js
  tests/js/server/recovery/view-arangosearch-rename-recreate-flush-noncluster.js
  tests/js/server/recovery/view-arangosearch-rename-recreate-noncluster.js
Labels: 1 Bug, 3 ArangoSearch

#13419 Error reporting for hotbackup restore
  CHANGELOG
Labels: 3 ImportExport

#13351 [3.7] Prepare register planning for rolling upgrades
  CHANGELOG
  arangod/Aql/RegisterPlan.cpp
Labels: 3 Upgrade, 9 Ready to Merge

#13371 Avoid removeFollower cycle
  CHANGELOG
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  tests/Agency/SupervisionTest.cpp
Labels: 3 Cluster

#13407 Docs: Fix collection truncate DocuBlock
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_truncate.md
Labels: 3 Documentation, 9 Ready to Merge

#13416 fix decoding of values in `padded` key generator
  CHANGELOG
  arangod/VocBase/KeyGenerator.cpp
  arangod/VocBase/KeyGenerator.h
  tests/CMakeLists.txt
  tests/VocBase/KeyGenerator-test.cpp
Labels: 3 ImportExport, 3 Index

#13418 Error reporting for hotbackup restore
  CHANGELOG
Labels: 3 ImportExport

#13422 fix a test-only memleak
  tests/Aql/BitFunctionsTest.cpp
Labels: 3 - Testing

#13424 Make `padded` and `autoincrement` key generators export their `lastVa…
  CHANGELOG
  arangod/VocBase/KeyGenerator.cpp
  tests/js/client/shell/shell-dump-integration.js
  tests/js/client/shell/shell-restore-integration.js
  tests/js/common/shell/shell-keygen.js
Labels: 3 ImportExport

#13425 Make `padded` and `autoincrement` key generators export their `lastValue` values, so that they are available in dumps and can be restored elsewhere from a dump.
  CHANGELOG
  arangod/VocBase/KeyGenerator.cpp
  tests/js/client/shell/shell-dump-integration.js
  tests/js/client/shell/shell-restore-integration.js
  tests/js/common/shell/shell-keygen.js
Labels: 3 ImportExport, 3 Index

#13378 Feature/read write metrics
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/RestAgencyHandler.cpp
  arangod/GeneralServer/GeneralCommTask.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/H2CommTask.h
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/HttpCommTask.h
  arangod/GeneralServer/VstCommTask.cpp
  arangod/GeneralServer/VstCommTask.h
  arangod/RestServer/Metrics.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Statistics/RequestStatistics.h
  arangod/Statistics/ServerStatistics.cpp
  arangod/Statistics/ServerStatistics.h
  tests/Metrics/MetricsTest.cpp
Labels: 1 Feature, 9 Ready to Merge

#13430 Bug in behaviour of ignoreRevs=false
  CHANGELOG
  arangod/RestHandler/RestDocumentHandler.cpp
  tests/rb/HttpInterface/api-document-update-spec.rb
Labels: 3 API

#13431 Bug in behaviour of ignoreRevs=false
  CHANGELOG
  arangod/RestHandler/RestDocumentHandler.cpp
  tests/rb/HttpInterface/api-document-update-spec.rb
Labels: 3 API

#13439 normalize directory names before chopping it into pieces (#13406)
  CHANGELOG
  arangosh/Dump/DumpFeature.cpp
  arangosh/Export/ExportFeature.cpp
  arangosh/Import/ImportFeature.cpp
  arangosh/Restore/RestoreFeature.cpp
  lib/Basics/files.cpp
  lib/Basics/files.h
Labels: 9 Ready to Merge

#13446 Fixed a too eager fast forwarding in ID executor.
  arangod/Aql/AqlItemBlockInputRange.cpp
  arangod/Aql/AqlItemBlockInputRange.h
  arangod/Aql/IdExecutor.cpp
  tests/Aql/IdExecutorTest.cpp
Labels: 1 Bug

#13444 Feature/make read write metrics optional
  CHANGELOG
  arangod/RestServer/MetricsFeature.cpp
  arangod/RestServer/MetricsFeature.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/Statistics/ServerStatistics.cpp
  arangod/Statistics/ServerStatistics.h
  tests/js/client/server_parameters/test-export-document-metrics-off-noncluster.js
  tests/js/client/server_parameters/test-export-document-metrics-on-noncluster.js
Labels: 1 Feature

#13440 StringUtils concat and join
  lib/Basics/StringUtils.h
  tests/Basics/StringUtilsTest.cpp
Labels: 9 Ready to Merge

#13452 Set CLEAN_NO_CUSTOM for some directories
  CMakeLists.txt
  Documentation/CMakeLists.txt
  arangod/CMakeLists.txt
Labels: 9 Ready to Merge
