Repository arangodb/arangodb, pull requests merged in 2021-05, with the labels that each got.

#14116 add diagnostics to Merkle tree
  arangod/RocksDBEngine/RocksDBTransactionState.h
  lib/Containers/MerkleTree.cpp
  lib/Containers/MerkleTree.h
  tests/Containers/MerkleTreeTest.cpp
Labels: 9 Ready to Merge

#14094 [3.8] starting up shard leader and response to writes
  CHANGELOG
  arangod/Cluster/FollowerInfo.h
  arangod/Transaction/Methods.cpp
Labels: 1 Bug, 3 Cluster

#14112 Fix move after free bug in connection pool
  CHANGELOG
  arangod/Network/ConnectionPool.cpp
Labels: 1 Bug

#14113 Fix move after free bug in connection pool
  CHANGELOG
  arangod/Network/ConnectionPool.cpp
Labels: 1 Bug

#14093 starting up shard leader and response to writes
  CHANGELOG
  arangod/Cluster/FollowerInfo.h
  arangod/Transaction/Methods.cpp
Labels: 1 Bug, 3 Cluster

#14133 fixed issue BTS-354
  CHANGELOG
  arangod/Aql/Collection.cpp
  arangod/Aql/Collection.h
Labels: 9 Ready to Merge

#14104 Fix DEVSUP-749: Fix potential deadlock
  CHANGELOG
  arangod/RocksDBEngine/RocksDBCollection.cpp
  lib/Basics/RecursiveLocker.h
  tests/Basics/RecursiveLockerTest.cpp
  tests/CMakeLists.txt
  tests/js/server/shell/shell-index-link-parallel-drop-create.js
Labels: 9 Ready to Merge

#14136 [3.8] coordinators isbuilding removal error handling
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  tests/js/common/shell/shell-cluster-collection.js
Labels: 3 Cluster

#14065 improve performance in case of conflicts in batch CRUD operation (#14…
  CHANGELOG
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  arangod/RocksDBEngine/RocksDBFulltextIndex.cpp
  arangod/RocksDBEngine/RocksDBFulltextIndex.h
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.h
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.h
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/RocksDBEngine/RocksDBTtlIndex.cpp
  arangod/RocksDBEngine/RocksDBTtlIndex.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
Labels: 9 Ready to Merge

#14127 Fixed issue #14122
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-graph-traverser.js
Labels: 1 Bug, 3 Optimizer

#14143 Improve exception safety for maintenance thread & shard unlocking
  CHANGELOG
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/ActionBase.h
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/CreateCollection.h
  arangod/Cluster/DropCollection.cpp
  arangod/Cluster/DropCollection.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceWorker.cpp
  arangod/Cluster/ResignShardLeadership.cpp
  arangod/Cluster/ResignShardLeadership.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/SynchronizeShard.h
  arangod/Cluster/TakeoverShardLeadership.cpp
  arangod/Cluster/TakeoverShardLeadership.h
  arangod/Cluster/UpdateCollection.cpp
  arangod/Cluster/UpdateCollection.h
Labels: 3 Cluster

#14074 Bug fix/collection not available during start up
  CHANGELOG
  arangod/Auth/UserManager.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/H2CommTask.h
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/HttpCommTask.h
  arangod/GeneralServer/VstCommTask.cpp
  arangod/RestServer/BootstrapFeature.cpp
  arangod/RestServer/BootstrapFeature.h
  arangod/RestServer/UpgradeFeature.cpp
  js/common/bootstrap/errors.js
  js/server/server.js
  lib/Basics/error-registry.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.h
  lib/Rest/GeneralResponse.cpp
  tests/js/client/authentication/auth.js
Labels: 3 Cluster

#14155 bug-fix/internal-issue-#700-1
  3rdParty/iresearch/core/formats/formats_10.cpp
Labels: 3 ArangoSearch

#14148 Improve "Shards" view in web UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/shardsView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/shardsView.js
Labels: 3 UI

#14029 Bug fix/fix tsan issues
  3rdParty/iresearch/core/index/index_writer.hpp
  3rdParty/iresearch/core/utils/object_pool.hpp
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/AsyncAgencyComm.h
  arangod/Agency/Supervision.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryContext.h
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/GeneralServer/AcceptorTcp.cpp
  arangod/GeneralServer/AcceptorTcp.h
  arangod/GeneralServer/AcceptorUnixDomain.cpp
  arangod/GeneralServer/AcceptorUnixDomain.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/Network/NetworkFeature.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/Worker.h
  arangod/RestServer/Metrics.h
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/Sharding/ShardingInfo.h
  arangod/Utils/Cursor.h
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/LogicalDataSource.h
  arangosh/Shell/V8ClientConnection.h
  tsan_arangodb_suppressions.txt
Labels: DO_NOT_MERGE

#14154 Make sure _recoveryManagerPtr is initialized correctly.
  arangod/Pregel/PregelFeature.h
Labels: 9 Ready to Merge

#14126 Fixed issue #14122
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-graph-traverser.js
Labels: 1 Bug, 3 Optimizer, 9 Ready to Merge

#14124 Fixed issue #14122
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-graph-traverser.js
Labels: 3 AQL, 3 Optimizer, 9 Ready to Merge

#14158 bug-fix-3.8/internal-issue-#700-1 (#14155)
  3rdParty/iresearch/core/formats/formats_10.cpp
Labels: 3 ArangoSearch

#14153 Fix bugs in fuerte with H2 and VST connections
  3rdParty/fuerte/include/fuerte/connection.h
  3rdParty/fuerte/src/GeneralConnection.h
  3rdParty/fuerte/src/H2Connection.h
  CHANGELOG
Labels: 9 Ready to Merge

#14149 [3.8] clear current entries of overriden plan entries by hot restore
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  js/client/modules/@arangodb/testsuites/dump.js
  tests/js/server/dump/dump-move-shard.js
Labels: 1 Bug, 3 ImportExport, 9 Ready to Merge

#14161 clear current entries of overriden plan entries by hot restore
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  js/client/modules/@arangodb/testsuites/dump.js
  tests/js/server/dump/dump-move-shard.js
Labels: 1 Bug, 3 Cluster, 3 ImportExport, 9 Ready to Merge

#14162 [3.7] clear current entries of overriden plan entries by hot restore
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangosh/Shell/V8ClientConnection.cpp
  js/client/modules/@arangodb/testsuites/dump.js
  tests/js/server/dump/dump-move-shard.js
Labels: 1 Bug, 3 Cluster, 3 ImportExport

#14145 Minor cleanup
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/RegisterId.h
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/WindowNode.cpp
  arangod/CMakeLists.txt
  arangod/Cluster/RebootTracker.cpp
  arangod/IResearch/GeoFilter.cpp
  arangod/Pregel/Worker-templates-algorithms.cpp
  arangod/Pregel/Worker.cpp
  arangod/RestServer/RestartAction.cpp
  arangod/RestServer/RestartAction.h
  arangod/RestServer/UpgradeFeature.cpp
  arangod/RestServer/arangod.cpp
  arangod/StorageEngine/TransactionState.cpp
  lib/Basics/debugging.h
  lib/CMakeLists.txt
  tests/CMakeLists.txt
  tests/Graph/MockGraph.cpp
  tests/main.cpp
Labels: 9 Ready to Merge

#14174 Fix operator<< lookup
  arangod/Cluster/ClusterTypes.cpp
  arangod/Cluster/ClusterTypes.h
  arangod/Cluster/RebootTracker.cpp
  arangod/Transaction/Status.cpp
  arangod/Transaction/Status.h
  lib/Basics/AttributeNameParser.cpp
  lib/Basics/AttributeNameParser.h
  lib/Basics/Identifier.cpp
  lib/Basics/Identifier.h
  lib/Basics/Result.cpp
  lib/Basics/Result.h
  lib/Basics/debugging.h
Labels: 9 Ready to Merge

#14168 Bug fix 3.8/pregel lifetime management
  CHANGELOG
  arangod/Aql/Functions.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/AlgoRegistry.h
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/Worker.cpp
  arangod/Pregel/Worker.h
  arangod/RestHandler/RestControlPregelHandler.cpp
  arangod/RestHandler/RestControlPregelHandler.h
  arangod/RestHandler/RestPregelHandler.cpp
  arangod/RestHandler/RestPregelHandler.h
  arangod/V8Server/v8-collection.cpp
Labels: 3 Pregel

#14179 Docs: Cast response.body from Buffer to string
  js/client/bootstrap/modules/internal.js
Labels: 3 Documentation

#14190 fixed issue BTS-354 (#14133)
  CHANGELOG
  arangod/Aql/Collection.cpp
  arangod/Aql/Collection.h
Labels: 3 Cluster

#14188 [3.7] correctly report shutdown as shard leader
  CHANGELOG
  arangod/Aql/Collection.cpp
  arangod/Aql/Collection.h
  arangod/Transaction/Methods.cpp
Labels: 1 Bug, 3 Cluster

#14186 [3.8] correctly report shutdown as shard leader
  CHANGELOG
  arangod/Transaction/Methods.cpp
Labels: 1 Bug, 3 Cluster

#14177 Bug fix3.8/window operation issues
  CHANGELOG
  arangod/Aql/Functions.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/WindowNode.cpp
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  js/common/modules/@arangodb/aql/explainer.js
  lib/Basics/datetime.cpp
  tests/js/server/aql/aql-window-cumulative-sum.js
  tests/js/server/aql/aql-window-malarkey.js
Labels: 3 AQL, 3 Optimizer

#14194 Fix index range calculation for queries where both bounds are expressed using the same operator.
  CHANGELOG
  arangod/Aql/Condition.cpp
  arangod/Indexes/SortedIndexAttributeMatcher.cpp
  arangod/Indexes/SortedIndexAttributeMatcher.h
  tests/js/server/aql/aql-index-choice.js
Labels: 3 Index, 3 Optimizer

#14196 Fix index range calculation for queries where both bounds are expressed using the same operator.
  CHANGELOG
  arangod/Aql/Condition.cpp
  arangod/Indexes/SortedIndexAttributeMatcher.cpp
  arangod/Indexes/SortedIndexAttributeMatcher.h
  tests/js/server/aql/aql-index-choice.js
Labels: 3 Index, 3 Optimizer

#14187 correctly report shutdown as shard leader
  CHANGELOG
  arangod/Transaction/Methods.cpp
Labels: 1 Bug, 3 Cluster

#14185 Feature/redirect root
  CHANGELOG
  arangod/Actions/RestActionHandler.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.h
  tests/js/client/server_parameters/http-permanently-redirect-root-off.js
  tests/js/client/server_parameters/http-permanently-redirect-root-on.js
  tests/js/client/server_parameters/http-redirect-root-to-301.js
  tests/js/client/server_parameters/http-redirect-root-to-302.js
Labels: 3 API

#14178 Weighted Traversal negative edges
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Graph/TraverserOptions.cpp
  js/common/bootstrap/errors.js
  lib/Basics/error-registry.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.h
  tests/js/server/aql/aql-graph-weighted-traversal.js
Labels: 3 Graph

#14173 Throw an exception when a negative edge weight is detected.
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Graph/TraverserOptions.cpp
  js/common/bootstrap/errors.js
  lib/Basics/error-registry.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.h
  tests/js/server/aql/aql-graph-weighted-traversal.js
Labels: 3 Graph

#14198 fix metrics names
  Documentation/Metrics/arangodb_aql_global_query_memory_limit_reached_total.yaml
  Documentation/Metrics/arangodb_aql_local_query_memory_limit_reached_total.yaml
  arangod/RestServer/QueryRegistryFeature.cpp
  tests/js/client/server_parameters/test-global-memory-limit.js
  tests/js/client/server_parameters/test-memory-limit.js
Labels: 3 Metrics

#14199 fix metrics names
  CHANGELOG
  Documentation/Metrics/arangodb_aql_global_query_memory_limit_reached_total.yaml
  Documentation/Metrics/arangodb_aql_local_query_memory_limit_reached_total.yaml
  arangod/RestServer/QueryRegistryFeature.cpp
  tests/js/client/server_parameters/test-global-memory-limit.js
  tests/js/client/server_parameters/test-memory-limit.js
Labels: 3 Metrics

#14180 Docs: Cast response.body from Buffer to string
  js/client/bootstrap/modules/internal.js
Labels: 3 Documentation

#13976 Add experimental asynchronous prefetching
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlItemBlock.h
  arangod/Aql/AqlItemBlockInputMatrix.cpp
  arangod/Aql/AqlItemBlockInputMatrix.h
  arangod/Aql/AqlItemBlockInputRange.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/Optimizer.cpp
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/SharedAqlItemBlockPtr.h
Labels: 9 Review Required

#14211 Allow make to find its jobserver again
  3rdParty/V8/CMakeLists.txt
  3rdParty/jemalloc/CMakeLists.txt
  3rdParty/libunwind/CMakeLists.txt
Labels: 9 Ready to Merge

#14213 Check return value flow of metrics YAML generator
  utils/generateAllMetricsDocumentation.py
Labels: 3 Build, 3 Documentation, 3 Metrics

#14209 SEARCH-7
  3rdParty/iresearch/core/search/bm25.cpp
  3rdParty/iresearch/core/search/disjunction.hpp
  3rdParty/iresearch/tests/resources/v_DSS_Entity_id.json
  3rdParty/iresearch/tests/search/levenshtein_filter_test.cpp
  3rdParty/iresearch/tests/search/ngram_similarity_filter_tests.cpp
  CHANGELOG
  tests/js/common/aql/aql-view-arangosearch-cluster.inc
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
Labels: 1 Bug, 3 ArangoSearch

#14223 Docs: List possible execution state strings for GET /_api/query/current
  Documentation/DocuBlocks/Rest/AQL/GetApiQueryCurrent.md
Labels: 3 API, 3 Documentation

#14221 Delete libunwind Makefiles
  3rdParty/libunwind/v1.5/src/Makefile
  3rdParty/libunwind/v1.5/tests/Makefile
Labels: 9 Ready to Merge

#14235 Small change on creation scripts for metrics
  utils/makeDashboards.py
Labels: 3 Metrics

#14230 Fixed issue BTS-424: fix invalid input row handling in WINDOW execution.
  CHANGELOG
  arangod/Aql/WindowExecutor.cpp
  tests/js/server/aql/aql-window-malarkey.js
Labels: 3 AQL, 3 Optimizer

#14219 forbid invalid edge weights and negative default weight in K_SHORTEST
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Graph/ShortestPathOptions.cpp
  arangod/Graph/ShortestPathOptions.h
  tests/Graph/KShortestPathsFinder.cpp
  tests/js/server/aql/aql-graph-k-shortest-path.js
  tests/js/server/aql/aql-graph.js
Labels: 1 Bug, 3 Graph, 9 Review Required

#14216 fixed issue BTS-422
  CHANGELOG
  arangod/Aql/OptimizerRulesCluster.cpp
  tests/js/server/aql/aql-optimizer-optimize-cluster-single-document-operations.js
Labels: 3 AQL

#14224 Docs: List possible execution state strings for GET /_api/query/current
  Documentation/DocuBlocks/Rest/AQL/GetApiQueryCurrent.md
Labels: 3 API, 3 Documentation, 9 Ready to Merge

#14225 Docs: List possible execution state strings for GET /_api/query/current
  Documentation/DocuBlocks/Rest/AQL/GetApiQueryCurrent.md
Labels: 3 API, 3 Documentation, 9 Ready to Merge

#14251 Move a hotbackup test to enterprise where it belongs
  tests/js/client/shell/shell-deadlock-trx-hotbackup-cluster.js
Labels: 3 - Testing, 3 ImportExport

#14250 Move a hotbackup test to enterprise where it belongs
  tests/js/client/shell/shell-deadlock-trx-hotbackup-cluster.js
Labels: 3 - Testing, 3 ImportExport

#14229 Fixed issue BTS-424: fix invalid input row handling in WINDOW execution.
  CHANGELOG
  arangod/Aql/WindowExecutor.cpp
  tests/js/server/aql/aql-window-malarkey.js
Labels: 1 Bug

#14253 rename "storedTree" attribute to just "stored".
  arangod/RocksDBEngine/RocksDBV8Functions.cpp
Labels: 9 Ready to Merge

#14218 forbid invalid edge weights and negative default weight in K_SHORTEST…
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Graph/ShortestPathOptions.cpp
  arangod/Graph/ShortestPathOptions.h
  tests/Graph/KShortestPathsFinder.cpp
  tests/js/server/aql/aql-graph-k-shortest-path.js
  tests/js/server/aql/aql-graph.js
Labels: 1 Bug, 3 Graph, 9 Review Required

#14226 Add observationsSampleDataset for docs
  js/common/modules/@arangodb/examples/examples.js
Labels: 3 AQL, 3 Documentation

#14259 Add observationsSampleDataset for docs (#14226)
  js/common/modules/@arangodb/examples/examples.js
Labels: 3 AQL, 3 Documentation

#14277 Honor the upper bound of file-descriptors on MacOs
  CHANGELOG
  arangod/RestServer/FileDescriptorsFeature.cpp
Labels: 4 MacOSX

#14265 additional grindr tests for traversals
  tests/js/server/aql/aql-traversal-grinder.js
Labels: 3 - Testing, 3 Graph, 9 Ready to Merge

#14269 Fix BTS-442
  CHANGELOG
  arangod/Aql/ParallelUnsortedGatherExecutor.cpp
  tests/js/server/aql/aql-skipping-cluster.js
Labels: 3 AQL
