Repository arangodb/arangodb, pull requests merged in 2022-01, with the labels that each got.

#15413 [CINFRA-144] Avoid an unnecessary warning
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
Labels: 9 Ready to Merge, cinfra

#15427 [CINFRA-191] softWriteConcern defaults to writeConcern
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  tests/Replication2/Serialization/LogCommonTest.cpp
Labels: 9 Ready to Merge, cinfra

#15411 [CINFRA-167] Introduced ParticipantResignedException in LogLeader and LogFollower
  arangod/CMakeLists.txt
  arangod/Replication2/Exceptions/ParticipantResignedException.h
  arangod/Replication2/Methods.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/Streams/LogMultiplexer.tpp
  lib/Basics/Exceptions.h
  tests/Replication2/ReplicatedLog/FollowerAppendEntries.cpp
  tests/Replication2/ReplicatedLog/LogReclaimTest.cpp
Labels: 9 Ready to Merge, cinfra

#15404 [CINFRA-187] Replicated Logs Maintenance Integration Tests
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  js/client/modules/@arangodb/testsuites/replication2.js
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra

#15081 Bug fix/bts 590
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
Labels: 9 Ready to Merge

#14745 using lookahead in zkd
  arangod/Aql/ConditionFinder.cpp
  arangod/Aql/IndexHint.cpp
  arangod/Aql/IndexHint.h
  arangod/Indexes/IndexIterator.h
  arangod/RocksDBEngine/RocksDBZkdIndex.cpp
  tests/js/server/aql/aql-optimizer-zkdindex-multi.js
Labels: performance, 3 Search, 3 RocksDB, 3 Index, cinfra

#15441 Delete obsolete symlink
  cmake/RocksDBConfig.cmake.in
Labels: 3 Build, 9 Ready to Merge

#15454 Disable replcation2 server test.
  UnitTests/OskarTestSuitesBlockList
Labels: 3 - Testing, cinfra

#15455 Disable replication2 server test.
  UnitTests/OskarTestSuitesBlockList
Labels: 3 - Testing, cinfra

#15345 [CINFRA-148] Expand the Flags update to allow adding and removing followers
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.h
  lib/Basics/debugging.h
  tests/Replication2/ReplicatedLog/LogStatusTest.cpp
  tests/Replication2/ReplicatedLog/MaintenanceTests.cpp
  tests/Replication2/ReplicatedLog/UpdateParticipantsFlags.cpp
  tests/Replication2/Serialization/LogStatusTest.cpp
Labels: 9 Ready to Merge, cinfra

#15456 Disable replication2 server test.
  UnitTests/OskarTestSuitesBlockList
Labels: 3 - Testing, cinfra

#15431 [3.8] AQL function SHARD_ID
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  arangod/IResearch/IResearchAqlAnalyzer.cpp
  tests/js/server/aql/aql-functions-misc.js
Labels: 1 Feature

#15461 [ES-1025] Fix performance regression caused by different hash calculation.
  CHANGELOG
  lib/Basics/Identifier.cpp
  lib/Basics/Identifier.h
Labels: 1 Bug

#15405 [ORCO-5] Bugfix/improve replication dump performance (#15371)
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/tokens.cpp
  arangod/IResearch/AqlHelper.cpp
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/ReplicationApplierConfiguration.h
  arangod/RocksDBEngine/RocksDBIterators.h
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/Transaction/Methods.cpp
  lib/VPackDeserializer/validate.h
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/IResearch/IResearchFilterBoolean-test.cpp
  tests/IResearch/IResearchQueryComplexBoolean-test.cpp
  tests/IResearch/IResearchQueryOr-test.cpp
  tests/IResearch/IResearchQueryPhrase-test.cpp
  tests/Utils/CollectionNameResolver-test.cpp
  tests/VocBase/vocbase-test.cpp
Labels: 9 Ready to Merge

#15408 Increase cache timeouts
  CHANGELOG
  arangod/ClusterEngine/ClusterSelectivityEstimates.h
  arangod/VocBase/LogicalCollection.cpp
Labels: 9 Ready to Merge, cla-signed

#15430 [3.9] AQL function SHARD_ID
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  arangod/IResearch/IResearchAqlAnalyzer.cpp
  tests/js/server/aql/aql-functions-misc.js
Labels: 1 Feature, 3 AQL, cla-signed

#15428 [APM-292] AQL function SHARD_ID
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  arangod/IResearch/IResearchAqlAnalyzer.cpp
  tests/js/server/aql/aql-functions-misc.js
Labels: 1 Feature, cla-signed

#15463 [ES-1025] Fix performance regression caused by different hash calculation.
  CHANGELOG
  lib/Basics/Identifier.cpp
  lib/Basics/Identifier.h
Labels: cla-signed

#15452 verify that replicationFactor >= writeConcern
  arangod/Sharding/ShardingInfo.cpp
  tests/js/common/shell/01_shell-database.js
Labels: cla-signed

#15460 BTS-707: rename "hardened" option value
  CHANGELOG
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/RestHandler/RestSupportInfoHandler.cpp
  tests/js/client/server_permissions/test-support-info-api-admin-noncluster.js
  tests/js/client/server_permissions/test-support-info-api-admin-off-noncluster.js
Labels: 3 API, cla-signed

#15462 [ES-1025] Fix performance regression caused by different hash calculation.
  CHANGELOG
  lib/Basics/Identifier.cpp
  lib/Basics/Identifier.h
Labels: cla-signed

#15451 [CINFRA-184] Replicated Log + Supervision Integration Test
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  js/client/modules/@arangodb/testsuites/replication2.js
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: 9 Review Required, cinfra, cla-signed

#15468 Remove prebuilt iql files
  3rdParty/iresearch.build/core/iql/location.hh
  3rdParty/iresearch.build/core/iql/parser.cc
  3rdParty/iresearch.build/core/iql/parser.hh
  3rdParty/iresearch.build/core/iql/parser.yy
  3rdParty/iresearch.build/core/iql/position.hh
Labels: cla-signed

#15446 add more indexHints: `disableIndex` and `maxProjections`
  CHANGELOG
  arangod/Aql/ConditionFinder.cpp
  arangod/Aql/DocumentProducingNode.cpp
  arangod/Aql/DocumentProducingNode.h
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IndexHint.cpp
  arangod/Aql/IndexHint.h
  arangod/Aql/OptimizerUtils.cpp
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/js/server/aql/aql-index-hints.js
  tests/js/server/aql/aql-optimizer-rule-reduce-extraction-to-projection.js
  tests/js/server/aql/aql-options-verification.js
  tests/js/server/aql/aql-projections.js
Labels: cla-signed

#15467 fix pitfall for comdat folding
  arangod/Aql/Ast.cpp
  arangod/Aql/IResearchViewNode.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/Utils/CollectionNameResolver.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/LogicalDataSource.cpp
  arangod/VocBase/LogicalDataSource.h
  arangod/VocBase/LogicalView.cpp
  arangod/VocBase/LogicalView.h
  arangod/VocBase/vocbase.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/VocBase/LogicalDataSourceTest.cpp
Labels: cla-signed

#15474 small code cleanup
  arangod/Agency/AddFollower.cpp
  arangod/Agency/Agent.cpp
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Node.cpp
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/State.cpp
  arangod/Agency/Store.cpp
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/Maintenance.cpp
  tests/Agency/CleanUpLostCollectionTest.cpp
Labels: cla-signed

#15352 [CINFRA-161] Follower State Transfer
  arangod/CMakeLists.txt
  arangod/Replication2/ReplicatedLog/ILogInterfaces.h
  arangod/Replication2/ReplicatedLog/InMemoryLog.h
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.h
  arangod/Replication2/ReplicatedState/AbstractStateMachine.tpp
  arangod/Replication2/ReplicatedState/FollowerStateManager.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/LeaderStateManager.h
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/ReplicatedStateCore.cpp
  arangod/Replication2/ReplicatedState/ReplicatedStateCore.h
  arangod/Replication2/ReplicatedState/ReplicatedStateFeature.h
  arangod/Replication2/ReplicatedState/StateCommon.cpp
  arangod/Replication2/ReplicatedState/StateCommon.h
  arangod/Replication2/ReplicatedState/StateInterfaces.h
  arangod/Replication2/ReplicatedState/StateStatus.h
  arangod/Replication2/Streams/MultiplexedValues.h
  arangod/Replication2/Streams/StreamInformationBlock.tpp
  arangod/Replication2/Streams/Streams.tpp
  tests/CMakeLists.txt
  tests/Replication2/Helper/WaitForQueue.cpp
  tests/Replication2/Helper/WaitForQueue.h
  tests/Replication2/Mocks/AsyncFollower.cpp
  tests/Replication2/Mocks/AsyncFollower.h
  tests/Replication2/Mocks/FakeAbstractFollower.h
  tests/Replication2/Mocks/FakeFollower.cpp
  tests/Replication2/Mocks/FakeFollower.h
  tests/Replication2/Mocks/FakeReplicatedState.cpp
  tests/Replication2/Mocks/FakeReplicatedState.h
  tests/Replication2/ReplicatedLog/AppendEntriesErrorReasonTest.cpp
  tests/Replication2/ReplicatedLog/LeaderAppendEntriesTest.cpp
  tests/Replication2/ReplicatedLog/WaitForSyncTest.cpp
  tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
  tests/Replication2/ReplicatedState/LeaderRecoveryTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/MyStateMachine.cpp
  tests/Replication2/ReplicatedState/StateMachines/MyStateMachine.h
Labels: 9 Ready to Merge, cinfra, cla-signed

#15387 UI for Classification and Nearest Neighbor Analyzers
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/Actions.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/AnalyzersReactView.jsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/constants.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/ClassificationForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/NearestNeighborsForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/inputs/ModelInput.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/helpers.tsx
Labels: 3 UI, 3 Search, cla-signed

#15480 Fixed issue #15476: FATAL {crash} occurs on a simple query.
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Labels: cla-signed

#15415 attempt to fix compaction shutdown hangers
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: cla-signed

#15349 [CINFRA-162] Supervision for Replicated State Machines
  arangod/CMakeLists.txt
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/Replication2/ReplicatedState/Supervision.h
  arangod/Replication2/ReplicatedState/SupervisionVelocyPackHell.cpp
  tests/CMakeLists.txt
  tests/Replication2/ReplicatedState/SupervisionTest.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#15483 [CINFRA-203] CommitFailReason Leadership
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.h
  tests/Replication2/ReplicatedLog/CalcCommitIndexTest.cpp
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
Labels: cinfra, cla-signed

#15490 [BTS-705] Add more decay tests
  tests/Aql/DecaysFunctionTest.cpp
  tests/js/server/aql/aql-functions-numeric.js
Labels: cla-signed

#15491 TSAN workaround
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchView.cpp
Labels: cla-signed

#15495 add tests for vector functions
  tests/js/server/aql/aql-vector-functions.js
Labels: cla-signed

#15488 BTS-718: potential fix for assertion failure
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBMetadata.h
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
Labels: cla-signed

#15494 [CINFRA-207] Wait for server to recover after test suspend
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: 3 - Testing, cinfra, cla-signed

#15492 TSAN workaround 3.9 backport
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchView.cpp
Labels: ASan

#15502 Allow to compile with python 3.10
  3rdParty/V8/gyp/common.py
  3rdParty/V8/gyp/msvs_emulation.py
  3rdParty/V8/v7.9.317/third_party/jinja2/tests.py
Labels: 9 Ready to Merge, cla-signed

#15510 [CINFRA-214] Fixing memory leaks in replication2 tests.
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  tests/Replication2/ReplicatedState/LeaderRecoveryTest.cpp
Labels: cinfra, cla-signed

#15457 [CINFRA-190] Move participant list out of term
  arangod/Agency/AgencyPaths.h
  arangod/Agency/Supervision.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/UpdateReplicatedLogAction.cpp
  arangod/Replication2/AgencyMethods.cpp
  arangod/Replication2/AgencyMethods.h
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/Algorithms.h
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedState/Supervision.cpp
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/Cluster/AgencyPathsTest.cpp
  tests/Replication2/ReplicatedLog/CheckLogsTest.cpp
  tests/Replication2/ReplicatedLog/MaintenanceTests.cpp
  tests/Replication2/ReplicatedLog/UpdateReplicatedLogTests.cpp
  tests/Replication2/ReplicatedState/SupervisionTest.cpp
  tests/js/common/shell/shell-replicated-logs-cluster.js
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra, cla-signed

#15478 Fixed issue #14576: FATAL {crash} occurs on a simple query.
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Labels: 3 AQL, 3 Optimizer, 9 Ready to Merge, cla-signed

#15479 Fixed issue #15476: FATAL {crash} occurs on a simple query.
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Labels: 3 AQL, 3 Optimizer, 9 Ready to Merge, cla-signed

#15481 verify that replicationFactor >= writeConcern
  CHANGELOG
  arangod/Sharding/ShardingInfo.cpp
  tests/js/common/shell/01_shell-database.js
Labels: 3 Cluster, 9 Ready to Merge, cla-signed

#15504 Fix data race
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBMetadata.h
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  client-tools/Benchmark/BenchmarkThread.h
  tsan_arangodb_suppressions.txt
Labels: cla-signed

#15489 [3.9] [BTS-705] Add more decay tests
  tests/Aql/DecaysFunctionTest.cpp
  tests/js/server/aql/aql-functions-numeric.js
Labels: 3 AQL, 3 - Testing, cla-signed

#15499 added push-queue operation
  CHANGELOG
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  tests/js/client/agency/agency-test.js
Labels: cinfra, cla-signed

#15440 [CINFRA-168] Report Supervision Election result in coordinator
  arangod/Replication2/AgencyMethods.cpp
  arangod/Replication2/AgencyMethods.h
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.h
  arangod/RestHandler/RestLogHandler.cpp
  arangod/RestHandler/RestLogHandler.h
  arangod/V8Server/v8-replicated-logs.cpp
  js/client/modules/@arangodb/replicated-logs.js
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  lib/Basics/process-utils.cpp
  lib/V8/v8-utils.cpp
  tests/Replication2/Serialization/LogStatusTest.cpp
  tests/js/common/shell/shell-replicated-logs-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: 9 Ready to Merge, cinfra, cla-signed

#15505 Fix data race 3.9
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBMetadata.h
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangosh/Benchmark/BenchmarkThread.h
  tsan_arangodb_suppressions.txt
Labels: ASan, cla-signed

#15487 BTS-718: potential fix for assertion failure
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBMetadata.h
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
Labels: 3 - Testing, cla-signed

#15497 clang-format adjustments
  .githooks/pre-commit-linux
  .githooks/pre-commit-macos
  .githooks/pre-commit-windows
  .github/workflows/clang-format.yml
Labels: cla-signed

#15521 remove stray console.log calls
  js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/notificationView.js
Labels: cla-signed

#15511 Bug fix 3.9/fix exit code
  CHANGELOG
  arangod/Scheduler/SchedulerFeature.cpp
  arangosh/Backup/arangobackup.cpp
  arangosh/Benchmark/arangobench.cpp
  arangosh/Dump/arangodump.cpp
  arangosh/Export/arangoexport.cpp
  arangosh/Import/arangoimport.cpp
  arangosh/Restore/arangorestore.cpp
  arangosh/Shell/arangosh.cpp
  arangosh/VPack/arangovpack.cpp
  lib/Basics/signals.cpp
  lib/Basics/signals.h
Labels: 3 ImportExport, cla-signed

#15513 simplify PR template a bit
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#15523 simplify PR template
  PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#15529 simplify PR template
  PULL_REQUEST_TEMPLATE.md
Labels: cla-signed

#15528 license grace period
  CHANGELOG
Labels: 3 License, cla-signed

#15525 BTS-734 hotbackup upload can miss files
  CHANGELOG
  lib/Basics/FileUtils.cpp
  lib/Basics/files.cpp
Labels: 3 ImportExport, cla-signed

#15519 Added test for complex queries
  tests/js/server/aql/aql-complex-queries-callstack.js
Labels: 3 AQL, 3 - Testing, cla-signed

#15527 [3.9] license grace period
  CHANGELOG
Labels: 3 License, cla-signed

#15536 [SEARCH-287] Ensure new link format doesn't use old norms
  3rdParty/velocypack/include/velocypack/Builder.h
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchAnalyzerFeature.h
  arangod/IResearch/IResearchCommon.cpp
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchLinkHelper.h
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewMeta.h
  arangod/IResearch/VelocyPackHelper.cpp
  arangod/IResearch/VelocyPackHelper.h
  tests/IResearch/IResearchDocumentTest.cpp
  tests/IResearch/IResearchLinkCoordinatorTest.cpp
  tests/IResearch/IResearchLinkMetaTest.cpp
  tests/IResearch/IResearchLinkTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewMetaTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/IResearch/common.cpp
Labels: cla-signed

#15522 BTS-734 hotbackup upload can miss files
  CHANGELOG
  lib/Basics/FileUtils.cpp
  lib/Basics/files.cpp
Labels: cla-signed

#15506 [CINFRA-197] Use non-system databases
  arangod/Replication2/Methods.cpp
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/js/common/shell/shell-replicated-logs-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra, cla-signed

#15518 Added unittest for complex queries
  tests/js/server/aql/aql-complex-queries-callstack.js
Labels: 3 AQL, 3 - Testing, cla-signed

#15531 Refuse to concat a char.
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  lib/Basics/StringUtils.h
  tests/Basics/StringUtilsTest.cpp
Labels: cinfra, cla-signed

#15515 [BTS-714] Fix various TSan issues.
  arangod/Aql/Query.cpp
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryList.h
  arangod/Aql/QueryProfile.cpp
  arangod/Aql/QueryProfile.h
  arangod/Cluster/ClusterCollectionCreationInfo.cpp
  arangod/Cluster/ClusterCollectionCreationInfo.h
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/GeneralServer/GeneralServer.cpp
  arangod/Utils/Cursor.h
  lib/ApplicationFeatures/ApplicationServer.cpp
  lib/ApplicationFeatures/ApplicationServer.h
Labels: ASan, cla-signed

#15538 [SEARCH-287] Ensure new link format doesn't use old norms
  3rdParty/velocypack/include/velocypack/Builder.h
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchAnalyzerFeature.h
  arangod/IResearch/IResearchCommon.cpp
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchLinkHelper.h
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewMeta.h
  arangod/IResearch/VelocyPackHelper.cpp
  arangod/IResearch/VelocyPackHelper.h
  tests/IResearch/IResearchDocument-test.cpp
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchLinkCoordinator-test.cpp
  tests/IResearch/IResearchLinkMeta-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewCoordinator-test.cpp
  tests/IResearch/IResearchViewMeta-test.cpp
  tests/IResearch/common.cpp
Labels: 3 ArangoSearch, cla-signed

#15541 Address cpp-check issues
  arangod/Pregel/Algos/AIR/Accumulators.cpp
  lib/Containers/MerkleTree.cpp
  lib/Rest/Version.cpp
  lib/VPackDeserializer/deserialize-with.h
  lib/VPackDeserializer/validate.h
Labels: cla-signed

#15540 BTS-712
  3rdParty/iresearch/core/analysis/collation_token_stream.cpp
  3rdParty/iresearch/core/analysis/collation_token_stream.hpp
  3rdParty/iresearch/core/analysis/collation_token_stream_encoder.hpp
  CHANGELOG
  tests/js/common/aql/aql-view-arangosearch-feature.js
Labels: 3 ArangoSearch, cla-signed

#15543 [3.9] BTS-712
  3rdParty/iresearch/core/analysis/collation_token_stream.cpp
  3rdParty/iresearch/core/analysis/collation_token_stream.hpp
  3rdParty/iresearch/core/analysis/collation_token_stream_encoder.hpp
  CHANGELOG
  tests/js/common/aql/aql-view-arangosearch-feature.js
Labels: 3 ArangoSearch, cla-signed

#15542 Address cppcheck issues
  lib/Basics/debugging.h
Labels: cla-signed

#15544 Address cpp-check issues (#15541)
  arangod/Pregel/Algos/AIR/Accumulators.cpp
  lib/Containers/MerkleTree.cpp
  lib/Rest/Version.cpp
  lib/VPackDeserializer/deserialize-with.h
  lib/VPackDeserializer/validate.h
Labels: cla-signed

#15551 Fixed python imports to work with 3.10 (#15502)
  3rdParty/V8/gyp/common.py
  3rdParty/V8/gyp/msvs_emulation.py
  3rdParty/V8/gypfiles/standalone.gypi
  3rdParty/V8/v7.9.317/third_party/jinja2/tests.py
  CMakeLists.txt
Labels: 3 Build, cla-signed

#15550 Fixed python imports to work with 3.10 (#15502)
  3rdParty/V8/gyp/common.py
  3rdParty/V8/gyp/msvs_emulation.py
  3rdParty/V8/gypfiles/standalone.gypi
  3rdParty/V8/v7.9.317/third_party/jinja2/tests.py
  CMakeLists.txt
Labels: 3 Build, cla-signed

#15549 Fixed python imports to work with 3.10 (#15502)
  3rdParty/V8/gyp/common.py
  3rdParty/V8/gyp/msvs_emulation.py
  3rdParty/V8/gypfiles/standalone.gypi
  3rdParty/V8/v7.9.317/third_party/jinja2/tests.py
  CMakeLists.txt
Labels: 3 Build, cla-signed

#15532 Add CHANGELOG for boost 1.78.0 upgrade
  CHANGELOG
Labels: cla-signed

#15539 Improve performance of `db._explain()`
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/Parser.cpp
  arangod/Aql/PlanCache.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/QueryOptions.cpp
  arangod/Aql/QueryOptions.h
  arangod/Aql/QueryString.h
  arangod/V8Server/v8-vocbase.cpp
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#15560 Build/add zlib dependency
  3rdParty/V8/gypfiles/standalone.gypi
  CMakeLists.txt
Labels: 3 Build, cla-signed

#15557 Disable an optimizer rule in exclusive lock mode
  CHANGELOG
  arangod/Aql/OptimizerRulesCluster.cpp
  tests/js/server/aql/aql-optimizer-rule-optimize-cluster-single-document-operations.js
Labels: cla-signed

#15569 remove internal `_constAstNode` from `Variable` struct
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/Variable.h
Labels: cla-signed

#15573 delete test since test for gzip transfer encoding /_api/version via …
  tests/rb/HttpInterface/api-http-spec.rb
Labels: 3 - Testing, cla-signed

#15572 delete test since test for gzip transfer encoding /_api/version via …
  tests/rb/HttpInterface/api-http-spec.rb
Labels: 3 - Testing, cla-signed

#15571 delete test since test for gzip transfer encoding /_api/version via …
  tests/rb/HttpInterface/api-http-spec.rb
Labels: 3 - Testing, cla-signed

#15570 delete test since test for gzip transfer encoding /_api/version
  tests/rb/HttpInterface/api-http-spec.rb
Labels: 3 - Testing, cla-signed

#15577 add a suppression for UBSan
  lib/Logger/LogContext.h
Labels: cla-signed

#15565 Fixed issue #15501
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/GeneralServer/RequestLane.h
  arangod/Network/Utils.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  tests/RestHandler/RestDocumentHandlerTest.cpp
Labels: cla-signed

#15568 [CINFRA] Hide bogus maybe-uninitialized errors.
  arangod/Replication2/ReplicatedLog/NetworkMessages.h
  arangod/Replication2/ReplicatedLog/types.h
Labels: cinfra, cla-signed

#15553 [CINFRA-218] Construct Leader with Participant Flags
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  tests/Replication2/Mocks/FakeReplicatedLog.cpp
  tests/Replication2/Mocks/FakeReplicatedLog.h
  tests/Replication2/ReplicatedLog/ChangeStreamTests.cpp
  tests/Replication2/ReplicatedLog/EstablishLeadershipTest.cpp
  tests/Replication2/ReplicatedLog/LeaderAppendEntriesTest.cpp
  tests/Replication2/ReplicatedLog/LogReclaimTest.cpp
  tests/Replication2/ReplicatedLog/LogStatusTest.cpp
  tests/Replication2/ReplicatedLog/SimpleInsertTests.cpp
  tests/Replication2/ReplicatedLog/TestHelper.h
  tests/Replication2/ReplicatedLog/UpdateParticipantsFlags.cpp
  tests/Replication2/ReplicatedLog/UpdateReplicatedLogTests.cpp
  tests/Replication2/ReplicatedLog/WaitForSyncTest.cpp
  tests/Replication2/ReplicatedState/AbstractStateMachinePollTest.cpp
  tests/Replication2/ReplicatedState/LeaderRecoveryTest.cpp
  tests/Replication2/ReplicatedState/ReplicatedStateTest.cpp
  tests/Replication2/Streams/LogMultiplexerTest.cpp
  tests/Replication2/Streams/MultiplexerConcurrencyTest.cpp
  tests/Replication2/Streams/TestLogSpecification.h
Labels: 9 Ready to Merge, cinfra, cla-signed

#15548 [CINFRA-220] No-Op state machine
  arangod/CMakeLists.txt
  arangod/Replication2/ReplicatedState/ReplicatedStateFeature.cpp
  arangod/Replication2/ReplicatedState/ReplicatedStateFeature.h
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.cpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.h
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachineFeature.cpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachineFeature.h
  arangod/RestServer/arangod.cpp
Labels: cinfra, cla-signed

#15576 BTS-735, BTS-736 and other tsan issues fix
  arangod/Aql/IResearchViewNode.cpp
  arangod/IResearch/Containers.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewMeta.h
  tests/IResearch/ContainersTest.cpp
  tests/IResearch/IResearchFeatureTest.cpp
  tests/IResearch/IResearchViewDBServerTest.cpp
  tests/IResearch/IResearchViewTest.cpp
Labels: cla-signed

#15562 BTS-713: Bug fix/debug weak wrappers
  arangod/V8Server/v8-analyzers.cpp
  arangod/V8Server/v8-collection-util.cpp
  arangod/V8Server/v8-views.cpp
  lib/V8/v8-globals.cpp
Labels: cla-signed

#15595 BTS-758 | Docs: Clarify intended usage and describe actual behavior of Coordinator soft-shutdown
  Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
Labels: 3 Documentation, 9 Ready to Merge, cla-signed

#15602 add cleanup
  tests/js/server/aql/aql-inverted-index.js
  tests/js/server/aql/aql-iresearch-view-executor-regression.js
Labels: cla-signed

#15603 BTS-501
  tests/IResearch/IResearchFeatureTest.cpp
Labels: cla-signed

#15559 Disable an optimizer rule in exclusive lock mode
  CHANGELOG
  arangod/Aql/OptimizerRulesCluster.cpp
  tests/js/server/aql/aql-optimizer-rule-optimize-cluster-single-document-operations.js
Labels: 3 Optimizer, 9 Ready to Merge, cla-signed

#15586 Fix creation of satellite graphs with a `numberOfShards` value != 1.
  CHANGELOG
  arangod/Graph/GraphManager.cpp
Labels: 3 API, 3 Graph, cla-signed

#15598 BTS-758 | Documentation-3.7/soft-coordinator-shutdown-fix
  Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
Labels: 3 Documentation, 9 Ready to Merge, cla-signed

#15597 BTS-758 | Documentation-3.8/soft-coordinator-shutdown-fix
  Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
Labels: 3 Documentation, 9 Ready to Merge, cla-signed

#15583 Fix creation of satellite graphs with a `numberOfShards` value != 1.
  CHANGELOG
  arangod/Graph/GraphManager.cpp
Labels: 3 API, 3 Graph, cla-signed

#15596 BTS-758 | Documentation-3.9/soft-coordinator-shutdown-fix
  Documentation/DocuBlocks/Rest/Administration/delete_api_shutdown.md
Labels: 3 Documentation, 9 Ready to Merge, cla-signed

#15584 fix creation of satellite graphs with invalid number of shards
  CHANGELOG
  arangod/Graph/GraphManager.cpp
Labels: 3 API, 3 Graph, cla-signed

#15585 fix creation of satellite graphs with invalid number of shards
  CHANGELOG
  arangod/Graph/GraphManager.cpp
Labels: 3 API, 3 Graph, cla-signed

#15591 Bug fix/bts 740
  CHANGELOG
  js/client/modules/@arangodb/testutils/collect-crud-api-generic-tests.js
  js/common/modules/@arangodb/testutils/collection-wrapper-util.js
  js/server/modules/@arangodb/testutils/collection-modification-aql-generic-tests.js
  tests/js/client/shell/shell-document.js
Labels: 1 Bug, cla-signed

#15563 Fixed issue #15501
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/GeneralServer/RequestLane.h
  arangod/Network/Utils.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  tests/RestHandler/RestDocumentHandler-test.cpp
Labels: cla-signed

#15605 Fix a potential deadlock in QueryList introduced in #15515
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryList.h
Labels: TSan

#15416 add optional "storedValues" attribute for persistent indexes
  CHANGELOG
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_persistent.md
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/Projections.cpp
  arangod/Aql/WindowExecutor.cpp
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndex.h
  arangod/ClusterEngine/ClusterIndexFactory.cpp
  arangod/Graph/PathEnumerator.cpp
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/Indexes/IndexFactory.cpp
  arangod/Indexes/IndexFactory.h
  arangod/Indexes/IndexIterator.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.h
  arangod/RocksDBEngine/RocksDBIndexFactory.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  arangod/RocksDBEngine/RocksDBValue.cpp
  arangod/RocksDBEngine/RocksDBValue.h
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/Transaction/Helpers.cpp
  arangod/Transaction/Helpers.h
  arangod/Transaction/Methods.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Indexes.cpp
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/indicesView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/indicesView.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Utilities/Timers.h
  tests/js/common/shell/shell-index-stored-values.js
Labels: cla-signed

#15607 [3.9] BTS-501
  tests/IResearch/IResearchFeature-test.cpp
Labels: 3 - Testing, cla-signed

#15606 Reduce overhead for checking failure points when none are set.
  lib/Basics/debugging.cpp
Labels: cla-signed

#15587 [CINFRA-206] Fix checkCommitIndex returning without a commit fail reason
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/Algorithms.h
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  tests/Replication2/ReplicatedLog/CalcCommitIndexTest.cpp
  tests/Replication2/ReplicatedLog/EstablishLeadershipTest.cpp
  tests/Replication2/ReplicatedLog/UpdateParticipantsFlags.cpp
  tests/js/common/shell/shell-replicated-logs-cluster.js
Labels: cinfra, cla-signed

#15593 BTS-735, BTS-736 3.9
  arangod/Aql/IResearchViewNode.cpp
  arangod/IResearch/Containers.h
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewMeta.h
  tests/IResearch/Containers-test.cpp
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchQueryNoMaterialization-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
Labels: 3 ArangoSearch, TSan, cla-signed

#15604 Bug fix/bts 729
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/EngineInfoContainerDBServerServerBased.h
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
Labels: cla-signed

#15615 Refactor LogContext to produce less moves/copies
  lib/Logger/LogContext.h
  tests/Logger/LogContextTest.cpp
Labels: cla-signed

#15611 PRESUPP-445: Fix Foxx queues with multiple coordinators
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/HeartbeatThread.h
  arangod/V8Server/FoxxFeature.cpp
  arangod/V8Server/FoxxFeature.h
  arangod/V8Server/v8-actions.cpp
  js/server/modules/@arangodb/foxx/queues/manager.js
  tests/js/client/load-balancing/load-balancing-cursor-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-foxx-queues-noauth-cluster.js
  tests/js/server/shell/shell-foxx-queues.js
Labels: cla-signed

#15620 Bug fix/bts 728
  CHANGELOG
  arangod/Graph/PathEnumerator.cpp
  arangod/Graph/WeightedEnumerator.cpp
Labels: 1 Bug, cla-signed

#15622 Backport Bug fix 3.9/bts 729
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/EngineInfoContainerDBServerServerBased.h
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
Labels: cla-signed

#15628 3.9 backport of bug-fix-3.9/BTS-728
  CHANGELOG
  arangod/Graph/PathEnumerator.cpp
  arangod/Graph/WeightedEnumerator.cpp
Labels: 1 Bug, 3 Graph, cla-signed

#15514 [ORCO-26] Fix various TSan issues.
  arangod/Aql/Query.cpp
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryList.h
  arangod/Aql/QueryProfile.cpp
  arangod/Aql/QueryProfile.h
  arangod/Cache/CacheManagerFeature.cpp
  arangod/Cluster/ClusterCollectionCreationInfo.cpp
  arangod/Cluster/ClusterCollectionCreationInfo.h
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/GeneralServer/GeneralServer.cpp
  arangod/Replication/GlobalReplicationApplier.cpp
  arangod/Replication/GlobalReplicationApplier.h
  arangod/Replication/TailingSyncer.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.h
  arangod/Utils/Cursor.h
  lib/ApplicationFeatures/ApplicationServer.cpp
  lib/ApplicationFeatures/ApplicationServer.h
  lib/Basics/signals.cpp
  lib/Containers/MerkleTree.cpp
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
  tsan_arangodb_suppressions.txt
Labels: ASan, cla-signed

#15556 [CINFRA-162] Replicated Log Supervision
  arangod/Agency/AgencyPaths.cpp
  arangod/Agency/AgencyPaths.h
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/TransactionBuilder.h
  arangod/CMakeLists.txt
  arangod/Replication2/AgencyMethods.cpp
  arangod/Replication2/AgencyMethods.h
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/Algorithms.h
  arangod/Replication2/ReplicatedLog/ParticipantsHealth.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/Supervision.h
  arangod/Replication2/ReplicatedLog/SupervisionAction.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.h
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/Replication2/ReplicatedState/Supervision.h
  arangod/Replication2/ReplicatedState/SupervisionVelocyPackHell.cpp
  arangod/RestHandler/RestLogHandler.cpp
  arangod/V8Server/v8-replicated-logs.cpp
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/CMakeLists.txt
  tests/Cluster/AgencyPathsTest.cpp
  tests/Replication2/ReplicatedLog/CheckLogsTest.cpp
  tests/Replication2/ReplicatedLog/MaintenanceTests.cpp
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
  tests/Replication2/ReplicatedState/SupervisionTest.cpp
  tests/js/common/shell/shell-replicated-logs-cluster.js
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra, cla-signed

#15619 Backport 3.9 BTS-740
  CHANGELOG
  js/client/modules/@arangodb/testutils/collect-crud-api-generic-tests.js
  js/common/modules/@arangodb/testutils/collection-wrapper-util.js
  js/server/modules/@arangodb/testutils/collection-modification-aql-generic-tests.js
  tests/js/client/shell/shell-document.js
Labels: cla-signed

#15630 Added more detail to time consumption and data amount parsed log
  CHANGELOG
  client-tools/Dump/DumpFeature.cpp
  client-tools/Restore/RestoreFeature.cpp
Labels: cla-signed

#15626 Updated documentation
  Documentation/DocuBlocks/Rest/Administration/get_admin_log.md
Labels: cla-signed

#15618 Slightly improve the explain output of SingleRemoteOperationNodes.
  CHANGELOG
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#15634 upgrade velocypack to latest version
  3rdParty/velocypack/include/velocypack/Builder.h
  3rdParty/velocypack/include/velocypack/Slice.h
  3rdParty/velocypack/src/Builder.cpp
  3rdParty/velocypack/tests/testsBuilder.cpp
  3rdParty/velocypack/tools/CMakeLists.txt
  3rdParty/velocypack/tools/bench.cpp
  3rdParty/velocypack/tools/bench.md
  3rdParty/velocypack/tools/bench.png
  CHANGELOG
Labels: cla-signed

#15575 add testsuite to invoke the makedata suite from the RTA
  CONTRIBUTING.md
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/process-utils.js
Labels: 3 - Testing, cla-signed

#15631 [CINFRA] Revert change that introduced compiler issues with apple-clang-13.
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#15508 Refactor/tracing path validator
  arangod/CMakeLists.txt
  arangod/Graph/PathManagement/PathValidator.cpp
  arangod/Graph/PathManagement/PathValidator.h
  arangod/Graph/PathManagement/PathValidatorTracer.cpp
  arangod/Graph/PathManagement/PathValidatorTracer.h
  arangod/Graph/Providers/TypeAliases.h
  arangod/Graph/algorithm-aliases.h
  tests/Graph/GraphMockProviderInstances.cpp
Labels: cla-signed

#15632 [CINFRA] Fixing testLogStatus.
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra, cla-signed

#15644 Use `optimize_filters_for_hits` for documents CF
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: cla-signed

#15638 reduce peak memory usage of some AQL queries
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AstResources.cpp
  arangod/Aql/AstResources.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  arangod/Aql/ShortStringStorage.cpp
  arangod/Aql/ShortStringStorage.h
  lib/Basics/FixedSizeAllocator.h
  tests/Aql/AstResourcesTest.cpp
  tests/Basics/FixedSizeAllocatorTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-queries-nested-joins.js
Labels: cla-signed
