Repository arangodb/arangodb, pull requests merged in 2022-08, with the labels that each got.

#16665 Fix /_admin/cluster/rebalance DocuBlocks (3.10)
  Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance.md
  Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance_execute.md
  Documentation/DocuBlocks/Rest/Administration/put_admin_cluster_rebalance.md
Labels: 3 Documentation, 3 Cluster

#16664 BTS-874 | Documentation/immutable-startup-options
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/EndpointFeature.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  client-tools/Benchmark/BenchFeature.cpp
  client-tools/Export/ExportFeature.cpp
  client-tools/Import/ImportFeature.cpp
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Shell/V8ShellFeature.cpp
  lib/ApplicationFeatures/ConfigFeature.cpp
  lib/ApplicationFeatures/LanguageFeature.cpp
  lib/Logger/LoggerFeature.cpp
Labels: 3 Documentation, 9 Ready to Merge

#16657 DOC-123 | Add computedFields collection property for Computed Values
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
Labels: 1 Feature, 3 Documentation

#16669 Bug fix/insert enterprise edge
  CHANGELOG
Labels: 1 Bug

#16602 Cleanout server before testing rebalance.
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: cinfra, 3.10

#16648 Bugfix 3.10/stop total pregel time correctly
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Status/Status.h
Labels: 3 Pregel, 3.10

#16673 Bug fix 3.10 /insert enterprise edge
  CHANGELOG
Labels: 3 Graph

#16666 Fix /_admin/cluster/rebalance DocuBlocks
  Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance.md
  Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance_execute.md
  Documentation/DocuBlocks/Rest/Administration/put_admin_cluster_rebalance.md
Labels: 3 Documentation

#16605 [PREGEL] Add Conductor state machine and use it for the Loading state
  arangod/CMakeLists.txt
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  arangod/Pregel/Conductor/LoadingState.cpp
  arangod/Pregel/Conductor/LoadingState.h
  arangod/Pregel/Conductor/State.h
  arangod/Pregel/Worker.cpp
  arangod/Pregel/WorkerConductorMessages.h
Labels: 3 Pregel

#16688 Update OpenSSL to 1.1.1q and OpenLDAP to 2.6.3 (3.8)
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#16689 Update OpenSSL to 1.1.1q and OpenLDAP to 2.6.3 (3.9)
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#16691 Update OpenSSL to 1.1.1q and OpenLDAP to 2.6.3
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#16692 Update OpenSSL to 1.1.1q and OpenLDAP to 2.6.3
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#16617 Feature/reprio test definitions
  tests/test-definitions.txt
Labels: 3 - Testing

#16684 Fix incorrect destroy order that cause data race 3.10
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
Labels: 1 Bug, 3 ArangoSearch, ASan

#16674 Update Rclone to v1.59.0
  CHANGELOG
  VERSIONS
Labels: 3 ImportExport

#16695 Bugfix 3.10/bts 902
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/AnalyzersReactView.jsx
Labels: 3 UI, 3 Search

#16700 Feature/reprio test definitions (#16617)
  tests/test-definitions.txt
Labels: 3 - Testing

#16703 Update Rclone to v1.59.0 (3.10)
  CHANGELOG
  VERSIONS
Labels: 3 ImportExport

#16698 [CINFRA-508] LeaderElection sets write concern
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.h
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
Labels: cinfra

#16709 fix UB in collection properties updating
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndex.h
  tests/js/common/shell/shell-collection.js
Labels: 3 Index, 3 ArangoSearch

#16697 Suppress absl::Mutex false positive atomic race
  tsan_arangodb_suppressions.txt
Labels: TSan

#16719 Add VALUE AQL function for dynamic access by a specified attribute path
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  tests/js/server/aql/aql-functions.js
Labels: 3 AQL

#16722 Feature 3.10/search 335 and atleast support
  CHANGELOG
  arangod/Aql/AqlValue.h
  arangod/Aql/OptimizerUtils.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  tests/IResearch/IResearchFilterArrayInTest.cpp
  tests/IResearch/common.cpp
  tests/IResearch/common.h
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
Labels: 3 AQL, 3 ArangoSearch

#16583 Web Interface: Add missing `AT LEAST` operator and AQL functions to code highlighter
  js/apps/system/_admin/aardvark/APP/react/public/assets/src/mode-aql.js
Labels: 1 Bug, 3 UI

#16486 BTS-874 | Documentation/immutable-startup-options
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/EndpointFeature.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  client-tools/Benchmark/BenchFeature.cpp
  client-tools/Export/ExportFeature.cpp
  client-tools/Import/ImportFeature.cpp
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Shell/V8ShellFeature.cpp
  lib/ApplicationFeatures/ConfigFeature.cpp
  lib/ApplicationFeatures/LanguageFeature.cpp
  lib/Logger/LoggerFeature.cpp
Labels: 3 Documentation, 9 Ready to Merge

#16720 [CINFRA] Add suffixes to auto test names
  tests/Definition/rlog/pr.fish
  tests/Definition/rlog/pr.ps1
Labels: cinfra

#16724 Added serverId for _admin/log/level
  CHANGELOG
  Documentation/DocuBlocks/Rest/Administration/get_admin_log.md
  arangod/RestHandler/RestAdminLogHandler.cpp
  arangod/RestHandler/RestAdminLogHandler.h
  tests/js/client/shell/shell-admin-log.js
Labels: cinfra

#16744 [PREGEL] Fix windows build
  arangod/Pregel/Graph.h
Labels: 3 Pregel

#16710 Fix few tsan issues
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/ClusterQuery.h
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryOptions.h
  lib/Futures/Future.h
  tests/Cache/Rebalancer.cpp
  tests/Cache/TransactionsWithBackingStore.cpp
  tests/Fuerte/ConnectionFailuresTest.cpp
  tests/Futures/FutureTest.cpp
  tests/IResearch/IResearchFeatureTest.cpp
  tests/IResearch/IResearchViewNodeTest.cpp
  tests/Network/MethodsTest.cpp
  tests/Replication2/ModelChecker/ModelChecker.h
  tsan_arangodb_suppressions.txt
Labels: TSan

#16748 fix an invalid attribute access
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  tests/js/server/aql/aql-queries-optimizer.js
Labels: 3 AQL, 3 Optimizer

#16762 Fixing testSingleTransactionIntermediateCommitsOnFollowerWithRollback.
  tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
Labels: cinfra

#16733 Fixed illegal optimizer rule on multiple consecutive SORTs
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-collect-count.js
  tests/js/server/aql/aql-queries-optimizer-sort.js
Labels: 3 AQL, 9 Review Required, 3 Optimizer

#16736 added unit tests for computed values (#16713)
  tests/CMakeLists.txt
  tests/VocBase/ComputedValuesTest.cpp
Labels: 3 AQL, 3 - Testing

#16743 fix shutdown memleak for temp storage db
  arangod/RocksDBEngine/RocksDBTempStorage.cpp
Labels: 3 RocksDB

#16739 Fix "transaction not found" issues
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/RestHandler/RestControlPregelHandler.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  js/client/modules/@arangodb/testsuites/restart.js
  tests/js/client/load-balancing/load-balancing-cursor-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-queries-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
  tests/js/client/restart/test-restart-coordinator-transactions.js
Labels: 3 Pregel

#16759 [PREGEL] Update pregel status documentation
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_overview.md
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
Labels: 3 Documentation, 3 Pregel, 3.10

#16595 [PREGEL] Update pregel status documentation
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_overview.md
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
Labels: 3 Documentation, 3 Pregel

#16752 [PREGEL] Separate pregel cmake build
  arangod/CMakeLists.txt
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/Pregel/Algos/AIR/CMakeLists.txt
  arangod/Pregel/Algos/CMakeLists.txt
  arangod/Pregel/Algos/DMID/CMakeLists.txt
  arangod/Pregel/Algos/EffectiveCloseness/CMakeLists.txt
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/Conductor/CMakeLists.txt
  arangod/Pregel/REST/CMakeLists.txt
  arangod/Pregel/REST/RestControlPregelHandler.cpp
  arangod/Pregel/REST/RestControlPregelHandler.h
  arangod/Pregel/REST/RestPregelHandler.cpp
  arangod/Pregel/REST/RestPregelHandler.h
  tests/CMakeLists.txt
  tests/Pregel/CMakeLists.txt
Labels: 3 Pregel

#16761 Backport fix data races to 3.10
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/ClusterQuery.h
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryOptions.h
  lib/Futures/Future.h
  tests/Cache/Rebalancer.cpp
  tests/Cache/TransactionsWithBackingStore.cpp
  tests/Fuerte/ConnectionFailuresTest.cpp
  tests/Futures/FutureTest.cpp
  tests/IResearch/IResearchFeatureTest.cpp
  tests/IResearch/IResearchViewNodeTest.cpp
  tests/Network/MethodsTest.cpp
  tsan_arangodb_suppressions.txt
Labels: TSan

#16745 BTS-933: SmartSearch error handling
  arangod/InternalRestHandler/InternalRestTraverserHandler.cpp
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
Labels: 9 Waiting for Jenkins

#16716 [PREGEL] Use message structs everywhere possible
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  arangod/Pregel/Conductor/CanceledState.cpp
  arangod/Pregel/Conductor/RecoveringState.cpp
  arangod/Pregel/Conductor/StoringState.cpp
  arangod/Pregel/Statistics.h
  arangod/Pregel/Worker.cpp
  arangod/Pregel/Worker.h
  arangod/Pregel/WorkerConductorMessages.h
  lib/Inspection/Access.h
  tests/Basics/InspectionTest.cpp
Labels: 3 Pregel

#16765 Fix loophole for creating duplicate keys
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/RemoteExecutor.cpp
  tests/js/server/aql/aql-optimizer-rule-distribute-in-cluster.js
Labels: 3 AQL

#16760 Fix data race on query vptr
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  tests/IResearch/IResearchViewNodeTest.cpp
Labels: TSan

#16769 [CMAKE] Supporting Mac M1
  CMakeLists.txt
Labels: 3 Build, 4 MacOSX

#16778 Windows testing scripts
  scripts/startLocalCluster.bat
  scripts/unittest.ps1
Labels: 4 Windows, 3 - Testing

#16727 [PREGEL] Hide (de)serialization of messages inside Conductor::sendToAllDBServers function
  arangod/Aql/Functions.cpp
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  arangod/Pregel/Conductor/CanceledState.cpp
  arangod/Pregel/Conductor/DoneState.cpp
  arangod/Pregel/Conductor/FatalErrorState.cpp
  arangod/Pregel/Conductor/RecoveringState.cpp
  arangod/Pregel/Conductor/StoringState.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Statistics.h
  arangod/Pregel/Worker.cpp
  arangod/Pregel/WorkerConductorMessages.h
Labels: 3 Pregel

#16737 [PREGEL] Return pregel results struct instead of using VPackBuilder
  arangod/Aql/Functions.cpp
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  arangod/Pregel/Conductor/CanceledState.h
  arangod/Pregel/Conductor/ComputingState.h
  arangod/Pregel/Conductor/DoneState.cpp
  arangod/Pregel/Conductor/DoneState.h
  arangod/Pregel/Conductor/FatalErrorState.cpp
  arangod/Pregel/Conductor/FatalErrorState.h
  arangod/Pregel/Conductor/InErrorState.h
  arangod/Pregel/Conductor/InitialState.h
  arangod/Pregel/Conductor/LoadingState.h
  arangod/Pregel/Conductor/RecoveringState.h
  arangod/Pregel/Conductor/State.h
  arangod/Pregel/Conductor/StoringState.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Worker.cpp
  arangod/Pregel/Worker.h
  arangod/V8Server/v8-collection.cpp
Labels: 3 Pregel

#16732 BTS-325 Collection Validation Edge/Vertex API Gharial
  arangod/Graph/GraphOperations.cpp
  lib/Rest/GeneralResponse.cpp
  tests/js/client/shell/api/general-graph.js
Labels: 3 API, 3 Graph

#16774 Cleanup of ast-modifications in TraversalExecutor
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalExecutor.h
  arangod/Graph/Enumerators/OneSidedEnumerator.cpp
Labels: 3 AQL

#16770 Added docublocks for HTTP Graph creation API
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Labels: 3 Documentation

#16702 Feature/reprio test definitions (#16617)
  tests/test-definitions.txt
Labels: 3 - Testing

#16701 Feature/reprio test definitions (#16617)
  tests/test-definitions.txt
Labels: 3 - Testing

#16750 fix an invalid attribute access
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  tests/js/server/aql/aql-queries-optimizer.js
Labels: 3 AQL, 3 Optimizer

#16749 fix an invalid attribute access
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  tests/js/server/aql/aql-queries-optimizer.js
Labels: 3 AQL, 3 Optimizer

#16785 remove duplicates
  tests/test-definitions.txt
Labels: 3 - Testing

#16730 Bug fix/fe 142 remove edge after cancel
  js/apps/system/_admin/aardvark/APP/react/src/views/g6graphs/AddEdgeModal.js
  js/apps/system/_admin/aardvark/APP/react/src/views/g6graphs/G6JsGraph.jsx
Labels: 1 Bug, 3 UI

#16731 bug-fix/FE-141 Add a help modal
  js/apps/system/_admin/aardvark/APP/react/src/views/g6graphs/Headerinfo.js
  js/apps/system/_admin/aardvark/APP/react/src/views/g6graphs/HelpModal.js
Labels: 1 Bug, 3 UI

#16728 bug-fix/FE-139 Apply node color correctly after receiving data
  js/apps/system/_admin/aardvark/APP/aardvark.js
Labels: 1 Bug, 3 UI

#16766 Bug fix/bts 722
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Graph/PathType.cpp
  arangod/Graph/PathType.h
  tests/js/server/aql/aql-graph.js
Labels: 3 AQL, 3 Graph, 9 Waiting for Jenkins

#16777 Docs: Fix `/_api/control_pregel` HTTP API descriptions
  Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
  Documentation/DocuBlocks/Rest/Pregel/1_struct.md
  Documentation/DocuBlocks/Rest/Pregel/delete_api_control_pregel_cancel.md
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_overview.md
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
  Documentation/DocuBlocks/Rest/Pregel/post_api_control_pregel_start.md
Labels: 3 Documentation, 3 API, 3 Pregel

#16768 Fix loophole for creating duplicate keys
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-distribute-in-cluster.js
Labels: 3 AQL, 3 Cluster

#16767 Fix loophole for creating duplicate keys
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-distribute-in-cluster.js
Labels: 3 AQL, 3 Cluster

#16776 [CINFRA-523] Set assumedWaitForSync when creating replicated log
  arangod/Replication2/ReplicatedLog/SupervisionAction.h
  tests/Replication2/Helper/ModelChecker/Predicates.h
  tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
Labels: cinfra

#16779 Docs: Fix /_api/control_pregel HTTP API descriptions
  Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
  Documentation/DocuBlocks/Rest/Pregel/1_struct.md
  Documentation/DocuBlocks/Rest/Pregel/delete_api_control_pregel_cancel.md
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_overview.md
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
  Documentation/DocuBlocks/Rest/Pregel/post_api_control_pregel_start.md
Labels: 3 Documentation, 3 API, 3 Pregel

#16780 Added forward port for bug-fix-3.9/distinguish-query-options-warning-…
  CHANGELOG
  arangod/Aql/IndexHint.cpp
Labels: 3 AQL

#16794 [PREGEL] Fix staging bugs
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/PregelFeature.cpp
Labels: 3 Pregel

#16632 BTS-913: Abort startup if timezone is not configured properly. (#16593)
  CHANGELOG
  lib/ApplicationFeatures/TimeZoneFeature.cpp
Labels: 1 Bug

#16631 BTS-913: Abort startup if timezone is not configured properly. (#16593)
  CHANGELOG
  lib/ApplicationFeatures/TimeZoneFeature.cpp
Labels: 1 Bug

#16682 Fix incorrect destroy order that cause data race 3.8
  arangod/IResearch/IResearchLink.cpp
Labels: ASan

#16735 Fixed illegal optimizer rule on multiple consecutive SORTs (3.8)
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-collect-count.js
  tests/js/server/aql/aql-queries-optimizer-sort-cluster.js
Labels: 3 AQL, 3 Optimizer

#16734 Fixed illegal optimizer rule on multiple consecutive SORTs (3.9)
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-collect-count.js
  tests/js/server/aql/aql-queries-optimizer-sort-cluster.js
Labels: 3 AQL, 9 Waiting for Jenkins, 3 Optimizer

#16741 [BTS-721] Added distinguishing warning messages for query options index hint
  CHANGELOG
  arangod/Aql/IndexHint.cpp
Labels: 3 AQL

#16783 [CMake] Require more recent cmake
  CMakeLists.txt
Labels: 3 Build

#16598 [3.9] Fix potential deadlock in rocksdb compaction.
  3rdParty/rocksdb/6.27/db/compaction/compaction_picker_level.cc
  CHANGELOG
Labels: 3 RocksDB

#16681 Fix incorrect destroy order that cause data race 3.9
  arangod/IResearch/IResearchLink.cpp
Labels: ASan

#16756 fix "transaction not found" issues
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/RestHandler/RestControlPregelHandler.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  tests/js/client/load-balancing/load-balancing-cursor-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-queries-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
  tests/js/client/restart/test-restart-coordinator-transactions.js
Labels: 3 Cluster, 3 Transaction

#16755 fix "transaction not found" issues
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/RestHandler/RestControlPregelHandler.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  tests/js/client/load-balancing/load-balancing-cursor-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-queries-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
  tests/js/client/restart/test-restart-coordinator-transactions.js
Labels: 3 Cluster, 3 Transaction

#16801 [CINFRA-528] Add commandline option to set default replication version.
  arangod/Replication2/Version.h
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/VocBase/VocbaseInfo.cpp
Labels: cinfra

#16543 Fixes for RocksDB throttle
  CHANGELOG
  arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
  arangod/RocksDBEngine/Listeners/RocksDBThrottle.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 3 RocksDB

#16805 [PREGEL] Use wrapper class around ExecutionNumber
  arangod/Aql/Functions.cpp
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  arangod/Pregel/ExecutionNumber.cpp
  arangod/Pregel/ExecutionNumber.h
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/GraphStore.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/REST/RestControlPregelHandler.cpp
  arangod/Pregel/WorkerConductorMessages.h
  arangod/Pregel/WorkerConfig.cpp
  arangod/Pregel/WorkerConfig.h
  arangod/V8Server/v8-collection.cpp
Labels: 3 Pregel

#16806 re-add functions lost in merchcident of cd74fb3501276ae1efd4e40b5e48d8448021c4f3
  js/common/modules/@arangodb/test-helper-common.js
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  js/server/modules/@arangodb/test-helper.js
  tests/js/server/resilience/failover/resilience-failure-oracle.js
  tests/js/server/resilience/move/moving-shards-cluster.js
Labels: 3 - Testing

#16813 fix assertion
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
Labels: 3 Cluster, 3 - Testing

#16818 Add progress reporting to WAL recovery
  CHANGELOG
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
Labels: 3 Recovery

#16814 [CMAKE] Move building SEPP into its own place
  CMakeLists.txt
  tests/CMakeLists.txt
  tests/sepp/CMakeLists.txt
Labels: 3 Build

#16836 Added headers for graph creation examples
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Labels: 3 Documentation

#16812 fix assertion
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
Labels: 3 Cluster, 3 - Testing

#16564 [PREGEL] Test SSSP
  js/common/modules/@arangodb/graph/graphs-generation.js
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/common/shell/shell-pregel-components.js
Labels: 3 Pregel, 3 - Testing

#16834 Bug fix 3.10/handle not in nested search
  CHANGELOG
  arangod/Aql/OptimizerUtils.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  tests/js/server/aql/aql-inverted-index.js
Labels: 3 ArangoSearch

#16837 Documentation 3.10/add topics for graph creations
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Labels: 3 Documentation

#16833 fix use-after-scope in test
  tests/Aql/AqlSharedExecutionBlockImplTest.cpp
Labels: 3 RocksDB

#16852 Feature/apm 128 leftovers 2 (#16826)
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/IResearchViewOptimizerRules.h
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/CMakeLists.txt
  arangod/IResearch/AqlHelper.cpp
  arangod/IResearch/AqlHelper.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchOrderFactory.cpp
  arangod/IResearch/SearchFuncReplace.cpp
  arangod/IResearch/SearchFuncReplace.h
  js/common/modules/@arangodb/aql/explainer.js
Labels: 3 ArangoSearch

#16854 Bug fix 3.10/search 329 fix nested removes
  CHANGELOG
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchKludge.h
  arangod/IResearch/IResearchLink.cpp
Labels: 3 AQL, 3 Arangosh

#16858 exclude some tests from TSan runs as well (#16853)
  js/client/modules/@arangodb/testutils/test-utils.js
Labels: 3 - Testing, TSan

#16815 Add sources directly to cmake-targets in enterprise
  CMakeLists.txt
  arangod/CMakeLists.txt
  client-tools/CMakeLists.txt
  lib/CMakeLists.txt
  tests/CMakeLists.txt
  tests/IResearch/CMakeLists.txt
Labels: cmake improvements

#16738 [PREGEL] Logging for Pregel soft shutdown fail
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Worker.cpp
  tests/js/client/restart/test-soft-shutdown-cluster.js
Labels: 3 Pregel

#16871 Bug fix 3.10/SEARCH-328 fix cookie key
  CHANGELOG
  arangod/IResearch/IResearchInvertedIndex.cpp
  tests/js/server/aql/aql-inverted-index.js
Labels: 1 Bug, 3 ArangoSearch

#16860 remove unused cmake variable for RocksDB version
  3rdParty/CMakeLists.txt
  CMakeLists.txt
Labels: cmake improvements

#16791 Cleanup of ast-modifications in TraversalExecutor (3.10)
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalExecutor.h
  arangod/Graph/Enumerators/OneSidedEnumerator.cpp
Labels: 3 AQL, 3 Graph, 9 Review Required

#16797 Added EnterpriseGraph Dump & Restore Tests
  arangod/Sharding/ShardingFeature.cpp
  arangod/Sharding/ShardingFeature.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/vocbase.cpp
  tests/js/server/dump/dump-authentication.js
  tests/js/server/dump/dump-cluster.js
  tests/js/server/dump/dump-modified.js
  tests/js/server/dump/dump-setup-cluster.js
  tests/js/server/dump/dump-setup-common.inc
  tests/js/server/dump/dump-setup-mixed.js
  tests/js/server/dump/dump-setup.js
  tests/js/server/dump/dump-test.inc
  tests/js/server/dump/dump.js
  tests/test-definitions.txt
Labels: 3 Graph, 9 Review Required

#16816 Add progress reporting for WAL recovery
  CHANGELOG
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
Labels: 3 Recovery

#16817 Add progress reporting to WAL recovery
  CHANGELOG
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
Labels: 3 RocksDB, 3 Recovery

#16849 Fix comparison of JSON schema data
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/VocBase/Validators.cpp
  arangod/VocBase/Validators.h
Labels: 3 Schema Validation

#16867 Fixing testSingleTransactionIntermediateCommitsOnFollowerWithRollback…
  tests/js/client/shell/shell-transaction-intermediate-commit-cluster.js
Labels: 3 - Testing

#16866 Fixing testSingleTransactionIntermediateCommitsOnFollowerWithRollback
  tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
Labels: 3 - Testing

#16839 add hint for sparse indexes to UI
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/indicesView.ejs
Labels: 3 UI

#16857 [3.10] Move transitive dependencies
  .gitignore
  CHANGELOG
  LICENSES-OTHER-COMPONENTS.md
  js/node/node_modules/.package-lock.json
  js/node/node_modules/is-wsl/readme.md
  js/node/node_modules/media-typer/HISTORY.md
  js/node/node_modules/node-netstat/node_modules/is-wsl/index.js
  js/node/node_modules/node-netstat/node_modules/is-wsl/license
  js/node/node_modules/node-netstat/node_modules/is-wsl/package.json
  js/node/node_modules/type-is/node_modules/media-typer/LICENSE
  js/node/node_modules/type-is/node_modules/media-typer/index.js
  js/node/node_modules/type-is/node_modules/media-typer/package.json
  js/node/package-lock.json
  js/node/package.json
Labels: 9 Waiting for Jenkins, 3 JS API, dependencies, 3.10

#16856 Move transitive dependencies
  .gitignore
  CHANGELOG
  LICENSES-OTHER-COMPONENTS.md
  js/node/node_modules/.package-lock.json
  js/node/node_modules/is-wsl/readme.md
  js/node/node_modules/media-typer/HISTORY.md
  js/node/node_modules/node-netstat/node_modules/is-wsl/index.js
  js/node/node_modules/node-netstat/node_modules/is-wsl/license
  js/node/node_modules/node-netstat/node_modules/is-wsl/package.json
  js/node/node_modules/type-is/node_modules/media-typer/LICENSE
  js/node/node_modules/type-is/node_modules/media-typer/index.js
  js/node/node_modules/type-is/node_modules/media-typer/package.json
  js/node/package-lock.json
  js/node/package.json
Labels: 9 Waiting for Jenkins, 3 JS API, dependencies

#16850 Fix comparison of JSON schema data
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/VocBase/Validators.cpp
  arangod/VocBase/Validators.h
Labels: 3 Schema Validation

#16851 Fix comparison of JSON schema data
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/VocBase/Validators.cpp
  arangod/VocBase/Validators.h
Labels: 3 Schema Validation

#16873 SEARCH-342 fix includeAllFields handling, backport to 3.10
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/IResearch/IResearchFilterFactory.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/Search.cpp
  arangod/IResearch/Search.h
Labels: 1 Bug, 3 ArangoSearch

#16876 Fix chaos test result transport
  js/client/modules/@arangodb/testsuites/chaos.js
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: 3 - Testing

#16790 BTS-325 Collection Validation Edge/Vertex API Gharial (3.10)
  arangod/Graph/GraphOperations.cpp
  lib/Rest/GeneralResponse.cpp
  tests/js/client/shell/api/general-graph.js
Labels: 3 API, 3 Graph, 9 Review Required

#16846 [BTS-951] Fix removeUnnecessaryRemoteScatterRule
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
Labels: 1 Bug

#16883 Delete pregel recovery mode
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  arangod/Pregel/Conductor/CMakeLists.txt
  arangod/Pregel/Conductor/CanceledState.h
  arangod/Pregel/Conductor/ComputingState.cpp
  arangod/Pregel/Conductor/ComputingState.h
  arangod/Pregel/Conductor/DoneState.h
  arangod/Pregel/Conductor/FatalErrorState.h
  arangod/Pregel/Conductor/InErrorState.cpp
  arangod/Pregel/Conductor/InErrorState.h
  arangod/Pregel/Conductor/InitialState.h
  arangod/Pregel/Conductor/LoadingState.h
  arangod/Pregel/Conductor/RecoveringState.cpp
  arangod/Pregel/Conductor/RecoveringState.h
  arangod/Pregel/Conductor/State.h
  arangod/Pregel/Conductor/StoringState.cpp
  arangod/Pregel/Conductor/StoringState.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/Recovery.cpp
  arangod/Pregel/Recovery.h
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker.cpp
  arangod/Pregel/Worker.h
  arangod/Pregel/WorkerConductorMessages.h
Labels: 3 Pregel

#16890 Bug fix 3.10/fix chaos test identifiers
  js/client/modules/@arangodb/testsuites/chaos.js
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: 3 - Testing

#16865 Fixed race condition in replication2 test
  tests/js/client/shell/shell-admin-cluster-rebalance.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: 1 Bug, cinfra

#16904 [3.10] Fix SEARCH-364 and SEARCH-347
  CHANGELOG
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndex.h
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  tests/IResearch/IResearchInvertedIndexMetaTest.cpp
Labels: 3 ArangoSearch

#16897 fix dumping of active failover agency
  js/client/modules/@arangodb/testsuites/resilience.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing

#16916 Make SUBSTRING_BYTES work similar to SUBSTRING (#16912)
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  tests/IResearch/IResearchQueryAndTest.cpp
  tests/js/server/aql/aql-functions-string.js
Labels: 3 AQL

#16917 Bug fix 3.10/search 368
  CHANGELOG
  arangod/Aql/OptimizerUtils.cpp
  tests/js/server/aql/aql-inverted-index.js
Labels: 3 ArangoSearch

#16855 [PREGEL]Refactor/move worker to own directory
  arangod/Aql/Functions.cpp
  arangod/Pregel/AlgoRegistry.h
  arangod/Pregel/Algorithm.h
  arangod/Pregel/Algos/AIR/AIR.cpp
  arangod/Pregel/Algos/AIR/WorkerContext.h
  arangod/Pregel/Algos/LineRank.cpp
  arangod/Pregel/Algos/ShortestPath.cpp
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/GraphStore.h
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/OutgoingCache.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Recovery.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/VertexComputation.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/Worker/WorkerConfig.cpp
  arangod/Pregel/Worker/WorkerConfig.h
  arangod/Pregel/Worker/WorkerContext.h
  arangod/V8Server/v8-collection.cpp
Labels: 3 Pregel

#16922 [PREGEL] Extract all conductor stuff into separate dir
  arangod/Aql/Functions.cpp
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/Conductor/CMakeLists.txt
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/CMakeLists.txt
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/CanceledState.h
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/ComputingState.h
  arangod/Pregel/Conductor/States/DoneState.cpp
  arangod/Pregel/Conductor/States/DoneState.h
  arangod/Pregel/Conductor/States/FatalErrorState.cpp
  arangod/Pregel/Conductor/States/FatalErrorState.h
  arangod/Pregel/Conductor/States/InErrorState.cpp
  arangod/Pregel/Conductor/States/InErrorState.h
  arangod/Pregel/Conductor/States/InitialState.cpp
  arangod/Pregel/Conductor/States/InitialState.h
  arangod/Pregel/Conductor/States/LoadingState.cpp
  arangod/Pregel/Conductor/States/LoadingState.h
  arangod/Pregel/Conductor/States/State.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/Conductor/States/StoringState.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/REST/RestControlPregelHandler.cpp
  arangod/Pregel/Worker/CMakeLists.txt
  arangod/Pregel/Worker/Worker.cpp
  arangod/V8Server/v8-collection.cpp
Labels: 3 Pregel

#16811 [PREGEL] implement load graph with future
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/LoadingState.cpp
  arangod/Pregel/Conductor/States/LoadingState.h
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/GraphStore.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/WorkerConductorMessages.h
  arangod/Pregel/WorkerInterface.h
Labels: 3 Pregel

#16925 [3.9] SEARCH-350
  3rdParty/iresearch/core/formats/columnstore2.cpp
  3rdParty/iresearch/core/index/index_writer.cpp
  CHANGELOG
Labels: 3 ArangoSearch

#16903 [3.9] [BTS-951] Fix removeUnnecessaryRemoteScatterRule
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
Labels: 3 Optimizer

#16914 BTS-959 Fix 3.10
  arangod/IResearch/IResearchLink.cpp
  tests/IResearch/IResearchInvertedIndexConditionTest.cpp
  tests/IResearch/IResearchInvertedIndexIteratorTest.cpp
  tests/IResearch/IResearchLinkTest.cpp
  tests/IResearch/common.cpp
  tests/IResearch/common.h
  tests/Mocks/IResearchInvertedIndexMock.cpp
  tests/Mocks/IResearchInvertedIndexMock.h
  tests/Mocks/IResearchLinkMock.h
Labels: 3 ArangoSearch

#16892 [CINFRA-427] create collection group
  arangod/CMakeLists.txt
  arangod/Cluster/ServerDefaults.cpp
  arangod/Cluster/ServerDefaults.h
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  arangod/VocBase/Properties/PlanCollection.cpp
  arangod/VocBase/Properties/PlanCollection.h
  js/client/modules/@arangodb/arango-database.js
  lib/Inspection/VPack.h
  tests/CMakeLists.txt
  tests/VocBase/PlanCollectionTest.cpp
  tests/js/client/shell/api/collection.js
  tests/js/common/replication_api/shell-api-replication-global.js
  tests/js/common/shell/shell-figures-rocksdb.js
  tests/js/common/shell/shell-one-shard.js
Labels: cinfra

#16894 Bug fix/bts 722 (3.10)
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Graph/PathType.cpp
  arangod/Graph/PathType.h
  tests/js/server/aql/aql-graph.js
Labels: 3 AQL, 3 Graph

#16940 MBkkt backport fixes
  CHANGELOG
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndex.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/IResearchView.h
  arangod/IResearch/Search.cpp
  arangod/IResearch/ViewSnapshot.cpp
  arangod/IResearch/ViewSnapshot.h
  lib/Basics/locks-win32.cpp
  lib/Basics/locks-win32.h
  tests/IResearch/IResearchInvertedIndexConditionTest.cpp
  tests/IResearch/IResearchLinkTest.cpp
  tests/js/common/shell/shell-view-search-alias.js
Labels: 3 ArangoSearch
