Repository arangodb/arangodb, pull requests merged in 2022-02, with the labels that each got.

#15637 add "Filtered" column to query profiling output
  CHANGELOG
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionNodeStats.h
  arangod/Aql/ExecutionStats.cpp
  arangod/Aql/ExecutorExpressionContext.cpp
  arangod/Aql/ExecutorExpressionContext.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
  arangod/Aql/Stats.h
  js/common/modules/@arangodb/aql/explainer.js
  js/server/modules/@arangodb/testutils/aql-profiler-test-helper.js
  tests/js/server/aql/aql-profiler-cluster.js
  tests/js/server/aql/aql-profiler-noncluster-nightly.js
  tests/js/server/aql/aql-profiler-noncluster.js
  tests/js/server/aql/aql-profiler.js
Labels: cla-signed

#15627 Change some default values for RocksDB memory usage
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: cla-signed

#15649 Harden velocypack validator after fuzz testing
  3rdParty/velocypack/include/velocypack/Slice.h
  3rdParty/velocypack/src/Validator.cpp
  3rdParty/velocypack/tests/testsValidator.cpp
Labels: cla-signed

#15623 BTS-621 fix
  CHANGELOG
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  tests/IResearch/IResearchLinkTest.cpp
Labels: cla-signed

#15653 Ensure feature creation order at compile time
  arangod/Cluster/ClusterFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationMetricsFeature.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLogFeature.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/arangod.h
  arangod/Transaction/ManagerFeature.cpp
  arangod/V8Server/V8DealerFeature.cpp
  client-tools/Backup/BackupFeature.cpp
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Shell/ClientFeature.h
  lib/ApplicationFeatures/ApplicationServer.h
  lib/ApplicationFeatures/ConfigFeature.h
Labels: cla-signed

#15608 Build/windows and wsl cleanup
  3rdParty/V8/gypfiles/detect_v8_host_arch.py
  3rdParty/V8/gypfiles/download.py
  3rdParty/iresearch/core/shared.hpp
  3rdParty/iresearch/core/utils/object_pool.hpp
  3rdParty/iresearch/external/CMakeLists.txt
  3rdParty/iresearch/external/fastText/CMakeLists.txt
  3rdParty/s2geometry/dfefe0c/CMakeLists.txt
  3rdParty/snappy/snappy-1.1.9/CMakeLists.txt
  3rdParty/velocypack/cmake/Modules/AR_CompilerSettings.cmake
  3rdParty/velocypack/include/velocypack/Iterator.h
  CMakeLists.txt
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/IResearchViewNode.cpp
  arangod/CMakeLists.txt
  arangod/RestHandler/RestSystemReportHandler.cpp
  arangod/RestServer/LogBufferFeature.cpp
  arangod/RestServer/PrivilegeFeature.cpp
  arangod/RestServer/PrivilegeFeature.h
  arangod/RestServer/WindowsServiceFeature.cpp
  arangod/Utils/OperationOptions.cpp
  client-tools/CMakeLists.txt
  lib/Basics/Mutex.h
  lib/Basics/files.cpp
  lib/Basics/hashes.h
  lib/Basics/process-utils.cpp
  lib/CMakeLists.txt
  lib/Containers/MerkleTree.cpp
  lib/Zip/iowin32.cpp
  tests/Aql/ExecutionBlockImplTestInstances.cpp
  tests/Aql/MockTypedNode.h
  tests/CMakeLists.txt
Labels: 9 Ready to Merge, cla-signed

#15655 [CINFRA-237] fix graceful leader replacement
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra, cla-signed

#15665 fix startup dependency between features
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: cla-signed

#15616 Remove v1 metrics
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/MaintenanceWorker.cpp
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterEngine.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/Metrics/Batch.h
  arangod/Metrics/Counter.cpp
  arangod/Metrics/Counter.h
  arangod/Metrics/CounterBuilder.h
  arangod/Metrics/Gauge.h
  arangod/Metrics/GaugeBuilder.h
  arangod/Metrics/Histogram.h
  arangod/Metrics/Metric.cpp
  arangod/Metrics/Metric.h
  arangod/Metrics/MetricsFeature.cpp
  arangod/Metrics/MetricsFeature.h
  arangod/RestHandler/RestEngineHandler.cpp
  arangod/RestHandler/RestMetricsHandler.cpp
  arangod/RestHandler/RestSupportInfoHandler.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  arangod/StorageEngine/StorageEngine.cpp
  arangod/StorageEngine/StorageEngine.h
  arangod/V8Server/v8-vocbase.cpp
  js/client/modules/@arangodb/test-helper.js
  js/server/modules/@arangodb/test-helper.js
  tests/IResearch/IResearchLinkTest.cpp
  tests/js/client/communication/test-communication.js
  tests/js/client/http/cluster-metrics-cluster-spec.js
  tests/js/client/server_parameters/statistics-history-off.js
  tests/js/client/server_parameters/statistics-off.js
  tests/js/client/server_parameters/statistics-on.js
  tests/js/client/server_parameters/test-export-document-metrics-on-noncluster.js
  tests/js/client/server_parameters/test-global-memory-limit.js
  tests/js/client/server_parameters/test-memory-limit.js
  tests/js/client/server_parameters/test-statistics-enabled-false.js
  tests/js/client/shell/shell-check-metrics-move-noncluster.js
  tests/js/client/shell/shell-process-metrics-cluster.js
Labels: cla-signed

#14913 Set default module root to cwd
  CHANGELOG
  js/client/client.js
  js/common/bootstrap/modules.js
Labels: 9 Ready to Merge, 3 JS API, cla-signed

#15664 Fix sanitizer issues in LogContext
  lib/Logger/LogContext.h
Labels: cla-signed

#15677 fix potentially dangling references
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
Labels: 3 Cluster, cla-signed

#15675 fix potentially dangling references
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
Labels: 3 Cluster, cla-signed

#15678 fix potentially dangling references
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
Labels: cla-signed

#15674 fix potentially dangling references
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
Labels: 3 Cluster, cla-signed

#15679 decrease loglevel for less noise in development.
  arangod/Cluster/CreateDatabase.cpp
Labels: cla-signed

#15690 Bug fix/window executor in subqueries
  CHANGELOG
  arangod/Aql/WindowExecutor.cpp
  tests/Aql/WindowExecutorTest.cpp
Labels: 1 Bug, cla-signed

#15696 Fix unstable Containers test
  tests/IResearch/ContainersTest.cpp
Labels: cla-signed

#15658 Remove kludge read_write_mutex and fix data race in link metrics and another in test
  3rdParty/boost/CMakeLists.txt
  arangod/CMakeLists.txt
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterEngine.h
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchKludge.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/StorageEngine/StorageEngine.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/LogicalDataSource.cpp
  arangod/VocBase/LogicalDataSource.h
  arangod/VocBase/LogicalView.cpp
  arangod/VocBase/LogicalView.h
  arangod/VocBase/vocbase.cpp
  tests/IResearch/IResearchFeatureTest.cpp
  tests/IResearch/IResearchLinkTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/Mocks/IResearchLinkMock.h
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/RestHandler/RestUsersHandlerTest.cpp
  tests/RestHandler/RestViewHandlerTest.cpp
  tests/Utils/CollectionNameResolverTest.cpp
  tests/V8Server/V8UsersTest.cpp
  tests/V8Server/V8ViewsTest.cpp
  tests/VocBase/LogicalDataSourceTest.cpp
  tests/VocBase/LogicalViewTest.cpp
  tests/VocBase/VocbaseTest.cpp
Labels: cla-signed

#15666 [CINFRA-239] Detailed global status
  arangod/Agency/AsyncAgencyComm.cpp
  arangod/Agency/AsyncAgencyComm.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Replication2/Methods.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.h
  tests/Replication2/Serialization/LogStatusTest.cpp
  tests/js/common/shell/shell-replicated-logs-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra, cla-signed

#15567 [CINFRA-177] Replicated State Vocbase Maintenance
  arangod/Agency/AgencyPaths.cpp
  arangod/Agency/AgencyPaths.h
  arangod/Agency/AgencyStrings.h
  arangod/CMakeLists.txt
  arangod/Cluster/Action.cpp
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/DBServerAgencySync.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/Maintenance.h
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/UpdateReplicatedStateAction.cpp
  arangod/Cluster/UpdateReplicatedStateAction.h
  arangod/Replication2/ReplicatedState/AgencySpecification.cpp
  arangod/Replication2/ReplicatedState/AgencySpecification.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/LeaderStateManager.h
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/ReplicatedStateCore.h
  arangod/Replication2/ReplicatedState/ReplicatedStateFeature.cpp
  arangod/Replication2/ReplicatedState/StateCommon.cpp
  arangod/Replication2/ReplicatedState/StateCommon.h
  arangod/Replication2/ReplicatedState/StateStatus.cpp
  arangod/Replication2/ReplicatedState/StateStatus.h
  arangod/Replication2/ReplicatedState/UpdateReplicatedState.cpp
  arangod/Replication2/ReplicatedState/UpdateReplicatedState.h
  arangod/Replication2/Streams/LogMultiplexer.tpp
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  js/server/modules/@arangodb/testutils/replicated-state-helper.js
  js/server/modules/@arangodb/testutils/replicated-state-predicates.js
  lib/Logger/LogTopic.cpp
  tests/Maintenance/MaintenanceTest.cpp
  tests/Network/MethodsTest.cpp
  tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
  tests/Replication2/ReplicatedState/LeaderRecoveryTest.cpp
  tests/Replication2/ReplicatedState/ReplicatedStateTest.cpp
  tests/js/server/replication2/replication2-maintenance-replicated-state-cluster.js
Labels: cinfra, cla-signed

#15699 [3.8] BTS-501
  tests/IResearch/IResearchFeature-test.cpp
Labels: 3 - Testing, 3 ArangoSearch, cla-signed

#15633 [CINFRA-186] Replicated State Supervision
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/CMakeLists.txt
  arangod/Replication2/ReplicatedState/AgencySpecification.cpp
  arangod/Replication2/ReplicatedState/AgencySpecification.h
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/Replication2/ReplicatedState/Supervision.h
  arangod/Replication2/ReplicatedState/SupervisionAction.cpp
  arangod/Replication2/ReplicatedState/SupervisionAction.h
  js/server/modules/@arangodb/testutils/replicated-state-predicates.js
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
  tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
Labels: cinfra, cla-signed

#15702 Shutdown heartbeat thread properly
  arangod/Cluster/ClusterFeature.cpp
Labels: cla-signed

#15703 added missing jemalloc dependency to greenspun
  tests/Greenspun/CMakeLists.txt
Labels: cla-signed

#15704 [CINFRA-249] Replicated Maintenance Actions Fast Track
  arangod/Cluster/UpdateReplicatedLogAction.cpp
  arangod/Cluster/UpdateReplicatedStateAction.cpp
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
Labels: cinfra, cla-signed

#15669 Improved performance of nested loop joins for vpack index
  CHANGELOG
  arangod/Aql/ExecutionStats.cpp
  arangod/Aql/ExecutionStats.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  arangod/Aql/Stats.h
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/Indexes/SimpleAttributeEqualityMatcher.cpp
  arangod/Indexes/SimpleAttributeEqualityMatcher.h
  arangod/Indexes/SortedIndexAttributeMatcher.cpp
  arangod/Indexes/SortedIndexAttributeMatcher.h
  arangod/RocksDBEngine/RocksDBKeyBounds.cpp
  arangod/RocksDBEngine/RocksDBKeyBounds.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  arangod/RocksDBEngine/RocksDBZkdIndex.cpp
  js/server/modules/@arangodb/aql-helper.js
  js/server/modules/@arangodb/testutils/aql-profiler-test-helper.js
  tests/js/server/aql/aql-modify-cluster.js
  tests/js/server/aql/aql-modify-noncluster.js
  tests/js/server/aql/aql-modify-subqueries.js
  tests/js/server/aql/aql-vpack-index-rearming.js
Labels: cla-signed

#15693 Bug fix/window executor in subqueries api hardening
  arangod/Aql/AllRowsFetcher.cpp
  arangod/Aql/AqlItemBlockInputMatrix.cpp
  arangod/Aql/AqlItemBlockInputMatrix.h
  arangod/Aql/AqlItemBlockInputRange.cpp
  arangod/Aql/AqlItemBlockInputRange.h
  arangod/Aql/ConstFetcher.cpp
  arangod/Aql/DistinctCollectExecutor.cpp
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionState.h
  arangod/Aql/FilterExecutor.cpp
  arangod/Aql/HashedCollectExecutor.cpp
  arangod/Aql/MultiAqlItemBlockInputRange.cpp
  arangod/Aql/MultiAqlItemBlockInputRange.h
  arangod/Aql/MultiDependencySingleRowFetcher.cpp
  arangod/Aql/ReturnExecutor.cpp
  arangod/Aql/SingleRowFetcher.cpp
  arangod/Aql/SortedCollectExecutor.cpp
  arangod/Aql/WindowExecutor.cpp
  tests/Aql/AqlItemBlockInputRangeTest.cpp
  tests/Aql/AqlItemMatrixTest.cpp
  tests/Aql/AqlSharedExecutionBlockImplTest.cpp
  tests/Aql/EnumerateCollectionExecutorTest.cpp
  tests/Aql/EnumerateListExecutorTest.cpp
  tests/Aql/IdExecutorTest.cpp
  tests/Aql/InputRangeTest.cpp
  tests/Aql/KShortestPathsExecutorTest.cpp
  tests/Aql/ShortestPathExecutorTest.cpp
  tests/Aql/SortedCollectExecutorTest.cpp
  tests/Aql/TraversalExecutorTest.cpp
  tests/IResearch/IResearchViewCountApproximateTest.cpp
Labels: cla-signed

#15599 [3.8] fix race leading to 403 on coordinator insert doc
  CHANGELOG
  arangod/Cluster/FollowerInfo.h
  arangod/Transaction/Methods.cpp
Labels: 1 Bug, 3 Cluster, cla-signed

#15613 Bug fix 3.8/bts 750
  CHANGELOG
  arangod/Aql/OptimizerRulesCluster.cpp
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/SingleRemoteModificationExecutor.cpp
  tests/js/server/aql/aql-optimizer-rule-optimize-cluster-single-document-operations.js
Labels: 3 AQL, 9 Ready to Merge, cla-signed

#15625 Fixed issue #15501 (#15563)
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/HeartbeatThread.h
  arangod/V8Server/FoxxFeature.cpp
  arangod/V8Server/FoxxFeature.h
  arangod/V8Server/v8-actions.cpp
  js/server/modules/@arangodb/foxx/queues/manager.js
  tests/js/client/load-balancing/load-balancing-foxx-queues-noauth-cluster.js
  tests/js/server/shell/shell-foxx-queues.js
Labels: 3 Cluster, 9 Ready to Merge, 3 Foxx Queues, cla-signed

#15650 [3.8] more consistent rocksdb throttle in compating
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: performance, 3 RocksDB, 3 Compaction, cla-signed

#15681 reintroduce disabled shard synchronisation cancellation check
  CHANGELOG
  arangod/Agency/Supervision.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/DatabaseInitialSyncer.h
  tests/js/client/shell/shell-abort-replication-cluster.js
Labels: 3 Cluster, cla-signed

#15687 Fix nullptr access with WINDOW operation.
  CHANGELOG
  arangod/Aql/WindowNode.cpp
  tests/js/server/aql/aql-window-malarkey.js
Labels: 3 AQL, cla-signed

#15695 Bug fix/window executor in subqueries (#15690)
  CHANGELOG
  arangod/Aql/WindowExecutor.cpp
  tests/Aql/WindowExecutorTest.cpp
Labels: 1 Bug, 3 Optimizer, cla-signed

#15708 [3.8] Gracefully shutdown heartbeat thread for single server
  arangod/Cluster/ClusterFeature.cpp
Labels: 3 Cluster, cla-signed

#15697 APM-290 and some fixes
  Documentation/Metrics/arangodb_search_cleanup_time.yaml
  Documentation/Metrics/arangodb_search_commit_time.yaml
  Documentation/Metrics/arangodb_search_consolidation_time.yaml
  Documentation/Metrics/arangodb_search_index_size.yaml
  Documentation/Metrics/arangodb_search_num_docs.yaml
  Documentation/Metrics/arangodb_search_num_failed_cleanups.yaml
  Documentation/Metrics/arangodb_search_num_failed_commits.yaml
  Documentation/Metrics/arangodb_search_num_failed_consolidations.yaml
  Documentation/Metrics/arangodb_search_num_files.yaml
  Documentation/Metrics/arangodb_search_num_live_docs.yaml
  Documentation/Metrics/arangodb_search_num_segments.yaml
  Documentation/Metrics/arangosearch_num_docs.yaml
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/IResearch/GeoAnalyzer.cpp
  arangod/IResearch/IResearchAqlAnalyzer.cpp
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/VocBase/LogicalView.h
  lib/Basics/DownCast.h
  tests/IResearch/IResearchLinkCoordinatorTest.cpp
  tests/IResearch/IResearchLinkTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewNodeTest.cpp
  tests/RestHandler/RestViewHandlerTest.cpp
  tests/V8Server/V8ViewsTest.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
Labels: cla-signed

#15715 [3.8] BTS-621
  CHANGELOG
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  tests/IResearch/IResearchLink-test.cpp
Labels: cla-signed

#15564 Fixed issue #15501
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/GeneralServer/RequestLane.h
  arangod/Network/Utils.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  tests/RestHandler/RestDocumentHandler-test.cpp
Labels: 3 AQL, cla-signed

#15600 [3.9] fix race leading to 403 on coordinator insert doc
  CHANGELOG
  arangod/Cluster/FollowerInfo.h
  arangod/Transaction/Methods.cpp
Labels: 1 Bug, 3 Cluster, cla-signed

#15624 PRESUPP-445: Fix Foxx queues with multiple coordinators (#15611)
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/HeartbeatThread.h
  arangod/V8Server/FoxxFeature.cpp
  arangod/V8Server/FoxxFeature.h
  arangod/V8Server/v8-actions.cpp
  js/server/modules/@arangodb/foxx/queues/manager.js
  tests/js/client/load-balancing/load-balancing-cursor-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-foxx-queues-noauth-cluster.js
  tests/js/server/shell/shell-foxx-queues.js
Labels: 3 Cluster, 9 Ready to Merge, 3 Foxx Queues, cla-signed

#15668 [3.9] BTS-621
  CHANGELOG
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  tests/IResearch/Containers-test.cpp
  tests/IResearch/IResearchLink-test.cpp
Labels: 3 ArangoSearch, 3 Upgrade, cla-signed

#15683 reintroduce disabled shard synchronisation cancellation check
  CHANGELOG
  arangod/Agency/Supervision.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/DatabaseInitialSyncer.h
  tests/js/client/shell/shell-abort-replication-cluster.js
Labels: 3 Cluster, cla-signed

#15714 [CINFRA-251] Add meta information to empty log entries
  arangod/CMakeLists.txt
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedLog/ILogInterfaces.h
  arangod/Replication2/ReplicatedLog/InMemoryLog.h
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/ReplicatedLog/LogCore.h
  arangod/Replication2/ReplicatedLog/LogEntries.cpp
  arangod/Replication2/ReplicatedLog/LogEntries.h
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/NetworkMessages.h
  arangod/Replication2/ReplicatedLog/PersistedLog.h
  arangod/Replication2/ReplicatedState/AbstractStateMachine.tpp
  arangod/Replication2/Streams/LogMultiplexer.tpp
  arangod/Replication2/Streams/Streams.h
  arangod/RestHandler/RestLogHandler.cpp
  arangod/RestServer/arangod.cpp
  arangod/RocksDBEngine/RocksDBValue.h
  arangod/V8Server/v8-replicated-logs.cpp
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/Replication2/Mocks/FakeFollower.h
  tests/Replication2/ReplicatedLog/AppendEntriesBatchTest.cpp
  tests/Replication2/ReplicatedLog/ConcurrencyTests.cpp
  tests/Replication2/ReplicatedLog/EstablishLeadershipTest.cpp
  tests/Replication2/ReplicatedLog/RewriteLogTest.cpp
  tests/Replication2/ReplicatedLog/RocksDBLogTest.cpp
  tests/Replication2/ReplicatedLog/SimpleInsertTests.cpp
  tests/Replication2/ReplicatedLog/UpdateParticipantsFlags.cpp
  tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
Labels: cinfra, cla-signed

#15686 Fix nullptr access with WINDOW operation.
  CHANGELOG
  arangod/Aql/WindowNode.cpp
  tests/js/server/aql/aql-window-malarkey.js
Labels: 3 AQL, cla-signed

#15694 Bug fix 3.9/window executor in subqueries
  CHANGELOG
  arangod/Aql/WindowExecutor.cpp
  tests/Aql/WindowExecutorTest.cpp
Labels: 3 Optimizer, cla-signed

#15719 Add comments on how to use ApplicationServerT
  lib/ApplicationFeatures/ApplicationServer.h
Labels: cla-signed

#15707 [3.9] Gracefully shutdown heartbeat thread for single server.
  arangod/Cluster/ClusterFeature.cpp
Labels: 3 Cluster, cla-signed

#15706 removed obsolete files, more include-what-you-use
  arangod/Aql/ModificationExecutorAccumulator.h
  arangod/Cluster/ClusterRepairOperations.h
  arangod/Graph/Providers/BaseStep.h
  arangod/Pregel/Algos/DMID/DMIDMessageFormat.h
  arangod/Pregel/Algos/DMID/VertexSumAggregator.h
  arangod/Pregel/GraphSerializer.h
  arangod/Pregel/MessageCombiner.h
  arangod/RestHandler/RestHandlerCreator.h
  arangod/RocksDBEngine/RocksDBPrefixExtractor.h
  arangod/StorageEngine/StorageEngineFeature.h
  arangod/Utils/VersionTracker.h
  arangod/V8Server/v8-externals.h
  arangod/V8Server/v8-user-functions.h
Labels: cla-signed

#15717 [CINFRA-255] Unconfigured Log Replicated State Fix
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.h
  arangod/Replication2/ReplicatedLog/NetworkMessages.cpp
  arangod/Replication2/ReplicatedLog/NetworkMessages.h
  arangod/VocBase/vocbase.cpp
  tests/Replication2/Mocks/FakeFollower.cpp
  tests/Replication2/ReplicatedLog/LeaderAppendEntriesTest.cpp
  tests/Replication2/Serialization/LogStatusTest.cpp
Labels: cinfra, cla-signed

#15651 [3.9] more consistent rocksdb throttle when compating
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: performance, 3 RocksDB, 3 Compaction, cla-signed

#15654 Replace ansi-html with ansi-html-community
  CHANGELOG
  LICENSES-OTHER-COMPONENTS.md
  js/node/node_modules/.package-lock.json
  js/node/node_modules/ansi-html-community/LICENSE
  js/node/node_modules/ansi-html-community/bin/ansi-html
  js/node/node_modules/ansi-html-community/index.js
  js/node/node_modules/ansi-html-community/package.json
  js/node/node_modules/ansi-html/README.md
  js/node/package-lock.json
  js/node/package.json
  js/server/modules/@arangodb/foxx/routing.js
Labels: 1 Feature, 3 Foxx, 9 Ready to Merge, cla-signed

#15656 [3.9] Replace ansi-html with ansi-html-community
  CHANGELOG
  LICENSES-OTHER-COMPONENTS.md
  js/node/ansi-html.js
  js/node/node_modules/.package-lock.json
  js/node/node_modules/ansi-html-community/LICENSE
  js/node/node_modules/ansi-html-community/bin/ansi-html
  js/node/node_modules/ansi-html-community/index.js
  js/node/node_modules/ansi-html-community/package.json
  js/node/node_modules/ansi-html/README.md
  js/node/package-lock.json
  js/node/package.json
  js/server/modules/@arangodb/foxx/routing.js
Labels: 1 Feature, 3 Foxx, 9 Ready to Merge, cla-signed

#15680 BTS-766 | Docs: Add DocuBlock for PUT /_api/collection/<coll>/compact
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_compact.md
Labels: 3 Documentation, cla-signed

#15691 BTS-766 | Docs: Add DocuBlock for PUT /_api/collection/<coll>/compact
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_compact.md
Labels: 3 Documentation, cla-signed

#15692 BTS-766 | Docs: Add DocuBlock for PUT /_api/collection/<coll>/compact
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_compact.md
Labels: 3 Documentation, cla-signed

#15612 Added backport for BTS-750
  CHANGELOG
  arangod/Aql/OptimizerRulesCluster.cpp
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/SingleRemoteModificationExecutor.cpp
  tests/js/server/aql/aql-optimizer-rule-optimize-cluster-single-document-operations.js
Labels: 3 AQL, 9 Ready to Merge, cla-signed

#15659 Replace xmldom with @xmldom/xmldom
  CHANGELOG
  LICENSES-OTHER-COMPONENTS.md
  js/client/modules/@arangodb/testsuites/export.js
  js/node/node_modules/.package-lock.json
  js/node/node_modules/@xmldom/xmldom/LICENSE
  js/node/node_modules/@xmldom/xmldom/index.d.ts
  js/node/node_modules/@xmldom/xmldom/lib/conventions.js
  js/node/node_modules/@xmldom/xmldom/lib/dom-parser.js
  js/node/node_modules/@xmldom/xmldom/lib/dom.js
  js/node/node_modules/@xmldom/xmldom/lib/entities.js
  js/node/node_modules/@xmldom/xmldom/lib/index.js
  js/node/node_modules/@xmldom/xmldom/lib/sax.js
  js/node/node_modules/@xmldom/xmldom/package.json
  js/node/node_modules/@xmldom/xmldom/readme.md
  js/node/node_modules/xmldom/CHANGELOG.md
  js/node/node_modules/xmldom/package.json
  js/node/package-lock.json
  js/node/package.json
Labels: 1 Feature, 9 Ready to Merge, 3 - Testing, cla-signed

#15660 [3.9] Replace xmldom with @xmldom/xmldom
  CHANGELOG
  LICENSES-OTHER-COMPONENTS.md
  js/client/modules/@arangodb/testsuites/export.js
  js/node/node_modules/.package-lock.json
  js/node/node_modules/@xmldom/xmldom/LICENSE
  js/node/node_modules/@xmldom/xmldom/index.d.ts
  js/node/node_modules/@xmldom/xmldom/lib/conventions.js
  js/node/node_modules/@xmldom/xmldom/lib/dom-parser.js
  js/node/node_modules/@xmldom/xmldom/lib/dom.js
  js/node/node_modules/@xmldom/xmldom/lib/entities.js
  js/node/node_modules/@xmldom/xmldom/lib/index.js
  js/node/node_modules/@xmldom/xmldom/lib/sax.js
  js/node/node_modules/@xmldom/xmldom/package.json
  js/node/node_modules/@xmldom/xmldom/readme.md
  js/node/node_modules/xmldom/CHANGELOG.md
  js/node/node_modules/xmldom/package.json
  js/node/package-lock.json
  js/node/package.json
  js/node/xmldom.js
Labels: 1 Feature, 9 Ready to Merge, 3 - Testing, cla-signed

#15698 change log
  CHANGELOG
Labels: 3 License, cla-signed

#15724 Added changelog entry for zkd index lookahead.
  CHANGELOG
Labels: cla-signed

#15726 Refactor/traversal executor add server
  arangod/Aql/KShortestPathsNode.cpp
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalExecutor.h
  arangod/Aql/TraversalNode.cpp
  arangod/Graph/Enumerators/OneSidedEnumerator.cpp
  arangod/Graph/Providers/BaseProviderOptions.cpp
  arangod/Graph/Providers/BaseProviderOptions.h
  arangod/Graph/Providers/SingleServerProvider.cpp
  arangod/Graph/Providers/SingleServerProvider.h
  arangod/Graph/Queues/QueueTracer.cpp
  arangod/Graph/Steps/ClusterProviderStep.h
  tests/Aql/TraversalExecutorTest.cpp
  tests/Graph/GenericGraphProviderTest.cpp
  tests/Graph/SingleServerProviderTest.cpp
Labels: cla-signed

#15609 Bug fix/bts 750
  CHANGELOG
  arangod/Aql/OptimizerRulesCluster.cpp
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/SingleRemoteModificationExecutor.cpp
  tests/js/server/aql/aql-optimizer-rule-optimize-cluster-single-document-operations.js
Labels: cla-signed

#15652 more consistent rocksdb throttle when compacting
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: performance, 3 RocksDB, 3 Compaction, cla-signed

#15601 fix race leading to 403 on coordinator insert doc
  CHANGELOG
  arangod/Cluster/FollowerInfo.cpp
  arangod/Cluster/FollowerInfo.h
  arangod/Transaction/Methods.cpp
Labels: 1 Bug, 3 Cluster, cla-signed

#15730 [CINFRA-128] Spearhead.term to big
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  tests/Replication2/Mocks/FakeReplicatedLog.h
Labels: cinfra, cla-signed

#15741 [CINFRA-257] Test Error due to Plan update
  tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
Labels: cinfra

#15720 Search-240
  3rdParty/iresearch/core/CMakeLists.txt
  3rdParty/iresearch/external/fastText/CMakeLists.txt
  arangod/CMakeLists.txt
  arangod/IResearch/IResearchAnalyzerFeature.cpp
Labels: cla-signed

#15746 debug logging for rocksdb stall events only
  CHANGELOG
  arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.cpp
Labels: 1 Bug, cla-signed

#15744 [3.8] debug logging for rocksdb stall events only
  CHANGELOG
  arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.cpp
Labels: 3 RocksDB, cla-signed

#15190 Use static variable names in Foxx generator
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/generator/templates/dcRouter.js.tmpl
  js/apps/system/_admin/aardvark/APP/generator/templates/ecRouter.js.tmpl
  js/apps/system/_admin/aardvark/APP/generator/templates/main.js.tmpl
  js/apps/system/_admin/aardvark/APP/generator/templates/setup.js.tmpl
  js/apps/system/_admin/aardvark/APP/generator/templates/teardown.js.tmpl
  js/apps/system/_admin/aardvark/APP/generator/templates/test.js.tmpl
Labels: 1 Bug, 3 UI, 9 Ready to Merge, cla-signed

#15290 Bugfix for BTS-673
  CHANGELOG
  arangod/Aql/ExecutionBlockImpl.cpp
  tests/Aql/FixedOutputExecutionBlockMock.cpp
  tests/Aql/FixedOutputExecutionBlockMock.h
  tests/Aql/SubqueryEndExecutorTest.cpp
  tests/Aql/SubqueryStartExecutorTest.cpp
  tests/js/server/aql/aql-subquery-splicing-regression-2.js
Labels: cla-signed

#15734 [3.8] better long term throttle
  CHANGELOG
  arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
Labels: performance, 3 RocksDB, cla-signed

#15732 i@0.3.7
  CHANGELOG
  js/node/node_modules/.package-lock.json
  js/node/node_modules/i/LICENSE
  js/node/node_modules/i/README.md
  js/node/node_modules/i/lib/defaults.js
  js/node/node_modules/i/lib/inflect.js
  js/node/node_modules/i/lib/inflections.js
  js/node/node_modules/i/lib/methods.js
  js/node/node_modules/i/lib/native.js
  js/node/node_modules/i/lib/util.js
  js/node/node_modules/i/package.json
  js/node/package-lock.json
  js/node/package.json
Labels: 1 Bug, 9 Ready to Merge, 3 JS API, cla-signed

#15735 [3.8] i@0.3.7
  CHANGELOG
  js/node/node_modules/.package-lock.json
  js/node/node_modules/i/LICENSE
  js/node/node_modules/i/README.md
  js/node/node_modules/i/lib/defaults.js
  js/node/node_modules/i/lib/inflect.js
  js/node/node_modules/i/lib/inflections.js
  js/node/node_modules/i/lib/methods.js
  js/node/node_modules/i/lib/native.js
  js/node/node_modules/i/lib/util.js
  js/node/node_modules/i/package.json
  js/node/package-lock.json
  js/node/package.json
Labels: 1 Bug, 9 Ready to Merge, 3 JS API, cla-signed

#15647 [CINFRA-232] Server Failure Oracle
  arangod/CMakeLists.txt
  arangod/Cluster/FailureOracle.h
  arangod/Cluster/FailureOracleFeature.cpp
  arangod/Cluster/FailureOracleFeature.h
  arangod/Cluster/UpdateReplicatedLogAction.cpp
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/Algorithms.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminClusterHandler.h
  arangod/RestServer/arangod.cpp
  arangod/RestServer/arangod.h
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/CMakeLists.txt
  tests/Replication2/Mocks/FakeFailureOracle.cpp
  tests/Replication2/Mocks/FakeFailureOracle.h
  tests/Replication2/Mocks/FakeReplicatedLog.cpp
  tests/Replication2/Mocks/FakeReplicatedLog.h
  tests/Replication2/ReplicatedLog/EstablishLeadershipTest.cpp
  tests/Replication2/ReplicatedLog/MultiTermTest.cpp
  tests/Replication2/ReplicatedLog/TestHelper.h
  tests/Replication2/ReplicatedLog/UpdateReplicatedLogTests.cpp
  tests/Replication2/ReplicatedState/AbstractStateMachinePollTest.cpp
  tests/Replication2/Streams/TestLogSpecification.h
  tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js
  tests/js/server/resilience/failover/resilience-failure-oracle.js
Labels: 9 Ready to Merge, cinfra, cla-signed

#15725 [ES-1060] Feature/optimize upsert empty update
  CHANGELOG
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/Transaction/Methods.cpp
  tests/js/server/aql/aql-modify-cluster.js
  tests/js/server/aql/aql-modify-noncluster.js
Labels: cla-signed

#15728 Fix assertion failure and crash on HTTP header error, BTS-792
  CHANGELOG
  arangod/GeneralServer/HttpCommTask.cpp
Labels: cla-signed

#14723 BTS-697: Eradicate LngLatRects from Geo code
  CHANGELOG
  arangod/Aql/Functions.cpp
  arangod/CMakeLists.txt
  arangod/GeoIndex/Covering.cpp
  arangod/GeoIndex/Covering.h
  arangod/GeoIndex/Index.cpp
  arangod/GeoIndex/Index.h
  arangod/IResearch/Geo.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/Indexes/IndexFactory.cpp
  arangod/Indexes/IndexFactory.h
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Geo/GeoJson.cpp
  lib/Geo/GeoJson.h
  lib/Geo/GeoParams.h
  lib/Geo/GeoUtils.cpp
  lib/Geo/ShapeContainer.cpp
  lib/Geo/ShapeContainer.h
  lib/Geo/Utils.cpp
  tests/Geo/GeoConstructorTest.cpp
  tests/Geo/GeoFunctionsTest.cpp
  tests/Geo/GeoJsonTest.cpp
  tests/Geo/NearUtilsTest.cpp
  tests/Geo/ShapeContainerTest.cpp
  tests/IResearch/GeoAnalyzerTest.cpp
  tests/IResearch/GeoFilterTest.cpp
  tests/IResearch/IResearchQueryGeoContainsTest.cpp
  tests/IResearch/IResearchQueryGeoIntersectsTest.cpp
  tests/js/common/shell/shell-index-ensure.js
  tests/js/server/aql/aql-geo.js
  tests/js/server/aql/aql-queries-geo.js
  tests/js/server/aql/aql-within-rectangle.js
Labels: Post_Clang_Format_Earthquake, cla-signed

#15773 avoid deadlock in agency
  arangod/Agency/Inception.cpp
  arangod/Agency/Inception.h
Labels: cla-signed

#15705 Upgrade bundled version of velocypack to latest state
  3rdParty/velocypack/CMakeLists.txt
  3rdParty/velocypack/README.md
  3rdParty/velocypack/include/velocypack/Builder.h
  3rdParty/velocypack/include/velocypack/Exception.h
  3rdParty/velocypack/include/velocypack/HexDump.h
  3rdParty/velocypack/include/velocypack/Options.h
  3rdParty/velocypack/include/velocypack/Parser.h
  3rdParty/velocypack/include/velocypack/SliceStaticData.h
  3rdParty/velocypack/include/velocypack/Validator.h
  3rdParty/velocypack/include/velocypack/velocypack-common.h
  3rdParty/velocypack/src/Builder.cpp
  3rdParty/velocypack/src/Exception.cpp
  3rdParty/velocypack/src/HexDump.cpp
  3rdParty/velocypack/src/Parser.cpp
  3rdParty/velocypack/src/Slice.cpp
  3rdParty/velocypack/src/Validator.cpp
  3rdParty/velocypack/tests/CMakeLists.txt
  3rdParty/velocypack/tests/testsException.cpp
  3rdParty/velocypack/tests/testsHexDump.cpp
  3rdParty/velocypack/tests/testsParser.cpp
  3rdParty/velocypack/tests/testsSharedSlice.cpp
  3rdParty/velocypack/tests/testsValidator.cpp
  3rdParty/velocypack/tools/CMakeLists.txt
  3rdParty/velocypack/tools/README.md
  3rdParty/velocypack/tools/fuzzer.cpp
  3rdParty/velocypack/tools/vpack-to-json.cpp
  3rdParty/velocypack/tools/vpack-validate.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  lib/Basics/VelocyPackHelper.cpp
Labels: cla-signed

#15758 Added log message that displays ppid and process name if there is one
  CHANGELOG
  arangod/RestServer/EnvironmentFeature.cpp
Labels: cla-signed

#15737 better long term throttle
  CHANGELOG
  arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
Labels: performance, 3 RocksDB, cla-signed

#15723 improve clang-formatting commit hook for linux
  .githooks/README.md
  .githooks/pre-commit-linux
  CONTRIBUTING.md
  STYLEGUIDE.md
  scripts/clang-format-linux.sh
Labels: cla-signed

#15745 [3.9] debug logging for rocksdb stall events only
  CHANGELOG
  arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.cpp
Labels: 1 Bug, cla-signed

#15722 Set DerivePointerAlignment: false in .clang-format
  .clang-format
Labels: cla-signed

#15757 Fix counts and size sum in hotbackup META files APM-409
  CHANGELOG
  arangod/StorageEngine/HotBackupCommon.h
Labels: cla-signed

#15727 --cluster.max-number-of-move-shards introduced in 3.9.0
  arangod/Cluster/ClusterFeature.cpp
Labels: 3 Documentation, cla-signed

#15795 Give superpowers to arangsync to allow it to also replicate all SmartGraphCollections
  CHANGELOG
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/V8Server/v8-vocindex.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
Labels: 1 Bug

#15802 [3.9] Give superpowers to arangsync for SmartGraphs
  CHANGELOG
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/V8Server/v8-vocindex.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
Labels: 1 Bug

#15661 Harden velocypack validator after fuzz testing
  3rdParty/velocypack/include/velocypack/Builder.h
  3rdParty/velocypack/include/velocypack/Exception.h
  3rdParty/velocypack/include/velocypack/Options.h
  3rdParty/velocypack/include/velocypack/Parser.h
  3rdParty/velocypack/include/velocypack/Slice.h
  3rdParty/velocypack/include/velocypack/Validator.h
  3rdParty/velocypack/src/Builder.cpp
  3rdParty/velocypack/src/Exception.cpp
  3rdParty/velocypack/src/Parser.cpp
  3rdParty/velocypack/src/Validator.cpp
  3rdParty/velocypack/tests/testsValidator.cpp
  CHANGELOG
  arangod/Replication/DatabaseInitialSyncer.cpp
Labels: 9 Ready to Merge, velocypack, cla-signed

#15645 reduce peak memory usage of some AQL queries
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AstResources.cpp
  arangod/Aql/AstResources.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  arangod/Aql/ShortStringStorage.cpp
  arangod/Aql/ShortStringStorage.h
  lib/Basics/FixedSizeAllocator.h
  tests/Aql/AstResourcesTest.cpp
  tests/Basics/FixedSizeAllocatorTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-queries-nested-joins.js
Labels: 3 AQL, 9 Ready to Merge, cla-signed

#15806 Reduced some maintenance log-levels
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/MaintenanceFeature.cpp
Labels: 9 Ready to Merge

#15755 Added docs to fix CORS errors when running development server
  CONTRIBUTING.md
Labels: cla-signed

#15804 [CINFRA-262] The FailureOracle should not regard BAD servers as FAILED
  arangod/Cluster/FailureOracleFeature.cpp
Labels: 9 Ready to Merge, cinfra

#15805 [CINFRA-263] Don't regard failed servers as non-eligible
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  lib/Basics/VelocyPackHelper.h
  tests/Replication2/ReplicatedLog/CalcCommitIndexTest.cpp
Labels: cinfra

#15810 [CINFRA-266] Treat BAD servers as OK
  arangod/Agency/Supervision.cpp
  arangod/Replication2/ReplicatedLog/ParticipantsHealth.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/Supervision.h
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
Labels: 9 Ready to Merge, cinfra

#15807 [CINFRA-264] testing.js regards servers as failed too eagerly, or ignores them completely
  client-tools/Shell/ClientFeature.h
  client-tools/Shell/V8ClientConnection.cpp
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  js/client/modules/@arangodb/testsuites/server_permissions.js
  js/client/modules/@arangodb/testutils/process-utils.js
Labels: cinfra
