Repository arangodb/arangodb, pull requests merged in 2022-05, with the labels that each got.

#16207 [CINFRA] Latest Staging
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/ParticipantsHealth.h
  arangod/Replication2/ReplicatedState/AgencySpecification.h
  arangod/Replication2/ReplicatedState/StateCommon.cpp
  arangod/Replication2/ReplicatedState/StateCommon.h
  arangod/Replication2/ReplicatedState/Supervision.cpp
  tests/CMakeLists.txt
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/Helper/ModelChecker/Actors.cpp
  tests/Replication2/Helper/ModelChecker/Actors.h
  tests/Replication2/Helper/ModelChecker/AgencyState.h
  tests/Replication2/Helper/ModelChecker/AgencyTransition.cpp
  tests/Replication2/Helper/ModelChecker/AgencyTransitions.h
  tests/Replication2/Helper/ModelChecker/HashValues.h
  tests/Replication2/Helper/ModelChecker/Predicates.h
  tests/Replication2/Mocks/MaintenanceMock.cpp
  tests/Replication2/Mocks/MaintenanceMock.h
  tests/Replication2/ModelChecker/ActorModel.h
  tests/Replication2/ModelChecker/ModelChecker.cpp
  tests/Replication2/ModelChecker/ModelChecker.h
  tests/Replication2/ModelChecker/Predicates.h
  tests/Replication2/ModelChecker/Tests/ModelCheckerTest.cpp
  tests/Replication2/ReplicatedState/SupervisionSimulationTest2.cpp
Labels: cinfra

#16209 Feature/cinfra 367 model checker dfs loop detection
  tests/CMakeLists.txt
  tests/Replication2/ModelChecker/ActorModel.h
  tests/Replication2/ModelChecker/ModelChecker.h
  tests/Replication2/ModelChecker/Predicates.h
  tests/Replication2/ModelChecker/Tests/ModelCheckerTest.cpp
  tests/Replication2/ReplicatedState/SupervisionModelChecker.cpp
Labels: cinfra

#16208 [CINFRA-211] Coordinator returns empty response
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/RestHandler/RestLogHandler.cpp
  tests/js/server/replication2/replication2-replicated-log-http-api-cluster.js
Labels: 9 Ready to Merge, cinfra

#16153 Added option `--enable-revision-trees` to arangorestore
  CHANGELOG
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Restore/RestoreFeature.h
  tests/js/client/shell/shell-restore-integration.js
Labels: 3 ImportExport

#16154 Added option `--enable-revision-trees` to arangorestore
  CHANGELOG
  arangosh/Restore/RestoreFeature.cpp
  arangosh/Restore/RestoreFeature.h
  tests/js/client/shell/shell-restore-integration.js
Labels: 3 ImportExport

#16123 [CINFRA-360] Synchronize append entries and check compaction
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.h
  arangod/Replication2/ReplicatedLog/SupervisionAction.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.h
  arangod/Replication2/ReplicatedLog/types.cpp
  arangod/Replication2/ReplicatedLog/types.h
  arangod/Replication2/ReplicatedState/AgencySpecification.cpp
  lib/Basics/Guarded.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/CMakeLists.txt
  tests/Replication2/ReplicatedLog/FollowerAppendEntries.cpp
  tests/Replication2/ReplicatedLog/LogFollowerCompactionTest.cpp
  tests/Replication2/ReplicatedLog/TestHelper.h
  tests/Replication2/ReplicatedState/PrototypeStateMachineTest.cpp
  tests/Replication2/Serialization/LogStatusTest.cpp
Labels: cinfra

#16213 Remove ancient Windows README
  README.windows
  cmake/ArangoDBInstall.cmake
  cmake/packages/client/nsis.txt
Labels: 1 Bug, 4 Windows

#16212 Remove ancient Windows README
  README.windows
  cmake/ArangoDBInstall.cmake
  cmake/packages/client/nsis.txt
Labels: 1 Bug, 4 Windows

#16211 Remove ancient Windows README
  README.windows
  cmake/ArangoDBInstall.cmake
  cmake/packages/client/nsis.txt
Labels: 1 Bug, 4 Windows

#16210 Remove ancient Windows README
  README.windows
  cmake/ArangoDBInstall.cmake
  cmake/packages/client/nsis.txt
Labels: 1 Bug, 4 Windows

#16217 [CINFRA-325] Prototype State API update
  arangod/Replication2/StateMachines/Prototype/PrototypeFollowerState.h
  arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.h
  arangod/RestHandler/RestPrototypeStateHandler.cpp
  arangod/RestHandler/RestPrototypeStateHandler.h
  arangod/V8Server/v8-prototype-states.cpp
  js/client/modules/@arangodb/arango-prototype-state.js
  js/server/modules/@arangodb/testutils/replicated-state-predicates.js
  lib/Rest/GeneralRequest.cpp
  tests/js/common/shell/shell-prototype-state-cluster.js
Labels: cinfra

#16218 [CINFRA-329] Run supervision and maintenance tests using prototype
  tests/js/server/replication2/replication2-maintenance-replicated-state-cluster.js
  tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
Labels: cinfra

#16223 [CINFRA-322] wait for resign race
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/LogUnconfiguredParticipant.cpp
  arangod/Replication2/ReplicatedLog/LogUnconfiguredParticipant.h
  arangod/Replication2/ReplicatedLog/WaitForBag.cpp
  arangod/Replication2/ReplicatedLog/WaitForBag.h
  tests/CMakeLists.txt
  tests/Replication2/ReplicatedLog/ParticipantResignTest.cpp
Labels: 1 Bug, cinfra

#16231 allow compilation with libssl3 when using USE_STRICT_OPENSSL_VERSION=Off
  CMakeLists.txt
Labels: OpenSSL

#16234 remove obsolete STORAGE_ENGINE variable
  scripts/startLocalCluster.sh
Labels: 3 - Testing

#16242 [CINFRA-375] Prototype Compare Exchange
  arangod/Replication2/StateMachines/Prototype/PrototypeCore.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeCore.h
  arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.h
  arangod/Replication2/StateMachines/Prototype/PrototypeLogEntry.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeLogEntry.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.h
  arangod/Replication2/Streams/LogMultiplexer.tpp
  arangod/Replication2/Streams/Streams.h
  arangod/Replication2/Streams/Streams.tpp
  arangod/RestHandler/RestPrototypeStateHandler.cpp
  arangod/RestHandler/RestPrototypeStateHandler.h
  tests/Replication2/ReplicatedState/PrototypeStateMachineTest.cpp
  tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
Labels: cinfra

#16238 Update OpenSSL to 1.1.1o and OpenLDAP to 2.6.2
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#16237 Update OpenSSL to 1.1.1o and OpenLDAP to 2.6.2
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#16235 Update OpenSSL to 1.1.1o and OpenLDAP to 2.6.2
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#16236 Update OpenSSL to 1.1.1o and OpenLDAP to 2.6.2
  CHANGELOG
  VERSIONS
Labels: OpenSSL

#16239 Allow starting with edge cache size of 0
  CHANGELOG
  arangod/Cache/CacheManagerFeature.cpp
Labels: 9 Ready to Merge

#16243 [BTS-862] unstable js test grants spec
  arangod/Auth/UserManager.cpp
  tests/js/client/shell/api/grants-spec.js
Labels: cinfra

#16257 High prio hotbackup BTS-865
  CHANGELOG
Labels: 3 ImportExport

#16251 High prio hotbackup BTS-865
  CHANGELOG
Labels: 3 ImportExport

#16258 High prio hotbackup BTS-865
  CHANGELOG
Labels: 3 ImportExport

#16042 clang-format: Pass through arguments from PowerShell wrapper to .sh script
  scripts/clang-format.ps1
Labels: 1 Feature, 9 Ready to Merge

#16256 [3.9] bts 860 ignore link create on recovery
  CHANGELOG
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  tests/js/server/recovery/view-arangosearch-link-populate-drop-view-no-flushthread.js
Labels: 3 Index, 3 ArangoSearch

#16263 [3.8] BTS-860 ignore link create on recovery
  CHANGELOG
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  tests/js/server/recovery/view-arangosearch-link-populate-drop-view-no-flushthread.js
Labels: 3 Index, 3 ArangoSearch

#16265 try to fix test
  tests/js/server/recovery/view-arangosearch-link-recover-view-not-again-noncluster.js
Labels: 3 - Testing, 3 ArangoSearch

#16275 [CINFRA-374] Delete Replicated log
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  js/server/modules/@arangodb/testutils/replicated-logs-http-helper.js
  js/server/modules/@arangodb/testutils/replicated-logs-predicates.js
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-replicated-log-http-api-cluster.js
Labels: cinfra

#16264 allow building 3.9 with non-matching libssl version
  CMakeLists.txt
Labels: 3 Build, OpenSSL

#16285 fixed issue #16279
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-cluster.js
  tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-noncluster.js
Labels: 1 Bug, 3 Optimizer

#16284 fixed issue #16279
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-cluster.js
  tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-noncluster.js
Labels: 1 Bug, 3 Optimizer

#16273 Fix shutdown hang
  CHANGELOG
  arangod/VocBase/vocbase.cpp
Labels: 9 Ready to Merge

#16282 fixed issue #16279
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-cluster.js
  tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-noncluster.js
Labels: 1 Bug, 3 Optimizer

#16267 [3.9] fix verbose analysis failures
  CHANGELOG
  arangod/IResearch/Geo.cpp
Labels: performance, 3 Geo

#16280 Fix ambiguity between date::format and std::format with MSVC 16.11.14
  lib/Basics/datetime.cpp
Labels: 3 Build, 4 Windows

#16278 add documentation for Pregel jobs API
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_overview.md
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_status.md
Labels: 3 Documentation, 3 Pregel

#16269 [3.8] fix verbose geojson parsing
  CHANGELOG
  arangod/IResearch/Geo.cpp
Labels: performance

#16116 Improve shard resync
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RestHandler/RestWalAccessHandler.h
Labels: 1 Bug

#16283 fixed issue #16279
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-cluster.js
  tests/js/server/aql/aql-optimizer-rule-interchange-adjacent-enumerations-noncluster.js
Labels: 1 Bug, 3 Optimizer

#16099 reduce sizes of sync replication responses from followers
  CHANGELOG
  arangod/Transaction/Methods.cpp
  tests/js/client/shell/shell-replication-responses-cluster.js
Labels: 3 Cluster

#16281 [CIS-368] Fix AppleClang Issues
  tests/Replication2/ModelChecker/Predicates.h
Labels: cinfra

#16293 decrease wait time in agency inception in case of HTTP 503
  arangod/Agency/Inception.cpp
Labels: 9 Ready to Merge

#16296 Improve CHANGELOG for IO heartbeat
  CHANGELOG
Labels: 3 Documentation

#16294 Improve CHANGELOG for IO heartbeat
  CHANGELOG
Labels: 3 Documentation

#16295 Improve CHANGELOG for IO heartbeat
  CHANGELOG
Labels: 3 Documentation

#16144 time-limited shard synchronization
  CHANGELOG
  Documentation/Metrics/arangodb_sync_timeouts_total.yaml
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/ReplicationTimeoutFeature.cpp
  arangod/Cluster/ReplicationTimeoutFeature.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/SynchronizeShard.h
  arangod/ClusterEngine/ClusterRestReplicationHandler.cpp
  arangod/ClusterEngine/ClusterRestReplicationHandler.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/DatabaseTailingSyncer.cpp
  arangod/Replication/DatabaseTailingSyncer.h
  arangod/Replication/TailingSyncer.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.h
  arangod/Transaction/Methods.cpp
  js/common/bootstrap/errors.js
  lib/Basics/error-registry.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.h
  tests/Maintenance/MaintenanceFeatureTest.cpp
Labels: 3 Cluster, 9 Ready to Merge

#16289 [3.8] fix default collection property cache enabled
  CHANGELOG
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
Labels: 3 Documentation

#16288 [3.9] fix default collection property cache enabled
  CHANGELOG
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
Labels: 3 Documentation

#16204 [CINFRA-xxx] Refactor Log Supervision
  arangod/Agency/Supervision.cpp
  arangod/CMakeLists.txt
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.cpp
  arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.h
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/Supervision.h
  arangod/Replication2/ReplicatedLog/SupervisionAction.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.h
  arangod/Replication2/ReplicatedLog/SupervisionContext.h
  arangod/Replication2/ReplicatedState/Supervision.cpp
  tests/CMakeLists.txt
  tests/Replication2/Helper/ModelChecker/Actors.cpp
  tests/Replication2/Helper/ModelChecker/Actors.h
  tests/Replication2/Helper/ModelChecker/AgencyState.h
  tests/Replication2/Helper/ModelChecker/AgencyTransition.cpp
  tests/Replication2/Helper/ModelChecker/AgencyTransitions.h
  tests/Replication2/Helper/ModelChecker/Predicates.h
  tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
  tests/Replication2/Serialization/LogStatusTest.cpp
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra

#16215 Cleanup old traversal code
  arangod/Aql/GraphNode.cpp
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalExecutor.h
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraversalNode.h
  arangod/CMakeLists.txt
  arangod/Cluster/ClusterEdgeCursor.cpp
  arangod/Cluster/ClusterTraverser.cpp
  arangod/Cluster/ClusterTraverser.h
  arangod/Graph/BreadthFirstEnumerator.cpp
  arangod/Graph/BreadthFirstEnumerator.h
  arangod/Graph/NeighborsEnumerator.cpp
  arangod/Graph/NeighborsEnumerator.h
  arangod/Graph/PathEnumerator.cpp
  arangod/Graph/PathEnumerator.h
  arangod/Graph/SingleServerEdgeCursor.h
  arangod/Graph/SingleServerTraverser.cpp
  arangod/Graph/SingleServerTraverser.h
  arangod/Graph/Traverser.cpp
  arangod/Graph/Traverser.h
  arangod/Graph/TraverserOptions.cpp
  arangod/Graph/TraverserOptions.h
  arangod/Graph/WeightedEnumerator.cpp
  arangod/Graph/WeightedEnumerator.h
  arangod/RestHandler/RestSimpleHandler.cpp
  tests/Aql/TraversalExecutorTest.cpp
  tests/CMakeLists.txt
Labels: 9 Review Required

#16304 [CINFRA] Adding old tests
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra

#16306 [CINFRA] Try to fix maybe uninitialized error.
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.h
Labels: cinfra

#16305 [CINFRA-xxx] Test failed dictated leader
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  js/server/modules/@arangodb/testutils/replicated-logs-predicates.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra

#16307 Add debug information.
  arangod/RocksDBEngine/Methods/RocksDBTrxMethods.cpp
  tests/js/client/shell/shell-transaction-intermediate-commit-cluster.js
Labels: cinfra

#16302 Fix behavior when accessing document APIs with view names
  CHANGELOG
  arangod/Utils/SingleCollectionTransaction.cpp
  tests/js/client/shell/api/view-instead-of-collection.js
Labels: 3 API, 9 Ready to Merge, 3 ArangoSearch

#16299 Fix behavior when accessing document APIs with view names
  CHANGELOG
  arangod/Utils/SingleCollectionTransaction.cpp
  js/client/modules/@arangodb/testutils/test-utils.js
  js/common/modules/jsunity.js
  js/common/modules/jsunity/jsunity.js
  tests/js/client/shell/api/view-instead-of-collection.js
Labels: 3 API, 9 Ready to Merge, 3 ArangoSearch

#16104 Improve shard resync
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RestHandler/RestWalAccessHandler.h
Labels: 1 Bug

#16312 [CINFRA-342] Enable MC tests for replicated state
  tests/Replication2/Helper/ModelChecker/AgencyState.h
  tests/Replication2/ModelChecker/Predicates.h
  tests/Replication2/ReplicatedState/SupervisionModelChecker.cpp
Labels: cinfra

#16313 [CINFRA-355] Only consider participants in Plan
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
Labels: cinfra

#16308 Production Assert
  arangod/Replication2/ReplicatedState/Supervision.cpp
  lib/Basics/debugging.cpp
  lib/Basics/debugging.h
Labels: cinfra

#16316 [CINFRA] Log Supervision Spam Reduction
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.cpp
  js/client/modules/@arangodb/testsuites/replication2.js
Labels: cinfra

#16317 [CINFRA-385] Incorrect ongoing state in prototype
  arangod/Replication2/StateMachines/Prototype/PrototypeCore.h
Labels: cinfra

#16321 [CINFRA-301] remove to/fromVelocyPack
  arangod/Agency/Supervision.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/UpdateReplicatedLogAction.cpp
  arangod/Cluster/UpdateReplicatedStateAction.cpp
  arangod/Replication2/AgencyMethods.cpp
  arangod/Replication2/Methods.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedState/AgencySpecification.cpp
  arangod/Replication2/ReplicatedState/AgencySpecification.h
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/RestHandler/RestReplicatedStateHandler.cpp
  tests/Replication2/Helper/ModelChecker/AgencyState.h
  tests/Replication2/ReplicatedState/MaintenanceTest.cpp
  tests/Replication2/Serialization/AgencyLogSpecificationTest.cpp
  tests/Replication2/Serialization/LogCommonTest.cpp
Labels: cinfra

#16323 [CINFRA-386] Check Resigned before release
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  tests/Replication2/ReplicatedLog/MultiTermTest.cpp
Labels: cinfra

#16324 [CINFRA-301] Remove more of from/toVelocyPack 2
  arangod/Replication2/AgencyMethods.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/ReplicatedLog/LogEntries.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.h
  arangod/Replication2/ReplicatedLog/types.cpp
  arangod/Replication2/ReplicatedLog/types.h
  arangod/Replication2/ReplicatedState/AgencySpecification.h
  arangod/Replication2/ReplicatedState/StateCommon.cpp
  arangod/Replication2/ReplicatedState/StateCommon.h
  arangod/Replication2/ReplicatedState/StateStatus.cpp
  arangod/Replication2/ReplicatedState/StateStatus.h
  lib/Basics/ErrorCode.h
  lib/Inspection/Transformers.h
  tests/Replication2/Serialization/LogCommonTest.cpp
  tests/Replication2/Serialization/LogStatusTest.cpp
Labels: cinfra

#16326 don't install RocksDB headers
  3rdParty/CMakeLists.txt
Labels: 3 Build, 3 RocksDB

#16329 [CINFRA-80] Fix log not found error
  arangod/Cluster/ClusterInfo.cpp
  arangod/Replication2/Methods.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  arangod/VocBase/vocbase.cpp
  js/common/bootstrap/errors.js
  lib/Basics/Exceptions.h
  lib/Basics/Exceptions.tpp
  lib/Basics/Identifier.h
  lib/Basics/Result.h
  lib/Basics/Result.tpp
  lib/Basics/ResultError.cpp
  lib/Basics/ResultError.h
  lib/Basics/ResultError.tpp
  lib/Basics/errors.dat
  lib/CMakeLists.txt
  lib/Rest/GeneralResponse.cpp
Labels: 1 Feature, cinfra

#16334 [CINFRA-388] InMemoryLog assertions
  arangod/Replication2/ReplicatedLog/InMemoryLog.cpp
Labels: cinfra

#16322 [CINFRA-380] Remove replicationFactor from LogConfig
  arangod/Replication2/Methods.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  js/server/modules/@arangodb/testutils/replicated-state-helper.js
  tests/Replication2/Mocks/FakeReplicatedLog.cpp
  tests/Replication2/ReplicatedLog/EstablishLeadershipTest.cpp
  tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
  tests/Replication2/ReplicatedLog/TestHelper.h
  tests/Replication2/ReplicatedState/PrototypeConcurrencyTest.cpp
  tests/Replication2/ReplicatedState/SupervisionModelChecker.cpp
  tests/Replication2/ReplicatedState/SupervisionTest.cpp
  tests/Replication2/Serialization/AgencyLogSpecificationTest.cpp
  tests/Replication2/Serialization/LogCommonTest.cpp
  tests/Replication2/Streams/TestLogSpecification.h
  tests/js/common/shell/shell-prototype-state-cluster.js
  tests/js/common/shell/shell-replicated-logs-cluster.js
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-maintenance-replicated-state-cluster.js
  tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
  tests/js/server/replication2/replication2-regression.js
  tests/js/server/replication2/replication2-replicated-log-create-api-cluster.js
  tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
  tests/js/server/replication2/replication2-replicated-log-http-api-cluster.js
  tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
  tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-drop-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-state-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
Labels: cinfra

#16336 [CINFRA-380] Introduce effectiveWriteConcern
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/Algorithms.h
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.h
  arangod/Replication2/ReplicatedState/AgencySpecification.cpp
  arangod/Replication2/ReplicatedState/AgencySpecification.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.h
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/Helper/AgencyStateBuilder.h
  tests/Replication2/Mocks/FakeReplicatedLog.cpp
  tests/Replication2/ReplicatedLog/CalcCommitIndexTest.cpp
  tests/Replication2/ReplicatedLog/CheckLogsTest.cpp
  tests/Replication2/ReplicatedLog/EstablishLeadershipTest.cpp
  tests/Replication2/ReplicatedLog/MaintenanceTests.cpp
  tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
  tests/Replication2/ReplicatedLog/TestHelper.h
  tests/Replication2/ReplicatedState/PrototypeConcurrencyTest.cpp
  tests/Replication2/ReplicatedState/SupervisionModelChecker.cpp
  tests/Replication2/ReplicatedState/SupervisionTest.cpp
  tests/Replication2/Serialization/AgencyLogSpecificationTest.cpp
  tests/Replication2/Serialization/LogCommonTest.cpp
  tests/Replication2/Streams/TestLogSpecification.h
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-maintenance-replicated-state-cluster.js
  tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js
Labels: cinfra

#16345 [CINFRA-407] Prevent write to current if State/Plan is deleted
  arangod/Cluster/Maintenance.cpp
Labels: cinfra

#16341 Fix ARANGODB_RPM_UPSTREAM generation for devel and nightly (3.8)
  CMakeLists.txt
Labels: 3 Build, 4 Linux, 3 Packaging

#16339 Fix ARANGODB_RPM_UPSTREAM generation for devel and nightly
  CMakeLists.txt
Labels: 3 Build, 4 Linux, 3 Packaging

#16330 [CINFRA-363] Create replicated state for each shard
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/Replication2/AgencyMethods.cpp
  arangod/Replication2/AgencyMethods.h
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra

#16340 Fix ARANGODB_RPM_UPSTREAM generation for devel and nightly (3.9)
  CMakeLists.txt
Labels: 3 Build, 4 Linux, 3 Packaging

#16353 [CINFRA-408] Document State Implementation
  arangod/CMakeLists.txt
  arangod/Cluster/ClusterInfo.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.h
  arangod/RestServer/arangod.cpp
  arangod/RestServer/arangod.h
Labels: cinfra

#16343 [CINFRA-381] Move Log config from Term to ParticipantsConfig
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.h
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/ReplicatedLog/LogEntries.cpp
  arangod/Replication2/ReplicatedLog/LogEntries.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/LogStatus.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.h
  arangod/Replication2/ReplicatedState/Supervision.cpp
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/Helper/ModelChecker/HashValues.h
  tests/Replication2/Mocks/FakeReplicatedLog.cpp
  tests/Replication2/ReplicatedLog/CheckLogsTest.cpp
  tests/Replication2/ReplicatedLog/EstablishLeadershipTest.cpp
  tests/Replication2/ReplicatedLog/MaintenanceTests.cpp
  tests/Replication2/ReplicatedLog/RocksDBLogTest.cpp
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
  tests/Replication2/ReplicatedLog/TestHelper.h
  tests/Replication2/ReplicatedLog/UpdateParticipantsFlags.cpp
  tests/Replication2/ReplicatedState/MaintenanceTest.cpp
  tests/Replication2/ReplicatedState/PrototypeConcurrencyTest.cpp
  tests/Replication2/Serialization/AgencyLogSpecificationTest.cpp
  tests/Replication2/Serialization/LogCommonTest.cpp
  tests/Replication2/Serialization/LogStatusTest.cpp
  tests/Replication2/Streams/TestLogSpecification.h
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-maintenance-replicated-state-cluster.js
Labels: cinfra

#16354 [CINFRA-411] Mac Test Issues
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/SupervisionContext.h
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-state-cluster.js
Labels: cinfra
