Repository arangodb/arangodb, pull requests merged in 2022-07, with the labels that each got.

#16479 [CINFRA] Fix Document State Feature Dependencies
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
Labels: 9 Ready to Merge, cinfra

#16444 [CINFRA-454] refactor replicated state leader manager state machine
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/LeaderStateManager.h
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  arangod/Replication2/ReplicatedState/StateStatus.cpp
  arangod/Replication2/ReplicatedState/StateStatus.h
Labels: cinfra

#16470 Feature/add netstat by instance
  LICENSES-OTHER-COMPONENTS.md
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/result-processing.js
  js/client/modules/@arangodb/testutils/testrunner.js
  js/common/bootstrap/modules/process.js
  js/node/node_modules/.package-lock.json
  js/node/node_modules/is-wsl/index.js
  js/node/node_modules/is-wsl/license
  js/node/node_modules/is-wsl/package.json
  js/node/node_modules/is-wsl/readme.md
  js/node/node_modules/node-netstat/Gruntfile.js
  js/node/node_modules/node-netstat/README.md
  js/node/node_modules/node-netstat/UNLICENSE
  js/node/node_modules/node-netstat/index.js
  js/node/node_modules/node-netstat/lib/activators.js
  js/node/node_modules/node-netstat/lib/filters.js
  js/node/node_modules/node-netstat/lib/netstat.js
  js/node/node_modules/node-netstat/lib/parser-factories.js
  js/node/node_modules/node-netstat/lib/parsers.js
  js/node/node_modules/node-netstat/lib/utils.js
  js/node/node_modules/node-netstat/package.json
  js/node/node_modules/node-netstat/test/activators.js
  js/node/node_modules/node-netstat/test/data.json
  js/node/node_modules/node-netstat/test/data2.json
  js/node/node_modules/node-netstat/test/netstat.js
  js/node/node_modules/node-netstat/test/parsers.js
  js/node/node_modules/node-netstat/test/utils.js
  js/node/package-lock.json
  js/node/package.json
Labels: 3 - Testing

#16469 Change default macOS CI compiler to LLVM clang-12
  3rdParty/iresearch/core/utils/type_info.hpp
  CHANGELOG
  VERSIONS
Labels: 3 Build, 4 MacOSX

#16467 Feature/enable llvm clang macos
  CHANGELOG
  VERSIONS
Labels: 3 Build, 4 MacOSX

#16485 [CINFRA-472] Convergence Fix
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/Replication2/ReplicatedState/SupervisionAction.h
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/Helper/ModelChecker/HashValues.h
  tests/Replication2/ReplicatedState/SupervisionTest.cpp
Labels: cinfra

#16474 Change default Linux CI compiler to gcc-11
  CHANGELOG
  CMakeLists.txt
  VERSIONS
  tests/js/server/aql/aql-functions-date.js
Labels: 3 Build, 4 Linux

#16489 [CINFRA-466] softwriteconcern multiple changes dead lock
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  tests/Replication2/Helper/ModelChecker/Actors.cpp
  tests/Replication2/Helper/ModelChecker/Actors.h
  tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
Labels: cinfra

#16483 [CINFRA-471] Leader State Manager Resign Tests
  arangod/Replication2/ReplicatedState/LeaderStateManager.h
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  lib/Basics/Exceptions.cpp
  lib/Basics/Exceptions.h
  tests/CMakeLists.txt
  tests/Replication2/Mocks/FakeLeader.cpp
  tests/Replication2/Mocks/FakeLeader.h
  tests/Replication2/Mocks/FakeReplicatedState.h
  tests/Replication2/ReplicatedState/LeaderResignTest.cpp
Labels: cinfra

#16255 fixed wrong test definition in transformed ruby -> js test
  tests/js/client/shell/api/general-graph.js
Labels: 9 Review Required

#16156 Bug fix/es 1084
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
Labels: 1 Bug, 3 UI, 9 Ready to Merge

#16447 [AQL] Rename KShortestPathsNode to EnumeratePathsNode
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/CollectNode.cpp
  arangod/Aql/ConditionFinder.cpp
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/EnumeratePathsExecutor.cpp
  arangod/Aql/EnumeratePathsExecutor.h
  arangod/Aql/EnumeratePathsNode.cpp
  arangod/Aql/EnumeratePathsNode.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/GraphNode.cpp
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QuerySnippet.cpp
  arangod/Aql/ShardLocking.cpp
  arangod/Aql/TraversalConditionFinder.cpp
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.y
  arangod/CMakeLists.txt
  arangod/Graph/BaseOptions.h
  arangod/Graph/PathType.cpp
  arangod/Graph/PathType.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/Aql/EnumeratePathsExecutorTest.cpp
  tests/Aql/EnumeratePathsNodeTest.cpp
  tests/CMakeLists.txt
Labels: 3 AQL

#16268 fix verbose analysis failures
  CHANGELOG
  arangod/IResearch/Geo.cpp
Labels: performance

#16517 [AQL] Disallow range in K_SHORTEST_PATHS
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-graph-k-shortest-path-range-syntax-regression.js
Labels: 3 AQL

#16524 [CINFRA-442] Configuration change: waitForSync
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.h
  tests/Replication2/Helper/ModelChecker/Actors.cpp
  tests/Replication2/Helper/ModelChecker/Actors.h
  tests/Replication2/Helper/ModelChecker/AgencyTransition.cpp
  tests/Replication2/Helper/ModelChecker/AgencyTransitions.h
  tests/Replication2/Helper/ModelChecker/Predicates.h
  tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
Labels: cinfra

#16529 [CINFRA-479] Convergence waits for Leadership
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/Helper/AgencyStateBuilder.h
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
Labels: cinfra

#16494 [PREGEL] Report worker status to conductor every 1000 loaded vertices
  arangod/Pregel/Common.h
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/GraphStore.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Status/ConductorStatus.h
  arangod/Pregel/Status/WorkerStatus.h
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker.cpp
Labels: 3 Pregel

#16473 [CINFRA-455] Refactor replicated state follower manager state machine
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCallback.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Network/Utils.cpp
  arangod/Replication2/ReplicatedState/FollowerStateManager.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/StateStatus.cpp
  arangod/Replication2/ReplicatedState/StateStatus.h
  arangod/VocBase/vocbase.cpp
  tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
  tests/Replication2/ReplicatedState/ReplicatedStateTest.cpp
  tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
Labels: 9 Ready to Merge, cinfra

#16462 Switch to Visual Studio 2022
  3rdParty/V8/CMakeLists.txt
  3rdParty/V8/gyp/MSVS/MSVSVersion.py
  3rdParty/taocpp-json/include/tao/json/external/pegtl/internal/demangle.hpp
  CHANGELOG
  CMakeLists.txt
  VERSIONS
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  cmake/custom/ArangoDB_FindOpenSSL_WIN32.cmake
  lib/Basics/debugging.cpp
  lib/Basics/process-utils.cpp
Labels: 3 Build, 4 Windows

#16425 [PREGEL] Tests for Pregel SCC
  js/common/modules/@arangodb/graph/graphs-generation.js
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/common/shell/shell-pregel-components-nightly.js
  tests/js/common/shell/shell-pregel-components.js
Labels: 3 Pregel

#16534 [CINFRA] BugFix Replicated Log Maintenance Race
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  tests/Replication2/ReplicatedLog/LogParticipantWaitForResignTests.cpp
  tests/Replication2/ReplicatedLog/ReplicatedLogTest.cpp
Labels: cinfra

#16538 we have to mimic the instanceInfo structure better in order to work with the crash-utils
  js/client/modules/@arangodb/testutils/process-utils.js
Labels: 3 - Testing

#16482 [PREGEL] Tests and BugFix for Label Propagation
  CHANGELOG
  arangod/Pregel/Algos/LabelPropagation.cpp
  js/common/modules/@arangodb/graph/graphs-generation.js
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/common/shell/shell-pregel-components.js
Labels: 3 Pregel

#16515 [PREGEL] APM-538 Add reporting for loading state observables
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/GraphStore.h
  arangod/Pregel/Status/ConductorStatus.h
  arangod/Pregel/Status/Status.h
  arangod/Pregel/Worker.cpp
  tests/CMakeLists.txt
  tests/Pregel/StatusTest.cpp
Labels: 3 Pregel

#16490 [CINFRA-424] Replicated State Metrics
  arangod/CMakeLists.txt
  arangod/Replication2/MetricsHelper.cpp
  arangod/Replication2/MetricsHelper.h
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLogMetrics.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLogMetrics.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
Labels: cinfra

#16471 Feature/parallelize moar traversals
  arangod/Aql/AsyncExecutor.cpp
  arangod/Aql/BlocksWithClients.cpp
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/DistributeConsumerNode.cpp
  arangod/Aql/DistributeConsumerNode.h
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionEngine.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/MutexNode.cpp
  arangod/Aql/QuerySnippet.cpp
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/WalkerWorker.h
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
  js/server/modules/@arangodb/testutils/collection-modification-aql-generic-tests.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Aql/NodeWalkerTest.cpp
  tests/CMakeLists.txt
Labels: 1 Feature, 3 AQL, 3 Graph, 3 Cluster

#16493 [PREGEL] [APM-539] Add Metrics Feature to Pregel
  Documentation/Metrics/arangodb_pregel_conductors_loading_number.yaml
  Documentation/Metrics/arangodb_pregel_conductors_number.yaml
  Documentation/Metrics/arangodb_pregel_conductors_running_number.yaml
  Documentation/Metrics/arangodb_pregel_conductors_storing_number.yaml
  Documentation/Metrics/arangodb_pregel_graph_memory_bytes_number.yaml
  Documentation/Metrics/arangodb_pregel_messages_received_total.yaml
  Documentation/Metrics/arangodb_pregel_messages_sent_total.yaml
  Documentation/Metrics/arangodb_pregel_threads_number.yaml
  Documentation/Metrics/arangodb_pregel_workers_loading_number.yaml
  Documentation/Metrics/arangodb_pregel_workers_number.yaml
  Documentation/Metrics/arangodb_pregel_workers_running_number.yaml
  Documentation/Metrics/arangodb_pregel_workers_storing_number.yaml
  arangod/CMakeLists.txt
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/GraphStore.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/PregelMetrics.cpp
  arangod/Pregel/PregelMetrics.h
  arangod/Pregel/PregelMetricsDeclarations.h
  arangod/Pregel/Worker.cpp
Labels: 3 Pregel

#16539 [PREGEL] APM-538 Add loading state
  CHANGELOG
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Conductor.h
  arangod/Pregel/PregelFeature.cpp
  tests/js/client/load-balancing/load-balancing-pregel-auth-cluster.js
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
  tests/js/common/shell/shell-pregel-basics-example.js
  tests/js/common/shell/shell-pregel-components.js
  tests/js/common/shell/shell-pregel-multicollection-edgecol.js
  tests/js/common/shell/shell-pregel-random.js
  tests/js/common/shell/shell-pregel-start-cluster.js
Labels: 3 Pregel

#16521 [PREGEL] APM-538 Add reporting for storing state observables
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/GraphStore.h
  arangod/Pregel/Status/Status.h
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker.cpp
  tests/Pregel/StatusTest.cpp
Labels: 3 Pregel

#16536 [CINFRA-475] use same leader state during transaction
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.h
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionCollection.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
Labels: cinfra

#16535 [PREGEL] APM-538 add reporting for running state observables
  arangod/Pregel/GraphStore.h
  arangod/Pregel/Status/Status.h
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker.cpp
  arangod/Pregel/Worker.h
  tests/Pregel/StatusTest.cpp
Labels: 3 Pregel

#16561 Remove stray LOG_DEVEL
  arangod/Pregel/Worker.cpp
Labels: 3 Pregel

#16559 work around BTS-903: turn of logging for the queries facility.
  js/client/modules/@arangodb/testsuites/aql.js
Labels: 3 - Testing

#16394 APM-318 | Implemented Web UI support for EnterpriseGraphs
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoDocuments.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/select2.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/select2.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/edgeDefinitionTable.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/graphManagementView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalGraphTable.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/modalTable.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/modalView.js
  js/apps/system/_admin/aardvark/APP/frontend/scss/_colors.scss
  js/apps/system/_admin/aardvark/APP/frontend/scss/_graphViewer.scss
  js/apps/system/_admin/aardvark/APP/frontend/scss/_modals.scss
  js/apps/system/_admin/aardvark/APP/frontend/scss/_tiles.scss
  js/apps/system/_admin/aardvark/APP/react/src/App.js
  js/client/modules/@arangodb/general-graph.js
  js/server/modules/@arangodb/general-graph.js
Labels: 1 Feature, 3 UI, 3 Graph

#16547 [CINFRA-475] Test replicated state change during transaction
  js/client/modules/@arangodb/test-helper.js
  js/common/modules/@arangodb/test-helper-common.js
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-http-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
  js/common/modules/@arangodb/testutils/replicated-state-helper.js
  js/common/modules/@arangodb/testutils/replicated-state-predicates.js
  js/server/modules/@arangodb/test-helper.js
  tests/js/client/replication2/replication2-cluster.js
  tests/js/client/shell/transaction/shell-transaction.js
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/resilience/failover-failure/resilience-synchronous-repl-failureAt-cluster.js
  tests/js/server/resilience/move/moving-shards-cluster.js
Labels: cinfra

#16573 [CINFRA-352] WriteConcern > ReplicationFactor tests
  arangod/Agency/Supervision.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
  tests/js/server/replication2/replication2-regression.js
Labels: cinfra

#16568 [CINFRA-492] Add suite shell_client_transaction
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/Transaction/Methods.cpp
  tests/js/client/shell/transaction/shell-transaction-intermediate-commit-babies-cluster.js
  tests/js/client/shell/transaction/shell-transaction.js
  tests/test-definitions.txt
Labels: 9 Ready to Merge, cinfra

#16578 [Search-324] Fix slow search view creation
  arangod/IResearch/Search.cpp
Labels: 3.10

#16585 [CINFRA-491] WaitForReplicatedComplete for SimpleFailoverTest
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra

#16563 Maintenance mode for dbservers, APM-222
  arangod/Agency/AgencyPaths.h
  arangod/Agency/AgencyStrings.h
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminClusterHandler.h
  tests/Agency/FailedFollowerTest.cpp
  tests/Agency/FailedFollowerTest.json
  tests/Agency/FailedLeaderTest.cpp
  tests/Agency/SupervisionTest.cpp
  tests/js/client/shell/shell-admin-cluster-maintenance-dbservers.js
Labels: 9 Ready to Merge, cinfra, 3.10

#16511 Feature/auto shard rebalance
  CHANGELOG
  Documentation/DocuBlocks/Rest/Administration/get_admin_cluster_rebalance.md
  Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance.md
  Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance_execute.md
  Documentation/DocuBlocks/Rest/Administration/put_admin_cluster_rebalance.md
  arangod/Agency/MoveShard.cpp
  arangod/CMakeLists.txt
  arangod/Cluster/AutoRebalance.cpp
  arangod/Cluster/AutoRebalance.h
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminClusterHandler.h
  tests/CMakeLists.txt
  tests/Cluster/ShardAutoRebalancerTest.cpp
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: 9 Ready to Merge, cinfra, 3.10

#16562 Let arangoimport also ignore Attributes on JSON input
  CHANGELOG
  client-tools/Import/ImportFeature.cpp
  client-tools/Import/ImportHelper.cpp
  client-tools/Import/ImportHelper.h
  js/client/modules/@arangodb/testsuites/importing.js
  tests/js/common/test-data/import/import-large.json
  tests/js/server/import/import-setup.js
  tests/js/server/import/import-teardown.js
  tests/js/server/import/import.js
Labels: 3 ImportExport, 3.10

#16591 [CINFRA-493] Missing Stream if snapshot complete
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/StateMachines/Prototype/PrototypeFollowerState.cpp
  tests/Replication2/Mocks/FakeReplicatedState.h
  tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
Labels: cinfra

#16570 [PREGEL] Fix various small bugs ahead of 3.10
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Worker.cpp
  arangod/Pregel/Worker.h
Labels: 1 Bug, 3 Pregel, 3.10

#16554 Use std::semaphore for UnshackledMutex
  lib/Basics/UnshackledMutex.cpp
  lib/Basics/UnshackledMutex.h
Labels: 3.10

#16588 SEARCH-327 and mock for InvertedIndex
  arangod/IResearch/Search.cpp
  arangod/IResearch/Search.h
  arangod/VocBase/LogicalView.cpp
  tests/CMakeLists.txt
  tests/IResearch/IResearchQueryAggregateTest.cpp
  tests/IResearch/IResearchQueryCommon.h
  tests/Mocks/IResearchInvertedIndexMock.cpp
  tests/Mocks/IResearchInvertedIndexMock.h
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
Labels: 9 WIP

#16567 Bug fix/bts 903
  js/client/modules/@arangodb/testsuites/aql.js
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
  tests/js/common/shell/shell-statement-encoding-noncluster.js
Labels: 3 - Testing, 3.10

#16592 fix tests; need to load the UUID from the file
  js/client/modules/@arangodb/test-helper.js
  js/common/modules/@arangodb/test-helper-common.js
  tests/js/client/shell/shell-replication-responses-cluster.js
  tests/js/server/resilience/failover-failure/resilience-synchronous-repl-failureAt-cluster.js
Labels: 3 - Testing

#16580 make sure a hit deadline produces a bad result
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: 3 - Testing

#16586 Bug fix/cinfra 475 fix assertion during leader change and commit response on failure
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  lib/Basics/Exceptions.cpp
  lib/Basics/Exceptions.h
  tests/js/client/shell/transaction/shell-transaction.js
Labels: cinfra

#16594 fix invocation of golang tests
  js/client/modules/@arangodb/testsuites/go.js
Labels: 9 Ready to Merge, 3 - Testing, 3.10

#16612 [CINFRA-495] Unintentional Dirty Read
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.h
  arangod/RestHandler/RestPrototypeStateHandler.cpp
  arangod/V8Server/v8-prototype-states.cpp
  js/client/modules/@arangodb/arango-prototype-state.js
  tests/js/common/shell/shell-prototype-state-cluster.js
  tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
Labels: cinfra

#16593 BTS-913: Abort startup if timezone is not configured properly.
  CHANGELOG
  arangod/RestServer/TimeZoneFeature.cpp
Labels: 1 Bug

#16603 Web UI: fix edit of community graphs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
Labels: 1 Bug, 3 UI, 3.10

#16613 Feature 3.10/rocksdb change default compression
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: 3 RocksDB

#16601 BTS-824: make sure all are dead on abort
  js/client/modules/@arangodb/testsuites/server_permissions.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/process-utils.js
Labels: 3 - Testing

#16633 try to better align windows core dump handling to jenkins and the crash handler
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: 4 Windows, 3 - Testing

#16531 [CINFRA-470] Follower appendEntries
  CONTRIBUTING.md
  arangod/CMakeLists.txt
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Replication2/ReplicatedLog/LogCommon.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/StateMachines/Document/DocumentCore.cpp
  arangod/Replication2/StateMachines/Document/DocumentCore.h
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentLogEntry.cpp
  arangod/Replication2/StateMachines/Document/DocumentLogEntry.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateStrategy.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateStrategy.h
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/Transaction/ManagedContext.cpp
  arangod/Transaction/ManagedContext.h
  arangod/Transaction/Manager.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/ReplicatedContext.cpp
  arangod/Transaction/ReplicatedContext.h
  arangod/Transaction/SmartContext.cpp
  arangod/Transaction/SmartContext.h
  arangod/Utils/DatabaseGuard.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/vocbase.cpp
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  js/common/modules/@arangodb/testutils/replicated-state-helper.js
  js/common/modules/@arangodb/testutils/replicated-state-predicates.js
  tests/Definition/rlog/pr.fish
  tests/Definition/rlog/pr.ps1
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/js/client/shell/transaction/shell-transaction-cluster.js
  tests/js/client/shell/transaction/shell-transaction.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra

#16626 [CINFRA-443] Fix remaining concurrency issues
  arangod/Replication2/LoggerContext.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/StateInterfaces.h
  arangod/Replication2/ReplicatedState/UnconfiguredStateManager.h
  arangod/Replication2/ReplicatedState/UnconfiguredStateManager.tpp
  arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.h
  tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
  tests/main.cpp
Labels: cinfra

#16643 [3.10] Revert "Use std::semaphore for UnshackledMutex"
  lib/Basics/UnshackledMutex.cpp
  lib/Basics/UnshackledMutex.h
Labels: 1 Bug

#16624 make error message more readable
  client-tools/Benchmark/BenchmarkThread.h
Labels: 3 Benchmark

#16618 Feature 3.10/computed values add test
  tests/js/common/shell/shell-collection-computed-values.js
Labels: 3 - Testing

#16628 BTS-913: Abort startup if timezone is not configured properly. (#16593)
  CHANGELOG
  arangod/RestServer/TimeZoneFeature.cpp
Labels: 1 Bug

#16641 [CINFRA] Proper feature dependencies
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLogFeature.cpp
  arangod/Replication2/ReplicatedState/ReplicatedStateFeature.cpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachineFeature.cpp
  arangod/VocBase/vocbase.cpp
Labels: cinfra

#16540 [PREGEL] Tests for Seeded Pagerank
  js/common/modules/@arangodb/graph/graphs-generation.js
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/common/shell/shell-pregel-components.js
Labels: 3 Pregel, 3 - Testing

#16560 [PREGEL] Add aql pregel result test
  arangod/Aql/Functions.cpp
  arangod/Pregel/Conductor.cpp
  tests/js/common/shell/shell-pregel-basics-example.js
Labels: 3 Pregel

#16634 [PREGEL] Bugfix: stop total pregel time correctly when not storing results
  arangod/Pregel/Conductor.cpp
  arangod/Pregel/Status/Status.h
Labels: 3 Pregel

#16655 [CINFRA-506] Add index to status.
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/StateStatus.h
  tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
  tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
Labels: cinfra

#16625 Bugfix/query search test
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/IResearch/AqlHelper.h
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchFilterFactory.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchKludge.h
  arangod/IResearch/IResearchLinkMeta.h
  tests/IResearch/IResearchFilterArrayInTest.cpp
  tests/IResearch/IResearchFilterBooleanTest.cpp
  tests/IResearch/IResearchFilterInTest.cpp
  tests/IResearch/IResearchQueryAggregateTest.cpp
  tests/IResearch/IResearchQueryAndTest.cpp
  tests/IResearch/IResearchQueryBooleanTermTest.cpp
  tests/IResearch/IResearchQueryCommon.h
  tests/IResearch/IResearchQueryComplexBooleanTest.cpp
  tests/IResearch/IResearchQueryExistsTest.cpp
  tests/IResearch/IResearchQueryFilterTest.cpp
  tests/IResearch/IResearchQueryGeoContainsTest.cpp
  tests/IResearch/IResearchQueryGeoDistanceTest.cpp
  tests/IResearch/IResearchQueryGeoInRangeTest.cpp
  tests/IResearch/IResearchQueryGeoIntersectsTest.cpp
  tests/IResearch/IResearchQueryInRangeTest.cpp
  tests/IResearch/IResearchQueryInTest.cpp
  tests/IResearch/IResearchQueryJoinTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewCountApproximateTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/IResearch/common.cpp
Labels: 9 WIP

#16662 turn down severety, fix error message
  CHANGELOG
  arangod/RestServer/TimeZoneFeature.cpp
Labels: 1 Bug

#16661 turn down severety, fix error message
  CHANGELOG
  arangod/RestServer/TimeZoneFeature.cpp
Labels: 1 Bug

#16637 3.10 backport of PR #16506.
  CHANGELOG
  arangod/GeneralServer/CommTask.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/js/client/shell/api/http-novst.js
  tests/js/client/shell/shell-foxx-cors-spec.js
Labels: 3 UI, 3.10

#16647 Bugfix 3.10/pregel result is empty when store equals true
  arangod/Aql/Functions.cpp
  arangod/Pregel/Conductor.cpp
  tests/js/common/shell/shell-pregel-basics-example.js
Labels: 3 Pregel, 3.10

#16654 Backport in 3.10 for Feature/inverted index tests backport
  tests/Mocks/IResearchInvertedIndexMock.h
Labels: 3 Index, 3 - Testing, 3 ArangoSearch, 3.10

#16658 Fix mangling and add tests 3.10
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/IResearch/AqlHelper.h
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchFilterFactory.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchKludge.h
  arangod/IResearch/IResearchLinkMeta.h
  tests/IResearch/IResearchFilterArrayInTest.cpp
  tests/IResearch/IResearchFilterBooleanTest.cpp
  tests/IResearch/IResearchFilterInTest.cpp
  tests/IResearch/IResearchQueryAggregateTest.cpp
  tests/IResearch/IResearchQueryAndTest.cpp
  tests/IResearch/IResearchQueryBooleanTermTest.cpp
  tests/IResearch/IResearchQueryCommon.h
  tests/IResearch/IResearchQueryComplexBooleanTest.cpp
  tests/IResearch/IResearchQueryExistsTest.cpp
  tests/IResearch/IResearchQueryFilterTest.cpp
  tests/IResearch/IResearchQueryGeoContainsTest.cpp
  tests/IResearch/IResearchQueryGeoDistanceTest.cpp
  tests/IResearch/IResearchQueryGeoInRangeTest.cpp
  tests/IResearch/IResearchQueryGeoIntersectsTest.cpp
  tests/IResearch/IResearchQueryInRangeTest.cpp
  tests/IResearch/IResearchQueryInTest.cpp
  tests/IResearch/IResearchQueryJoinTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewCountApproximateTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/IResearch/common.cpp
Labels: 3 - Testing, 3 ArangoSearch, 3.10

#16660 Fix version to 3.10.0
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/GeneralServer.cpp
  arangod/GeneralServer/GeneralServer.h
  arangod/GeneralServer/GeneralServerFeature.cpp
Labels: 3 API
