Repository arangodb/arangodb, pull requests merged in 2022-09, with the labels that each got.

#16878 [CINFRA-488] EnsureIndex busy loop maintenance
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
Labels: cinfra

#16956 Harden iresearch checks
  3rdParty/iresearch/core/search/min_match_disjunction.hpp
  3rdParty/iresearch/core/search/ngram_similarity_filter.cpp
Labels: 3 ArangoSearch

#16959 make it clear in query explain output that there are document lookups
  CHANGELOG
  js/common/modules/@arangodb/aql/explainer.js
Labels: 3 AQL

#16952 Do not drop follower shard after too many failed shard sync attempts.
  CHANGELOG
  Documentation/Metrics/arangodb_sync_rebuilds_total.yaml
  arangod/Cluster/SynchronizeShard.cpp
  tests/js/client/shell/shell-collection-counts-cluster.js
Labels: 3 Cluster

#16937 fix extracing _id sub attribute with projections
  CHANGELOG
  arangod/Aql/Projections.cpp
  tests/js/server/aql/aql-optimizer-rule-reduce-extraction-to-projection.js
Labels: 3 ArangoSearch

#16964 [3.9] Update potentially invalidated iterator
  3rdParty/iresearch/core/search/min_match_disjunction.hpp
Labels: 3 ArangoSearch

#16910 [CINFRA-538] Resign and apply race condition
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
Labels: cinfra

#16844 [CINFRA-528] Use configured default replication version in more cases.
  arangod/Agency/AgencyComm.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/Maintenance.h
  tests/IResearch/IResearchFeatureTest.cpp
  tests/IResearch/IResearchLinkCoordinatorTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
Labels: cinfra

#16927 add a way to generate stacktraces and coredumps via the debugger
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  tests/test-definitions.txt
Labels: 3 - Testing

#16980 Added startup option `--rocksdb.periodic-compaction-ttl`
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.h
Labels: 3 RocksDB

#16827 [PREGEL] Add tests for Effective Closeness
  js/common/modules/@arangodb/graph/graph-in-database.js
  js/common/modules/@arangodb/graph/graphs-generation.js
  js/common/modules/@arangodb/graph/pregel-test-effective-closeness-helpers.js
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/common/shell/shell-pregel-components.js
Labels: 3 Pregel

#16987 [PREGEL]replaced "PageRank" by "pagerank" everywhere in the API
  CHANGELOG
  arangod/Pregel/Algos/ConnectedComponents.h
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.h
  arangod/Pregel/Algos/HITS.h
  arangod/Pregel/Algos/LabelPropagation.h
  arangod/Pregel/Algos/LineRank.cpp
  arangod/Pregel/Algos/PageRank.cpp
  arangod/Pregel/Algos/RecoveringPageRank.h
  arangod/Pregel/Algos/SCC.h
  arangod/Pregel/Algos/SSSP.h
  arangod/Pregel/Algos/WCC.h
  js/client/modules/@arangodb/air/single-source-shortest-paths.js
  js/client/modules/@arangodb/air/strongly-connected-components.js
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
  tests/js/common/shell/shell-pregel-random.js
Labels: 3 Pregel

#16877 [PREGEL]Test/pregel linerank
  arangod/Pregel/Algos/LineRank.h
Labels: 3 Pregel

#16985 BTS-1000: wait for agency to give us a good state before we start firing up the rest of the instance
  js/client/modules/@arangodb/testsuites/server_permissions.js
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing

#17000 [PREGEL] use future to start gss
  arangod/Pregel/Conductor/ClusterWorkerApi.cpp
  arangod/Pregel/Conductor/ClusterWorkerApi.h
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/SingleServerWorkerApi.cpp
  arangod/Pregel/Conductor/SingleServerWorkerApi.h
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/ComputingState.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/NetworkConnection.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/WorkerConductorMessages.h
  arangod/Pregel/WorkerInterface.h
Labels: 3 Pregel

#16902 [3.10] [BTS-951] Fix removeUnnecessaryRemoteScatterRule
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
Labels: 1 Bug

#16929 fix potential data races in dump/restore queue (#16775)
  client-tools/Dump/DumpFeature.cpp
  client-tools/Dump/DumpFeature.h
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Restore/RestoreFeature.h
  client-tools/Utils/ClientTaskQueue.h
Labels: TSan

#16933 [3.10] Fix stack-use-after-scope in fuertetest
  tests/Fuerte/ConnectionConcurrentTest.cpp
Labels: ASan

#16949 [3.10] SEARCH-343 and SEARCH-322
  CHANGELOG
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/IResearch/AqlHelper.h
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchFilterFactory.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/ViewSnapshot.cpp
  arangod/IResearch/ViewSnapshot.h
  tests/IResearch/IResearchFilterArrayInTest.cpp
  tests/IResearch/IResearchInvertedIndexMetaTest.cpp
  tests/IResearch/common.cpp
  tests/IResearch/common.h
Labels: 3 ArangoSearch

#16954 Do not drop follower shard after too many failed shard sync attempts.
  CHANGELOG
  Documentation/Metrics/arangodb_sync_rebuilds_total.yaml
  arangod/Cluster/SynchronizeShard.cpp
  tests/js/client/shell/shell-collection-counts-cluster.js
Labels: 3 Cluster

#16968 [3.10] Removed endless and useless SPAM from WARN
  CHANGELOG
  arangod/IResearch/GeoFilter.cpp
Labels: 3 Search

#16971 added new option --arangosearch.skip-recovery (#16900)
  CHANGELOG
  Documentation/Metrics/arangodb_search_num_out_of_sync_links.yaml
  arangod/Aql/IResearchViewNode.cpp
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.h
  arangod/IResearch/ViewSnapshot.cpp
  arangod/IResearch/ViewSnapshot.h
  arangod/Metrics/MetricsFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBRecoveryHelper.h
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  tests/IResearch/CMakeLists.txt
  tests/IResearch/IResearchFeatureTest.cpp
  tests/IResearch/IResearchRocksDBRecoveryHelperTest.cpp
  tests/js/client/shell/shell-arangosearch-out-of-sync-cluster.js
  tests/js/server/recovery/out-of-sync-inverted-index.js
  tests/js/server/recovery/out-of-sync-link.js
Labels: 3 ArangoSearch, 3 Recovery

#16983 Inverted index stats and metric backport for 3.10
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndex.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchLinkCoordinator.h
  arangod/IResearch/IResearchMetricStats.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/Metrics/ClusterMetricsFeature.h
  tests/Mocks/IResearchInvertedIndexMock.cpp
  tests/Mocks/IResearchInvertedIndexMock.h
  tests/Mocks/IResearchLinkMock.h
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
Labels: 3 Index, 3 ArangoSearch, 3 Metrics

#16984 [3.10] SEARCH-334 and SEARCH-376
  CHANGELOG
  arangod/Aql/OptimizerUtils.cpp
  arangod/IResearch/AqlHelper.cpp
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/Search.cpp
  arangod/IResearch/Search.h
  arangod/Indexes/Index.h
  tests/IResearch/IResearchDocumentTest.cpp
  tests/IResearch/IResearchInvertedIndexMetaTest.cpp
  tests/js/common/shell/shell-view-search-alias.js
  tests/js/server/aql/aql-inverted-index.js
Labels: 3 ArangoSearch

#17005 Fix waitForSync for non-maintainer build 3.10
  CHANGELOG
  arangod/IResearch/Search.cpp
  arangod/IResearch/ViewSnapshot.cpp
Labels: 3 ArangoSearch

#16936 fix extracing _id sub attribute with projections
  CHANGELOG
  arangod/Aql/Projections.cpp
  tests/js/server/aql/aql-optimizer-rule-reduce-extraction-to-projection.js
Labels: 3 Optimizer, 3 ArangoSearch

#16981 Added startup option `--rocksdb.periodic-compaction-ttl`
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.h
  arangod/RocksDBEngine/RocksDBOptionsProvider.cpp
  arangod/RocksDBEngine/RocksDBOptionsProvider.h
  tests/sepp/RocksDBOptions.cpp
  tests/sepp/RocksDBOptions.h
Labels: 3 RocksDB

#16998 add optional log output for RocksDB compactions
  arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.cpp
  arangod/RocksDBEngine/Listeners/RocksDBMetricsListener.h
Labels: 3 RocksDB

#16999 BTS-1003: make test use less memory
  tests/js/server/aql/aql-vector-functions.js
Labels: 3 AQL, 3 - Testing

#16938 fix extracing _id sub attribute with projections
  CHANGELOG
  arangod/Aql/Projections.cpp
  tests/js/server/aql/aql-optimizer-rule-reduce-extraction-to-projection.js
Labels: 3 Optimizer, 3 ArangoSearch

#16965 [3.8] Update potenitally invalidated iterator.
  3rdParty/iresearch/core/search/min_match_disjunction.hpp
Labels: 3 ArangoSearch

#17012 fix wrong type for geoJson attribute (string -> boolean)
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
Labels: 3 Documentation, 3 Swagger, 3 Geo

#16953 Do not drop follower shard after too many failed shard sync attempts
  CHANGELOG
  Documentation/Metrics/arangodb_sync_rebuilds_total.yaml
  arangod/Cluster/SynchronizeShard.cpp
  tests/js/client/shell/shell-collection-counts-cluster.js
Labels: 3 Cluster

#17021 [3.10] Fixes to `test-soft-shutdown-cluster.js`
  js/client/modules/@arangodb/pregel.js
  js/server/modules/@arangodb/pregel.js
  tests/js/client/restart/test-soft-shutdown-cluster.js
  tests/js/client/restart/test-soft-shutdown-pregel-cluster.js
Labels: 3 Cluster, 3 - Testing

#17010 [CINFRA-511] Improve transaction handling in leader state
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
  arangod/Transaction/Manager.h
  tests/Replication2/ReplicatedLog/RocksDBLogTest.cpp
  tests/Replication2/ReplicatedLog/TestHelper.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Labels: cinfra

#17013 fix wrong type for geoJson attribute (string -> boolean)
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
Labels: 3 Documentation, 3 Swagger, 3 Geo, 3.10-beta-1

#16958 make it clear in query explain output that there are document lookups
  js/common/modules/@arangodb/aql/explainer.js
Labels: 3 AQL

#17018 Prefetch for revision trees - BTS-989
  CHANGELOG
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.h
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBV8Functions.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/StorageEngine/PhysicalCollection.h
Labels: 3 RocksDB, 3.10-beta-1

#17020 Fixed a rare traversal issue (Satellite -> DisjointSmartGraph & OneShard rule) ES-1265
  CHANGELOG
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/QueryOptions.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/Graph/PathManagement/PathValidator.h
  arangod/Graph/PathManagement/PathValidatorOptions.cpp
  arangod/Graph/PathManagement/PathValidatorOptions.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
Labels: 1 Bug, 3 Graph, 9 Review Required, 3.10-beta-1

#17024 fix random haustier bug
  arangod/Aql/Quantifier.cpp
  tests/js/server/aql/aql-array-access.js
Labels: 3 AQL, 3.10-beta-1

#17033 adjust naming to better reflect their meaning
  tests/test-definitions.txt
Labels: 3 - Testing

#17035 adjust naming to better reflect their meaning
  tests/test-definitions.txt
Labels: 3 - Testing

#17034 adjust naming to better reflect their meaning
  tests/test-definitions.txt
Labels: 3 - Testing

#17039 [3.10] Search-371
  arangod/Aql/ConditionFinder.cpp
  arangod/Aql/IndexHint.cpp
  arangod/Aql/IndexHint.h
  arangod/Aql/IndexNode.cpp
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/Indexes/IndexIterator.h
  lib/Basics/StaticStrings.h
  tests/js/client/shell/shell-arangosearch-out-of-sync-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/server/aql/aql-inverted-index.js
  tests/js/server/aql/aql-options-verification.js
  tests/js/server/recovery/view-search-alias-create-drop-no-flushthread.js
  tests/js/server/recovery/view-search-alias-create-nonempty.js
  tests/js/server/recovery/view-search-alias-create.js
  tests/js/server/recovery/view-search-alias-drop-collection-no-flushthread.js
  tests/js/server/recovery/view-search-alias-drop-collection.js
  tests/js/server/recovery/view-search-alias-drop-no-flushthread.js
  tests/js/server/recovery/view-search-alias-drop.js
  tests/js/server/recovery/view-search-alias-index-create-no-flushthread.js
  tests/js/server/recovery/view-search-alias-index-create.js
  tests/js/server/recovery/view-search-alias-modify-properties.js
  tests/js/server/recovery/view-search-alias-populate-crash-after-release.js
  tests/js/server/recovery/view-search-alias-populate-drop-collection-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-drop-link-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-drop-view-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-fail.js
  tests/js/server/recovery/view-search-alias-populate-no-callbacks.js
  tests/js/server/recovery/view-search-alias-populate-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-no-release.js
  tests/js/server/recovery/view-search-alias-populate-no-sync.js
  tests/js/server/recovery/view-search-alias-populate-remove-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-remove.js
  tests/js/server/recovery/view-search-alias-populate-transaction-abort-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction-abort.js
  tests/js/server/recovery/view-search-alias-populate-transaction-multiple-batches-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction-single-batch-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction.js
  tests/js/server/recovery/view-search-alias-populate-truncate-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-truncate-replay.js
  tests/js/server/recovery/view-search-alias-populate-truncate.js
  tests/js/server/recovery/view-search-alias-populate.js
  tests/js/server/recovery/view-search-alias-properties.js
  tests/js/server/recovery/view-search-alias-recover-tick-in-past-noncluster.js
  tests/js/server/recovery/view-search-alias-recover-view-not-again-noncluster.js
  tests/js/server/recovery/view-search-alias-recreate.js
  tests/js/server/recovery/view-search-alias-rename-collection-no-flushthread-noncluster.js
  tests/js/server/recovery/view-search-alias-rename-collection-noncluster.js
  tests/js/server/recovery/view-search-alias-rename-no-flushthread-noncluster.js
  tests/js/server/recovery/view-search-alias-rename-noncluster.js
  tests/js/server/recovery/view-search-alias-rename-query-noncluster.js
  tests/js/server/recovery/view-search-alias-rename-recreate-flush-noncluster.js
  tests/js/server/recovery/view-search-alias-rename-recreate-noncluster.js
  tests/js/server/recovery/view-search-alias-view-create-drop.js
  tests/js/server/recovery/view-searhc-alias-populate-crash-after-release.js
Labels: 3 ArangoSearch, 3.10-beta-1

#17032 adjust naming to better reflect their meaning
  tests/test-definitions.txt
Labels: 3 - Testing

#16967 [3.9] Removed endless and useless SPAM from WARN
  arangod/IResearch/GeoFilter.cpp
Labels: 3 Search, 3 ArangoSearch

#17014 fix wrong type for geoJson attribute (string -> boolean)
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
Labels: 3 Documentation

#16584 DOC-123 | Add `computedValues` collection property for Computed Values
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
Labels: 3 Documentation

#17011 Docs/added missing descriptions for HTTP Graph examples
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
Labels: 3 Documentation

#17040 BTS-1002: make timeout in tests progressive if we monitor test progress
  tests/js/server/shell/shell-index-background.js
Labels: 3 - Testing

#17038 BTS-998: use setupAll, split writing tests
  tests/js/server/aql/aql-optimizer-collect-count.js
Labels: 3 Optimizer, 3 - Testing

#17045 Inverted index hotbackup 3.10
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/Search.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/StorageEngine/HotBackup.cpp
  client-tools/Restore/RestoreFeature.cpp
  tests/js/server/dump/dump-authentication.js
  tests/js/server/dump/dump-setup-cluster.js
  tests/js/server/dump/dump-setup-common.inc
  tests/js/server/dump/dump-setup-mixed.js
  tests/js/server/dump/dump-setup.js
  tests/js/server/dump/dump-test.inc
Labels: 3 ArangoSearch, 3.10-beta-1

#17059 do not carry out insert/remove in out-of-sync links
  arangod/IResearch/IResearchDataStore.cpp
  tests/js/server/shell/shell-arangosearch-out-of-sync-noncluster.js
Labels: 3 ArangoSearch, 3.10-beta-1

#17062 Bugfix 3.10/BTS-980
  arangod/Aql/Functions.cpp
  tests/Aql/DistanceFunctionTest.cpp
Labels: 3 AQL, 3.10-beta-1

#17078 [SEARCH-362] Handle nested fields in CE (#17070)
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchLinkMeta.cpp
  tests/IResearch/IResearchIndexTest.cpp
  tests/IResearch/IResearchInvertedIndexMetaTest.cpp
  tests/IResearch/IResearchLinkMetaTest.cpp
Labels: 3.10-beta-1

#17069 fix a potential nullptr dereference in revision tree fetching
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
Labels: 3.10-beta-1

#17063 remove special handling for is-wsl node module (#17054)
  cmake/InstallArangoDBJSClient.cmake
Labels: 3 Packaging

#17071 display progress during link recovery
  CHANGELOG
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
Labels: 3 ArangoSearch, 3 Recovery

#17068 make test use less memory (#16999)
  tests/js/server/aql/aql-vector-functions.js
Labels: 9 Ready to Merge, 3 - Testing

#17050 DOC-160 | DOC-182 | Index API parameters / Rebalance API improvements
  Documentation/DocuBlocks/Rest/Administration/1_structs.md
  Documentation/DocuBlocks/Rest/Administration/get_admin_cluster_rebalance.md
  Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance.md
  Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance_execute.md
  Documentation/DocuBlocks/Rest/Administration/put_admin_cluster_rebalance.md
  Documentation/DocuBlocks/Rest/Indexes/get_api_index.md
Labels: 3 Documentation, 3 API, 3 Search, 3 Index

#17019 Prefetch for revision trees - BTS-989
  CHANGELOG
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.h
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBV8Functions.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/StorageEngine/PhysicalCollection.h
Labels: 9 Ready to Merge

#16979 added new option --arangosearch.skip-recovery
  CHANGELOG
  Documentation/Metrics/arangodb_search_num_out_of_sync_links.yaml
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.h
  arangod/IResearch/IResearchView.cpp
  arangod/RocksDBEngine/RocksDBRecoveryHelper.h
  tests/IResearch/CMakeLists.txt
  tests/IResearch/IResearchFeature-test.cpp
  tests/IResearch/IResearchRocksDBRecoveryHelper-test.cpp
  tests/js/client/shell/shell-arangosearch-out-of-sync-cluster.js
  tests/js/server/recovery/out-of-sync-link.js
  tests/js/server/shell/shell-arangosearch-out-of-sync-noncluster.js
  utils/generateAllMetricsDocumentation.py
Labels: 3 ArangoSearch, 3 Recovery

#17076 BTS-970: verify collection pointer before dereferencing it
  arangod/Transaction/Methods.cpp
Labels: 1 Bug

#17051 add more logging for revision trees
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: 3.10.1

#17049 DOC-160 | DOC-182 | Index API parameters / Rebalance API improvements
  Documentation/DocuBlocks/Rest/Administration/1_structs.md
  Documentation/DocuBlocks/Rest/Administration/get_admin_cluster_rebalance.md
  Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance.md
  Documentation/DocuBlocks/Rest/Administration/post_admin_cluster_rebalance_execute.md
  Documentation/DocuBlocks/Rest/Administration/put_admin_cluster_rebalance.md
  Documentation/DocuBlocks/Rest/Indexes/get_api_index.md
Labels: 3 Documentation, 3 API, 3 Search, 3 Index

#17052 Bug fix 3.9/SEARCH-374
  3rdParty/iresearch/core/formats/sparse_bitmap.cpp
  CHANGELOG
Labels: 3 ArangoSearch

#17061 bugfix 3.9/BTS-980
  arangod/Aql/Functions.cpp
  tests/Aql/DistanceFunctionTest.cpp
Labels: 3 AQL

#17030 Documentation/inverted index
  Documentation/DocuBlocks/Rest/Indexes/post_api_index.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_fulltext.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_persistent.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_ttl.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_zkd.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_searchalias.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_searchalias.md
Labels: 1 Feature, 3 Documentation, 3 API, 3 Index

#17002 Documentation 3.10/inverted index
  Documentation/DocuBlocks/Rest/Indexes/post_api_index.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_fulltext.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_persistent.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_ttl.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_zkd.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_searchalias.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_searchalias.md
Labels: 1 Feature, 3 Documentation, 3 API, 3 Index

#17082 Testframework: Fix handling in crash analysis
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing

#17087 Testframework: Fix handling in crash analysis
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing

#17081 improve test stability
  tests/js/server/recovery/out-of-sync-link.js
Labels: 3 - Testing, 3 ArangoSearch

#17092 Testframework: if we timeout waiting for an instance shutdown, properly pick up the debugger again
  js/client/modules/@arangodb/testutils/instance.js
  tests/js/client/restart/test-soft-shutdown-pregel-cluster.js
Labels: 3 - Testing

#17025 Fixed a rare traversal issue (Satellite -> DisjointSmartGraph & OneShard rule) ES-1265
  CHANGELOG
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/QueryOptions.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/Graph/TraverserOptions.cpp
  arangod/Graph/TraverserOptions.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
Labels: 1 Bug, 3 Graph, 9 Review Required

#17102 Disable frequently failing soft shutdown pregel test
  tests/js/client/restart/test-soft-shutdown-pregel-cluster-disabled.js
Labels: 3 Pregel

#17110 Disable frequently failing pregel test... correctly
  tests/js/client/restart/test-soft-shutdown-pregel-cluster.js_DISABLED
Labels: 3 Pregel

#17037 [PREGEL]Copy vertex property
  arangod/CMakeLists.txt
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/Algos/ReadWrite.cpp
  arangod/Pregel/Algos/ReadWrite.h
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/Worker.cpp
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  js/common/modules/@arangodb/graph/pregel-test-read-write-helpers.js
  tests/js/common/shell/shell-pregel-components.js
Labels: 3 Pregel

#17066 [CINFRA-483] MoveShard for Replication 2
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/MoveShard.h
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  tests/js/server/resilience/move/moving-shards-cluster.js
Labels: cinfra

#17108 [PREGEL] Delete brittle pregel test assertion
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
Labels: 3 Pregel

#16966 Removed endless and useless SPAM from WARN
  CHANGELOG
  arangod/IResearch/GeoFilter.cpp
Labels: 3 Search

#17103 [3.10] Disable frequently failing soft shutdown pregel test
  tests/js/client/restart/test-soft-shutdown-pregel-cluster.js_DISABLED
Labels: 3 Pregel, 3 - Testing

#17091 Testframework: if we timeout waiting for an instance shutdown, properly pick up the debugger again
  js/client/modules/@arangodb/testutils/instance.js
  tests/js/client/restart/test-soft-shutdown-cluster.js
  tests/js/client/restart/test-soft-shutdown-pregel-cluster.js_DISABLED
Labels: 3 - Testing

#16874 Remove clock_gettime detection
  CMakeLists.txt
  cmake/test_clock_gettime.c
  lib/CMakeLists.txt
  lib/Utilities/clock_gettime.cpp
Labels: cmake improvements, post-3.10-beta-mergefest

#16875 Extract cmake files in arangod
  arangod/Agency/CMakeLists.txt
  arangod/Aql/CMakeLists.txt
  arangod/CMakeLists.txt
  arangod/Cache/CMakeLists.txt
  arangod/Pregel/Algos/AIR/CMakeLists.txt
  arangod/Pregel/Algos/CMakeLists.txt
  arangod/Pregel/Algos/DMID/CMakeLists.txt
  arangod/Pregel/Algos/EffectiveCloseness/CMakeLists.txt
  arangod/Pregel/CMakeLists.txt
  arangod/StorageEngine/CMakeLists.txt
Labels: cmake improvements, post-3.10-beta-mergefest

#17036 [PREGEL] Send general messages between worker and conductor
  arangod/Pregel/Conductor/ClusterWorkerApi.cpp
  arangod/Pregel/Conductor/ClusterWorkerApi.h
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/NetworkConnection.cpp
  arangod/Pregel/NetworkConnection.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/WorkerConductorMessages.h
Labels: 3 Pregel

#17053 [PREGEL] use general messages for all communication between conductor and workers
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/DoneState.cpp
  arangod/Pregel/Conductor/States/FatalErrorState.cpp
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/IncomingCache.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Status/ConductorStatus.h
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/WorkerConductorMessages.h
Labels: 3 Pregel

#17067 [PREGEL] Improve connection
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/Conductor/CMakeLists.txt
  arangod/Pregel/Conductor/ClusterWorkerApi.h
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/SingleServerWorkerApi.cpp
  arangod/Pregel/Conductor/SingleServerWorkerApi.h
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/Connection/CMakeLists.txt
  arangod/Pregel/Connection/Connection.h
  arangod/Pregel/Connection/DirectConnection.cpp
  arangod/Pregel/Connection/DirectConnection.h
  arangod/Pregel/Connection/NetworkConnection.cpp
  arangod/Pregel/Connection/NetworkConnection.h
  arangod/Pregel/NetworkConnection.cpp
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/OutgoingCache.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel

#17126 [PREGEL] Improved explanation of Pregel SCC and tidification
  arangod/Pregel/Aggregator.h
  arangod/Pregel/Algos/SCC.cpp
  arangod/Pregel/Algos/SCC.h
  arangod/Pregel/Graph.h
Labels: 3 Pregel

#17065 [CINFRA-521] Always perform replace operations during replication
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransaction.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/VocBase/Identifiers/TransactionId.cpp
  arangod/VocBase/Identifiers/TransactionId.h
  tests/Replication2/Mocks/PersistedLog.cpp
  tests/Replication2/Mocks/PersistedLog.h
  tests/Replication2/ReplicatedLog/TestHelper.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Labels: cinfra

#17096 [PREGEL] Use future for cleanup
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/CanceledState.h
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/Conductor/States/StoringState.h
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/Worker/GraphStore.cpp
  arangod/Pregel/Worker/GraphStore.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/WorkerConductorMessages.h
  arangod/Pregel/WorkerInterface.h
Labels: 3 Pregel

#17105 [PREGEL] Use future to collect results
  arangod/Aql/Functions.cpp
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/DoneState.cpp
  arangod/Pregel/Conductor/States/DoneState.h
  arangod/Pregel/Conductor/States/FatalErrorState.cpp
  arangod/Pregel/Conductor/States/FatalErrorState.h
  arangod/Pregel/Conductor/States/State.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/Connection/Connection.h
  arangod/Pregel/Connection/DirectConnection.cpp
  arangod/Pregel/Connection/DirectConnection.h
  arangod/Pregel/Connection/NetworkConnection.cpp
  arangod/Pregel/Connection/NetworkConnection.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/WorkerConductorMessages.h
  arangod/Pregel/WorkerInterface.h
  arangod/V8Server/v8-collection.cpp
Labels: 3 Pregel

#17106 Make collection name available for inverted index on DBServer
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  tests/IResearch/IResearchInvertedIndexMetaTest.cpp
Labels: 3.10

#17113 avoid static init order fiasco
  lib/ProgramOptions/Parameters.cpp
Labels: 3.10

#17117 more checks for potential nullptr dereferences
  arangod/Transaction/Methods.cpp
Labels: 3.10

#17122 Bug fix 3.10/SEARCH-373 SEARCH-386
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.h
  tests/js/server/aql/aql-inverted-index.js
Labels: 3 ArangoSearch, 3.10

#17134 [BTS-1017] Fix optimizer rule for Hybrid Disjoint Smart Graphs
  CHANGELOG
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
Labels: 1 Bug, 3 AQL, 3 Graph

#17125 [PREGEL] New Pregel SCC test
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
Labels: 3 Pregel, 3 - Testing

#17142 Bug fix/SEARCH-392
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.h
  tests/IResearch/IResearchInvertedIndexMetaTest.cpp
Labels: Backport Needed

#17136 [BTS-1017] Fix optimizer rule for Hybrid Disjoint Smart Graphs
  CHANGELOG
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
Labels: 1 Bug, 3 AQL, 3 Graph

#17135 added missing parameter documentation for components
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: 3 Documentation, 9 Ready to Merge

#17148 [PREGEL] Cleanup conductor statemachine
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/CMakeLists.txt
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/CanceledState.h
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/ComputingState.h
  arangod/Pregel/Conductor/States/DoneState.cpp
  arangod/Pregel/Conductor/States/DoneState.h
  arangod/Pregel/Conductor/States/FatalErrorState.cpp
  arangod/Pregel/Conductor/States/FatalErrorState.h
  arangod/Pregel/Conductor/States/InErrorState.cpp
  arangod/Pregel/Conductor/States/InErrorState.h
  arangod/Pregel/Conductor/States/InitialState.cpp
  arangod/Pregel/Conductor/States/InitialState.h
  arangod/Pregel/Conductor/States/LoadingState.cpp
  arangod/Pregel/Conductor/States/LoadingState.h
  arangod/Pregel/Conductor/States/State.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/Conductor/States/StoringState.h
  arangod/Pregel/PregelFeature.cpp
Labels: 3 Pregel

#17147 [SEARCH-396] Use warnings instead of errors for search-alias views
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchFilterFactory.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/Search.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.inc
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
Labels: Backport Needed

#17149 add additional test cases for the OFFSET_INFO feature
  LICENSES-OTHER-COMPONENTS.md
  js/common/bootstrap/modules/internal.js
  tests/js/common/test-data/search/texts/chinese_dreams.txt
Labels: 3 - Testing, 3 ArangoSearch

#17161 Hotbackup up/download speedup - BTS-987
  CHANGELOG
  lib/Basics/process-utils.cpp
  lib/Basics/process-utils.h
Labels: 3.10

#17160 [SEARCH-396] Use warnings instead of errors for search-alias views
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchFilterFactory.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/Search.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.inc
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
Labels: 3 ArangoSearch, 3.10

#17172 test-infrastructure: put crashdump into json file; put reason string into crashinfo
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/result-processing.js
  scripts/examine_results.js
Labels: 3 - Testing

#17166 add test cases for OFFSET_INFO feature
  LICENSES-OTHER-COMPONENTS.md
  js/common/bootstrap/modules/internal.js
  tests/js/common/test-data/search/texts/chinese_dreams.txt
Labels: 3 - Testing, 3 ArangoSearch

#17174 put crashdump into json file; put reason string into crashinfo (#17172)
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/result-processing.js
  scripts/examine_results.js
Labels: 3 - Testing

#17162 Hotbackup up/download speedup - BTS-987
  CHANGELOG
  lib/Basics/process-utils.cpp
  lib/Basics/process-utils.h
Labels: 3 ImportExport

#17178 [PREGEL] Delete AIR directory
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/Algos/AIR/AIR.cpp
  arangod/Pregel/Algos/AIR/AIR.h
  arangod/Pregel/Algos/AIR/AbstractAccumulator.cpp
  arangod/Pregel/Algos/AIR/AbstractAccumulator.h
  arangod/Pregel/Algos/AIR/AccumulatorOptions.cpp
  arangod/Pregel/Algos/AIR/AccumulatorOptions.h
  arangod/Pregel/Algos/AIR/Accumulators.cpp
  arangod/Pregel/Algos/AIR/Accumulators.h
  arangod/Pregel/Algos/AIR/CMakeLists.txt
  arangod/Pregel/Algos/AIR/EdgeData.cpp
  arangod/Pregel/Algos/AIR/EdgeData.h
  arangod/Pregel/Algos/AIR/GraphFormat.cpp
  arangod/Pregel/Algos/AIR/GraphFormat.h
  arangod/Pregel/Algos/AIR/MasterContext.cpp
  arangod/Pregel/Algos/AIR/MasterContext.h
  arangod/Pregel/Algos/AIR/MessageData.cpp
  arangod/Pregel/Algos/AIR/MessageData.h
  arangod/Pregel/Algos/AIR/MessageFormat.cpp
  arangod/Pregel/Algos/AIR/MessageFormat.h
  arangod/Pregel/Algos/AIR/VertexComputation.cpp
  arangod/Pregel/Algos/AIR/VertexComputation.h
  arangod/Pregel/Algos/AIR/VertexData.cpp
  arangod/Pregel/Algos/AIR/VertexData.h
  arangod/Pregel/Algos/AIR/WorkerContext.cpp
  arangod/Pregel/Algos/AIR/WorkerContext.h
  arangod/Pregel/Algos/CMakeLists.txt
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/Worker/GraphStore.cpp
  arangod/Pregel/Worker/Worker.cpp
  js/client/modules/@arangodb/air/access-data.js
  js/client/modules/@arangodb/air/accumulators.js
  js/client/modules/@arangodb/air/global-accumulator-test.js
  js/client/modules/@arangodb/air/js-syntax.js
  js/client/modules/@arangodb/air/pagerank.js
  js/client/modules/@arangodb/air/pregel-example-graphs.js
  js/client/modules/@arangodb/air/propagation-demo.js
  js/client/modules/@arangodb/air/random-walk.js
  js/client/modules/@arangodb/air/sexpression-syntax.js
  js/client/modules/@arangodb/air/single-source-shortest-paths.js
  js/client/modules/@arangodb/air/strongly-connected-components.js
  js/client/modules/@arangodb/air/test-helpers.js
  js/client/modules/@arangodb/air/vertex-degrees-sexpression.js
  js/client/modules/@arangodb/air/vertex-degrees.js
  tests/js/client/shell/shell-custom-pregel-timecritical.js
Labels: 3 Pregel

#17179 [PREGEL] Delete reports
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/MasterContext.h
  arangod/Pregel/Reports.cpp
  arangod/Pregel/Reports.h
  arangod/Pregel/VertexComputation.h
  arangod/Pregel/Worker/GraphStore.cpp
  arangod/Pregel/Worker/GraphStore.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/Worker/WorkerContext.h
  arangod/Pregel/WorkerConductorMessages.h
Labels: 3 Pregel

#17181 [PREGEL] Delete greenspun
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  arangod/Pregel/GraphFormat.h
  arangod/Pregel/Worker/GraphStore.cpp
  arangod/Pregel/Worker/Worker.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/CMakeLists.txt
  lib/Greenspun/EvalResult.h
  lib/Greenspun/Extractor.h
  lib/Greenspun/Interpreter.cpp
  lib/Greenspun/Interpreter.h
  lib/Greenspun/Primitives.cpp
  lib/Greenspun/Primitives.h
  lib/Greenspun/lib/DateTime.cpp
  lib/Greenspun/lib/DateTime.h
  lib/Greenspun/lib/Dicts.cpp
  lib/Greenspun/lib/Dicts.h
  lib/Greenspun/lib/Lists.cpp
  lib/Greenspun/lib/Lists.h
  lib/Greenspun/lib/Math.cpp
  lib/Greenspun/lib/Math.h
  lib/Greenspun/lib/Strings.cpp
  lib/Greenspun/lib/Strings.h
  tests/CMakeLists.txt
  tests/Greenspun/CMakeLists.txt
  tests/Greenspun/PrimitivesTest.cpp
  tests/Greenspun/REPL.cpp
Labels: 3 Pregel

#17158 bug-fix/SEARCH-393
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/Search.cpp
  tests/js/common/shell/shell-view-search-alias.js
Labels: Backport Needed

#17182 [3.10][ES-1195] Add sorting by history
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/queryView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 3 UI

#17183 [3.10] APM-517: Show values upon hover on blue attribute labels
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 3 UI

#17184 [3.10] ES-1085: Keep node color consistent after expansion when coloring by attribute
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 3 UI

#16893 Added EnterpriseGraph Dump & Restore Tests
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Sharding/ShardingFeature.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/vocbase.cpp
  tests/js/server/dump/dump-authentication.js
  tests/js/server/dump/dump-cluster.js
  tests/js/server/dump/dump-modified.js
  tests/js/server/dump/dump-setup-cluster.js
  tests/js/server/dump/dump-setup-common.inc
  tests/js/server/dump/dump-setup-mixed.js
  tests/js/server/dump/dump-setup.js
  tests/js/server/dump/dump-test.inc
  tests/js/server/dump/dump.js
  tests/test-definitions.txt
Labels: 9 Waiting for Jenkins, 9 Review Required, 3.10

#17187 Bug fix 3.10/search 393
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/Search.cpp
  tests/js/common/shell/shell-view-search-alias.js
Labels: 3 ArangoSearch, 3.10

#17180 fix view creation order
  arangod/Replication/DatabaseInitialSyncer.cpp
  tests/js/server/replication/sync/replication-sync.js
Labels: 3 ArangoSearch, 3.10

#17155 BTS-1014: fix issues with transactional truncate
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  tests/IResearch/IResearchAnalyzerFeatureTest.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: 3.10

#17164 Hotbackup up/download speedup - BTS-987
  CHANGELOG
  lib/Basics/process-utils.cpp
  lib/Basics/process-utils.h
  tests/CMakeLists.txt
Labels: 3 ImportExport

#17173 [CINFRA-496] CleanOut/Resign Server for Repl2
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.h
  arangod/Agency/ResignLeadership.cpp
  tests/Agency/CleanOutServerTest.json
  tests/js/server/resilience/move/moving-shards-cluster.js
  tests/js/server/resilience/sharddist/shard-distribution-spec.js
  tests/js/server/resilience/sharddist/shard-distribution.js
Labels: cinfra

#16919 GitHub Workflows security hardening
  .github/workflows/clang-format.yml
Labels: 9 CLA available

#17170 [CINFRA-548] Disable collection-count tests for replication 2.0
  tests/js/client/shell/shell-collection-counts-cluster.js
  tests/js/client/shell/shell-dropped-followers-elcheapo-commit-cluster.js
  tests/js/client/shell/shell-following-term-id-cluster.js
Labels: cinfra

#17171 [CINFRA-556] Fix drop index operation with replication 2.0
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/Transaction/Options.h
  arangod/VocBase/Methods/Indexes.cpp
Labels: cinfra

#17194 [testInfrastructure]: improve shutdown force messages
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: 3 - Testing

#17201 [BTS-1043] Fix index executor
  arangod/Aql/IndexExecutor.cpp
  tests/js/server/aql/aql-index-skip-regression.js
Labels: Backport Needed

#17206 Drop replicated states during database shutdown
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/VocBase/vocbase.cpp
  tests/Replication2/ReplicatedState/StateCleanupTest.cpp
Labels: 1 Bug, cinfra

#17214 Removing intentional sleep from tests
  tests/js/client/shell/transaction/shell-transaction.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra

#17226 fix failing test
  tests/js/client/shell/shell-transaction-intermediate-commit-cluster.js
Labels: 3 - Testing

#17208 Fix view properties change replication
  CHANGELOG
  arangod/Replication/TailingSyncer.cpp
  tests/js/server/replication/ongoing/global/replication-ongoing-global.js
  tests/js/server/replication/ongoing/replication-ongoing.js
  tests/js/server/replication/static/replication-static.js
Labels: 3 Leader/Follower Replication, 3 ArangoSearch

#17211 Fix view properties change replication
  CHANGELOG
  arangod/Replication/TailingSyncer.cpp
  tests/js/server/replication/ongoing/global/replication-ongoing-global.js
  tests/js/server/replication/ongoing/replication-ongoing.js
  tests/js/server/replication/static/replication-static.js
Labels: 3 ArangoSearch

#17212 allow cmaking with "wrong" openssl version for developers
  CMakeLists.txt
Labels: 3 Build

#17156 BTS-1014: fix issues with transactional truncate
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/Transaction/Methods.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  tests/IResearch/IResearchAnalyzerFeature-test.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: 3 Transaction

#17169 [PREGEL] Combine worker apis
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/CanceledState.h
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/ComputingState.h
  arangod/Pregel/Conductor/States/DoneState.cpp
  arangod/Pregel/Conductor/States/DoneState.h
  arangod/Pregel/Conductor/States/FatalErrorState.cpp
  arangod/Pregel/Conductor/States/FatalErrorState.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/Conductor/States/StoringState.h
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/WorkerConductorMessages.h
Labels: 3 Pregel

#17175 [PREGEL] Separate worker creation from loading graph
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/AlgoRegistry.h
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/LoadingState.cpp
  arangod/Pregel/Conductor/States/LoadingState.h
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/Connection/Connection.h
  arangod/Pregel/Connection/DirectConnection.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/Worker/WorkerConfig.cpp
  arangod/Pregel/Worker/WorkerConfig.h
  arangod/Pregel/WorkerConductorMessages.h
Labels: 3 Pregel

#17176 [PREGEL] Pregel use inspector for statistics
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/DoneState.cpp
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Statistics.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/WorkerConductorMessages.h
Labels: 3 Pregel

#17210 [PREGEL] Aggregate response results
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/DoneState.cpp
  arangod/Pregel/Conductor/States/FatalErrorState.cpp
  arangod/Pregel/Conductor/States/LoadingState.cpp
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/WorkerConductorMessages.h
Labels: 3 Pregel

#17227 [PREGEL] Delete unused master context methods
  arangod/Pregel/Algos/ShortestPath.cpp
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/ComputingState.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/MasterContext.h
  arangod/Pregel/Statistics.h
  arangod/Pregel/VertexComputation.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/Worker/WorkerContext.h
  arangod/Pregel/WorkerConductorMessages.h
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
Labels: 3 Pregel
