Repository arangodb/arangodb, pull requests merged in 2022-06, with the labels that each got.

#16351 fetch schema only once per batch operation
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/Transaction/Methods.cpp
  arangod/Utils/OperationOptions.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
Labels: 9 Ready to Merge

#16356 fixed BTS-875 (#16349)
  CHANGELOG
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBMetadata.h
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
Labels: 3 Cluster, 9 Ready to Merge

#16367 [CINFRA-412] Disable some supervision jobs for replication 2 DBs
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Helpers.cpp
  arangod/Agency/Helpers.h
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/Supervision.cpp
  arangod/CMakeLists.txt
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/CleanOutServerTest.json
  tests/Agency/SupervisionTest.cpp
Labels: cinfra

#16366 Fix unstable test
  tests/js/client/shell/shell-collection-counts-cluster.js
Labels: 3 Cluster, 9 Ready to Merge, 3 - Testing

#16374 [CNFRA-414] Add CoreParameterType to Replicated States
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Replication2/ReplicatedState/AgencySpecification.cpp
  arangod/Replication2/ReplicatedState/AgencySpecification.h
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/UpdateReplicatedState.cpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.h
  lib/Inspection/VPackLoadInspector.h
  lib/Inspection/VPackSaveInspector.h
  lib/Inspection/detail/traits.h
  tests/CMakeLists.txt
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
  tests/Replication2/ReplicatedState/LeaderRecoveryTest.cpp
  tests/Replication2/ReplicatedState/PrototypeConcurrencyTest.cpp
  tests/Replication2/ReplicatedState/PrototypeStateMachineTest.cpp
  tests/Replication2/ReplicatedState/ReplicatedStateTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/MyStateMachine.h
Labels: cinfra

#16376 [CINFRA-25] Sorted write batches for RocksDB
  arangod/RocksDBEngine/RocksDBPersistedLog.cpp
Labels: cinfra

#16382 [CINFRA-415] Core Parameter Type
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  lib/Inspection/VPackLoadInspector.h
  tests/Replication2/ReplicatedState/FollowerWaitForTest.cpp
Labels: cinfra

#16333 [3.9] Restrict hybrid disjoint sg directions for Path Queries
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/KShortestPathsNode.cpp
  arangod/Aql/KShortestPathsNode.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/ShortestPathNode.h
  arangod/Cluster/ClusterMethods.cpp
  js/common/bootstrap/errors.js
  lib/Basics/error-registry.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.h
Labels: 1 Bug, 3 Graph

#16384 Bug fix 3.9/remove deletion after bts 750
  js/server/modules/@arangodb/testutils/collection-modification-aql-generic-tests.js
Labels: 9 Ready to Merge

#16400 Fix compile warnings/errors with clang14 and gcc11
  arangod/IResearch/AqlHelper.cpp
  arangod/Replication2/Methods.cpp
  lib/SimpleHttpClient/SslClientConnection.cpp
Labels: 9 Ready to Merge

#16401 [PREGEL] Replace Vertex Key store by std::string
  arangod/Pregel/Graph.h
  arangod/Pregel/GraphStore.cpp
Labels: 3 Pregel

#16405 [PREGEL] Remove custom edge key store
  arangod/Pregel/Graph.h
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/GraphStore.h
Labels: 3 Pregel

#16393 [CINFRA-410] lookup shard info in replicated log
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Replication2/Methods.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  tests/js/server/shell/shell-responsibleservers-cluster.js
Labels: cinfra

#16410 [CINFRA-383] Forward Config to Log
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/Replication2/ReplicatedState/SupervisionAction.h
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/ReplicatedState/SupervisionTest.cpp
  tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
Labels: cinfra

#16411 [CINFRA-390] Added number of servers parameter
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.h
  tests/js/server/replication2/replication2-replicated-log-create-api-cluster.js
Labels: cinfra

#16385 pick state of https://github.com/arangodb/arangodb/pull/16052
  .github/CODEOWNERS
  tests/test-definitions.txt
Labels: 3 - Testing

#16423 Fix potential resource leak when reusing PinnableSlice instances
  3rdParty/rocksdb/6.27/db/db_impl/db_impl.cc
  CHANGELOG
Labels: 3 RocksDB

#16272 Optionally allow range deletions for truncates.
  CHANGELOG
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  tests/js/server/shell/shell-collection-rangedelete.js
Labels: 3 Recovery

#16424 Fix potential resource leak when reusing PinnableSlice instances
  3rdParty/rocksdb/6.8/db/db_impl/db_impl.cc
  CHANGELOG
Labels: 3 RocksDB

#16427 these are only eligible in single server
  tests/test-definitions.txt
Labels: 4 Windows, 3 - Testing

#16432 add api tests
  tests/test-definitions.txt
Labels: 3 API, 3 - Testing

#16396 Bug-fix/import-headers-merge-attrs
  CHANGELOG
  client-tools/Import/ImportHelper.cpp
  js/client/modules/@arangodb/testsuites/importing.js
  tests/js/common/test-data/import/import-merge-attrs-headers.csv
  tests/js/common/test-data/import/import-merge-attrs.csv
  tests/js/server/import/import.js
Labels: 1 Bug, 3 ImportExport

#16402 Issue #15592: Allow MERGE_RECURSIVE() to be called with single argument
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  tests/js/server/aql/aql-functions.js
  tests/js/server/aql/aql-stresstest-nightly.js
Labels: 1 Feature, 3 AQL

#16435 [CINFRA-422] Replicated Log Metrics
  Documentation/Metrics/arangodb_replication2_replicated_log_inserts_rtt.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_number_accepted_entries.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_number_committed_entries.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_number_compacted_entries.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_number_meta_entries.yaml
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLogMetrics.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLogMetrics.h
  arangod/Replication2/ReplicatedLog/ReplicatedLogMetricsDeclarations.h
  tests/CMakeLists.txt
  tests/Replication2/Mocks/FakeReplicatedLog.h
  tests/Replication2/ReplicatedLog/ChangeStreamTests.cpp
  tests/Replication2/ReplicatedLog/LogStatusTest.cpp
  tests/Replication2/ReplicatedLog/MetricsTest.cpp
  tests/Replication2/ReplicatedLog/SimpleInsertTests.cpp
Labels: cinfra

#16309 Feature/enterprise graphs
  CHANGELOG
  arangod/Aql/Functions.cpp
  arangod/Graph/Graph.cpp
  arangod/Graph/Graph.h
  arangod/Graph/Providers/ClusterProvider.cpp
  arangod/Graph/Providers/ClusterProvider.h
  arangod/Graph/Providers/ProviderTracer.cpp
  arangod/Graph/Providers/ProviderTracer.h
  arangod/Graph/Providers/SingleServerProvider.cpp
  arangod/Graph/Providers/SingleServerProvider.h
  arangod/Sharding/ShardingFeature.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingStrategyDefault.cpp
  arangod/Sharding/ShardingStrategyDefault.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  js/client/modules/@arangodb/general-graph.js
  js/client/modules/@arangodb/graph-classes.js
  js/client/modules/@arangodb/testutils/collect-crud-api-generic-tests.js
  js/common/modules/@arangodb/general-graph-common.js
  js/server/modules/@arangodb/general-graph.js
  js/server/modules/@arangodb/graph-classes.js
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/testutils/collection-modification-aql-generic-tests.js
  tests/Mocks/MockGraphProvider.cpp
  tests/Mocks/MockGraphProvider.h
  tests/js/common/shell/shell-figures-rocksdb.js
Labels: 9 Review Required

#16442 Update mac_tool.py (#3.8)
  3rdParty/V8/gyp/buildtime_helpers/mac_tool.py
  3rdParty/iresearch/core/store/data_input.hpp
  3rdParty/iresearch/core/utils/type_info.hpp
  3rdParty/iresearch/external/absl/absl/functional/function_ref.h
  arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
  tests/Auth/UserManagerClusterTest.cpp
Labels: 3 Build, 4 MacOSX

#16445 Fix some warnings 3.9
  3rdParty/iresearch/core/store/data_input.hpp
  3rdParty/iresearch/external/absl/absl/functional/function_ref.h
  arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
Labels: 3 Build, 4 MacOSX

#16457 [CINFRA] Agency Supervision Refactor
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Agency/AddFollower.cpp
  arangod/Agency/AgencyFeature.cpp
  arangod/Agency/AgencyFeature.h
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/AgentCallback.cpp
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/MoveShard.cpp
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Network/Methods.cpp
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/FailedFollowerTest.cpp
  tests/Agency/FailedLeaderTest.cpp
  tests/Agency/MoveShardTest.cpp
Labels: cinfra

#16452 OskarTestSuitesBlockList <-> test-definitions.txt
  UnitTests/OskarTestSuitesBlockList
  tests/test-definitions.txt
Labels: 3 - Testing

#16453 Feature 3.9/remove blacklist contents
  UnitTests/OskarTestSuitesBlockList
  tests/test-definitions.txt
Labels: 3 - Testing

#16454 Feature 3.8/remove blacklist contents
  UnitTests/OskarTestSuitesBlockList
  tests/test-definitions.txt
Labels: 3 - Testing

#16466 [CINFRA] Bugfix Log Supervision Loop
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  tests/Replication2/Helper/ModelChecker/Actors.cpp
  tests/Replication2/Helper/ModelChecker/Actors.h
  tests/Replication2/Helper/ModelChecker/AgencyTransition.cpp
  tests/Replication2/Helper/ModelChecker/AgencyTransitions.h
  tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
Labels: cinfra

#16464 [CINFRA-463] Added last matched index.
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.h
  arangod/Replication2/ReplicatedLog/types.h
  tests/Replication2/ReplicatedLog/AppendEntriesBatchTest.cpp
  tests/Replication2/Serialization/LogStatusTest.cpp
Labels: cinfra

#16431 Testcase success temporary data cleanup refactoring
  js/client/modules/@arangodb/testsuites/agency-restart.js
  js/client/modules/@arangodb/testsuites/arangobench.js
  js/client/modules/@arangodb/testsuites/arangosh.js
  js/client/modules/@arangodb/testsuites/authentication.js
  js/client/modules/@arangodb/testsuites/config.js
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testsuites/endpoints.js
  js/client/modules/@arangodb/testsuites/fail.js
  js/client/modules/@arangodb/testsuites/foxxmanager.js
  js/client/modules/@arangodb/testsuites/fuerte.js
  js/client/modules/@arangodb/testsuites/gtest.js
  js/client/modules/@arangodb/testsuites/importing.js
  js/client/modules/@arangodb/testsuites/permissions_client.js
  js/client/modules/@arangodb/testsuites/queryCacheAuthorization.js
  js/client/modules/@arangodb/testsuites/readOnly.js
  js/client/modules/@arangodb/testsuites/recovery.js
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  js/client/modules/@arangodb/testsuites/server_permissions.js
  js/client/modules/@arangodb/testsuites/version.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/process-utils.js
  js/client/modules/@arangodb/testutils/testing.js
  js/client/modules/@arangodb/testutils/testrunner.js
  js/client/modules/@arangodb/testutils/tmpDirManager.js
Labels: 3 - Testing

#16459 [CINFRA-421] Commit and abort transactions
  arangod/Aql/StandaloneCalculation.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/ClusterEngine/ClusterTransactionState.h
  arangod/Replication2/StateMachines/Document/DocumentCore.cpp
  arangod/Replication2/StateMachines/Document/DocumentCore.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentLogEntry.cpp
  arangod/Replication2/StateMachines/Document/DocumentLogEntry.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/RocksDBEngine/SimpleRocksDBTransactionState.cpp
  arangod/RocksDBEngine/SimpleRocksDBTransactionState.h
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Methods.cpp
  arangod/VocBase/LogicalCollection.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/js/client/shell/transaction/shell-transaction.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: 9 Ready to Merge, cinfra

#16429 Bug-fix/import-headers-merge-attrs
  CHANGELOG
  arangosh/Import/ImportHelper.cpp
  js/client/modules/@arangodb/testsuites/importing.js
  tests/js/common/test-data/import/import-merge-attrs-headers.csv
  tests/js/common/test-data/import/import-merge-attrs.csv
  tests/js/server/import/import.js
Labels: 1 Bug, 9 Ready to Merge, 3 ImportExport
