Repository arangodb/arangodb, pull requests merged in 2022-04, with the labels that each got.

#16006 Docs: Add unit to lockTimeout (seconds)
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
Labels: 3 Documentation

#16010 Documentation/note-about-key-generator-sequence-gaps
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
Labels: 3 Documentation

#15932 [3.7] Fix BTS-621
  CHANGELOG
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  tests/IResearch/IResearchLink-test.cpp
Labels: 1 Bug, 3 Upgrade

#16005 Docs: Add unit to lockTimeout (seconds)
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
Labels: 3 Documentation

#16009 Documentation 3.8/note about key generator sequence gaps
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
Labels: 3 Documentation

#16041 clang-format: Pass through arguments from PowerShell wrapper to .sh script
  scripts/clang-format.ps1
Labels: 1 Feature, 9 Ready to Merge

#16004 Docs: Add unit to lockTimeout (seconds)
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction.md
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
Labels: 3 Documentation

#16008 Documentation/note-about-key-generator-sequence-gaps
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
Labels: 3 Documentation

#16049 BUG-Fix BTS-787
  CHANGELOG
Labels: 1 Bug

#16045 [CINFRA-333] Allow removal of replicated state participants
  arangod/Cluster/DBServerAgencySync.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/Maintenance.h
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/Replication2/ReplicatedState/SupervisionAction.h
  arangod/Replication2/ReplicatedState/UpdateReplicatedState.cpp
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
Labels: cinfra

#16040 Docs: Deprecate --default-language and set version for --icu-language
  lib/ApplicationFeatures/LanguageFeature.cpp
Labels: 3 Documentation

#15961 Docs: DocuBlock for GET /_api/query/rules
  Documentation/DocuBlocks/Rest/AQL/GetApiQueryRules.md
Labels: 3 Documentation

#16024 [CINFRA-330] Speedup log creation
  arangod/Agency/Supervision.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/ParticipantsHealth.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.h
  arangod/Replication2/ReplicatedState/Supervision.cpp
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
  tests/js/common/shell/shell-replicated-logs-cluster.js
  tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
Labels: cinfra

#16069 [CINFRA-343] EvictLeaderAction considered harmful
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.h
Labels: cinfra

#16068 [CINFRA-342] Bug fix/update leader property when replacing leader
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  arangod/Replication2/AgencyMethods.cpp
  arangod/Replication2/AgencyMethods.h
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/RestHandler/RestReplicatedStateHandler.cpp
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  js/server/modules/@arangodb/testutils/replicated-logs-predicates.js
  js/server/modules/@arangodb/testutils/replicated-state-helper.js
  js/server/modules/@arangodb/testutils/replicated-state-predicates.js
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-maintenance-replicated-state-cluster.js
  tests/js/server/replication2/replication2-regression.js
  tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
  tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
  tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
  tests/js/server/resilience/failover/resilience-failure-oracle.js
Labels: cinfra

#16074 [CINFRA-344] Remove Multiple Participants
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  js/client/modules/@arangodb/testsuites/replication2.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra

#16077 [CINFRA-345] proper replicated log creation
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.cpp
  arangod/RestHandler/RestLogHandler.cpp
  arangod/V8Server/v8-replicated-logs.cpp
  js/client/modules/@arangodb/arango-database.js
  tests/js/common/shell/shell-replicated-logs-cluster.js
  tests/js/server/replication2/replication2-replicated-log-create-api-cluster.js
Labels: 9 Review Required, 9 Ready to Merge, cinfra

#16048 Documentation/http docublock rendering
  Documentation/DocuBlocks/Rest/Administration/post_admin_echo.md
  Documentation/DocuBlocks/Rest/Bulk/batch_processing.md
  Documentation/Scripts/codeBlockReader.py
Labels: 3 Documentation

#16064 Documentation/http docublock rendering
  Documentation/DocuBlocks/Rest/Administration/post_admin_echo.md
  Documentation/DocuBlocks/Rest/Bulk/batch_processing.md
  Documentation/Scripts/codeBlockReader.py
Labels: 3 Documentation

#16078 [CINFRA-348] Use `getRebootId` instead of directly accessing _health
  arangod/Replication2/ReplicatedLog/ParticipantsHealth.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
Labels: cinfra

#16065 Documentation/http docublock rendering
  Documentation/DocuBlocks/Rest/Administration/post_admin_echo.md
  Documentation/DocuBlocks/Rest/Bulk/batch_processing.md
  Documentation/Scripts/codeBlockReader.py
Labels: 3 Documentation

#16075 [CINFRA-202] Report all planned participants in election outcome
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/Supervision.h
Labels: 9 Review Required, cinfra

#16086 [CINFRA-353] Fix for Replicated State Supervision
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/Replication2/ReplicatedState/SupervisionAction.h
  tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
Labels: cinfra

#15956 [CINFRA-321] Restart Snapshot Transfer
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  arangod/Replication2/ReplicatedState/ReplicatedStateFeature.cpp
  arangod/Replication2/ReplicatedState/StateCommon.cpp
  arangod/Replication2/ReplicatedState/StateCommon.h
  arangod/Replication2/ReplicatedState/UpdateReplicatedState.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  arangod/RestHandler/RestReplicatedStateHandler.cpp
  js/client/modules/@arangodb/testutils/restart-helper.js
  js/server/modules/@arangodb/testutils/replicated-state-helper.js
  tests/CMakeLists.txt
  tests/Replication2/ReplicatedState/MaintenanceTest.cpp
  tests/js/client/restart/test-restart-replication2-prototype-state-cluster-grey.js
  tests/js/server/replication2/replication2-maintenance-replicated-state-cluster.js
Labels: 9 Review Required, cinfra

#16063 Documentation/http docublock rendering
  Documentation/DocuBlocks/Rest/Administration/post_admin_echo.md
  Documentation/DocuBlocks/Rest/Bulk/batch_processing.md
  Documentation/Scripts/codeBlockReader.py
Labels: 3 Documentation

#16088 [CINFRA-340] Remove dead code
  arangod/Replication2/ReplicatedState/UpdateReplicatedState.cpp
Labels: 9 Ready to Merge, cinfra

#16072 [CINFRA-150] Read replicated log on followers
  arangod/Replication2/Methods.cpp
  arangod/Replication2/ReplicatedLog/ILogInterfaces.h
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.h
  arangod/Replication2/ReplicatedLog/LogUnconfiguredParticipant.cpp
  arangod/Replication2/ReplicatedLog/LogUnconfiguredParticipant.h
  js/common/bootstrap/errors.js
  lib/Basics/error-registry.h
  lib/Basics/errors.dat
  lib/Basics/voc-errors.h
  tests/Replication2/Mocks/AsyncFollower.cpp
  tests/Replication2/Mocks/AsyncFollower.h
  tests/Replication2/Mocks/FakeFollower.cpp
  tests/Replication2/Mocks/FakeFollower.h
  tests/Replication2/Mocks/FakeReplicatedLog.h
  tests/js/server/replication2/replication2-replicated-log-http-api-cluster.js
Labels: cinfra

#16044 Docs: Add extra.stats reply description to Cursor DocuBlock
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
Labels: 3 Documentation

#15974 Follower resync on restart BTS-829
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/SynchronizeShard.cpp
Labels: 1 Bug

#16019 Deadlocked SynchronizeShards BTS-662
  CHANGELOG
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/SynchronizeShard.cpp
  tests/Maintenance/MaintenanceFeatureTest.cpp
Labels: 1 Bug

#16020 Fix potential dead lock in agent
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
Labels: 1 Bug

#15999 Follower resync on restart BTS-829
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceStrings.h
  arangod/Cluster/SynchronizeShard.cpp
Labels: 1 Bug

#16050 bug-fix-3.9/bts787
  CHANGELOG
  arangod/VocBase/LogicalCollection.h
Labels: 1 Bug, 3 Graph

#16059 Fix potential dead lock in agent
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
Labels: 1 Bug

#16101 [CINFRA-213] Move some logic in a more fitting place
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  tests/Replication2/ReplicatedLog/EstablishLeadershipTest.cpp
  tests/Replication2/ReplicatedLog/UpdateParticipantsFlags.cpp
Labels: cinfra

#15978 [CINFRA-318] Prototype Consolidation
  arangod/CMakeLists.txt
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  arangod/Replication2/ReplicatedState/StateInterfaces.h
  arangod/Replication2/StateMachines/Prototype/PrototypeCore.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeCore.h
  arangod/Replication2/StateMachines/Prototype/PrototypeFollowerState.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeFollowerState.h
  arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.h
  arangod/Replication2/StateMachines/Prototype/PrototypeLogEntry.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeLogEntry.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachineFeature.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachineFeature.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.h
  arangod/RestHandler/RestPrototypeStateHandler.cpp
  arangod/V8Server/v8-prototype-states.cpp
  lib/Basics/Result.cpp
  lib/Basics/Result.h
  tests/CMakeLists.txt
  tests/Replication2/ReplicatedState/PrototypeConcurrencyTest.cpp
  tests/Replication2/ReplicatedState/PrototypeStateMachineTest.cpp
  tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: 9 Review Required, 9 Ready to Merge, cinfra

#16112 fix a test that had random execution times
  tests/js/common/aql/aql-view-arangosearch-feature.js
Labels: 3 - Testing, 3 ArangoSearch

#16109 [CINFRA-337] Let RocksDB Log Persistor resolve promises with its executor
  arangod/RocksDBEngine/RocksDBPersistedLog.cpp
Labels: cinfra

#16117 [CINFRA-180] Some noexcept additions, renamed a class
  arangod/Replication2/ReplicatedState/FollowerStateManager.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/LeaderStateManager.h
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/UnconfiguredStateManager.h
  arangod/Replication2/ReplicatedState/UnconfiguredStateManager.tpp
Labels: cinfra

#16120 [CINFRA-315] Prototype Concurrency Test Fix
  tests/Replication2/ReplicatedState/PrototypeConcurrencyTest.cpp
Labels: cinfra

#16067 Deadlocked SynchronizeShards BTS-662
  CHANGELOG
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/SynchronizeShard.cpp
  tests/Maintenance/MaintenanceFeatureTest.cpp
Labels: 3 Cluster

#16066 Deadlocked SynchronizeShards BTS-662
  CHANGELOG
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/SynchronizeShard.cpp
  tests/Maintenance/MaintenanceFeatureTest.cpp
Labels: 3 Cluster

#16119 Make transaction lock stripes configurable
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.h
Labels: 3 RocksDB, 3 Transaction

#16126 Improve validation of COLLECT KEEP variables
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-optimizer-collect-methods.js
  tests/js/server/aql/aql-optimizer-keep.js
Labels: 3 AQL

#16108 [CINFRA-359] Refactor Replicated State Supervision
  arangod/Agency/Job.cpp
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/FailureOracleFeature.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Pregel/Conductor.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedState/AgencySpecification.cpp
  arangod/Replication2/ReplicatedState/AgencySpecification.h
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  arangod/Replication2/ReplicatedState/StateCommon.cpp
  arangod/Replication2/ReplicatedState/StateCommon.h
  arangod/Replication2/ReplicatedState/StateStatus.cpp
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/Replication2/ReplicatedState/Supervision.h
  arangod/Replication2/ReplicatedState/SupervisionAction.cpp
  arangod/Replication2/ReplicatedState/SupervisionAction.h
  arangod/Replication2/Supervision/ModifyContext.h
  arangod/RestHandler/RestAdminClusterHandler.cpp
  js/server/modules/@arangodb/testutils/replicated-logs-helper.js
  js/server/modules/@arangodb/testutils/replicated-logs-predicates.js
  js/server/modules/@arangodb/testutils/replicated-state-helper.js
  js/server/modules/@arangodb/testutils/replicated-state-predicates.js
  lib/Basics/TimeString.h
  lib/Inspection/Transformers.h
  tests/CMakeLists.txt
  tests/Mocks/Servers.cpp
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/Helper/AgencyStateBuilder.h
  tests/Replication2/ReplicatedState/SupervisionTest.cpp
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-state-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-state-target-cluster.js
Labels: cinfra

#16125 Improve validation of COLLECT KEEP variables
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-optimizer-collect-methods.js
  tests/js/server/aql/aql-optimizer-keep.js
Labels: 3 AQL, 9 Ready to Merge

#16073 Feature/fe 45 view UI improve settings page
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/src/components/arango/tootip.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/ViewSettingsReactView.jsx
  js/apps/system/_admin/aardvark/APP/react/yarn.lock
Labels: 3 UI, 3 ArangoSearch

#16128 Improve validation of COLLECT KEEP variables
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-optimizer-collect-methods.js
  tests/js/server/aql/aql-optimizer-keep.js
Labels: 3 AQL, 9 Ready to Merge

#16130 Increase lock timeout on followers (#16121)
  CHANGELOG
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
Labels: 3 Cluster, 9 Ready to Merge

#16132 Increase number of transaction lock stripes
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 9 Ready to Merge, 3 Transaction

#16129 Increase lock timeout on followers (#16121)
  CHANGELOG
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
Labels: 3 Cluster, 9 Ready to Merge

#16055 refactor internals of key generators
  CHANGELOG
  arangod/Aql/BlocksWithClients.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/v8-cluster.cpp
  arangod/Graph/Traverser.cpp
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingInfo.h
  arangod/Sharding/ShardingStrategy.h
  arangod/Sharding/ShardingStrategyDefault.h
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/Transaction/Methods.cpp
  arangod/V8Server/v8-util.cpp
  arangod/V8Server/v8-vocbase.cpp
  arangod/VocBase/KeyGenerator.cpp
  arangod/VocBase/KeyGenerator.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Collections.cpp
  js/common/modules/@arangodb/aql/explainer.js
  js/server/modules/@arangodb/aql-helper.js
  js/server/modules/@arangodb/arango-database.js
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/errors.dat
  lib/V8/v8-globals.cpp
  tests/VocBase/KeyGeneratorTest.cpp
  tests/js/client/shell/shell-keygen.js
  tests/js/common/aql/aql-view-arangosearch-feature.js
  tests/js/common/shell/shell-keygen-noncluster.js
  tests/js/common/shell/shell-keygen.js
  tests/js/server/aql/aql-modify-subqueries.js
  tests/js/server/dump/dump-setup-common.inc
Labels: 3 - Testing, 3 ArangoSearch

#16062 View UI: "Info" page
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/react/src/views/views/helpers.ts
Labels: 3 UI, 3 ArangoSearch

#16087 Feature/FE-46 view UI usability improvements
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/views/ViewInfoReactView.jsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/forms/ConsolidationPolicyForm.tsx
Labels: 3 UI, 3 ArangoSearch

#16141 fix clang-format Github action
  .github/workflows/clang-format.yml
  arangod/Aql/SortExecutor.cpp
Labels: 9 Ready to Merge

#16140 make generated files pass clang-format check
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.h
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  arangod/Aql/tokens.cpp
  arangod/Aql/tokens.ll
  arangod/CMakeLists.txt
  utils/bison-c.sh
Labels: 9 Ready to Merge

#16143 [CINFRA-363] More Unittests Replicated State Supervision
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/Replication2/ReplicatedState/SupervisionAction.h
  tests/Replication2/Helper/AgencyStateBuilder.h
  tests/Replication2/ReplicatedState/SupervisionTest.cpp
Labels: cinfra

#16147 Ensure snappy does not use BMI2 instructions.
  3rdParty/README_maintainers.md
  3rdParty/snappy/snappy-1.1.9/CMakeLists.txt
  CHANGELOG
Labels: 3 Build, 4 Windows

#16160 fix users checking
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: 3 - Testing

#16174 [CINFRA-364] Supervision Model Checker
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/ParticipantsHealth.h
  arangod/Replication2/ReplicatedState/AgencySpecification.h
  arangod/Replication2/ReplicatedState/StateCommon.cpp
  arangod/Replication2/ReplicatedState/StateCommon.h
  arangod/Replication2/ReplicatedState/Supervision.cpp
  tests/CMakeLists.txt
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/Helper/ModelChecker/Actors.cpp
  tests/Replication2/Helper/ModelChecker/Actors.h
  tests/Replication2/Helper/ModelChecker/AgencyState.h
  tests/Replication2/Helper/ModelChecker/AgencyTransition.cpp
  tests/Replication2/Helper/ModelChecker/AgencyTransitions.h
  tests/Replication2/Helper/ModelChecker/HashValues.h
  tests/Replication2/Helper/ModelChecker/Predicates.h
  tests/Replication2/Mocks/MaintenanceMock.cpp
  tests/Replication2/Mocks/MaintenanceMock.h
  tests/Replication2/ModelChecker/ActorModel.h
  tests/Replication2/ModelChecker/ModelChecker.cpp
  tests/Replication2/ModelChecker/ModelChecker.h
  tests/Replication2/ModelChecker/Predicates.h
  tests/Replication2/ModelChecker/Tests/ModelCheckerTest.cpp
  tests/Replication2/ReplicatedState/SupervisionSimulationTest2.cpp
Labels: cinfra

#16184 [CINFRA] Bug Fix for mac compilation
  tests/Replication2/ModelChecker/ModelChecker.h
  tests/Replication2/ModelChecker/Predicates.h
Labels: cinfra

#16169 Adjust importing test structure to be more similar to dumping
  js/client/modules/@arangodb/testsuites/importing.js
  js/client/modules/@arangodb/testutils/process-utils.js
Labels: 3 - Testing

#16171 fix assertion handling to produce actual error states
  js/client/modules/@arangodb/testsuites/importing.js
Labels: 3 ImportExport, 3 - Testing

#16167 fix reference of server JWT
  js/client/modules/@arangodb/testsuites/ldap.js
  js/client/modules/@arangodb/testutils/ldap-generic-failover.js
  js/client/modules/@arangodb/testutils/testrunner.js
  js/common/modules/jsunity/jsunity.js
Labels: 3 - Testing

#16170 fix assertion handling to produce actual error states
  js/client/modules/@arangodb/testsuites/importing.js
Labels: 3 ImportExport, 3 - Testing

#16179 Use 201 status code for put license
  Documentation/DocuBlocks/Rest/Administration/put_admin_license.md
Labels: 3 Documentation, 3 License

#15953 Bug fix/optimize scorers sort
  CHANGELOG
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/IResearchViewOptimizerRules.h
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRulesFeature.cpp
  js/common/modules/@arangodb/aql/explainer.js
  lib/Basics/ResourceUsage.h
  tests/IResearch/IResearchViewCountApproximateTest.cpp
  tests/IResearch/IResearchViewNodeTest.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.inc
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
  tests/js/server/aql/aql-arangosearch-constrained-sort-optimization.inc
  tests/js/server/aql/aql-arangosearch-constrained-sort-optimization.js
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
  tests/js/server/shell/shell-transactions-view-noncluster.js
Labels: 9 WIP

#16166 Fix server startup with missing `smartGraphAttribute`
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestServer/UpgradeFeature.cpp
  arangod/Transaction/Helpers.cpp
  arangod/Transaction/Methods.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Upgrade.cpp
Labels: 3 Graph

#16199 Bug fix/3.9 maintanence lock shard
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
Labels: 1 Bug, 3 Graph

#16186 improve log output for WAL recovery
  CHANGELOG
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
Labels: 9 Ready to Merge

#16190 add testsuite missing in backport
  UnitTests/OskarTestSuitesBlockList
  js/client/modules/@arangodb/testsuites/replication.js
  tests/js/common/replication_api/shell-api-replication-global.js
  tests/js/common/replication_api/shell-api-replication.js
Labels: 3 - Testing

#16162 Disable index estimates for TTL indexes
  CHANGELOG
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/RocksDBEngine/RocksDBTtlIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  tests/js/common/shell/shell-index-estimates.js
  tests/js/common/shell/shell-ttl.js
  tests/js/server/recovery/indexes-ttl.js
Labels: 9 Ready to Merge, 3 Index

#16164 Disable index estimates for TTL indexes
  CHANGELOG
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/RocksDBEngine/RocksDBTtlIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  tests/js/common/shell/shell-index-estimates.js
  tests/js/common/shell/shell-ttl.js
  tests/js/server/recovery/indexes-ttl.js
Labels: 9 Ready to Merge, 3 Index

#16196 fix agency startup when gossip peers return HTTP 503
  CHANGELOG
  arangod/Agency/Inception.cpp
Labels: 3 Cluster, 9 Ready to Merge

#16189 add testsuite missing in backport
  UnitTests/OskarTestSuitesBlockList
  js/client/modules/@arangodb/testsuites/replication.js
  tests/js/common/replication_api/shell-api-replication-global.js
  tests/js/common/replication_api/shell-api-replication.js
Labels: 3 - Testing

#16191 add testsuite missing in backport
  UnitTests/OskarTestSuitesBlockList
  js/client/modules/@arangodb/testsuites/replication.js
  tests/js/common/replication_api/shell-api-replication-global.js
  tests/js/common/replication_api/shell-api-replication.js
Labels: 3 - Testing

#16155 Added option `--enable-revision-trees` to arangorestore
  CHANGELOG
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Restore/RestoreFeature.h
  tests/js/client/shell/shell-restore-integration.js
Labels: 3 ImportExport
