Repository arangodb/arangodb, pull requests merged in 2022-11, with the labels that each got.

#17480 [CINFRA-593] Compaction Test Fix
  tests/js/common/shell/shell-replicated-logs-cluster.js
Labels: cinfra, cla-signed

#17469 deprecate startup option `--agency.pool-size`
  CHANGELOG
  arangod/Agency/AgencyFeature.cpp
  arangod/Agency/AgencyFeature.h
  arangod/Agency/AgentConfiguration.cpp
  arangod/Agency/AgentConfiguration.h
  js/client/modules/@arangodb/testutils/instance.js
Labels: cla-signed

#17379 log document counts in replication
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/SynchronizeShard.h
Labels: cla-signed

#17399 BTS-1082: Updating properties of a satellite collection breaks replicationFactor
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
Labels: cla-signed

#17406 Bug fix 3.10/bts 1070
  CHANGELOG
  arangod/Aql/AstNode.cpp
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/client/shell/api/cursor.js
  tests/js/client/shell/api/explain.js
  tests/js/server/aql/aql-window-malarkey.js
Labels: cla-signed

#17420 Solve excessive memory consumption in multi-iterators - BTS-1088
  CHANGELOG
  arangod/Indexes/IndexIterator.cpp
  arangod/Indexes/IndexIterator.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
Labels: cla-signed

#17086 ES-1085: Keep node color consistent after expansion when coloring by attribute
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 1 Bug, 3 UI

#17031 APM-517: Show values upon hover on blue attribute labels
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 3 UI, cla-signed

#17407 Added backport for BTS-1070
  CHANGELOG
  arangod/Aql/AstNode.cpp
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/client/shell/api/cusror.js
  tests/js/client/shell/api/explain.js
  tests/js/server/aql/aql-window-malarkey.js
Labels: cla-signed

#17419 Solve excessive memory consumption in multi-iterators - BTS-1088
  CHANGELOG
  arangod/Indexes/IndexIterator.cpp
  arangod/Indexes/IndexIterator.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
Labels: cla-signed

#16085 [FE-51] Change help texts in new collection modal
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
Labels: 3 UI, cla-signed

#17089 ES-1195: Add sorting by history to query view
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/queryView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 3 UI, cla-signed

#17478 Repair "load indexes into memory" functions for web UI and SmartGraph edge collections
  CHANGELOG
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_load_indexes_in_memory.md
  arangod/Cluster/ClusterMethods.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/VocBase/Methods/Collections.cpp
  lib/Basics/LocalTaskQueue.cpp
  tests/js/common/shell/shell-collection-noncluster.js
Labels: cla-signed

#17438 BTS-999: Bug fix 3.10/bulk inserts
  tests/js/client/shell/shell-iterators-read-standalone.js
  tests/js/client/shell/shell-iterators-read-transaction.js
  tests/js/client/shell/shell-iterators-write-standalane.js
  tests/js/client/shell/shell-iterators-write-transaction.js
  tests/js/client/shell/shell-iterators.inc
  tests/js/common/shell/shell-pregel-components.js
  tests/js/common/shell/shell-pregel-multicollection-edgecol.js
Labels: cla-signed, 3.10

#17486 Use proper C++20 to store file and line information.
  tests/Replication2/ModelChecker/Predicates.h
Labels: cinfra, cla-signed

#17294 [BTS-483] Added restriction for query cache usage on transactions
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Context.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  arangod/V8Server/v8-vocbase.cpp
  arangod/VocBase/Methods/Transactions.cpp
  tests/js/client/shell/api/cursor-noncluster.js
  tests/js/server/aql/aql-query-cache-noncluster.js
Labels: cla-signed

#17495 Update OpenSSL to 1.1.1s
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#17494 Update OpenSSL to 1.1.1s (3.10)
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#17493 Update OpenSSL to 1.1.1s (3.9)
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#17492 Update OpenSSL to 1.1.1s (3.8)
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#17491 move StaticStrings into a library of its own
  lib/CMakeLists.txt
Labels: cla-signed

#17499 remove always-true subcondition
  arangod/RestHandler/RestDocumentStateHandler.cpp
Labels: cla-signed

#17501 remove unused variable from count method
  arangod/Cluster/ClusterMethods.cpp
Labels: cla-signed

#17490 de-inline v8 helper functions
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/Cluster/MaintenanceStrings.h
  arangod/ClusterEngine/ClusterEngine.h
  arangod/ClusterEngine/ClusterRestWalHandler.cpp
  arangod/ClusterEngine/ClusterV8Functions.cpp
  arangod/Replication/DatabaseTailingSyncer.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBRestWalHandler.cpp
  arangod/RocksDBEngine/RocksDBV8Functions.cpp
  arangod/StorageEngine/StorageEngine.h
  arangod/Transaction/Options.cpp
  lib/V8/v8-globals.cpp
  lib/V8/v8-globals.h
  tests/Maintenance/MaintenanceTest.cpp
Labels: cla-signed

#17502 [PREGEL] Delete tests for deleted function
  tests/Pregel/Messaging/CMakeLists.txt
  tests/Pregel/Messaging/MessageTest.cpp
Labels: 3 Pregel, cla-signed

#17488 obsolete startup option `--database.force-sync-properties`
  CHANGELOG
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterEngine.h
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndex.h
  arangod/IResearch/IResearchDataStore.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/StorageEngine/StorageEngine.cpp
  arangod/StorageEngine/StorageEngine.h
  arangod/VocBase/LogicalCollection.cpp
  etc/testing/arangod-common.conf
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
Labels: cla-signed

#16861 [FE-156] Correct graph view routing
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/g6GraphManagementView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/g6GraphManagementView.js
Labels: 3 UI

#17503 remove unused lambda capture
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
Labels: cla-signed

#17346 BTS-1080: [testing] add method to detect setup errors in recovery tests
  js/client/modules/@arangodb/testsuites/recovery.js
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  js/client/modules/@arangodb/testutils/process-utils.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/common/modules/@arangodb/test-helper-common.js
  tests/js/server/recovery/applier-restart.js
  tests/js/server/recovery/check-warnings-exitzero.js
  tests/js/server/recovery/collection-duplicate-names-exitzero.js
  tests/js/server/recovery/crash-handler-abort-noasan.js
  tests/js/server/recovery/crash-handler-assert-noasan.js
  tests/js/server/recovery/crash-handler-segfault-noasan.js
  tests/js/server/recovery/crash-handler-terminate-active-noasan.js
  tests/js/server/recovery/crash-handler-terminate-noasan.js
  tests/js/server/recovery/documents-exitzero.js
  tests/js/server/recovery/drop-index-shutdown-exitzero.js
  tests/js/server/recovery/empty-journal-nonwindows.js
  tests/js/server/recovery/foxx-directories.js
  tests/js/server/recovery/indexes-inbackground-exitone.js
  tests/js/server/recovery/many-documents-exitzero.js
  tests/js/server/recovery/view-arangosearch-link-populate-fail.js
  tests/js/server/recovery/view-arangosearch-link-populate-transaction-abort-no-flushthread.js
  tests/js/server/recovery/view-arangosearch-link-populate-transaction-abort.js
  tests/js/server/recovery/view-arangosearch-link-populate-truncate-replay.js
  tests/js/server/recovery/view-search-alias-populate-fail.js
  tests/js/server/recovery/view-search-alias-populate-transaction-abort-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction-abort.js
  tests/js/server/recovery/view-search-alias-populate-truncate-replay.js
Labels: cla-signed

#17511 [testing] 3.8: Bug fix/asan timeouts, disable coredumping #17276
  js/client/modules/@arangodb/testsuites/recovery.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
  tests/js/server/recovery/check-warnings.js
Labels: 3 - Testing, cla-signed

#17509 [testing] 3.9: Bug fix/asan timeouts, disable coredumping #17276
  js/client/modules/@arangodb/testsuites/recovery.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
  tests/js/server/recovery/check-warnings.js
Labels: 3 - Testing, cla-signed

#17276 [testing] Bug fix/asan timeouts, disable coredumping
  js/client/modules/@arangodb/testsuites/recovery.js
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
  tests/js/server/recovery/check-warnings-exitzero.js
Labels: 3 - Testing, cla-signed

#17508 [testing] 3.10: Bug fix/asan timeouts, disable coredumping
  js/client/modules/@arangodb/testsuites/recovery.js
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
  tests/js/server/recovery/check-warnings.js
Labels: 3 - Testing, cla-signed

#17497 move from V8Context to StandaloneContext
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
Labels: cla-signed

#17515 Enable "collect-in-cluster" optimizer rule for SmartGraph edge collections
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-collect-count.js
  tests/js/server/aql/aql-optimizer-rule-collect-in-cluster.js
Labels: cla-signed

#17317 [PREGEL] Feature/ColorPropagation
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/Algorithm.h
  arangod/Pregel/Algos/CMakeLists.txt
  arangod/Pregel/Algos/ColorPropagation.cpp
  arangod/Pregel/Algos/ColorPropagation.h
  arangod/Pregel/CommonFormats.h
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker.cpp
Labels: 3 Pregel, cla-signed

#16723 Web UI: Improve AQL highlighter
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/public/assets/src/mode-aql.js
Labels: 1 Feature, 3 UI, cla-signed

#17518 [CINFRA] Ping Replicated Log
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedLog/ILogInterfaces.h
  arangod/Replication2/ReplicatedLog/LogEntries.cpp
  arangod/Replication2/ReplicatedLog/LogEntries.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/RestHandler/RestLogHandler.cpp
  arangod/RestHandler/RestLogHandler.h
  arangod/V8Server/v8-replicated-logs.cpp
  js/client/modules/@arangodb/replicated-logs.js
  tests/Replication2/Mocks/AsyncLeader.h
  tests/Replication2/Mocks/FakeLeader.h
  tests/js/common/shell/shell-replicated-logs-cluster.js
  tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
Labels: cinfra, cla-signed

#17467 Separate Replication2 and Graph test directory with their own CMakeLists.txt
  tests/CMakeLists.txt
  tests/Graph/CMakeLists.txt
  tests/Replication2/CMakeLists.txt
Labels: cla-signed

#17400 BTS-1082: Updating properties of a satellite collection breaks replicationFactor
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
Labels: 3 Cluster, cla-signed

#17401 Coordinator commit for streaming transactions - BTS-1086
  CHANGELOG
  arangod/Cluster/ClusterTrxMethods.cpp
Labels: 3 Cluster, 3 Transaction, cla-signed

#17405 Bug fix 3.9/bts 1070
  CHANGELOG
  arangod/Aql/AstNode.cpp
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/client/shell/api/cusror.js
  tests/js/client/shell/api/explain.js
  tests/js/server/aql/aql-window-malarkey.js
Labels: 3 AQL, cla-signed

#17408 Solve excessive memory consumption in multi-iterators - BTS-1088
  CHANGELOG
  arangod/Indexes/IndexIterator.cpp
  arangod/Indexes/IndexIterator.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
Labels: cla-signed

#17514 test must not assert during test setup to get proper results!
  tests/js/client/active-failover/basic.js
  tests/js/client/active-failover/readonly.js
Labels: cla-signed

#17413 Feature 3.9/SEARCH-408 arangosearch hot set
  3rdParty/iresearch/core/formats/columnstore.cpp
  3rdParty/iresearch/core/formats/columnstore2.cpp
  3rdParty/iresearch/core/formats/columnstore2.hpp
  3rdParty/iresearch/core/formats/formats.cpp
  3rdParty/iresearch/core/formats/formats.hpp
  3rdParty/iresearch/core/index/directory_reader.cpp
  3rdParty/iresearch/core/index/directory_reader.hpp
  3rdParty/iresearch/core/index/index_reader.hpp
  3rdParty/iresearch/core/index/index_writer.cpp
  3rdParty/iresearch/core/index/segment_reader.cpp
  3rdParty/iresearch/core/index/segment_reader.hpp
  3rdParty/iresearch/core/store/directory.hpp
  3rdParty/iresearch/core/store/fs_directory.cpp
  3rdParty/iresearch/core/store/mmap_directory.cpp
  3rdParty/iresearch/core/store/store_utils.cpp
  3rdParty/iresearch/core/store/store_utils.hpp
  3rdParty/iresearch/core/utils/compression.hpp
  3rdParty/iresearch/core/utils/file_utils.cpp
  3rdParty/iresearch/core/utils/file_utils.hpp
  3rdParty/iresearch/tests/formats/columnstore2_test.cpp
  3rdParty/iresearch/tests/index/merge_writer_tests.cpp
  3rdParty/iresearch/tests/search/index_reader_test.cpp
  CHANGELOG
  Documentation/Metrics/arangodb_search_columns_cache_size.yaml
  arangod/CMakeLists.txt
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchKludge.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/IResearchViewStoredValues.cpp
  arangod/IResearch/IResearchViewStoredValues.h
  arangod/RestServer/Metrics.h
  tests/IResearch/IResearchLinkMeta-test.cpp
Labels: 3 ArangoSearch, cla-signed

#17472 Repair "load indexes into memory" functions for web UI and SmartGraph edge collections
  CHANGELOG
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_load_indexes_in_memory.md
  arangod/Cluster/ClusterMethods.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/VocBase/Methods/Collections.cpp
  lib/Basics/LocalTaskQueue.cpp
Labels: 3 API, cla-signed

#17439 BTS-999: Bug fix 3.9/bulk inserts
  tests/js/client/shell/shell-iterators-read-standalone.js
  tests/js/client/shell/shell-iterators-read-transaction.js
  tests/js/client/shell/shell-iterators-write-standalane.js
  tests/js/client/shell/shell-iterators-write-transaction.js
  tests/js/client/shell/shell-iterators.inc
  tests/js/common/shell/shell-community-sharding-compat-cluster.js
  tests/js/common/shell/shell-pregel-components.js
  tests/js/common/shell/shell-pregel-multicollection-edgecol.js
  tests/js/server/aql/aql-optimizer-collect-count.js
Labels: 3 - Testing, cla-signed

#17525 [PREGEL] Bugfix/fix pregel staging
  tests/Pregel/Messaging/MessageQueueTest.cpp
Labels: 3 Pregel, cla-signed

#17530 [testing][documentation] fix link to the oskar documentation
  tests/test-definitions.txt
Labels: cla-signed

#17538 Show number of HTTP requests in cluster query profiles.
  CHANGELOG
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#17537 remove patch instruction for snowball
  3rdParty/README_maintainers.md
Labels: cla-signed

#17523 Removed assertions from cluster rebalance test
  CHANGELOG
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: cla-signed

#17542 BTS-944: fix disk space metrics on macOS
  lib/Basics/files.cpp
Labels: cla-signed

#17512 Bug fix 3.9/SEARCH-411 double commit fix
  3rdParty/iresearch/core/index/index_writer.cpp
  3rdParty/iresearch/core/index/index_writer.hpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLink.h
  arangod/IResearch/IResearchPrimaryKeyFilter.cpp
  arangod/IResearch/IResearchPrimaryKeyFilter.h
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.h
  arangod/RocksDBEngine/Methods/RocksDBReadOnlyBaseMethods.h
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.h
  arangod/RocksDBEngine/RocksDBRecoveryHelper.h
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  arangod/RocksDBEngine/RocksDBTransactionMethods.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  tests/IResearch/IResearchLink-test.cpp
  tests/IResearch/IResearchView-test.cpp
  tests/IResearch/IResearchViewDBServer-test.cpp
  tests/Mocks/IResearchLinkMock.h
  tests/Mocks/StorageEngineMock.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
  tests/js/server/recovery/view-arangosearch-link-three-transactions-noncluster.js
  tests/js/server/recovery/view-arangosearch-link-three-transactions_stage1-noncluster.js
  tests/js/server/recovery/view-arangosearch-link-three-transactions_stage2-noncluster.js
  tests/test-definitions.txt
Labels: 3 ArangoSearch, cla-signed

#17540 Show number of HTTP requests in cluster query profiles.
  CHANGELOG
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#16506 Added CSP headers for Aardvaark, as per BTS-196.
  CHANGELOG
  arangod/GeneralServer/CommTask.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/js/client/shell/api/http-novst.js
  tests/js/client/shell/shell-foxx-cors-spec.js
Labels: 3 UI, cla-signed

#17545 fix compile warnings in tests
  tests/Graph/AllShortestPathsFinderTest.cpp
  tests/Graph/ClusterTraverserCacheTest.cpp
  tests/Graph/ConstantWeightShortestPathFinder.cpp
  tests/Graph/DFSFinderTest.cpp
  tests/Graph/FifoQueueTest.cpp
  tests/Graph/KPathFinderTest.cpp
  tests/Graph/KShortestPathsFinder.cpp
  tests/Graph/LifoQueueTest.cpp
  tests/Graph/PathStoreTest.cpp
  tests/Graph/PathValidatorTest.cpp
  tests/Graph/SingleServerProviderTest.cpp
  tests/Graph/TraverserCacheTest.cpp
  tests/Graph/WeightedQueueTest.cpp
  tests/IResearch/common.cpp
  tests/Replication2/ModelChecker/Tests/ModelCheckerTest.cpp
  tests/Replication2/ReplicatedLog/CalcCommitIndexTest.cpp
  tests/Replication2/ReplicatedLog/ConcurrencyTests.cpp
  tests/Replication2/ReplicatedLog/EstablishLeadershipTest.cpp
  tests/Replication2/ReplicatedLog/LeaderAppendEntriesTest.cpp
  tests/Replication2/ReplicatedLog/MaintenanceTests.cpp
  tests/Replication2/ReplicatedLog/ParticipantsHealthTest.cpp
  tests/Replication2/ReplicatedLog/RewriteLogTest.cpp
  tests/Replication2/ReplicatedLog/RocksDBLogTest.cpp
  tests/Replication2/ReplicatedLog/SimpleInsertTests.cpp
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
  tests/Replication2/ReplicatedLog/UpdateParticipantsFlags.cpp
  tests/Replication2/ReplicatedLog/UpdateReplicatedLogTests.cpp
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/Replication2/ReplicatedState/MaintenanceTest.cpp
  tests/Replication2/ReplicatedState/PrototypeStateMachineTest.cpp
  tests/Replication2/ReplicatedState/ReplicatedStateTest.cpp
  tests/Replication2/ReplicatedState/StateCleanupTest.cpp
  tests/Replication2/ReplicatedState/SupervisionTest.cpp
  tests/Replication2/Serialization/AgencyLogSpecificationTest.cpp
Labels: cla-signed

#17536 [PREGEL] Cast PregelShard input explicitly to uint16_t
  arangod/Pregel/Algos/DMID/DMIDMessageFormat.h
  arangod/Pregel/Algos/DMID/VertexSumAggregator.h
  arangod/Pregel/CommonFormats.h
  arangod/Pregel/Worker/GraphStore.cpp
  arangod/Pregel/Worker/WorkerConfig.cpp
Labels: 3 Pregel, cla-signed

#17449 BTS-1098: Bug fix/fix resillience teardown
  tests/js/server/resilience/failover/resilience-synchronous-repl-cluster.js
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#17526 Implemented option of removing system collections from rebalance plan
  CHANGELOG
  arangod/Cluster/AutoRebalance.cpp
  arangod/Cluster/AutoRebalance.h
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminClusterHandler.h
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: cla-signed

#17445 Do not drop non-bounded queue items
  arangod/Scheduler/Scheduler.h
  arangod/Scheduler/SupervisedScheduler.cpp
Labels: 1 Bug, cla-signed

#17534 Move CMake definitions of some libraries inside the lib-directory into their own directories
  arangod/Agency/v8-agency.cpp
  arangod/Cluster/v8-cluster.cpp
  arangod/RestHandler/RestTasksHandler.cpp
  arangod/RestServer/arangod_includes.h
  arangod/V8Server/V8DealerFeature.cpp
  arangod/V8Server/v8-actions.cpp
  arangod/V8Server/v8-dispatcher.cpp
  arangod/VocBase/Methods/Transactions.cpp
  client-tools/Shell/V8ClientConnection.cpp
  client-tools/Shell/V8ShellFeature.cpp
  client-tools/Shell/arangosh.cpp
  lib/CMakeLists.txt
  lib/Geo/CMakeLists.txt
  lib/Geo/S2/CMakeLists.txt
  lib/Geo/karney/CMakeLists.txt
  lib/V8/CMakeLists.txt
  lib/V8/V8SecurityFeature.cpp
  lib/V8/V8SecurityFeature.h
  lib/V8/v8-environment.cpp
  lib/V8/v8-shell.cpp
  lib/V8/v8-utils.cpp
  lib/VelocypackUtils/CMakeLists.txt
  lib/VelocypackUtils/VelocyPackStringLiteral.cpp
  lib/VelocypackUtils/VelocyPackStringLiteral.h
  tests/Basics/InspectionTest.cpp
  tests/Basics/VelocyPackHelperTest.cpp
  tests/CMakeLists.txt
  tests/Mocks/Servers.cpp
  tests/V8Server/V8AnalyzersTest.cpp
  tests/V8Server/V8UsersTest.cpp
  tests/V8Server/V8ViewsTest.cpp
Labels: cla-signed, cmake improvements

#17547 Do not query vertex data in K_PATHS queries if vertex data is not needed
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/EnumeratePathsNode.cpp
  arangod/Aql/IndexNode.cpp
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/Aql/OptimizerUtils.h
  arangod/Aql/Projections.cpp
  arangod/Aql/Projections.h
  arangod/Aql/TraversalNode.cpp
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
  arangod/Graph/Cache/RefactoredTraverserCache.h
  arangod/Graph/Enumerators/OneSidedEnumerator.cpp
  arangod/Graph/Options/OneSidedEnumeratorOptions.cpp
  arangod/Graph/Options/OneSidedEnumeratorOptions.h
  arangod/Graph/Providers/BaseProviderOptions.cpp
  arangod/Graph/Providers/BaseProviderOptions.h
  arangod/Graph/Providers/ClusterProvider.cpp
  arangod/Graph/Providers/SingleServerProvider.cpp
  arangod/Graph/Queues/LifoQueue.h
  arangod/Graph/ShortestPathOptions.cpp
  arangod/Graph/Steps/ClusterProviderStep.cpp
  arangod/Graph/Steps/ClusterProviderStep.h
  arangod/Graph/Steps/SingleServerProviderStep.cpp
  arangod/Graph/Steps/SingleServerProviderStep.h
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  tests/Graph/GenericGraphProviderTest.cpp
  tests/Graph/KShortestPathsFinder.cpp
  tests/Graph/SingleServerProviderTest.cpp
  tests/Graph/TraverserCacheTest.cpp
  tests/Replication2/ReplicatedLog/SimpleInsertTests.cpp
  tests/js/server/aql/aql-graph.js
Labels: cla-signed

#17557 [testing] don't spawn test in its own arangosh
  js/client/modules/@arangodb/testsuites/resilience.js
Labels: 3 - Testing, cla-signed

#17531 Add missing targets
  CMakeLists.txt
Labels: cla-signed

#17555 small code cleanup
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/TraverserEngineShardLists.cpp
  arangod/Aql/TraverserEngineShardLists.h
  arangod/Cluster/TraverserEngine.cpp
  arangod/Graph/TraverserOptions.cpp
  arangod/InternalRestHandler/InternalRestTraverserHandler.cpp
  arangod/InternalRestHandler/InternalRestTraverserHandler.h
  arangod/RocksDBEngine/Listeners/RocksDBBackgroundErrorListener.cpp
Labels: cla-signed

#17564 cleanup of license manager code
  lib/Ssl/SslInterface.cpp
  scripts/startLocalCluster.sh
Labels: cla-signed

#17561 fix handling of parameters for `db._profileQuery(object)`
  js/client/modules/@arangodb/arango-database.js
  js/server/modules/@arangodb/arango-database.js
Labels: cla-signed

#17451 DOC-144 | APM-222 | Disable shard migration docs
  Documentation/DocuBlocks/Rest/Administration/get_api_cluster_endpoints.md
  Documentation/DocuBlocks/Rest/Cluster/get_cluster_health.md
  Documentation/DocuBlocks/Rest/Cluster/get_cluster_maintenance_dbserver.md
  Documentation/DocuBlocks/Rest/Cluster/get_cluster_statistics.md
  Documentation/DocuBlocks/Rest/Cluster/put_cluster_maintenance.md
  Documentation/DocuBlocks/Rest/Cluster/put_cluster_maintenance_dbserver.md
Labels: 3 Documentation, 3 API, cla-signed

#17461 DOC-144 | APM-222 | Disable shard migration docs
  Documentation/DocuBlocks/Rest/Administration/get_api_cluster_endpoints.md
  Documentation/DocuBlocks/Rest/Cluster/get_cluster_health.md
  Documentation/DocuBlocks/Rest/Cluster/get_cluster_maintenance_dbserver.md
  Documentation/DocuBlocks/Rest/Cluster/get_cluster_statistics.md
  Documentation/DocuBlocks/Rest/Cluster/put_cluster_maintenance.md
  Documentation/DocuBlocks/Rest/Cluster/put_cluster_maintenance_dbserver.md
Labels: 3 Documentation, 3 API, cla-signed

#17533 Added backport to 3.10
  CHANGELOG
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: 3 Cluster, 3 - Testing, cla-signed

#17539 Show number of HTTP requests in cluster query profiles.
  CHANGELOG
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#17484 AQL: Do not lex `NOT instance` or similar expressions as `NOT IN` operator plus something
  CHANGELOG
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.hpp
  arangod/Aql/tokens.cpp
  arangod/Aql/tokens.ll
  tests/js/server/aql/aql-parse.js
Labels: 1 Bug, 3 AQL, cla-signed

#17489 AQL: Do not lex `NOT instance` or similar expressions as `NOT IN` operator plus something
  CHANGELOG
  arangod/Aql/tokens.cpp
  arangod/Aql/tokens.ll
  tests/js/server/aql/aql-parse.js
Labels: 1 Bug, 3 AQL, cla-signed

#17565 simplify handling of special functions in arangosh
  client-tools/Shell/V8ShellFeature.cpp
  js/client/client.js
  js/client/modules/@arangodb/arangosh.js
  js/common/bootstrap/modules/internal.js
  lib/CMakeLists.txt
  lib/Utilities/IsArangoExecutable.cpp
  lib/Utilities/IsArangoExecutable.h
  lib/Utilities/LinenoiseShell.cpp
Labels: cla-signed

#17574 Delete IResearchSearchFunc.cpp
  arangod/IResearch/IResearchSearchFunc.cpp
Labels: cla-signed

#17575 [PREGEL] Bugfix/fix staging build
  arangod/Pregel/CommonFormats.h
  tests/Pregel/Messaging/MessageQueueTest.cpp
Labels: 3 Pregel, cla-signed

#17578 fix compile warnings with g++-11.3
  arangod/Agency/Job.cpp
Labels: cla-signed

#17585 Add suppression for iresearch
  tsan_arangodb_suppressions.txt
Labels: cla-signed

#17589 increase test timeout
  tests/js/client/server_parameters/wal-archive-size-limit-large-noncluster.js
  tests/js/client/server_parameters/wal-archive-size-limit-small-noncluster.js
  tests/js/client/server_parameters/wal-archive-size-limit.inc
Labels: cla-signed

#17496 JS tests for inverted index + search-alias [CE]
  js/client/modules/@arangodb/test-helper.js
  js/common/modules/@arangodb/test-helper-common.js
  js/server/modules/@arangodb/test-helper.js
  tests/js/common/aql/aql-arangosearch-inverted-index-search-alias-community.js
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/test-data/search/docs/generate_ii_sa_dataset.py
  tests/js/common/test-data/search/docs/ii_sa_dataset.json
  tests/js/common/test-data/search/docs/lsh_dataset.json
Labels: 3 - Testing, 3 ArangoSearch, cla-signed

#17593 print CPU and RAM info on non-mac systems, too
  arangod/RestServer/EnvironmentFeature.cpp
Labels: cla-signed

#17592 remove ManagedDocumentResult (RIP)
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
  arangod/Graph/Cache/RefactoredTraverserCache.h
  arangod/Graph/TraverserCache.cpp
  arangod/Graph/TraverserCache.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/StorageEngine/PhysicalCollection.h
  arangod/Transaction/Methods.cpp
  arangod/VocBase/CMakeLists.txt
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/ManagedDocumentResult.cpp
  arangod/VocBase/ManagedDocumentResult.h
  lib/Inspection/InspectorBase.h
  tests/Graph/GenericGraphProviderTest.cpp
  tests/IResearch/IResearchAnalyzerFeatureTest.cpp
  tests/IResearch/IResearchViewNodeTest.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
Labels: cla-signed

#17563 Implemented option of removing system collections from rebalance plan
  CHANGELOG
  Documentation/DocuBlocks/Rest/Administration/1_structs.md
  arangod/Cluster/AutoRebalance.cpp
  arangod/Cluster/AutoRebalance.h
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminClusterHandler.h
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: cla-signed

#17556 Actor for Pregel with tests
  .github/workflows/pregel.yml
  CMakeLists.txt
  CMakePresets.json
  arangod/Pregel/Actor/Actor.cpp
  arangod/Pregel/Actor/Actor.h
  arangod/Pregel/Actor/MPSCQueue.h
  arangod/Pregel/Actor/SimpleQueue.h
  arangod/Pregel/tests/Actor/ActorTest.cpp
  arangod/Pregel/tests/Actor/CMakeLists.txt
  arangod/Pregel/tests/Actor/InitialStateActorTest.cpp
  arangod/Pregel/tests/Actor/MPSCQueueTest.cpp
  arangod/Pregel/tests/Actor/SimpleQueueTest.cpp
  arangod/Pregel/tests/Actor/main.cpp
  arangod/Pregel/tests/CMakeLists.txt
Labels: 3 Pregel, cla-signed

#17600 [testing] distribute these tests, so the same tests don't run in parallel
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#17579 [testing] increase resource usage
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#17580 increase resource usage
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#17570 give the cluster fuzzer tests more resources
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#17604 Build googletest like CMake exists
  3rdParty/CMakeLists.txt
  tests/CMakeLists.txt
  tests/Replication2/CMakeLists.txt
Labels: cla-signed, cmake improvements

#17598 willify a test
  tests/js/client/server_parameters/wal-archive-size-limit-small-noncluster.js
Labels: 3 - Testing, cla-signed

#17599 Bug-fix 3.9 BTS-1125
  CHANGELOG
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchLinkHelper.h
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewMeta.h
  tests/IResearch/IResearchIndex-test.cpp
  tests/IResearch/IResearchViewMeta-test.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl.js
Labels: 3 ArangoSearch, cla-signed

#17455 [testing] having crash text definitely means the test is not stable.
  UnitTests/unittest.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/result-processing.js
Labels: 3 - Testing, cla-signed

#17588 willify a test
  tests/js/client/server_parameters/wal-archive-size-limit-small-noncluster.js
Labels: 3 - Testing, cla-signed

#17566 BTS-1075: unify behavior of DOCUMENT() function with empty keys
  CHANGELOG
  arangod/Aql/Functions.cpp
  tests/js/server/aql/aql-document.js
Labels: cla-signed

#17613 Fix setting query memory limit to 0 (unbounded)
  CHANGELOG
  arangod/Aql/QueryOptions.cpp
  tests/js/client/server_parameters/test-memory-limit.js
Labels: cla-signed

#17571 Bug fix 3.10/tcpdump crash prevails
  UnitTests/unittest.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/result-processing.js
Labels: 3 - Testing, cla-signed

#17477 Repair "load indexes into memory" functions for web UI and SmartGraph edge collections
  CHANGELOG
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_load_indexes_in_memory.md
  arangod/Cluster/ClusterMethods.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/VocBase/Methods/Collections.cpp
  lib/Basics/LocalTaskQueue.cpp
  tests/js/common/shell/shell-collection-noncluster.js
Labels: cla-signed

#17576 BTS-1075: unify behavior of DOCUMENT() function with empty keys
  CHANGELOG
  arangod/Aql/Functions.cpp
  tests/js/server/aql/aql-document.js
Labels: cla-signed

#17607 Improve put_api_collection_load_indexes_into_memory DocuBlock
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_load_indexes_in_memory.md
Labels: 3 Documentation, 3 API, cla-signed

#17595 [BTS-1119] Changed query memory limit to pass tests on mac
  tests/js/server/aql/aql-complex-queries-callstack.js
Labels: cla-signed

#17622 update socials
  README.md
Labels: cla-signed

#17587 [testing] Feature/test filtering for rta make checkdata
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: 3 - Testing, cla-signed

#17625 Fix division by zero
  lib/V8/v8-utils.cpp
Labels: cla-signed, Backport Needed

#17597 [3.10] JS tests for inverted index + search-alias [CE] (#17496)
  js/client/modules/@arangodb/test-helper.js
  js/common/modules/@arangodb/test-helper-common.js
  js/server/modules/@arangodb/test-helper.js
  tests/js/common/aql/aql-arangosearch-inverted-index-search-alias-community.js
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/test-data/search/docs/generate_ii_sa_dataset.py
  tests/js/common/test-data/search/docs/ii_sa_dataset.json
  tests/js/common/test-data/search/docs/lsh_dataset.json
Labels: 3 - Testing, 3 ArangoSearch, cla-signed

#17619 fixed issue #17291
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  tests/js/common/aql/aql-prune-expressions.js
Labels: cla-signed

#17546 Do not query vertex data in K_PATHS queries if vertex data is not needed
  CHANGELOG
  arangod/Aql/EnumeratePathsNode.cpp
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
  arangod/Graph/Cache/RefactoredTraverserCache.h
  arangod/Graph/Enumerators/OneSidedEnumerator.cpp
  arangod/Graph/Options/OneSidedEnumeratorOptions.cpp
  arangod/Graph/Options/OneSidedEnumeratorOptions.h
  arangod/Graph/Providers/BaseProviderOptions.cpp
  arangod/Graph/Providers/BaseProviderOptions.h
  arangod/Graph/Providers/ClusterProvider.cpp
  arangod/Graph/Providers/SingleServerProvider.cpp
  arangod/Graph/Queues/LifoQueue.h
  arangod/Graph/ShortestPathOptions.cpp
  arangod/Graph/Steps/ClusterProviderStep.cpp
  arangod/Graph/Steps/ClusterProviderStep.h
  arangod/Graph/Steps/SingleServerProviderStep.cpp
  arangod/Graph/Steps/SingleServerProviderStep.h
  tests/Graph/GenericGraphProviderTest.cpp
  tests/Graph/SingleServerProviderTest.cpp
  tests/Graph/TraverserCacheTest.cpp
  tests/js/server/aql/aql-graph.js
Labels: 3 Graph, cla-signed

#17611 fix USE_FAIL_ON_WARNINGS CMake option
  3rdParty/CMakeLists.txt
  3rdParty/immer/v0.7.0/immer/detail/hamts/champ.hpp
  3rdParty/immer/v0.7.0/immer/detail/hamts/node.hpp
  CMakeLists.txt
  arangod/Aql/Projections.cpp
  arangod/CMakeLists.txt
  arangod/IResearch/CMakeLists.txt
  arangod/Pregel/CommonFormats.h
  arangod/Zkd/ZkdHelper.cpp
  client-tools/CMakeLists.txt
  lib/ApplicationFeatures/ApplicationServer.h
  lib/CMakeLists.txt
  lib/Geo/CMakeLists.txt
  lib/V8/CMakeLists.txt
Labels: cla-signed

#17583 Remove more assertions from rebalance test
  CHANGELOG
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: cla-signed

#17615 Fix setting query memory limit to 0 (unbounded)
  CHANGELOG
  arangod/Aql/QueryOptions.cpp
  tests/js/client/server_parameters/test-memory-limit.js
Labels: cla-signed

#17614 Fix setting query memory limit to 0 (unbounded)
  CHANGELOG
  arangod/Aql/QueryOptions.cpp
  tests/js/client/server_parameters/test-memory-limit.js
Labels: cla-signed

#17632 [testing]if after a restore attempt the server isn't healthy anymore properly abort the test so we don't clean up
  js/client/modules/@arangodb/testsuites/dump.js
Labels: 3 ImportExport, 3 - Testing, cla-signed

#17610 IResearch backports 3.9
  3rdParty/iresearch/core/index/segment_writer.cpp
  3rdParty/iresearch/core/index/segment_writer.hpp
  arangod/IResearch/IResearchLink.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: 3 ArangoSearch, cla-signed

#17584 3.10 backport remove more rebalance test assertions
  CHANGELOG
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: 3 Cluster, 3 - Testing, cla-signed

#17629 SEARCH-385 and other fixes
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/Indexes/IndexFactory.cpp
  arangod/Indexes/IndexFactory.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  tests/js/common/aql/aql-arangosearch-inverted-index-search-alias-community.js
Labels: cla-signed, Backport Needed

#17640 Update ubsan_arangodb_suppressions.txt
  ubsan_arangodb_suppressions.txt
Labels: cla-signed, Backport Needed

#17650 Search fix asan
  arangod/IResearch/IResearchDataStore.h
Labels: cla-signed, Backport Needed

#17647 [testing] if after a restore attempt the server isn't healthy anymore properly …
  js/client/modules/@arangodb/testsuites/dump.js
Labels: 3 - Testing, cla-signed

#17628 Bug fix/search-408 cached columns
  Documentation/Metrics/arangodb_search_columns_cache_size.yaml
  arangod/IResearch/Containers.h
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchKludge.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchLinkHelper.h
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewMeta.h
  arangod/IResearch/IResearchViewStoredValues.cpp
  arangod/IResearch/IResearchViewStoredValues.h
  arangod/Indexes/CMakeLists.txt
  arangod/Metrics/Gauge.h
  tests/IResearch/CMakeLists.txt
  tests/IResearch/IResearchAnalyzerFeatureTest.cpp
  tests/IResearch/IResearchIndexTest.cpp
  tests/IResearch/IResearchLinkMetaTest.cpp
  tests/IResearch/IResearchOrderTest.cpp
  tests/IResearch/IResearchTestCommon.cpp
  tests/IResearch/IResearchViewMetaTest.cpp
  tests/Zkd/Library.cpp
  tests/js/common/aql/aql-inverted-index-ddl.js
  tests/js/common/aql/aql-view-arangosearch-ddl.js
Labels: cla-signed, Backport Needed

#17649 SEARCH-427 fix and test
  arangod/IResearch/AqlHelper.cpp
  tests/js/server/aql/aql-inverted-index.js
Labels: cla-signed, Backport Needed

#17636 Make two deprecated `--server.disable-authentication*` server startup options obsolete
  CHANGELOG
  arangod/GeneralServer/AuthenticationFeature.cpp
Labels: 3 Core, cla-signed

#17635 [PREG-180] Split Pregel V8 methods into their own file
  arangod/V8Server/CMakeLists.txt
  arangod/V8Server/v8-collection.cpp
  arangod/V8Server/v8-pregel.cpp
  arangod/V8Server/v8-pregel.h
  arangod/V8Server/v8-vocbase.cpp
Labels: 3 Pregel, cla-signed

#17663 fix test on Windows
  tests/js/server/aql/aql-temp-rocksdb-storage.js
Labels: cla-signed

#17623 fixed issue #17291
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  tests/js/common/aql/aql-prune-expressions.js
Labels: cla-signed

#17617 fixed issue #17291
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  tests/js/common/aql/aql-prune-expressions.js
Labels: cla-signed

#17618 fixed issue #17291
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  tests/js/common/aql/aql-prune-expressions.js
Labels: cla-signed

#17519 Enable "collect-in-cluster" optimizer rule for SmartGraph edge collections
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-collect-count.js
  tests/js/server/aql/aql-optimizer-rule-collect-in-cluster.js
Labels: 3 Graph, 3 Optimizer, cla-signed

#17661 Remove unnecessary crc32c implementation
  Documentation/DocuBlocks/Rest/Administration/get_api_return.md
  arangod/Aql/Functions.cpp
  arangod/Sharding/ShardingStrategyDefault.cpp
  js/apps/system/_admin/aardvark/APP/api-docs.json
  lib/Basics/crc1.S
  lib/Basics/crc4.S
  lib/Basics/crc5.S
  lib/Basics/files.cpp
  lib/Basics/hashes.cpp
  lib/Basics/hashes.h
  lib/CMakeLists.txt
  lib/Containers/MerkleTree.cpp
  lib/Rest/Version.cpp
  tests/Basics/HashesTest.cpp
  tests/js/server/shell/shell-database-noncluster.js
Labels: cla-signed

#17659 fix USE_FAIL_ON_WARNINGS for unit tests as well
  tests/CMakeLists.txt
  tests/Fuerte/ConnectionConcurrentTest.cpp
  tests/Replication2/Mocks/FakeLeader.cpp
Labels: cla-signed

#17664 fix test on Windows
  tests/js/server/aql/aql-temp-rocksdb-storage.js
Labels: 3 - Testing, cla-signed

#17631 simplify some V8 integration code
  lib/V8/v8-globals.cpp
  lib/V8/v8-globals.h
  lib/V8/v8-utils.cpp
Labels: cla-signed

#17651 fix traffic accounting in internal statistics / metrics
  CHANGELOG
  Documentation/Metrics/arangodb_http1_connections_total.yaml
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/Statistics/RequestStatistics.cpp
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  js/client/modules/@arangodb/testsuites/aql.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  tests/js/client/shell/shell-check-metrics-move-noncluster.js
  tests/js/client/shell/traffic/shell-check-metrics-move-noncluster.js
  tests/test-definitions.txt
Labels: cla-signed

#17665 disable access to /proc filesystem when not on Linux
  arangod/RestServer/EnvironmentFeature.cpp
Labels: cla-signed

#17642 simplify handling of numeric startup option values
  CHANGELOG
  arangod/Aql/Arithmetic.cpp
  arangod/Aql/Arithmetic.h
  arangod/Aql/Ast.cpp
  lib/Basics/Arithmetic.h
  lib/ProgramOptions/Parameters.cpp
  lib/ProgramOptions/Parameters.h
  lib/ProgramOptions/UnitsHelper.h
  tests/ProgramOptions/ParametersTest.cpp
Labels: cla-signed

#17569 Delay MoveShard job until old and new leader ready - BTS-1110
  CHANGELOG
  arangod/Agency/MoveShard.cpp
  arangod/Agency/MoveShard.h
  tests/Agency/MoveShardTest.cpp
Labels: 3 Cluster, cla-signed

#17568 Delay MoveShard job until old and new leader ready - BTS-1110
  CHANGELOG
  arangod/Agency/MoveShard.cpp
  arangod/Agency/MoveShard.h
  tests/Agency/MoveShardTest.cpp
Labels: cla-signed

#17608 [CMAKE] Some CMakeLists.txt cleanups
  CMakeLists.txt
Labels: cla-signed, cmake improvements

#17616 Make CrashHandler its own thing
  arangod/RestServer/arangod_includes.h
  lib/ApplicationFeatures/TempFeature.cpp
  lib/Basics/PhysicalMemory.cpp
  lib/Basics/debugging.cpp
  lib/Basics/debugging.h
  lib/CMakeLists.txt
  lib/CrashHandler/CMakeLists.txt
  lib/CrashHandler/CrashHandler.cpp
  lib/CrashHandler/CrashHandler.h
  lib/CrashHandler/CrashHandlerLight.cpp
  tests/CMakeLists.txt
  tests/CrashHandler/CMakeLists.txt
  tests/CrashHandler/CrashHandlerLightTest.cpp
Labels: cla-signed

#17567 Delay MoveShard job until old and new leader ready - BTS-1110
  CHANGELOG
  arangod/Agency/MoveShard.cpp
  arangod/Agency/MoveShard.h
  tests/Agency/MoveShardTest.cpp
Labels: cla-signed

#17634 add missing `serverId` parameter
  CHANGELOG
  Documentation/DocuBlocks/Rest/Administration/get_admin_log.md
  arangod/RestHandler/RestAdminLogHandler.cpp
  arangod/RestHandler/RestAdminLogHandler.h
  tests/js/client/shell/shell-admin-log.js
Labels: cla-signed

#17652 fix traffic accounting in internal statistics / metrics
  CHANGELOG
  Documentation/Metrics/arangodb_http1_connections_total.yaml
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/Statistics/RequestStatistics.cpp
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  js/client/modules/@arangodb/testsuites/aql.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  tests/js/client/shell/shell-check-metrics-move-noncluster.js
  tests/js/client/shell/traffic/shell-check-metrics-move-noncluster.js
  tests/test-definitions.txt
Labels: cla-signed

#17667 disable access to /proc filesystem when not on Linux
  arangod/RestServer/EnvironmentFeature.cpp
Labels: cla-signed

#17669 Fix intermediate commit for arangosearch links and inverted index
  arangod/Aql/StandaloneCalculation.cpp
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/RocksDBEngine/Methods/RocksDBReadOnlyBaseMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBReadOnlyBaseMethods.h
  arangod/RocksDBEngine/Methods/RocksDBSingleOperationTrxMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBSingleOperationTrxMethods.h
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.h
  arangod/RocksDBEngine/Methods/RocksDBTrxMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxMethods.h
  arangod/RocksDBEngine/RocksDBTransactionMethods.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/SimpleRocksDBTransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  tests/Mocks/StorageEngineMock.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: cla-signed

#17668 Bug fix 3.10/SEARCH-427 SEARCH-408 backports
  CHANGELOG
  Documentation/Metrics/arangodb_search_columns_cache_size.yaml
  arangod/CMakeLists.txt
  arangod/IResearch/AqlHelper.cpp
  arangod/IResearch/Containers.h
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchKludge.h
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchLinkHelper.h
  arangod/IResearch/IResearchLinkMeta.cpp
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewMeta.h
  arangod/IResearch/IResearchViewStoredValues.cpp
  arangod/IResearch/IResearchViewStoredValues.h
  arangod/Metrics/Gauge.h
  tests/IResearch/CMakeLists.txt
  tests/IResearch/IResearchIndexTest.cpp
  tests/IResearch/IResearchLinkMetaTest.cpp
  tests/IResearch/IResearchViewMetaTest.cpp
  tests/Zkd/Library.cpp
  tests/js/common/aql/aql-inverted-index-ddl.js
  tests/js/common/aql/aql-view-arangosearch-ddl.js
  tests/js/server/aql/aql-inverted-index.js
  ubsan_arangodb_suppressions.txt
Labels: cla-signed

#17654 fix traffic accounting in internal statistics / metrics
  CHANGELOG
  Documentation/Metrics/arangodb_http1_connections_total.yaml
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  js/client/modules/@arangodb/testsuites/aql.js
  js/client/modules/@arangodb/testutils/test-utils.js
  tests/js/client/shell/shell-check-metrics-move-noncluster.js
  tests/js/client/shell/traffic/shell-check-metrics-move-noncluster.js
  tests/test-definitions.txt
Labels: cla-signed

#17603 arangosearch Views: Add primarySortCache and primaryKeyCache options to DocuBlocks
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_arangosearch.md
Labels: 3 Documentation, 3 Swagger, cla-signed

#17677 Fix v8 environment variable buffer overrun
  lib/V8/v8-environment.cpp
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#17653 fix traffic accounting in internal statistics / metrics
  CHANGELOG
  Documentation/Metrics/arangodb_http1_connections_total.yaml
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/Statistics/RequestStatistics.cpp
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  js/client/modules/@arangodb/testsuites/aql.js
  js/client/modules/@arangodb/testutils/test-utils.js
  tests/js/client/shell/shell-check-metrics-move-noncluster.js
  tests/js/client/shell/traffic/shell-check-metrics-move-noncluster.js
  tests/test-definitions.txt
Labels: cla-signed

#17517 Enable "collect-in-cluster" optimizer rule for SmartGraph edge collections
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-collect-count.js
  tests/js/server/aql/aql-optimizer-rule-collect-in-cluster.js
Labels: cla-signed

#17662 [PREG-182] Delete current customizable pregel
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/Functions.h
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/Algos/AIR/AIR.cpp
  arangod/Pregel/Algos/AIR/AIR.h
  arangod/Pregel/Algos/AIR/AbstractAccumulator.cpp
  arangod/Pregel/Algos/AIR/AbstractAccumulator.h
  arangod/Pregel/Algos/AIR/AccumulatorOptions.cpp
  arangod/Pregel/Algos/AIR/AccumulatorOptions.h
  arangod/Pregel/Algos/AIR/Accumulators.cpp
  arangod/Pregel/Algos/AIR/Accumulators.h
  arangod/Pregel/Algos/AIR/CMakeLists.txt
  arangod/Pregel/Algos/AIR/EdgeData.cpp
  arangod/Pregel/Algos/AIR/EdgeData.h
  arangod/Pregel/Algos/AIR/GraphFormat.cpp
  arangod/Pregel/Algos/AIR/GraphFormat.h
  arangod/Pregel/Algos/AIR/MasterContext.cpp
  arangod/Pregel/Algos/AIR/MasterContext.h
  arangod/Pregel/Algos/AIR/MessageData.cpp
  arangod/Pregel/Algos/AIR/MessageData.h
  arangod/Pregel/Algos/AIR/MessageFormat.cpp
  arangod/Pregel/Algos/AIR/MessageFormat.h
  arangod/Pregel/Algos/AIR/VertexComputation.cpp
  arangod/Pregel/Algos/AIR/VertexComputation.h
  arangod/Pregel/Algos/AIR/VertexData.cpp
  arangod/Pregel/Algos/AIR/VertexData.h
  arangod/Pregel/Algos/AIR/WorkerContext.cpp
  arangod/Pregel/Algos/AIR/WorkerContext.h
  arangod/Pregel/Algos/CMakeLists.txt
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/GraphFormat.h
  arangod/Pregel/GraphStore.cpp
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/Worker.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/CMakeLists.txt
  lib/Greenspun/EvalResult.h
  lib/Greenspun/Extractor.h
  lib/Greenspun/Interpreter.cpp
  lib/Greenspun/Interpreter.h
  lib/Greenspun/Primitives.cpp
  lib/Greenspun/Primitives.h
  lib/Greenspun/lib/DateTime.cpp
  lib/Greenspun/lib/DateTime.h
  lib/Greenspun/lib/Dicts.cpp
  lib/Greenspun/lib/Dicts.h
  lib/Greenspun/lib/Lists.cpp
  lib/Greenspun/lib/Lists.h
  lib/Greenspun/lib/Math.cpp
  lib/Greenspun/lib/Math.h
  lib/Greenspun/lib/Strings.cpp
  lib/Greenspun/lib/Strings.h
  tests/CMakeLists.txt
  tests/Greenspun/CMakeLists.txt
  tests/Greenspun/PrimitivesTest.cpp
  tests/Greenspun/REPL.cpp
Labels: 3 Pregel, cla-signed
