Repository arangodb/arangodb, pull requests merged in 2022-10, with the labels that each got.

#17250 [PREGEL] Fix failing test
  tests/js/client/shell/shell-custom-pregel-timecritical.js
Labels: 3 Pregel

#17247 [PREGEL] Compilation fixes for pregel staging.
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/TypedBuffer.h
Labels: 3 Pregel

#17233 [CMAKE] Activate graph tests
  tests/CMakeLists.txt
  tests/Graph/GenericGraphProviderTest.cpp
  tests/Graph/GraphTestTools.h
  tests/Mocks/MockQuery.h
Labels: cmake improvements

#17234 Extract arangod libraries to subdirectories
  arangod/Aql/CMakeLists.txt
  arangod/CMakeLists.txt
  arangod/Cluster/CMakeLists.txt
  arangod/ClusterEngine/CMakeLists.txt
  arangod/Graph/CMakeLists.txt
  arangod/Graph/Cache/CMakeLists.txt
  arangod/Graph/Cursors/CMakeLists.txt
  arangod/Graph/Enumerators/CMakeLists.txt
  arangod/Graph/Helpers/CMakeLists.txt
  arangod/Graph/Options/CMakeLists.txt
  arangod/Graph/PathManagement/CMakeLists.txt
  arangod/Graph/Providers/CMakeLists.txt
  arangod/Graph/Queues/CMakeLists.txt
  arangod/Graph/Steps/CMakeLists.txt
  arangod/Graph/Types/CMakeLists.txt
  arangod/IResearch/CMakeLists.txt
  arangod/Indexes/CMakeLists.txt
  arangod/Metrics/CMakeLists.txt
  arangod/Network/CMakeLists.txt
  arangod/Replication/CMakeLists.txt
  arangod/Replication2/CMakeLists.txt
  arangod/Replication2/Exceptions/CMakeLists.txt
  arangod/Replication2/ReplicatedLog/CMakeLists.txt
  arangod/Replication2/ReplicatedState/CMakeLists.txt
  arangod/Replication2/StateMachines/BlackHole/CMakeLists.txt
  arangod/Replication2/StateMachines/CMakeLists.txt
  arangod/Replication2/StateMachines/Document/CMakeLists.txt
  arangod/Replication2/StateMachines/Prototype/CMakeLists.txt
  arangod/Replication2/Streams/CMakeLists.txt
  arangod/RestHandler/CMakeLists.txt
  arangod/RestServer/CMakeLists.txt
  arangod/RocksDBEngine/CMakeLists.txt
  arangod/RocksDBEngine/Listeners/CMakeLists.txt
  arangod/RocksDBEngine/Methods/CMakeLists.txt
  arangod/Utils/CMakeLists.txt
  arangod/V8Server/CMakeLists.txt
  arangod/VocBase/CMakeLists.txt
  arangod/VocBase/Identifiers/CMakeLists.txt
  arangod/VocBase/Methods/CMakeLists.txt
  arangod/VocBase/Properties/CMakeLists.txt
  arangod/Zkd/CMakeLists.txt
  arangod/arangoserver.cmake
Labels: cmake improvements

#17202 fix issues with view changes replication
  CHANGELOG
  arangod/IResearch/Search.cpp
  arangod/Replication/TailingSyncer.cpp
  tests/js/server/replication/ongoing/global/replication-ongoing-global.js
  tests/js/server/replication/ongoing/replication-ongoing.js
  tests/js/server/replication/static/replication-static.js
Labels: 9 Ready to Merge, 3 ArangoSearch

#16646 [CINFRA-498] Replaced explicit-destroy/placement-new hack with optionals
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionBlockImpl.tpp
Labels: cinfra

#17223 Docs: ArangoSearch v2 corrections
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_searchalias.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_searchalias.md
Labels: 3 Documentation, 3 API, 3 ArangoSearch, 3.10

#17236 Search-401 Fix inverted index inventory 3.10
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndex.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  arangod/Indexes/Index.h
  arangod/VocBase/LogicalCollection.cpp
  tests/js/client/shell/shell-inventory-cluster.js
  tests/js/client/shell/shell-inventory-noncluster.js
  tests/js/server/dump/dump-authentication.js
  tests/js/server/dump/dump-setup-cluster.js
  tests/js/server/dump/dump-setup-common.inc
  tests/js/server/dump/dump-setup-mixed.js
  tests/js/server/dump/dump-setup.js
  tests/js/server/dump/dump-test.inc
Labels: 3 ArangoSearch

#17203 BTS-943: testing: move test out of non-existing suite, adjust to new instance methods
  CHANGELOG
  tests/js/client/shell/api/api-gharial-spec.js
  tests/js/client/shell/api/cluster-metrics-cluster-spec.js
Labels: 9 Ready to Merge

#17264 [PREGEL] Bugfix/fix jenkins on staging
  arangod/Pregel/Connection/NetworkConnection.cpp
  tests/js/client/load-balancing/load-balancing-pregel-auth-cluster.js
Labels: 3 Pregel

#17272 [PREGEL] Separate dir for messages
  arangod/Aql/Functions.cpp
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/AlgoRegistry.h
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/DoneState.cpp
  arangod/Pregel/Conductor/States/FatalErrorState.cpp
  arangod/Pregel/Conductor/States/LoadingState.cpp
  arangod/Pregel/Conductor/States/State.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/Connection/Connection.h
  arangod/Pregel/Connection/DirectConnection.cpp
  arangod/Pregel/Connection/NetworkConnection.cpp
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/IncomingCache.h
  arangod/Pregel/Messaging/ConductorMessages.h
  arangod/Pregel/Messaging/Message.h
  arangod/Pregel/Messaging/WorkerMessages.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/Worker/GraphStore.cpp
  arangod/Pregel/Worker/GraphStore.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/Worker/WorkerConfig.cpp
  arangod/Pregel/Worker/WorkerConfig.h
  arangod/Pregel/WorkerInterface.h
Labels: 3 Pregel

#17257 Disable replication1 specific test for replication2
  tests/js/client/shell/shell-following-term-id-cluster.js
Labels: cinfra

#17222 Docs: ArangoSearch v2 corrections
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_searchalias.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_searchalias.md
Labels: 3 Documentation, 3 API, 3 ArangoSearch

#17209 stabilize a test
  tests/js/client/server_parameters/exclusive-collections-off.js
Labels: 9 Ready to Merge, 3 - Testing

#17277 [CINFRA-588] Restart issues with replication2 databases
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
Labels: cinfra

#17297 [CINFRA-579] Enabling range deletes on followers
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
Labels: cinfra

#17260 add proper brackets to fix asan test
  js/client/modules/@arangodb/testutils/test-utils.js
Labels: 3 - Testing

#17216 BTS-1046: print test-info, correct invoking of exports (#17207)
  js/client/modules/@arangodb/testsuites/export.js
Labels: 3 - Testing

#17217 one more place missing bulk insert (#17189)
  tests/js/common/shell/shell-community-sharding-compat-cluster.js
Labels: 3 Cluster, 3 - Testing

#17241 [BTS-969] 3.10 backport
  CHANGELOG
  arangod/Cluster/AutoRebalance.cpp
  arangod/Cluster/AutoRebalance.h
  arangod/RestHandler/RestAdminClusterHandler.cpp
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: 3 API, 3 Cluster

#17248 adjust permission checking of search-alias views (#17228)
  CHANGELOG
  arangod/IResearch/Search.cpp
  tests/js/client/authentication/auth-analyzer-view-integration.js
  tests/js/client/authentication/user-access-right-create-view-arangosearch-spec.js
  tests/js/client/authentication/user-access-right-drop-view-arangosearch-spec.js
  tests/js/client/authentication/user-access-right-read-view-arangosearch-spec.js
  tests/js/client/authentication/user-access-right-task-create-view-arangosearch-search-alias-spec.js
  tests/js/client/authentication/user-access-right-task-create-view-arangosearch-spec.js
  tests/js/client/authentication/user-access-right-task-drop-view-arangosearch-spec.js
  tests/js/client/authentication/user-access-right-task-read-view-arangosearch-spec.js
  tests/js/client/authentication/user-access-right-task-update-view-arangosearch.js
  tests/js/client/authentication/user-access-right-update-view-arangosearch.js
Labels: 3 - Testing, 3 ArangoSearch

#17263 BTS-1061: fixed recoginition of ARM on Apple M1
  CHANGELOG
  arangod/RestServer/EnvironmentFeature.cpp
  lib/Basics/operating-system.h
  lib/Rest/Version.cpp
Labels: 3 Build

#17266 BTS-943: testing: move test out of non-existing suite, adjust to new instance methods
  CHANGELOG
  tests/js/client/shell/api/api-gharial-spec.js
  tests/js/client/shell/api/cluster-metrics-cluster-spec.js
Labels: 9 Review Required, 3 - Testing

#17269 SEARCH-402/403 Fixes 3.10
  arangod/Aql/Expression.cpp
  arangod/Aql/IndexNode.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/Aql/OptimizerUtils.h
  arangod/Aql/TraversalNode.cpp
  arangod/Graph/BaseOptions.cpp
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  tests/IResearch/IResearchInvertedIndexConditionTest.cpp
  tests/js/server/aql/aql-inverted-index.js
Labels: 3 ArangoSearch

#17265 BTS-1061: fixed recoginition of ARM on Apple M1
  CHANGELOG
  arangod/RestServer/EnvironmentFeature.cpp
  lib/Basics/operating-system.h
  lib/Rest/Version.cpp
Labels: 3 Build

#17218 BTS-1045: Bug fix/split modify test suite (#17198)
  tests/js/server/aql/aql-modify-Insert-noncluster.js
  tests/js/server/aql/aql-modify-Modify-noncluster.js
  tests/js/server/aql/aql-modify-Remove-noncluster.js
  tests/js/server/aql/aql-modify-Update-noncluster.js
  tests/js/server/aql/aql-modify-noncluster.js
Labels: 3 - Testing

#17261 Removal of already deleted orphan collections out of graph definition
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  tests/js/client/shell/api/general-graph.js
Labels: 9 Review Required

#17306 [PREGEL] Have only one internal pregel endpoint
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Connection/CMakeLists.txt
  arangod/Pregel/Connection/DirectConnection.cpp
  arangod/Pregel/Connection/DirectConnection.h
  arangod/Pregel/Connection/DirectConnectionToConductor.cpp
  arangod/Pregel/Connection/DirectConnectionToWorker.cpp
  arangod/Pregel/Connection/DirectConnectionToWorker.h
  arangod/Pregel/Connection/NetworkConnection.cpp
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/REST/RestPregelHandler.cpp
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel

#17215 BTS-997: split way to big testsuite into its natural chunks (#17185)
  js/common/modules/@arangodb/graph/helpers.js
  tests/js/server/aql/aql-graph-traverser-brokenGraph.js
  tests/js/server/aql/aql-graph-traverser-complexFiltering.js
  tests/js/server/aql/aql-graph-traverser-complexInterna.js
  tests/js/server/aql/aql-graph-traverser-edgeConnectedFromVertexToEdge.js
  tests/js/server/aql/aql-graph-traverser-exampleGraphs.js
  tests/js/server/aql/aql-graph-traverser-invalidStartVertex.js
  tests/js/server/aql/aql-graph-traverser-limit.js
  tests/js/server/aql/aql-graph-traverser-multiCollectionGraph.js
  tests/js/server/aql/aql-graph-traverser-multiEdgeCollectionGraph.js
  tests/js/server/aql/aql-graph-traverser-multiEdgeDirection.js
  tests/js/server/aql/aql-graph-traverser-namedGraph.js
  tests/js/server/aql/aql-graph-traverser-nested.js
  tests/js/server/aql/aql-graph-traverser-optimizeIn.js
  tests/js/server/aql/aql-graph-traverser-optimizeNonVertexCentricIndexes-noncluster.js
  tests/js/server/aql/aql-graph-traverser-optimizeQuantifier.js
  tests/js/server/aql/aql-graph-traverser-options.js
  tests/js/server/aql/aql-graph-traverser-potentialErrors.js
  tests/js/server/aql/aql-graph-traverser-pruneTraversal.js
  tests/js/server/aql/aql-graph-traverser-simpleInboundOutbound.js
  tests/js/server/aql/aql-graph-traverser-subQuery.js
  tests/js/server/aql/aql-graph-traverser-unusedVariable.js
  tests/js/server/aql/aql-graph-traverser.js
Labels: 3 Graph, 3 - Testing

#17307 [PREGEL] Setup for CMakeLists.txt to run separate test binary for pregel stuff
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/tests/CMakeLists.txt
  arangod/Pregel/tests/WeaklyConnectedComponentsTest.cpp
Labels: 3 Pregel

#17308 [OPTIMIZER2] Setup for CMakeLists.txt to run separate test binary for optimizer stuff
  tests/CMakeLists.txt
  tests/Optimizer2/CMakeLists.txt
  tests/Optimizer2/main.cpp
Labels: optimizer-2.0

#17188 Bug fix/enterprise graphs dump restore tests v2
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Sharding/ShardingFeature.cpp
  arangod/Sharding/ShardingFeature.h
  arangod/VocBase/LogicalCollection.h
  tests/js/server/dump/dump-test.inc
Labels: 3 Graph, 3 Cluster, 9 Review Required

#17309 [CINFRA-531] Move Shard Tests
  arangod/Cluster/ClusterInfo.cpp
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/StateMachines/Document/DocumentStateAgencyHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateAgencyHandler.h
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
  tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
Labels: cinfra

#17313 Removal of already deleted orphan collections out of graph definition
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  tests/js/client/shell/api/general-graph.js
Labels: 3 Graph, 9 Ready to Merge

#17275 [3.9] Build Snappy with RTTI (and fix MacOS exceptions)
  3rdParty/README_maintainers.md
  3rdParty/snappy/snappy-1.1.9/CMakeLists.txt
  lib/CMakeLists.txt
Labels: 3 Build, 4 MacOSX

#17312 Removal of already deleted orphan collections out of graph definition
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  tests/js/client/shell/api/general-graph.js
Labels: 3 Graph, 9 Ready to Merge

#16675 Fix for BTS-852.
  CHANGELOG
  arangod/RestHandler/RestUsersHandler.cpp
  tests/js/client/shell/api/users.js
Labels: 3 API, 3 UserManagement

#17295 [3.10][MDS-1016]: Grey out fields if distributedshardslike is set
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
Labels: 1 Bug, 3 UI

#17255 MDS-1019: Make search case-insensitive and allow search by name
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userManagementView.js
Labels: 1 Bug, 3 UI

#17290 Update the gtest module in CMakeLists.txt
  3rdParty/CMakeLists.txt
Labels: 3 Build, 3 - Testing

#17157 [CINFRA-485] Intermediate Commits
  arangod/Aql/StandaloneCalculation.cpp
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/ClusterEngine/ClusterTransactionState.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLogEntry.cpp
  arangod/Replication2/StateMachines/Document/DocumentLogEntry.h
  arangod/Replication2/StateMachines/Document/DocumentStateTransaction.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransaction.h
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxMethods.h
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.h
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.h
  arangod/RocksDBEngine/RocksDBTransactionMethods.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/RocksDBEngine/SimpleRocksDBTransactionState.cpp
  arangod/RocksDBEngine/SimpleRocksDBTransactionState.h
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  js/common/modules/@arangodb/testutils/replicated-state-helper.js
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/js/common/shell/shell-transactions.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra

#17334 log extra diagnosis data when duplicate endpoints are configured
  CHANGELOG
  arangod/Cluster/ServerState.cpp
Labels: 9 Ready to Merge

#17331 Added default parameter to checkView
  tests/IResearch/IResearchQueryCommon.h
Labels: 3 - Testing, 3 ArangoSearch

#16845 Bug fix/ee edges shards method
  arangod/Cluster/ClusterInfo.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingInfo.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
Labels: 1 Bug, 3 Graph, 3 Cluster, 9 Review Required

#17344 Added default parameter to checkView
  tests/IResearch/IResearchQueryCommon.h
Labels: 3 - Testing, 3 ArangoSearch

#17335 log extra diagnosis data when duplicate endpoints are configured
  CHANGELOG
  arangod/Cluster/ServerState.cpp
Labels: 9 Ready to Merge

#17338 [OPTIMIZER-2.0] REST endpoint to return initial plan
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/RestHandler/RestExplainHandler.cpp
  arangod/V8Server/v8-vocbase.cpp
Labels: 3 API, 3 Optimizer, optimizer-2.0

#17350 [SEARCH-406] Fix handling of removals in presence of primary sort
  3rdParty/iresearch/core/index/index_writer.cpp
  3rdParty/iresearch/core/index/segment_writer.cpp
  3rdParty/iresearch/core/index/segment_writer.hpp
  tests/IResearch/IResearchView-test.cpp
Labels: 3 ArangoSearch

#17347 BTS-1073: Fix revision ids in replication
  3rdParty/fuerte/src/H1Connection.cpp
  CHANGELOG
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_revision.md
  arangod/Cluster/ClusterMethods.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/utilities.cpp
  arangod/Replication/utilities.h
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestGraphHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/Transaction/Helpers.cpp
  arangod/V8Server/v8-util.cpp
  arangod/VocBase/Identifiers/RevisionId.cpp
  arangod/VocBase/Identifiers/RevisionId.h
  lib/Basics/HybridLogicalClock.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Containers/MerkleTree.cpp
  lib/Rest/HttpRequest.cpp
  lib/Rest/Version.cpp
  lib/Rest/Version.h
  tests/Basics/HybridLogicalClockTest.cpp
  tests/CMakeLists.txt
  tests/Containers/MerkleTreeTest.cpp
  tests/Rest/HttpRequestTest.cpp
  tests/js/server/replication/sync/replication-sync-malarkey.js
Labels: 1 Bug

#17351 [SEARCH-406] Fix handling of removals in presence of primary sort
  3rdParty/iresearch/core/index/index_writer.cpp
  3rdParty/iresearch/core/index/segment_writer.cpp
  3rdParty/iresearch/core/index/segment_writer.hpp
  tests/IResearch/IResearchView-test.cpp
Labels: 3 ArangoSearch

#17360 [SEARCH-407] [SEARCH-405] [SEARCH-404] Fix handling of ALL quantifier
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchKludge.h
  tests/IResearch/ExpressionFilterTest.cpp
  tests/IResearch/GeoDistanceFilterTest.cpp
  tests/IResearch/GeoFilterTest.cpp
  tests/IResearch/IResearchFilterFunctionTest.cpp
  tests/IResearch/IResearchFilterNestedTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/IResearch/common.cpp
Labels: 3 ArangoSearch

#17340 Fixed BTS-852
  CHANGELOG
  arangod/RestHandler/RestUsersHandler.cpp
  tests/js/client/shell/api/users.js
Labels: 3 API, 3 UserManagement

#17341 Fix for BTS-852
  CHANGELOG
  arangod/RestHandler/RestUsersHandler.cpp
  tests/js/client/shell/api/users.js
Labels: 3 API, 3 UserManagement

#17364 Adding extra log info
  tests/js/client/shell/transaction/shell-transaction-cluster.js
Labels: cinfra

#17332 [PREGEL] Combine prepare and run superstep
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/ComputingState.h
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/Messaging/WorkerMessages.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel

#17368 [testing] re-shuffle testcases
  tests/test-definitions.txt
Labels: 3 - Testing

#17365 [testing] when running interactive bail out quick on error
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing

#17237 JS API: Fix undefined reference and logic of collection.iterate()
  js/common/modules/@arangodb/arango-collection-common.js
Labels: 3 JS API

#17386 ErrorT
  lib/Basics/ErrorT.h
  lib/Inspection/VPackWithStatusT.h
  tests/Basics/InspectionTest.cpp
  tests/CMakeLists.txt
  tests/Errors/CMakeLists.txt
  tests/Errors/ErrorTTest.cpp
  tests/Errors/main.cpp
Labels: cla-signed

#17348 [BTS-941] EnterpriseGraph edge shards() method bug-fix
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingInfo.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
Labels: 3 Graph, 3 Cluster, 9 Ready to Merge

#17366 [PREGEL] Wait until Worker received all messages that were sent to it
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/ComputingState.h
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/Messaging/ConductorMessages.h
  arangod/Pregel/Messaging/WorkerMessages.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/OutgoingCache.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel, cla-signed

#17339 [PREGEL] Separate sending and receiving messages to run gss
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/ComputingState.h
  arangod/Pregel/Conductor/States/LoadingState.cpp
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Worker/ConductorApi.cpp
  arangod/Pregel/Worker/ConductorApi.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel, cla-signed

#17392 Separate sending and receiving messages when cleaning up
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/CanceledState.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/Conductor/States/StoringState.h
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel, cla-signed

#17404 [CINFRA-586] Leader Change Test Fix
  js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
Labels: cinfra, cla-signed

#17403 [CINFRA-588] Document State vocbase race
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
Labels: cinfra, cla-signed

#17324 Documentation/api-fixes-2022-10-06
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
  Documentation/DocuBlocks/Rest/Documents/delete_remove_document.md
  Documentation/DocuBlocks/Rest/Documents/patch_update_document.md
  Documentation/DocuBlocks/Rest/Documents/patch_update_multiple_documents.md
  Documentation/DocuBlocks/Rest/Documents/post_create_document.md
  Documentation/DocuBlocks/Rest/Documents/post_create_multiple_document.md
  Documentation/DocuBlocks/Rest/Documents/put_replace_document.md
  Documentation/DocuBlocks/Rest/Documents/put_replace_multiple_documents.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_edge_definition_add_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_edge_definition_modify_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_vertex_collection_add_http_examples.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_persistent.md
  Documentation/DocuBlocks/Rest/Pregel/1_struct.md
  arangod/Replication/DatabaseInitialSyncer.cpp
  js/client/modules/@arangodb/arango-collection.js
Labels: 3 Documentation, 3 API, cla-signed

#17376 Documentation-3.10/api-fixes-2022-10-06
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
  Documentation/DocuBlocks/Rest/Documents/delete_remove_document.md
  Documentation/DocuBlocks/Rest/Documents/patch_update_document.md
  Documentation/DocuBlocks/Rest/Documents/patch_update_multiple_documents.md
  Documentation/DocuBlocks/Rest/Documents/post_create_document.md
  Documentation/DocuBlocks/Rest/Documents/post_create_multiple_document.md
  Documentation/DocuBlocks/Rest/Documents/put_replace_document.md
  Documentation/DocuBlocks/Rest/Documents/put_replace_multiple_documents.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_edge_definition_add_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_edge_definition_modify_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_vertex_collection_add_http_examples.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_persistent.md
  Documentation/DocuBlocks/Rest/Pregel/1_struct.md
  arangod/Replication/DatabaseInitialSyncer.cpp
  js/client/modules/@arangodb/arango-collection.js
Labels: 3 Documentation, 3 API, cla-signed

#17371 Introduce ErrorT and improved version of (de)serializeWithStatus
  lib/Basics/ErrorT.h
  lib/Inspection/VPackWithErrorT.h
  tests/Basics/InspectionTest.cpp
  tests/CMakeLists.txt
  tests/Errors/CMakeLists.txt
  tests/Errors/ErrorTTest.cpp
  tests/Errors/main.cpp
Labels: cla-signed

#17422 Fixes and add test for search-alias view
  arangod/Aql/IResearchViewNode.cpp
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.cpp
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchLinkMeta.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/Search.cpp
  tests/js/server/aql/aql-arangosearch-constrained-sort-optimization.inc
  tests/js/server/aql/aql-arangosearch-constrained-sort-optimization.js
  tests/js/server/aql/aql-arangosearch-count-optimization.js
  tests/js/server/aql/aql-arangosearch-filter-optimization.js
  tests/js/server/aql/aql-geo.js
  tests/js/server/aql/aql-iresearch-view-executor-regression.js
  tests/js/server/aql/aql-optimizer-rule-collect-in-cluster.js
  tests/js/server/aql/aql-optimizer-rule-inline-subqueries.js
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-primary-sort.inc
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-primary-sort.js
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-stored-values.inc
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch-stored-values.js
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization-arangosearch.js
  tests/js/server/aql/aql-optimizer-rule-no-document-materialization-arangosearch.js
  tests/js/server/aql/aql-optimizer-rule-views-sorted-indexes.inc
  tests/js/server/aql/aql-optimizer-rule-views-sorted-indexes.js
  tests/js/server/aql/aql-options-verification.js
  tests/js/server/aql/aql-profiler-noncluster.js
  tests/js/server/aql/aql-query-cache-noncluster.js
  tests/js/server/aql/aql-shadowrow-block-return-regression.js
  tests/js/server/aql/aql-skipping.js
  tests/js/server/aql/aql-view-arangosearch-server.js
Labels: cla-signed, Backport Needed

#17421 Solve excessive memory consumption in multi-iterators - BTS-1088
  CHANGELOG
  arangod/Indexes/IndexIterator.cpp
  arangod/Indexes/IndexIterator.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
Labels: cla-signed

#17397 remove unused URL parameter "useEnvelope"
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Restore/RestoreFeature.h
Labels: cla-signed

#17416 [PREGEL]: Add cancel function to state machine
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/States/CanceledState.h
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/ComputingState.h
  arangod/Pregel/Conductor/States/DoneState.cpp
  arangod/Pregel/Conductor/States/DoneState.h
  arangod/Pregel/Conductor/States/FatalErrorState.cpp
  arangod/Pregel/Conductor/States/FatalErrorState.h
  arangod/Pregel/Conductor/States/InitialState.h
  arangod/Pregel/Conductor/States/LoadingState.cpp
  arangod/Pregel/Conductor/States/LoadingState.h
  arangod/Pregel/Conductor/States/State.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/Conductor/States/StoringState.h
Labels: 3 Pregel, cla-signed

#17418 [PREGEL] Make each state own its specific worker api
  arangod/Pregel/Conductor/CMakeLists.txt
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/States/CanceledState.cpp
  arangod/Pregel/Conductor/States/CanceledState.h
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/ComputingState.h
  arangod/Pregel/Conductor/States/DoneState.cpp
  arangod/Pregel/Conductor/States/DoneState.h
  arangod/Pregel/Conductor/States/FatalErrorState.cpp
  arangod/Pregel/Conductor/States/FatalErrorState.h
  arangod/Pregel/Conductor/States/InitialState.cpp
  arangod/Pregel/Conductor/States/InitialState.h
  arangod/Pregel/Conductor/States/LoadingState.cpp
  arangod/Pregel/Conductor/States/LoadingState.h
  arangod/Pregel/Conductor/States/StoringState.cpp
  arangod/Pregel/Conductor/States/StoringState.h
  arangod/Pregel/Conductor/WorkerApi.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/Messaging/WorkerMessages.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/WorkerInterface.h
Labels: 3 Pregel, cla-signed

#17428 [PREGEL] Bugfix: Lock future creation
  arangod/Pregel/Conductor/States/ComputingState.cpp
  arangod/Pregel/Conductor/States/LoadingState.cpp
  arangod/Pregel/Conductor/WorkerApi.h
  arangod/Pregel/Worker/Worker.cpp
Labels: 3 Pregel, cla-signed

#17305 LSH community tests
  tests/js/common/aql/aql-arangosearch-lsh-community.js
  tests/js/common/test-data/search/docs/generate_lsh_dataset.py
  tests/js/common/test-data/search/docs/lsh_dataset.json
Labels: 3 - Testing, 3 ArangoSearch, cla-signed

#17432 Backport for 'LSH community tests'
  tests/js/common/aql/aql-arangosearch-lsh-community.js
  tests/js/common/test-data/search/docs/generate_lsh_dataset.py
  tests/js/common/test-data/search/docs/lsh_dataset.json
Labels: 3 - Testing, 3 ArangoSearch, cla-signed

#17437 Fix license headers for files
  arangod/IResearch/IResearchDataStoreMeta.h
  tests/IResearch/IResearchFilterMinHashMatchTest.cpp
  tests/IResearch/IResearchFilterNestedTest.cpp
  tests/js/common/aql/aql-arangosearch-offset-info-community.js
  utils/generateExamples.py
Labels: 3 License, cla-signed

#17429 Enable "_id" indexing for search/filter
  arangod/Indexes/IndexFactory.cpp
  tests/js/server/recovery/view-search-alias-populate.js
Labels: cla-signed, Backport Needed

#17441 [PREGEL] Check if pregel is finished with helper function
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
  tests/js/common/shell/shell-pregel-basics-example.js
  tests/js/common/shell/shell-pregel-components.js
  tests/js/common/shell/shell-pregel-multicollection-edgecol.js
  tests/js/common/shell/shell-pregel-random.js
  tests/js/common/shell/shell-pregel-start-cluster.js
Labels: 3 Pregel, cla-signed

#17442 BTS-1097: potentially fix assertion on mac
  arangod/RocksDBEngine/RocksDBChecksumEnv.cpp
Labels: cla-signed

#17425 [BTS-1085] Use a different algorithm for shard creation.
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
Labels: cinfra, cla-signed

#17431 Prevent excessive memory usage in multi iterator and better logging for high mem queries
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryContext.h
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryList.h
  arangod/Aql/QueryProfile.h
  arangod/Aql/QueryString.cpp
  arangod/Graph/BaseOptions.cpp
  arangod/Graph/BaseOptions.h
  arangod/Indexes/IndexIterator.cpp
  arangod/Indexes/IndexIterator.h
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/client/server_parameters/log-queries-failed-and-memory.js
Labels: cla-signed

#17385 avoid static init order fiasco (#17114)
  lib/ProgramOptions/Parameters.cpp
Labels: ASan

#17402 Coordinator commit for streaming transactions - BTS-1086
  CHANGELOG
  arangod/Cluster/ClusterTrxMethods.cpp
Labels: 3 Cluster, 3 Transaction, cla-signed

#17427 [CINFRA-589] Fix race when committing trx in replication2
  arangod/RocksDBEngine/Methods/RocksDBReadOnlyBaseMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBReadOnlyBaseMethods.h
  arangod/RocksDBEngine/Methods/RocksDBSingleOperationTrxMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBSingleOperationTrxMethods.h
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.h
  arangod/RocksDBEngine/Methods/RocksDBTrxMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxMethods.h
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.h
  arangod/RocksDBEngine/RocksDBTransactionMethods.h
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.h
  arangod/RocksDBEngine/SimpleRocksDBTransactionState.cpp
  arangod/RocksDBEngine/SimpleRocksDBTransactionState.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
Labels: cinfra, cla-signed

#17444 Stop dropped databases as well
  arangod/RestServer/DatabaseFeature.cpp
Labels: 1 Bug, cinfra, cla-signed

#17456 Add views to chaos test
  arangod/IResearch/Search.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: cla-signed, Backport Needed

#17459 Add an explicit compact API call for logs.
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedLog/ILogInterfaces.h
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/LogUnconfiguredParticipant.cpp
  arangod/Replication2/ReplicatedLog/LogUnconfiguredParticipant.h
  arangod/RestHandler/RestLogHandler.cpp
  arangod/RestHandler/RestLogHandler.h
  arangod/V8Server/v8-replicated-logs.cpp
  js/client/modules/@arangodb/replicated-logs.js
  tests/Replication2/Mocks/AsyncFollower.cpp
  tests/Replication2/Mocks/AsyncFollower.h
  tests/Replication2/Mocks/AsyncLeader.cpp
  tests/Replication2/Mocks/AsyncLeader.h
  tests/Replication2/Mocks/FakeFollower.h
  tests/Replication2/Mocks/FakeLeader.h
  tests/Replication2/Mocks/FakeReplicatedLog.h
  tests/js/common/shell/shell-replicated-logs-cluster.js
Labels: cinfra, cla-signed

#16687 [BUILD] Add CMakePresets.json
  CMakePresets.json
Labels: cla-signed

#17453 Expose assert() function in @EXAMPLE_ARANGOSH_OUTPUT (JS API) examples
  Documentation/Scripts/exampleHeader.js
  utils/generateExamples.py
Labels: cla-signed

#17452 Expose assert() function in @EXAMPLE_ARANGOSH_OUTPUT (JS API) examples
  Documentation/Scripts/exampleHeader.js
  utils/generateExamples.py
Labels: 3 Documentation, cla-signed

#17448 [3.10][BTS-1085] create collection shard balance
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
Labels: cinfra, cla-signed

#17447 [3.9][BTS-1085] create collection shard balance
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
Labels: cinfra, cla-signed, 3.9

#17466 SEARCH-418 Fix _id for primarySort
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/Transaction/Helpers.cpp
  arangod/Transaction/Methods.cpp
  tests/IResearch/IResearchDocumentTest.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: cla-signed, Backport Needed

#17465 Fixed issue #17394
  CHANGELOG
  arangod/Aql/AttributeNamePath.cpp
  arangod/Aql/AttributeNamePath.h
  arangod/Aql/Projections.cpp
  arangod/Aql/Projections.h
  arangod/Indexes/Index.cpp
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  tests/Aql/ProjectionsTest.cpp
  tests/js/common/shell/shell-index-stored-values.js
  tests/js/server/aql/aql-filter-projections.js
  tests/js/server/aql/aql-projections.js
Labels: cla-signed

#17426 [BTS-209] Added interpretation of payload to not treat everyone as plain text
  CHANGELOG
  arangod/RestHandler/RestAdminExecuteHandler.cpp
  lib/Rest/HttpRequest.cpp
  tests/js/client/shell/shell-admin-execute-formats.js
  tests/js/client/shell/shell-vpack.js
Labels: cla-signed

#17417 [OPTIMIZER2] Created a REST handler to execute AQL plan JSONs.
  arangod/Aql/Optimizer2/Plan/PlanRPCHandler.h
  arangod/Aql/Optimizer2/Plan/QueryPostBody.h
  arangod/Aql/Optimizer2/Plan/ResultPlan.h
  arangod/Aql/Optimizer2/Plan/VerbosePlan.h
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestCursorHandler.h
  arangod/RestHandler/RestExplainHandler.cpp
  arangod/RestHandler/RestPlanHandler.cpp
  arangod/RestHandler/RestPlanHandler.h
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  arangod/V8Server/v8-vocbase.cpp
  arangod/arangoserver.cmake
  lib/Rest/GeneralRequest.h
  tests/Optimizer2/CMakeLists.txt
  tests/Optimizer2/Plan/CMakeLists.txt
  tests/Optimizer2/Plan/QueryPostBodyTest.cpp
  tests/Optimizer2/Plan/ResultPlanTest.cpp
  tests/Optimizer2/Plan/VerbosePlanTest.cpp
Labels: 3 API, cla-signed, optimizer-2.0

#17410 setUpAll/tearDownAll for performance reasons (#17322)
  tests/js/client/shell/shell-iterators-read-standalone.js
  tests/js/client/shell/shell-iterators-read-transaction.js
  tests/js/client/shell/shell-iterators-write-standalane.js
  tests/js/client/shell/shell-iterators-write-transaction.js
  tests/js/client/shell/shell-iterators.inc
Labels: 3 - Testing, cla-signed

#17450 [CINFRA-587] Document State Compaction
  arangod/Replication2/Methods.cpp
  arangod/Replication2/StateMachines/Document/ActiveTransactionsQueue.cpp
  arangod/Replication2/StateMachines/Document/ActiveTransactionsQueue.h
  arangod/Replication2/StateMachines/Document/CMakeLists.txt
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMethods.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateNetworkHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateNetworkHandler.h
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.h
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.h
  arangod/V8Server/v8-replicated-logs.cpp
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/js/client/shell/transaction/shell-transaction-cluster.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#17373 improve estimate for EnumerateCollectionNode
  CHANGELOG
  arangod/Aql/ExecutionNode.cpp
  tests/js/server/aql/aql-optimizer-rule-remove-sort-rand-limit.js
Labels: 3 AQL, 3 Optimizer, cla-signed

#17387 Improve query logging
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryContext.h
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryList.h
  arangod/Aql/QueryProfile.h
  arangod/Aql/QueryString.cpp
  arangod/Graph/BaseOptions.cpp
  arangod/Graph/BaseOptions.h
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
  tests/js/client/server_parameters/log-queries-failed-and-memory.js
  tests/js/client/server_parameters/log-structured-params.js
Labels: cla-signed

#17395 [testing] re-shuffle testcases
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#17396 [testing] re-shuffle testcases
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#17393 [testing] re-shuffle testcases
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed
