Repository arangodb/arangodb, pull requests merged in 2023-05, with the labels that each got.

#18792 Bug fix/test failure backup dump collections not ready
  tests/js/server/dump/dump-test.inc
Labels: cla-signed

#18784 FE-254: bugfix - filter out empty storedValues for persistent index
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1b901450.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1b901450.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1b901450.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreatePersistentIndex.ts
Labels: 3 UI, cla-signed

#18803 feature-3.11/FE-254: bugfix - filter out empty storedValues for persistent index
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1b901450.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1b901450.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1b901450.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreatePersistentIndex.ts
Labels: 3 UI, cla-signed

#18796 FE-253: bugfix - validate JSON, show errors & disable save when error
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.6c29ade0.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.6c29ade0.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.6c29ade0.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/components/jsonEditor/JSONErrors.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexFormJSONEditor.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/EditEdgeModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/EditNodeModal.tsx
Labels: 3 UI, cla-signed

#18804 feature-3.11/FE-253: bugfix - validate JSON, show errors & disable save when error
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.6c29ade0.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.6c29ade0.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.6c29ade0.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ac441d53.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/components/jsonEditor/JSONErrors.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexFormJSONEditor.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/EditEdgeModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/EditNodeModal.tsx
Labels: 3 UI, cla-signed

#18798 Fix broken test
  tests/js/client/shell/multi/shell-numberof-servers-cluster.js
Labels: cla-signed, 3.11-Stabilization

#18799 Fix broken test (setting desired number of servers)
  CHANGELOG
  tests/js/client/shell/multi/shell-numberof-servers-cluster.js
Labels: cla-signed, 3.11-Stabilization

#18820 Fix arangodb_replication2_replicated_log_inserts_bytes metric.
  arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp
Labels: cinfra, cla-signed

#18829 Increase chaos client timeout
  js/client/modules/@arangodb/test-helper.js
Labels: cla-signed, Backport Needed, 3.11-Stabilization

#18641 [GORDO-1617] Get data out of actors safely
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/REST/RestControlPregelHandler.cpp
  arangod/Pregel/REST/RestPregelHandler.cpp
  arangod/Pregel/ResultActor.h
  arangod/Pregel/StatusActor.h
  arangod/V8Server/v8-pregel.cpp
  tests/Pregel/Actor/Actors/EgressActor.h
  tests/Pregel/Actor/CMakeLists.txt
  tests/Pregel/Actor/EgressActorTest.cpp
Labels: 3 Pregel, cla-signed

#18825 [PREGEL] Fix even more actor stuff
  arangod/Pregel/Conductor/ExecutionStates/CanceledState.cpp
  arangod/Pregel/Conductor/ExecutionStates/ComputingState.cpp
  arangod/Pregel/Conductor/ExecutionStates/ComputingState.h
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.cpp
  arangod/Pregel/Conductor/ExecutionStates/LoadingState.cpp
  arangod/Pregel/Conductor/Handler.h
  arangod/Pregel/Conductor/Messages.h
  arangod/Pregel/Conductor/State.h
  arangod/Pregel/GraphStore/GraphVPackBuilderStorer.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/REST/RestControlPregelHandler.cpp
  arangod/Pregel/REST/RestPregelHandler.cpp
  arangod/Pregel/ResultActor.h
  arangod/Pregel/SenderMessage.h
  arangod/Pregel/Statistics.h
  arangod/Pregel/StatusActor.h
  arangod/Pregel/StatusMessages.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/State.h
  arangod/Pregel/Worker/VertexProcessor.cpp
  arangod/Pregel/Worker/VertexProcessor.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/V8Server/v8-pregel.cpp
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/client/load-balancing/load-balancing-pregel-auth-cluster.js
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
  tests/js/common/shell/shell-pregel-basics-example.js
  tests/js/common/shell/shell-pregel-random.js
  tests/js/common/shell/shell-pregel-start-cluster.js
Labels: 3 Pregel, cla-signed

#18826 Bug fix 3.11/test failure backup dump collections not ready
  tests/js/server/dump/dump-test.inc
Labels: 3 ImportExport, 3 - Testing, cla-signed

#18819 Fix locally outdated information from Current
  CHANGELOG
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/Maintenance.cpp
  tests/js/server/resilience/move/moving-shards-cluster.js
Labels: cla-signed, 3.9

#18818 Fix locally outdated information from Current
  CHANGELOG
  arangod/Cluster/FollowerInfo.h
  arangod/Cluster/Maintenance.cpp
  tests/js/server/resilience/move/moving-shards-cluster.js
Labels: cla-signed, 3.10

#18800 Fix broken test (setting desired number of servers)
  CHANGELOG
  tests/js/client/shell/shell-numberof-servers-cluster.js
Labels: cla-signed

#18615 [GORDO-1556] Metrics Actor
  arangod/Pregel/Conductor/ExecutionStates/AQLResultsAvailableState.cpp
  arangod/Pregel/Conductor/ExecutionStates/AQLResultsAvailableState.h
  arangod/Pregel/Conductor/ExecutionStates/CanceledState.h
  arangod/Pregel/Conductor/ExecutionStates/ComputingState.cpp
  arangod/Pregel/Conductor/ExecutionStates/ComputingState.h
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.cpp
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.h
  arangod/Pregel/Conductor/ExecutionStates/DoneState.cpp
  arangod/Pregel/Conductor/ExecutionStates/DoneState.h
  arangod/Pregel/Conductor/ExecutionStates/FatalErrorState.h
  arangod/Pregel/Conductor/ExecutionStates/InitialState.cpp
  arangod/Pregel/Conductor/ExecutionStates/InitialState.h
  arangod/Pregel/Conductor/ExecutionStates/LoadingState.cpp
  arangod/Pregel/Conductor/ExecutionStates/LoadingState.h
  arangod/Pregel/Conductor/ExecutionStates/ProduceAQLResultsState.cpp
  arangod/Pregel/Conductor/ExecutionStates/ProduceAQLResultsState.h
  arangod/Pregel/Conductor/ExecutionStates/State.h
  arangod/Pregel/Conductor/ExecutionStates/StoringState.cpp
  arangod/Pregel/Conductor/ExecutionStates/StoringState.h
  arangod/Pregel/Conductor/Handler.h
  arangod/Pregel/Conductor/State.h
  arangod/Pregel/MetricsActor.h
  arangod/Pregel/MetricsMessages.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelMetrics.h
  arangod/Pregel/SpawnActor.h
  arangod/Pregel/SpawnMessages.h
  arangod/Pregel/StatusActor.h
  arangod/Pregel/StatusMessages.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/State.h
  tests/Pregel/ConductorStateTest.cpp
Labels: 3 Pregel, cla-signed

#18808 FE-251: Prohibit multiple expansions of the same node
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.92b16c61.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.92b16c61.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.92b16c61.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphNetwork/NodeRightClickMenu.tsx
Labels: 1 Bug, 3 UI, cla-signed

#18831 Bug-Fix-3.11/FE-251-prohibit-multiple-expansions backport
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.92b16c61.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.92b16c61.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.92b16c61.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphNetwork/NodeRightClickMenu.tsx
Labels: 1 Bug, 3 UI, cla-signed

#18840 Fix broken test (abort long running)
  CHANGELOG
  tests/js/client/shell/abort-long-running-operations-noncluster.js
Labels: cla-signed

#18801 Fix broken test (setting desired number of servers)
  CHANGELOG
  tests/js/client/shell/shell-numberof-servers-cluster.js
Labels: 3 - Testing, cla-signed

#18822 testing: fix filtering; implement skipN to aid debugging of broken tests
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
Labels: 3 - Testing, cla-signed

#18821 Feature 3.10/skip tests
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: cla-signed

#18761 FE-22: Don't display collection content by default when clicking on a collection in the Web UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsItemView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c1bd9b9e.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c1bd9b9e.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c1bd9b9e.js.gz
Labels: 3 UI, cla-signed

#18838 Feature-3.11/FE-22-Don't-display-collection-content-by-default-when-clicking-on-a-collection-in-the-WebUI backport
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsItemView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b336c966.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c1bd9b9e.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c1bd9b9e.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c1bd9b9e.js.gz
Labels: 3 UI, cla-signed

#18843 Remove unused cmake include
  cmake/packages/client/nsis.txt
Labels: 4 Windows, 3 Packaging, cla-signed

#18805 fix value of `internal.extendedNames` after restart
  arangod/RestServer/FrontendFeature.cpp
  arangod/V8Server/V8DealerFeature.cpp
  arangod/V8Server/v8-vocbase.cpp
Labels: cla-signed

#18415 QA-378: testing: reduce test load on MAC
  tests/test-definitions.txt
Labels: cla-signed

#18778 Bug fix/handle setup test errors
  client-tools/Shell/V8ShellFeature.cpp
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  tests/js/server/recovery/view-arangosearch-link-populate-crash-after-release.js
  tests/js/server/recovery/view-arangosearch-link-populate-no-callbacks.js
  tests/js/server/recovery/view-arangosearch-link-populate-no-release.js
  tests/js/server/recovery/view-arangosearch-link-populate-no-sync.js
  tests/js/server/recovery/view-arangosearch-link-populate-transaction-multiple-batches-no-flushthread.js
  tests/js/server/recovery/view-arangosearch-link-populate-transaction-no-flushthread.js
  tests/js/server/recovery/view-arangosearch-link-populate-transaction-single-batch-no-flushthread.js
  tests/js/server/recovery/view-arangosearch-link-populate-transaction.js
  tests/js/server/recovery/view-search-alias-populate-crash-after-release.js
  tests/js/server/recovery/view-search-alias-populate-no-callbacks.js
  tests/js/server/recovery/view-search-alias-populate-no-release.js
  tests/js/server/recovery/view-search-alias-populate-no-sync.js
  tests/js/server/recovery/view-search-alias-populate-transaction-multiple-batches-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction-single-batch-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction.js
Labels: 3 - Testing, cla-signed, 3.11-Stabilization

#18839 Fix broken test (abort long running)
  tests/js/client/shell/abort-long-running-operations-noncluster.js
Labels: cla-signed

#18848 Bug fix/handle setup test errors (#18778)
  client-tools/Shell/V8ShellFeature.cpp
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  tests/js/server/recovery/view-arangosearch-link-populate-crash-after-release.js
  tests/js/server/recovery/view-arangosearch-link-populate-no-callbacks.js
  tests/js/server/recovery/view-arangosearch-link-populate-no-release.js
  tests/js/server/recovery/view-arangosearch-link-populate-no-sync.js
  tests/js/server/recovery/view-arangosearch-link-populate-transaction-multiple-batches-no-flushthread.js
  tests/js/server/recovery/view-arangosearch-link-populate-transaction-no-flushthread.js
  tests/js/server/recovery/view-arangosearch-link-populate-transaction-single-batch-no-flushthread.js
  tests/js/server/recovery/view-arangosearch-link-populate-transaction.js
  tests/js/server/recovery/view-search-alias-populate-crash-after-release.js
  tests/js/server/recovery/view-search-alias-populate-no-callbacks.js
  tests/js/server/recovery/view-search-alias-populate-no-release.js
  tests/js/server/recovery/view-search-alias-populate-no-sync.js
  tests/js/server/recovery/view-search-alias-populate-transaction-multiple-batches-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction-single-batch-no-flushthread.js
  tests/js/server/recovery/view-search-alias-populate-transaction.js
Labels: 3 - Testing, cla-signed

#18590 [testing]: renice the debugger so it doesn't steal resources from other parallel testruns
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/common/bootstrap/modules/internal.js
  lib/Basics/process-utils.cpp
  lib/Basics/process-utils.h
  lib/V8/v8-utils.cpp
Labels: 3 - Testing, cla-signed

#18856 Fix SEARCH-466 3.9
  CHANGELOG
  arangod/IResearch/IResearchViewCoordinator.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl.js
Labels: 3 ArangoSearch, cla-signed

#18396 [3.9] [BTS-1148] Fix DBServer Race in running Query abort on DBServer
  CHANGELOG
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/RestAqlHandler.cpp
  lib/Futures/Promise.h
  lib/Futures/SharedState.h
  lib/Futures/Try.h
  tests/js/common/shell/test-kill-queries.js
Labels: cla-signed

#18834 reduce memory usage for incremental sync replication
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  tests/js/server/replication/sync/replication-sync.js
Labels: cla-signed

#18842 [CINFRA-738] Disable replication 2 in 3.11
  js/client/modules/@arangodb/testsuites/replication2.js
  lib/Basics/FeatureFlags.cpp
  tests/js/common/shell/shell-replicated-logs-cluster.js_DISABLED
  tests/js/server/resilience/move/moving-shards-cluster-data-R2.js_DISABLED
  tests/js/server/resilience/sharddist/shard-distribution.js
  tests/test-definitions.txt
Labels: cinfra, cla-signed

#18859 change error message for document not found error
  lib/Basics/RocksDBUtils.cpp
  tests/js/common/shell/shell-error-messages.js
Labels: cla-signed

#18860 change error message for document not found error
  lib/Basics/RocksDBUtils.cpp
  tests/js/common/shell/shell-error-messages.js
Labels: cla-signed

#18845 FE-243: add support for geo_s2 analyzer
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.33a65132.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.33a65132.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.33a65132.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c1bd9b9e.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c1bd9b9e.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c1bd9b9e.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/constants.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/GeoS2Form.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/PipelineForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/helpers.tsx
Labels: 3 UI, cla-signed

#18846 feature-3.11/FE-243: add support for geo_s2 analyzer
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.ea26cf36.css.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.467fd839.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.467fd839.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.467fd839.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ed36d222.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ed36d222.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ed36d222.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.9512fedafa8e56b22d68.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.beab3f58283dd9683614.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.916656a297b1a9fa698b.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.abd255e8d4a57cfa076a.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.8d11d1e159ab0e14c0e6.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.9c9c164e699d486b5abf.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.81dc9b21d2ced318e9ae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.bcf2ba9ef2bd549116a9.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-dark.994d1553f409200f5901.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-icon.35807d6e11925bd44973.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb.609cd935d9d34dab5e6b.eot.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/favicon.909457142f6be9dae418.ico.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.ed6298903ae1554c7f3e.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.f0af1680f082547a7aae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/jsoneditor-icons.ffbb30248a6fc9adfc7f.svg.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/constants.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/GeoS2Form.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/PipelineForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/helpers.tsx
Labels: 3 UI, cla-signed

#18866 Increase test timeout for pregel garbage collection
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
Labels: 3 Pregel, cla-signed

#18833 reduce memory usage for incremental sync replication
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  tests/js/server/replication/sync/replication-sync.js
Labels: cla-signed

#18857 Fix chaos timeout
  js/client/modules/@arangodb/test-helper.js
Labels: cla-signed

#18873 add support for a special case of 3.9.2 upgrades
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/SynchronizeShard.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/DatabaseInitialSyncer.h
  arangod/Replication/DatabaseTailingSyncer.cpp
  arangod/Replication/DatabaseTailingSyncer.h
  arangod/Replication/TailingSyncer.h
  arangod/Replication/utilities.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/Transaction/Methods.cpp
  tests/js/client/shell/shell-replication-drop-follower-shard.js
Labels: cla-signed

#18871 Disable version check in scripts/startLocalCluster
  scripts/startLocalCluster.sh
Labels: cla-signed

#18870 BTS-1347: add debug logging to arangosh connect code
  client-tools/Shell/V8ClientConnection.cpp
Labels: cla-signed

#18868 BTS-1347: add debug logging to arangosh connect code
  client-tools/Shell/V8ClientConnection.cpp
Labels: 3 - Testing, cla-signed

#18874 Bug fix 3.9/add debug logging to arangosh connect code
  arangosh/Shell/V8ClientConnection.cpp
Labels: cla-signed

#18861 [BTS-1343]
  CHANGELOG
  client-tools/Shell/ClientFeature.cpp
  client-tools/Shell/ClientFeature.h
  client-tools/Utils/ClientManager.cpp
Labels: cla-signed

#18880 [CINFRA-707] Removing PrototypeState and FailureOracle
  arangod/Cluster/FailureOracle.h
  arangod/Cluster/FailureOracleFeature.cpp
  arangod/Cluster/FailureOracleFeature.h
  arangod/Cluster/UpdateReplicatedLogAction.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/Replication2/CMakeLists.txt
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/Algorithms.h
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/StateMachines/CMakeLists.txt
  arangod/Replication2/StateMachines/Prototype/CMakeLists.txt
  arangod/Replication2/StateMachines/Prototype/PrototypeCore.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeCore.h
  arangod/Replication2/StateMachines/Prototype/PrototypeFollowerState.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeFollowerState.h
  arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeLeaderState.h
  arangod/Replication2/StateMachines/Prototype/PrototypeLogEntry.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeLogEntry.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachineFeature.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachineFeature.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMethods.h
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminClusterHandler.h
  arangod/RestHandler/RestPrototypeStateHandler.cpp
  arangod/RestHandler/RestPrototypeStateHandler.h
  arangod/RestServer/arangod.h
  arangod/RestServer/arangod_includes.h
  arangod/V8Server/CMakeLists.txt
  arangod/V8Server/v8-externals.h
  arangod/V8Server/v8-prototype-state.h
  arangod/V8Server/v8-prototype-states.cpp
  arangod/V8Server/v8-vocbase.cpp
  arangod/arangoserver.cmake
  js/client/modules/@arangodb/arango-database.js
  js/client/modules/@arangodb/arango-prototype-state.js
  js/client/modules/@arangodb/index.js
  js/common/modules/@arangodb/arango-prototype-state-common.js
  js/server/bootstrap/modules/internal.js
  js/server/modules/@arangodb/arango-prototype-state.js
  js/server/modules/@arangodb/index.js
  lib/V8/v8-globals.h
  tests/Replication2/CMakeLists.txt
  tests/Replication2/Mocks/FakeFailureOracle.cpp
  tests/Replication2/Mocks/FakeFailureOracle.h
  tests/Replication2/Mocks/FakeReplicatedLog.cpp
  tests/Replication2/Mocks/FakeReplicatedLog.h
  tests/Replication2/ReplicatedState/PrototypeConcurrencyTest.cpp
  tests/Replication2/ReplicatedState/PrototypeStateMachineTest.cpp
  tests/js/common/shell/shell-prototype-state-cluster.js_DISABLED
  tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
  tests/js/server/replication2/replication2-regression.js
  tests/js/server/resilience/failover/resilience-failure-oracle.js
Labels: cinfra, cla-signed

#18881 Fix handling of premature follower trx abortion
  CHANGELOG
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
  tests/js/client/shell/transaction/shell-transaction-dropped-followers-cluster.js
  tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
Labels: cla-signed

#18691 Fix for Foxx Service Installation
  CHANGELOG
  arangod/RestHandler/RestUploadHandler.cpp
  js/apps/system/_admin/aardvark/APP/foxxes.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installUploadServiceView.js
  js/server/modules/@arangodb/foxx/manager.js
  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
Labels: 1 Bug, cla-signed

#18887 [3.11] Fix handling of premature follower trx abortion
  CHANGELOG
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
  tests/js/client/shell/transaction/shell-transaction-dropped-followers-cluster.js
  tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
Labels: 9 Ready to Merge, cla-signed

#18884 [PREGEL] Fix performance regression (3.11 backport)
  arangod/Pregel/Worker/VertexProcessor.h
Labels: 3 Pregel, cla-signed

#18888 close the air gap
  js/client/modules/@arangodb/air/access-data.js
  js/client/modules/@arangodb/air/accumulators.js
  js/client/modules/@arangodb/air/global-accumulator-test.js
  js/client/modules/@arangodb/air/js-syntax.js
  js/client/modules/@arangodb/air/pagerank.js
  js/client/modules/@arangodb/air/pregel-example-graphs.js
  js/client/modules/@arangodb/air/propagation-demo.js
  js/client/modules/@arangodb/air/random-walk.js
  js/client/modules/@arangodb/air/sexpression-syntax.js
  js/client/modules/@arangodb/air/single-source-shortest-paths.js
  js/client/modules/@arangodb/air/strongly-connected-components.js
  js/client/modules/@arangodb/air/test-helpers.js
  js/client/modules/@arangodb/air/vertex-degrees-sexpression.js
  js/client/modules/@arangodb/air/vertex-degrees.js
Labels: cla-signed

#18898 add try...catch for debugging
  js/common/bootstrap/modules.js
Labels: cla-signed

#18905 fix typos
  arangod/StorageEngine/TransactionState.cpp
  arangod/Transaction/Manager.h
Labels: cla-signed

#18903 add debug output for agency segfault
  arangod/Agency/State.cpp
Labels: cla-signed

#18895 Better cleanup & observability for in-memory cache
  CHANGELOG
  Documentation/Metrics/rocksdb_cache_peak_allocated.yaml
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.h
  js/client/modules/@arangodb/test-helper.js
  tests/js/client/shell/shell-cache-cleanup-noncluster.js
Labels: cla-signed

#18902 add debug output for agency segfault
  arangod/Agency/State.cpp
Labels: 9 Ready to Merge, cla-signed

#18909 remove duplicate entry from CHANGELOG
  CHANGELOG
Labels: cla-signed

#18885 testing: we need to know the PID in order to calculate the filename
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing, cla-signed

#18889 we need to know the PID in order to calculate the filename
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing, cla-signed

#18921 [CINFRA-708] Removing waitForIndex parameter
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/StateInterfaces.h
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.cpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/Mocks/FakeReplicatedState.h
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/CoreTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/FollowerTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/SnapshotTest.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#18913 Fix chaos test timeouts: BTS-1356
  CHANGELOG
  js/client/modules/@arangodb/test-helper.js
Labels: 3 - Testing, cla-signed

#18918 [BTS-1392] "Fix" lock order inversion TSAN failure
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
Labels: 3 Pregel

#18865 [PREGEL] pregel with actors fixes
  arangod/Pregel/StatusActor.h
  arangod/Pregel/StatusMessages.h
Labels: 3 Pregel, cla-signed

#18901 Update CMakePresets.json
  CMakePresets.json
Labels: cla-signed

#18916 Fix chaos test timeouts: BTS-1356
  js/client/modules/@arangodb/test-helper.js
Labels: 3 - Testing, cla-signed

#18862 feature-3.11/FE-255: add validation for collection, document, graph, view and database names
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arangoValidationHelper.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.ea26cf36.css.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.cb10d961.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.cb10d961.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.cb10d961.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ed36d222.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ed36d222.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ed36d222.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.9512fedafa8e56b22d68.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.beab3f58283dd9683614.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.916656a297b1a9fa698b.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.abd255e8d4a57cfa076a.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.8d11d1e159ab0e14c0e6.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.9c9c164e699d486b5abf.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.81dc9b21d2ced318e9ae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.bcf2ba9ef2bd549116a9.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-dark.994d1553f409200f5901.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-icon.35807d6e11925bd44973.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb.609cd935d9d34dab5e6b.eot.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/favicon.909457142f6be9dae418.ico.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.ed6298903ae1554c7f3e.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.f0af1680f082547a7aae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/jsoneditor-icons.ffbb30248a6fc9adfc7f.svg.gz
  js/apps/system/_admin/aardvark/APP/react/src/App.js
  js/apps/system/_admin/aardvark/APP/react/src/global.d.ts
  js/apps/system/_admin/aardvark/APP/react/src/utils/yupHelper.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/IndexFieldsHelper.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/useInvertedIndexJSONSchema.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphHeader/GraphHeader.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/constants.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/AddNewViewModal.tsx
Labels: 3 UI, cla-signed

#18908 3.11 backport for BTS-1343
  CHANGELOG
  client-tools/Shell/ClientFeature.cpp
  client-tools/Shell/ClientFeature.h
  client-tools/Utils/ClientManager.cpp
Labels: cla-signed

#18925 Fix ES-1566
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  tests/js/server/aql/aql-traversal-restrict-collections.js
Labels: cla-signed

#18910 Add metric arangodb_file_descriptors_current
  CHANGELOG
  Documentation/Metrics/arangodb_file_descriptors_current.yaml
  Documentation/Metrics/arangodb_file_descriptors_limit.yaml
  arangod/RestServer/CpuUsageFeature.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/FileDescriptorsFeature.cpp
  arangod/RestServer/FileDescriptorsFeature.h
  arangod/Statistics/StatisticsFeature.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/FileUtils.h
  tests/Basics/FilesTest.cpp
Labels: cla-signed

#18892 [3.11][BTS-1315] Fix for Foxx Service Installation
  CHANGELOG
  arangod/RestHandler/RestUploadHandler.cpp
  js/apps/system/_admin/aardvark/APP/foxxes.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/installUploadServiceView.js
  js/server/modules/@arangodb/foxx/manager.js
  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
Labels: 3 Foxx, cla-signed

#18896 Better cleanup & observability for in-memory cache
  CHANGELOG
  Documentation/Metrics/rocksdb_cache_peak_allocated.yaml
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.h
  js/client/modules/@arangodb/test-helper.js
  tests/js/client/shell/shell-cache-cleanup-noncluster.js
Labels: 9 Ready to Merge, 3 Metrics, cla-signed

#18920 [BTS-1392] [3.11] "Fix" lock order inversion
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
Labels: 3 Pregel, TSan, cla-signed, 3.11-Stabilization

#18924 Fix ES-1566
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  tests/js/server/aql/aql-traversal-restrict-collections.js
Labels: 9 Ready to Merge, cla-signed

#18926 Add metric `arangodb_file_descriptors_current`
  CHANGELOG
  Documentation/Metrics/arangodb_file_descriptors_current.yaml
  Documentation/Metrics/arangodb_file_descriptors_limit.yaml
  arangod/RestServer/CpuUsageFeature.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/FileDescriptorsFeature.cpp
  arangod/RestServer/FileDescriptorsFeature.h
  arangod/Statistics/StatisticsFeature.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/FileUtils.h
  tests/Basics/FilesTest.cpp
Labels: 9 Ready to Merge, 3 Metrics, cla-signed

#18930 attempt to stabilize a flaky test
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  tests/js/client/server_parameters/test-return-queue-time-header-on.js
Labels: 9 Ready to Merge, 3 - Testing, cla-signed

#18911 [BTS-1350]
  CHANGELOG
  arangod/Utils/SupportInfoBuilder.cpp
  tests/js/client/server_parameters/test-telemetrics-true-auth.js
Labels: cla-signed

#18933 3.11 backport for BTS-1350
  CHANGELOG
  arangod/Utils/SupportInfoBuilder.cpp
  tests/js/client/server_parameters/test-telemetrics-true-auth.js
Labels: cla-signed, 3.11-Stabilization

#18854 [BTS-1340]
  CHANGELOG
  client-tools/Shell/ShellFeature.cpp
  client-tools/Shell/ShellFeature.h
  client-tools/Shell/TelemetricsHandler.cpp
  client-tools/Shell/TelemetricsHandler.h
  lib/SimpleHttpClient/GeneralClientConnection.cpp
  lib/SimpleHttpClient/GeneralClientConnection.h
  lib/SimpleHttpClient/SslClientConnection.cpp
  lib/SimpleHttpClient/SslClientConnection.h
  tests/js/client/server_parameters/test-telemetrics-true-auth.js
Labels: cla-signed

#18941 [BTS-1181] Fix data race on the collection list in TransactionState
  CHANGELOG
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  tests/js/client/shell/transaction/shell-transaction.inc
Labels: cla-signed

#18912 3.11 backport for BTS-1340
  CHANGELOG
  client-tools/Shell/ShellFeature.cpp
  client-tools/Shell/ShellFeature.h
  client-tools/Shell/TelemetricsHandler.cpp
  client-tools/Shell/TelemetricsHandler.h
  lib/SimpleHttpClient/GeneralClientConnection.cpp
  lib/SimpleHttpClient/GeneralClientConnection.h
  lib/SimpleHttpClient/SslClientConnection.cpp
  lib/SimpleHttpClient/SslClientConnection.h
  tests/js/client/server_parameters/test-telemetrics-true-auth.js
Labels: cla-signed, 3.11-Stabilization

#18943 [BTS-1181] [3.11] Fix data race on the collection list in TransactionState
  CHANGELOG
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  tests/js/client/shell/transaction/shell-transaction.inc
Labels: 9 Ready to Merge, cla-signed, 3.11-Stabilization

#18959 fix(UI): document key should allow empty values
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arangoValidationHelper.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.0a11d8ab.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.0a11d8ab.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.0a11d8ab.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.gz
Labels: 3 UI, cla-signed

#18960 bug-fix-3.11/fix(UI): document key should allow empty values
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arangoValidationHelper.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.cb10d961.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.cb10d961.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.cb10d961.js.gz
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18938 bug-fix-3.11/FE-257: allow additional properties in inverted index creation
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/useInvertedIndexJSONSchema.tsx
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18937 FE-257: allow additional properties in inverted index creation
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/useInvertedIndexJSONSchema.tsx
Labels: 3 UI, cla-signed

#18940 bug-fix-3.11/FE-258: allow specifying optimizeTopK during arangosearch view creation
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/AdvancedAccordionItem.tsx
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18939 FE-258: allow specifying optimizeTopK during arangosearch view creation
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/AdvancedAccordionItem.tsx
Labels: 3 UI, cla-signed

#18961 FE-268: remove 'switch to new graph' when no defined graph is present
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/graphViewer2.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 3 UI, cla-signed

#18962 bug-fix-3.11/FE-268: remove 'switch to new graph' when no defined graph is present
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/graphViewer2.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphViewer.js
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18934 FE-265: Fix user permissions radio button shadow
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userPermissions.js
Labels: 3 UI, cla-signed

#18935 bug-fix-3.11/FE-265: Fix user permissions radio button shadow
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userPermissions.js
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18949 FE-267: fix custom analyzer & features not showing up in inverted index view, add support for basic fields
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/FieldsDropdown.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexAnalyzerDropdown.tsx
Labels: 3 UI, cla-signed

#18950 bug-fix-3.11/FE-267: fix custom analyzer & features not showing up in inverted index view, add support for basic fields
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/FieldsDropdown.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexAnalyzerDropdown.tsx
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18956 fix handling of HTTP errors in client-tools response processing
  CHANGELOG
  client-tools/Utils/ClientManager.cpp
Labels: cla-signed

#18955 fix handling of HTTP errors in client-tools response processing
  CHANGELOG
  client-tools/Utils/ClientManager.cpp
Labels: 9 Ready to Merge, cla-signed

#18954 bug-fix-3.11/FE-266-use-fromGeoJson
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 1 Bug, 3 UI, cla-signed, 3.11-Stabilization

#18948 bug-fix/FE-266-Use-fromGeoJson
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 1 Bug, 3 UI, cla-signed

#18890 Bug-Fix/FE-256-minor-UI-fixes-for-the-graph-viewer
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.840a1962.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.840a1962.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.840a1962.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphHeader/FullscreenGraphButton.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/AttributesInfo.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/DeleteEdgeModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/DeleteNodeModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/EditEdgeModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/EditNodeModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphNetwork/EdgeRightClickMenu.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphNetwork/NodeRightClickMenu.tsx
Labels: 3 UI, cla-signed

#18899 Bug-Fix-3.11/FE-256-minor-UI-fixes-for-the-graph-viewer backport
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1e14f0bb.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.840a1962.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.840a1962.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.840a1962.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphHeader/FullscreenGraphButton.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/AttributesInfo.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/DeleteEdgeModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/DeleteNodeModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/EditEdgeModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphModals/EditNodeModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphNetwork/EdgeRightClickMenu.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/graphNetwork/NodeRightClickMenu.tsx
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18878 [CINFRA] Wait for follower to resign
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/FollowerTest.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#18958 Add the functionality for truncating files on Windows
  CHANGELOG
  lib/Basics/FileUtils.cpp
  lib/Basics/error.cpp
  lib/Basics/error.h
  lib/Basics/win-utils.cpp
Labels: 4 Windows, cla-signed, 3.11-Stabilization

#18963 Add the functionality for truncating files on Windows
  CHANGELOG
  lib/Basics/FileUtils.cpp
  lib/Basics/error.cpp
  lib/Basics/error.h
  lib/Basics/win-utils.cpp
Labels: 4 Windows, cla-signed, 3.11-Stabilization

#18946 add more tests and better error handling
  CHANGELOG
  arangod/Aql/Collection.cpp
  arangod/Aql/ExecutionPlan.cpp
  tests/js/server/aql/aql-traversal-restrict-collections.js
Labels: cla-signed

#18972 BTS-1398 Fix GEO_DISTANCE filter
  arangod/IResearch/GeoFilter.cpp
  tests/js/server/aql/aql-geo.inc
Labels: 3 ArangoSearch, 3 Geo, cla-signed

#18973 Bug fix 3.11/BTS-1398 fix range geo filter
  CHANGELOG
  arangod/IResearch/GeoFilter.cpp
  tests/js/server/aql/aql-geo.inc
Labels: 3 ArangoSearch, 3 Geo, cla-signed

#18975 Bug fix 3.10/BTS-1398 fix range geo filter
  CHANGELOG
  arangod/IResearch/GeoFilter.cpp
  tests/js/server/aql/aql-geo.inc
Labels: 3 Geo, cla-signed

#18977 disable `parallelize-gather` optimizer rules for some cases
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Labels: cla-signed

#18971 [GORDO-1642] [3.11] Try and address some obvious timewasters
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/IncomingCache.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/OutgoingCache.h
  arangod/Pregel/Worker/State.h
  arangod/Pregel/Worker/VertexProcessor.cpp
  arangod/Pregel/Worker/VertexProcessor.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/WorkerConfig.h
Labels: 3 Pregel, cla-signed, 3.11-Stabilization

#18906 [CINFRA] Reduce difference between single server and cluster again
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/vocbase.cpp
  tests/js/client/server_parameters/test-telemetrics-true-auth.js
Labels: cla-signed

#18979 Remove unnecessary assign
  arangod/IResearch/GeoFilter.cpp
Labels: cla-signed

#18990 Fix issues in junit xml generator
  js/client/modules/@arangodb/testutils/result-processing.js
Labels: cla-signed

#18970 [GORDO-1642] Try and address some obvious timewasters
  arangod/Pregel/Algorithm.h
  arangod/Pregel/Algos/SSSP/SSSP.cpp
  arangod/Pregel/Algos/SSSP/SSSP.h
  arangod/Pregel/GraphStore/GraphSerdeConfig.h
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/IncomingCache.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/OutgoingCache.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/State.h
  arangod/Pregel/Worker/VertexProcessor.cpp
  arangod/Pregel/Worker/VertexProcessor.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel, cla-signed

#18994 [BTS-1400] Fix query not found issue with parallel-gather
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/Aql/RestAqlHandler.cpp
  arangod/Aql/RestAqlHandler.h
  tests/js/client/shell/shell-aql-regression-cluster.js
Labels: cla-signed

#18984 fix TSan race
  client-tools/Shell/ShellFeature.cpp
  client-tools/Shell/ShellFeature.h
  client-tools/Shell/TelemetricsHandler.cpp
  client-tools/Shell/TelemetricsHandler.h
Labels: cla-signed

#18976 Feature/cursor api next batch no retriable
  CHANGELOG
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestCursorHandler.h
  arangod/Utils/Cursor.h
  js/client/modules/@arangodb/arango-query-cursor.js
  js/client/modules/@arangodb/arango-statement.js
  tests/js/client/shell/api/cursor.js
Labels: cla-signed

#18983 fix TSan race
  client-tools/Shell/ShellFeature.cpp
  client-tools/Shell/ShellFeature.h
  client-tools/Shell/TelemetricsHandler.cpp
  client-tools/Shell/TelemetricsHandler.h
Labels: 9 Ready to Merge, cla-signed

#18978 [BTS-1400] [3.11] Fix query not found issue with parallel-gather
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/Aql/RestAqlHandler.cpp
  arangod/Aql/RestAqlHandler.h
  tests/js/client/shell/shell-aql-regression-cluster.js
Labels: 9 Ready to Merge, cla-signed

#18995 random code willification
  arangod/Agency/State.cpp
Labels: cla-signed

#18996 [GORDO-1643] Create Pregel Status Collection entry on creation
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
Labels: 3 Pregel, cla-signed

#18969 [DEVEL][BTS-1331] Optimize data overfetch in cluster traversals
  CHANGELOG
  arangod/Graph/PathManagement/PathValidator.cpp
  arangod/Graph/PathManagement/PathValidator.h
  arangod/Graph/PathManagement/PathValidatorTracer.cpp
  arangod/Graph/PathManagement/PathValidatorTracer.h
  arangod/Graph/Providers/ClusterProvider.cpp
  arangod/Graph/Queues/FifoQueue.h
  arangod/Graph/Queues/LifoQueue.h
  arangod/Graph/Queues/WeightedQueue.h
  arangod/Graph/Steps/ClusterProviderStep.cpp
  arangod/Graph/Steps/ClusterProviderStep.h
  arangod/Graph/Steps/SingleServerProviderStep.h
  arangod/Graph/Types/ValidationResult.cpp
  arangod/Graph/Types/ValidationResult.h
  tests/Mocks/MockGraphProvider.h
Labels: 1 Bug, 3 Graph, cla-signed

#19008 fix duplicate changelog entry, and move it to correct version
  CHANGELOG
Labels: 9 Ready to Merge, cla-signed

#18944 [BTS-1181] [3.10] Fix data race on the collection list in TransactionState
  CHANGELOG
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  tests/js/client/shell/transaction/shell-transaction.js
Labels: 9 Ready to Merge, cla-signed

#19000 keep jwt secret when using `arango.reconnect(...)`
  client-tools/Shell/V8ClientConnection.cpp
  tests/js/client/server_parameters/database-password-noncluster.js
Labels: 9 Ready to Merge, cla-signed

#18964 Add the functionality for truncating files on Windows
  CHANGELOG
  lib/Basics/FileUtils.cpp
  lib/Basics/error.cpp
  lib/Basics/error.h
  lib/Basics/win-utils.cpp
Labels: 4 Windows, cla-signed, 3.10

#18953 CMakePresets.json in 3.10 branch
  CMakePresets.json
Labels: cla-signed

#18966 Add the functionality for truncating files on Windows
  CHANGELOG
  lib/Basics/FileUtils.cpp
  lib/Basics/error.cpp
  lib/Basics/error.h
  lib/Basics/win-utils.cpp
Labels: 4 Windows, cla-signed, 3.9

#18945 [BTS-1181] [3.9] Fix data race on the collection list in TransactionState
  CHANGELOG
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  tests/js/client/shell/shell-transaction.js
Labels: 9 Ready to Merge, cla-signed

#18957 bug-fix-3.10/FE-266-use-fromGeoJson
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 1 Bug, 3 UI, cla-signed

#18841 Disable R2 resilience tests
  tests/js/server/resilience/move/moving-shards-cluster-data-R2.js_DISABLED
  tests/js/server/resilience/sharddist/shard-distribution.js
  tests/test-definitions.txt
Labels: cinfra, cla-signed, 3.11-Stabilization

#18914 [BTS-1373] fix error in test code
  arangod/StorageEngine/TransactionState.cpp
  lib/Basics/DebugRaceController.cpp
  lib/Basics/DebugRaceController.h
Labels: 1 Bug, 9 Ready to Merge, cla-signed

#19002 fix result processing of the v8-shell suite
  js/client/modules/@arangodb/testsuites/aql.js
Labels: cla-signed

#19014 [BTS-1400] [3.11] Use correct lane
  arangod/Aql/QueryRegistry.cpp
Labels: 9 Ready to Merge, cla-signed, 3.11-Stabilization

#19005 Revert "disable `parallelize-gather` optimizer rules for some cases (#18977)"
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Labels: 9 Ready to Merge, cla-signed, 3.11-Stabilization

#19016 update documentation
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor_cursor.md
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor_cursor_batch.md
  Documentation/DocuBlocks/Rest/Queries/put_api_cursor_cursor.md
Labels: cla-signed

#19010 fix(UI): validation & alignment issues in index addition
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/DeleteIndexButton.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/IndexActionCell.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/AddIndexForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/IndexFormFieldList.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/useInvertedIndexJSONSchema.tsx
Labels: 3 UI, cla-signed

#19011 Fixup and cleanup checkLogIds
  arangod/Pregel/Conductor/Conductor.cpp
  utils/checkLogIds.py
Labels: cla-signed

#18999 keep jwt secret when using `arango.reconnect(...)`
  client-tools/Shell/V8ClientConnection.cpp
  tests/js/client/server_parameters/database-password-noncluster.js
Labels: 9 Ready to Merge, cla-signed, 3.11-Stabilization

#19037 Fix clang-format enterprise
  .circleci/base_config.yml
  scripts/clang-format-circleci.sh
Labels: cla-signed

#18781 [GORDO-1449] Worker State Machine
  arangod/Pregel/Conductor/Handler.h
  arangod/Pregel/Conductor/Messages.h
  arangod/Pregel/Worker/CMakeLists.txt
  arangod/Pregel/Worker/ExecutionStates/CMakeLists.txt
  arangod/Pregel/Worker/ExecutionStates/CleanedUpState.h
  arangod/Pregel/Worker/ExecutionStates/ComputingState.cpp
  arangod/Pregel/Worker/ExecutionStates/ComputingState.h
  arangod/Pregel/Worker/ExecutionStates/FatalErrorState.h
  arangod/Pregel/Worker/ExecutionStates/InitialState.cpp
  arangod/Pregel/Worker/ExecutionStates/InitialState.h
  arangod/Pregel/Worker/ExecutionStates/LoadedState.cpp
  arangod/Pregel/Worker/ExecutionStates/LoadedState.h
  arangod/Pregel/Worker/ExecutionStates/LoadingState.cpp
  arangod/Pregel/Worker/ExecutionStates/LoadingState.h
  arangod/Pregel/Worker/ExecutionStates/ProducingResultsState.cpp
  arangod/Pregel/Worker/ExecutionStates/ProducingResultsState.h
  arangod/Pregel/Worker/ExecutionStates/ResultsProducedState.h
  arangod/Pregel/Worker/ExecutionStates/State.h
  arangod/Pregel/Worker/ExecutionStates/StoredState.h
  arangod/Pregel/Worker/ExecutionStates/StoringState.cpp
  arangod/Pregel/Worker/ExecutionStates/StoringState.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/State.h
Labels: 3 Pregel, cla-signed

#19052 testing: as in oskar show stacktraces
  scripts/test/testing_runner.py
Labels: 3 - Testing, cla-signed

#19036 fix client cursor implementation
  js/client/modules/@arangodb/arango-query-cursor.js
Labels: cla-signed

#19013 [BTS-615] Invalid Key Babies error
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  tests/js/common/shell/shell-document-babies.js
Labels: cla-signed

#19031 increase too short timeouts
  arangod/Cluster/ClusterMethods.cpp
Labels: cla-signed

#18992 fixed BTS-1404
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraversalNode.h
  arangod/Aql/TraverserEngineShardLists.cpp
  arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
  tests/js/server/aql/aql-traversal-restrict-collections.js
  tests/js/server/aql/aql-traversal-restrict-edge-collections.js
Labels: cla-signed

#19032 Fix network response metric. Remove wrong divisor.
  arangod/Network/NetworkFeature.cpp
Labels: cla-signed

#19069 Added `--query.max-collections-per-query` option
  CHANGELOG
  arangod/Aql/Collections.cpp
  arangod/Aql/Collections.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
  tests/js/client/server_parameters/max-collections-per-query-cluster.js
Labels: cla-signed

#18836 reduce memory usage for incremental sync replication
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  tests/js/server/replication/sync/replication-sync.js
Labels: 9 Ready to Merge, cla-signed
