Repository arangodb/arangodb, pull requests merged in 2023-02, with the labels that each got.

#17283 Implement PrettyPrintInspector
  lib/Inspection/Access.h
  lib/Inspection/Format.h
  lib/Inspection/JsonPrintInspector.h
  lib/Inspection/SaveInspectorBase.h
  lib/Inspection/VPackLoadInspector.h
  lib/Inspection/VPackSaveInspector.h
  lib/Inspection/detail/traits.h
  tests/Basics/Inspection/InspectionTest.cpp
  tests/Basics/Inspection/InspectionTestHelper.h
  tests/Basics/Inspection/JsonPrintTest.cpp
  tests/Basics/Inspection/VPackLoadTest.cpp
  tests/Basics/Inspection/VPackSaveTest.cpp
  tests/Basics/Inspection/ValidateTest.cpp
  tests/Basics/InspectionTest.cpp
  tests/CMakeLists.txt
Labels: cla-signed

#18030 [CINFRA] Linking shards with collection groups
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/Supervision.cpp
  arangod/Cluster/ClusterCollectionMethods.cpp
  arangod/Cluster/ClusterCollectionMethods.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/Utils/CollectionGroupUpdates.cpp
  arangod/Cluster/Utils/CollectionGroupUpdates.h
  arangod/Cluster/Utils/PlanCollectionEntryReplication2.cpp
  arangod/Cluster/Utils/PlanCollectionEntryReplication2.h
  arangod/Cluster/Utils/TargetCollectionAgencyWriter.cpp
  arangod/Replication2/AgencyCollectionSpecificationInspectors.h
  arangod/Replication2/StateMachines/Document/DocumentCore.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Properties/CMakeLists.txt
  arangod/VocBase/Properties/ClusteringConstantProperties.h
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  js/common/modules/@arangodb/testutils/replicated-state-helper.js
  js/common/modules/@arangodb/testutils/replicated-state-predicates.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
  tests/js/client/shell/transaction/shell-transaction-cluster.js
  tests/js/server/replication2/replication2-collectiongroups-cluster.js
  tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
  tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
  tests/js/server/resilience/move/moving-shards-cluster.js
Labels: 9 Ready to Merge, cinfra, cla-signed

#18035 [CINFRA] Intermediate Commits Flaky Test
  arangod/Cluster/Utils/EvenDistribution.cpp
  tests/js/client/shell/transaction/shell-transaction-intermediate-commit-cluster.js
Labels: 9 Ready to Merge, cinfra, cla-signed

#17981 RDBCoveringIterator doesn't work but never created
  CHANGELOG
  arangod/GeoIndex/Index.cpp
  arangod/GeoIndex/Index.h
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  lib/Geo/GeoParams.cpp
  lib/Geo/GeoParams.h
Labels: cla-signed

#18006 Activate RDBCoveringIterator
  CHANGELOG
  arangod/GeoIndex/Index.cpp
  arangod/GeoIndex/Index.h
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  lib/Geo/GeoParams.h
Labels: cla-signed

#18012 [CINFRA] Report state machine state to the agency. Useful for tests.
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.h
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.cpp
  arangod/Replication2/ReplicatedLog/LogStatus.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/types.cpp
  arangod/Replication2/ReplicatedLog/types.h
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/Mocks/LogEventRecorder.h
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
Labels: cinfra, cla-signed

#18032 allow toggling supervision maintenance mode via af followers
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/GeneralServer/CommTask.cpp
Labels: cla-signed

#18040 Added backport for BTS-266
  CHANGELOG
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  js/client/modules/@arangodb/testsuites/server_permissions.js
Labels: cla-signed

#18047 [CINFRA-588] Don't create new states after the database was dropped
  arangod/VocBase/vocbase.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#18044 Minor changes, following cinfra-666
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
Labels: 9 Ready to Merge, cinfra, cla-signed

#18015 [CINFRA] Don't pick server as leader without snapshot
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/Supervision.h
  arangod/Replication2/ReplicatedState/Supervision.cpp
  arangod/Replication2/ReplicatedState/Supervision.h
  arangod/Replication2/ReplicatedState/SupervisionAction.cpp
  arangod/Replication2/ReplicatedState/SupervisionAction.h
  tests/Replication2/Helper/ModelChecker/Predicates.h
  tests/Replication2/ReplicatedLog/SupervisionSimulationTest.cpp
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
Labels: cinfra, cla-signed

#18033 allow toggling supervision maintenance mode via af followers
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/GeneralServer/CommTask.cpp
Labels: 9 Ready to Merge, cla-signed

#18046 launch it printing version information
  js/client/modules/@arangodb/testsuites/arangosh.js
Labels: cla-signed

#17963 [PREGEL] Split Graph.h, make PregelShard its own struct
  arangod/Pregel/Algos/DMID/DMID.cpp
  arangod/Pregel/Algos/DMID/DMIDMessageFormat.h
  arangod/Pregel/Algos/DMID/VertexSumAggregator.h
  arangod/Pregel/Algos/EffectiveCloseness/HLLCounter.cpp
  arangod/Pregel/Algos/EffectiveCloseness/HLLCounterFormat.h
  arangod/Pregel/Algos/HITS.cpp
  arangod/Pregel/Algos/SCC.cpp
  arangod/Pregel/Algos/ShortestPath.cpp
  arangod/Pregel/Algos/WCC.cpp
  arangod/Pregel/CommonFormats.h
  arangod/Pregel/GraphFormat.h
  arangod/Pregel/GraphStore/Edge.h
  arangod/Pregel/GraphStore/Graph.h
  arangod/Pregel/GraphStore/PregelShard.h
  arangod/Pregel/GraphStore/Vertex.h
  arangod/Pregel/GraphStore/VertexID.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/VertexComputation.h
  arangod/Pregel/Worker/GraphStore.cpp
  arangod/Pregel/Worker/GraphStore.h
  arangod/Pregel/Worker/Messages.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/WorkerConfig.cpp
  arangod/Pregel/Worker/WorkerConfig.h
  tests/Pregel/CMakeLists.txt
  tests/Pregel/PregelShardTest.cpp
Labels: 3 Pregel, cla-signed

#18050 Port #18044 directly to devel
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
Labels: cinfra, cla-signed

#18025 [PREGEL] Make pregel js tests more stable
  js/common/modules/@arangodb/graph/pregel-test-effective-closeness-helpers.js
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  js/common/modules/@arangodb/graph/pregel-test-read-write-helpers.js
  tests/js/client/load-balancing/load-balancing-pregel-auth-cluster.js
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
  tests/js/common/shell/shell-pregel-basics-example.js
  tests/js/common/shell/shell-pregel-components.js
  tests/js/common/shell/shell-pregel-multicollection-edgecol.js
  tests/js/common/shell/shell-pregel-random.js
  tests/js/common/shell/shell-pregel-start-cluster.js
Labels: 3 Pregel, cla-signed

#18031 [CINFRA] Feature/cinfra structs for collection groups in agency
  arangod/Agency/AgencyPaths.h
  arangod/Agency/Job.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/Utils/CollectionGroupUpdates.cpp
  arangod/Cluster/Utils/CollectionGroupUpdates.h
  arangod/Cluster/Utils/TargetCollectionAgencyWriter.cpp
  arangod/Replication2/AgencyCollectionSpecification.h
  arangod/Replication2/AgencyCollectionSpecificationInspectors.h
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/js/server/replication2/replication2-collectiongroups-cluster.js
Labels: cinfra, cla-signed

#18054 small internal code cleanup
  arangod/Aql/ModificationOptions.cpp
  arangod/Graph/Enumerators/OneSidedEnumerator.cpp
  arangod/Graph/Enumerators/OneSidedEnumerator.h
  arangod/Graph/Enumerators/OneSidedEnumeratorInterface.h
  arangod/Graph/PathManagement/PathValidatorOptions.h
Labels: cla-signed

#18061 Feature/add coverage to version
  lib/Rest/Version.cpp
Labels: cla-signed

#18048 Added startup option `--javascript.user-defined-functions`.
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/V8Server/V8DealerFeature.cpp
  arangod/V8Server/V8DealerFeature.h
  tests/js/client/server_parameters/javascript-user-defined-functions-off.js
Labels: cla-signed

#18042 added backport for BTS-266
  CHANGELOG
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  js/client/modules/@arangodb/testsuites/server_permissions.js
Labels: cla-signed

#18058 fix issues reported by cppcheck
  arangod/Aql/DocumentProducingNode.cpp
  arangod/Aql/ShadowAqlItemRow.cpp
  lib/Basics/ErrorT.h
  lib/Basics/SourceLocation.h
Labels: cla-signed

#18014 [BTS-1193]
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  tests/js/client/shell/shell-dump-integration.js
  tests/js/client/shell/shell-restore-integration.js
  tests/js/common/shell/multi/shell-validation.js
Labels: cla-signed

#18056 Fixed issue #18053: Computed Values become null when Schema is modified
  CHANGELOG
  arangod/VocBase/LogicalCollection.cpp
  tests/js/common/shell/shell-collection-computed-values.js
Labels: cla-signed

#18069 Remove stray LOG_DEVEL
  arangod/Aql/ShortestPathExecutor.tpp
Labels: cla-signed

#18049 Added startup option --javascript.user-defined-functions.
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/V8Server/V8DealerFeature.cpp
  arangod/V8Server/V8DealerFeature.h
  tests/js/client/server_parameters/javascript-user-defined-functions-off.js
Labels: 9 Ready to Merge, cla-signed

#18051 disable jemalloc cache_oblivious behavior
  3rdParty/jemalloc/CMakeLists.txt
  CHANGELOG
Labels: 9 Ready to Merge, cla-signed

#18057 Fixed issue #18053: Computed Values become null when Schema is modified
  CHANGELOG
  arangod/VocBase/LogicalCollection.cpp
  tests/js/common/shell/shell-collection-computed-values.js
Labels: 9 Ready to Merge, cla-signed

#18063 BTS-1193 backport for 3.8
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  tests/js/client/shell/shell-dump-integration.js
  tests/js/client/shell/shell-restore-integration.js
  tests/js/common/shell/shell-validation.js
Labels: cla-signed

#18062 BTS-1193 backport for 3.9
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  tests/js/client/shell/shell-dump-integration.js
  tests/js/client/shell/shell-restore-integration.js
  tests/js/common/shell/shell-validation.js
Labels: cla-signed

#18060 BTS-1193 backport for 3.10
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  tests/js/client/shell/shell-dump-integration.js
  tests/js/client/shell/shell-restore-integration.js
  tests/js/common/shell/shell-validation.js
Labels: cla-signed

#18071 Feature/cinfra 671
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
Labels: cinfra, cla-signed

#18070 Add support for VPackBuilder to NodeLoadInspector
  arangod/Agency/NodeLoadInspector.h
  lib/Inspection/Access.h
  lib/Inspection/VPackLoadInspector.h
  tests/Basics/Inspection/NodeLoadTest.cpp
  tests/Basics/Inspection/VPackLoadTest.cpp
Labels: cinfra, cla-signed

#17986 DOC-330 | Overhaul README
  README
  README.md
  utils/generateREADME.sh
Labels: cla-signed

#18073 Feature/fix clang 15 compilation
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/Supervision.cpp
  arangod/Aql/CMakeLists.txt
  arangod/Cluster/AutoRebalance.cpp
  arangod/Pregel/Algos/RecoveringPageRank.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  lib/Zip/zip.cpp
Labels: cinfra, cla-signed

#18080 [CINFRA-672] Use explicit shards for replicated operations.
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
  arangod/Transaction/Methods.cpp
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Labels: cinfra, cla-signed

#17970 [PREGEL] Add actor framework
  arangod/Pregel/Actor/CMakeLists.txt
  arangod/Pregel/Actor/README.md
  arangod/Pregel/Actor/include/Actor/Actor.h
  arangod/Pregel/Actor/include/Actor/ActorBase.h
  arangod/Pregel/Actor/include/Actor/ActorList.h
  arangod/Pregel/Actor/include/Actor/ActorPID.h
  arangod/Pregel/Actor/include/Actor/Assert.h
  arangod/Pregel/Actor/include/Actor/HandlerBase.h
  arangod/Pregel/Actor/include/Actor/MPSCQueue.h
  arangod/Pregel/Actor/include/Actor/Message.h
  arangod/Pregel/Actor/include/Actor/Runtime.h
  arangod/Pregel/CMakeLists.txt
  tests/CMakeLists.txt
  tests/Pregel/Actor/ActorListTest.cpp
  tests/Pregel/Actor/ActorTest.cpp
  tests/Pregel/Actor/Actors/FinishingActor.h
  tests/Pregel/Actor/Actors/PingPongActors.h
  tests/Pregel/Actor/Actors/SpawnActor.h
  tests/Pregel/Actor/Actors/TrivialActor.h
  tests/Pregel/Actor/CMakeLists.txt
  tests/Pregel/Actor/MPSCQueueTest.cpp
  tests/Pregel/Actor/MultiRuntimeTest.cpp
  tests/Pregel/Actor/RuntimeTest.cpp
  tests/Pregel/Actor/ThreadPoolScheduler.h
  tests/Pregel/CMakeLists.txt
Labels: 3 Pregel, cla-signed

#18083 [testing] compress agency dumps
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing, cla-signed

#18084 pimp testfailures.txt in fatal abort situation
  js/client/modules/@arangodb/testutils/result-processing.js
Labels: 3 - Testing, cla-signed

#18085 [testing]: it seems ARM tends to be slower on shutdown; lets give it some more time
  js/client/modules/@arangodb/testsuites/endpoints.js
Labels: 3 - Testing, cla-signed

#18093 fix error handling in arangobench test case for expected errors
  client-tools/Benchmark/BenchmarkThread.h
  client-tools/Benchmark/testcases/CustomQueryTestCase.h
  js/client/modules/@arangodb/testsuites/arangobench.js
Labels: cla-signed

#17680 [SEARCH-421, SEARCH-422] Extend JS tests with InvertedIndex and nested documents
  tests/js/client/communication/test-communication.js
  tests/js/client/shell/api/analyzer.js
  tests/js/client/shell/api/multi/coordinator-metrics-cluster.js
  tests/js/client/shell/api/view-arangosearch-noncluster.js
  tests/js/client/shell/multi/shell-evil-database-names.js
  tests/js/client/shell/multi/shell-inventory-cluster.js
  tests/js/client/shell/shell-arangosearch-out-of-sync-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-combined.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl.js
  tests/js/common/aql/aql-view-arangosearch-feature.js
  tests/js/server/aql/aql-arangosearch-count-optimization.js
  tests/js/server/aql/aql-arangosearch-filter-optimization.js
  tests/js/server/aql/aql-geo.js
  tests/js/server/aql/aql-iresearch-view-executor-regression.js
  tests/js/server/aql/aql-optimizer-rule-collect-in-cluster.js
  tests/js/server/aql/aql-optimizer-rule-inline-subqueries.js
  tests/js/server/aql/aql-optimizer-rule-views-sorted-indexes.inc
  tests/js/server/aql/aql-options-verification.js
  tests/js/server/aql/aql-profiler-noncluster.js
  tests/js/server/aql/aql-query-cache-noncluster.js
  tests/js/server/aql/aql-shadowrow-block-return-regression.js
  tests/js/server/aql/aql-skipping.js
  tests/js/server/aql/aql-view-arangosearch-server.js
  tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster.js
  tests/js/server/resilience/move-view/moving-shards-with-arangosearch-view-cluster.js_DISABLED
  tests/js/server/shell/shell-arangosearch-out-of-sync-noncluster.js
  tests/js/server/shell/shell-index-link-parallel-drop-create.js
  tests/js/server/shell/shell-transactions-view-noncluster.js
Labels: cla-signed

#18028 This test could use some more bulknig.
  tests/js/client/shell/shell-collection-counts-cluster.js
Labels: 3 - Testing, cla-signed

#18065 properly handle the covearge switch via cmake
  CMakeLists.txt
  CMakePresets.json
  js/client/modules/@arangodb/test-helper.js
  js/client/modules/@arangodb/testsuites/agency-restart.js
  js/client/modules/@arangodb/testsuites/audit.js
  js/client/modules/@arangodb/testsuites/drivers.js
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testsuites/export.js
  js/client/modules/@arangodb/testsuites/fuzzer.js
  js/client/modules/@arangodb/testsuites/java.js
  js/client/modules/@arangodb/testsuites/js.js
  js/client/modules/@arangodb/testsuites/ldap.js
  js/client/modules/@arangodb/testsuites/license.js
  js/client/modules/@arangodb/testsuites/php.js
  js/client/modules/@arangodb/testsuites/recovery.js
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  js/client/modules/@arangodb/testsuites/server_permissions.js
  js/client/modules/@arangodb/testutils/process-utils.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
  js/common/bootstrap/modules/internal.js
  js/common/modules/@arangodb/test-helper-common.js
  js/server/modules/@arangodb/test-helper.js
  lib/Rest/Version.cpp
  lib/V8/v8-utils.cpp
  tests/js/client/communication/test-kill.js
  tests/js/client/shell/transaction/shell-transaction.js
  tests/js/common/execute-infinite-shortest-path.js
  tests/js/common/shell/multi/shell-document.js
  tests/js/common/shell/shell-edge.js
  tests/js/common/shell/shell-index.js
  tests/js/server/shell/shell-transactions.js
Labels: 3 - Testing, cla-signed

#18079 [testing] make sure tests cleanup their instances directories and temporary files
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testsuites/export.js
  js/client/modules/@arangodb/testsuites/server_permissions.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  tests/js/client/shell/shell-dump-integration.js
  tests/js/client/shell/shell-restore-integration.js
Labels: 3 ImportExport, 3 - Testing, cla-signed

#18101 [GORDO-1511] Disable unstable test
  tests/Pregel/Actor/ActorTest.cpp
Labels: 3 Pregel, cla-signed

#18092 [CINFRA-656] CreateCollection on Leader Maintenance
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/CreateCollection.h
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/StateMachines/Document/DocumentCore.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentLogEntry.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Labels: cinfra, cla-signed

#18088 include database properties in debug dumps
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#18094 extract GlobalContextMethods from V8Context.h header
  arangod/Auth/UserManager.cpp
  arangod/RestHandler/RestAdminRoutingHandler.cpp
  arangod/V8Server/CMakeLists.txt
  arangod/V8Server/GlobalContextMethods.cpp
  arangod/V8Server/GlobalContextMethods.h
  arangod/V8Server/V8Context.cpp
  arangod/V8Server/V8Context.h
  arangod/V8Server/V8DealerFeature.cpp
  arangod/V8Server/V8DealerFeature.h
  arangod/V8Server/v8-actions.cpp
  arangod/VocBase/Methods/AqlUserFunctions.cpp
  arangod/VocBase/Methods/AqlUserFunctions.h
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/Methods/Databases.h
  js/server/modules/@arangodb/foxx/manager.js
  lib/V8/JavaScriptSecurityContext.cpp
  lib/V8/JavaScriptSecurityContext.h
Labels: cla-signed

#18090 Allow usage of projections in more cases
  CHANGELOG
  arangod/Aql/OptimizerUtils.cpp
  tests/js/server/aql/aql-subquery.js
  tests/js/server/aql/aql-traversal-projections.js
Labels: cla-signed

#18096 Return memory usage of query explain operation
  CHANGELOG
  arangod/Aql/Optimizer.cpp
  arangod/Aql/Optimizer.h
  arangod/Aql/Query.cpp
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#18087 feat: adds query search [FE-131]
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoQueries.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/queryView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.01f91e86715f72a4d211400258b9fc2d.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.e7208fbda40e8c8f99d181db3029bce3.js
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.e7208fbda40e8c8f99d181db3029bce3.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.3da6d2d0.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.3da6d2d0.chunk.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.710824e1.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.710824e1.chunk.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.710824e1.chunk.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.710824e1.chunk.js.gz
Labels: 3 UI, cla-signed

#18082 Improve Filter optimizations on Traversals in AQL
  CHANGELOG
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/Condition.cpp
  arangod/Aql/Condition.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/PruneExpressionEvaluator.cpp
  arangod/Aql/TraversalConditionFinder.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/types.h
  js/common/modules/@arangodb/aql/explainer.js
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
  tests/js/common/aql/aql-graph-traverser-pruneTraversal.js
  tests/js/server/aql/aql-graph-traverser-complexFiltering.js
  tests/js/server/aql/aql-optimizer-rule-optimize-traversals-spec.js
Labels: 9 Ready to Merge, cla-signed

#18091 Allow usage of projections in more cases
  CHANGELOG
  arangod/Aql/OptimizerUtils.cpp
  tests/js/server/aql/aql-subquery.js
  tests/js/server/aql/aql-traversal-projections.js
Labels: 9 Ready to Merge, cla-signed

#18098 3.10 - [SEARCH-421, SEARCH-422] Extend JS tests with InvertedIndex and nested documents
  tests/js/client/communication/test-communication.js
  tests/js/client/shell/api/analyzer.js
  tests/js/client/shell/api/coordinator-metrics-cluster.js
  tests/js/client/shell/api/view-arangosearch-noncluster.js
  tests/js/client/shell/shell-arangosearch-out-of-sync-cluster.js
  tests/js/client/shell/shell-evil-database-names.js
  tests/js/client/shell/shell-inventory-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-combined.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl.js
  tests/js/common/aql/aql-view-arangosearch-feature.js
  tests/js/server/aql/aql-arangosearch-count-optimization.js
  tests/js/server/aql/aql-arangosearch-filter-optimization.js
  tests/js/server/aql/aql-geo.js
  tests/js/server/aql/aql-iresearch-view-executor-regression.js
  tests/js/server/aql/aql-optimizer-rule-collect-in-cluster.js
  tests/js/server/aql/aql-optimizer-rule-inline-subqueries.js
  tests/js/server/aql/aql-optimizer-rule-views-sorted-indexes.inc
  tests/js/server/aql/aql-options-verification.js
  tests/js/server/aql/aql-profiler-noncluster.js
  tests/js/server/aql/aql-query-cache-noncluster.js
  tests/js/server/aql/aql-shadowrow-block-return-regression.js
  tests/js/server/aql/aql-skipping.js
  tests/js/server/aql/aql-view-arangosearch-server.js
  tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster.js
  tests/js/server/resilience/move-view/moving-shards-with-arangosearch-view-cluster.js_DISABLED
  tests/js/server/shell/shell-arangosearch-out-of-sync-noncluster.js
  tests/js/server/shell/shell-index-link-parallel-drop-create.js
  tests/js/server/shell/shell-transactions-view-noncluster.js
Labels: 3 - Testing, 3 ArangoSearch, cla-signed

#18104 Enable some cluster tests
  tests/js/client/shell/multi/shell-inventory-cluster.js
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#18095 Make geo index cheap again [BTS-1219].
  CHANGELOG
  arangod/Aql/ExecutionNode.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.h
  tests/js/server/aql/aql-optimizer-rule-move-filters-into-enumerate.js
  tests/js/server/aql/aql-queries-geo.js
Labels: cla-signed

#18089 Make geo index cheap again [BTS-1219].
  CHANGELOG
  arangod/Aql/ExecutionNode.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.h
  tests/js/server/aql/aql-optimizer-rule-move-filters-into-enumerate.js
  tests/js/server/aql/aql-queries-geo.js
Labels: cla-signed

#18117 Make the collectionGroupId available in the LogicalCollection
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
Labels: cinfra, cla-signed

#18110 increase timeout even more, add missing forced shutdown if we still fail
  js/client/modules/@arangodb/testsuites/endpoints.js
Labels: cla-signed

#18122 Feature/bts 470 471
  tests/js/server/aql/aql-geo-distance-range.js
Labels: 3 ArangoSearch, cla-signed

#18118 Split resilience_move tests
  js/client/modules/@arangodb/testsuites/resilience.js
  tests/js/server/resilience/move/moving-shards-cluster-data-R1.js
  tests/js/server/resilience/move/moving-shards-cluster-data-R2.js
  tests/js/server/resilience/move/moving-shards-cluster-no-data-R1.js
  tests/js/server/resilience/move/moving-shards-cluster.inc
  tests/test-definitions.txt
Labels: cla-signed

#18120 Split resilience tests in separate files and enable bucketizing
  tests/js/server/resilience/failover/resilience-synchronous-repl-cluster-fail-follower.js
  tests/js/server/resilience/failover/resilience-synchronous-repl-cluster-fail-leader.js
  tests/js/server/resilience/failover/resilience-synchronous-repl-cluster.inc
  tests/js/server/resilience/failover/resilience-synchronous-repl-cluster.js
  tests/test-definitions.txt
Labels: cla-signed

#18072 Make gharial transactions globally managed [BTS-1220].
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/Methods/Tasks.cpp
Labels: cla-signed

#18124 [CINFRA] Remove old supervision code
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
Labels: cinfra

#18019 Experimental Change on SmartGraphs
  CHANGELOG
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/Transaction/Methods.cpp
  arangod/V8Server/v8-collection.cpp
Labels: cla-signed

#18078 Make gharial transactions globally managed [BTS-1220].
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/Methods/Tasks.cpp
Labels: cla-signed

#18077 Make gharial transactions globally managed [BTS-1220].
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/Methods/Tasks.cpp
Labels: cla-signed

#18097 Return memory usage of query explain operation
  CHANGELOG
  arangod/Aql/Optimizer.cpp
  arangod/Aql/Optimizer.h
  arangod/Aql/Query.cpp
  js/common/modules/@arangodb/aql/explainer.js
Labels: 9 Ready to Merge, cla-signed

#18119 Split replication-sync tests into separate files
  tests/js/server/replication/sync/replication-sync-malarkey-new-format-intermediate-commits.js
  tests/js/server/replication/sync/replication-sync-malarkey-new-format.js
  tests/js/server/replication/sync/replication-sync-malarkey-no-hlc.js
  tests/js/server/replication/sync/replication-sync-malarkey-old-format.js
  tests/js/server/replication/sync/replication-sync-malarkey.inc
  tests/test-definitions.txt
Labels: cla-signed

#18066 improve filter naming
  CONTRIBUTING.md
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
  tests/js/server/aql/aql-complex-queries-callstack-noinstr.js
  tests/js/server/recovery/crash-handler-abort-noinstr-nonwindows.js
  tests/js/server/recovery/crash-handler-assert-noinstr.js
  tests/js/server/recovery/crash-handler-segfault-nonwindows-noinstr.js
  tests/js/server/recovery/crash-handler-terminate-active-noinstr.js
  tests/js/server/recovery/crash-handler-terminate-noinstr.js
Labels: 3 - Testing, cla-signed, cmake improvements

#18109 [CINFRA-673] Multi shard snapshot transfer
  arangod/Replication2/StateMachines/Document/CollectionReader.cpp
  arangod/Replication2/StateMachines/Document/CollectionReader.h
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.h
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.h
  tests/Replication2/Mocks/DocumentStateMocks.cpp
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Labels: cinfra, cla-signed

#18126 Bug fix/3.10 smartedges race condition
  CHANGELOG
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/Transaction/Methods.cpp
  arangod/V8Server/v8-collection.cpp
Labels: cla-signed

#18108 Replace JSON.parse(response.body) by response.parsedBody in HTTP examples
  Documentation/DocuBlocks/Rest/Administration/get_admin_license.md
  Documentation/DocuBlocks/Rest/Administration/get_admin_support_info.md
  Documentation/DocuBlocks/Rest/Administration/post_api_new_tasks.md
  Documentation/DocuBlocks/Rest/Bulk/import_document.md
  Documentation/DocuBlocks/Rest/Bulk/import_json.md
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_getResponsibleShard.md
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor_delete.md
  Documentation/DocuBlocks/Rest/Cursors/put_api_cursor_identifier.md
  Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
  Documentation/DocuBlocks/Rest/Pregel/post_api_control_pregel_start.md
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
  Documentation/DocuBlocks/Rest/job/job_delete.md
Labels: 3 Documentation, cla-signed

#18107 Replace JSON.parse(response.body) by response.parsedBody in HTTP examples
  Documentation/DocuBlocks/Rest/Administration/get_admin_license.md
  Documentation/DocuBlocks/Rest/Administration/get_admin_support_info.md
  Documentation/DocuBlocks/Rest/Administration/post_api_new_tasks.md
  Documentation/DocuBlocks/Rest/Bulk/import_document.md
  Documentation/DocuBlocks/Rest/Bulk/import_json.md
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_getResponsibleShard.md
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor_delete.md
  Documentation/DocuBlocks/Rest/Cursors/put_api_cursor_identifier.md
  Documentation/DocuBlocks/Rest/Documents/delete_mutliple_documents.md
  Documentation/DocuBlocks/Rest/Pregel/post_api_control_pregel_start.md
  Documentation/DocuBlocks/Rest/Transactions/post_api_transaction_begin.md
  Documentation/DocuBlocks/Rest/job/job_delete.md
Labels: 3 Documentation, cla-signed

#17792 CircleCI configuration
  .circleci/base_config.yml
  .circleci/config.yml
  .circleci/generate_config.py
  .gitignore
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testutils/result-processing.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testrunner.js
  lib/V8/v8-vpack.cpp
  scripts/build/arangodb-build.Dockerfile
  scripts/build/install-openssl.sh
  scripts/test/allure_commons/_allure.py
  scripts/test/arangosh.py
  scripts/test/async_client.py
  scripts/test/dmesg.py
  scripts/test/launch_handler.py
  scripts/test/site_config.py
  scripts/test/socket_counter.py
  scripts/test/test_config.py
  scripts/test/test_launch_controller.py
  scripts/test/testing_runner.py
  scripts/test/tools/asciiprint.py
  scripts/test/tools/killall.py
  tests/CMakeLists.txt
  tests/js/client/restart/test-restart-replication2-prototype-state-cluster-grey.js
  tests/test-definitions.txt
  utils/clang-format.sh
  utils/jslint-2.0.sh
Labels: cla-signed

#18131 [CINFRA] CircleCI for staging/replication-2.0 push
  .circleci/config.yml
Labels: cinfra, cla-signed

#18123 [CINFRA-679] Document State Tracks Multiple Shards
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/ReplicatedLog/LogCommon.h
  arangod/Replication2/StateMachines/Document/DocumentCore.cpp
  arangod/Replication2/StateMachines/Document/DocumentCore.h
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.h
  arangod/Replication2/StateMachines/Document/ShardProperties.h
  tests/Replication2/Mocks/DocumentStateMocks.cpp
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#18129 Bug fix/3.9 smartedges race condition
  CHANGELOG
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/Transaction/Methods.cpp
  arangod/V8Server/v8-collection.cpp
  lib/Basics/debugging.cpp
  lib/Basics/debugging.h
Labels: cla-signed

#18140 Add an empty .circleci/config.yml to 3.8 branch
  .circleci/config.yml
Labels: cla-signed

#18067 [CINFRA] Collection Group Supervision
  arangod/Agency/AgencyPaths.h
  arangod/Agency/Agent.cpp
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/AgencyCallbackRegistry.h
  arangod/Cluster/ClusterCollectionMethods.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/Utils/CollectionGroupUpdates.cpp
  arangod/Cluster/Utils/CollectionGroupUpdates.h
  arangod/Cluster/Utils/PlanCollectionEntry.cpp
  arangod/Cluster/Utils/PlanCollectionEntryReplication2.cpp
  arangod/Cluster/Utils/PlanCollectionEntryReplication2.h
  arangod/Cluster/Utils/PlanShardToServerMappping.h
  arangod/Cluster/Utils/TargetCollectionAgencyWriter.cpp
  arangod/Cluster/Utils/TargetCollectionAgencyWriter.h
  arangod/Replication2/AgencyCollectionSpecification.h
  arangod/Replication2/AgencyCollectionSpecificationInspectors.h
  arangod/Replication2/AgencyMethods.cpp
  arangod/Replication2/CMakeLists.txt
  arangod/Replication2/Methods.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/ParticipantsHealth.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/SupervisionAction.cpp
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/StateMachines/Document/DocumentStateAgencyHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.h
  arangod/RestHandler/RestLogHandler.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/Properties/CollectionIndexesProperties.h
  tests/Replication2/CMakeLists.txt
  tests/Replication2/CollectionGroups/CollectionGroupsSupervision.cpp
  tests/Replication2/Helper/AgencyLogBuilder.h
  tests/Replication2/ReplicatedLog/SupervisionTest.cpp
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/js/server/replication2/replication2-replicated-state-document-store.js
  tests/js/server/replication2/replication2-supervision-collection-groups.js
Labels: cinfra, cla-signed

#18138 Add an empty .circleci/config.yml to 3.10 branch
  .circleci/config.yml
Labels: cla-signed

#18112 Backport of BTS-1184 for 3.10
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-index-hints.js
Labels: cla-signed

#18128 SEARCH-279 snapshot for inverted index
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNodeOptimizerRules.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
  arangod/IResearch/IResearchInvertedClusterIndex.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndex.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/ViewSnapshot.cpp
  arangod/IResearch/ViewSnapshot.h
  arangod/Indexes/IndexIterator.h
  tests/IResearch/IResearchInvertedIndexIteratorTest.cpp
  tests/RocksDBEngine/ChecksumHelperTest.cpp
  tests/js/server/aql/aql-inverted-index.js
Labels: cla-signed

#18133 [testing] compress agency dumps (#18083)
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing, cla-signed

#18148 Update OpenSSL to 1.1.1t and OpenLDAP to 2.6.4
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#18147 Update OpenSSL to 1.1.1t and OpenLDAP to 2.6.4 (3.10)
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#18146 Update OpenSSL to 1.1.1t and OpenLDAP to 2.6.4 (3.9)
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#18145 Update OpenSSL to 1.1.1t and OpenLDAP to 2.6.4 (3.8)
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#18142 [CINFRA] CircleCI reduced test set
  .circleci/base_config.yml
  .circleci/config.yml
Labels: cinfra, cla-signed

#18141 [CINFRA-673] Snapshot Transfer Protocol Adaptation
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/StateMachines/Document/CMakeLists.txt
  arangod/Replication2/StateMachines/Document/DocumentCore.cpp
  arangod/Replication2/StateMachines/Document/DocumentCore.h
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentStateAgencyHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateAgencyHandler.h
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateNetworkHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateNetworkHandler.h
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.h
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.h
  arangod/Replication2/StateMachines/Document/ShardProperties.h
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  tests/Replication2/Mocks/DocumentStateMocks.cpp
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#18127 [GORDO-1518] Fix memory leak in tests
  tests/Pregel/Actor/MPSCQueueTest.cpp
  tests/Pregel/Actor/MultiRuntimeTest.cpp
  tests/Pregel/Actor/RuntimeTest.cpp
Labels: 3 Pregel, cla-signed

#18152 [CINFRA] Merging devel
  CHANGELOG
  VERSIONS
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNodeOptimizerRules.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
  arangod/IResearch/IResearchInvertedClusterIndex.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchInvertedIndex.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/ViewSnapshot.cpp
  arangod/IResearch/ViewSnapshot.h
  arangod/Indexes/IndexIterator.h
  tests/IResearch/IResearchInvertedIndexIteratorTest.cpp
  tests/Pregel/Actor/MPSCQueueTest.cpp
  tests/Pregel/Actor/MultiRuntimeTest.cpp
  tests/Pregel/Actor/RuntimeTest.cpp
  tests/RocksDBEngine/ChecksumHelperTest.cpp
  tests/js/server/aql/aql-inverted-index.js
Labels: cinfra, cla-signed

#18151 Update OpenSSL in Dockerfile
  .circleci/base_config.yml
  scripts/build/README.md
  scripts/build/arangodb-build.Dockerfile
Labels: cla-signed

#18155 Use PTY for test output redirect.
  scripts/test/async_client.py
  scripts/test/test_launch_controller.py
Labels: cla-signed

#18137 Coverage Presets, Small fix for CMakeLists.txt to work with clang
  CMakeLists.txt
  CMakePresets.json
Labels: cla-signed

#18160 Add missing sccache links
  scripts/build/arangodb-build.Dockerfile
Labels: cla-signed

#18161 CINFRA: ShardKeys are not part of Target yet, and hence are forgotten
  arangod/Cluster/Utils/PlanCollectionEntryReplication2.cpp
  arangod/Replication2/AgencyCollectionSpecification.h
  arangod/Replication2/AgencyCollectionSpecificationInspectors.h
Labels: cla-signed

#18164 Feature/cinfra 684 activate colletectiongroups
  arangod/Cluster/ClusterCollectionMethods.cpp
Labels: cla-signed

#18102 [CINFRA-656] Maintenance drop shard on leader + Supervision wait for Current
  arangod/Agency/Supervision.cpp
  arangod/Cluster/DropCollection.cpp
  arangod/Cluster/DropCollection.h
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentStateTransaction.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransaction.h
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.h
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.h
  arangod/VocBase/LogicalCollection.cpp
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/js/server/replication2/replication2-supervision-collection-groups.js
Labels: cinfra, cla-signed

#18021 Implement new geo_s2 analyzer
  3rdParty/s2geometry/master/src/s2/s2loop.cc
  3rdParty/s2geometry/master/src/s2/s2loop.h
  arangod/IResearch/ExpressionFilter.cpp
  arangod/IResearch/Geo.cpp
  arangod/IResearch/Geo.h
  arangod/IResearch/GeoAnalyzer.cpp
  arangod/IResearch/GeoAnalyzer.h
  arangod/IResearch/GeoFilter.cpp
  arangod/IResearch/GeoFilter.h
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchKludge.cpp
  lib/Geo/CMakeLists.txt
  lib/Geo/Coding.cpp
  lib/Geo/Coding.h
  lib/Geo/GeoJson.cpp
  lib/Geo/GeoJson.h
  lib/Geo/GeoParams.h
  lib/Geo/S2/CMakeLists.txt
  lib/Geo/S2/S2MultiPointRegion.cpp
  lib/Geo/S2/S2MultiPointRegion.h
  lib/Geo/S2/S2MultiPolyline.cpp
  lib/Geo/S2/S2MultiPolylineRegion.cpp
  lib/Geo/S2/S2MultiPolylineRegion.h
  lib/Geo/ShapeContainer.cpp
  lib/Geo/ShapeContainer.h
  tests/Geo/GeoJsonTest.cpp
  tests/Geo/ShapeContainerTest.cpp
  tests/IResearch/GeoAnalyzerTest.cpp
  tests/IResearch/GeoDistanceFilterTest.cpp
  tests/IResearch/GeoFilterTest.cpp
  tests/IResearch/IResearchFilterGeoTest.cpp
  tests/IResearch/IResearchQueryGeoContainsTest.cpp
  tests/IResearch/IResearchQueryGeoDistanceTest.cpp
  tests/IResearch/IResearchQueryGeoInRangeTest.cpp
  tests/IResearch/IResearchQueryGeoIntersectsTest.cpp
  tests/IResearch/common.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
  tests/js/server/aql/aql-geo-0.js
  tests/js/server/aql/aql-geo-1.js
  tests/js/server/aql/aql-geo-2.js
  tests/js/server/aql/aql-geo-3.js
  tests/js/server/aql/aql-geo.inc
Labels: cla-signed

#18170 Wait for shard to appear in current, not only collection.
  arangod/Agency/Supervision.cpp
  arangod/Replication2/AgencyCollectionSpecification.h
  arangod/Replication2/AgencyCollectionSpecificationInspectors.h
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.h
Labels: cinfra, cla-signed

#18171 Do not cleanup test output and store xml files as test artifacts
  .circleci/base_config.yml
  scripts/test/testing_runner.py
Labels: cla-signed

#18143 [CINFRA] Collection Groups Supervision
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/DropCollection.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.h
  arangod/VocBase/LogicalCollection.cpp
  tests/Replication2/CollectionGroups/CollectionGroupsSupervision.cpp
  tests/js/server/replication2/replication2-supervision-collection-groups.js
Labels: cinfra, cla-signed

#18177 [CINFRA] Create/DropShard vs resign mutex
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
Labels: cinfra, cla-signed

#18175 Move and rename CircleCI clang-format script
  .circleci/base_config.yml
  scripts/clang-format-circleci.sh
Labels: cla-signed

#18181 Fixing missing version increment.
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.h
Labels: cinfra, cla-signed

#18182 [CINFRA-513] Remove syncShardsWithLogs from tests
  tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#18184 Resign replicated logs when a database is dropped.
  arangod/RestServer/DatabaseFeature.cpp
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
Labels: cinfra, cla-signed

#18168 CINFRA-667 Use new CreateCollection methods for create Database
  arangod/Agency/AgencyPaths.h
  arangod/Cluster/ClusterCollectionMethods.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/Utils/CollectionGroupUpdates.cpp
  arangod/Cluster/Utils/CollectionGroupUpdates.h
  arangod/Cluster/Utils/TargetCollectionAgencyWriter.cpp
  arangod/Cluster/Utils/TargetCollectionAgencyWriter.h
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  arangod/VocBase/Methods/UpgradeTasks.cpp
  arangod/VocBase/Properties/ClusteringConstantProperties.cpp
  arangod/VocBase/Properties/UserInputCollectionProperties.cpp
  tests/js/server/replication2/replication2-collectiongroups-cluster.js
Labels: cinfra, cla-signed

#18013 [GORDO-1512] Graph Refactor -- K_SHORTEST_PATHS edition
  CHANGELOG
  arangod/Aql/EnumeratePathsExecutor.cpp
  arangod/Aql/EnumeratePathsExecutor.h
  arangod/Aql/EnumeratePathsNode.cpp
  arangod/Aql/EnumeratePathsNode.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ShortestPathExecutor.cpp
  arangod/Aql/ShortestPathExecutor.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Graph/BaseOptions.cpp
  arangod/Graph/BaseOptions.h
  arangod/Graph/CMakeLists.txt
  arangod/Graph/Enumerators/TwoSidedEnumerator.cpp
  arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.cpp
  arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.h
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  arangod/Graph/Options/TwoSidedEnumeratorOptions.cpp
  arangod/Graph/Options/TwoSidedEnumeratorOptions.h
  arangod/Graph/PathManagement/PathResult.cpp
  arangod/Graph/PathManagement/PathResult.h
  arangod/Graph/PathManagement/PathStore.cpp
  arangod/Graph/ShortestPathFinder.cpp
  arangod/Graph/ShortestPathFinder.h
  arangod/Graph/ShortestPathResult.cpp
  arangod/Graph/ShortestPathResult.h
  arangod/Graph/TraverserOptions.cpp
  arangod/Graph/algorithm-aliases.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Aql/EnumeratePathsExecutorTest.cpp
  tests/Aql/ShortestPathExecutorTest.cpp
  tests/Graph/CMakeLists.txt
  tests/Graph/GraphTestTools.cpp
  tests/Graph/GraphTestTools.h
  tests/Graph/KShortestPathsFinder.cpp
  tests/Graph/KShortestPathsFinderTest.cpp
  tests/Graph/TraverserCacheTest.cpp
  tests/Graph/WeightedShortestPathTest.cpp
  tests/Mocks/MockGraphProvider.cpp
  tests/Mocks/MockGraphProvider.h
  tests/js/server/aql/aql-memory-limit.js
Labels: cla-signed

#18190 [CINFRA] Maintenance TakeoverShardLeadership crash fix
  arangod/Cluster/FollowerInfo.cpp
Labels: cinfra, cla-signed

#18185 fix misleading message
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
Labels: cla-signed

#18134 Bug fix 3.10/only remove subdir (#18079)
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testsuites/export.js
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  js/client/modules/@arangodb/testsuites/server_permissions.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  tests/js/client/shell/shell-dump-integration.js
  tests/js/client/shell/shell-restore-integration.js
Labels: 3 - Testing, cla-signed

#18196 update wcwidth to current version
  3rdParty/linenoise-ng/LICENSE-wcwidth.txt
  3rdParty/linenoise-ng/src/wcwidth.cpp
  LICENSES-OTHER-COMPONENTS.md
Labels: cla-signed

#18197 small code cleanup (2)
  arangod/Aql/ClusterNodes.h
  arangod/Aql/ModificationExecutorHelpers.cpp
  arangod/Aql/ModificationExecutorHelpers.h
  arangod/Aql/ModificationNodes.cpp
  arangod/Aql/ModificationNodes.h
  arangod/Aql/ModificationOptions.cpp
  arangod/Aql/ModificationOptions.h
  arangod/Aql/OptimizerUtils.h
  arangod/Aql/RemoveModifier.cpp
  arangod/Aql/UpdateReplaceModifier.cpp
  arangod/Indexes/IndexIterator.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
Labels: cla-signed

#18193 small code cleanup
  arangod/Aql/ExecutionNode.h
  arangod/Aql/OptimizerRule.h
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/RestAqlHandler.h
  arangod/Aql/Variable.cpp
  arangod/Sharding/ShardDistributionReporter.cpp
Labels: cla-signed

#18198 [testing]: lean jsunity callstack
  js/common/modules/jsunity/jsunity.js
Labels: cla-signed

#18204 BTS-1249: Add startup option `--foxx.enable`.
  CHANGELOG
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/ServerSecurityFeature.cpp
  arangod/GeneralServer/ServerSecurityFeature.h
  arangod/Utils/ExecContext.cpp
  arangod/Utils/ExecContext.h
  arangod/V8Server/FoxxFeature.cpp
  arangod/V8Server/FoxxFeature.h
  tests/js/client/server_parameters/foxx-enable-false.js
  tests/js/client/server_parameters/foxx-enable-true.js
Labels: cla-signed

#18205 QA-367: fix tearDownAll error reporting, lint
  js/common/modules/jsunity/jsunity.js
Labels: cla-signed

#18187 Fix arangorestore API to create _rev on shard leader [BTS-1232].
  CHANGELOG
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: cla-signed

#18115 ES-1428: max number of V8 contexts depends on max threads
  CHANGELOG
  arangod/Scheduler/SchedulerFeature.cpp
  arangod/Scheduler/SchedulerFeature.h
  arangod/V8Server/V8DealerFeature.cpp
  tests/js/common/shell/shell-index.js
Labels: 9 Ready to Merge, cla-signed
