Repository arangodb/arangodb, pull requests merged in 2023-04, with the labels that each got.

#18537 [CINFRA-722] use scheduler storage manager
  arangod/Replication2/IScheduler.h
  arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.cpp
  arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.h
  arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/Components/LogFollower.h
  arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
  arangod/Replication2/ReplicatedLog/Components/StorageManager.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  tests/Replication2/Mocks/SchedulerMocks.h
  tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/StorageManagerTest.cpp
  tests/Replication2/ReplicatedLog/LogFollower/AppendEntriesTest.cpp
  tests/Replication2/ReplicatedState/StateManagerTest.cpp
Labels: cinfra, cla-signed

#18546 Fix red test caused by logic merge conflict when reintegrating devel
  arangod/VocBase/Properties/ClusteringConstantProperties.cpp
  arangod/VocBase/Properties/UserInputCollectionProperties.cpp
Labels: cinfra, cla-signed

#18539 [CINFRA-719] Fix CollectionGroups test
  tests/js/server/replication2/replication2-collectiongroups-cluster.js
Labels: cinfra, cla-signed

#18510 Bug-fix/slack-community
  README
  README.md
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/supportView.ejs
  utils/generateREADME.sh
Labels: 1 Bug, cla-signed

#18553 [CINFRA] fix cppcheck warnings
  arangod/Replication2/IScheduler.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLogMetrics.h
  arangod/Replication2/ReplicatedLog/TermIndexMapping.cpp
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
Labels: cinfra, cla-signed

#18554 Remove prototype state tests
  tests/js/common/shell/shell-prototype-state-cluster.js_DISABLED
  tests/test-definitions-rlog.txt
Labels: cinfra, cla-signed

#18522 MDS-1001: Optimize Access to last element in Path.
  CHANGELOG
  arangod/Aql/CMakeLists.txt
  arangod/Aql/GraphOptimizerRules.cpp
  arangod/Aql/GraphOptimizerRules.h
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRulesFeature.cpp
  tests/js/server/aql/aql-optimizer-rule-last-access-on-path.js
  tests/js/server/aql/aql-traversal-projections.js
Labels: cla-signed

#18543 [GORDO-xxx] Speed up testing
  tests/js/common/shell/shell-pregel-basics-example.js
  tests/js/common/shell/shell-pregel-multicollection-edgecol.js
  tests/js/common/shell/shell-pregel-random.js
  tests/js/common/shell/shell-pregel-start-cluster.js
Labels: 3 Pregel, cla-signed

#18549 Make InCaches independent of WorkerConfig
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/IncomingCache.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/State.h
  arangod/Pregel/Worker/Worker.cpp
Labels: 3 Pregel, cla-signed

#18551 Fix cppcheck issue in QueryRegistry
  arangod/Aql/QueryRegistry.cpp
Labels: cla-signed

#18540 improve shutdown times (useful for testing)
  CHANGELOG
  arangod/RestHandler/RestShutdownHandler.cpp
Labels: cla-signed

#18512 Bug fix 3.9/slack community
  README
  README.md
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/supportView.ejs
Labels: 1 Bug, cla-signed

#18511 Bug fix 3.10/slack community
  README
  README.md
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/supportView.ejs
Labels: 1 Bug, cla-signed

#18513 [GORDO-1598] Send status updates from worker
  arangod/Pregel/Conductor/Handler.h
  arangod/Pregel/GraphStore/GraphLoader.cpp
  arangod/Pregel/GraphStore/GraphLoader.h
  arangod/Pregel/GraphStore/GraphStorer.cpp
  arangod/Pregel/GraphStore/GraphStorer.h
  arangod/Pregel/SpawnActor.h
  arangod/Pregel/SpawnMessages.h
  arangod/Pregel/Statistics.h
  arangod/Pregel/StatusActor.h
  arangod/Pregel/StatusMessages.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/State.h
  arangod/Pregel/Worker/Worker.cpp
Labels: 3 Pregel, cla-signed

#18547 fix several issues reported by cppcheck
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Aql/OptimizerRulesCluster.cpp
  arangod/Aql/QuerySnippet.cpp
  arangod/Aql/ShortestPathExecutor.tpp
  arangod/Aql/TraversalExecutor.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeoIndex/Index.cpp
  arangod/GeoIndex/Index.h
  arangod/Graph/GraphOperations.cpp
  arangod/Graph/GraphOperations.h
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.h
Labels: cla-signed

#18530 Fix for query execution stats info
  CHANGELOG
  arangod/Aql/SingleRemoteModificationExecutor.cpp
  tests/js/server/aql/aql-optimizer-rule-optimize-cluster-single-document-operations.js
Labels: cla-signed

#18567 Enable debug logging for tests.
  etc/testing/arangod-common.conf
Labels: cinfra, cla-signed

#18565 [CINFRA] Fixing Windows
  arangod/Agency/Supervision.cpp
Labels: cinfra, cla-signed

#18548 [BTS-1285] Fix issue with sync tests not finishing
  arangod/RestHandler/RestReplicationHandler.cpp
  tests/test-definitions.txt
Labels: 1 Bug, cla-signed

#18558 testing: don't run chaos in coverage builds
  .circleci/base_config.yml
  .circleci/generate_config.py
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#18552 Fix potential race when cloning repository in CircleCI
  .circleci/base_config.yml
Labels: cla-signed

#18521 BTS-1292 Cleanup dangling links
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterTypes.cpp
  arangod/Cluster/ClusterTypes.h
  arangod/Cluster/RebootTracker.cpp
  arangod/Cluster/RebootTracker.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/Pregel/CMakeLists.txt
  arangod/VocBase/LogicalView.cpp
  tests/Cluster/RebootTrackerTest.cpp
  tests/js/client/shell/shell-arangosearch-dangling-link-cluster.js
Labels: cla-signed

#18562 [GORDO-1600] Multiple Quiver<V,E>s in a Worker
  arangod/Pregel/GraphStore/CMakeLists.txt
  arangod/Pregel/GraphStore/GraphLoader.cpp
  arangod/Pregel/GraphStore/GraphLoader.h
  arangod/Pregel/GraphStore/GraphLoaderBase.h
  arangod/Pregel/GraphStore/GraphVPackBuilderStorer.cpp
  arangod/Pregel/GraphStore/GraphVPackBuilderStorer.h
  arangod/Pregel/GraphStore/Magazine.cpp
  arangod/Pregel/GraphStore/Magazine.h
  arangod/Pregel/GraphStore/Quiver.h
  arangod/Pregel/VertexComputation.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/State.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel, cla-signed

#18576 remove js code out of cpp directory
  arangod/Pregel/examples/create-graph.js
  arangod/Pregel/examples/list-importer.js
Labels: 3 Pregel, cla-signed

#18560 Fix for coordinator-metrics-cluster.js
  js/client/modules/@arangodb/testutils/testrunner.js
  js/common/modules/@arangodb/test-helper-common.js
  tests/js/client/shell/api/multi/coordinator-metrics-cluster.js
Labels: 3 - Testing, cla-signed

#18571 testing: need to actually invoke the code :/
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: 3 - Testing, cla-signed

#18568 testing: stabilize test by disabling deferred foxx startup
  tests/js/client/server_parameters/foxx-enable-true.js
Labels: cla-signed

#18570 fix more cppcheck errors
  arangod/RestHandler/RestGraphHandler.cpp
  arangod/RestHandler/RestGraphHandler.h
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/Utils/CollectionNameResolver.cpp
  utils/cppcheck.sh
Labels: cla-signed

#18577 [CINFRA] Add missing preconditions to collection groups supervision
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
Labels: cinfra, cla-signed

#18578 [CINFRA-732] Fix lock inversions in the leader
  arangod/Replication2/ReplicatedLog/CMakeLists.txt
  arangod/Replication2/ReplicatedLog/Components/IInMemoryLogManager.h
  arangod/Replication2/ReplicatedLog/Components/IStorageManager.h
  arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp
  arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.h
  arangod/Replication2/ReplicatedLog/Components/StorageManager.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  tests/Replication2/CMakeLists.txt
  tests/Replication2/Mocks/StorageManagerMock.h
  tests/Replication2/ReplicatedLog/Components/CompactionManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
Labels: cinfra, cla-signed

#18564 [GORDO-1600] [GORDO-1585] Parallel vertex processing on worker
  arangod/Pregel/AggregatorHandler.cpp
  arangod/Pregel/AggregatorHandler.h
  arangod/Pregel/GraphStore/Magazine.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel, cla-signed

#18572 fix potential UB in CollectionNameResolver
  arangod/Utils/CollectionNameResolver.cpp
Labels: 9 Ready to Merge, cla-signed

#17601 [DOC-59] Bug fix/js api forward ttl cursor option
  CHANGELOG
  js/client/modules/@arangodb/arango-database.js
  js/client/modules/@arangodb/arango-statement.js
  js/common/modules/@arangodb/arango-statement-common.js
  tests/js/client/shell/shell-query.js
  tests/js/client/shell/shell-statement.js
Labels: 1 Bug, 3 AQL, 3 JS API, cla-signed

#18585 [CINFRA] Disabled transaction tests
  tests/js/client/shell/transaction/shell-transaction.js
Labels: cinfra, cla-signed

#18591 [CINFRA] Race in Restart Tests
  arangod/Cluster/ClusterInfo.cpp
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
  lib/Rest/GeneralResponse.cpp
  tests/js/client/restart/test-restart-replication2-database.js
Labels: cinfra, cla-signed

#18588 Use minReplicationFactor instead of default.
  arangod/VocBase/VocbaseInfo.cpp
Labels: cinfra, cla-signed

#18581 [GORDO-1599] Re-parallelise graph storing
  arangod/Pregel/GraphStore/GraphStorer.cpp
  arangod/Pregel/GraphStore/GraphStorer.h
  arangod/Pregel/GraphStore/GraphStorerBase.h
  arangod/Pregel/GraphStore/GraphVPackBuilderStorer.cpp
  arangod/Pregel/GraphStore/GraphVPackBuilderStorer.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/Worker.cpp
Labels: 3 Pregel, cla-signed

#18589 [CINFRA-735] Fix lock inversion on the Leader Log/State
  CMakePresets.json
  arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp
  arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  lib/Inspection/include/Inspection/SaveInspectorBase.h
Labels: 9 Ready to Merge, cinfra, cla-signed

#18592 Work around MSVC parse error
  arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp
Labels: cinfra, cla-signed

#18555 testing: make sure to disable test cleanup after failure
  js/client/modules/@arangodb/testsuites/server_permissions.js
Labels: cla-signed

#18575 [GORDO-1606] Read specific status out of pregel collection (by pid)
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/REST/RestControlPregelHandler.cpp
  arangod/Pregel/REST/RestControlPregelHandler.h
  arangod/Pregel/StatusWriter/CollectionStatusWriter.cpp
  arangod/Pregel/StatusWriter/CollectionStatusWriter.h
  arangod/V8Server/v8-pregel.cpp
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/client/shell/shell-pregel-status-writer.js
  tests/js/common/shell/shell-pregel-random.js
  tests/js/common/shell/shell-pregel-status-writer.js
Labels: 3 Pregel, cla-signed

#18573 fix potential UB in CollectionNameResolver
  arangod/Utils/CollectionNameResolver.cpp
Labels: 9 Ready to Merge, cla-signed

#18593 add possibility to provide Arguments to cluster instances similar as to the starter
  CONTRIBUTING.md
  js/client/modules/@arangodb/testutils/instance.js
Labels: cla-signed

#18599 Fix logging for server health status
  arangod/Cluster/ClusterInfo.cpp
Labels: cla-signed

#18601 [CINFRA-736] Fix memory leaks in RocksDBEngine
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#18598 testing: stabilize test by disabling deferred foxx startup (#18568)
  tests/js/client/server_parameters/foxx-enable-true.js
Labels: 3 Foxx, 3 - Testing, cla-signed

#18594 Fix for coordinator-metrics-cluster.js - 2
  tests/js/client/shell/api/multi/coordinator-metrics-cluster.js
Labels: 3 - Testing, cla-signed

#18603 correct a CHANGELOG entry
  CHANGELOG
Labels: 3 Documentation, cla-signed

#18605 add more tests
  tests/js/client/server_parameters/test-extended-names-collections-off.js
  tests/js/client/server_parameters/test-extended-names-collections-on.js
Labels: 3 - Testing, cla-signed

#18609 Keep shared_ptr alive while iterating.
  arangod/VocBase/LogicalCollection.cpp
Labels: 3 Cluster, 9 Ready to Merge, cla-signed

#18444 SEARCH-459 Don't show analyzerDefinitions in ensureIndex output in cluster
  arangod/VocBase/Methods/Indexes.cpp
  tests/js/common/shell/shell-ensure-inverted-index.js
Labels: cla-signed

#18619 [CINFRA-740] Enable Transaction Tests
  tests/js/client/shell/transaction/shell-transaction.js
Labels: cinfra, cla-signed

#18626 [CINFRA-739] Flaky JS test
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#18611 [CINFRA-716] Fix effective write concern
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  arangod/Replication2/ReplicatedLog/Supervision.h
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.cpp
  js/common/modules/@arangodb/testutils/collection-groups-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
  tests/Replication2/ReplicatedLog/Supervision/SupervisionSimulationTest.cpp
  tests/Replication2/ReplicatedLog/Supervision/SupervisionTest.cpp
  tests/js/server/replication2/replication2-replicated-state-document-store.js
  tests/js/server/replication2/replication2-supervision-collection-groups.js
Labels: 9 Ready to Merge, cinfra, cla-signed

#18622 fix for date library printing #STDOFF messages
  3rdParty/date/src/tz.cpp
Labels: cla-signed, 3.11-Stabilization

#18623 fix for date library printing #STDOFF messages
  3rdParty/date/src/tz.cpp
Labels: cla-signed

#18624 fix for date library printing #STDOFF messages
  3rdParty/date/src/tz.cpp
Labels: cla-signed

#18621 testing: better test errors
  tests/js/client/server_parameters/www-authenticate.js
Labels: 3 - Testing, cla-signed, 3.11-Stabilization

#18607 Drain all syncer queues.
  arangod/Cluster/ClusterInfo.cpp
Labels: cla-signed, 3.11-Stabilization

#18583 testing: on the client we now only have the global instanceManager object anymore.
  js/client/modules/@arangodb/test-helper.js
  tests/js/client/communication/test-communication.js
Labels: cla-signed, 3.11-Stabilization

#18569 Fix red test on SatelliteGraphs
  arangod/Graph/GraphManager.cpp
Labels: cinfra, cla-signed

#18633 remove global namespace declaration
  arangod/IResearch/IResearchFilterFactoryCommon.h
Labels: cla-signed, 3.11-Stabilization

#18610 [PREGEL] Make pregel API again backwards compatible to 3.10
  arangod/Pregel/REST/RestControlPregelHandler.cpp
Labels: 3 Pregel, cla-signed, 3.11-Stabilization

#18643 use local foxx zip to reduce test flakyness
  tests/js/client/server_parameters/foxx-enable-true.js
Labels: 3 Foxx, 3 - Testing, cla-signed, 3.11-Stabilization

#18642 Use proper gtest macros for more visibility.
  tests/Cache/PlainCache.cpp
Labels: 3 - Testing, cla-signed, 3.11-Stabilization

#18604 fix vpack handling for orphan collections
  arangod/V8Server/v8-general-graph.cpp
  tests/js/common/shell/shell-general-graph.js
Labels: cla-signed, 3.11-Stabilization

#18644 Disable crash handler tests on mac
  lib/Basics/debugging.cpp
  tests/js/server/recovery/crash-handler-segfault-nonwindows-nonmac-noinstr.js
Labels: 9 Ready to Merge, cla-signed, 3.11-Stabilization

#18635 Set agency log level to debug on agents.
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing, cla-signed, 3.11-Stabilization

#18636 Using ASSERT_EQ in DurationTest
  tests/Pregel/DurationTest.cpp
Labels: 3 Pregel, cla-signed, 3.11-Stabilization

#18645 Fix race in kill queries test
  arangod/Aql/RestAqlHandler.cpp
  lib/Futures/include/Futures/SharedState.h
  lib/Futures/include/Futures/Try.h
Labels: cla-signed, 3.11-Stabilization

#18649 [CINFRA] Use after move
  arangod/Replication2/ReplicatedState/ReplicatedStateFeature.h
Labels: 9 Ready to Merge, cinfra, cla-signed

#18647 don't trip over a testcase not having a message
  js/client/modules/@arangodb/testutils/result-processing.js
Labels: 3 - Testing, cla-signed, 3.11-Stabilization

#18660 use local foxx zip to reduce test flakyness (#18643)
  tests/js/client/server_parameters/foxx-enable-true.js
Labels: 3 Foxx, 3 - Testing, cla-signed

#18654 added test for intermediate commits
  arangod/Transaction/Methods.cpp
  tests/js/client/shell/shell-replication-intermediate-commits-cluster.js
Labels: cla-signed, 3.11-Stabilization

#18650 Try to stabilize load-balancing-key-generator-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-key-generator-noauth-cluster.js
Labels: cla-signed, 3.11-Stabilization

#18648 Apply intermediate commits during getting shards in sync
  CHANGELOG
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Transaction/Methods.cpp
  tests/js/client/shell/shell-replication-intermediate-commits-cluster.js
Labels: cla-signed

#18652 Apply intermediate commits during getting shards in sync
  CHANGELOG
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Transaction/Methods.cpp
  tests/js/client/shell/shell-replication-intermediate-commits-cluster.js
Labels: cla-signed

#18638 Do not forward GET and POST request in PregelCommand RestHandler
  arangod/Pregel/REST/RestControlPregelHandler.cpp
  arangod/Pregel/StatusWriter/CollectionStatusWriter.cpp
Labels: 3 Pregel, cla-signed, 3.11-Stabilization

#18661 Fix testCreateInParallel
  tests/js/common/shell/shell-index.js
Labels: cla-signed, 3.11-Stabilization

#18625 [3.10] SEARCH-461 cache only leaders
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchLink.cpp
  tests/IResearch/IResearchIndexTest.cpp
  tests/Mocks/Servers.cpp
Labels: 3 ArangoSearch, cla-signed

#18658 backport all changes to the endpoints test, so we better see it faili…
  js/client/modules/@arangodb/testsuites/endpoints.js
Labels: 3 - Testing, cla-signed

#18668 add more code ownership
  .github/CODEOWNERS
Labels: cla-signed, 3.11-Stabilization

#18673 Fix cppcheck nightly
  arangod/Aql/QueryCursor.cpp
  arangod/Aql/ShardLocking.cpp
  arangod/Aql/StandaloneCalculation.cpp
  arangod/Graph/Providers/SingleServerProvider.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxMethods.cpp
  arangod/VocBase/Methods/Databases.cpp
  client-tools/Shell/V8ClientConnection.cpp
Labels: 9 Ready to Merge, cla-signed, 3.11-Stabilization

#18679 FE-222: fix search & index views
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.208dea6d.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.208dea6d.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.208dea6d.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.3634bdf0.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.3634bdf0.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.3634bdf0.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/useCreateInvertedIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/views/Components/ViewLinksBreadcrumbs.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/constants.ts
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18671 silence windows warning while reading pipes
  lib/Basics/win-utils.cpp
Labels: cla-signed, 3.11-Stabilization

#18680 Splitting shell-transaction tests
  CONTRIBUTING.md
  tests/js/client/shell/transaction/shell-transaction-part1-R1.js
  tests/js/client/shell/transaction/shell-transaction-part1-R2.js_DISABLED
  tests/js/client/shell/transaction/shell-transaction-part2-R1.js
  tests/js/client/shell/transaction/shell-transaction-part2-R2.js_DISABLED
  tests/js/client/shell/transaction/shell-transaction.inc
  tests/test-definitions-rlog.txt
Labels: 9 Ready to Merge, cla-signed, 3.11-Stabilization

#18682 SEARCH-466 Fix viewOnly options in links
  CHANGELOG
  arangod/IResearch/IResearchCommon.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  tests/js/common/aql/aql-view-arangosearch-ddl-combined.js
Labels: 3 ArangoSearch, cla-signed, Backport Needed, 3.11-Stabilization

#18687 More logging in case of failure
  tests/js/client/load-balancing/load-balancing-key-generator-noauth-cluster.js
Labels: cla-signed, 3.11-Stabilization

#18531 3.10 backport for query execution stats fix
  CHANGELOG
  arangod/Aql/SingleRemoteModificationExecutor.cpp
  tests/js/server/aql/aql-optimizer-rule-optimize-cluster-single-document-operations.js
Labels: 9 Ready to Merge, cla-signed

#18646 Bug fix-3.10/mds 1098 dropping variable content to early
  CHANGELOG
  arangod/Aql/TraversalNode.cpp
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
Labels: cla-signed

#18653 added test for intermediate commits
  arangod/Transaction/Methods.cpp
  tests/js/client/shell/shell-replication-intermediate-commits-cluster.js
Labels: 9 Ready to Merge, cla-signed

#18395 [3.10] [BTS-1148] Fix DBServer Race in running Query abort on DBServer
  CHANGELOG
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/RestAqlHandler.cpp
  lib/Futures/SharedState.h
  lib/Futures/Try.h
  tests/js/common/shell/test-kill-queries.js
Labels: cla-signed

#18685 Wait for the supervision to actually kill the job.
  tests/js/server/resilience/move/moving-shards-cluster.inc
Labels: cla-signed, 3.11-Stabilization

#18678 Reset log level to normal on agents after startup.
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: cla-signed, 3.11-Stabilization

#18688 FE-212 - bugfix: links not getting removed when copying from another view in UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.208dea6d.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.208dea6d.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.208dea6d.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.dcc4d7f0.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.dcc4d7f0.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.dcc4d7f0.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/views/forms/inputs/CopyFromInput.tsx
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18698 Remove automatic circleci run on devel branch
  .circleci/config.yml
Labels: cla-signed

#18686 [PREGEL] Use number of cores as upper cut for pregel parallelism
  js/server/modules/@arangodb/test-helper.js
  tests/js/common/shell/shell-pregel-multicollection-edgecol.js
Labels: 3 Pregel, cla-signed, 3.11-Stabilization

#18697 Minor rewording of `--database.extended-names` description
  arangod/RestServer/DatabaseFeature.cpp
Labels: 3 Documentation, cla-signed

#18695 Fix cppcheck nightly
  arangod/Aql/ShardLocking.cpp
Labels: 9 Ready to Merge, cla-signed, 3.11-Stabilization

#18672 generate unique tasks id for foxx queue jobs
  arangod/V8Server/v8-dispatcher.cpp
  js/server/modules/@arangodb/foxx/queues/manager.js
Labels: 3 - Testing, cla-signed, 3.11-Stabilization

#18690 DOC-431 | APM-594 | Add `optimizeTopK` to `arangosearch` View and inverted index DocuBlocks
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
Labels: 3 Documentation, cla-signed

#18616 [GORDO-1619] Fix parallelism for processing vertices
  arangod/Pregel/Iterators.h
  arangod/Pregel/Statistics.h
  arangod/Pregel/Worker/CMakeLists.txt
  arangod/Pregel/Worker/VertexProcessor.cpp
  arangod/Pregel/Worker/VertexProcessor.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel, cla-signed, 3.11-Stabilization

#18617 [GORDO-1621] Respect parallelism while storing results
  arangod/Pregel/GraphStore/GraphStorer.cpp
  arangod/Pregel/GraphStore/GraphStorer.h
  arangod/Pregel/GraphStore/Magazine.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/Worker.cpp
Labels: 3 Pregel, cla-signed, 3.11-Stabilization

#18618 [GORDO-1620] Respect parallelism for graph loading
  arangod/Pregel/DatabaseTypes.h
  arangod/Pregel/GraphStore/GraphLoader.cpp
  arangod/Pregel/GraphStore/GraphLoader.h
  arangod/Pregel/GraphStore/LoadableVertexShard.h
Labels: 3 Pregel, cla-signed, 3.11-Stabilization

#18664 [PREGEL] Add pregel api tests for starting pregel
  tests/js/client/shell/api/pregel.js
Labels: 3 Pregel, cla-signed, 3.11-Stabilization

#18669 Updated test that was failing
  tests/js/client/server_parameters/exclusive-collections-off.js
Labels: cla-signed, 3.11-Stabilization

#18634 rearrange some members for more clarity
  arangod/Network/Methods.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
Labels: cla-signed, 3.11-Stabilization

#18659 testing: do the failurepoints check as the verry first thing
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: cla-signed, 3.11-Stabilization

#18703 ES-1515: Make metrics output format configurable
  CHANGELOG
  arangod/IResearch/IResearchDataStore.cpp
  arangod/Metrics/Batch.h
  arangod/Metrics/ClusterMetricsFeature.cpp
  arangod/Metrics/ClusterMetricsFeature.h
  arangod/Metrics/Counter.cpp
  arangod/Metrics/Counter.h
  arangod/Metrics/Gauge.h
  arangod/Metrics/Histogram.h
  arangod/Metrics/IBatch.h
  arangod/Metrics/Metric.h
  arangod/Metrics/MetricsFeature.cpp
  arangod/Metrics/MetricsFeature.h
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  js/client/modules/@arangodb/test-helper.js
  js/server/modules/@arangodb/test-helper.js
  tests/IResearch/IResearchLinkTest.cpp
  tests/Metrics/MetricsFeatureTest.cpp
  tests/Metrics/MetricsTest.cpp
  tests/js/client/server_parameters/test-ensure-whitespace-metrics-format-off.js
  tests/js/client/server_parameters/test-ensure-whitespace-metrics-format-on.js
Labels: 3 Metrics, cla-signed

#18708 Bug fix-3.10/mds 1098 dropping variable content to early
  CHANGELOG
  arangod/Aql/TraversalNode.cpp
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-graphs.js
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
Labels: cla-signed

#18694 Bug fix/fix wait for satellites
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/ClusterQuery.h
  arangod/Aql/EnumeratePathsNode.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionEngine.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/QueryOptions.cpp
  arangod/Aql/QueryOptions.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/TraversalNode.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Graph/GraphManager.cpp
  arangod/Graph/GraphManager.h
  arangod/Graph/GraphOperations.cpp
  arangod/Sharding/ShardingInfo.h
  arangod/Transaction/Methods.cpp
Labels: 1 Bug, 3 AQL, cla-signed, 3.11-Stabilization

#18700 Trying to work around OS cache
  tests/js/server/recovery/foxx-directories.js
Labels: cla-signed, 3.11-Stabilization

#18631 [CINFRA-742] Simplify DocumentStateMachineTests
  tests/Replication2/CMakeLists.txt
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/CoreTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/DocumentStateMachineTest.h
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/FollowerTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/LeaderTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/ShardHandlerTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/SnapshotTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/TransactionHandlerTest.cpp
Labels: cinfra, cla-signed

#18715 Documentation 3.10/cache only leaders
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_collection_loadIndexesIntoMemory.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_collection_properties.md
  Documentation/DocuBlocks/Rest/Databases/post_api_database.md
  Documentation/DocuBlocks/Rest/Graphs/1_structs.md
  Documentation/DocuBlocks/Rest/Graphs/post_api_gharial.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_dump.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_logger_follow.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
  Documentation/Metrics/arangodb_shards_not_replicated.yaml
  Documentation/Metrics/arangodb_shards_out_of_sync.yaml
  arangod/IResearch/IResearchFeature.cpp
Labels: 3 Documentation, cla-signed

#18714 Documentation/cache-only-leaders
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_collection_loadIndexesIntoMemory.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_collection_properties.md
  Documentation/DocuBlocks/Rest/Databases/post_api_database.md
  Documentation/DocuBlocks/Rest/Graphs/1_structs.md
  Documentation/DocuBlocks/Rest/Graphs/post_api_gharial.md
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_dump.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_logger_follow.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
  Documentation/Metrics/arangodb_shards_not_replicated.yaml
  Documentation/Metrics/arangodb_shards_out_of_sync.yaml
  arangod/IResearch/IResearchFeature.cpp
Labels: 3 Documentation, cla-signed

#18718 [CINFRA-595] Custom type handler
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/RestHandler/RestBaseHandler.cpp
  arangod/RestHandler/RestBaseHandler.h
  arangod/RestHandler/RestDocumentStateHandler.cpp
  arangod/RestHandler/RestDocumentStateHandler.h
Labels: 9 Ready to Merge, cinfra, cla-signed

#18710 Automatically repair revision trees after shard sync failures
  CHANGELOG
  Documentation/Metrics/arangodb_sync_tree_rebuilds_total.yaml
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/ClusterEngine/ClusterTransactionCollection.cpp
  arangod/ClusterEngine/ClusterTransactionState.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/RocksDBTransactionState.cpp
  arangod/Transaction/Hints.h
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  arangod/VocBase/Methods/Indexes.cpp
  tests/Mocks/Servers.cpp
  tests/js/client/shell/shell-replication-auto-repair-cluster.js
Labels: cla-signed, 3.11-Stabilization

#18702 ES-1515: Make metrics output format configurable
  CHANGELOG
  arangod/IResearch/IResearchDataStore.cpp
  arangod/Metrics/Batch.h
  arangod/Metrics/ClusterMetricsFeature.cpp
  arangod/Metrics/ClusterMetricsFeature.h
  arangod/Metrics/Counter.cpp
  arangod/Metrics/Counter.h
  arangod/Metrics/Gauge.h
  arangod/Metrics/Histogram.h
  arangod/Metrics/IBatch.h
  arangod/Metrics/Metric.h
  arangod/Metrics/MetricsFeature.cpp
  arangod/Metrics/MetricsFeature.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  js/client/modules/@arangodb/test-helper.js
  js/server/modules/@arangodb/test-helper.js
  tests/IResearch/IResearchLinkTest.cpp
  tests/Metrics/MetricsFeatureTest.cpp
  tests/Metrics/MetricsTest.cpp
  tests/js/client/server_parameters/test-ensure-whitespace-metrics-format-off.js
  tests/js/client/server_parameters/test-ensure-whitespace-metrics-format-on.js
Labels: cla-signed, 3.11-Stabilization

#18719 do not make _globalVersion go backwards
  arangod/Auth/TokenCache.cpp
  arangod/Auth/UserManager.cpp
  arangod/Auth/UserManager.h
Labels: cla-signed, 3.11-Stabilization

#18721 avoid startup warnings on ARM
  arangod/RestServer/EnvironmentFeature.cpp
Labels: cla-signed, 3.11-Stabilization

#18725 testing: proper namespacing for gtests
  js/client/modules/@arangodb/testsuites/gtest.js
  js/client/modules/@arangodb/testutils/result-processing.js
  tests/test-definitions.txt
Labels: cla-signed, 3.11-Stabilization

#18683 Log delays in sending, adjust commit timeouts.
  3rdParty/fuerte/include/fuerte/message.h
  3rdParty/fuerte/src/GeneralConnection.h
  3rdParty/fuerte/src/H1Connection.cpp
  CHANGELOG
  Documentation/Metrics/arangodb_network_dequeue_duration.yaml
  Documentation/Metrics/arangodb_network_response_duration.yaml
  Documentation/Metrics/arangodb_network_send_duration.yaml
  Documentation/Metrics/arangodb_network_unfinished_sends_total.yaml
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
  arangod/Network/Utils.cpp
  arangod/RestHandler/RestStatusHandler.cpp
Labels: cla-signed, 3.11-Stabilization

#18737 Avoid lockup with trace logging and log rotation, BTS-1326.
  lib/Basics/files.cpp
  lib/Logger/LogAppenderFile.cpp
Labels: cla-signed, 3.11-Stabilization

#18709 [PREGEL] Fix load-balancing-pregel-auth-cluster test
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelOptions.h
  tests/js/client/load-balancing/load-balancing-pregel-auth-cluster.js
Labels: 3 Pregel, cla-signed, 3.11-Stabilization

#18699 ES-1515: Make metrics export format configurable
  CHANGELOG
  arangod/IResearch/IResearchDataStore.cpp
  arangod/Metrics/Batch.h
  arangod/Metrics/ClusterMetricsFeature.cpp
  arangod/Metrics/ClusterMetricsFeature.h
  arangod/Metrics/Counter.cpp
  arangod/Metrics/Counter.h
  arangod/Metrics/Gauge.h
  arangod/Metrics/Histogram.h
  arangod/Metrics/IBatch.h
  arangod/Metrics/Metric.h
  arangod/Metrics/MetricsFeature.cpp
  arangod/Metrics/MetricsFeature.h
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  js/client/modules/@arangodb/test-helper.js
  js/server/modules/@arangodb/test-helper.js
  tests/IResearch/IResearchLinkTest.cpp
  tests/Metrics/MetricsFeatureTest.cpp
  tests/Metrics/MetricsTest.cpp
  tests/js/client/server_parameters/test-ensure-whitespace-metrics-format-off.js
  tests/js/client/server_parameters/test-ensure-whitespace-metrics-format-on.js
Labels: 3 Metrics, cla-signed

#18500 Feature 3.10/sent time accounting
  3rdParty/fuerte/include/fuerte/message.h
  3rdParty/fuerte/src/GeneralConnection.h
  3rdParty/fuerte/src/H1Connection.cpp
  CHANGELOG
  Documentation/Metrics/arangodb_network_dequeue_duration.yaml
  Documentation/Metrics/arangodb_network_response_duration.yaml
  Documentation/Metrics/arangodb_network_send_duration.yaml
  Documentation/Metrics/arangodb_network_unfinished_sends_total.yaml
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
  arangod/Network/Utils.cpp
  arangod/RestHandler/RestStatusHandler.cpp
Labels: cla-signed

#18738 Avoid lockup with trace logging and log rotation, BTS-1326.
  lib/Basics/files.cpp
  lib/Logger/LogAppenderFile.cpp
Labels: cla-signed

#18740 Do not candidate if we became follower just before.
  arangod/Agency/Constituent.cpp
  arangod/Agency/Constituent.h
Labels: 9 Ready to Merge, cinfra, cla-signed, 3.11-Stabilization

#18745 Do not specify invalid replicationFactor and numberOfShards.
  tests/js/client/shell/api/pregel.js
  tests/js/common/shell/shell-pregel-components.js
Labels: cinfra, cla-signed

#18734 FE-241: bugfix - filter predefined queries
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1f0a07a8.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1f0a07a8.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1f0a07a8.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.db0e4ebd.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.db0e4ebd.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.db0e4ebd.js.gz
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18742 FE-247: bugfix - missing storedValues field in persistent index
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.273ec4fc.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.273ec4fc.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.273ec4fc.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ae44716c.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ae44716c.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.ae44716c.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreatePersistentIndex.ts
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18717 fix issues reported by cppcheck
  arangod/IResearch/GeoAnalyzer.cpp
  arangod/RestServer/EnvironmentFeature.cpp
  arangod/Utils/UrlHelper.cpp
  lib/VPackDeserializer/parameter-list.h
Labels: cla-signed

#18749 [CINFRA-746] MoveShard flaky tests
  tests/js/server/resilience/move/moving-shards-cluster.inc
Labels: cinfra, cla-signed

#18739 Avoid lockup with trace logging and log rotation, BTS-1326.
  lib/Basics/files.cpp
  lib/Logger/LogAppenderFile.cpp
Labels: cla-signed

#18748 Fix for delaySupervisionFailoverActions
  tests/js/server/resilience/move/moving-shards-cluster.inc
Labels: 9 Ready to Merge, cla-signed, 3.11-Stabilization

#18705 backport xml fixes
  js/client/modules/@arangodb/testsuites/chaos.js
  js/client/modules/@arangodb/testutils/result-processing.js
  js/client/modules/@arangodb/testutils/testing.js
  js/client/modules/@arangodb/testutils/testrunner.js
  scripts/test/site_config.py
Labels: cla-signed

#18684 Log delays in sending, adjust commit timeouts.
  3rdParty/fuerte/include/fuerte/message.h
  3rdParty/fuerte/src/GeneralConnection.h
  3rdParty/fuerte/src/H1Connection.cpp
  CHANGELOG
  Documentation/Metrics/arangodb_network_dequeue_duration.yaml
  Documentation/Metrics/arangodb_network_response_duration.yaml
  Documentation/Metrics/arangodb_network_send_duration.yaml
  Documentation/Metrics/arangodb_network_unfinished_sends_total.yaml
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
  arangod/Network/Utils.cpp
  arangod/RestHandler/RestStatusHandler.cpp
Labels: cla-signed

#18706 backport xml fixes
  js/client/modules/@arangodb/testsuites/export.js
  js/client/modules/@arangodb/testsuites/importing.js
  js/client/modules/@arangodb/testutils/result-processing.js
  js/client/modules/@arangodb/testutils/testing.js
  scripts/test/site_config.py
Labels: 3 - Testing, cla-signed

#18751 Fix test failure metrics cluster
  tests/js/client/shell/api/multi/coordinator-metrics-cluster.js
Labels: cla-signed, 3.11-Stabilization

#18752 Increase container size for shell_server_aql tests to avoid OOM kills
  tests/test-definitions.txt
Labels: cla-signed

#18727 do not make _globalVersion go backwards
  CHANGELOG
  arangod/Auth/TokenCache.cpp
  arangod/Auth/UserManager.cpp
  arangod/Auth/UserManager.h
Labels: cla-signed, 3.10.6

#18732 Bug fix 3.10/proper namespacing for gtests
  js/client/modules/@arangodb/testsuites/gtest.js
  js/client/modules/@arangodb/testutils/result-processing.js
Labels: cla-signed

#18736 testing: rta-makedata debugging
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
Labels: 3 - Testing, cla-signed

#18723 FE-238 - auto-login support on core web UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoUsers.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/userBarView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userBarView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.9a6b3dd3.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.9a6b3dd3.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.9a6b3dd3.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.f65cbcd5.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.f65cbcd5.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.f65cbcd5.js.gz
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18712 Automatically repair revision trees after shard sync failures
  CHANGELOG
  Documentation/Metrics/arangodb_sync_tree_rebuilds_total.yaml
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  tests/Mocks/Servers.cpp
  tests/js/client/shell/shell-replication-auto-repair-cluster.js
Labels: cla-signed

#18711 Automatically repair revision trees after shard sync failures
  CHANGELOG
  Documentation/Metrics/arangodb_sync_tree_rebuilds_total.yaml
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  tests/Mocks/Servers.cpp
  tests/js/client/shell/shell-replication-auto-repair-cluster.js
Labels: cla-signed, 3.10.6

#18757 BTS-1292 Cleanup dangling links (#18521)
  CHANGELOG
  arangod/Agency/AddFollower.cpp
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterTypes.cpp
  arangod/Cluster/ClusterTypes.h
  arangod/Cluster/RebootTracker.cpp
  arangod/Cluster/RebootTracker.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/VocBase/LogicalView.cpp
  tests/Cluster/RebootTrackerTest.cpp
  tests/js/client/shell/shell-arangosearch-dangling-link-cluster.js
Labels: 3 ArangoSearch, cla-signed, 3.10.6

#18753 expose extended naming convention in frontendConfig
  arangod/RestServer/BootstrapFeature.cpp
  arangod/RestServer/FrontendFeature.cpp
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/server/bootstrap/modules/internal.js
Labels: 3 UI, cla-signed, 3.11-Stabilization

#18772 Enable scheduled pipeline triggers on CircleCI
  .circleci/config.yml
Labels: cla-signed

#18754 fix validation of leading and trailing spaces in names
  lib/Utilities/NameValidator.cpp
  tests/Utils/NameValidatorTest.cpp
  tests/VocBase/KeyGeneratorTest.cpp
Labels: cla-signed, 3.11-Stabilization
