Repository arangodb/arangodb, pull requests merged in 2023-06, with the labels that each got.

#19135 [BTS-1396]
  CHANGELOG
  arangod/Utils/SupportInfoBuilder.cpp
  client-tools/Shell/TelemetricsHandler.cpp
Labels: cla-signed

#19138 Fix TimeStampTransformer
  lib/Inspection/CMakeLists.txt
  lib/Inspection/include/Inspection/Transformers.h
  tests/Inspection/CMakeLists.txt
  tests/Inspection/TransformerTest.cpp
Labels: cla-signed

#19133 Bug fix/bts 846
  CHANGELOG
  arangod/Indexes/Index.cpp
  tests/js/server/aql/aql-persistent-index.js
Labels: cla-signed

#19140 SEARCH-479 Use less memory for n removes in single transaction
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchPrimaryKeyFilter.cpp
  arangod/IResearch/IResearchPrimaryKeyFilter.h
  tests/IResearch/IResearchDocumentTest.cpp
Labels: cla-signed, Backport Needed

#19152 Use medium container for hot backup tests to avoid OOM kills.
  tests/test-definitions.txt
Labels: cla-signed

#19153 Fix IN lookup
  CHANGELOG
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/server/aql/aql-index-rearming.js
Labels: 3 AQL, cla-signed

#19154 Fix IN lookup
  CHANGELOG
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/server/aql/aql-index-rearming.js
Labels: 3 AQL, cla-signed

#19132 micro-optimizations for cache performance
  arangod/Cache/BucketState.cpp
  arangod/Cache/BucketState.h
  arangod/Cache/Cache.h
  arangod/Cache/PlainBucket.cpp
  arangod/Cache/PlainBucket.h
  arangod/Cache/PlainCache.cpp
  arangod/Cache/PlainCache.h
  arangod/Cache/TransactionalBucket.cpp
  arangod/Cache/TransactionalBucket.h
  arangod/Cache/TransactionalCache.cpp
  arangod/Cache/TransactionalCache.h
  arangod/Graph/TraverserDocumentCache.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  tests/Cache/Manager.cpp
  tests/Cache/PlainBucket.cpp
  tests/Cache/PlainCache.cpp
  tests/Cache/Rebalancer.cpp
  tests/Cache/TransactionalBucket.cpp
  tests/Cache/TransactionalCache.cpp
  tests/Cache/TransactionalCacheVPackKeyHasher.cpp
  tests/Cache/TransactionalStore.cpp
Labels: cla-signed

#18867 [GORDO] Add status details in every conductor state
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/StatusWriter/StatusEntry.h
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/common/shell/shell-pregel-random.js
Labels: 3 Pregel, cla-signed

#19161 [SEARCH-479] [APM-766] bug-fix/search backports 3.11
  CHANGELOG
  arangod/IResearch/GeoFilter.cpp
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchPrimaryKeyFilter.cpp
  arangod/IResearch/IResearchPrimaryKeyFilter.h
  tests/IResearch/IResearchDocumentTest.cpp
  tests/js/server/aql/aql-geo.inc
  tests/js/server/aql/aql-index-hints.js
  tests/js/server/aql/aql-inverted-index.js
Labels: 3 ArangoSearch, cla-signed

#19162 [SEARCH-479] [APM-766] bug-fix/search backports 3.10
  CHANGELOG
  arangod/IResearch/GeoFilter.cpp
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchPrimaryKeyFilter.cpp
  arangod/IResearch/IResearchPrimaryKeyFilter.h
  tests/IResearch/IResearchDocumentTest.cpp
  tests/js/server/aql/aql-index-hints.js
  tests/js/server/aql/aql-inverted-index.js
Labels: 3 ArangoSearch, cla-signed

#19167 fixed BTS-1435
  CHANGELOG
  arangod/Aql/Expression.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-remove-regression.js
Labels: 3 AQL, cla-signed

#19165 Fix BTS-1435
  CHANGELOG
  arangod/Aql/Expression.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-remove-regression.js
Labels: 3 AQL, cla-signed

#19166 fixed BTS-1435
  CHANGELOG
  arangod/Aql/Expression.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-remove-regression.js
Labels: 3 AQL, cla-signed

#19172 3.9: Update OpenSSL to 1.1.1u
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#19171 3.10: Update OpenSSL to 1.1.1u
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#19169 3.11: Update OpenSSL to 3.0.9
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#19170 Upgrade OpenSSL to 3.1.1
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#19179 Update OpenSSL in build container
  .circleci/base_config.yml
  scripts/build/README.md
  scripts/build/arangodb-build.Dockerfile
  scripts/build/build-image.sh
  scripts/build/install-openssl.sh
Labels: 3 Build, cla-signed

#19186 Maintenance shutdown hanger
  arangod/Cluster/ClusterInfo.cpp
Labels: cla-signed

#18729 [BTS-1325] Don't go to sleep forever
  CHANGELOG
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AsyncExecutor.cpp
  arangod/Aql/AsyncExecutor.h
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionEngine.h
  arangod/Aql/ExecutionNodeId.h
  arangod/Aql/ExecutionState.cpp
  arangod/Aql/ExecutionState.h
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/SharedQueryState.cpp
  arangod/Aql/SharedQueryState.h
  lib/Assertions/AssertionConditionalLogger.h
  lib/Basics/Identifier.h
  tests/Aql/AqlExecutorTestCase.cpp
  tests/Aql/AqlExecutorTestCase.h
  tests/Aql/AsyncExecutorTest.cpp
  tests/Aql/ExecutorTestHelper.cpp
  tests/Aql/ExecutorTestHelper.h
  tests/Aql/WaitingExecutionBlockMock.cpp
  tests/Aql/WaitingExecutionBlockMock.h
  tests/CMakeLists.txt
  tests/IResearch/IResearchViewNodeTest.cpp
  tests/Mocks/FakeScheduler.cpp
  tests/Mocks/FakeScheduler.h
  tests/Mocks/MockQuery.h
  tests/Mocks/Servers.cpp
  tests/Mocks/Servers.h
Labels: 1 Bug, 3 AQL, 9 Ready to Merge, cla-signed

#19181 Fix typos in hotbackup error messages
  client-tools/Backup/arangobackup.cpp
Labels: cla-signed

#19183 [3.11] Update OpenSSL in build container
  .circleci/base_config.yml
  scripts/build/README.md
  scripts/build/arangodb-build.Dockerfile
  scripts/build/build-image.sh
Labels: 3 Build, cla-signed

#19160 [3.11] Set default enterprise branch to 3.11 for CircleCI on 3.11 branch
  .circleci/base_config.yml
Labels: cla-signed

#19192 Don't abandon promise
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
Labels: cla-signed

#19189 [CINFRA-780] Report reboot id and use in election
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.h
  arangod/Replication2/ReplicatedLog/Supervision.cpp
  tests/Replication2/ReplicatedLog/Supervision/SupervisionTest.cpp
Labels: cla-signed

#19194 Fixing Node API.
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Agency/AddFollower.cpp
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/NodeLoadInspector.h
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/Store.cpp
  arangod/Agency/Supervision.cpp
  tests/Agency/NodeLoadTest.cpp
  tests/Maintenance/MaintenanceTest.cpp
Labels: cla-signed

#19054 Feature/cinfra 749 rest replication handler
  .circleci/config.yml
  arangod/RestHandler/RestReplicationHandler.cpp
  tests/js/client/shell/api/api-replication.js
Labels: cla-signed

#19203 Adjust soft-write-concern tests
  tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js
Labels: cinfra, cla-signed

#19123 improve representation of crashed arangod in testfailures.txt
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance-manager.js
Labels: 3 - Testing, cla-signed

#19211 [CIRCLECI] Fix clang format job
  .circleci/base_config.yml
Labels: cla-signed

#19210 [BTS-1452] fix cppcheck issues
  arangod/Agency/Agent.cpp
  arangod/Agency/State.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Metrics/ClusterMetricsFeature.cpp
  arangod/Network/Methods.cpp
  arangod/Replication/ReplicationApplier.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
Labels: cla-signed

#19198 [BTS-1451] Avoid cppcheck warnings "Ineffective call of function 'substr'"
  arangod/Agency/AgencyFeature.cpp
  arangod/Cluster/ClusterFeature.cpp
  arangod/RestHandler/RestImportHandler.cpp
  lib/Basics/StringUtils.cpp
  lib/Basics/files.cpp
  lib/ProgramOptions/ArgumentParser.h
  lib/ProgramOptions/Option.cpp
  lib/ProgramOptions/ProgramOptions.cpp
Labels: cla-signed

#19156 Use libunwind in jemalloc heap profiling
  3rdParty/CMakeLists.txt
  3rdParty/jemalloc/CMakeLists.txt
  CHANGELOG
  CMakeLists.txt
  arangod/CMakeLists.txt
  tests/CMakeLists.txt
  tests/js/client/server_parameters/test-memory-profiling-noncluster.js
Labels: cla-signed

#19177 [BTS-1325] [3.11] Don't go to sleep forever
  CHANGELOG
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AsyncExecutor.cpp
  arangod/Aql/AsyncExecutor.h
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionEngine.h
  arangod/Aql/ExecutionNodeId.h
  arangod/Aql/ExecutionState.cpp
  arangod/Aql/ExecutionState.h
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/SharedQueryState.cpp
  arangod/Aql/SharedQueryState.h
  lib/Assertions/AssertionConditionalLogger.h
  lib/Basics/Identifier.h
  tests/Aql/AqlExecutorTestCase.cpp
  tests/Aql/AqlExecutorTestCase.h
  tests/Aql/AsyncExecutorTest.cpp
  tests/Aql/ExecutorTestHelper.cpp
  tests/Aql/ExecutorTestHelper.h
  tests/Aql/WaitingExecutionBlockMock.cpp
  tests/Aql/WaitingExecutionBlockMock.h
  tests/CMakeLists.txt
  tests/IResearch/IResearchViewNodeTest.cpp
  tests/Mocks/FakeScheduler.cpp
  tests/Mocks/FakeScheduler.h
  tests/Mocks/MockQuery.h
  tests/Mocks/Servers.cpp
  tests/Mocks/Servers.h
Labels: 9 Ready to Merge, cla-signed

#19182 [BTS-1325] [3.10] Don't go to sleep forever
  CHANGELOG
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AsyncExecutor.cpp
  arangod/Aql/AsyncExecutor.h
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionEngine.h
  arangod/Aql/ExecutionNodeId.h
  arangod/Aql/ExecutionState.cpp
  arangod/Aql/ExecutionState.h
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/SharedQueryState.cpp
  arangod/Aql/SharedQueryState.h
  lib/Basics/Identifier.h
  tests/Aql/AqlExecutorTestCase.cpp
  tests/Aql/AqlExecutorTestCase.h
  tests/Aql/AsyncExecutorTest.cpp
  tests/Aql/ExecutorTestHelper.cpp
  tests/Aql/ExecutorTestHelper.h
  tests/Aql/WaitingExecutionBlockMock.cpp
  tests/Aql/WaitingExecutionBlockMock.h
  tests/CMakeLists.txt
  tests/Mocks/FakeScheduler.cpp
  tests/Mocks/FakeScheduler.h
  tests/Mocks/MockQuery.h
  tests/Mocks/Servers.cpp
  tests/Mocks/Servers.h
Labels: 9 Ready to Merge, cla-signed

#19201 DOC-479 | Next batch can be requested from `POST /_api/cursor/<cursor-id>/<batch-id>` even if `allowRetry` is `false`
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor_cursor.md
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor_cursor_batch.md
Labels: 3 Documentation, cla-signed

#19202 DOC-479 | Next batch can be requested from `POST /_api/cursor/<cursor-id>/<batch-id>` even if `allowRetry` is `false`
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor_cursor.md
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor_cursor_batch.md
Labels: 3 Documentation, cla-signed

#19196 SEARCH-476 Fix fst builder 3.9
  3rdParty/iresearch/core/utils/fstext/fst_builder.hpp
  3rdParty/iresearch/core/utils/fstext/fst_string_weight.h
  CHANGELOG
Labels: 3 ArangoSearch, cla-signed

#19221 Fix set out of sync for very old iresearch links
  arangod/IResearch/IResearchDataStore.cpp
Labels: 3 ArangoSearch, 3 Upgrade, cla-signed, 3 Recovery

#19222 Fix set out of sync for very old iresearch links 3.10
  arangod/IResearch/IResearchDataStore.cpp
Labels: 3 ArangoSearch, 3 Upgrade, cla-signed, 3 Recovery

#19223 Fix set out of sync for very old iresearch links 3.11
  arangod/IResearch/IResearchDataStore.cpp
Labels: 3 ArangoSearch, 3 Upgrade, cla-signed, 3 Recovery

#19225 Supress cppcheck error.
  arangod/IResearch/IResearchFeature.h
Labels: cla-signed

#19239 Data Race in ArangoDump
  client-tools/Dump/DumpFeature.cpp
Labels: 3 Cluster, 3 ImportExport, TSan, cla-signed

#19130 [FE-15] Make keyboard shortcuts easier to discover
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/versionCheck.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/navigationView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
  js/apps/system/_admin/aardvark/APP/frontend/scss/_navbar.scss
Labels: 3 UI, 9 Review Required, cla-signed

#19245 Chore/cinfra fix cppcheck staging
  arangod/Agency/ResignLeadership.cpp
  arangod/RestHandler/RestDocumentStateHandler.cpp
Labels: cla-signed

#19242 Reenable retry createCollection for Replication1
  arangod/Cluster/ClusterCollectionMethods.cpp
Labels: cla-signed

#19191 DOC-474 | Add `legacyPolygons` option to geo index DocuBlock
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_geo.md
Labels: 3 Documentation, 3 Geo, cla-signed

#19232 Bug fix 3.11/telemetrics force string persisted
  arangod/Utils/SupportInfoBuilder.cpp
Labels: 9 Ready to Merge, cla-signed

#19247 Supress cppcheck error. (#19225)
  arangod/IResearch/IResearchFeature.h
Labels: cla-signed

#19262 Medium prio lockups in AgencyCache and Query shutdown, BTS-1475, BTS-1486
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/Cluster/AgencyCache.cpp
  tests/js/client/shell/shell-med-queue-blocked-cluster.js
Labels: cla-signed

#19260 Medium prio lockups in AgencyCache and Query shutdown, BTS-1475, BTS-1486
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/Cluster/AgencyCache.cpp
  tests/js/client/shell/shell-med-queue-blocked-cluster.js
Labels: cla-signed

#19254 Medium prio lockups in AgencyCache and Query shutdown, BTS-1475, BTS-1486
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/Cluster/AgencyCache.cpp
  tests/js/client/shell/shell-med-queue-blocked-cluster.js
Labels: cla-signed

#19149 Simplify and fix timepointToString and stringToTimepoint
  lib/Basics/TimeString.h
Labels: cla-signed

#19090 FE-285: bugfix - use post request for query download
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.211e6aca.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.211e6aca.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.211e6aca.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.85870ec0.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.85870ec0.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.85870ec0.js.gz
Labels: 1 Bug, 3 UI, cla-signed

#19212 FE-240 - fix - disable JSON editor when viewing inverted index
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.372afdca.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.372afdca.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.372afdca.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.3d595a03.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.3d595a03.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.3d595a03.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/components/jsonEditor/ControlledJSONEditor.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexFormJSONEditor.tsx
Labels: 3 UI, cla-signed

#19258 Use CircleCI context for sccache config
  .circleci/base_config.yml
Labels: cla-signed

#19237 Allow to specify a factory for non default-constructible types
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.h
  lib/Inspection/include/Inspection/Access.h
  lib/Inspection/include/Inspection/Factory.h
  lib/Inspection/include/Inspection/LoadInspectorBase.h
  tests/Inspection/VPackLoadTest.cpp
  tests/Inspection/VPackSaveTest.cpp
  tests/Inspection/include/Inspection/InspectionTestHelper.h
Labels: cla-signed

#19256 [CINFRA-787] Commit participants config sequentially
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
Labels: cinfra, cla-signed

#19269 Try to stabilize a possibly flaky test
  tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js
Labels: cla-signed

#19253 cinfra - Made all Graphs OneShard aware
  arangod/Graph/Graph.cpp
  arangod/Graph/Graph.h
  arangod/Graph/GraphManager.cpp
Labels: cla-signed

#19236 DOC-398 | DOC-477 | Improve View examples
  Documentation/DocuBlocks/Rest/Views/delete_api_view.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_name.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_properties.md
  Documentation/DocuBlocks/Rest/Views/get_api_views.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_rename.md
Labels: 3 Documentation, cla-signed

#19234 DOC-398 | DOC-477 | Add `search-alias` examples, improve View examples
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_pregel.md
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Views/delete_api_view_view.md
  Documentation/DocuBlocks/Rest/Views/get_api_view.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_view.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_searchalias.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_view_rename.md
Labels: 3 Documentation, cla-signed

#19277 Suppress cppcheck false positive
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.cpp
Labels: cinfra, cla-signed

#19188 [BTS-1443] Fix Github issue #19175
  arangod/Aql/Condition.cpp
  tests/js/server/aql/aql-traversal-graph-object-regression.js
Labels: 1 Bug, cla-signed

#19264 [BTS-1443] Fix Github issue #19175
  CHANGELOG
  arangod/Aql/Condition.cpp
  tests/js/server/aql/aql-traversal-graph-object-regression.js
Labels: cla-signed

#19048 DOC-398 | DOC-477 | Add `search-alias` examples, improve View examples
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_pregel.md
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Views/delete_api_view_view.md
  Documentation/DocuBlocks/Rest/Views/get_api_view.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_view.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_searchalias.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_view_rename.md
Labels: 3 Documentation, cla-signed

#19205 [APM-662] Improve ExecutionNodes Memory Tracking
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ClusterNodes.h
  arangod/Aql/CollectNode.cpp
  arangod/Aql/CollectNode.h
  arangod/Aql/DistributeConsumerNode.cpp
  arangod/Aql/DistributeConsumerNode.h
  arangod/Aql/EnumeratePathsNode.cpp
  arangod/Aql/EnumeratePathsNode.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  arangod/Aql/ModificationNodes.cpp
  arangod/Aql/ModificationNodes.h
  arangod/Aql/MultipleRemoteModificationNode.cpp
  arangod/Aql/MultipleRemoteModificationNode.h
  arangod/Aql/MutexNode.cpp
  arangod/Aql/MutexNode.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/ShortestPathNode.h
  arangod/Aql/SortNode.cpp
  arangod/Aql/SortNode.h
  arangod/Aql/SubqueryEndExecutionNode.cpp
  arangod/Aql/SubqueryEndExecutionNode.h
  arangod/Aql/SubqueryStartExecutionNode.cpp
  arangod/Aql/SubqueryStartExecutionNode.h
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraversalNode.h
  arangod/Aql/WindowNode.cpp
  arangod/Aql/WindowNode.h
  tests/Aql/MockTypedNode.cpp
  tests/Aql/MockTypedNode.h
Labels: cla-signed

#19249 [CINFRA-781] Have leaders track their participants' RebootIds
  arangod/Agency/AgencyPaths.h
  arangod/Cluster/ClusterTypes.cpp
  arangod/Cluster/ClusterTypes.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/RebootTracker.cpp
  arangod/Cluster/RebootTracker.h
  arangod/Replication2/ReplicatedLog/AgencyLogSpecification.h
  arangod/Replication2/ReplicatedLog/AgencySpecificationInspectors.h
  arangod/Replication2/ReplicatedLog/CMakeLists.txt
  arangod/Replication2/ReplicatedLog/DefaultRebootIdCache.cpp
  arangod/Replication2/ReplicatedLog/DefaultRebootIdCache.h
  arangod/Replication2/ReplicatedLog/IRebootIdCache.h
  arangod/Replication2/ReplicatedLog/LogEntries.cpp
  arangod/Replication2/ReplicatedLog/LogEntries.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/LogStatus.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.cpp
  arangod/Transaction/Options.h
  arangod/VocBase/VocBaseLogManager.cpp
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  lib/Basics/RebootId.h
  tests/Replication2/CMakeLists.txt
  tests/Replication2/Mocks/RebootIdCacheMock.h
  tests/Replication2/ReplicatedState/StateManagerTest.cpp
  tests/js/server/replication2/replication2-maintenance-replicated-log-cluster.js
  tests/js/server/replication2/replication2-regression.js
  tests/js/server/replication2/replication2-replicated-log-entry-cluster.js
Labels: 9 Ready to Merge, cinfra, cla-signed

#19272 Bug fix/cinfra fix unstable leader election tests
  js/client/modules/@arangodb/test-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
Labels: cla-signed

#19127 [FE-20] Implement locale placeholder
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.bf11c9c2.css
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.bf11c9c2.css.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.407a080a.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.407a080a.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.407a080a.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b8c227a7.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b8c227a7.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.b8c227a7.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.9512fedafa8e56b22d68.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.beab3f58283dd9683614.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.916656a297b1a9fa698b.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.abd255e8d4a57cfa076a.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.8d11d1e159ab0e14c0e6.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.9c9c164e699d486b5abf.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.81dc9b21d2ced318e9ae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.bcf2ba9ef2bd549116a9.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-dark.994d1553f409200f5901.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-icon.35807d6e11925bd44973.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb.609cd935d9d34dab5e6b.eot.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/favicon.909457142f6be9dae418.ico.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.ed6298903ae1554c7f3e.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.f0af1680f082547a7aae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/jsoneditor-icons.ffbb30248a6fc9adfc7f.svg.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/CollationConfig.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/NormConfig.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/StemConfig.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/TextConfig.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/inputs/LocaleInput.tsx
Labels: 3 UI, 9 Review Required, 3 Search, cla-signed

#19241 [FE-229] improve shard rebalancing UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/rebalanceShardsView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/shardDistributionView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/rebalanceShardsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/shardDistributionView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.407a080a.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.407a080a.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.407a080a.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.76987d1e.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.76987d1e.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.76987d1e.js.gz
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/src/App.js
  js/apps/system/_admin/aardvark/APP/react/src/actions/arangodb.tsx
  js/apps/system/_admin/aardvark/APP/react/src/actions/taskRepeater.tsx
  js/apps/system/_admin/aardvark/APP/react/src/configureStore.tsx
  js/apps/system/_admin/aardvark/APP/react/src/setupProxy.js
  js/apps/system/_admin/aardvark/APP/react/src/store/cluster/actions.tsx
  js/apps/system/_admin/aardvark/APP/react/src/store/cluster/middleware.tsx
  js/apps/system/_admin/aardvark/APP/react/src/store/cluster/reducer.tsx
  js/apps/system/_admin/aardvark/APP/react/src/store/cluster/types.tsx
  js/apps/system/_admin/aardvark/APP/react/src/store/index.tsx
  js/apps/system/_admin/aardvark/APP/react/src/store/logging/middleware.tsx
  js/apps/system/_admin/aardvark/APP/react/src/utils/arangoClient.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/ShardsReactView.js
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/distribution/LegacyShardDistributionContent.jsx
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/distribution/RebalanceShards.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/distribution/ShardDistributionReactView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/moveShard.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/overview.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/shardInfoRow.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/shards/specifics.tsx
  js/apps/system/_admin/aardvark/APP/react/yarn.lock
Labels: 1 Feature, 3 UI, 9 Review Required, cla-signed

#19267 [3.11] Fix TimeStampTransformer
  lib/Inspection/CMakeLists.txt
  lib/Inspection/include/Inspection/Transformers.h
Labels: cla-signed

#19268 [3.11] Simplify and fix timepointToString and stringToTimepoint
  lib/Basics/TimeString.h
Labels: cla-signed

#19286 Fix missing includes
  arangod/Replication2/ReplicatedLog/Components/ISnapshotManager.h
  arangod/Replication2/ReplicatedLog/Components/IStateHandleManager.h
  arangod/VocBase/Properties/KeyGeneratorProperties.h
Labels: cla-signed

#19281 Fix unstable test
  tests/IResearch/IResearchLinkTest.cpp
Labels: cla-signed, Backport Needed

#19289 Remove staging/replication2 remnants
  .circleci/base_config.yml
  .circleci/config.yml
  js/client/modules/@arangodb/testsuites/gtest.js
  tests/test-definitions-rlog.txt
Labels: cla-signed

#19091 bug-fix-3.11/FE-285: bugfix - use post request for query download
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 1 Bug, 3 UI, cla-signed

#19120 bug-fix-3.11/FE-287: fix number validation for replicationFactor and writeConcern
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
Labels: 1 Bug, 3 UI, cla-signed

#19219 bug-fix-3.11/FE-240 - fix - disable JSON editor when viewing inverted index
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/ControlledJSONEditor.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexFormJSONEditor.tsx
Labels: 1 Bug, 3 UI, cla-signed

#19122 bug-fix-3.9/FE-287: fix number validation for replicationFactor and writeConcern
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
Labels: 1 Bug, 3 UI, cla-signed

#19290 Show "dynamic default" hint for startup options
  CHANGELOG
  lib/ProgramOptions/Option.cpp
Labels: cla-signed

#19291 Dont show write query options in explain output
  CHANGELOG
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#19128 [3.11] [FE-20] Implement locale placeholder
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.5dd34b3e.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.5dd34b3e.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.5dd34b3e.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.e602e1f3.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.e602e1f3.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.e602e1f3.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/CollationForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/NormForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/StemForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/TextForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/forms/inputs/LocaleInput.tsx
Labels: 3 UI, 9 Review Required, 3 Search, cla-signed

#19235 DOC-398 | DOC-477 | Add `search-alias` examples, improve View examples
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Pregel/get_api_control_pregel_pregel.md
  Documentation/DocuBlocks/Rest/Queries/post_api_cursor.md
  Documentation/DocuBlocks/Rest/Views/delete_api_view_view.md
  Documentation/DocuBlocks/Rest/Views/get_api_view.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_view.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/get_api_view_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/patch_api_view_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_searchalias.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_view_properties_arangosearch.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_view_properties_searchalias.md
  Documentation/DocuBlocks/Rest/Views/put_api_view_view_rename.md
Labels: 3 Documentation, cla-signed

#19246 DOC-347 | DOC-460 | Add `description` field to optimizer rules & add missing
  CHANGELOG
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/OptimizerRulesFeature.h
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
Labels: cla-signed

#19282 DOC-347 | DOC-460 | Add `description` field to optimizer rules & add missing
  CHANGELOG
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/OptimizerRulesFeature.h
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
Labels: 3 Documentation, cla-signed

#19283 DOC-347 | DOC-460 | Add `description` field to optimizer rules & add missing
  CHANGELOG
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/OptimizerRulesFeature.h
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
Labels: 3 Documentation, cla-signed

#19271 [3.10] Simplify and fix timepointToString and stringToTimepoint
  lib/Basics/TimeString.h
Labels: cla-signed

#19303 Fix data race.
  client-tools/Dump/DumpFeature.cpp
Labels: cla-signed

#19294 Avoid busy looping when locking collections with a timeout [3.10]
  CHANGELOG
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: cla-signed

#19293 Avoid busy looping when locking collections with a timeout
  CHANGELOG
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: cla-signed

#19295 Avoid busy looping when locking collections with a timeout [3.11]
  CHANGELOG
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: cla-signed

#19296 Docs: `keepNull: false` does not remove attributes in arrays
  Documentation/DocuBlocks/Rest/Documents/patch_api_document_collection.md
  Documentation/DocuBlocks/Rest/Documents/patch_api_document_collection_key.md
  Documentation/DocuBlocks/Rest/Documents/post_api_document_collection.md
  Documentation/DocuBlocks/Rest/Documents/post_api_document_collection_multiple.md
  Documentation/DocuBlocks/Rest/Graphs/patch_api_gharial_graph_edge_collection_edge.md
  Documentation/DocuBlocks/Rest/Graphs/patch_api_gharial_graph_vertex_collection_vertex.md
  Documentation/DocuBlocks/Rest/Graphs/put_api_gharial_graph_edge_collection_edge.md
  Documentation/DocuBlocks/Rest/Graphs/put_api_gharial_graph_vertex_collection_vertex.md
Labels: 3 Documentation, cla-signed

#19297 Docs: `keepNull: false` does not remove attributes in arrays
  Documentation/DocuBlocks/Rest/Documents/patch_api_document_collection.md
  Documentation/DocuBlocks/Rest/Documents/patch_api_document_collection_key.md
  Documentation/DocuBlocks/Rest/Documents/post_api_document_collection.md
  Documentation/DocuBlocks/Rest/Documents/post_api_document_collection_multiple.md
  Documentation/DocuBlocks/Rest/Graphs/patch_api_gharial_graph_edge_collection_edge.md
  Documentation/DocuBlocks/Rest/Graphs/patch_api_gharial_graph_vertex_collection_vertex.md
  Documentation/DocuBlocks/Rest/Graphs/put_api_gharial_graph_edge_collection_edge.md
  Documentation/DocuBlocks/Rest/Graphs/put_api_gharial_graph_vertex_collection_vertex.md
Labels: 3 Documentation, cla-signed

#19298 Docs: `keepNull: false` does not remove attributes in arrays
  Documentation/DocuBlocks/Rest/Documents/patch_api_document_collection.md
  Documentation/DocuBlocks/Rest/Documents/patch_api_document_collection_key.md
  Documentation/DocuBlocks/Rest/Documents/post_api_document_collection.md
  Documentation/DocuBlocks/Rest/Documents/post_api_document_collection_multiple.md
  Documentation/DocuBlocks/Rest/Graphs/patch_api_gharial_graph_edge_collection_edge.md
  Documentation/DocuBlocks/Rest/Graphs/patch_api_gharial_graph_vertex_collection_vertex.md
  Documentation/DocuBlocks/Rest/Graphs/put_api_gharial_graph_edge_collection_edge.md
  Documentation/DocuBlocks/Rest/Graphs/put_api_gharial_graph_vertex_collection_vertex.md
Labels: 3 Documentation, cla-signed

#19311 Fixed wrong changelog entry
  CHANGELOG
Labels: cla-signed

#19292 BTS-1495 Inverted index cause incorrect plan optimization
  arangod/Aql/Condition.cpp
  arangod/Aql/Condition.h
  arangod/Aql/ConditionFinder.cpp
  arangod/Aql/ConditionFinder.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  tests/js/common/aql/aql-arangosearch-inverted-index-optimization.js
Labels: cla-signed, Backport Needed

#19321 [CINFRA] Waiting for rebootId to change
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#19299 Fixed BTS-1490
  CHANGELOG
  arangod/Aql/ModificationExecutor.cpp
  tests/js/server/aql/aql-memory-limit.js
Labels: cla-signed

#19306 Fixes second issue of BTS-1490
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/common/shell/shell-explain-cluster.js
  tests/js/server/aql/aql-optimizer-rule-undistribute-remove-after-enum-coll-cluster.js
Labels: cla-signed

#19322 Make lower and upper bound values for cache fill ratio configurable
  CHANGELOG
  arangod/Cache/Cache.cpp
  arangod/Cache/CacheManagerFeature.cpp
  arangod/Cache/CacheManagerFeature.h
  arangod/Cache/Common.h
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/Cache/PlainBucket.h
  arangod/Cache/Table.cpp
  arangod/Cache/Table.h
  arangod/Cache/TransactionalBucket.h
  tests/Cache/Manager.cpp
  tests/Cache/PlainCache.cpp
  tests/Cache/Rebalancer.cpp
  tests/Cache/Table.cpp
  tests/Cache/TransactionalCache.cpp
  tests/Cache/TransactionalCacheVPackKeyHasher.cpp
  tests/Cache/TransactionsWithBackingStore.cpp
Labels: cla-signed

#19301 Fixed BTS-1490
  CHANGELOG
  arangod/Aql/ModificationExecutor.cpp
  tests/js/server/aql/aql-memory-limit.js
Labels: cla-signed

#19307 Fixes second issue of BTS-1490
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/common/shell/shell-explain-cluster.js
  tests/js/server/aql/aql-optimizer-rule-undistribute-remove-after-enum-coll-cluster.js
Labels: cla-signed

#19302 Fixed BTS-1490
  CHANGELOG
  arangod/Aql/ModificationExecutor.cpp
  tests/js/server/aql/aql-memory-limit.js
Labels: cla-signed

#19308 Fixes second issue of BTS-1490
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/common/shell/shell-explain-cluster.js
  tests/js/server/aql/aql-optimizer-rule-undistribute-remove-after-enum-coll-cluster.js
Labels: cla-signed

#19334 testing: try to acquire an agency dump even if we are in force shutdown
  js/client/modules/@arangodb/testutils/instance-manager.js
Labels: cla-signed

#19327 Fixed BTS-1495 Inverted index cause incorrect plan optimization 3.11
  arangod/Aql/Condition.cpp
  arangod/Aql/Condition.h
  arangod/Aql/ConditionFinder.cpp
  arangod/Aql/ConditionFinder.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  tests/js/common/aql/aql-arangosearch-inverted-index-optimization.js
Labels: cla-signed

#19333 [CINFRA-791] Fix supervision flaky test
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra, cla-signed

#19300 Replication2.0 micro optimizations
  arangod/Cluster/UpdateReplicatedLogAction.cpp
  arangod/Replication2/Methods.cpp
  arangod/Replication2/ReplicatedLog/LogEntries.cpp
  arangod/Replication2/ReplicatedLog/LogEntries.h
  arangod/Replication2/ReplicatedLog/NetworkAttachedFollower.cpp
  arangod/Replication2/ReplicatedLog/NetworkAttachedFollower.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/V8Server/v8-replicated-logs.cpp
  arangod/VocBase/VocBaseLogManager.cpp
  tests/Replication2/Mocks/FakeFollower.h
Labels: cla-signed

#19329 clean up temporary backup directory if backup fails
  CHANGELOG
Labels: cla-signed

#19320 Fixed incorrect assumption in wfs=false test
  tests/js/server/replication2/replication2-supervision-wait-for-sync-false.js
Labels: cla-signed

#19344 Try to make cluster tests tsan run more useful
  arangod/Agency/Supervision.cpp
  arangod/Metrics/ClusterMetricsFeature.cpp
  arangod/Metrics/ClusterMetricsFeature.h
  arangod/Pregel/PregelFeature.cpp
  tsan_arangodb_suppressions.txt
Labels: cla-signed

#19331 clean up temporary backup directory if backup fails
  CHANGELOG
Labels: cla-signed

#19330 clean up temporary backup directory if backup fails
  CHANGELOG
Labels: cla-signed

#19350 Checkout enterprise only when building enterprise
  .circleci/base_config.yml
Labels: cla-signed

#19326 Use CircleCI context for sccache config
  .circleci/base_config.yml
Labels: cla-signed

#19347 [APM-750] Fix some data races
  arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
  client-tools/Import/SenderThread.cpp
  tsan_arangodb_suppressions.txt
Labels: cla-signed

#19328 Fixed BTS-1495 Inverted index cause incorrect plan optimization 3.10
  arangod/Aql/Condition.cpp
  arangod/Aql/Condition.h
  arangod/Aql/ConditionFinder.cpp
  arangod/Aql/ConditionFinder.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  tests/js/common/aql/aql-arangosearch-inverted-index-optimization.js
Labels: cla-signed

#19345 Optimise runtime lock performance [3.10]
  CHANGELOG
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/Transaction/Manager.h
  lib/Basics/ReadWriteLock.cpp
  lib/Basics/ReadWriteLock.h
  tests/Basics/ReadWriteLockTest.cpp
Labels: cla-signed

#19273 Add grace period for disconnected leaders in active failover
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
  js/client/modules/@arangodb/testsuites/resilience.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  tests/js/client/active-failover/basic.js
  tests/js/client/active-failover/disconnected-leader-nonwindows.js
Labels: cla-signed
