Repository arangodb/arangodb, pull requests merged in 2023-03, with the labels that each got.

#17903 [CINFRA-686] Recreate states on start up.
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/DBServerAgencySync.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/Maintenance.h
  arangod/Replication2/ReplicatedLog/LogStatus.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/ReplicatedStateFeature.cpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachineFeature.cpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachineFeature.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.h
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachineFeature.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachineFeature.h
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  js/client/modules/@arangodb/testutils/restart-helper.js
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  tests/Replication2/ReplicatedLog/Integration/MaintenanceTests.cpp
  tests/Replication2/ReplicatedLog/ReplicatedLogConnectTest.cpp
  tests/js/client/restart/test-restart-replication2-database.js
Labels: cinfra, cla-signed

#18223 Added metric for observing the number of replication clients
  CHANGELOG
  Documentation/Metrics/arangodb_replication_clients.yaml
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/ReplicationClients.cpp
  arangod/Replication/ReplicationClients.h
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBSettingsManager.cpp
  arangod/VocBase/vocbase.cpp
  tests/Replication/ReplicationClientsProgressTrackerTest.cpp
Labels: cla-signed

#18166 Some cleanups in base_config.yml
  .circleci/base_config.yml
  .circleci/generate_config.py
  js/client/modules/@arangodb/testsuites/gtest.js
  tests/test-definitions.txt
Labels: cla-signed

#18191 Fix arangorestore API to create _rev on shard leader [BTS-1232].
  CHANGELOG
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: cla-signed

#18000 [GORDO-1509] Use actor framework in pregel
  arangod/Pregel/Actor/include/Actor/ActorPID.h
  arangod/Pregel/Actor/include/Actor/HandlerBase.h
  arangod/Pregel/Actor/include/Actor/Message.h
  arangod/Pregel/Actor/include/Actor/Runtime.h
  arangod/Pregel/ArangoExternalDispatcher.h
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/Conductor/Actor.h
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Messages.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/REST/RestPregelHandler.cpp
  arangod/Pregel/SpawnActor.h
  arangod/Pregel/SpawnMessages.h
  arangod/Pregel/Worker/Actor.h
  arangod/Pregel/Worker/Messages.h
  tests/Pregel/Actor/ActorTest.cpp
  tests/Pregel/Actor/Actors/TrivialActor.h
  tests/Pregel/Actor/MultiRuntimeTest.cpp
  tests/Pregel/Actor/RuntimeTest.cpp
Labels: 3 Pregel, cla-signed

#18221 add options for BlobDB configuration
  CHANGELOG
  arangod/RocksDBEngine/Listeners/RocksDBThrottle.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.h
  js/common/modules/jsunity/jsunity.js
  tests/js/server/recovery/check-warnings-exitzero.js
Labels: cla-signed

#18207 improve debuggability of errors upon database creation failure
  arangod/Cluster/ServerState.h
  arangod/RestHandler/RestDatabaseHandler.cpp
  arangod/VocBase/Methods/Databases.cpp
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/client/modules/@arangodb/test-helper.js
  js/common/modules/@arangodb/test-helper-common.js
  js/server/modules/@arangodb/test-helper.js
  lib/V8/v8-utils.cpp
  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-off.js
  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-on.js
  tests/js/client/shell/shell-auto-refill-index-caches-on-modify-noncluster.js
  tests/js/client/shell/shell-in-background-failures-noncluster.js
  tests/test-definitions.txt
Labels: cla-signed

#18224 add peak memory usage in slow/current query list
  CHANGELOG
  Documentation/DocuBlocks/Rest/AQL/GetApiQueryCurrent.md
  Documentation/DocuBlocks/Rest/AQL/GetApiQuerySlow.md
  arangod/Aql/Functions.cpp
  arangod/Aql/QueryList.cpp
  arangod/Aql/QueryList.h
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryManagementView.js
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/client/shell/api/query-analysis.js
  tests/js/common/shell/multi/shell-query-spec.js
  tests/js/common/shell/shell-query-stream-spec.js
Labels: cla-signed

#18194 Bugfix BTS-1243
  arangod/IResearch/IResearchDataStore.cpp
  arangod/Metrics/ClusterMetricsFeature.cpp
  arangod/Metrics/ClusterMetricsFeature.h
  arangod/RestHandler/RestMetricsHandler.cpp
  tests/IResearch/IResearchLinkTest.cpp
Labels: cla-signed, Backport Needed

#18024 [PREGEL] Use struct for pregel constants
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/PregelOptions.h
  arangod/Pregel/Worker/WorkerConfig.cpp
  arangod/Pregel/Worker/WorkerConfig.h
  tests/js/common/shell/shell-pregel-multicollection-edgecol.js
Labels: 3 Pregel, cla-signed

#18214 [GORDO-1554] Key generation ASSERT inspection
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  tests/js/common/shell/shell-document-babies.js
  tests/js/common/shell/shell-keygen.js
  tests/js/server/aql/aql-optimizer-undistribute-remove-regression.js
Labels: 1 Bug, 9 Waiting for Jenkins, 9 Review Required, cla-signed

#18218 Removed comment from test of BTS-1184
  tests/js/server/aql/aql-geo.inc
Labels: cla-signed

#18219 Removed comment from test in BTS-1184 3.10 backport
  tests/js/server/aql/aql-geo.js
Labels: 3 - Testing, cla-signed

#18227 Make sure testresults are also copied when test fails
  .circleci/base_config.yml
Labels: cla-signed

#18173 Make inspection its own library
  arangod/arangoserver.cmake
  lib/CMakeLists.txt
  lib/Inspection/CMakeLists.txt
  lib/Inspection/include/Inspection/Access.h
  lib/Inspection/include/Inspection/Format.h
  lib/Inspection/include/Inspection/InspectorBase.h
  lib/Inspection/include/Inspection/JsonPrintInspector.h
  lib/Inspection/include/Inspection/LoadInspectorBase.h
  lib/Inspection/include/Inspection/README.md
  lib/Inspection/include/Inspection/SaveInspectorBase.h
  lib/Inspection/include/Inspection/Status.h
  lib/Inspection/include/Inspection/Transformers.h
  lib/Inspection/include/Inspection/Types.h
  lib/Inspection/include/Inspection/VPack.h
  lib/Inspection/include/Inspection/VPackLoadInspector.h
  lib/Inspection/include/Inspection/VPackSaveInspector.h
  lib/Inspection/include/Inspection/VPackWithErrorT.h
  lib/Inspection/include/Inspection/ValidateInspector.h
  lib/Inspection/include/Inspection/detail/Fields.h
  lib/Inspection/include/Inspection/detail/traits.h
  tests/Agency/NodeLoadTest.cpp
  tests/Basics/CMakeLists.txt
  tests/CMakeLists.txt
  tests/Inspection/CMakeLists.txt
  tests/Inspection/InspectionTest.cpp
  tests/Inspection/JsonPrintTest.cpp
  tests/Inspection/VPackLoadTest.cpp
  tests/Inspection/VPackSaveTest.cpp
  tests/Inspection/ValidateTest.cpp
  tests/Inspection/include/Inspection/InspectionTestHelper.h
  tests/Pregel/Actor/CMakeLists.txt
  tests/Pregel/CMakeLists.txt
Labels: cla-signed

#18176 remove unittests directory from the source
  etc/testing/server.pem
  etc/testing/server2.pem
  etc/testing/tls-ca.crt
  etc/testing/tls-ca.key
  etc/testing/tls.keyfile
  js/client/modules/@arangodb/testsuites/endpoints.js
  js/client/modules/@arangodb/testsuites/server_permissions.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/unittest.js
  scripts/test/arangosh.py
  scripts/unittest
  scripts/unittest.ps1
  tests/js/client/server_secrets/tls-rotation.js
Labels: cla-signed

#18236 improve usefulness of debug messages
  arangod/Replication/ReplicationClients.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: cla-signed

#18234 Slick GEO tests to just create each set of data *once* at the beginning in individual collections / views
  tests/js/server/aql/aql-geo.inc
Labels: 3 - Testing, 3 Geo, cla-signed

#18240 don't try to jslint files in UnitTests
  utils/jslint.sh
Labels: 3 - Testing, cla-signed

#18241 Install GDB in testing dockers
  .circleci/base_config.yml
Labels: cla-signed

#18212 QA-367: fix tearDownAll error reporting, lint (#18205)
  js/common/modules/jsunity/jsunity.js
  tests/js/server/replication/aql/replication-aql.js
  tests/js/server/replication/random/replication-random.js
Labels: 3 - Testing, cla-signed

#18211 QA-367: fix tearDownAll error reporting, lint (#18205)
  js/common/modules/jsunity/jsunity.js
  tests/js/server/replication/aql/replication-aql.js
  tests/js/server/replication/random/replication-random.js
Labels: cla-signed

#18116 ES-1428: max number of V8 contexts depends on max threads
  CHANGELOG
  arangod/Scheduler/SchedulerFeature.cpp
  arangod/Scheduler/SchedulerFeature.h
  arangod/V8Server/V8DealerFeature.cpp
  tests/js/common/shell/shell-index.js
Labels: 9 Ready to Merge, cla-signed

#18188 Fix arangorestore API to create _rev on shard leader [BTS-1232].
  CHANGELOG
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: cla-signed

#18203 BTS-1249: Add startup option `--foxx.enable`.
  CHANGELOG
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/ServerSecurityFeature.cpp
  arangod/GeneralServer/ServerSecurityFeature.h
  arangod/Utils/ExecContext.cpp
  arangod/Utils/ExecContext.h
  arangod/V8Server/FoxxFeature.cpp
  arangod/V8Server/FoxxFeature.h
  tests/js/client/server_parameters/foxx-enable-false.js
  tests/js/client/server_parameters/foxx-enable-true.js
Labels: 9 Ready to Merge, cla-signed

#18206 improve debuggability of errors upon database creation failure
  arangod/Cluster/ServerState.h
  arangod/RestHandler/RestDatabaseHandler.cpp
  arangod/VocBase/Methods/Databases.cpp
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  lib/V8/v8-utils.cpp
  tests/js/client/shell/shell-auto-refill-index-caches-on-modify-noncluster.js
  tests/js/client/shell/shell-in-background-failures-noncluster.js
Labels: 9 Ready to Merge, cla-signed

#18222 Added metric for observing the number of replication clients
  CHANGELOG
  Documentation/Metrics/arangodb_replication_clients.yaml
  arangod/Replication/ReplicationClients.cpp
  arangod/Replication/ReplicationClients.h
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBSettingsManager.cpp
  arangod/VocBase/vocbase.cpp
  tests/Replication/ReplicationClientsProgressTrackerTest.cpp
Labels: 9 Ready to Merge, cla-signed

#18230 [GORDO-1554] Key generation ASSERT inspection
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  tests/js/common/shell/shell-document-babies.js
  tests/js/common/shell/shell-keygen.js
  tests/js/server/aql/aql-optimizer-undistribute-remove-regression.js
Labels: 1 Bug, 9 Review Required, 9 Ready to Merge, cla-signed

#18213 reduce the number of elements and timeout for the coverage runs
  tests/js/common/shell/multi/shell-ttl.js
Labels: 3 - Testing, cla-signed

#18246 [CINFRA] Run gtests only once
  tests/test-definitions-rlog.txt
Labels: 9 Ready to Merge, cinfra, cla-signed

#18238 [GORDO-1554] 2
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  tests/js/common/shell/shell-document-babies.js
  tests/js/common/shell/shell-keygen.js
Labels: cla-signed

#18228 Silence compiler warning
  tests/Replication2/Helper/ModelChecker/Actors.cpp
Labels: cla-signed

#18229 Silence Compiler Warning (forward port to staging branch)
  tests/Replication2/Helper/ModelChecker/Actors.cpp
Labels: cla-signed

#18237 Added `--rocksdb.auto-refill-index-caches-on-followers`
  CHANGELOG
  arangod/ClusterEngine/ClusterEngine.h
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.cpp
  arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.h
  arangod/StorageEngine/StorageEngine.h
  arangod/Transaction/Methods.cpp
  js/client/modules/@arangodb/test-helper.js
  js/client/modules/@arangodb/testsuites/server_permissions.js
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/js/client/server_parameters/auto-refill-index-caches-on-followers-off-cluster.js
  tests/js/client/server_parameters/auto-refill-index-caches-on-followers-on-cluster.js
Labels: cla-signed

#18247 [CINFRA] Prototype State Flaky Test
  tests/js/common/shell/shell-prototype-state-cluster.js
Labels: cinfra, cla-signed

#18251 testing: SKIPPED testcase should now indicate the full error
  js/client/modules/@arangodb/testutils/result-processing.js
Labels: cla-signed

#18253 Remove dependency on ApplicationServer from GraphFormat
  arangod/Pregel/Algos/ColorPropagation/ColorPropagation.cpp
  arangod/Pregel/Algos/ColorPropagation/ColorPropagation.h
  arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.cpp
  arangod/Pregel/Algos/DMID/DMID.cpp
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.cpp
  arangod/Pregel/Algos/HITS/HITS.cpp
  arangod/Pregel/Algos/HITSKleinberg/HITSKleinberg.cpp
  arangod/Pregel/Algos/LabelPropagation/LabelPropagation.cpp
  arangod/Pregel/Algos/LineRank/LineRank.h
  arangod/Pregel/Algos/PageRank/PageRank.cpp
  arangod/Pregel/Algos/ReadWrite/ReadWrite.cpp
  arangod/Pregel/Algos/RecoveringPageRank/RecoveringPageRank.h
  arangod/Pregel/Algos/SCC/SCC.cpp
  arangod/Pregel/Algos/SLPA/SLPA.cpp
  arangod/Pregel/Algos/SSSP/SSSP.cpp
  arangod/Pregel/Algos/ShortestPath/ShortestPath.cpp
  arangod/Pregel/Algos/WCC/WCC.cpp
  arangod/Pregel/GraphFormat.h
Labels: 3 Pregel, cla-signed

#18245 improve query optimizer
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/AstNode.cpp
  arangod/Aql/Condition.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-projections.js
Labels: cla-signed

#18255 [CINFRA-696] Fix crashes in AppendEntriesManager on store errors or resign race
  arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
  arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.h
  arangod/Replication2/ReplicatedLog/Components/IAppendEntriesManager.h
  arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
  tests/Replication2/ReplicatedLog/LogFollower/AppendEntriesTest.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#18264 [CINFRA-699] Call acquireSnapshot after becomeFollower
  arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/Components/SnapshotManager.cpp
  arangod/Replication2/ReplicatedLog/Components/SnapshotManager.h
  tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#18250 [GORDO-1547] Remove ConductorState vocbase dependency
  arangod/Agency/AgencyComm.h
  arangod/Graph/Providers/BaseStep.h
  arangod/Pregel/Conductor/CMakeLists.txt
  arangod/Pregel/Conductor/ExecutionStates/CMakeLists.txt
  arangod/Pregel/Conductor/ExecutionStates/CollectionLookup.h
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkers.cpp
  arangod/Pregel/Conductor/ExecutionStates/DatabaseCollectionLookup.h
  arangod/Pregel/Conductor/Messages.h
  arangod/Pregel/Conductor/State.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Statistics.h
  arangod/Pregel/Utils.h
  tests/Pregel/CMakeLists.txt
  tests/Pregel/ConductorStateTest.cpp
Labels: 3 Pregel, cla-signed

#18266 Fix MSVC build issues + don't try to jslint files in UnitTests
  arangod/Pregel/Actor/include/Actor/Actor.h
  tests/IResearch/ExpressionFilterTest.cpp
  tests/IResearch/GeoDistanceFilterTest.cpp
  tests/IResearch/GeoFilterTest.cpp
  utils/jslint-2.0.sh
Labels: 3 - Testing, cla-signed

#18267 Upload test results even if test fails
  .circleci/base_config.yml
Labels: cla-signed

#18257 Spelling (root, docs, utils)
  .githooks/README.md
  CHANGELOG
  CMakeLists.txt
  CONTRIBUTING.md
  Documentation/DocuBlocks/Rest/AQL/delete_api_aqlfunction.md
  Documentation/DocuBlocks/Rest/AQL/get_api_aqlfunction.md
  Documentation/DocuBlocks/Rest/Administration/delete_api_tasks.md
  Documentation/DocuBlocks/Rest/Administration/get_admin_statistics.md
  Documentation/DocuBlocks/Rest/Administration/get_api_return.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_create.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_download.md
  Documentation/DocuBlocks/Rest/BackupRestore/post_admin_backup_upload.md
  Documentation/DocuBlocks/Rest/Bulk/batch_processing.md
  Documentation/DocuBlocks/Rest/Bulk/import_json.md
  Documentation/DocuBlocks/Rest/Collections/1_structs.md
  Documentation/DocuBlocks/Rest/Collections/get_api_collection_figures.md
  Documentation/DocuBlocks/Rest/Collections/post_api_collection.md
  Documentation/DocuBlocks/Rest/Collections/put_api_collection_properties.md
  Documentation/DocuBlocks/Rest/Database/get_api_database_new.md
  Documentation/DocuBlocks/Rest/Documents/delete_multiple_documents.md
  Documentation/DocuBlocks/Rest/Graph/1_structs.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_create_http_examples.md
  Documentation/DocuBlocks/Rest/Graph/general_graph_edge_definition_add_http_examples.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_cluster_inventory.md
  Documentation/DocuBlocks/Rest/Replication/get_api_replication_logger_follow.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_last_tick.md
  Documentation/DocuBlocks/Rest/Replication/get_api_wal_access_tail.md
  Documentation/DocuBlocks/Rest/Replication/put_api_replication_applier.md
  Documentation/DocuBlocks/Rest/job/job_getStatusById.md
  Documentation/Metrics/rocksdb_wal_sequence_lower_bound.yaml
  Documentation/README_maintainers.md
  Documentation/StyleGuide/StyleGuide.tex
  Documentation/arango.doxygen
  README
  README.md
  STYLEGUIDE.md
  utils/checkLogIds.py
  utils/cleanupCFiles
  utils/generateErrorfile.py
  utils/generateExamples.js
  utils/generateSwagger.py
  utils/makeDashboards.py
Labels: 3 Documentation, cla-signed

#18239 Added `--rocksdb.auto-refill-index-caches-on-followers`
  CHANGELOG
  arangod/ClusterEngine/ClusterEngine.h
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.cpp
  arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.h
  arangod/StorageEngine/StorageEngine.h
  arangod/Transaction/Methods.cpp
  js/client/modules/@arangodb/test-helper.js
  js/client/modules/@arangodb/testsuites/server_permissions.js
  js/common/modules/@arangodb/test-helper-common.js
  js/server/modules/@arangodb/test-helper.js
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/js/client/server_parameters/auto-refill-index-caches-on-followers-off-cluster.js
  tests/js/client/server_parameters/auto-refill-index-caches-on-followers-on-cluster.js
Labels: 9 Ready to Merge, cla-signed

#18242 improve usefulness of debug messages
  arangod/Replication/ReplicationClients.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: 9 Ready to Merge, cla-signed

#18244 improve query optimizer
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/AstNode.cpp
  arangod/Aql/Condition.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-projections.js
Labels: 9 Ready to Merge, cla-signed

#18268 fixed error in query-test spec if it runs too long
  tests/js/common/shell/multi/shell-query-spec.js
Labels: cla-signed

#18272 remove unused scripts from `utils` and `scripts`
  scripts/startArangoDBClusterLocal.sh
  utils/cleanupCFiles
  utils/reformat.sh
  utils/replace_string.sh
Labels: cla-signed

#18270 simplify code
  arangod/Agency/AsyncAgencyComm.cpp
  arangod/Cluster/AgencyCache.cpp
  arangod/GeneralServer/RestHandlerFactory.cpp
  arangod/Replication/common-defines.cpp
  arangod/V8Server/V8DealerFeature.cpp
  arangod/VocBase/Methods/Indexes.cpp
  lib/ProgramOptions/Translator.cpp
Labels: cla-signed

#18263 [GORDO-1565] Remove ApplicationServer dependency out of Algorithm
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/AlgoRegistry.h
  arangod/Pregel/Algorithm.h
  arangod/Pregel/Algos/ColorPropagation/ColorPropagation.h
  arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.cpp
  arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.h
  arangod/Pregel/Algos/DMID/DMID.h
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.h
  arangod/Pregel/Algos/HITS/HITS.h
  arangod/Pregel/Algos/HITSKleinberg/HITSKleinberg.h
  arangod/Pregel/Algos/LabelPropagation/LabelPropagation.cpp
  arangod/Pregel/Algos/LabelPropagation/LabelPropagation.h
  arangod/Pregel/Algos/LineRank/LineRank.cpp
  arangod/Pregel/Algos/LineRank/LineRank.h
  arangod/Pregel/Algos/PageRank/PageRank.cpp
  arangod/Pregel/Algos/PageRank/PageRank.h
  arangod/Pregel/Algos/ReadWrite/ReadWrite.cpp
  arangod/Pregel/Algos/ReadWrite/ReadWrite.h
  arangod/Pregel/Algos/RecoveringPageRank/RecoveringPageRank.h
  arangod/Pregel/Algos/SCC/SCC.h
  arangod/Pregel/Algos/SLPA/SLPA.h
  arangod/Pregel/Algos/SSSP/SSSP.cpp
  arangod/Pregel/Algos/SSSP/SSSP.h
  arangod/Pregel/Algos/ShortestPath/ShortestPath.cpp
  arangod/Pregel/Algos/ShortestPath/ShortestPath.h
  arangod/Pregel/Algos/WCC/WCC.h
  arangod/Pregel/Conductor/Conductor.cpp
Labels: 9 Waiting for Jenkins, 3 Pregel, cla-signed

#18208 Feature/openssl 3.0.8
  CHANGELOG
  CMakeLists.txt
  VERSIONS
  cmake/custom/ArangoDB_FindOpenSSL_WIN32.cmake
Labels: OpenSSL, cla-signed

#18252 Support INTO clauses in AQL hashed COLLECT variant
  CHANGELOG
  arangod/Aql/CollectNode.cpp
  arangod/Aql/HashedCollectExecutor.cpp
  arangod/Aql/HashedCollectExecutor.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/SortedCollectExecutor.h
  tests/Aql/HashedCollectExecutorTest.cpp
  tests/js/server/aql/aql-explain-cluster.js
  tests/js/server/aql/aql-explain-noncluster.js
  tests/js/server/aql/aql-failures-noncluster.js
  tests/js/server/aql/aql-optimizer-collect-into.js
  tests/js/server/aql/aql-optimizer-collect-methods.js
  tests/js/server/aql/aql-optimizer-rule-remove-collect-variables.js
Labels: cla-signed

#18275 Update OpenSSL to 3.0.8 for CircleCI
  .circleci/base_config.yml
  scripts/build/arangodb-build.Dockerfile
  scripts/build/install-openssl.sh
Labels: cla-signed

#18189 Fix arangorestore API to create _rev on shard leader [BTS-1232].
  CHANGELOG
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: cla-signed

#18249 Added `--rocksdb.auto-refill-index-caches-on-followers`
  CHANGELOG
  arangod/ClusterEngine/ClusterEngine.h
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.cpp
  arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.h
  arangod/StorageEngine/StorageEngine.h
  arangod/Transaction/Methods.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/js/client/server_parameters/auto-refill-index-caches-on-followers-off-cluster.js
  tests/js/client/server_parameters/auto-refill-index-caches-on-followers-on-cluster.js
Labels: cla-signed

#18288 Web interface: Add missing 3.10 functions to AQL code highlighter
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/assets/src/mode-aql.js
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.0854849aa107f3e3604e18c84dc2cdc0.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.8da917104a510651db46ac50e6babff4.js
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.8da917104a510651db46ac50e6babff4.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.bb8c1afa1a840785f7c23dbc444dbfef.js
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.bb8c1afa1a840785f7c23dbc444dbfef.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js.gz
  js/apps/system/_admin/aardvark/APP/react/public/assets/src/mode-aql.js
Labels: 1 Bug, 3 UI, 3 AQL, cla-signed

#18286 suppress a useless error message
  client-tools/Shell/ClientFeature.cpp
Labels: cla-signed

#18269 add more transparency for WAL file deletions
  CHANGELOG
  Documentation/Metrics/arangodb_flush_subscriptions.yaml
  Documentation/Metrics/rocksdb_live_wal_files.yaml
  Documentation/Metrics/rocksdb_wal_released_tick_flush.yaml
  Documentation/Metrics/rocksdb_wal_released_tick_replication.yaml
  arangod/IResearch/IResearchDataStore.cpp
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/FlushFeature.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBBackgroundThread.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  tests/RestServer/FlushFeatureTest.cpp
Labels: cla-signed

#18297 fix test failure on windows
  tests/js/common/shell/multi/shell-query-spec.js
Labels: cla-signed

#18279 [GORDO-1567] Remove raw pointers referring to WorkerConfig
  arangod/Pregel/Algorithm.h
  arangod/Pregel/Algos/ColorPropagation/ColorPropagation.cpp
  arangod/Pregel/Algos/ColorPropagation/ColorPropagation.h
  arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.cpp
  arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.h
  arangod/Pregel/Algos/DMID/DMID.cpp
  arangod/Pregel/Algos/DMID/DMID.h
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.cpp
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.h
  arangod/Pregel/Algos/HITS/HITS.cpp
  arangod/Pregel/Algos/HITS/HITS.h
  arangod/Pregel/Algos/HITSKleinberg/HITSKleinberg.cpp
  arangod/Pregel/Algos/HITSKleinberg/HITSKleinberg.h
  arangod/Pregel/Algos/LabelPropagation/LabelPropagation.cpp
  arangod/Pregel/Algos/LabelPropagation/LabelPropagation.h
  arangod/Pregel/Algos/LineRank/LineRank.cpp
  arangod/Pregel/Algos/LineRank/LineRank.h
  arangod/Pregel/Algos/PageRank/PageRank.cpp
  arangod/Pregel/Algos/PageRank/PageRank.h
  arangod/Pregel/Algos/ReadWrite/ReadWrite.cpp
  arangod/Pregel/Algos/ReadWrite/ReadWrite.h
  arangod/Pregel/Algos/RecoveringPageRank/RecoveringPageRank.cpp
  arangod/Pregel/Algos/RecoveringPageRank/RecoveringPageRank.h
  arangod/Pregel/Algos/SCC/SCC.cpp
  arangod/Pregel/Algos/SCC/SCC.h
  arangod/Pregel/Algos/SLPA/SLPA.cpp
  arangod/Pregel/Algos/SLPA/SLPA.h
  arangod/Pregel/Algos/SSSP/SSSP.cpp
  arangod/Pregel/Algos/SSSP/SSSP.h
  arangod/Pregel/Algos/ShortestPath/ShortestPath.cpp
  arangod/Pregel/Algos/ShortestPath/ShortestPath.h
  arangod/Pregel/Algos/WCC/WCC.cpp
  arangod/Pregel/Algos/WCC/WCC.h
  arangod/Pregel/GraphStore/GraphStore.cpp
  arangod/Pregel/GraphStore/GraphStore.h
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/IncomingCache.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/OutgoingCache.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/Worker/WorkerConfig.h
Labels: 3 Pregel, cla-signed

#18256 Implement Inspection for std::set, std::unordered_set and the like
  lib/Inspection/include/Inspection/Access.h
  lib/Inspection/include/Inspection/LoadInspectorBase.h
  lib/Inspection/include/Inspection/VPackLoadInspector.h
  lib/Inspection/include/Inspection/detail/traits.h
  tests/Inspection/JsonPrintTest.cpp
  tests/Inspection/VPackLoadTest.cpp
  tests/Inspection/VPackSaveTest.cpp
  tests/Inspection/include/Inspection/InspectionTestHelper.h
Labels: cla-signed

#18291 add more transparency for WAL file deletions
  CHANGELOG
  Documentation/Metrics/arangodb_flush_subscriptions.yaml
  Documentation/Metrics/rocksdb_live_wal_files.yaml
  Documentation/Metrics/rocksdb_wal_released_tick_flush.yaml
  Documentation/Metrics/rocksdb_wal_released_tick_replication.yaml
  arangod/IResearch/IResearchDataStore.cpp
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/FlushFeature.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBBackgroundThread.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  tests/RestServer/FlushFeatureTest.cpp
Labels: 9 Ready to Merge, cla-signed

#18153 [CINFRA] Fixing Windows build
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/Utils/TargetCollectionAgencyWriter.cpp
  arangod/Replication2/AgencyCollectionSpecificationInspectors.h
  scripts/unittest.ps1
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/js/client/restart/test-restart-replication2-database.js
Labels: 9 Ready to Merge, cinfra, cla-signed

#18277 [GORDO-1557] Improve some pregel algorithms code
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/AlgoRegistry.h
  arangod/Pregel/Algorithm.h
  arangod/Pregel/Algos/ColorPropagation/ColorPropagation.cpp
  arangod/Pregel/Algos/ColorPropagation/ColorPropagation.h
  arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.cpp
  arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.h
  arangod/Pregel/Algos/DMID/DMID.cpp
  arangod/Pregel/Algos/DMID/DMID.h
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.cpp
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.h
  arangod/Pregel/Algos/HITS/HITS.cpp
  arangod/Pregel/Algos/HITS/HITS.h
  arangod/Pregel/Algos/HITSKleinberg/HITSKleinberg.cpp
  arangod/Pregel/Algos/HITSKleinberg/HITSKleinberg.h
  arangod/Pregel/Algos/LabelPropagation/LabelPropagation.cpp
  arangod/Pregel/Algos/LabelPropagation/LabelPropagation.h
  arangod/Pregel/Algos/LineRank/LineRank.cpp
  arangod/Pregel/Algos/LineRank/LineRank.h
  arangod/Pregel/Algos/PageRank/PageRank.cpp
  arangod/Pregel/Algos/PageRank/PageRank.h
  arangod/Pregel/Algos/ReadWrite/ReadWrite.cpp
  arangod/Pregel/Algos/ReadWrite/ReadWrite.h
  arangod/Pregel/Algos/RecoveringPageRank/RecoveringPageRank.cpp
  arangod/Pregel/Algos/RecoveringPageRank/RecoveringPageRank.h
  arangod/Pregel/Algos/SCC/SCC.cpp
  arangod/Pregel/Algos/SCC/SCC.h
  arangod/Pregel/Algos/SLPA/SLPA.cpp
  arangod/Pregel/Algos/SLPA/SLPA.h
  arangod/Pregel/Algos/SSSP/SSSP.cpp
  arangod/Pregel/Algos/SSSP/SSSP.h
  arangod/Pregel/Algos/ShortestPath/ShortestPath.cpp
  arangod/Pregel/Algos/ShortestPath/ShortestPath.h
  arangod/Pregel/Algos/WCC/WCC.cpp
  arangod/Pregel/Algos/WCC/WCC.h
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/MasterContext.h
Labels: 3 Pregel, cla-signed

#18232 [GORDO-1557] Create proper worker actor state
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkers.cpp
  arangod/Pregel/Conductor/ExecutionStates/LoadingState.h
  arangod/Pregel/Conductor/Handler.h
  arangod/Pregel/Conductor/State.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/REST/RestPregelHandler.cpp
  arangod/Pregel/SpawnActor.h
  arangod/Pregel/SpawnMessages.h
  arangod/Pregel/Worker/Actor.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/State.h
  tests/Pregel/ConductorStateTest.cpp
Labels: 3 Pregel, cla-signed

#18163 [CINFRA-674][CINFRA-675] Replicated operations refactoring
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/DropCollection.cpp
  arangod/Replication2/StateMachines/Document/ActiveTransactionsQueue.cpp
  arangod/Replication2/StateMachines/Document/ActiveTransactionsQueue.h
  arangod/Replication2/StateMachines/Document/CMakeLists.txt
  arangod/Replication2/StateMachines/Document/DocumentCore.cpp
  arangod/Replication2/StateMachines/Document/DocumentCore.h
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentLogEntry.cpp
  arangod/Replication2/StateMachines/Document/DocumentLogEntry.h
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.h
  arangod/Replication2/StateMachines/Document/DocumentStateTransaction.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransaction.h
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.h
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.cpp
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.h
  arangod/Replication2/StateMachines/Document/ReplicatedOperationInspectors.h
  arangod/Replication2/StateMachines/Document/ShardProperties.h
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
  arangod/Transaction/Methods.cpp
  js/common/modules/@arangodb/testutils/document-state-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
  js/common/modules/@arangodb/testutils/replicated-state-helper.js
  js/common/modules/@arangodb/testutils/replicated-state-predicates.js
  tests/Replication2/Mocks/DocumentStateMocks.cpp
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/js/client/shell/transaction/replication2_recovery/shell-transaction-replication2-recovery.js
  tests/js/client/shell/transaction/shell-transaction-cluster.js
  tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
  tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: 9 Ready to Merge, cinfra, cla-signed

#18306 [PREGEL] Fix using aggregator
  arangod/Pregel/Conductor/Conductor.cpp
Labels: 3 Pregel, cla-signed

#18307 Add a mutex to guard the methods in the stream proxy.
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
Labels: cinfra, cla-signed

#18293 add more transparency for WAL file deletions
  CHANGELOG
  Documentation/Metrics/arangodb_flush_subscriptions.yaml
  Documentation/Metrics/rocksdb_live_wal_files.yaml
  Documentation/Metrics/rocksdb_wal_released_tick_flush.yaml
  Documentation/Metrics/rocksdb_wal_released_tick_replication.yaml
  arangod/IResearch/IResearchLink.cpp
  arangod/RestServer/FlushFeature.cpp
  arangod/RestServer/FlushFeature.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBBackgroundThread.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  tests/RestServer/FlushFeature-test.cpp
Labels: 9 Ready to Merge, cla-signed

#18300 Auto-flushing of WAL and column family data
  CHANGELOG
  arangod/ClusterEngine/ClusterEngine.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBRestWalHandler.cpp
Labels: 9 Ready to Merge, cla-signed

#18305 Docs: Add 3.9.2 as version for `--database.io-heartbeat`
  arangod/RestServer/DatabaseFeature.cpp
Labels: 3 Documentation, cla-signed

#18314 Docs: Add 3.9.2 as version for `--database.io-heartbeat`
  arangod/RestServer/DatabaseFeature.cpp
Labels: 3 Documentation, cla-signed

#18315 Docs: Add 3.9.2 as version for `--database.io-heartbeat`
  arangod/RestServer/DatabaseFeature.cpp
Labels: 3 Documentation, cla-signed

#18313 Add missing deleteLog code for tests.
  tests/js/server/replication2/replication2-regression.js
Labels: cinfra, cla-signed

#18215 [CINFRA-669] Prevent replicated state usage before they're ready
  arangod/Replication2/CMakeLists.txt
  arangod/Replication2/ReplicatedLog/Components/ISnapshotManager.h
  arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/Components/SnapshotManager.cpp
  arangod/Replication2/ReplicatedLog/Components/SnapshotManager.h
  arangod/Replication2/ReplicatedLog/Components/StateHandleManager.cpp
  arangod/Replication2/ReplicatedLog/Components/StateHandleManager.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedLog/types.cpp
  arangod/Replication2/ReplicatedLog/types.h
  arangod/Replication2/ReplicatedState/CMakeLists.txt
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/StateStatus.cpp
  arangod/Replication2/ReplicatedState/StateStatus.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/vocbase.cpp
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
  tests/Replication2/CMakeLists.txt
  tests/Replication2/ReplicatedLog/LogFollower/AppendEntriesTest.cpp
  tests/Replication2/ReplicatedLog/ReplicatedLogConnectTest.cpp
  tests/Replication2/ReplicatedState/StateManagerTest.cpp
Labels: cinfra, cla-signed

#18248 Fix conditional compile flags
  CMakeLists.txt
Labels: cla-signed

#18320 [CINFRA] Fixing linting issues
  js/common/modules/@arangodb/testutils/document-state-helper.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#18321 Don't loose EXTRA_*_FLAGS in favor of external -DCMAKE_*_FLAGS usage (3.8)
  CMakeLists.txt
Labels: 3 Build, cla-signed

#18322 Don't loose EXTRA_*_FLAGS in favor of external -DCMAKE_*_FLAGS usage (3.9)
  CMakeLists.txt
Labels: 3 Build, cla-signed

#18323 Don't loose EXTRA_*_FLAGS in favor of external -DCMAKE_*_FLAGS usage (3.10)
  CMakeLists.txt
Labels: 3 Build, cla-signed

#18304 Auto-flushing of WAL and column family data
  CHANGELOG
  arangod/ClusterEngine/ClusterEngine.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBRestWalHandler.cpp
Labels: 9 Ready to Merge, cla-signed

#18327 Error hanlding if no DBServers are available for CollectionCreation
  arangod/Cluster/Utils/EvenDistribution.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
Labels: cla-signed

#18294 abort long-running commands if db/collection is dropped
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/vocbase.cpp
  tests/js/client/shell/abort-long-running-operations-noncluster.js
Labels: cla-signed

#18324 Speedup of the geo tests
  tests/js/common/aql/aql-geo-distance-range.js
Labels: 3 - Testing, 3 Geo, cla-signed

#18298 [GORDO-1553] Add FatalError conductor state
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.cpp
  arangod/Pregel/Conductor/ExecutionStates/FatalErrorState.h
  tests/Pregel/ConductorStateTest.cpp
Labels: 3 Pregel, cla-signed

#18312 [GORDO-1549] Make worker context own aggregators
  arangod/Pregel/Algorithm.h
  arangod/Pregel/Algos/ColorPropagation/ColorPropagation.cpp
  arangod/Pregel/Algos/ColorPropagation/ColorPropagation.h
  arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.cpp
  arangod/Pregel/Algos/ConnectedComponents/ConnectedComponents.h
  arangod/Pregel/Algos/DMID/DMID.cpp
  arangod/Pregel/Algos/DMID/DMID.h
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.cpp
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.h
  arangod/Pregel/Algos/HITS/HITS.cpp
  arangod/Pregel/Algos/HITS/HITS.h
  arangod/Pregel/Algos/HITSKleinberg/HITSKleinberg.cpp
  arangod/Pregel/Algos/HITSKleinberg/HITSKleinberg.h
  arangod/Pregel/Algos/LabelPropagation/LabelPropagation.cpp
  arangod/Pregel/Algos/LabelPropagation/LabelPropagation.h
  arangod/Pregel/Algos/LineRank/LineRank.cpp
  arangod/Pregel/Algos/LineRank/LineRank.h
  arangod/Pregel/Algos/PageRank/PageRank.cpp
  arangod/Pregel/Algos/PageRank/PageRank.h
  arangod/Pregel/Algos/ReadWrite/ReadWrite.cpp
  arangod/Pregel/Algos/ReadWrite/ReadWrite.h
  arangod/Pregel/Algos/RecoveringPageRank/RecoveringPageRank.cpp
  arangod/Pregel/Algos/RecoveringPageRank/RecoveringPageRank.h
  arangod/Pregel/Algos/SCC/SCC.cpp
  arangod/Pregel/Algos/SCC/SCC.h
  arangod/Pregel/Algos/SLPA/SLPA.cpp
  arangod/Pregel/Algos/SLPA/SLPA.h
  arangod/Pregel/Algos/SSSP/SSSP.cpp
  arangod/Pregel/Algos/SSSP/SSSP.h
  arangod/Pregel/Algos/ShortestPath/ShortestPath.cpp
  arangod/Pregel/Algos/ShortestPath/ShortestPath.h
  arangod/Pregel/Algos/WCC/WCC.cpp
  arangod/Pregel/Algos/WCC/WCC.h
  arangod/Pregel/MasterContext.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/WorkerContext.h
  tests/Pregel/ConductorStateTest.cpp
Labels: 3 Pregel, cla-signed

#18333 Return service unavailable if state is unavailable.
  arangod/VocBase/LogicalCollection.cpp
  lib/Rest/GeneralResponse.cpp
Labels: cinfra, cla-signed

#18319 BTS-325 | Docs: Referencing a vertex collection in _from/_to that is not in named graph returns 404
  Documentation/DocuBlocks/Rest/Graph/general_graph_edge_create_http_examples.md
Labels: 3 Documentation, cla-signed

#18318 BTS-325 | Docs: Referencing a vertex collection in _from/_to that is not in named graph returns 404
  Documentation/DocuBlocks/Rest/Graph/general_graph_edge_create_http_examples.md
Labels: 3 Documentation, cla-signed

#18332 Make resilience tests stable again [BTS-1235].
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster.js
  tests/js/server/resilience/failover/resilience-synchronous-repl-cluster.inc
Labels: 3 - Testing, cla-signed

#18334 Make resilience tests stable again [BTS-1235].
  CHANGELOG
  tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster.js
  tests/js/server/resilience/failover/resilience-synchronous-repl-cluster.js
Labels: 3 - Testing, cla-signed

#18335 Make resilience tests stable again [BTS-1235].
  CHANGELOG
  tests/js/server/resilience/failover-view/resilience-synchronous-repl-with-arangosearch-view-cluster-grey.js
  tests/js/server/resilience/failover/resilience-synchronous-repl-cluster.js
Labels: 3 - Testing, cla-signed

#18341 [CINFRA] LogicalCollection Shard store replicated state id
  arangod/Cluster/CreateCollection.cpp
  arangod/VocBase/LogicalCollection.cpp
  tests/js/client/restart/test-restart-replication2-database.js
Labels: cinfra, cla-signed

#18339 slightly improve usefulness of log messages
  arangod/Cluster/ClusterFeature.cpp
  arangod/RestServer/FlushFeature.cpp
Labels: cla-signed

#18346 add more TRACE logging at startup for collection metadata
  arangod/RestServer/FlushFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: cla-signed

#18344 [testing] work on endpoints test
  js/client/modules/@arangodb/testsuites/endpoints.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: cla-signed

#18292 add support for gzip server responses
  3rdParty/fuerte/src/types.cpp
  CHANGELOG
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/V8Server/v8-actions.cpp
  lib/Basics/EncodingUtils.cpp
  lib/Basics/EncodingUtils.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/StringBuffer.h
  lib/Basics/StringBufferAdvanced.cpp
  lib/Rest/CommonDefines.h
  lib/Rest/GeneralResponse.h
  lib/Rest/HttpResponse.h
  lib/Rest/VstResponse.cpp
  lib/Rest/VstResponse.h
  tests/js/client/shell/api/multi/foxx-spec.js
  tests/js/common/test-data/apps/headers/index.js
Labels: cla-signed

#18349 [testing] use execution deadlines in chaos tests to avoid hard killing
  js/client/modules/@arangodb/test-helper.js
Labels: cla-signed

#18336 [CINFRA] Fix a compile error
  arangod/Replication2/StateMachines/Document/ActiveTransactionsQueue.cpp
  tests/Replication2/ReplicatedState/StateManagerTest.cpp
Labels: cinfra, cla-signed

#18356 [testing] wait for spawned debuggers to join
  js/client/modules/@arangodb/testsuites/endpoints.js
Labels: cla-signed

#18354 Followup-Bug-fixes from edge devel->replication-2.0
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/Properties/ClusteringConstantProperties.h
  tests/js/common/shell/shell-one-shard.js
Labels: cla-signed

#18343 [CINFRA-687] Use larger int types in v8-replicated-logs
  arangod/V8Server/v8-replicated-logs.cpp
Labels: cinfra, cla-signed

#18359 [testing] shorten filenames, DRY
  js/client/modules/@arangodb/testutils/result-processing.js
Labels: cla-signed

#18367 Forward correct logger context to Follower Manager.
  arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.cpp
  arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/Components/LogFollower.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  tests/Replication2/ReplicatedLog/LogFollower/AppendEntriesTest.cpp
Labels: cinfra

#17985 if shell-general-graph-creation-cluster.js is ran with coverage instrumented binaries, this test will not finish any time soon
  tests/js/server/shell/shell-general-graph-creation-cluster.js
Labels: cla-signed

#18360 give chaos more resources
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#18233 Make API response to failed write concern configurable 503 vs 403 [APM-73].
  CHANGELOG
  Documentation/DocuBlocks/Rest/Documents/delete_multiple_documents.md
  Documentation/DocuBlocks/Rest/Documents/delete_remove_document.md
  Documentation/DocuBlocks/Rest/Documents/patch_update_document.md
  Documentation/DocuBlocks/Rest/Documents/patch_update_multiple_documents.md
  Documentation/DocuBlocks/Rest/Documents/post_create_document.md
  Documentation/DocuBlocks/Rest/Documents/post_create_multiple_document.md
  Documentation/DocuBlocks/Rest/Documents/put_replace_document.md
  Documentation/DocuBlocks/Rest/Documents/put_replace_multiple_documents.md
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/Transaction/Methods.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Rest/GeneralResponse.cpp
  tests/js/client/server_parameters/test-failed-write-concern-cluster-403.js
  tests/js/client/server_parameters/test-failed-write-concern-cluster-503.js
Labels: cla-signed

#18355 added debug message to assertion
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RocksDBEngine/RocksDBWalAccess.cpp
  arangod/StorageEngine/WalAccess.h
Labels: cla-signed

#18372 Fix some undefined behaviour in some maintainer mode code (#14891)
  arangod/Agency/AsyncAgencyComm.cpp
Labels: cla-signed

#18358 [CINFRA-687] Remove public Follower APIs exposing InMemoryLog
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedLog/Components/IStorageManager.h
  arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/Components/LogFollower.h
  arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
  arangod/Replication2/ReplicatedLog/Components/StorageManager.h
  arangod/Replication2/ReplicatedLog/ILogInterfaces.h
  arangod/Replication2/ReplicatedLog/InMemoryLog.cpp
  arangod/Replication2/ReplicatedLog/InMemoryLog.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/RestHandler/RestLogHandler.cpp
  arangod/V8Server/v8-replicated-logs.cpp
  tests/Replication2/Mocks/FakeFollower.cpp
  tests/Replication2/Mocks/FakeFollower.h
  tests/Replication2/ReplicatedLog/Components/CompactionManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
  tests/Replication2/ReplicatedLog/ReplicatedLogConnectTest.cpp
Labels: cinfra, cla-signed

#18273 Feature/cinfra 632 graphs use new collection api
  arangod/Agency/Agent.cpp
  arangod/Agency/Supervision.cpp
  arangod/Graph/Graph.cpp
  arangod/Graph/Graph.h
  arangod/Graph/GraphManager.cpp
  arangod/Graph/GraphManager.h
  arangod/Graph/GraphOperations.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/Sharding/ShardingFeature.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/StorageEngine/EngineSelectorFeature.cpp
  arangod/StorageEngine/EngineSelectorFeature.h
  arangod/VocBase/Methods/Collections.cpp
Labels: cla-signed

#18361 Log response bodies and HTTP headers on requests=trace.
  CHANGELOG
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/GeneralCommTask.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  lib/Basics/StringUtils.cpp
  lib/Basics/StringUtils.h
Labels: cla-signed

#18274 [APM-283] Almost always use parallel gather
  CHANGELOG
  arangod/Aql/ExecutionNode.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/OptimizerRulesFeature.h
  arangod/Aql/QueryContext.h
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/Aql/RestAqlHandler.cpp
  tests/js/client/server_parameters/test-parallel-gather-writes-cluster-off.js
  tests/js/client/server_parameters/test-parallel-gather-writes-cluster-on.js
  tests/js/server/aql/aql-optimizer-rule-parallelize-gather-cluster.js
Labels: cla-signed

#18369 [CINFRA] Fix CleanOut and ResignLeadership
  arangod/Agency/CMakeLists.txt
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/CleanOutServer.h
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/JobContext.cpp
  arangod/Agency/ReconfigureReplicatedLog.cpp
  arangod/Agency/ReconfigureReplicatedLog.h
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/ResignLeadership.h
  js/client/modules/@arangodb/testsuites/replication2.js
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-predicates.js
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra, cla-signed

#18375 Improvements for WAL file handling
  CHANGELOG
  Documentation/Metrics/rocksdb_archived_wal_files.yaml
  Documentation/Metrics/rocksdb_archived_wal_files_size.yaml
  Documentation/Metrics/rocksdb_live_wal_files_size.yaml
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
Labels: cla-signed

#18325 [CINFRA-676] Garbage collection of snapshots
  arangod/Replication2/StateMachines/Document/CollectionReader.cpp
  arangod/Replication2/StateMachines/Document/CollectionReader.h
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.h
  arangod/Replication2/StateMachines/Document/DocumentStateMethods.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateNetworkHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateNetworkHandler.h
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.h
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.h
  arangod/RestHandler/RestDocumentStateHandler.cpp
  js/common/modules/@arangodb/testutils/document-state-helper.js
  tests/Replication2/Mocks/DocumentStateMocks.cpp
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/js/client/shell/transaction/shell-transaction-cluster.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#18330 [GORDO-1575] Implemented 'done' conductor state
  arangod/Pregel/Conductor/ExecutionStates/DoneState.h
Labels: 3 Pregel, cla-signed

#18384 Improve enterprise checkout a bit
  .circleci/base_config.yml
  js/client/modules/@arangodb/testutils/result-processing.js
Labels: cla-signed

#18378 Delete documentRevision.md
  Documentation/DocuBlocks/documentRevision.md
Labels: 3 Documentation, cla-signed

#18389 use std::string::starts_with
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/Query.cpp
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/Cluster/TakeoverShardLeadership.cpp
Labels: cla-signed

#18331 [GORDO-1549] Start computing state
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/AlgoRegistry.h
  arangod/Pregel/Algorithm.h
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/ExecutionStates/AQLResultsAvailableState.h
  arangod/Pregel/Conductor/ExecutionStates/ComputingState.cpp
  arangod/Pregel/Conductor/ExecutionStates/ComputingState.h
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.cpp
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.h
  arangod/Pregel/Conductor/ExecutionStates/DoneState.h
  arangod/Pregel/Conductor/ExecutionStates/FatalErrorState.h
  arangod/Pregel/Conductor/ExecutionStates/InitialState.h
  arangod/Pregel/Conductor/ExecutionStates/LoadingState.cpp
  arangod/Pregel/Conductor/ExecutionStates/LoadingState.h
  arangod/Pregel/Conductor/ExecutionStates/ProduceAQLResultsState.h
  arangod/Pregel/Conductor/ExecutionStates/State.h
  arangod/Pregel/Conductor/Handler.h
  arangod/Pregel/Conductor/Messages.h
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/IncomingCache.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/REST/RestPregelHandler.cpp
  arangod/Pregel/SpawnActor.h
  arangod/Pregel/SpawnMessages.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/Messages.h
  arangod/Pregel/Worker/State.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/Worker/WorkerConfig.cpp
  arangod/Pregel/Worker/WorkerConfig.h
  tests/Pregel/ConductorStateTest.cpp
Labels: 3 Pregel, cla-signed

#18390 [CINFRA] Fixing mac build
  arangod/Agency/CleanOutServer.cpp
  arangod/VocBase/VocBaseLogManager.cpp
  tests/Agency/CleanOutServerTest.json
Labels: 9 Ready to Merge, cinfra, cla-signed

#18387 simplify sending code
  client-tools/Shell/TelemetricsHandler.cpp
  client-tools/Shell/TelemetricsHandler.h
  lib/Basics/StringUtils.cpp
  lib/Basics/StringUtils.h
  lib/V8/v8-utils.cpp
  lib/V8/v8-utils.h
Labels: cla-signed

#18393 simplify setup of SimpleHttpClients in client-tools
  arangod/Replication/Syncer.cpp
  arangod/Replication/Syncer.h
  client-tools/Benchmark/BenchFeature.cpp
  client-tools/Benchmark/BenchmarkThread.h
  client-tools/CMakeLists.txt
  client-tools/Export/ExportFeature.cpp
  client-tools/Export/ExportFeature.h
  client-tools/Import/ImportFeature.cpp
  client-tools/Import/ImportFeature.h
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Shell/ClientFeature.cpp
  client-tools/Shell/ClientFeature.h
  client-tools/Utils/ClientManager.cpp
  client-tools/Utils/ClientManager.h
  client-tools/V8Client/ArangoClientHelper.cpp
  client-tools/V8Client/ArangoClientHelper.h
  lib/SimpleHttpClient/SimpleHttpClient.h
Labels: cla-signed

#18391 [BTS-1148] Add tests and failure points
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/RestAqlHandler.cpp
  tests/js/common/shell/test-kill-queries.js
Labels: cla-signed

#18403 very small improvements for telemetrics
  arangod/Utils/SupportInfoBuilder.cpp
  lib/SimpleHttpClient/GeneralClientConnection.cpp
Labels: cla-signed

#18380 [GORDO-1549] Execute one gss in worker
  arangod/Pregel/Conductor/ExecutionStates/CollectionLookup.h
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.cpp
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.h
  arangod/Pregel/Conductor/ExecutionStates/LoadingState.cpp
  arangod/Pregel/Conductor/ExecutionStates/LoadingState.h
  arangod/Pregel/Conductor/Handler.h
  arangod/Pregel/Conductor/Messages.h
  arangod/Pregel/DatabaseTypes.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/OutgoingCache.h
  arangod/Pregel/Statistics.h
  arangod/Pregel/VertexComputation.h
  arangod/Pregel/Worker/Handler.h
  arangod/Pregel/Worker/Messages.h
  arangod/Pregel/Worker/State.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/WorkerConfig.h
  arangod/Pregel/WorkerContext.h
Labels: 3 Pregel, cla-signed

#18370 [testing] process monitoring thread
  arangod/Cache/CacheManagerFeature.cpp
  client-tools/CMakeLists.txt
  client-tools/Shell/ProcessMonitoringFeature.cpp
  client-tools/Shell/ProcessMonitoringFeature.h
  client-tools/Shell/arangosh.cpp
  client-tools/Shell/arangosh.h
  client-tools/Shell/v8-deadline.cpp
  js/client/bootstrap/modules/internal.js
  js/client/modules/@arangodb/test-helper.js
  js/client/modules/@arangodb/testsuites/aql.js
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  js/client/modules/@arangodb/testsuites/replication2.js
  js/client/modules/@arangodb/testsuites/resilience.js
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
  lib/Basics/process-utils.cpp
  lib/V8/CMakeLists.txt
  lib/V8/V8SecurityFeature.cpp
  lib/V8/V8SecurityFeature.h
  lib/V8/v8-deadline.h
  lib/V8/v8-no-deadline.cpp
  lib/V8/v8-utils.cpp
  tests/js/client/active-failover/basic.js
  tests/js/client/active-failover/readonly.js
  tests/js/client/shell/aql-failures-cluster.js
  tests/js/client/shell/multi/shell-admin-cluster-maintenance-dbservers.js
  tests/js/client/shell/multi/shell-admin-log.js
  tests/js/client/shell/shell-admin-cluster-rebalance.js
  tests/js/client/shell/shell-promtool-cluster.js
Labels: cla-signed

#18405 deprecate DatabaseFeature::lookupDatabase()
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/DropCollection.cpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/Replication/Syncer.cpp
  arangod/Replication/TailingSyncer.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestUsersHandler.cpp
  arangod/RestServer/CheckVersionFeature.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/RestServer/UpgradeFeature.cpp
  arangod/Utils/DatabaseGuard.h
  arangod/Utils/SupportInfoBuilder.cpp
  arangod/V8Server/v8-replication.cpp
  arangod/V8Server/v8-users.cpp
Labels: cla-signed

#18382 Speed up tests
  arangod/RestServer/TtlFeature.cpp
  js/client/modules/@arangodb/testutils/instance-manager.js
  tests/js/common/shell/multi/shell-fulltext.js
  tests/js/common/shell/multi/shell-tasks.js
  tests/js/common/shell/multi/shell-ttl.js
  tests/js/common/shell/multi/shell-validation.js
Labels: cla-signed

#18413 [CINFRA] Fix CircleCI Job
  .circleci/base_config.yml
  .circleci/config.yml
Labels: cinfra, cla-signed

#18371 Fix some undefined behaviour in some maintainer mode code (#14891)
  arangod/Agency/AsyncAgencyComm.cpp
Labels: cla-signed

#18416 fix single-to-single replication with authentication
  arangod/Replication/DatabaseInitialSyncer.cpp
  js/client/modules/@arangodb/testsuites/replication.js
  tests/js/server/replication/sync/replication-sync-malarkey.inc
  tests/js/server/replication/sync/replication-sync.js
Labels: cla-signed

#18412 BTS-1272: correct counting of connections in pool
  CHANGELOG
  arangod/Network/ConnectionPool.cpp
  arangod/Network/ConnectionPool.h
  tests/Network/ConnectionPoolTest.cpp
Labels: cla-signed

#18411 BTS-1272: correct counting of connections in pool
  CHANGELOG
  arangod/Network/ConnectionPool.cpp
  arangod/Network/ConnectionPool.h
  tests/Network/ConnectionPoolTest.cpp
Labels: cla-signed

#18426 add the possibility to launch testsuites with different arguments
  CONTRIBUTING.md
  js/client/modules/@arangodb/testutils/testing.js
Labels: cla-signed

#18345 add more TRACE logging at startup for collection metadata
  arangod/RestServer/FlushFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 9 Ready to Merge, cla-signed

#18379 Delete documentRevision.md
  Documentation/DocuBlocks/documentRevision.md
Labels: 3 Documentation, cla-signed

#18410 BTS-1272: correct counting of connections in pool
  CHANGELOG
  arangod/Network/ConnectionPool.cpp
  tests/Network/ConnectionPoolTest.cpp
Labels: 9 Ready to Merge, cla-signed

#18437 Fix changing a generated file in the repo
  utils/generateErrorfile.py
Labels: cla-signed

#18363 Log response bodies and HTTP headers on requests=trace.
  CHANGELOG
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/GeneralCommTask.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  lib/Basics/StringUtils.cpp
  lib/Basics/StringUtils.h
Labels: cla-signed

#18427 Bug-Fix 3.9: ES-1508 (EE only) (#18422)
  CHANGELOG
Labels: cla-signed

#18408 Added simple anti-overwhelm protection for telemetrics API
  3rdParty/fuerte/include/fuerte/connection.h
  CHANGELOG
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.h
  arangod/GeneralServer/RestHandler.cpp
  arangod/Network/ConnectionPool.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/RestHandler/RestTelemetricsHandler.cpp
  arangod/RestHandler/RestTelemetricsHandler.h
  client-tools/Shell/TelemetricsHandler.cpp
  etc/testing/arangod-common.conf
  js/common/bootstrap/errors.js
  lib/Basics/EncodingUtils.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/errors.dat
  lib/Rest/CommonDefines.h
  lib/Rest/GeneralResponse.cpp
  lib/Rest/HttpRequest.cpp
  lib/SimpleHttpClient/SimpleHttpResult.cpp
  tests/js/client/server_parameters/test-telemetrics-false-auth.js
  tests/js/client/server_parameters/test-telemetrics-true-auth.js
Labels: cla-signed

#18362 Log response bodies and HTTP headers on requests=trace.
  CHANGELOG
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/GeneralCommTask.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/VstCommTask.cpp
  lib/Basics/StringUtils.cpp
  lib/Basics/StringUtils.h
Labels: cla-signed

#18436 [CINFRA] Remove getCommittedLog finally.
  arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.cpp
  arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.h
  arangod/Replication2/ReplicatedLog/Components/IStorageManager.h
  arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
  arangod/Replication2/ReplicatedLog/Components/StorageManager.h
  tests/Replication2/ReplicatedLog/Components/CompactionManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
Labels: cinfra, cla-signed

#18340 Mark mmaped-files commandline options obsolete
  CHANGELOG
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/ExecutionStates/CreateWorkersState.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/PregelOptions.h
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker/Messages.h
  arangod/Pregel/Worker/WorkerConfig.cpp
  arangod/Pregel/Worker/WorkerConfig.h
Labels: 3 Pregel, cla-signed

#18439 [CINFRA] Remove InMemoryLogs from StorageManager
  arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
  arangod/Replication2/ReplicatedLog/Components/IStorageManager.h
  arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
  arangod/Replication2/ReplicatedLog/Components/StorageManager.h
  arangod/Replication2/ReplicatedLog/TermIndexMapping.cpp
  arangod/Replication2/ReplicatedLog/TermIndexMapping.h
  tests/Replication2/ReplicatedLog/Components/CompactionManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
Labels: cinfra, cla-signed

#18417 fix single-to-single replication with authentication
  CHANGELOG
  arangod/Replication/DatabaseInitialSyncer.cpp
  js/client/modules/@arangodb/testsuites/replication.js
  tests/js/server/replication/sync/replication-sync-malarkey.js
  tests/js/server/replication/sync/replication-sync.js
Labels: 9 Ready to Merge, cla-signed

#18420 SEARCH-300 (BTS-789) remove database directory for arangosearch
  arangod/Cluster/HeartbeatThread.cpp
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/RestServer/FlushFeature.cpp
  arangod/V8Server/V8DealerFeature.cpp
  arangod/V8Server/V8DealerFeature.h
  arangod/VocBase/LogicalView.h
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/Methods/Databases.h
  arangod/VocBase/VocbaseInfo.cpp
  arangod/VocBase/VocbaseInfo.h
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  tests/IResearch/IResearchAnalyzerFeatureTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/js/common/shell/arangosearch-update-consistency.js
  tests/js/common/shell/view-drop-database.js
Labels: 3 ArangoSearch, cla-signed, Backport Needed
