Repository arangodb/arangodb, pull requests merged in 2023-01, with the labels that each got.

#17764 Changing log time format to print microseconds
  etc/testing/arangod-common.conf
Labels: 3 - Testing, cla-signed

#17873 [CINFRA-614] Error Reporting In Transaction Handler
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/RocksDBEngine/SimpleRocksDBTransactionState.h
  arangod/Transaction/Methods.cpp
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#17870 jemalloc cache_oblivious configurable, default false
  3rdParty/jemalloc/CMakeLists.txt
  3rdParty/jemalloc/v5.3.0/src/jemalloc.c
  CHANGELOG
Labels: cla-signed

#17874 Fix san issues in cluster
  arangod/Sharding/ShardingStrategyDefault.cpp
  arangod/Sharding/ShardingStrategyDefault.h
  lsan_arangodb_suppressions.txt
  ubsan_arangodb_suppressions.txt
Labels: cla-signed, Backport Needed

#17878 Make ServerState::_rebootId atomic
  arangod/Cluster/ClusterTypes.h
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
Labels: 1 Bug, 9 Ready to Merge, cla-signed

#17862 [SEARCH-442, BTS-1169] Make GeoJson parsing faster
  3rdParty/s2geometry/master/src/s2/s2polygon.h
  arangod/Aql/Functions.cpp
  arangod/GeoIndex/Covering.cpp
  arangod/GeoIndex/Covering.h
  arangod/GeoIndex/Index.cpp
  arangod/GeoIndex/Index.h
  arangod/GeoIndex/Near.h
  arangod/IResearch/Geo.cpp
  arangod/IResearch/Geo.h
  arangod/IResearch/GeoAnalyzer.cpp
  arangod/IResearch/GeoAnalyzer.h
  arangod/IResearch/GeoFilter.cpp
  arangod/IResearch/GeoFilter.h
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  lib/Basics/DownCast.h
  lib/Geo/CMakeLists.txt
  lib/Geo/Ellipsoid.cpp
  lib/Geo/Ellipsoid.h
  lib/Geo/GeoJson.cpp
  lib/Geo/GeoJson.h
  lib/Geo/GeoParams.cpp
  lib/Geo/GeoParams.h
  lib/Geo/S2/S2MultiPointRegion.cpp
  lib/Geo/S2/S2MultiPointRegion.h
  lib/Geo/S2/S2MultiPolyline.cpp
  lib/Geo/S2/S2MultiPolyline.h
  lib/Geo/ShapeContainer.cpp
  lib/Geo/ShapeContainer.h
  lib/Geo/Shapes.cpp
  lib/Geo/Shapes.h
  lib/Geo/Utils.cpp
  lib/Geo/Utils.h
  lib/Geo/karney/CMakeLists.txt
  tests/Geo/GeoJsonTest.cpp
  tests/Geo/NearUtilsTest.cpp
  tests/Geo/ShapeContainerTest.cpp
  tests/IResearch/GeoAnalyzerTest.cpp
  tests/IResearch/GeoDistanceFilterTest.cpp
  tests/IResearch/GeoFilterTest.cpp
  tests/IResearch/IResearchFilterGeoTest.cpp
  tests/IResearch/IResearchQueryGeoContainsTest.cpp
  tests/js/common/shell/shell-index-geo.js
  tests/js/server/aql/aql-queries-geo.js
Labels: cla-signed, Backport Needed

#17876 use a compact velocypack array in ModificationExecutorAccumulator
  arangod/Aql/ModificationExecutorAccumulator.h
Labels: cla-signed

#17879 clean up BlocksWithClients
  arangod/Aql/AqlCall.h
  arangod/Aql/BlocksWithClients.cpp
  arangod/Aql/BlocksWithClients.h
Labels: cla-signed

#17875 remove unused methods from RemoteExecutor
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/RemoteExecutor.h
Labels: cla-signed

#17891 add startup option to configure number of bloom bits
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.h
Labels: cla-signed

#17890 remove unneeded AqlItemMatrix
  arangod/Aql/AqlItemMatrix.cpp
  arangod/Aql/AqlItemMatrix.h
  arangod/Aql/CMakeLists.txt
  arangod/Aql/Collection.cpp
  arangod/Aql/Collection.h
  arangod/Aql/ConstrainedSortExecutor.h
  arangod/Aql/ModificationExecutor.h
  arangod/Aql/MutexExecutor.cpp
  arangod/Aql/NoResultsExecutor.cpp
  arangod/Aql/ScatterExecutor.cpp
  arangod/Aql/SortExecutor.h
  arangod/Aql/SortedRowsStorageBackendMemory.cpp
  arangod/Aql/SortedRowsStorageBackendMemory.h
  arangod/Aql/SortedRowsStorageBackendStaged.h
  tests/Aql/AqlItemMatrixTest.cpp
  tests/Aql/AqlSharedExecutionBlockImplTest.cpp
  tests/Aql/ExecutorTestHelper.h
  tests/Aql/InputRangeTest.cpp
  tests/Aql/RowFetcherHelper.cpp
  tests/Aql/RowFetcherHelper.h
  tests/CMakeLists.txt
Labels: cla-signed

#17886 BTS-163: no network::Response::slice() noexcept
  arangod/Network/Methods.cpp
  arangod/Network/Methods.h
Labels: cla-signed

#17889 [CINFRA-647] Make the Stream throw an exception after resign
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
Labels: 1 Bug, cinfra, cla-signed

#17885 BTS-199: remove check and setting of GLIBCXX_FORCE_NEW
  CHANGELOG
  Installation/ARM/rc.arangodb
  Installation/Ubuntu/snapcraft.yaml.in
  Installation/debian/arangodb.init
  Installation/debian/postinst.in
  Installation/rpm/rc.arangod.Centos
  Installation/rpm/rc.arangod.OpenSuSE
  Installation/rpm/rc.arangod.OpenSuSE_13
  Installation/systemd/arangodb3.service.in
  arangod/RestServer/EnvironmentFeature.cpp
  scripts/unittest
Labels: cla-signed

#17898 improve performance of distance functions
  arangod/Aql/Functions.cpp
Labels: cla-signed

#17888 Remove superflous OPENSSL version guards
  arangod/GeneralServer/AcceptorTcp.cpp
  arangod/GeneralServer/SslServerFeature.cpp
  arangod/RocksDBEngine/RocksDBChecksumEnv.cpp
  lib/SimpleHttpClient/SslClientConnection.cpp
  lib/Ssl/ssl-helper.cpp
  lib/Ssl/ssl-helper.h
Labels: cla-signed

#17899 Fixing formatting issues
  arangod/RestServer/DatabaseFeature.cpp
Labels: cla-signed

#17872 Make cache_oblivious configurable via env for jemalloc
  3rdParty/jemalloc/v5.2.1/src/jemalloc.c
  CHANGELOG
Labels: cla-signed

#17854 Updated ArangoDB logo.
  README.md
Labels: cla-signed

#17701 APM-84 | Add `spillOverThreshold*` options to Cursor API DocuBlock
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  arangod/RestServer/TemporaryStorageFeature.cpp
Labels: 3 Documentation, cla-signed

#17901 [CINFRA-620] Fixing remove operations and adding extra tests
  arangod/Replication2/StateMachines/Document/ActiveTransactionsQueue.cpp
  arangod/Replication2/StateMachines/Document/DocumentCore.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#17700 APM-84 | Add `spillOverThreshold*` options to Cursor API DocuBlock
  Documentation/DocuBlocks/Rest/Cursors/post_api_cursor.md
  arangod/RestServer/TemporaryStorageFeature.cpp
Labels: 3 Documentation, cla-signed

#17892 add startup option to configure number of bloom bits
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.h
Labels: 9 Ready to Merge, cla-signed

#17900 improve query plan serialization time
  CHANGELOG
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraverserEngineShardLists.cpp
  arangod/Aql/Variable.cpp
  arangod/Aql/Variable.h
  arangod/Aql/VariableGenerator.cpp
Labels: cla-signed

#17883 Allow database server start with invalid repl factor settings
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/VocBase/VocbaseInfo.cpp
  arangod/VocBase/VocbaseInfo.h
Labels: cla-signed

#17880 Allow database server start with invalid repl factor settings
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/VocBase/VocbaseInfo.cpp
  arangod/VocBase/VocbaseInfo.h
Labels: cla-signed

#17884 Allow database server start with invalid repl factor settings
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/VocBase/VocbaseInfo.cpp
  arangod/VocBase/VocbaseInfo.h
Labels: cla-signed

#17904 [cmake] Ignore user presets
  .gitignore
  tests/CMakeLists.txt
  tests/Futures/CMakeLists.txt
  tests/Zkd/CMakeLists.txt
Labels: cla-signed, cmake improvements

#17902 Improve efficiency of array/object serialization in query plans
  CHANGELOG
  arangod/Aql/AqlCallList.cpp
  arangod/Aql/AqlCallStack.cpp
  arangod/Aql/Ast.cpp
  arangod/Aql/AstNode.cpp
  arangod/Aql/AstNode.h
  arangod/Aql/Condition.cpp
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/Aql/SortingGatherExecutor.cpp
  arangod/IResearch/AqlHelper.cpp
  arangod/IResearch/AqlHelper.h
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchFilterFactoryCommon.h
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  js/common/modules/@arangodb/aql/explainer.js
  js/server/modules/@arangodb/aql-helper.js
  tests/Aql/AstNodeTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-optimizer-condition.js
  tests/js/server/aql/aql-optimizer-geoindex.js
Labels: cla-signed

#17911 Small improvements for cmake presets
  CMakePresets.json
Labels: cla-signed

#17916 [FE-48] only admin see license info PART2
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
Labels: 1 Bug, 3 UI, cla-signed

#17915 [CINFRA] State Creation Speedup
  arangod/Replication2/ReplicatedLog/ILogInterfaces.h
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/Replication2/ReplicatedLog/ReplicatedLogConnectTest.cpp
Labels: cinfra, cla-signed

#17921 Remove broken image reference from readme.
  README.md
Labels: cla-signed

#17913 remove unused functionality from LoggerStream
  lib/Basics/memory-map-posix.cpp
  lib/Basics/memory-map-win32.cpp
  lib/CrashHandler/CrashHandler.cpp
  lib/Logger/Logger.h
  lib/Logger/LoggerStream.cpp
  lib/Logger/LoggerStream.h
Labels: cla-signed

#17920 [CINFRA] Replace Participant Race with Agency Cache
  arangod/Agency/AsyncAgencyComm.cpp
  arangod/Agency/AsyncAgencyComm.h
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  arangod/Replication2/AgencyMethods.cpp
  arangod/RestHandler/RestLogHandler.cpp
Labels: cinfra, cla-signed

#17894 [CINFRA] Some performance improvements and more metrics
  Documentation/Metrics/arangodb_replication2_replicated_state_follower_apply_debt.yaml
  Documentation/Metrics/arangodb_replication2_rocksdb_num_persistor_worker.yaml
  Documentation/Metrics/arangodb_replication2_rocksdb_queue_length.yaml
  Documentation/Metrics/arangodb_replication2_rocksdb_sync_time_us.yaml
  Documentation/Metrics/arangodb_replication2_rocksdb_write_batch_size.yaml
  Documentation/Metrics/arangodb_replication2_rocksdb_write_time_us.yaml
  Documentation/Metrics/arangodb_replication2_storage_operation_latency_us.yaml
  arangod/Replication2/MetricsHelper.cpp
  arangod/Replication2/MetricsHelper.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/ReplicatedStateMetrics.cpp
  arangod/Replication2/ReplicatedState/ReplicatedStateMetrics.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBOptionsProvider.cpp
  arangod/RocksDBEngine/RocksDBPersistedLog.cpp
  arangod/RocksDBEngine/RocksDBPersistedLog.h
  arangod/VocBase/vocbase.cpp
  lib/Logger/LogTopic.cpp
  tests/Replication2/ReplicatedLog/Integration/StorageEngineMethodsTest.cpp
  tests/Replication2/ReplicatedLog/MetricsTest.cpp
Labels: cinfra, cla-signed

#17906 [CINFRA-645] acquireSnapshot could be called concurrently
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Labels: cinfra, cla-signed

#17927 Change request lane for active failover catchup requests
  CHANGELOG
  arangod/GeneralServer/RestHandler.h
  arangod/RestHandler/RestWalAccessHandler.cpp
Labels: cla-signed

#17907 DOC-312 | Inverted indexes and `arangosearch` Views accept an array of strings for `storedValues`
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
Labels: 3 Documentation, cla-signed

#17908 DOC-312 | Inverted indexes and `arangosearch` Views accept an array of strings for `storedValues`
  Documentation/DocuBlocks/Rest/Indexes/post_api_index_inverted.md
  Documentation/DocuBlocks/Rest/Views/post_api_view_arangosearch.md
Labels: cla-signed

#17912 Simplify status handling and dropping of collections
  arangod/Agency/State.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/DropCollection.cpp
  arangod/Graph/GraphManager.cpp
  arangod/Graph/GraphOperations.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/GlobalInitialSyncer.cpp
  arangod/Replication/Syncer.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/V8Server/v8-collection.cpp
  arangod/V8Server/v8-vocbase.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/LogicalDataSource.cpp
  arangod/VocBase/LogicalDataSource.h
  arangod/VocBase/LogicalView.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  arangod/VocBase/Methods/UpgradeTasks.cpp
  arangod/VocBase/voc-types.h
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  lib/Containers/MerkleTree.cpp
  tests/IResearch/IResearchAnalyzerFeatureTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/Mocks/Servers.cpp
  tests/RestHandler/RestUsersHandlerTest.cpp
  tests/Utils/CollectionNameResolverTest.cpp
  tests/V8Server/V8UsersTest.cpp
  tests/VocBase/ComputedValuesTest.cpp
  tests/VocBase/VocbaseTest.cpp
  tests/js/common/shell/shell-rename-noncluster.js
Labels: cla-signed

#17928 Change request lane for active failover catchup requests
  CHANGELOG
  arangod/GeneralServer/RestHandler.h
  arangod/RestHandler/RestWalAccessHandler.cpp
Labels: 9 Ready to Merge, cla-signed

#17933 Fixed assumption about return value
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: 3 - Testing, cla-signed

#17934 Bug fix 3.10/rebalance test request
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: 3 - Testing, cla-signed

#17935 [CINFRA-657] Return a successful result such that we don't crash
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#17926 [CINFRA-654] Introduce shard operations on follower
  arangod/Replication2/StateMachines/Document/DocumentCore.cpp
  arangod/Replication2/StateMachines/Document/DocumentCore.h
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLogEntry.h
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.h
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
Labels: cinfra, cla-signed

#17936 fix wrong version numbers in `introducedIn` of metrics
  Documentation/Metrics/arangodb_replication2_replicated_log_append_entries_rtt.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_creation_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_deletion_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_follower_append_entries_rt.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_follower_number.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_inactive_number.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_inserts_bytes.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_inserts_rtt.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_leader_number.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_leader_took_over_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_number.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_number_accepted_entries_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_number_committed_entries_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_number_compacted_entries_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_number_meta_entries_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_log_started_following_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_acquire_snapshot_errors_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_applied_entries_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_apply_entries_errors_total.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_follower_acquire_snapshot_rt.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_follower_apply_entries_rt.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_follower_number.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_follower_waiting_for_leader_number.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_follower_waiting_for_snapshot_number.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_leader_number.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_leader_recover_entries_rt.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_leader_waiting_for_recovery_number.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_number.yaml
  Documentation/Metrics/arangodb_replication2_replicated_state_processed_entries_total.yaml
Labels: cla-signed

#17845 [SEARCH-344] Add "numPrimaryDocs" ArangoSearch metric
  Documentation/Metrics/arangodb_search_num_primary_docs.yaml
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchInvertedClusterIndex.cpp
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchMetricStats.h
  tests/IResearch/IResearchLinkCoordinatorTest.cpp
  tests/IResearch/IResearchLinkTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/js/client/shell/api/multi/coordinator-metrics-cluster.js
  tests/js/common/aql/aql-arangosearch-inverted-index-search-alias-community.js
  tests/js/common/aql/aql-view-arangosearch-ddl-cluster.js
  tests/js/common/aql/aql-view-arangosearch-ddl-noncluster.js
  tests/js/server/dump/dump-test.inc
  tests/js/server/recovery/view-search-alias-populate-cluster.js
Labels: cla-signed

#17932 attempt to fix unstable test
  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-off.js
  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-on.js
Labels: cla-signed

#17919 Make agency watertight against illegal agents with new UUIDs - BTS-1185
  CHANGELOG
  arangod/Agency/AgentConfiguration.cpp
  arangod/Agency/State.cpp
Labels: cla-signed

#17948 BTS-1192: fix potential race in sha creation during hot backup
  arangod/RocksDBEngine/RocksDBChecksumEnv.cpp
Labels: cla-signed

#17946 Minimal s2 update to fix sanitizer issue
  3rdParty/s2geometry/master/CMakeLists.txt
  3rdParty/s2geometry/master/src/python/pywraps2_test.py
  3rdParty/s2geometry/master/src/python/s2_common.i
  3rdParty/s2geometry/master/src/s2/encoded_s2point_vector.cc
  3rdParty/s2geometry/master/src/s2/s2loop.cc
  3rdParty/s2geometry/master/src/s2/s2loop.h
  3rdParty/s2geometry/master/src/s2/s2polygon.cc
  3rdParty/s2geometry/master/src/s2/util/gtl/compact_array.h
  LICENSES-OTHER-COMPONENTS.md
Labels: cla-signed, Backport Needed

#17951 added documentation for jemalloc patch
  3rdParty/README_maintainers.md
Labels: cla-signed

#17925 [PREG-207] Use struct for pregel options
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  arangod/Pregel/PregelOptions.h
  arangod/Pregel/REST/CMakeLists.txt
  arangod/Pregel/REST/RestControlPregelHandler.cpp
  arangod/Pregel/REST/RestOptions.cpp
  arangod/Pregel/REST/RestOptions.h
  arangod/V8Server/v8-pregel.cpp
  tests/js/client/load-balancing/load-balancing-pregel-noauth-cluster.js
Labels: 3 Pregel, cla-signed

#17941 [cmake] Get rid of duplicated dependencies in graph and rep2 tests
  tests/CMakeLists.txt
  tests/Graph/CMakeLists.txt
  tests/Replication2/CMakeLists.txt
Labels: cla-signed, cmake improvements

#17893 Add native s2 geo analyzer
  3rdParty/README_maintainers.md
  3rdParty/s2geometry/master/CMakeLists.txt
  3rdParty/s2geometry/master/src/s2/s2polygon.h
  arangod/IResearch/AqlHelper.h
  arangod/IResearch/Containers.h
  arangod/IResearch/Geo.cpp
  arangod/IResearch/Geo.h
  arangod/IResearch/GeoAnalyzer.cpp
  arangod/IResearch/GeoAnalyzer.h
  arangod/IResearch/GeoFilter.cpp
  arangod/IResearch/GeoFilter.h
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchAnalyzerFeature.h
  arangod/IResearch/IResearchAqlAnalyzer.cpp
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStoreMeta.cpp
  arangod/IResearch/IResearchDocument.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFilterFactory.cpp
  arangod/IResearch/IResearchFilterFactory.h
  arangod/IResearch/IResearchFilterFactoryCommon.h
  arangod/IResearch/IResearchIdentityAnalyzer.cpp
  arangod/IResearch/IResearchKludge.cpp
  arangod/IResearch/IResearchKludge.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchRocksDBEncryption.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/IResearchRocksDBLink.cpp
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchViewMeta.cpp
  arangod/IResearch/IResearchViewSort.h
  arangod/IResearch/Misc.h
  arangod/IResearch/VelocyPackHelper.h
  lib/Geo/S2/S2MultiPointRegion.cpp
  lib/Geo/S2/S2MultiPointRegion.h
  lib/Geo/S2/S2MultiPolyline.cpp
  lib/Geo/S2/S2MultiPolyline.h
  lib/Geo/ShapeContainer.cpp
  lib/Geo/ShapeContainer.h
  tests/IResearch/GeoAnalyzerTest.cpp
  tests/IResearch/GeoDistanceFilterTest.cpp
  tests/IResearch/GeoFilterTest.cpp
  tests/IResearch/IResearchDocumentTest.cpp
  tests/IResearch/IResearchFields.h
  tests/IResearch/IResearchFilterGeoTest.cpp
  tests/IResearch/IResearchQueryGeoContainsTest.cpp
  tests/IResearch/IResearchQueryGeoDistanceTest.cpp
  tests/IResearch/IResearchQueryGeoInRangeTest.cpp
  tests/IResearch/IResearchQueryGeoIntersectsTest.cpp
  tests/IResearch/common.cpp
  tests/js/server/aql/aql-geo.js
Labels: cla-signed

#17957 remove public willUseV8() / setWillUseV8() APIs
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/StandaloneCalculation.cpp
Labels: cla-signed

#17922 [PREGEL] Provide test binary for Pregel
  arangod/Pregel/CommonFormats.h
  arangod/Pregel/ExecutionNumber.h
  arangod/Pregel/Status/ConductorStatus.h
  arangod/Pregel/Status/ExecutionStatus.h
  arangod/Pregel/Status/Status.h
  lib/Assertions/ProdAssert.h
  tests/CMakeLists.txt
  tests/Pregel/CMakeLists.txt
Labels: 3 Pregel, cla-signed

#17939 Make agency watertight against illegal agents with new UUIDs BTS-1185
  CHANGELOG
  arangod/Agency/AgentConfiguration.cpp
  arangod/Agency/State.cpp
Labels: cla-signed

#17958 log crash info in tests
  js/client/modules/@arangodb/testutils/instance.js
Labels: 3 - Testing, cla-signed

#17938 Make agency watertight against illegal agents with new UUIDs BTS-1185
  CHANGELOG
  arangod/Agency/AgentConfiguration.cpp
  arangod/Agency/State.cpp
Labels: cla-signed

#17931 fix unstable test
  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-off.js
  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-on.js
Labels: 9 Ready to Merge, 3 - Testing, cla-signed

#17960 fix failing test, next attempt
  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-off.js
  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-on.js
Labels: cla-signed

#17947 BTS-1192: fix potential race in sha file creation
  CHANGELOG
  arangod/RocksDBEngine/RocksDBChecksumEnv.cpp
Labels: 9 Ready to Merge, cla-signed

#17954 Fix OASIS-24962
  CHANGELOG
  arangod/Aql/Ast.h
  arangod/Aql/AstNode.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Function.cpp
  arangod/Aql/Functions.cpp
  arangod/Transaction/V8Context.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.inc
  tests/js/common/aql/aql-view-arangosearch-common-noncluster.inc
  tests/js/server/aql/aql-multiple-snippets-javascript-cluster.js
Labels: cla-signed

#17943 [PREG-211] improve directory structure
  arangod/Aql/Functions.cpp
  arangod/Pregel/AlgoRegistry.h
  arangod/Pregel/Algorithm.h
  arangod/Pregel/Algos/ConnectedComponents.cpp
  arangod/Pregel/Algos/DMID/DMID.cpp
  arangod/Pregel/Algos/EffectiveCloseness/EffectiveCloseness.cpp
  arangod/Pregel/Algos/HITS.cpp
  arangod/Pregel/Algos/HITSKleinberg.cpp
  arangod/Pregel/Algos/LabelPropagation.cpp
  arangod/Pregel/Algos/SCC.cpp
  arangod/Pregel/Algos/SLPA.cpp
  arangod/Pregel/Algos/SSSP.cpp
  arangod/Pregel/Algos/ShortestPath.cpp
  arangod/Pregel/Algos/WCC.cpp
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/Conductor/CMakeLists.txt
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/IncomingCache.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/OutgoingCache.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/REST/RestControlPregelHandler.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/VertexComputation.h
  arangod/Pregel/Worker/CMakeLists.txt
  arangod/Pregel/Worker/GraphStore.cpp
  arangod/Pregel/Worker/GraphStore.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/Worker/WorkerConfig.cpp
  arangod/Pregel/Worker/WorkerConfig.h
  arangod/V8Server/v8-pregel.cpp
Labels: 3 Pregel, cla-signed

#17944 BTS-1192: fix a potential race in sha file creation
  CHANGELOG
  arangod/RocksDBEngine/Listeners/RocksDBShaCalculator.cpp
  arangod/RocksDBEngine/Listeners/RocksDBShaCalculator.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  tests/RocksDBEngine/ShaEventListener.cpp
Labels: 3 RocksDB, 9 Ready to Merge, 3 ImportExport, cla-signed

#17962 [PREGEL] Remove ReportManager
  arangod/Pregel/CMakeLists.txt
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/MasterContext.h
  arangod/Pregel/Reports.cpp
  arangod/Pregel/Reports.h
  arangod/Pregel/VertexComputation.h
  arangod/Pregel/Worker/GraphStore.cpp
  arangod/Pregel/Worker/GraphStore.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/WorkerContext.h
Labels: 3 Pregel, cla-signed

#17956 Fix OASIS-24962
  CHANGELOG
  arangod/Aql/Ast.h
  arangod/Aql/AstNode.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Function.cpp
  arangod/Aql/Functions.cpp
  arangod/Transaction/V8Context.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.inc
  tests/js/common/aql/aql-view-arangosearch-noncluster.js
  tests/js/server/aql/aql-multiple-snippets-javascript-cluster.js
Labels: 9 Ready to Merge, cla-signed

#17953 Fix OASIS-24962
  CHANGELOG
  arangod/Aql/Ast.h
  arangod/Aql/AstNode.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Function.cpp
  arangod/Aql/Functions.cpp
  arangod/Transaction/V8Context.cpp
  tests/js/common/aql/aql-view-arangosearch-cluster.inc
  tests/js/common/aql/aql-view-arangosearch-common-noncluster.inc
  tests/js/server/aql/aql-multiple-snippets-javascript-cluster.js
Labels: 9 Ready to Merge, cla-signed

#17923 [BTS-413]
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/dashboardView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/assets/src/mode-aql.js
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.0650c2c921a9123f462a9c97d8c9e76e.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.e7ee12c313a75dbc14cd652b57251c29.js
  js/apps/system/_admin/aardvark/APP/react/build/precache-manifest.e7ee12c313a75dbc14cd652b57251c29.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js
  js/apps/system/_admin/aardvark/APP/react/build/service-worker.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.0dd5f4df.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.0dd5f4df.chunk.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.7ea01d37.chunk.js
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.7ea01d37.chunk.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.7ea01d37.chunk.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.7ea01d37.chunk.js.gz
Labels: 3 UI, cla-signed

#17952 [PREG-226] Use structs for conductor messages
  arangod/Pregel/AlgoRegistry.cpp
  arangod/Pregel/AlgoRegistry.h
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/Conductor/Messages.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Utils.cpp
  arangod/Pregel/Utils.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
  arangod/Pregel/Worker/WorkerConfig.cpp
  arangod/Pregel/Worker/WorkerConfig.h
Labels: 3 Pregel, cla-signed

#17964 Make inspection formatter independent of exceptions
  lib/Inspection/Format.h
  tests/Basics/InspectionTest.cpp
Labels: cla-signed

#17977 allow usage of suffix `b` in startup option values
  lib/ProgramOptions/UnitsHelper.cpp
  tests/ProgramOptions/ParametersTest.cpp
Labels: cla-signed

#17979 small cleanup w.r.t. HeartbeatThread
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/ActionBase.h
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/HeartbeatThread.h
  arangod/Cluster/MaintenanceRestHandler.cpp
  arangod/Cluster/RestClusterHandler.cpp
  arangod/RestServer/ServerFeature.cpp
Labels: cla-signed

#17980 testing: relax timeout of tests under gcov
  js/client/modules/@arangodb/testutils/testing.js
Labels: cla-signed

#17978 added server options for arangosearch cache in RTA
  js/client/modules/@arangodb/testsuites/rta_makedata.js
Labels: 3 - Testing, cla-signed

#17959 [CMake] Add PR presets and clean up a bit
  .gitignore
  CMakePresets.json
Labels: cla-signed

#17961 make frontend dev server available to windows. fix collection view search doesn't allow Ctrl + A
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/collectionsView.js
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/scripts/build.js
  js/apps/system/_admin/aardvark/APP/react/scripts/start.js
Labels: cla-signed

#17984 [BTS-899] _admin/status crash on agents
  arangod/RestHandler/RestStatusHandler.cpp
Labels: cla-signed

#17983 added server options for arangosearch cache in RTA
  js/client/modules/@arangodb/testsuites/rta_makedata.js
Labels: 3 - Testing, cla-signed

#17918 [FE-48] only admin see license info PART2
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
Labels: 1 Bug, 3 UI, 9 Review Required, cla-signed

#17968 fixed ES-1396
  CHANGELOG
  arangod/RestServer/FlushFeature.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  tests/js/client/shell/shell-in-background-failures-noncluster.js
  tests/js/server/recovery/corrupt-wal-marker-multiple.js
Labels: cla-signed

#17753 Bug fix 3.10/endpoints error handling
  js/client/modules/@arangodb/testsuites/endpoints.js
  js/client/modules/@arangodb/testutils/process-utils.js
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: 3 - Testing, cla-signed

#17967 fixed ES-1396
  CHANGELOG
  arangod/RestServer/FlushFeature.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  tests/js/client/shell/shell-in-background-failures-noncluster.js
  tests/js/server/recovery/corrupt-wal-marker-multiple.js
Labels: 9 Ready to Merge, cla-signed

#17976 Fix hotbackup restore w.r.t. permuted servers, BTS-1196
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  tests/HotBackup/HotBackupCoordinatorTest.cpp
Labels: cla-signed

#17965 fixed ES-1396
  CHANGELOG
  arangod/RestServer/FlushFeature.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  tests/js/client/shell/shell-in-background-failures-noncluster.js
  tests/js/server/recovery/corrupt-wal-marker-multiple.js
Labels: 9 Ready to Merge, cla-signed

#17895 SEARCH-323 SEARCH-279 Have a dedicated storage engine snapshot for ArangoSearch index and aggressive LM
  arangod/Aql/CMakeLists.txt
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IResearchViewExecutor.tpp
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
  arangod/ClusterEngine/ClusterEngine.h
  arangod/IResearch/CMakeLists.txt
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchReadUtils.cpp
  arangod/IResearch/IResearchReadUtils.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/Search.cpp
  arangod/IResearch/Search.h
  arangod/IResearch/SearchDoc.h
  arangod/IResearch/ViewSnapshot.cpp
  arangod/IResearch/ViewSnapshot.h
  arangod/IResearch/ViewTrx.h
  arangod/RocksDBEngine/Methods/RocksDBBatchedMethods.h
  arangod/RocksDBEngine/Methods/RocksDBBatchedWithIndexMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBBatchedWithIndexMethods.h
  arangod/RocksDBEngine/Methods/RocksDBReadOnlyBaseMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBReadOnlyBaseMethods.h
  arangod/RocksDBEngine/Methods/RocksDBSstFileMethods.h
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBMethods.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/StorageEngine/StorageEngine.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/IResearch/IResearchQueryGeoContainsTest.cpp
  tests/IResearch/IResearchQueryGeoDistanceTest.cpp
  tests/IResearch/IResearchQueryGeoInRangeTest.cpp
  tests/IResearch/IResearchQueryGeoIntersectsTest.cpp
  tests/IResearch/IResearchViewCountApproximateTest.cpp
  tests/IResearch/IResearchViewNodeTest.cpp
  tests/IResearch/IResearchViewSortedTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/Mocks/StorageEngineMock.h
Labels: cla-signed

#17853 BTS-943: testing: move test out of non-existing suite, adjust to new instance methods (#17203)
  tests/js/client/shell/api/api-gharial-spec.js
  tests/js/client/shell/api/cluster-metrics-cluster-spec.js
Labels: 3 - Testing, cla-signed

#17966 fixed ES-1396
  CHANGELOG
  arangod/RestServer/FlushFeature.h
  arangod/RocksDBEngine/RocksDBBackgroundThread.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  tests/js/client/shell/shell-in-background-failures-noncluster.js
  tests/js/server/recovery/corrupt-wal-marker-multiple.js
Labels: 9 Ready to Merge, cla-signed

#17990 testing: split the long running server_parameters testsuite into buckets for better parallelism.
  js/client/modules/@arangodb/testsuites/server_permissions.js
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#17994 Bug fix 3.9/search 429 plus irsearch asan
  3rdParty/iresearch/core/utils/bit_packing.cpp
  CHANGELOG
  arangod/IResearch/IResearchAnalyzerFeature.cpp
Labels: 3 ArangoSearch, cla-signed

#17864 Added lightweight libarango.
  arangod/Cluster/ClusterTypes.cpp
  arangod/Cluster/ClusterTypes.h
  arangod/Metrics/CMakeLists.txt
  arangod/V8Server/V8DealerFeature.cpp
  client-tools/CMakeLists.txt
  client-tools/Import/ImportFeature.cpp
  client-tools/Shell/V8ShellFeature.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/RebootId.cpp
  lib/Basics/RebootId.h
  lib/Basics/StringBuffer.cpp
  lib/Basics/StringBufferAdvanced.cpp
  lib/Basics/Utf8Helper.cpp
  lib/Basics/Utf8Helper.h
  lib/Basics/files-advanced.cpp
  lib/Basics/files.cpp
  lib/Basics/files.h
  lib/Basics/process-utils.cpp
  lib/Basics/tri-strings.cpp
  lib/Basics/win-utils.cpp
  lib/Basics/win-utils.h
  lib/CMakeLists.txt
  lib/CrashHandler/CMakeLists.txt
  lib/ProgramOptions/IniFileParser.cpp
Labels: cinfra, cla-signed

#17991 Log information about follower state/apply progress
  CHANGELOG
  arangod/Agency/ActiveFailoverJob.cpp
Labels: cla-signed

#17992 Log information about follower state/apply progress
  CHANGELOG
  arangod/Agency/ActiveFailoverJob.cpp
Labels: cla-signed

#17993 Log information about follower state/apply progress
  CHANGELOG
  arangod/Agency/ActiveFailoverJob.cpp
Labels: cla-signed

#17996 [CINFRA] PrototypeState check ready
  tests/js/server/replication2/replication2-prototype-replicated-state-cluster.js
Labels: cinfra, cla-signed

#18002 Fix devel tsan suppressions
  tsan_arangodb_suppressions.txt
Labels: cla-signed

#17972 [PREG-226] Use structs for worker messages
  arangod/Aql/Functions.cpp
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/Conductor/Conductor.h
  arangod/Pregel/IncomingCache.cpp
  arangod/Pregel/IncomingCache.h
  arangod/Pregel/OutgoingCache.cpp
  arangod/Pregel/OutgoingCache.h
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/Statistics.h
  arangod/Pregel/Worker/Messages.h
  arangod/Pregel/Worker/Worker.cpp
  arangod/Pregel/Worker/Worker.h
Labels: 3 Pregel, cla-signed

#17971 [CINFRA-665] Drop replicated states along with their database
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBKeyBounds.cpp
  arangod/RocksDBEngine/RocksDBKeyBounds.h
  arangod/RocksDBEngine/RocksDBPersistedLog.cpp
  arangod/RocksDBEngine/RocksDBPersistedLog.h
  tests/IResearch/common.cpp
  tests/Replication2/ReplicatedLog/StorageEngineMethodsTest.cpp
Labels: cinfra, cla-signed

#17982 improve object lifetime management in replication manager
  arangod/RocksDBEngine/CMakeLists.txt
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBReplicationContextGuard.cpp
  arangod/RocksDBEngine/RocksDBReplicationContextGuard.h
  arangod/RocksDBEngine/RocksDBReplicationIterator.cpp
  arangod/RocksDBEngine/RocksDBReplicationIterator.h
  arangod/RocksDBEngine/RocksDBReplicationManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationManager.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/RocksDBEngine/RocksDBV8Functions.cpp
Labels: cla-signed

#18004 Disable "maybe-uninitialized" warnings as errors for GCC
  CMakeLists.txt
Labels: 9 Ready to Merge, cla-signed

#18011 [SEARCH-284] Fix geo distance/in_range for search
  arangod/IResearch/GeoAnalyzer.cpp
  arangod/IResearch/GeoAnalyzer.h
  arangod/IResearch/GeoFilter.cpp
  tests/IResearch/GeoAnalyzerTest.cpp
  tests/js/server/aql/aql-geo.js
Labels: cla-signed, Backport Needed

#18007 Add missing include for gcc 11.2 with glibc
  lib/Assertions/ProdAssert.h
Labels: cla-signed

#17988 move IOHeartbeatThread into its own file
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/RestServer/IOHeartbeatThread.cpp
  arangod/RestServer/IOHeartbeatThread.h
  arangod/arangoserver.cmake
Labels: cla-signed

#18003 Feature/cinfra 660 collectiongroups in plan
  arangod/Agency/AgencyPaths.h
  arangod/Cluster/ClusterCollectionMethods.cpp
  arangod/Cluster/ClusterCollectionMethods.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/Utils/CMakeLists.txt
  arangod/Cluster/Utils/CollectionGroupUpdates.cpp
  arangod/Cluster/Utils/CollectionGroupUpdates.h
  arangod/Cluster/Utils/TargetCollectionAgencyWriter.cpp
  arangod/Cluster/Utils/TargetCollectionAgencyWriter.h
  arangod/Replication2/AgencyCollectionSpecification.cpp
  arangod/Replication2/AgencyCollectionSpecification.h
  arangod/Replication2/AgencyCollectionSpecificationInspectors.h
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/js/server/replication2/replication2-collectiongroups-cluster.js
Labels: cinfra, cla-signed

#18016 fix inefficient temporary string creation for log messages
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Agency/AddFollower.cpp
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/MoveShard.cpp
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/Supervision.cpp
  arangod/Cluster/DropCollection.cpp
  arangod/Cluster/DropIndex.cpp
  arangod/Cluster/EnsureIndex.cpp
  arangod/Cluster/ResignShardLeadership.cpp
  arangod/Cluster/TakeoverShardLeadership.cpp
  arangod/Cluster/UpdateCollection.cpp
  arangod/Replication/TailingSyncer.cpp
Labels: cla-signed

#18018 small code improvements for agency code
  arangod/Agency/AddFollower.cpp
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/JobContext.cpp
  arangod/Agency/JobContext.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/Store.cpp
  arangod/Agency/Store.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  tests/Agency/SupervisionTest.cpp
Labels: cla-signed

#18017 simplify code
  arangod/Agency/AsyncAgencyComm.cpp
  arangod/Agency/Store.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Auth/Common.cpp
  arangod/Auth/Common.h
  arangod/Network/Methods.cpp
  arangod/Network/Utils.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/RestHandler/RestUsersHandler.cpp
Labels: cla-signed

#17974 [BTS-266] Turning `--cluster.force-one-shard` on later should not always enable Analyzer optimizations
  CHANGELOG
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  js/client/modules/@arangodb/testsuites/server_permissions.js
Labels: cla-signed

#17975 Fix hotbackup restore w.r.t. permuted servers, BTS-1196
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  tests/HotBackup/HotBackupCoordinatorTest.cpp
Labels: cla-signed

#17924 [CINFRA] Snapshot Version
  arangod/Replication2/ReplicatedLog/Components/IStateHandleManager.h
  arangod/Replication2/ReplicatedLog/Components/LogFollower2.cpp
  arangod/Replication2/ReplicatedLog/Components/SnapshotManager.cpp
  arangod/Replication2/ReplicatedLog/Components/SnapshotManager.h
  arangod/Replication2/ReplicatedLog/Components/StateHandleManager.cpp
  arangod/Replication2/ReplicatedLog/Components/StateHandleManager.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  tests/Replication2/CMakeLists.txt
  tests/Replication2/Mocks/LogEventRecorder.cpp
  tests/Replication2/Mocks/LogEventRecorder.h
  tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
  tests/Replication2/ReplicatedLog/LogFollower/AppendEntriesTest.cpp
  tests/Replication2/ReplicatedLog/ReplicatedLogConnectTest.cpp
Labels: cinfra, cla-signed

#17929 [CINFRA] TermIndexMapping
  arangod/Replication2/CMakeLists.txt
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/Algorithms.h
  arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
  arangod/Replication2/ReplicatedLog/Components/IStorageManager.h
  arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
  arangod/Replication2/ReplicatedLog/Components/StorageManager.h
  arangod/Replication2/ReplicatedLog/InMemoryLog.cpp
  arangod/Replication2/ReplicatedLog/InMemoryLog.h
  arangod/Replication2/ReplicatedLog/TermIndexMapping.cpp
  arangod/Replication2/ReplicatedLog/TermIndexMapping.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  tests/Replication2/CMakeLists.txt
  tests/Replication2/ReplicatedLog/Algorithms/DetectConflictTest.cpp
  tests/Replication2/ReplicatedLog/Components/CompactionManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/TermIndexMapping.cpp
Labels: cinfra, cla-signed

#17940 [CINFRA] Use Persisted LogIterator on Follower
  arangod/Replication2/ReplicatedLog/Components/IStorageManager.h
  arangod/Replication2/ReplicatedLog/Components/LogFollower2.cpp
  arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
  arangod/Replication2/ReplicatedLog/Components/StorageManager.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  tests/Replication2/ReplicatedLog/Components/CompactionManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/FollowerCommitManagerTest.cpp
  tests/Replication2/ReplicatedLog/Components/SnapshotManagerTest.cpp
Labels: cinfra, cla-signed

#18026 [PREGEL] Delete duplicated log id
  arangod/Pregel/Conductor/Conductor.cpp
Labels: 3 Pregel, cla-signed

#18027 disable full chaos run on windows for the nightlies until s.b. wants to work on it
  tests/test-definitions.txt
Labels: 4 Windows, 3 - Testing, cla-signed

#17999 [CINFRA-666] Pass vocbase to document state machine
  arangod/Replication2/ReplicatedLog/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogFollower.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/ReplicatedLog.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.cpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentCore.cpp
  arangod/Replication2/StateMachines/Document/DocumentCore.h
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/Replication2/StateMachines/Document/DocumentStateMachineFeature.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.h
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.cpp
  arangod/Replication2/StateMachines/Prototype/PrototypeStateMachine.h
  arangod/VocBase/VocbaseInfo.cpp
  arangod/VocBase/VocbaseInfo.h
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  lib/Assertions/ProdAssert.h
  tests/Replication2/Mocks/DocumentStateMocks.cpp
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedLog/ReplicatedLogConnectTest.cpp
  tests/Replication2/ReplicatedState/DocumentStateMachineTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/MyStateMachine.cpp
  tests/Replication2/ReplicatedState/StateMachines/MyStateMachine.h
Labels: cinfra, cla-signed

#18029 disable test on asan / gcov; instrumented binaries don't scale for this
  tests/js/server/aql/aql-complex-queries-callstack-noasan.js
Labels: cla-signed
