Repository arangodb/arangodb, pull requests merged in 2023-07, with the labels that each got.

#19343 adjust options for RocksDB WAL file deletion
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  lib/ApplicationFeatures/OptionsCheckFeature.cpp
Labels: cla-signed

#19353 [CINFRA-777] Report syncIndex to the leader
  arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/NetworkMessages.cpp
  arangod/Replication2/ReplicatedLog/NetworkMessages.h
  tests/Replication2/ReplicatedLog/LogFollower/AppendEntriesTest.cpp
Labels: cinfra, cla-signed

#19332 clean up temporary backup directory if backup fails
  CHANGELOG
Labels: cla-signed

#19356 fix a failing cache test
  tests/js/server/aql/aql-index-cache.js
Labels: cla-signed

#19359 [CINFRA-791] Fix supervision flaky test
  tests/js/server/replication2/replication2-supervision-replicated-log-target-cluster.js
Labels: cinfra, cla-signed

#19357 adjust hit rates test
  arangod/Cache/PlainCache.cpp
  arangod/Cache/TransactionalCache.cpp
  tests/Cache/PlainCache.cpp
Labels: cla-signed

#19339 Add grace period for disconnected leaders in active failover
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
  js/client/modules/@arangodb/testsuites/resilience.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  tests/js/client/active-failover/basic.js
  tests/js/client/active-failover/disconnected-leader-nonwindows.js
  tests/js/client/active-failover/readonly.js
Labels: cla-signed

#19351 [CINFRA-792] Fix flaky test
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js
Labels: cinfra, cla-signed

#19364 [OASIS-25344][3.10] Fix document API inconsistency
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  tests/js/client/shell/api/document-read.js
Labels: 1 Bug, 3 API, cla-signed

#19365 [OASIS-25344][3.11] API inconsistency regression test
  tests/js/client/shell/api/multi/document-read.js
Labels: cla-signed

#19366 [OASIS-25344][DEVEL] API inconsistency regression test
  tests/js/client/shell/api/multi/document-read.js
Labels: cla-signed

#19367 [OASIS-25344][3.9] Fix document API inconsistency
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  tests/js/client/shell/api/document-read.js
Labels: cla-signed

#19370 Make lower and upper bound values for cache fill ratio configurable
  CHANGELOG
  arangod/Cache/Cache.cpp
  arangod/Cache/CacheManagerFeature.cpp
  arangod/Cache/CacheManagerFeature.h
  arangod/Cache/Common.h
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/Cache/PlainBucket.h
  arangod/Cache/Table.cpp
  arangod/Cache/Table.h
  arangod/Cache/TransactionalBucket.h
  tests/Cache/Manager.cpp
  tests/Cache/PlainCache.cpp
  tests/Cache/Rebalancer.cpp
  tests/Cache/Table.cpp
  tests/Cache/TransactionalCache.cpp
  tests/Cache/TransactionalCacheVPackKeyHasher.cpp
  tests/Cache/TransactionsWithBackingStore.cpp
Labels: cla-signed

#19360 Fix SEARCH-465
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/Indexes/Index.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  tests/Mocks/IResearchInvertedIndexMock.cpp
  tests/Mocks/IResearchInvertedIndexMock.h
  tests/Mocks/PhysicalCollectionMock.cpp
  tests/js/server/recovery/view-arangosearch-link-populate-truncate-replay-noncluster.js
  tests/js/server/recovery/view-search-alias-populate-truncate-replay-noncluster.js
Labels: cla-signed, Backport Needed

#19372 fix small issues in client-tools
  client-tools/Backup/arangobackup.cpp
  client-tools/Import/SenderThread.cpp
  client-tools/Utils/ManagedDirectory.cpp
Labels: cla-signed

#18516 Index progress visibility
  arangod/Cluster/Action.h
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/ActionBase.h
  arangod/Cluster/EnsureIndex.cpp
  arangod/Cluster/EnsureIndex.h
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndex.h
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Indexes.cpp
  arangod/VocBase/Methods/Indexes.h
  tests/Maintenance/MaintenanceFeatureMock.h
  tests/Mocks/PhysicalCollectionMock.cpp
  tests/Mocks/PhysicalCollectionMock.h
Labels: cla-signed

#19374 Replication 2.0 refactoring the 3rd
  arangod/Replication2/ReplicatedLog/Components/IInMemoryLogManager.h
  arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp
  arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.h
  arangod/Replication2/ReplicatedLog/InMemoryLog.cpp
  arangod/Replication2/ReplicatedLog/InMemoryLog.h
  arangod/Replication2/ReplicatedLog/InMemoryLogEntry.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLogIterator.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/LeaderStateManager.h
  arangod/Replication2/ReplicatedState/LeaderStateManager.tpp
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/ReplicatedStateImpl.tpp
  arangod/Replication2/ReplicatedState/ReplicatedStateManager.h
  arangod/Replication2/ReplicatedState/ReplicatedStateManager.tpp
  arangod/Replication2/ReplicatedState/StreamProxy.h
  arangod/Replication2/ReplicatedState/StreamProxy.tpp
  arangod/Replication2/ReplicatedState/UnconfiguredStateManager.h
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.cpp
  tests/Replication2/ReplicatedState/FollowerResignTest.cpp
  tests/Replication2/ReplicatedState/FollowerSnapshotTest.cpp
  tests/Replication2/ReplicatedState/FollowerWaitForTest.cpp
  tests/Replication2/ReplicatedState/LeaderRecoveryTest.cpp
  tests/Replication2/ReplicatedState/LeaderResignTest.cpp
  tests/Replication2/ReplicatedState/StateCleanupTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/DocumentStateMachineTest.h
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/ShardHandlerTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/MyStateMachine.cpp
  tests/Replication2/ReplicatedState/StateManagerTest.cpp
Labels: cla-signed

#19377 small code simplifications
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
Labels: cla-signed

#19379 remove unnecessary parameter from createBlock() API
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ClusterNodes.h
  arangod/Aql/CollectNode.cpp
  arangod/Aql/CollectNode.h
  arangod/Aql/DistributeConsumerNode.cpp
  arangod/Aql/DistributeConsumerNode.h
  arangod/Aql/EnumeratePathsNode.cpp
  arangod/Aql/EnumeratePathsNode.h
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  arangod/Aql/ModificationNodes.cpp
  arangod/Aql/ModificationNodes.h
  arangod/Aql/MultipleRemoteModificationNode.cpp
  arangod/Aql/MultipleRemoteModificationNode.h
  arangod/Aql/MutexNode.cpp
  arangod/Aql/MutexNode.h
  arangod/Aql/ShortestPathNode.cpp
  arangod/Aql/ShortestPathNode.h
  arangod/Aql/SortNode.cpp
  arangod/Aql/SortNode.h
  arangod/Aql/SubqueryEndExecutionNode.cpp
  arangod/Aql/SubqueryEndExecutionNode.h
  arangod/Aql/SubqueryStartExecutionNode.cpp
  arangod/Aql/SubqueryStartExecutionNode.h
  arangod/Aql/TraversalNode.cpp
  arangod/Aql/TraversalNode.h
  arangod/Aql/WindowNode.cpp
  arangod/Aql/WindowNode.h
  tests/Aql/MockTypedNode.cpp
  tests/Aql/MockTypedNode.h
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewNodeTest.cpp
Labels: cla-signed

#19363 [DUMP] Retry on write, read and connect errors
  CHANGELOG
  arangod/Agency/Job.cpp
  arangod/Agency/Supervision.cpp
  arangod/Cluster/TraverserEngine.cpp
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/Pregel/Algos/RecoveringPageRank.cpp
  arangod/RestHandler/RestDumpHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  client-tools/Dump/DumpFeature.cpp
  lib/Rest/HttpResponse.h
  lib/SimpleHttpClient/SimpleHttpClient.cpp
  tests/js/client/server_permissions/test-foxx-service-access-denied.js
Labels: cla-signed

#19378 use an std::allocator-like thing instead of PMRs
  arangod/Aql/Optimizer.cpp
  arangod/Aql/Optimizer.h
  arangod/Aql/Query.cpp
  arangod/IResearch/IResearchAqlAnalyzer.cpp
  lib/Basics/ResourceUsage.h
  lib/Containers/RollingVector.h
Labels: cla-signed

#19376 fix small issues in client-tools, add split file support for dump/restore
  client-tools/Backup/arangobackup.cpp
  client-tools/Dump/DumpFeature.cpp
  client-tools/Dump/DumpFeature.h
  client-tools/Import/SenderThread.cpp
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Restore/RestoreFeature.h
  client-tools/Utils/ManagedDirectory.cpp
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testutils/process-utils.js
  tests/js/client/shell/shell-dump-integration.js
  tests/js/client/shell/shell-restore-integration.js
  tests/test-definitions.txt
Labels: cla-signed

#19383 Bug fix/read write connect error retry
  CHANGELOG
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/RestHandler/RestDumpHandler.cpp
  client-tools/Dump/DumpFeature.cpp
  lib/Rest/HttpResponse.h
  lib/SimpleHttpClient/SimpleHttpClient.cpp
  tests/js/client/server_permissions/test-foxx-service-access-denied.js
Labels: cla-signed

#19337 Add grace period for disconnected leaders in active failover
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
  js/client/modules/@arangodb/testsuites/resilience.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  tests/js/client/active-failover/basic.js
  tests/js/client/active-failover/disconnected-leader-nonwindows.js
  tests/js/client/active-failover/readonly.js
Labels: cla-signed

#19382 [QA-427] Upgrade OpenSSL to 3.0.9 for 3.10
  CHANGELOG
  CMakeLists.txt
  VERSIONS
  cmake/custom/ArangoDB_FindOpenSSL_WIN32.cmake
Labels: OpenSSL, cla-signed

#19125 QA-433: re-sync various testing.js changes to 3.11
  js/client/modules/@arangodb/testsuites/aql.js
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testsuites/fuerte.js
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testsuites/server_permissions.js
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/test-utils.js
  js/client/modules/@arangodb/testutils/testing.js
  js/client/modules/@arangodb/testutils/testrunner.js
  lib/V8/v8-utils.cpp
Labels: 3 - Testing, cla-signed

#19348 QA-451: testing: implement san logfile reading in testing.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/testing.js
Labels: 3 - Testing, cla-signed

#19375 [CINFRA-778] Use syncIndex for compaction
  arangod/Replication2/ReplicatedLog/Algorithms.cpp
  arangod/Replication2/ReplicatedLog/Algorithms.h
  arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp
  arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedLog/LogStatus.h
  arangod/Replication2/ReplicatedLog/types.h
  arangod/Replication2/Storage/RocksDB/AsyncLogWriteBatcher.cpp
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Replication2/ReplicatedLog/Algorithms/CalcCommitIndexTest.cpp
  tests/js/server/replication2/replication2-replicated-log-wait-for-sync.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
  tests/js/server/replication2/replication2-soft-write-concern-replicated-log-cluster.js
Labels: cinfra, cla-signed

#19346 Optimise runtime lock performance [3.11]
  CHANGELOG
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/Transaction/Manager.h
  lib/Basics/ReadWriteLock.cpp
  lib/Basics/ReadWriteLock.h
  tests/Basics/ReadWriteLockTest.cpp
Labels: cla-signed

#19385 track sizes of requests more accurately
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/RestHandler/RestBaseHandler.cpp
  arangod/RestHandler/RestBaseHandler.h
  arangod/RestHandler/RestBatchHandler.cpp
  arangod/RestHandler/RestImportHandler.cpp
  lib/Rest/GeneralRequest.cpp
  lib/Rest/GeneralRequest.h
  lib/Rest/HttpRequest.cpp
  lib/Rest/HttpRequest.h
  lib/Rest/VstRequest.cpp
  lib/Rest/VstRequest.h
  tests/IResearch/RestHandlerMock.cpp
  tests/IResearch/RestHandlerMock.h
  tests/js/client/shell/api/multi/import-novst.js
Labels: cla-signed

#19387 [CINFRA] Adding error messages
  arangod/Replication2/ReplicatedLog/Components/StorageManager.cpp
Labels: cinfra, cla-signed

#19340 Add grace period for disconnected leaders in active failover
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
  tests/js/client/active-failover/basic.js
  tests/js/client/active-failover/disconnected-leader-nonwindows.js
Labels: cla-signed

#19027 [3.11][BTS-1331] Optimize data overfetch in cluster traversals
  CHANGELOG
  arangod/Graph/PathManagement/PathValidator.cpp
  arangod/Graph/PathManagement/PathValidator.h
  arangod/Graph/PathManagement/PathValidatorTracer.cpp
  arangod/Graph/PathManagement/PathValidatorTracer.h
  arangod/Graph/Providers/ClusterProvider.cpp
  arangod/Graph/Queues/FifoQueue.h
  arangod/Graph/Queues/LifoQueue.h
  arangod/Graph/Queues/WeightedQueue.h
  arangod/Graph/Steps/ClusterProviderStep.cpp
  arangod/Graph/Steps/ClusterProviderStep.h
  arangod/Graph/Steps/SingleServerProviderStep.h
  arangod/Graph/Types/ValidationResult.cpp
  arangod/Graph/Types/ValidationResult.h
  tests/Mocks/MockGraphProvider.h
Labels: 3 Graph, cla-signed

#19158 Use libunwind in jemalloc heap profiling
  3rdParty/CMakeLists.txt
  3rdParty/jemalloc/CMakeLists.txt
  CHANGELOG
  CMakeLists.txt
  arangod/CMakeLists.txt
  tests/CMakeLists.txt
  tests/js/client/server_parameters/test-memory-profiling-noncluster.js
Labels: cla-signed

#19229 Backport: Bug fix/bts 1460 Directly kill aborted query, do not wait for GC
  CHANGELOG
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/RemoteExecutor.cpp
  tests/js/server/aql/aql-failures-cluster.js
Labels: 1 Bug, 9 Ready to Merge, cla-signed

#19384 Bug fix 3.11/read write connect error retry
  CHANGELOG
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/RestHandler/RestDumpHandler.cpp
  client-tools/Dump/DumpFeature.cpp
  lib/Rest/HttpResponse.h
  lib/SimpleHttpClient/SimpleHttpClient.cpp
  tests/js/client/server_permissions/test-foxx-service-access-denied.js
Labels: cla-signed

#19265 Medium prio lockups in AgencyCache and Query shutdown, BTS-1475, BTS-1486
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/Cluster/AgencyCache.cpp
  tests/js/client/shell/shell-med-queue-blocked-cluster.js
Labels: cla-signed

#19393 Bug fix/fix active failover tests
  js/client/modules/@arangodb/testsuites/resilience.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/testrunner.js
  tests/js/client/active-failover/basic.js
  tests/js/client/active-failover/disconnected-leader-nonwindows.js
  tests/js/client/active-failover/readonly.js
Labels: 3 - Testing, cla-signed

#19390 Add python code to control a cluster and HotBackup test script
  scripts/toolbox/HotBackupConsistencyTest.py
  scripts/toolbox/modules/ArangodEnvironment/Agent.py
  scripts/toolbox/modules/ArangodEnvironment/ArangodEnvironment.py
  scripts/toolbox/modules/ArangodEnvironment/ArangodServer.py
  scripts/toolbox/modules/ArangodEnvironment/Coordinator.py
  scripts/toolbox/modules/ArangodEnvironment/DBServer.py
  scripts/toolbox/modules/ArangodEnvironment/__init__.py
Labels: cla-signed

#19399 Do not run LongRunning google tests
  js/client/modules/@arangodb/testsuites/gtest.js
Labels: cla-signed

#19401 testing: don't sniff anymore
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#19406 testing: don't sniff anymore
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#19394 Bug fix 3.11/fix active failover tests
  js/client/modules/@arangodb/testsuites/resilience.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/testrunner.js
  tests/js/client/active-failover/basic.js
  tests/js/client/active-failover/disconnected-leader-nonwindows.js
  tests/js/client/active-failover/readonly.js
Labels: 3 - Testing, cla-signed

#19398 QA-451: testing: implement san logfile reading in testing.js (#19348)
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/testing.js
Labels: 3 - Testing, cla-signed

#19362 fix: FE-304, FE-305, use navigator.onLine for checking internet connection, correct path for running/slow queries
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/queryManagementCollectionActive.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/queryManagementCollectionSlow.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.bf11c9c2.css
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.bf11c9c2.css.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.2a86f609.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.2a86f609.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.2a86f609.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.501aab80.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.501aab80.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.501aab80.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.9512fedafa8e56b22d68.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.beab3f58283dd9683614.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.916656a297b1a9fa698b.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.abd255e8d4a57cfa076a.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.8d11d1e159ab0e14c0e6.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.9c9c164e699d486b5abf.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.81dc9b21d2ced318e9ae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.bcf2ba9ef2bd549116a9.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-dark.994d1553f409200f5901.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-icon.35807d6e11925bd44973.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb.609cd935d9d34dab5e6b.eot.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/favicon.909457142f6be9dae418.ico.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.ed6298903ae1554c7f3e.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.f0af1680f082547a7aae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/jsoneditor-icons.ffbb30248a6fc9adfc7f.svg.gz
Labels: 1 Bug, 3 UI, cla-signed

#19407 BTS-1512: testing: if we have a crashdump, test state must be failed
  arangod/IResearch/IResearchDataStore.cpp
  scripts/test/testing_runner.py
Labels: cla-signed

#19411 BTS-1512: Bug fix 3.11/fix crash state
  arangod/IResearch/IResearchDataStore.cpp
  scripts/test/testing_runner.py
Labels: 3 - Testing, cla-signed

#19413 BTS-1512: disable coredumps in this case
  arangod/IResearch/IResearchLink.cpp
Labels: 3 - Testing, cla-signed

#19412 BTS-1512: disable coredumps in this case
  arangod/IResearch/IResearchDataStore.cpp
Labels: 3 - Testing, cla-signed

#19392 adjust LZ4 parameter documentation
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 3 Documentation, cla-signed

#19415 improve documentation for /_admin/server/availability route
  Documentation/DocuBlocks/Rest/Administration/get_admin_server_availability.md
Labels: 3 Documentation, cla-signed

#19409 attempt to fix chaos tests
  js/client/modules/@arangodb/test-helper.js
Labels: 3 - Testing, cla-signed

#19410 [CINFRA] Fix flaky test
  tests/js/server/replication2/replication2-replicated-log-wait-for-sync.js
Labels: cinfra, cla-signed

#19092 [APM-674] ClusterInfo memory accounting
  Documentation/Metrics/arangodb_internal_cluster_info_memory_usage.yaml
  arangod/Aql/Optimizer.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/Cluster/ClusterTypes.h
  arangod/Cluster/v8-cluster.cpp
  arangod/IResearch/IResearchMetricStats.h
  arangod/Metrics/MetricsResourceMonitor.h
  arangod/Network/Utils.cpp
  arangod/Pregel/GraphStore/GraphSerdeConfigBuilderCluster.cpp
  lib/Basics/ResourceUsage.h
  lib/Basics/debugging.h
  tests/Basics/CMakeLists.txt
  tests/Basics/ResourceUsageAllocatorTest.cpp
  tests/js/client/shell/shell-cluster-info-memory-usage-cluster.js
Labels: cla-signed

#19408 attempt to fix chaos tests
  js/client/modules/@arangodb/test-helper.js
Labels: cla-signed

#19423 [BTS-1428] Explaining the reson for suppression
  tsan_arangodb_suppressions.txt
Labels: cinfra, cla-signed

#19421 [CINFRA-805] Pass waitForSync parameter per operation (e.g. document modification)
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/ReplicatedLog.h
  arangod/Replication2/ReplicatedState/StreamProxy.h
  arangod/Replication2/ReplicatedState/StreamProxy.tpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateMachine.h
  arangod/Replication2/Streams/Streams.h
  arangod/Transaction/Methods.cpp
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/LeaderTest.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#19244 Use custom docker image for CircelCI tests
  .circleci/base_config.yml
  scripts/build/README.md
  scripts/build/build-image.sh
  scripts/docker/README.md
  scripts/docker/build/arangodb-build-x86-64.Dockerfile
  scripts/docker/build/build-image.sh
  scripts/docker/build/install-openldap.sh
  scripts/docker/build/install-openssl.sh
  scripts/docker/test/arangodb-test-x86-64.Dockerfile
  scripts/docker/test/build-image.sh
Labels: cla-signed

#19417 Add `--database.max-databases`
  CHANGELOG
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/VocBase/Methods/Databases.cpp
  tests/js/client/server_parameters/max-databases-limit.js
  tests/js/client/server_parameters/max-databases-unlimited.js
Labels: cla-signed

#19336 [FE-289] Improve database views
  .gitignore
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/databaseView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/databaseView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.bf11c9c2.css
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.bf11c9c2.css.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.44b463de.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.44b463de.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.44b463de.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.7a5f1c93.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.7a5f1c93.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.7a5f1c93.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.9512fedafa8e56b22d68.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.beab3f58283dd9683614.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.916656a297b1a9fa698b.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.abd255e8d4a57cfa076a.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.8d11d1e159ab0e14c0e6.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.9c9c164e699d486b5abf.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.81dc9b21d2ced318e9ae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.bcf2ba9ef2bd549116a9.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-dark.994d1553f409200f5901.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-icon.35807d6e11925bd44973.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb.609cd935d9d34dab5e6b.eot.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/favicon.909457142f6be9dae418.ico.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.ed6298903ae1554c7f3e.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.f0af1680f082547a7aae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/jsoneditor-icons.ffbb30248a6fc9adfc7f.svg.gz
  js/apps/system/_admin/aardvark/APP/react/src/App.js
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/Database.types.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/DatabasesContext.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/DatabasesReactView.jsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/DatabasesView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/DatabasesViewWrap.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/addDatabase/AddDatabaseForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/addDatabase/AddDatabaseModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/listDatabases/DatabasesTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/useFetchDatabase.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/useFetchDatabases.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/useFetchInitialValues.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/viewDatabase/DatabaseInfo.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/viewDatabase/DeleteDatabaseModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/viewDatabase/SingleDatabaseView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/users/useFetchUsers.ts
Labels: 1 Feature, 3 UI, cla-signed

#19425 Reactivate building devel in CI on merge.
  .circleci/config.yml
Labels: cla-signed

#18886 Bug-Fix-3.10/FE-162-display-geodesic-lines backport
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/css/leaflet.css
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/leaflet.js
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/src/App.js
  js/apps/system/_admin/aardvark/APP/react/yarn.lock
Labels: 1 Bug, 3 UI, cla-signed

#19361 bug-fix-3.10/FE-303: geo map doesn't show up in query UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/src/App.js
  js/apps/system/_admin/aardvark/APP/react/yarn.lock
Labels: 1 Bug, 3 UI, cla-signed

#19404 bug-fix-3.10/fix FE-304, FE-305, use navigator.onLine for checking internet connection, correct path for running/slow queries
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/queryManagementCollectionActive.js
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/queryManagementCollectionSlow.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 1 Bug, 3 UI, cla-signed

#19099 [3.10] Minor code cleanup & compilation fix
  arangod/Agency/RemoveFollower.cpp
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Cluster/AutoRebalance.cpp
Labels: 9 Review Required, cla-signed

#19431 Removed an unnecessary header include and fixed aftermath
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/CreateCollection.h
  arangod/Graph/Graph.cpp
  arangod/Graph/GraphManager.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  arangod/VocBase/vocbase.h
Labels: cla-signed

#19279 DOC-489 | APM-688 | Add description for rebalance `piFactor`
  Documentation/DocuBlocks/Rest/Cluster/1_structs.md
Labels: 3 Documentation, cla-signed

#19278 DOC-489 | APM-688 | Add description for rebalance `piFactor`
  Documentation/DocuBlocks/Rest/Cluster/1_structs.md
Labels: 3 Documentation, cla-signed

#19280 DOC-489 | APM-688 | Add description for rebalance `piFactor`
  Documentation/DocuBlocks/Rest/Cluster/1_structs.md
Labels: 3 Documentation, cla-signed

#19434 Fixing Hotbackup Test
  scripts/toolbox/HotBackupConsistencyTest.py
Labels: cla-signed

#19113 Remove ttl and observe support in Agency
  CHANGELOG
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Agency/AddFollower.cpp
  arangod/Agency/AgencyCommon.h
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/CleanOutServer.h
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Inception.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/JobContext.cpp
  arangod/Agency/MoveShard.cpp
  arangod/Agency/MoveShard.h
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/NodeDeserialization.h
  arangod/Agency/ReconfigureReplicatedLog.cpp
  arangod/Agency/ReconfigureReplicatedLog.h
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/ResignLeadership.h
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Agency/RestAgencyPrivHandler.cpp
  arangod/Agency/State.cpp
  arangod/Agency/Store.cpp
  arangod/Agency/Store.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Agency/v8-agency.cpp
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  tests/Agency/ActiveFailoverTest.cpp
  tests/Agency/AddFollowerTest.cpp
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/CleanUpLostCollectionTest.cpp
  tests/Agency/FailedFollowerTest.cpp
  tests/Agency/FailedLeaderTest.cpp
  tests/Agency/FailedServerTest.cpp
  tests/Agency/MoveShardTest.cpp
  tests/Agency/NodeLoadTest.cpp
  tests/Agency/NodeTest.cpp
  tests/Agency/RemoveFollowerTest.cpp
  tests/Agency/StoreTest.cpp
  tests/Agency/StoreTestAPI.cpp
  tests/Agency/SupervisionTest.cpp
  tests/IResearch/AgencyMock.cpp
  tests/Maintenance/MaintenanceTest.cpp
  tests/js/client/agency/agency-test.js
  tests/js/server/shell/shell-cluster-agency.js
Labels: cla-signed

#19402 [3.11] Do not run LongRunning google tests
  js/client/modules/@arangodb/testsuites/gtest.js
Labels: cla-signed

#19312 Agency Node Refactor
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Agency/AddFollower.cpp
  arangod/Agency/Agent.cpp
  arangod/Agency/CleanOutServer.cpp
  arangod/Agency/FailedFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/FailedServer.cpp
  arangod/Agency/Helpers.cpp
  arangod/Agency/Job.cpp
  arangod/Agency/Job.h
  arangod/Agency/MoveShard.cpp
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Agency/NodeDeserialization.h
  arangod/Agency/NodeLoadInspector.h
  arangod/Agency/ReconfigureReplicatedLog.cpp
  arangod/Agency/RemoveFollower.cpp
  arangod/Agency/ResignLeadership.cpp
  arangod/Agency/ResignLeadership.h
  arangod/Agency/State.cpp
  arangod/Agency/Store.cpp
  arangod/Agency/Store.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/Maintenance.h
  lib/Basics/ResultT.h
  scripts/startStandAloneAgency.sh
  tests/Agency/ActiveFailoverTest.cpp
  tests/Agency/AddFollowerTest.cpp
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/CleanUpLostCollectionTest.cpp
  tests/Agency/FailedFollowerTest.cpp
  tests/Agency/FailedLeaderTest.cpp
  tests/Agency/FailedServerTest.cpp
  tests/Agency/MoveShardTest.cpp
  tests/Agency/NodeLoadTest.cpp
  tests/Agency/NodeTest.cpp
  tests/Agency/RemoveFollowerTest.cpp
  tests/Agency/StoreTest.cpp
  tests/Agency/StoreTestAPI.cpp
  tests/Agency/SupervisionTest.cpp
  tests/Maintenance/MaintenanceTest.cpp
  tests/js/client/agency/agency-test.js
Labels: cla-signed

#19428 Make post recovery callbacks parallel
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
Labels: cla-signed, Backport Needed

#19437 Add `--database.max-databases` (#19417)
  CHANGELOG
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/VocBase/Methods/Databases.cpp
  tests/js/client/server_parameters/max-databases-limit.js
  tests/js/client/server_parameters/max-databases-unlimited.js
Labels: cla-signed

#19441 cppcheck suppressions
  arangod/Agency/Node.cpp
  arangod/Replication2/Storage/RocksDB/AsyncLogWriteBatcher.cpp
  lib/Rest/GeneralRequest.cpp
  lib/Rest/HttpRequest.cpp
  lib/Rest/VstRequest.cpp
Labels: cla-signed

#19381 [APM-662] Improve memory usage / tracking in GraphNodes
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  arangod/Aql/GraphNode.h
  arangod/Auth/User.cpp
  arangod/Auth/User.h
  arangod/Auth/UserManager.cpp
  arangod/Auth/UserManager.h
  arangod/Cluster/TraverserEngine.cpp
  arangod/Cluster/TraverserEngine.h
  arangod/Graph/BaseOptions.cpp
  arangod/Graph/BaseOptions.h
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
  arangod/Graph/Cache/RefactoredTraverserCache.h
  arangod/Graph/Providers/BaseProviderOptions.cpp
  arangod/Graph/Providers/BaseProviderOptions.h
  arangod/Graph/TraverserCache.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/Utils/ExecContext.cpp
  arangod/Utils/ExecContext.h
  arangod/Utils/SingleCollectionTransaction.cpp
  arangod/Utils/SingleCollectionTransaction.h
  arangod/VocBase/vocbase.cpp
  lib/Basics/MemoryTypes/MemoryTypes.h
  tests/Graph/GenericGraphProviderTest.cpp
  tests/Graph/SingleServerProviderTest.cpp
  tests/Graph/TraverserCacheTest.cpp
Labels: 9 Waiting for Jenkins, cla-signed

#19445 QA-433: Bug fix 3.10/missing backport communication
  tests/js/client/communication/test-communication.js
Labels: 3 - Testing, cla-signed

#18851 QA-378: testing: reduce test load on MAC
  tests/test-definitions.txt
Labels: 4 MacOSX, 3 - Testing, cla-signed

#19452 fix compilation with msvc
  arangod/Agency/Node.cpp
Labels: cla-signed

#19439 fix lock code when a lock timeout occurs
  CHANGELOG
  arangod/Aql/OptimizerRulesCluster.cpp
  lib/Basics/ReadWriteLock.cpp
  tests/Basics/ReadWriteLockTest.cpp
  tests/js/server/aql/aql-temp-rocksdb-storage.js
Labels: cla-signed

#19440 fix lock code when a lock timeout occurs
  lib/Basics/ReadWriteLock.cpp
  tests/Basics/ReadWriteLockTest.cpp
  tests/js/server/aql/aql-temp-rocksdb-storage.js
Labels: cla-signed

#19446 avoid recursive locking in agency
  CHANGELOG
  arangod/Agency/State.cpp
Labels: cla-signed

#19430 Recreate Backwards Compatible CreateCollection API
  CHANGELOG
  arangod/Cluster/Utils/PlanCollectionEntryReplication2.cpp
  arangod/Replication2/AgencyCollectionSpecification.h
  arangod/VocBase/Properties/ClusteringMutableProperties.cpp
  arangod/VocBase/Properties/CollectionConstantProperties.cpp
  arangod/VocBase/Properties/CollectionConstantProperties.h
  arangod/VocBase/Properties/CollectionInternalProperties.h
  arangod/VocBase/Properties/CollectionMutableProperties.cpp
  arangod/VocBase/Properties/CollectionMutableProperties.h
  arangod/VocBase/Properties/CreateCollectionBody.cpp
  arangod/VocBase/Properties/CreateCollectionBody.h
  arangod/VocBase/Properties/DatabaseConfiguration.h
  arangod/VocBase/Properties/UserInputCollectionProperties.cpp
  arangod/VocBase/Properties/UserInputCollectionProperties.h
  arangod/VocBase/vocbase.cpp
  lib/Logger/LogTopic.cpp
  lib/Logger/Logger.h
  tests/VocBase/Properties/ClusteringPropertiesTest.cpp
  tests/VocBase/Properties/CollectionConstantPropertiesTest.cpp
  tests/VocBase/Properties/CollectionInternalPropertiesTest.cpp
  tests/VocBase/Properties/CollectionMutablePropertiesTest.cpp
  tests/VocBase/Properties/CreateCollectionBodyTest.cpp
  tests/js/common/shell/shell-collection-api.js
  tests/js/common/shell/shell-keygen.js
  tests/js/common/shell/shell-one-shard.js
  tests/js/server/shell/shell-collection-noncluster.js
  tests/js/server/shell/shell-collection-properties-cluster-spec.js
Labels: cla-signed

#19448 avoid recursive locking in agency
  CHANGELOG
  arangod/Agency/State.cpp
Labels: cla-signed

#19447 avoid recursive locking agency
  CHANGELOG
  arangod/Agency/State.cpp
Labels: cla-signed

#19453 hotbakcup test stabilization
  scripts/toolbox/HotBackupConsistencyTest.py
Labels: cla-signed

#19315 Optimise runtime lock performance
  CHANGELOG
  arangod/Aql/OptimizerRulesCluster.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/Transaction/Manager.h
  lib/Basics/ReadWriteLock.cpp
  lib/Basics/ReadWriteLock.h
  tests/Basics/ReadWriteLockTest.cpp
  tests/js/server/aql/aql-temp-rocksdb-storage.js
Labels: cla-signed

#19444 Backports to 3.11
  CHANGELOG
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/Indexes/Index.h
  arangod/Metrics/ClusterMetricsFeature.cpp
  arangod/Metrics/ClusterMetricsFeature.h
  arangod/Pregel/PregelFeature.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  tests/IResearch/IResearchLinkTest.cpp
  tests/Mocks/IResearchInvertedIndexMock.cpp
  tests/Mocks/IResearchInvertedIndexMock.h
  tests/Mocks/StorageEngineMock.cpp
  tests/js/server/recovery/view-arangosearch-link-populate-truncate-replay-noncluster.js
  tests/js/server/recovery/view-search-alias-populate-truncate-replay-noncluster.js
  tsan_arangodb_suppressions.txt
Labels: cla-signed

#19449 [BTS-1511] Fix AqlValues with 7-byte integers
  CHANGELOG
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  lib/Inspection/include/Inspection/VPackWithErrorT.h
  lib/VelocypackUtils/VelocyPackStringLiteral.cpp
  lib/VelocypackUtils/VelocyPackStringLiteral.h
  tests/Aql/AqlValueMemoryLayoutTest.cpp
  tests/Aql/SortExecutorTest.cpp
Labels: 1 Bug, 3 AQL, 9 Ready to Merge, cla-signed

#19405 [APM-662] Improve memory usage (Expressions, AqlNamePath)
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AttributeAccessor.cpp
  arangod/Aql/AttributeNamePath.cpp
  arangod/Aql/AttributeNamePath.h
  arangod/Aql/DocumentProducingNode.cpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesReplaceFunctions.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/Aql/Projections.cpp
  arangod/Aql/Projections.h
  arangod/Aql/SortRegister.cpp
  arangod/Aql/SortRegister.h
  arangod/Aql/SortingGatherExecutor.cpp
  arangod/Graph/BaseOptions.cpp
  arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
  arangod/Graph/SingleServerEdgeCursor.cpp
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/Indexes/Index.h
  arangod/Pregel/IndexHelpers.cpp
  lib/Basics/MemoryTypes/MemoryTypes.h
  tests/Aql/AttributeNamePathTest.cpp
  tests/Aql/GatherExecutorCommonTest.cpp
  tests/Aql/ProjectionsTest.cpp
  tests/Aql/SortExecutorTest.cpp
  tests/IResearch/IResearchInvertedIndexConditionTest.cpp
  tests/IResearch/IResearchInvertedIndexIteratorTest.cpp
Labels: cla-signed

#19471 Add --database.max-databases
  CHANGELOG
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/VocBase/Methods/Databases.cpp
  tests/js/client/server_parameters/max-databases-limit.js
  tests/js/client/server_parameters/max-databases-unlimited.js
Labels: cla-signed

#19472 optionally allow partitioning of .sst files
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.h
Labels: cla-signed

#19474 [BTS-1526] Prevent purging WAL files during HotBackup
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: cla-signed

#19479 added tests to verify HLC behavior
  lib/Basics/HybridLogicalClock.h
  tests/Basics/HybridLogicalClockTest.cpp
Labels: 9 Ready to Merge, cla-signed

#19480 Fix some unrelated test issues
  arangod/RestHandler/RestReplicationHandler.cpp
  tests/js/client/active-failover/disconnected-leader-nonwindows-nocov-noasan.js
  tests/js/client/shell/shell-in-background-failures-noncluster.js
Labels: 9 Ready to Merge, cla-signed

#19478 improve naming consistency for memory usage metrics
  CHANGELOG
  Documentation/Metrics/arangodb_index_estimates_memory_usage.yaml
  Documentation/Metrics/arangodb_scheduler_queue_memory_usage.yaml
  Documentation/Metrics/arangodb_scheduler_stack_memory_usage.yaml
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  tests/js/client/shell/shell-track-index-selectivity-estimates-noncluster.js
Labels: 9 Ready to Merge, cla-signed

#19465 Improvements for in-memory cache subsystem
  CHANGELOG
  Documentation/Metrics/rocksdb_cache_edge_empty_inserts_total.yaml
  Documentation/Metrics/rocksdb_cache_edge_inserts_effective_entries_size_total.yaml
  Documentation/Metrics/rocksdb_cache_edge_inserts_uncompressed_entries_size_total.yaml
  arangod/Cache/Cache.cpp
  arangod/Cache/Cache.h
  arangod/Cache/CacheOptionsProvider.h
  arangod/Cache/CachedValue.cpp
  arangod/Cache/CachedValue.h
  arangod/Cache/FrequencyBuffer.h
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/Cache/ManagerTasks.cpp
  arangod/Cache/ManagerTasks.h
  arangod/Cache/Metadata.cpp
  arangod/Cache/PlainCache.cpp
  arangod/Cache/PlainCache.h
  arangod/Cache/Table.cpp
  arangod/Cache/Table.h
  arangod/Cache/TransactionalCache.cpp
  arangod/Cache/TransactionalCache.h
  arangod/Graph/TraverserDocumentCache.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.h
  tests/Cache/Manager.cpp
  tests/Cache/PlainCache.cpp
  tests/Cache/Rebalancer.cpp
  tests/Cache/Table.cpp
  tests/Cache/TransactionalCache.cpp
  tests/Cache/TransactionalCacheVPackKeyHasher.cpp
  tests/Cache/TransactionalStore.cpp
  tests/Cache/TransactionsWithBackingStore.cpp
  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-off.js
  tests/js/client/server_parameters/auto-refill-index-caches-on-modify-noncluster-on.js
  tests/js/client/server_parameters/edge-index-compression-off-noncluster.js
  tests/js/client/server_parameters/edge-index-compression-on-noncluster.js
  tests/js/client/shell/shell-auto-refill-index-caches-on-modify-noncluster.js
  tests/sepp/Workloads/EdgeCache.cpp
Labels: 9 Ready to Merge, cla-signed

#19483 Bug-Fix: Write default values of computedValues into Plan
  arangod/VocBase/Methods/Collections.cpp
Labels: cla-signed

#19477 fixed potential deadlock() in cache::Manager::unprepareTask()
  CHANGELOG
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/Cache/ManagerTasks.cpp
  tests/Cache/Rebalancer.cpp
Labels: cla-signed

#19482 fix wrong assertion and return error correctly
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: 9 Ready to Merge, cla-signed

#19475 fixed potential deadlock() in cache::Manager::unprepareTask()
  CHANGELOG
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/Cache/ManagerTasks.cpp
  tests/Cache/Rebalancer.cpp
Labels: cla-signed

#19476 optionally allow partitioning of .sst files
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.h
Labels: 9 Ready to Merge, cla-signed

#19481 fix wrong assertion and return error correctly
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: 9 Ready to Merge, cla-signed

#19457 [3.11] [BTS-1511] Fix AqlValues with 7-byte integers
  CHANGELOG
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  tests/Aql/AqlValueMemoryLayoutTest.cpp
  tests/Aql/SortExecutorTest.cpp
Labels: 1 Bug, 3 AQL, cla-signed

#19459 [3.9] [BTS-1511] Fix AqlValues with 7-byte integers
  CHANGELOG
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  tests/Aql/AqlValueMemoryLayoutTest.cpp
  tests/Aql/SortExecutorTest.cpp
Labels: 1 Bug, 3 AQL, cla-signed

#19454 Backports to 3.10
  CHANGELOG
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchRocksDBInvertedIndex.h
  arangod/IResearch/IResearchRocksDBLink.h
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/Indexes/Index.h
  arangod/Metrics/ClusterMetricsFeature.cpp
  arangod/Metrics/ClusterMetricsFeature.h
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/DatabaseFeature.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.h
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndex.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  tests/IResearch/IResearchLinkTest.cpp
  tests/Mocks/IResearchInvertedIndexMock.cpp
  tests/Mocks/IResearchInvertedIndexMock.h
  tests/Mocks/StorageEngineMock.cpp
  tests/js/server/recovery/view-arangosearch-link-populate-truncate-replay-noncluster.js
  tests/js/server/recovery/view-search-alias-populate-truncate-replay-noncluster.js
  tsan_arangodb_suppressions.txt
Labels: 3 ArangoSearch, cla-signed

#19426 3.11 Test-Only - Added a more sophisticated test for createCollection API
  arangod/RestHandler/RestCollectionHandler.cpp
  tests/js/common/shell/shell-collection-api.js
  tests/js/common/shell/shell-figures-rocksdb.js
Labels: cla-signed

#19458 [3.10] [BTS-1511] Fix AqlValues with 7-byte integers
  CHANGELOG
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  tests/Aql/AqlValueMemoryLayoutTest.cpp
  tests/Aql/SortExecutorTest.cpp
Labels: 1 Bug, 3 AQL, cla-signed

#19486 [3.10] Fix potential logical race condition
  arangod/RocksDBEngine/RocksDBCollection.cpp
Labels: cla-signed

#19024 [3.11] [GORDO-1643] Create Pregel Status Collection entry on creation
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
Labels: 3 Pregel, cla-signed

#19484 Suppress some cppcheck issue 3.10
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchFeature.h
  arangod/IResearch/IResearchInvertedIndex.cpp
Labels: cla-signed

#19456 Feature/cinfra 809 collection groups rest replication handler
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/VocBase/Properties/ClusteringMutableProperties.cpp
  arangod/VocBase/Properties/ClusteringMutableProperties.h
  arangod/VocBase/Properties/CreateCollectionBody.cpp
  arangod/VocBase/Properties/CreateCollectionBody.h
  tests/VocBase/Properties/ClusteringPropertiesTest.cpp
  tests/js/client/shell/api/api-replication.js
  tests/js/common/shell/shell-collection-api.js
Labels: cla-signed

#19493 try to improve flaky test
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  tests/js/client/active-failover/disconnected-leader-nonwindows-nocov-noasan.js
  tests/js/client/shell/shell-collection-counts-cluster.js
Labels: cla-signed

#19498 Fix HotBackupConsistencyTest.py
  scripts/toolbox/HotBackupConsistencyTest.py
Labels: cla-signed
