Repository arangodb/arangodb, pull requests merged in 2023-10, with the labels that each got.

#19885 add code documentation for IndexIterator
  arangod/Indexes/IndexIterator.h
Labels: cla-signed

#19874 better reporting for hotbackup errors
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
Labels: 3 ImportExport, cla-signed

#19873 better reporting for hotbackup errors
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
Labels: 3 ImportExport, cla-signed

#19883 MaterializeRocksDBExecutor is passthrough
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
  tests/js/server/aql/aql-optimizer-rule-late-document-materialization.js
  tests/js/server/aql/aql-profiler-noncluster.js
Labels: cla-signed

#19854 fix potential recursive lock invocation
  arangod/Cache/Manager.cpp
  tests/Cache/Manager.cpp
Labels: cla-signed

#19889 Optimize projections
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
Labels: cla-signed

#19891 fix assertion failure
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: cla-signed

#19858 bug-fix-3.11/FE-323: allow 'nested' property in view JSON UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/views/constants.ts
Labels: 1 Bug, 3 UI, cla-signed

#19856 bug-fix-3.10/FE-317: add graph name validation
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arangoValidationHelper.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/graphManagementView.js
  js/apps/system/_admin/aardvark/APP/react/src/App.js
Labels: 1 Bug, 3 UI, cla-signed

#19859 bug-fix-3.10/FE-323: allow 'nested' property in view JSON UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/views/constants.ts
Labels: 1 Bug, 3 UI, cla-signed

#19894 avoid duplicate creation of edge AqlValues
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
Labels: cla-signed

#19895 Projections for JoinNode
  arangod/Aql/IndexJoin/GenericMerge.h
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/JoinExecutor.h
  arangod/Aql/JoinNode.cpp
  arangod/Aql/JoinNode.h
  arangod/Aql/OptimizerRules.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/server/aql/aql-index-join-noncluster.js
Labels: cla-signed

#19896 avoid duplicate creation of edge AqlValues
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
Labels: cla-signed

#19884 [CINFRA-843] Fix flaky test
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#19901 Fix warning about unused ftruncate result
  arangod/Replication2/Storage/WAL/FileWriterImpl.cpp
Labels: cla-signed

#19897 Fix updating of collection properties when there are views
  CHANGELOG
  arangod/ClusterEngine/ClusterCollection.cpp
  tests/js/common/shell/shell-index.js
Labels: cla-signed

#19899 Fix updating of collection properties when there are views
  CHANGELOG
  arangod/ClusterEngine/ClusterCollection.cpp
  tests/js/common/shell/shell-index.js
Labels: cla-signed

#19900 Fix updating of collection properties when there are views
  CHANGELOG
  arangod/ClusterEngine/ClusterCollection.cpp
  tests/js/common/shell/shell-index.js
Labels: cla-signed

#19903 Add document projections for join nodes.
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/JoinNode.cpp
  tests/js/server/aql/aql-index-join-noncluster.js
Labels: cla-signed

#19909 [CINFRA-851] Fixing DropIndex test
  js/common/modules/@arangodb/testutils/document-state-helper.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#19915 Enable Join Rule
  arangod/Aql/OptimizerRulesFeature.cpp
  tests/js/server/aql/aql-optimizer-stats-noncluster.js
Labels: cla-signed

#19912 [BTS-1634] Fix has nested for links
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchLinkMeta.cpp
Labels: 3 ArangoSearch, cla-signed, Backport Needed

#19916 Join Node polish
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/JoinNode.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/server/aql/aql-index-join-noncluster.js
Labels: cla-signed

#19917 Build without V8 on CircleCI
  .circleci/base_config.yml
  CMakePresets.json
Labels: cla-signed

#19919 fix compile error with -DUSE_V8=Off
  .circleci/base_config.yml
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/RestHandler/RestAqlUserFunctionsHandler.cpp
  arangod/RestHandler/RestAqlUserFunctionsHandler.h
  arangod/arangoserver.cmake
Labels: cla-signed

#19913 distribute memory in a way that all tests work
  js/client/modules/@arangodb/testutils/instance-manager.js
Labels: 3 - Testing, cla-signed

#19922 Fix incorrect ifdef that unnecessary disabled rocksdb feature
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: cla-signed

#19925 remove obsolete files from repository
  arangod/Graph/KShortestPathsFinder.cpp
  arangod/Graph/KShortestPathsFinder.h
  arangod/Graph/ShortestPathFinder.cpp
  arangod/Graph/ShortestPathFinder.h
  arangod/Graph/ShortestPathResult.cpp
  arangod/Graph/ShortestPathResult.h
Labels: cla-signed

#19911 smaller AQL cleanups
  arangod/Aql/AqlCall.cpp
  arangod/Aql/AqlCall.h
  arangod/Aql/AqlCallList.cpp
  arangod/Aql/AqlCallList.h
  arangod/Aql/AsyncExecutor.cpp
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/EngineInfoContainerCoordinator.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryCursor.cpp
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/RemoteExecutor.h
  arangod/Aql/RestAqlHandler.cpp
  arangod/IResearch/IResearchAqlAnalyzer.cpp
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/VocBase/LogicalCollection.cpp
  tests/Aql/AsyncExecutorTest.cpp
  tests/Aql/ExecutorTestHelper.h
  tests/Aql/IndexNodeTest.cpp
  tests/Aql/QueryLimitsTest.cpp
  tests/Aql/SortLimitTest.cpp
  tests/IResearch/common.cpp
  tests/Transaction/ManagerTest.cpp
Labels: cla-signed

#19930 small improvement for cluster-internal error handling
  arangod/Cluster/ClusterMethods.cpp
Labels: cla-signed

#19934 improve client-side cursor API
  js/client/modules/@arangodb/arango-query-cursor.js
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/client/shell/api/cursor.js
  tests/js/client/shell/shell-statement.js
Labels: cla-signed

#19937 replace several calls to deprecated APIs
  arangod/Aql/Functions.cpp
  arangod/Aql/SkipResult.cpp
  arangod/Graph/GraphManager.cpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/VelocyPackHelper.cpp
  arangod/RestHandler/RestImportHandler.cpp
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
Labels: cla-signed

#19938 Allow usage of `_id` attribute in stored values of persistent indexes
  CHANGELOG
  arangod/Aql/Projections.cpp
  arangod/ClusterEngine/ClusterIndexFactory.cpp
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  arangod/Indexes/IndexFactory.cpp
  arangod/Indexes/IndexFactory.h
  arangod/RocksDBEngine/RocksDBIndexFactory.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/common/shell/shell-index-stored-values.js
Labels: cla-signed

#19918 Improve reading document from collection
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IResearchViewExecutor.tpp
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MultiGet.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Cluster/TraverserEngine.cpp
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
  arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
  arangod/Graph/SingleServerEdgeCursor.cpp
  arangod/Graph/TraverserCache.cpp
  arangod/Indexes/IndexIterator.h
  arangod/Pregel/GraphStore/GraphLoader.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/RocksDBEngine/RocksDBIterators.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/Transaction/Methods.cpp
  arangod/V8Server/v8-query.cpp
  arangod/VocBase/Methods/Collections.cpp
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
  tests/Graph/TraverserCacheTest.cpp
  tests/Mocks/PhysicalCollectionMock.cpp
  tests/VocBase/ComputedValuesTest.cpp
Labels: cla-signed

#19920 [BTS-1634] backport to 3.10
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchLinkMeta.cpp
Labels: cla-signed

#19923 distribute memory in a way that all tests work (#19913)
  js/client/modules/@arangodb/testutils/instance-manager.js
Labels: cla-signed

#19921 [BTS-1634] backport to 3.11
  arangod/IResearch/IResearchInvertedIndexMeta.h
  arangod/IResearch/IResearchLinkMeta.cpp
Labels: 3 ArangoSearch, cla-signed

#19929 Fix ineffective startup option
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: cla-signed

#19936 Post Filter for JoinNode
  arangod/Aql/IndexJoin/GenericMerge.h
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/JoinExecutor.h
  arangod/Aql/JoinNode.cpp
  arangod/Aql/JoinNode.h
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/Projections.cpp
  arangod/Aql/Projections.h
  arangod/RocksDBEngine/RocksDBKey.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  js/common/modules/@arangodb/aql/explainer.js
  tests/Aql/JoinStrategy/GenericJoinTest.cpp
  tests/js/server/aql/aql-index-join.js
Labels: cla-signed

#19865 BTS-1622: Feature 3.11/ distribute memory
  js/client/modules/@arangodb/testsuites/endpoints.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/testing.js
Labels: 3 - Testing, cla-signed

#19939 forward V8 flag into client package
  cmake/packages/client/nsis.txt
  cmake/packages/nsis.cmake
Labels: 4 Windows, 3 Packaging, cla-signed

#19932 always return `warnings` attribute for `/_api/query`
  arangod/RestHandler/RestQueryHandler.cpp
Labels: cla-signed

#19881 add cluster-internal connectivity checks
  CHANGELOG
  Documentation/Metrics/arangodb_network_connectivity_failures_coordinators_total.yaml
  Documentation/Metrics/arangodb_network_connectivity_failures_dbservers_total.yaml
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
Labels: cla-signed

#19882 add cluster-internal connectivity checks
  CHANGELOG
  Documentation/Metrics/arangodb_network_connectivity_failures_coordinators_total.yaml
  Documentation/Metrics/arangodb_network_connectivity_failures_dbservers_total.yaml
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
Labels: cla-signed

#19948 fix a crash in supervision
  arangod/Agency/Supervision.cpp
Labels: cla-signed

#19946 JoinNode check index supports stream
  arangod/Aql/IndexStreamIterator.h
  arangod/Aql/JoinNode.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndex.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  tests/js/server/aql/aql-index-join.js
Labels: cla-signed

#19951 make exception macros more versatile
  lib/Basics/Exceptions.h
Labels: cla-signed

#19949 Just for check
  arangod/Aql/MaterializeExecutor.cpp
Labels: cla-signed

#19956 Introduce variables for each projection.
  arangod/Aql/Ast.cpp
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/JoinExecutor.h
  arangod/Aql/JoinNode.cpp
  tests/js/server/aql/aql-index-join.js
Labels: cla-signed

#19792 FE-307: Move services screen to new UI
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/applicationsView.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.50fa5a4c.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.50fa5a4c.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.50fa5a4c.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.fac818cd.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.fac818cd.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.fac818cd.js.gz
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/src/App.js
  js/apps/system/_admin/aardvark/APP/react/src/components/select/SelectBase.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/services/Service.types.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/services/ServicesContext.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/services/ServicesReactView.jsx
  js/apps/system/_admin/aardvark/APP/react/src/views/services/ServicesView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/services/ServicesViewWrap.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/services/listServices/ServicesTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/services/useFetchServices.ts
  js/apps/system/_admin/aardvark/APP/react/yarn.lock
Labels: cla-signed

#19952 Remove int48
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  arangod/Aql/Expression.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/OutputAqlItemRow.cpp
  tests/Aql/AqlValueMemoryLayoutTest.cpp
Labels: cla-signed

#19959 remove some dead code
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Aql/Ast.cpp
  arangod/Aql/RegisterPlan.cpp
  arangod/RestServer/WindowsServiceFeature.cpp
  arangod/RocksDBEngine/RocksDBCuckooIndexEstimator.cpp
Labels: cla-signed

#19968 Some cleanups in graph code
  arangod/Aql/ShortestPathExecutor.h
  arangod/Aql/ShortestPathExecutor.tpp
  arangod/Graph/Enumerators/OneSidedEnumeratorInterface.cpp
  arangod/Graph/Providers/ClusterProvider.cpp
  arangod/Graph/Providers/ClusterProvider.h
  arangod/Graph/Providers/ProviderTracer.cpp
  arangod/Graph/Providers/ProviderTracer.h
  arangod/Graph/Providers/SingleServerProvider.cpp
  arangod/Graph/Providers/SingleServerProvider.h
  arangod/Graph/ShortestPathOptions.cpp
  arangod/Graph/ShortestPathOptions.h
  arangod/Graph/algorithm-aliases.h
Labels: cla-signed

#19704 Remove GitHub action for clang-format
  .github/workflows/clang-format.yml
Labels: cla-signed

#19955 [Feature] merge join unique
  arangod/Aql/IndexJoin/TwoIndicesUniqueMergeJoin.h
  arangod/Aql/IndexJoinStrategy.cpp
  arangod/Aql/IndexJoinStrategy.h
  arangod/Aql/JoinExecutor.cpp
  tests/Aql/JoinStrategy/GenericJoinTest.cpp
  tests/Aql/JoinStrategy/TwoIndicesUniqueJoinTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-index-join-unique.js
  tests/js/server/aql/aql-index-join.js
Labels: cla-signed

#19778 [BTS-1610] Fix shadowrow forwarding
  CHANGELOG
  arangod/Aql/AqlCallStack.cpp
  arangod/Aql/AqlCallStack.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/ShadowAqlItemRow.cpp
  arangod/Aql/SubqueryStartExecutionNode.cpp
  tests/Aql/AqlItemBlockHelper.h
  tests/Aql/CalculationExecutorTest.cpp
  tests/Aql/CountCollectExecutorTest.cpp
  tests/Aql/DistinctCollectExecutorTest.cpp
  tests/Aql/EnumerateCollectionExecutorTest.cpp
  tests/Aql/EnumerateListExecutorTest.cpp
  tests/Aql/ExecutorTestHelper.h
  tests/Aql/FilterExecutorTest.cpp
  tests/Aql/HashedCollectExecutorTest.cpp
  tests/Aql/NoResultsExecutorTest.cpp
  tests/Aql/ReturnExecutorTest.cpp
  tests/Aql/ShadowRowForwardingTest.cpp
  tests/Aql/SortExecutorTest.cpp
  tests/Aql/SortedCollectExecutorTest.cpp
  tests/Aql/SplicedSubqueryIntegrationTest.cpp
  tests/Aql/SubqueryStartExecutorTest.cpp
  tests/Aql/WindowExecutorTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-subquery-splicing-regression-2.js
Labels: 1 Bug, 3 AQL, 9 WIP, DO_NOT_MERGE, cla-signed

#19961 try to stabilize flaky queue-time-header test
  tests/js/client/server_parameters/test-return-queue-time-header-on.js
Labels: cla-signed

#19973 Refresh timezone database as of 16.10.2023 (3.10)
  3rdParty/tzdata/windowsZones.xml
Labels: cla-signed

#19972 Refresh timezone database as of 16.10.2023 (3.11)
  3rdParty/tzdata/windowsZones.xml
Labels: cla-signed

#19678 [FE-288] Implement new UI for collection indexes
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/router.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.508f425f.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.508f425f.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.508f425f.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.e308889b.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.e308889b.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.e308889b.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/global.d.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/figures/useFetchCollectionFigures.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesContext.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesHelpers.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesReactView.jsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesTab.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesTabWrap.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesViewWrap.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/DeleteIndexButton.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/DeleteIndexModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/IndexActionCell.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/ViewIndexButton.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/AddIndexForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexAnalyzerDropdown.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/listIndices/CollectionIndexActionButtons.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/listIndices/CollectionIndicesTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/useDeleteIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/useFetchCollectionIndices.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/useFetchIndices.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/useSupportedIndexTypes.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/useSyncIndexCreationJob.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/viewIndex/CollectionIndexDetails.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/viewIndex/IndexStats.tsx
Labels: 3 UI, cla-signed

#19975 3.10: [BTS-1610] Fix shadowrow forwarding
  CHANGELOG
  arangod/Aql/AqlCallStack.cpp
  arangod/Aql/AqlCallStack.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/ShadowAqlItemRow.cpp
  arangod/Aql/SubqueryStartExecutionNode.cpp
  tests/Aql/AqlItemBlockHelper.h
  tests/Aql/CalculationExecutorTest.cpp
  tests/Aql/CountCollectExecutorTest.cpp
  tests/Aql/DistinctCollectExecutorTest.cpp
  tests/Aql/EnumerateCollectionExecutorTest.cpp
  tests/Aql/EnumerateListExecutorTest.cpp
  tests/Aql/ExecutorTestHelper.h
  tests/Aql/FilterExecutorTest.cpp
  tests/Aql/HashedCollectExecutorTest.cpp
  tests/Aql/NoResultsExecutorTest.cpp
  tests/Aql/ReturnExecutorTest.cpp
  tests/Aql/ShadowRowForwardingTest.cpp
  tests/Aql/SortExecutorTest.cpp
  tests/Aql/SortedCollectExecutorTest.cpp
  tests/Aql/SplicedSubqueryIntegrationTest.cpp
  tests/Aql/SubqueryStartExecutorTest.cpp
  tests/Aql/WindowExecutorTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-subquery-splicing-regression-2.js
Labels: cla-signed

#19963 Reduce number of shared_ptr copies in cache subsystem
  CHANGELOG
  arangod/Cache/Cache.cpp
  arangod/Cache/Cache.h
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/Cache/ManagerTasks.cpp
  arangod/Cache/PlainCache.cpp
  arangod/Cache/PlainCache.h
  arangod/Cache/Table.cpp
  arangod/Cache/TransactionManager.cpp
  arangod/Cache/TransactionManager.h
  arangod/Cache/TransactionalCache.cpp
  arangod/Cache/TransactionalCache.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  tests/Cache/TransactionManager.cpp
Labels: cla-signed

#19971 Refresh timezone database as of 16.10.2023
  3rdParty/tzdata/windowsZones.xml
Labels: cla-signed

#19979 Disabling replication2 tests
  tests/js/client/shell/transaction/DISABLED_shell-transaction-part1-R2.js
  tests/js/client/shell/transaction/DISABLED_shell-transaction-part2-R2.js
  tests/js/client/shell/transaction/replication2_recovery/DISABLED_shell-transaction-replication2-recovery.js
  tests/js/server/resilience/move/DISABLED_moving-shards-cluster-data-R2.js
Labels: cinfra, cla-signed

#19957 Optimize Projections
  arangod/Aql/DocumentExpressionContext.cpp
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/DocumentProducingNode.cpp
  arangod/Aql/DocumentProducingNode.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/LateMaterializedExpressionContext.cpp
  arangod/Aql/LateMaterializedExpressionContext.h
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/Projections.cpp
  arangod/Aql/Projections.h
  arangod/Indexes/IndexIterator.cpp
  arangod/Indexes/IndexIterator.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/server/aql/aql-filter-projections.js
  tests/js/server/aql/aql-index-hints.js
  tests/js/server/aql/aql-index-join.js
  tests/js/server/aql/aql-optimizer-index-only.js
  tests/js/server/aql/aql-optimizer-rule-distribute-in-cluster.js
  tests/js/server/aql/aql-optimizer-rule-remove-filter-covered-by-index.js
  tests/js/server/aql/aql-primary-index-noncluster.js
  tests/js/server/aql/aql-projections.js
Labels: cla-signed

#19935 add potentially missing response headers
  arangod/RestHandler/RestBaseHandler.cpp
Labels: cla-signed

#19977 Reduce number of shared_ptr copies in cache subsystem
  CHANGELOG
  arangod/Cache/Cache.cpp
  arangod/Cache/Cache.h
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/Cache/ManagerTasks.cpp
  arangod/Cache/PlainCache.cpp
  arangod/Cache/PlainCache.h
  arangod/Cache/Table.cpp
  arangod/Cache/TransactionManager.cpp
  arangod/Cache/TransactionManager.h
  arangod/Cache/TransactionalCache.cpp
  arangod/Cache/TransactionalCache.h
  tests/Cache/Rebalancer.cpp
  tests/Cache/TransactionManager.cpp
Labels: cla-signed

#19967 simplify metrics creation code
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Metrics/Batch.h
  arangod/Metrics/Counter.cpp
  arangod/Metrics/Gauge.h
  arangod/Metrics/Metric.cpp
  arangod/Metrics/MetricsFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/Statistics/StatisticsFeature.cpp
  arangod/Statistics/StatisticsFeature.h
  arangod/StorageEngine/StorageEngine.cpp
  arangod/StorageEngine/StorageEngine.h
Labels: cla-signed

#19942 FE-378: fix fields containing spaces during index creation
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.488a1ac3.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.488a1ac3.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.488a1ac3.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.508f425f.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.508f425f.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.508f425f.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreateFulltextIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreateGeoIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreatePersistentIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreateTTLIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreateZKDIndex.ts
Labels: 1 Bug, 3 UI, cla-signed

#19978 FE-385: fix web UI query import stuck on loading for faulty JSON
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.488a1ac3.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.488a1ac3.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.488a1ac3.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.e0393e9c.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.e0393e9c.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.e0393e9c.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/query/QueryContextProvider.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/editor/ImportQueryModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/editor/useQueryImport.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/useSavedQueriesHandlers.tsx
Labels: 1 Bug, 3 UI, cla-signed

#19987 fix failing test
  js/client/modules/@arangodb/testutils/aql-profiler-test-helper.js
  js/common/modules/@arangodb/graph/helpers.js
  tests/js/client/aql/aql-index-hints.js
  tests/js/client/aql/aql-optimizer-primary-index-ranges.js
  tests/js/client/aql/aql-projections.js
Labels: 3 - Testing, cla-signed

#19992 projections fix in unique merge join
  arangod/Aql/IndexJoin/TwoIndicesUniqueMergeJoin.h
  arangod/Aql/IndexJoinStrategy.cpp
Labels: cla-signed

#19993 do not restrict AQL cursor garbage collection too much
  arangod/Utils/CursorRepository.h
Labels: cla-signed

#19995 do not restrict AQL cursor garbage collection too much
  CHANGELOG
  arangod/Utils/CursorRepository.cpp
Labels: cla-signed

#19999 Update OpenSSL to 3.0.11 (3.11)
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#20000 Update OpenSSL to 3.0.11
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#19998 Update OpenSSL to 3.1.3
  .circleci/base_config.yml
  CHANGELOG
  VERSIONS
  scripts/docker/build/arangodb-build.Dockerfile
Labels: OpenSSL, cla-signed

#19988 More tests for JoinNode
  arangod/Aql/IndexJoin/TwoIndicesUniqueMergeJoin.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/JoinNode.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/client/aql/aql-index-join-multi.js
Labels: cla-signed

#19997 remove unreachable test code
  tests/js/client/aql/aql-arangosearch-inverted-index-optimization.js
Labels: cla-signed

#20001 Bug fix/fix review comments3
  js/client/modules/@arangodb/aql-helper.js
  js/client/modules/@arangodb/arango-database.js
  js/client/modules/@arangodb/test-helper.js
  js/server/modules/@arangodb/aql-helper.js
  tests/js/client/aql/aql-array-access.js
  tests/js/client/aql/aql-dynamic-attributes.js
  tests/js/client/aql/aql-fullcount.js
  tests/js/client/aql/aql-graph-traverser-brokenGraph.js
  tests/js/client/aql/aql-graph-traverser-complexFiltering.js
  tests/js/client/aql/aql-graph-traverser-complexInterna.js
  tests/js/client/aql/aql-graph-traverser-edgeConnectedFromVertexToEdge.js
  tests/js/client/aql/aql-graph-traverser-exampleGraphs.js
  tests/js/client/aql/aql-graph-traverser-invalidStartVertex.js
  tests/js/client/aql/aql-graph-traverser-limit.js
  tests/js/client/aql/aql-graph-traverser-multiCollectionGraph.js
  tests/js/client/aql/aql-graph-traverser-multiEdgeCollectionGraph.js
  tests/js/client/aql/aql-graph-traverser-multiEdgeDirection.js
  tests/js/client/aql/aql-graph-traverser-namedGraph.js
  tests/js/client/aql/aql-graph-traverser-nested.js
  tests/js/client/aql/aql-graph-traverser-optimizeIn.js
  tests/js/client/aql/aql-graph-traverser-optimizeNonVertexCentricIndexes-noncluster.js
  tests/js/client/aql/aql-graph-traverser-optimizeQuantifier.js
  tests/js/client/aql/aql-graph-traverser-options.js
  tests/js/client/aql/aql-graph-traverser-potentialErrors.js
  tests/js/client/aql/aql-graph-traverser-pruneTraversal.js
  tests/js/client/aql/aql-graph-traverser-simpleInboundOutbound.js
  tests/js/client/aql/aql-graph-traverser-subQuery.js
  tests/js/client/aql/aql-graph-traverser-unusedVariable.js
  tests/js/client/aql/aql-multiple-snippets-javascript-cluster.js
  tests/js/client/aql/aql-optimizer-dynamic-bounds.js
  tests/js/client/aql/aql-optimizer-edge-index.js
  tests/js/client/aql/aql-optimizer-indexes-sort.js
  tests/js/client/aql/aql-optimizer-rule-interchange-adjacent-enumerations-cluster.js
  tests/js/client/aql/aql-optimizer-rule-interchange-adjacent-enumerations-noncluster.js
  tests/js/client/aql/aql-optimizer-rule-optimize-traversals-spec.js
  tests/js/client/aql/aql-optimizer-rule-remove-unnecessary-remote-scatter-cluster.js
  tests/js/client/aql/aql-parse.js
  tests/js/client/aql/aql-query-cache-noncluster.js
Labels: 3 - Testing, cla-signed

#20006 Remove ManagedDoc and resolveExternals
  arangod/Aql/Aggregator.cpp
  arangod/Aql/AqlFunctionsInternalCache.cpp
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  arangod/Aql/AqlValueMaterializer.cpp
  arangod/Aql/AqlValueMaterializer.h
  arangod/Aql/Ast.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/FixedVarExpressionContext.cpp
  arangod/Aql/Functions.cpp
  arangod/Aql/HashedCollectExecutor.cpp
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/QueryCursor.cpp
  arangod/Aql/SortedCollectExecutor.cpp
  arangod/Aql/SubqueryEndExecutor.cpp
  arangod/Aql/Variable.cpp
  arangod/Graph/BaseOptions.cpp
  arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
  arangod/IResearch/AqlHelper.h
  arangod/IResearch/IResearchFeature.cpp
  arangod/VocBase/ComputedValues.cpp
  tests/Aql/AqlValueMemoryLayoutTest.cpp
Labels: cla-signed

#20004 Adjust callstack limit in test
  tests/js/server/aql/aql-complex-queries-callstack-noinstr.js
Labels: 3 - Testing, cla-signed

#20002 Increase the CircelCI no_output_timeout
  .circleci/base_config.yml
Labels: cla-signed

#19969 Add CircleCI windows build on local runner
  .circleci/base_config.yml
  .circleci/generate_config.py
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/ClusterIndexMethods.cpp
  lib/Basics/win-utils.cpp
  scripts/docker/build/linux/arangodb-build.Dockerfile
  scripts/docker/build/linux/build-image_arm64.sh
  scripts/docker/build/linux/build-image_x86-64.sh
  scripts/docker/build/linux/build-manifest.sh
  scripts/docker/build/linux/install-cppcheck.sh
  scripts/docker/build/linux/install-openldap.sh
  scripts/docker/build/linux/install-openssl.sh
  scripts/docker/build/windows/arangodb-build-win.Dockerfile
  scripts/docker/build/windows/build-image.bat
  scripts/docker/build/windows/install-openssl.ps1
Labels: cla-signed

#20005 Disable one more replication2 test
  tests/js/client/shell/transaction/shell-transaction-cluster.js
Labels: cinfra, cla-signed

#20007 do not ignore `--javascript.*` startup options
  lib/ProgramOptions/ProgramOptions.cpp
Labels: cla-signed

#19994 do not restrict AQL cursor garbage collection too much
  CHANGELOG
  arangod/Utils/CursorRepository.cpp
Labels: cla-signed

#20009 remove `_clusterId` member
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
Labels: cla-signed

#20008 retry requests in active_failover test
  tests/js/client/active-failover/basic.js
Labels: cla-signed

#19983 improve error messages
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Transaction/Manager.cpp
Labels: cla-signed

#19974 3.11: [BTS-1610] Fix shadowrow forwarding
  CHANGELOG
  arangod/Aql/AqlCallStack.cpp
  arangod/Aql/AqlCallStack.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/ShadowAqlItemRow.cpp
  arangod/Aql/SubqueryStartExecutionNode.cpp
  tests/Aql/AqlItemBlockHelper.h
  tests/Aql/CalculationExecutorTest.cpp
  tests/Aql/CountCollectExecutorTest.cpp
  tests/Aql/DistinctCollectExecutorTest.cpp
  tests/Aql/EnumerateCollectionExecutorTest.cpp
  tests/Aql/EnumerateListExecutorTest.cpp
  tests/Aql/ExecutorTestHelper.h
  tests/Aql/FilterExecutorTest.cpp
  tests/Aql/HashedCollectExecutorTest.cpp
  tests/Aql/NoResultsExecutorTest.cpp
  tests/Aql/ReturnExecutorTest.cpp
  tests/Aql/ShadowRowForwardingTest.cpp
  tests/Aql/SortExecutorTest.cpp
  tests/Aql/SortedCollectExecutorTest.cpp
  tests/Aql/SplicedSubqueryIntegrationTest.cpp
  tests/Aql/SubqueryStartExecutorTest.cpp
  tests/Aql/WindowExecutorTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-subquery-splicing-regression-2.js
Labels: 9 Ready to Merge, cla-signed

#19781 parallel execution for AQL
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/ClusterNodes.h
  arangod/Aql/CollectNode.cpp
  arangod/Aql/CollectNode.h
  arangod/Aql/DocumentProducingNode.cpp
  arangod/Aql/DocumentProducingNode.h
  arangod/Aql/EngineInfoContainerCoordinator.cpp
  arangod/Aql/EngineInfoContainerCoordinator.h
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/ExecutionNodeStats.h
  arangod/Aql/ExecutionPlan.h
  arangod/Aql/ExecutionStats.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  arangod/Aql/JoinNode.cpp
  arangod/Aql/JoinNode.h
  arangod/Aql/ModificationNodes.cpp
  arangod/Aql/ModificationNodes.h
  arangod/Aql/Optimizer.cpp
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/RemoteExecutor.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Aql/RestAqlHandler.h
  arangod/Aql/ScatterExecutor.cpp
  arangod/Aql/SharedQueryState.cpp
  arangod/Aql/SharedQueryState.h
  arangod/Aql/SortNode.cpp
  arangod/Aql/SortNode.h
  arangod/Aql/Timing.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/Transaction/ManagerTest.cpp
  tests/js/client/aql/aql-explain-all.js
  tests/js/client/aql/aql-optimizer-rule-async-prefetch-cluster.js
  tests/js/client/aql/aql-optimizer-rule-async-prefetch-noncluster.js
  tests/js/client/aql/aql-optimizer-rule-optimize-cluster-single-document-operations.js
  tests/js/client/aql/aql-optimizer-rule-remove-filter-covered-by-index.js
  tests/js/common/shell/multi/shell-statement.js
  tests/js/common/shell/shell-statement-noncluster.js
Labels: cla-signed

#20003 [Join] SkipRowsRange
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/OptimizerRules.cpp
  js/common/modules/@arangodb/aql/joinHelper.js
  tests/js/client/aql/aql-index-join-multi-unique-false-sort-false.js
  tests/js/client/aql/aql-index-join-multi-unique-false-sort-true.js
  tests/js/client/aql/aql-index-join-multi-unique-true-sort-false.js
  tests/js/client/aql/aql-index-join-multi-unique-true-sort-true.js
  tests/js/client/aql/aql-index-join-multi.js
  tests/js/client/aql/aql-index-join.js
Labels: cla-signed

#19953 bug-fix-3.11/FE-374: Query UI - fix switching from table to JSON
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/queryView.js
Labels: 1 Bug, 3 UI, cla-signed

#19982 Improve a few error messages
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Transaction/Manager.cpp
Labels: cla-signed

#20014 fix query performance regression
  arangod/Aql/IndexExecutor.cpp
Labels: cla-signed

#20013 fix `server_parameters` dump test
  tests/js/client/server_parameters/dump-limits-noncluster-nonwindows.js
Labels: cla-signed

#20011 Added cursors metric
  CHANGELOG
  Documentation/Metrics/arangodb_aql_cursors_active.yaml
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
  arangod/Utils/Cursor.h
  arangod/Utils/CursorRepository.cpp
  arangod/Utils/CursorRepository.h
  arangod/VocBase/vocbase.cpp
  tests/js/client/shell/shell-aql-cursors-metric.js
Labels: cla-signed

#19618 Backport of scheduler bugfixes
  CHANGELOG
  arangod/Network/Methods.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
  arangod/Pregel/PregelFeature.h
  arangod/Scheduler/Scheduler.cpp
  arangod/Scheduler/Scheduler.h
  tests/Network/MethodsTest.cpp
Labels: cla-signed

#19797 [BTS-1259][DEVEL] Gharial CRUD Vertex / Edge operations now always do check the GraphDefinition
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  tests/js/client/shell/api/api-gharial-spec.js
  tests/js/client/shell/api/multi/general-graph.js
Labels: cla-signed

#19986 [EF-2] Feature/aql merge join primary index
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.h
  tests/js/client/aql/aql-index-join.js
  tests/js/client/aql/aql-optimizer-rule-reduce-extraction-to-projection.js
  tests/js/client/aql/aql-primary-index-join.js
  tests/js/client/aql/aql-read-own-writes.js
Labels: cla-signed

#20019 Rename CircleCI Windows job
  .circleci/base_config.yml
Labels: cla-signed

#20016 do not fail when trying to increase file descriptors limit
  lib/Basics/FileDescriptors.cpp
Labels: cla-signed

#20015 remove outdated files from repository
  Documentation/Scripts/html2html.sh
  Documentation/StyleGuide/.gitignore
  Documentation/StyleGuide/StyleGuide.pdf
  Documentation/StyleGuide/StyleGuide.tex
  Documentation/arango.doxygen
  Documentation/arangodb.css
Labels: cla-signed

#20020 [BTS-1599] Adding write-concern parameter to arangorestore.
  CHANGELOG
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Restore/RestoreFeature.h
  tests/js/client/shell/shell-restore-integration.js
Labels: cla-signed

#20028 Agency Nodes Free list Fix
  arangod/Agency/Node.h
Labels: cla-signed

#20021 [BTS-1602] Add --ignore-collection flag to arangodump
  CHANGELOG
  client-tools/Dump/DumpFeature.cpp
  client-tools/Dump/DumpFeature.h
  tests/js/client/shell/shell-dump-integration.js
Labels: 1 Feature, 3 ImportExport, cla-signed

#20027 Add company to the Window binaries
  .circleci/base_config.yml
  CHANGELOG
  CMakeLists.txt
  arangod/CMakeLists.txt
  client-tools/CMakeLists.txt
Labels: cla-signed

#20022 enable parallel dump by default
  CHANGELOG
  arangod/RestHandler/RestDumpHandler.cpp
  client-tools/Dump/DumpFeature.cpp
  client-tools/Dump/DumpFeature.h
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testutils/process-utils.js
  tests/test-definitions.txt
Labels: cla-signed

#20033 Clean up collection if it was created successfully.
  tests/js/client/active-failover/disconnected-leader-nonwindows-nocov-noasan.js
Labels: cla-signed

#20030 enable async prefetching for some graph nodes
  arangod/Aql/EnumeratePathsExecutor.cpp
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/GraphNode.h
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalExecutor.h
  arangod/Aql/TraversalNode.cpp
  tests/js/client/aql/aql-optimizer-rule-async-prefetch-cluster.js
  tests/js/client/aql/aql-optimizer-rule-async-prefetch-noncluster.js
Labels: cla-signed

#20040 enable async prefetching for direct dependencies of RemoteNodes
  arangod/Aql/OptimizerRules.cpp
  tests/js/client/aql/aql-optimizer-rule-async-prefetch-cluster.js
  tests/js/client/aql/aql-optimizer-rule-remove-filter-covered-by-index.js
  tests/js/common/shell/shell-statement-cluster.js
Labels: cla-signed

#20052 simplify execution block setup
  arangod/Aql/AqlCallStack.cpp
  arangod/Aql/AqlCallStack.h
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/ExecutionBlockImpl.tpp
Labels: cla-signed

#20042 Fixed BTS-1669
  CHANGELOG
  arangod/Transaction/Manager.cpp
  tests/Transaction/ManagerTest.cpp
Labels: cla-signed

#20044 Fixed BTS-1669
  CHANGELOG
  arangod/Transaction/Manager.cpp
  tests/Transaction/ManagerTest.cpp
Labels: cla-signed

#20043 Fixed BTS-1669
  CHANGELOG
  arangod/Transaction/Manager.cpp
  tests/Transaction/ManagerTest.cpp
Labels: cla-signed
