Repository arangodb/arangodb, pull requests merged in 2023-09, with the labels that each got.

#19677 Bug fix/bts 1570
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
Labels: cla-signed

#19675 [SEARCH-330] Use rocksdb MultiGet for materialize from search views
  arangod/Aql/AqlValue.cpp
  arangod/Aql/AqlValue.h
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IResearchViewExecutor.tpp
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewNode.h
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
  arangod/Aql/MultiGet.h
  arangod/IResearch/IResearchDocument.h
  arangod/IResearch/IResearchFilterFactory.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/RocksDBEngine/Methods/RocksDBBatchedMethods.h
  arangod/RocksDBEngine/Methods/RocksDBBatchedWithIndexMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBBatchedWithIndexMethods.h
  arangod/RocksDBEngine/Methods/RocksDBReadOnlyBaseMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBReadOnlyBaseMethods.h
  arangod/RocksDBEngine/Methods/RocksDBSstFileMethods.h
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBFormat.cpp
  arangod/RocksDBEngine/RocksDBFormat.h
  arangod/RocksDBEngine/RocksDBMethods.h
Labels: cla-signed

#19694 BTS-1598: Bug fix 3.10/fix unprotected access
  CHANGELOG
  arangod/Agency/State.cpp
Labels: cla-signed

#19680 clean up arangodump & arangorestore
  CHANGELOG
  arangod/RestHandler/RestDumpHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RocksDBEngine/RocksDBDumpContext.cpp
  arangod/RocksDBEngine/RocksDBDumpContext.h
  arangod/RocksDBEngine/RocksDBDumpManager.cpp
  arangod/RocksDBEngine/RocksDBDumpManager.h
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/VocBase/Methods/Collections.cpp
  client-tools/Dump/DumpFeature.cpp
  client-tools/Dump/DumpFeature.h
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Restore/RestoreFeature.h
  client-tools/Shell/TelemetricsHandler.cpp
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testutils/process-utils.js
  lib/Basics/InputProcessors.cpp
  lib/Basics/InputProcessors.h
  lib/CMakeLists.txt
  lib/Maskings/Maskings.cpp
  lib/Maskings/Maskings.h
  lib/SimpleHttpClient/HttpResponseChecker.cpp
  tests/js/client/shell/api/multi/document-replication-novst.js
  tests/js/client/shell/shell-dump-integration.js
  tests/js/server/dump/dump-check-dump-files-compressed.js
  tests/js/server/dump/dump-check-dump-files-uncompressed-no-envelopes.js
  tests/js/server/dump/dump-check-dump-files-uncompressed.js
  tests/js/server/dump/dump-maskings.js
  tests/test-definitions.txt
Labels: cla-signed

#19708 Fix windows build
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  client-tools/Restore/RestoreFeature.cpp
Labels: 3 Build, 4 Windows, cla-signed

#19632 [CINFRA-825] Remove external release api from replicated log
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/Components/LogFollower.h
  arangod/Replication2/ReplicatedLog/ILogInterfaces.h
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/ReplicatedState/ReplicatedState.h
  arangod/Replication2/ReplicatedState/ReplicatedStateFeature.h
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.cpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.h
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachineFeature.cpp
  tests/Replication2/Mocks/FakeFollower.cpp
  tests/Replication2/Mocks/FakeFollower.h
  tests/Replication2/ReplicatedLog/ReplicatedLogConnectTest.cpp
  tests/Replication2/ReplicatedState/StateManagerTest.cpp
  tests/js/common/shell/shell-replicated-logs-cluster.js
Labels: cinfra, cla-signed

#19703 Fix bugs around legacy little endian key encoding format
  CHANGELOG
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBDumpManager.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBKeyBounds.cpp
  arangod/RocksDBEngine/RocksDBUpgrade.cpp
  arangod/RocksDBEngine/RocksDBUpgrade.h
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  tests/RocksDBEngine/KeyTest.cpp
Labels: cla-signed

#19709 Fixed COLLECT variable validation loophole
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/AstNode.cpp
  arangod/Aql/Parser.cpp
  arangod/Aql/Parser.h
  arangod/Aql/VariableGenerator.cpp
  arangod/Aql/VariableGenerator.h
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  arangod/Aql/types.h
  tests/js/server/aql/aql-collect-subquery-scope-regression.js
Labels: cla-signed

#19707 minor internal improvements for arangodump
  client-tools/Dump/DumpFeature.cpp
Labels: cla-signed

#19713 remove unused options
  arangod/RocksDBEngine/RocksDBSettingsManager.cpp
Labels: cla-signed

#19714 Fixed BTS-1380
  CHANGELOG
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#19717 Refuse server startup with outdated little-endian on-disk format.
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBUpgrade.cpp
Labels: cla-signed

#19715 Fixed BTS-1543
  CHANGELOG
  client-tools/Utils/ManagedDirectory.cpp
  lib/Endpoint/Endpoint.cpp
  tests/Basics/EndpointTest.cpp
Labels: cla-signed

#19716 BTS-1531
  CHANGELOG
  arangod/GeneralServer/RestHandler.cpp
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/VocBase/Methods/Transactions.cpp
  tests/js/client/shell/api/multi/async.js
Labels: cla-signed

#19725 fix issues with Pregel garbage-collection
  CHANGELOG
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/PregelFeature.cpp
  arangod/Pregel/PregelFeature.h
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/common/shell/shell-pregel-basics-example.js
  tests/js/common/shell/shell-pregel-random.js
  tests/js/common/shell/shell-pregel-start-cluster.js
  tests/js/common/shell/shell-pregel-status-writer.js
Labels: cla-signed

#19711 Add arangotools build target
  CMakeLists.txt
Labels: cla-signed

#19724 Fixed COLLECT variable validation loophole
  CHANGELOG
  arangod/Aql/Ast.cpp
  arangod/Aql/Ast.h
  arangod/Aql/grammar.cpp
  arangod/Aql/grammar.hpp
  arangod/Aql/grammar.y
  tests/js/server/aql/aql-collect-subquery-scope-regression.js
Labels: cla-signed

#19726 try to fix compilation on Windows
  arangod/RestServer/arangod.cpp
  arangod/RestServer/arangod.h
  client-tools/Dump/DumpFeature.cpp
  client-tools/Dump/arangodump.cpp
  client-tools/Dump/arangodump.h
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Restore/arangorestore.cpp
  client-tools/Restore/arangorestore.h
Labels: 3 Build, 4 Windows, cla-signed

#19720 Fix bugs around legacy little endian key encoding format
  CHANGELOG
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBDumpManager.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBKeyBounds.cpp
  arangod/RocksDBEngine/RocksDBUpgrade.cpp
  arangod/RocksDBEngine/RocksDBUpgrade.h
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  tests/RocksDBEngine/KeyTest.cpp
Labels: 3 RocksDB, cla-signed

#19721 Feature/cinfra 430 modify collections replication2
  arangod/Agency/AgencyPaths.h
  arangod/Cluster/ClusterCollectionMethods.cpp
  arangod/Cluster/ClusterCollectionMethods.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/Utils/PlanCollectionEntryReplication2.cpp
  arangod/Cluster/Utils/TargetCollectionAgencyWriter.cpp
  arangod/Replication2/AgencyCollectionSpecification.h
  arangod/Replication2/AgencyCollectionSpecificationInspectors.h
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/VocBase/LogicalCollection.cpp
  js/common/modules/@arangodb/testutils/collection-groups-helper.js
  tests/js/client/shell/api/api-replication.js
Labels: cla-signed

#19728 change container type back to std::unordered_map
  arangod/Aql/VariableGenerator.h
Labels: cla-signed

#19727 BTS-1489: Race condition in AsioSocket shutdown when using SSL.
  CHANGELOG
  arangod/GeneralServer/Acceptor.h
  arangod/GeneralServer/AcceptorTcp.cpp
  arangod/GeneralServer/AcceptorTcp.h
  arangod/GeneralServer/AcceptorUnixDomain.cpp
  arangod/GeneralServer/AcceptorUnixDomain.h
  arangod/GeneralServer/AsioSocket.h
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/GeneralCommTask.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/H2CommTask.h
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/HttpCommTask.h
  arangod/GeneralServer/VstCommTask.cpp
  arangod/GeneralServer/VstCommTask.h
Labels: cla-signed

#19697 [BTS-1460][3.10] Directly kill aborted query, do not wait for GC
  CHANGELOG
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/RemoteExecutor.cpp
  tests/js/server/aql/aql-failures-cluster.js
Labels: 9 Waiting for Jenkins, cla-signed

#19730 Fix MemoryAccounting Agency Node Array
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
Labels: cla-signed

#19733 fix an assertion failure in chaos tests
  arangod/RocksDBEngine/RocksDBMethodsMemoryTracker.cpp
Labels: cla-signed

#19723 Remove some large copies in ClusterInfo loadPlan via shared_ptr
  arangod/Aql/Collection.cpp
  arangod/Aql/Collection.h
  arangod/Aql/ShardLocking.cpp
  arangod/Aql/TraverserEngineShardLists.cpp
  arangod/Aql/TraverserEngineShardLists.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/GeneralServer/AuthenticationFeature.cpp
  arangod/Sharding/ShardDistributionReporter.cpp
  lib/Containers/FlatHashMap.h
  lib/Containers/FlatHashSet.h
  tests/Mocks/ClusterInfoMock.cpp
Labels: cla-signed

#19614 [BTS-724][DEVEL] Added test for opt-rule: remove-redundant-path-var
  js/server/modules/@arangodb/testutils/aql-graph-traversal-generic-tests.js
Labels: cla-signed

#19592 [BTS-1553] Fix wrong limit value use in LimitExecutor
  CHANGELOG
  arangod/Aql/AqlCall.h
  arangod/Aql/LimitExecutor.cpp
  tests/Aql/LimitExecutorTest.cpp
Labels: 1 Bug, cla-signed

#19605 [BTS-1544][3.10] _system db not reporting its sharding property correctly
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/VocBase/VocbaseInfo.cpp
  arangod/VocBase/VocbaseInfo.h
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
Labels: 9 Review Required, cla-signed

#19751 Der Tragödie zweiter Teil
  arangod/RocksDBEngine/RocksDBMethodsMemoryTracker.cpp
Labels: cla-signed

#19749 Added minimal bug-fix (#19611)
  CHANGELOG
  arangod/Cluster/ClusterFeature.cpp
Labels: cla-signed

#19754 BTS-1601
  arangod/Aql/Functions.cpp
Labels: cla-signed

#19742 Add arangotools target 3.11
  CMakeLists.txt
Labels: 3 ArangoSearch, cla-signed

#19755 Fix compile with address sanitizer
  lib/Containers/FlatHashMap.h
  lib/Containers/FlatHashSet.h
Labels: 3 Build, cla-signed

#19757 This is a follow-up commit to slightly optimize some new code from
  arangod/Aql/Functions.cpp
Labels: cla-signed

#19759 Added cppcheck to base images for circleci
  scripts/docker/build/arangodb-build.Dockerfile
  scripts/docker/build/install-cppcheck.sh
Labels: 3 Build, cla-signed

#19699 [CINFRA-818] Index creation should go through the replicated log
  arangod/Cluster/EnsureIndex.cpp
  arangod/Cluster/EnsureIndex.h
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.h
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.h
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.h
  arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.cpp
  arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.h
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.cpp
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.h
  arangod/Replication2/StateMachines/Document/ReplicatedOperationInspectors.h
  arangod/VocBase/Methods/Indexes.cpp
  arangod/VocBase/Methods/Indexes.h
  js/common/modules/@arangodb/testutils/document-state-helper.js
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#19762 fix wrong version number in options documentation
  arangod/RestServer/DatabaseFeature.cpp
Labels: 3 Documentation, cla-signed

#19765 [BTS-1613] Do not check revisions on single
  CHANGELOG
  arangod/IResearch/IResearchAnalyzerFeature.cpp
Labels: 3 ArangoSearch, cla-signed, Backport Needed

#19761 [OASIS-25486] Fix line rank computation.
  arangod/Pregel/Algos/LineRank/LineRank.cpp
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/common/shell/shell-pregel-components.js
Labels: cla-signed

#19741 Chore Cinfra: Bug-Fixes on Replication2 only
  arangod/Cluster/CMakeLists.txt
  arangod/Cluster/ClusterIndexMethods.cpp
  arangod/Cluster/ClusterIndexMethods.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/CreateCollection.cpp
  arangod/Replication2/AgencyCollectionSpecification.cpp
  arangod/Replication2/AgencyCollectionSpecification.h
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/VocBase/Methods/Indexes.cpp
  arangod/VocBase/VocbaseInfo.cpp
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cla-signed

#19769 BTS-1611: fix issues with maskings, add test
  client-tools/Dump/DumpFeature.cpp
  lib/Basics/InputProcessors.cpp
  tests/Basics/CMakeLists.txt
  tests/Basics/InputProcessorsData.json
  tests/Basics/InputProcessorsTest.cpp
Labels: 3 ImportExport, cla-signed

#19606 QA-462 - Improved Memory Accounting
  CHANGELOG
  arangod/ClusterEngine/ClusterEngine.cpp
  arangod/ClusterEngine/ClusterEngine.h
  arangod/ClusterEngine/ClusterV8Functions.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.h
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBSettingsManager.cpp
  arangod/RocksDBEngine/RocksDBV8Functions.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/StorageEngine/PhysicalCollection.h
  arangod/StorageEngine/StorageEngine.h
  arangod/VocBase/vocbase.cpp
  arangod/VocBase/vocbase.h
  js/client/modules/@arangodb/test-helper.js
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/js/client/shell/api/arangosearch-memory-metrics-noncluster.js
  tests/js/client/shell/api/arangosearch-memory-metrics.inc
  tests/js/client/shell/shell-improved-metrics-accounting-cluster.js
  tests/js/client/shell/shell-improved-metrics-accounting-fail-at.inc
  tests/js/client/shell/shell-improved-metrics-accounting-no-repl.js
  tests/js/client/shell/shell-improved-metrics-accounting-oneshard-cluster.js
  tests/js/client/shell/shell-improved-metrics-accounting.inc
  tests/js/client/shell/shell-revision-tree-tracking-noncluster.js
  tests/js/client/shell/shell-track-index-selectivity-estimates-noncluster.js
  tests/js/server/shell/shell-database-noncluster.js
Labels: 3 - Testing, cla-signed

#19766 [3.11] BTS-1613 fix importing analyzers to single from cluster
  CHANGELOG
  arangod/IResearch/IResearchAnalyzerFeature.cpp
Labels: 3 ArangoSearch, cla-signed

#19771 [BTS-1239] Fixed restoring single server dump into cluster
  CHANGELOG
  arangod/VocBase/Properties/CreateCollectionBody.cpp
  arangod/VocBase/Properties/DatabaseConfiguration.h
  arangod/VocBase/vocbase.cpp
  tests/js/client/shell/api/api-replication.js
Labels: cla-signed

#19760 [CINFRA-819] DropIndex operation
  arangod/Cluster/DropIndex.cpp
  arangod/Cluster/DropIndex.h
  arangod/Cluster/EnsureIndex.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.cpp
  arangod/Replication2/StateMachines/Document/DocumentFollowerState.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.h
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.h
  arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.cpp
  arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.h
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.cpp
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.h
  arangod/Replication2/StateMachines/Document/ReplicatedOperationInspectors.h
  js/common/modules/@arangodb/testutils/document-state-helper.js
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#19753 Added cppcheck run on pr runs
  .circleci/base_config.yml
  lib/Basics/socket-utils.cpp
  utils/cppcheck-circleci.sh
Labels: cla-signed

#19780 fix UB in NetworkFeature
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
Labels: cla-signed

#19785 add thread-id to log output during tests
  etc/testing/arangod-common.conf
  tests/js/client/server_parameters/log-json-no-shorten.js
  tests/js/client/server_parameters/log-json-shorten.js
  tests/js/client/server_parameters/log-json.js
Labels: cla-signed

#19784 small AQL cleanup
  arangod/Aql/AsyncExecutor.h
  arangod/Aql/CalculationExecutor.h
  arangod/Aql/ConstrainedSortExecutor.cpp
  arangod/Aql/ConstrainedSortExecutor.h
  arangod/Aql/CountCollectExecutor.cpp
  arangod/Aql/CountCollectExecutor.h
  arangod/Aql/DistinctCollectExecutor.cpp
  arangod/Aql/DistinctCollectExecutor.h
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/EnumerateCollectionExecutor.h
  arangod/Aql/EnumerateListExecutor.h
  arangod/Aql/EnumeratePathsExecutor.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/FilterExecutor.cpp
  arangod/Aql/FilterExecutor.h
  arangod/Aql/HashedCollectExecutor.cpp
  arangod/Aql/HashedCollectExecutor.h
  arangod/Aql/IResearchViewExecutor.h
  arangod/Aql/IdExecutor.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  arangod/Aql/LimitExecutor.h
  arangod/Aql/MaterializeExecutor.h
  arangod/Aql/ModificationExecutor.h
  arangod/Aql/MultipleRemoteModificationExecutor.h
  arangod/Aql/NoResultsExecutor.cpp
  arangod/Aql/NoResultsExecutor.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/ParallelUnsortedGatherExecutor.h
  arangod/Aql/ReturnExecutor.cpp
  arangod/Aql/ReturnExecutor.h
  arangod/Aql/ShortestPathExecutor.h
  arangod/Aql/SingleRemoteModificationExecutor.h
  arangod/Aql/SortExecutor.h
  arangod/Aql/SortedCollectExecutor.cpp
  arangod/Aql/SortedCollectExecutor.h
  arangod/Aql/SortingGatherExecutor.h
  arangod/Aql/SubqueryEndExecutor.cpp
  arangod/Aql/SubqueryEndExecutor.h
  arangod/Aql/SubqueryStartExecutor.cpp
  arangod/Aql/SubqueryStartExecutor.h
  arangod/Aql/TraversalExecutor.h
  arangod/Aql/UnsortedGatherExecutor.h
  arangod/Aql/WindowExecutor.cpp
  arangod/Aql/WindowExecutor.h
  tests/Aql/SubqueryEndExecutorTest.cpp
  tests/Aql/SubqueryStartExecutorTest.cpp
  tests/Aql/TestEmptyExecutorHelper.h
  tests/Aql/TestLambdaExecutor.h
Labels: cla-signed

#19738 we need to reflect whether running the arangosh was successfull or not.
  js/client/modules/@arangodb/testutils/test-utils.js
Labels: 3 - Testing, cla-signed

#19637 FE-365: fix query import
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.0ed773df.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.0ed773df.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.0ed773df.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.6c8dbeca.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.6c8dbeca.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.6c8dbeca.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/addCollection/AddCollectionModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/editor/ImportQueryModal.tsx
Labels: 1 Bug, 3 UI, cla-signed

#19750 APM-780: limits for arangodump
  CHANGELOG
  Documentation/Metrics/arangodb_dump_memory_usage.yaml
  Documentation/Metrics/arangodb_dump_ongoing.yaml
  Documentation/Metrics/arangodb_dump_threads_blocked_total.yaml
  arangod/RestServer/DumpLimitsFeature.cpp
  arangod/RestServer/DumpLimitsFeature.h
  arangod/RestServer/arangod.h
  arangod/RestServer/arangod_includes.h
  arangod/RocksDBEngine/RocksDBDumpContext.cpp
  arangod/RocksDBEngine/RocksDBDumpContext.h
  arangod/RocksDBEngine/RocksDBDumpManager.cpp
  arangod/RocksDBEngine/RocksDBDumpManager.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.h
  arangod/RocksDBEngine/RocksDBRestReplicationHandler.cpp
  arangod/arangoserver.cmake
  client-tools/Dump/DumpFeature.cpp
  client-tools/Dump/DumpFeature.h
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Restore/RestoreFeature.h
  tests/js/client/server_parameters/dump-limits-noncluster-nonwindows.js
  tests/test-definitions.txt
Labels: cla-signed

#19786 clean up AqlCall
  arangod/Aql/AqlCall.cpp
  arangod/Aql/AqlCall.h
  arangod/Aql/EnumerateCollectionExecutor.cpp
  arangod/Aql/EnumerateListExecutor.cpp
  arangod/Aql/EnumeratePathsExecutor.cpp
  arangod/Aql/IResearchViewExecutor.tpp
  arangod/Aql/SortExecutor.cpp
  arangod/Aql/SubqueryStartExecutor.cpp
  arangod/Aql/TraversalExecutor.cpp
  tests/Aql/ExecutionBlockImplTest.cpp
  tests/Aql/SplicedSubqueryIntegrationTest.cpp
Labels: cla-signed

#19791 some further small AQL refactoring
  arangod/Aql/AqlCall.h
  arangod/Aql/AqlCallList.cpp
  arangod/Aql/AqlCallList.h
  arangod/Aql/AqlCallStack.cpp
  arangod/Aql/AqlCallStack.h
  arangod/Aql/AqlItemBlockInputRange.cpp
  arangod/Aql/AqlItemBlockInputRange.h
  arangod/Aql/AsyncExecutor.cpp
  arangod/Aql/AsyncExecutor.h
  arangod/Aql/ConstFetcher.cpp
  arangod/Aql/ConstFetcher.h
  arangod/Aql/DependencyProxy.cpp
  arangod/Aql/DependencyProxy.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/IResearchViewExecutor.tpp
  arangod/Aql/MultiDependencySingleRowFetcher.cpp
  arangod/Aql/MultiDependencySingleRowFetcher.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
  arangod/Aql/RemoveModifier.cpp
  arangod/Aql/SingleRowFetcher.cpp
  arangod/Aql/SingleRowFetcher.h
  arangod/Aql/UpdateReplaceModifier.cpp
  arangod/Aql/UpsertModifier.cpp
  arangod/Graph/PathManagement/PathValidatorOptions.h
  arangod/Pregel/Algos/ShortestPath/ShortestPath.cpp
  tests/Aql/DependencyProxyMock.cpp
  tests/Aql/DependencyProxyMock.h
Labels: cla-signed

#19790 Feature/testing broadcast bind
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/testing.js
Labels: 3 - Testing, cla-signed

#19773 [3.10] [OASIS-25486] fix line rank computation
  arangod/Pregel/Algos/LineRank.cpp
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/common/shell/shell-pregel-components.js
Labels: cla-signed

#19772 [3.11] [OASIS-25486] fix line rank computation
  arangod/Pregel/Algos/LineRank/LineRank.cpp
  js/common/modules/@arangodb/graph/pregel-test-helpers.js
  tests/js/common/shell/shell-pregel-components.js
Labels: cla-signed

#19638 bugfix-3.11/FE-365: fix query import
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoQueries.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/css/main.ea26cf36.css.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.5d8c92a8.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.5d8c92a8.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.5d8c92a8.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.d318c7cf.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.d318c7cf.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.d318c7cf.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.9512fedafa8e56b22d68.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-300.beab3f58283dd9683614.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.916656a297b1a9fa698b.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-500.abd255e8d4a57cfa076a.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.8d11d1e159ab0e14c0e6.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-700.9c9c164e699d486b5abf.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.81dc9b21d2ced318e9ae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/Roboto-regular.bcf2ba9ef2bd549116a9.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-dark.994d1553f409200f5901.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb-icon.35807d6e11925bd44973.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/arangodb.609cd935d9d34dab5e6b.eot.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/favicon.909457142f6be9dae418.ico.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.ed6298903ae1554c7f3e.svg.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/fontawesome-webfont.f0af1680f082547a7aae.ttf.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/media/jsoneditor-icons.ffbb30248a6fc9adfc7f.svg.gz
Labels: 1 Bug, 3 UI, cla-signed

#19796 fix error handling to have proper brackets.
  js/common/modules/@arangodb/test-helper-common.js
Labels: 3 - Testing, cla-signed

#19800 [3.10] fix eslint
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoQueries.js
Labels: cla-signed

#19799 [3.11] fix eslint
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoQueries.js
Labels: cla-signed

#19798 Make our waitpid implementation interupteable by the monitoring thread
  client-tools/Shell/ProcessMonitoringFeature.cpp
  client-tools/Shell/v8-deadline.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/process-utils.cpp
  lib/Basics/process-utils.h
  lib/V8/v8-deadline.h
  lib/V8/v8-no-deadline.cpp
  lib/V8/v8-utils.cpp
Labels: 3 - Testing, cla-signed

#19802 disable the right test
  js/client/modules/@arangodb/testsuites/dump.js
Labels: 3 - Testing, cla-signed

#19794 Small AQL refactoring
  arangod/Aql/AqlCall.cpp
  arangod/Aql/AqlCallList.cpp
  arangod/Aql/AqlCallStack.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionEngine.h
  arangod/Aql/Query.cpp
  arangod/Aql/QueryCursor.cpp
  js/server/modules/@arangodb/testutils/aql-profiler-test-helper.js
  tests/js/server/aql/aql-optimizer-collect-aggregate.js
  tests/js/server/aql/aql-profiler-cluster.js
Labels: cla-signed

#19812 detect numeric attribute ids in returned VelocyPack data
  lib/Basics/VelocyPackHelper.cpp
  tests/js/client/shell/multi/shell-vpack.js
Labels: cla-signed

#19801 Fix test for arangodb_search_writers_memory_usage
  tests/js/client/shell/api/arangosearch-memory-metrics.inc
Labels: 3 - Testing, 3 ArangoSearch, 3 Metrics, cla-signed

#19805 Add prefetching for WAL tailing
  CHANGELOG
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/DatabaseInitialSyncer.h
  arangod/Replication/DatabaseTailingSyncer.cpp
  arangod/Replication/DatabaseTailingSyncer.h
  arangod/Replication/Syncer.cpp
  arangod/Replication/Syncer.h
Labels: cla-signed

#19811 small code cleanup, pulled out of larger PR
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AsyncExecutor.cpp
  arangod/Aql/CalculationExecutor.cpp
  arangod/Aql/DistinctCollectExecutor.h
  arangod/Aql/DocumentProducingNode.cpp
  arangod/Aql/DocumentProducingNode.h
  arangod/Aql/ExecutionStats.h
  arangod/Aql/HashedCollectExecutor.cpp
  arangod/Aql/ModificationNodes.h
  arangod/Aql/OutputAqlItemRow.cpp
  arangod/Aql/OutputAqlItemRow.h
  arangod/Aql/Query.cpp
  arangod/Aql/SortedCollectExecutor.cpp
  arangod/Aql/SortedCollectExecutor.h
Labels: cla-signed

#19817 FE-376: fix query UI crash on null response
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.13069a83.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.13069a83.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.13069a83.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c63a5daa.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c63a5daa.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.c63a5daa.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryExecuteResult.tsx
Labels: 1 Bug, 3 UI, cla-signed

#19807 Fixed issue with `keepNull=false` updates
  CHANGELOG
  arangod/Transaction/Methods.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
  tests/js/client/shell/shell-document-keepnull-cluster.js
Labels: cla-signed

#19809 Fixed issue with `keepNull=false` updates
  CHANGELOG
  arangod/Transaction/Methods.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
  tests/js/client/shell/shell-document-keepnull-cluster.js
Labels: cla-signed

#19808 Fixed issue with `keepNull=false` updates
  CHANGELOG
  arangod/Transaction/Methods.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
  tests/js/client/shell/shell-document-keepnull-cluster.js
Labels: cla-signed

#19815 clean up AQL node serialization
  CHANGELOG
  arangod/Aql/ClusterNodes.cpp
  arangod/Aql/CollectionAccessingNode.cpp
  arangod/Aql/GraphNode.cpp
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IndexNode.cpp
  arangod/Aql/OptimizerRules.cpp
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/server/aql/aql-explain-cluster.js
  tests/js/server/aql/aql-explain-noncluster.js
  tests/js/server/aql/aql-gather-block-cluster.js
  tests/js/server/aql/aql-optimizer-rule-use-index-for-sort.js
Labels: cla-signed

#19820 Avoid ReadWriteLock overflow
  CHANGELOG
  lib/Basics/ReadWriteLock.h
  tests/Basics/ReadWriteLockTest.cpp
Labels: cla-signed

#19768 Make it slightly more possible to just install client-tools
  CMakeLists.txt
  client-tools/CMakeLists.txt
Labels: 3 Build, 3 Packaging, cla-signed

#19828 Fix windows build
  lib/Basics/ReadWriteLock.h
Labels: cla-signed

#19826 Remove special handling for backups taken with ArangoDB 3.5
  CHANGELOG
Labels: cla-signed

#19822 [3.11] Backport #19768 (Make it slightly more possible to install client-tools)
  CMakeLists.txt
  client-tools/CMakeLists.txt
Labels: 3 Build, 3 Packaging, cla-signed

#19836 assert that atomic ops on basic integral types are always lock-free
  arangod/RestServer/EnvironmentFeature.cpp
Labels: cla-signed

#19838 Fixed issue with `keepNull=false` updates
  CHANGELOG
  arangod/Transaction/Methods.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
  tests/js/client/shell/shell-document-keepnull-cluster.js
Labels: cla-signed

#19835 make {Plain,Transactional}Cache::freeMemoryWhile() cheaper
  CHANGELOG
  arangod/Cache/PlainCache.cpp
  arangod/Cache/PlainCache.h
  arangod/Cache/TransactionalCache.cpp
  arangod/Cache/TransactionalCache.h
Labels: cla-signed

#19770 improve performance of LimitExecutor
  CHANGELOG
  arangod/Aql/LimitExecutor.cpp
  arangod/Aql/LimitExecutor.h
Labels: cla-signed

#19831 make {Plain,Transactional}Cache::freeMemoryWhile() cheaper
  arangod/Cache/PlainCache.cpp
  arangod/Cache/PlainCache.h
  arangod/Cache/TransactionalCache.cpp
  arangod/Cache/TransactionalCache.h
Labels: cla-signed

#19833 make {Plain,Transactional}Cache::freeMemoryWhile() cheaper
  CHANGELOG
  arangod/Cache/PlainCache.cpp
  arangod/Cache/PlainCache.h
  arangod/Cache/TransactionalCache.cpp
  arangod/Cache/TransactionalCache.h
Labels: cla-signed

#19829 fix taking hot backups with allowInconsistent=false
  CHANGELOG
Labels: cla-signed

#19832 make {Plain,Transactional}Cache::freeMemoryWhile() cheaper
  CHANGELOG
  arangod/Cache/PlainCache.cpp
  arangod/Cache/PlainCache.h
  arangod/Cache/TransactionalCache.cpp
  arangod/Cache/TransactionalCache.h
Labels: cla-signed

#19839 improve PlainCache::freeMemoryWhile() performance
  arangod/Cache/PlainCache.cpp
Labels: cla-signed

#19837 Fixed issue with `keepNull=false` updates
  CHANGELOG
  arangod/Transaction/Methods.cpp
  tests/js/client/chaos/test-chaos-load-common.inc
  tests/js/client/shell/shell-document-keepnull-cluster.js
Labels: cla-signed

#19746 JoinNode + Executor
  arangod/Aql/CMakeLists.txt
  arangod/Aql/CollectNode.cpp
  arangod/Aql/ConditionFinder.cpp
  arangod/Aql/EngineInfoContainerCoordinator.cpp
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IResearchViewNode.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/IndexJoin/GenericMerge.h
  arangod/Aql/IndexJoinStrategy.cpp
  arangod/Aql/IndexJoinStrategy.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexStreamIterator.h
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/JoinExecutor.h
  arangod/Aql/JoinNode.cpp
  arangod/Aql/JoinNode.h
  arangod/Aql/OptimizerRule.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRules.h
  arangod/Aql/OptimizerRulesFeature.cpp
  arangod/Aql/QuerySnippet.cpp
  arangod/Aql/ShardLocking.cpp
  arangod/Aql/TraversalConditionFinder.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/Aql/JoinStrategy/GenericJoinTest.cpp
  tests/CMakeLists.txt
  tests/js/server/aql/aql-index-join-noncluster.js
  tests/js/server/aql/aql-memory-limit.js
  tests/js/server/aql/aql-optimizer-stats-noncluster.js
Labels: cla-signed

#19842 further improve performance of `freeMemoryWhile`
  arangod/Cache/Cache.cpp
  arangod/Cache/PlainCache.cpp
  arangod/Cache/TransactionalCache.cpp
Labels: cla-signed

#19852 Bugfix 3.11: Fix build of arangodb target
  CMakeLists.txt
Labels: 3 Build, cla-signed

#19863 Remove weird template parameter.
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
Labels: cla-signed

#19867 Feature/use materialize multi node for inverted index
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/IndexNodeOptimizerRules.cpp
Labels: cla-signed

#19806 implement shortening of cdb stacktraces filtering out the unneded threads
  js/client/modules/@arangodb/testutils/crash-utils.js
  js/client/modules/@arangodb/testutils/filter_cdb_stacks.json
  js/client/modules/@arangodb/testutils/filter_gdb_stacks.json
  js/client/modules/@arangodb/testutils/process-utils.js
Labels: 4 Windows, 3 - Testing, cla-signed

#19845 add more cache metrics
  CHANGELOG
  Documentation/Metrics/rocksdb_cache_free_memory_tasks_duration_total.yaml
  Documentation/Metrics/rocksdb_cache_free_memory_tasks_total.yaml
  Documentation/Metrics/rocksdb_cache_migrate_tasks_duration_total.yaml
  Documentation/Metrics/rocksdb_cache_migrate_tasks_total.yaml
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/Cache/ManagerTasks.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
Labels: 3 Metrics, cla-signed

#19862 Make ServerState::_rebootId atomic (#17878)
  arangod/Cluster/ClusterTypes.h
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
Labels: cla-signed

#19846 further improve performance of `freeMemoryWhile`
  arangod/Cache/Cache.cpp
  arangod/Cache/PlainCache.cpp
  arangod/Cache/TransactionalCache.cpp
Labels: cla-signed

#19855 improve error message for wrong batchSize values
  arangod/RestHandler/RestCursorHandler.cpp
  client-tools/Restore/RestoreFeature.cpp
  lib/Basics/ArangoGlobalContext.cpp
  lib/Basics/VelocyPackHelper.cpp
  lib/Basics/VelocyPackHelper.h
  tests/Aql/SortLimitTest.cpp
Labels: cla-signed

#19860 BTS-1622: add possibility to configure the available memory and distribute it a…
  js/client/modules/@arangodb/testsuites/endpoints.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/testing.js
Labels: 3 - Testing, cla-signed

#19872 More MaterializeExecutor cleanup.
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IndexNodeOptimizerRules.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
Labels: cla-signed

#19875 fix documentation for startup option
  arangod/V8Server/V8DealerFeature.cpp
Labels: cla-signed

#19783 [CINFRA-830] Create and Drop Index in Target (First version)
  arangod/Agency/Agent.cpp
  arangod/Agency/TransactionBuilder.h
  arangod/Cluster/ClusterIndexMethods.cpp
  arangod/Replication2/AgencyCollectionSpecification.cpp
  arangod/Replication2/AgencyCollectionSpecification.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  etc/testing/arangod-common.conf
  js/common/modules/@arangodb/testutils/document-state-helper.js
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cla-signed

#19876 fix documentation for startup option
  arangod/V8Server/V8DealerFeature.cpp
Labels: cla-signed

#19866 better reporting for hotbackup errors
  CHANGELOG
  arangod/Cluster/ClusterMethods.cpp
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
Labels: cla-signed

#19877 add code documentation to scheduler API
  arangod/Cluster/ClusterInfo.cpp
  arangod/Scheduler/Scheduler.h
  arangod/Scheduler/SupervisedScheduler.cpp
Labels: cla-signed

#19853 fix potential recursive lock invocation
  arangod/Cache/Manager.cpp
  tests/Cache/Manager.cpp
Labels: cla-signed

#19824 Speed up hotbackup incremental up-/download [BTS-1629]
  CHANGELOG
  js/client/modules/@arangodb/test-helper.js
  tests/test-definitions.txt
Labels: 3 ImportExport, cla-signed

#19880 remove unused include
  arangod/Graph/GraphOperations.cpp
Labels: cla-signed

#19857 FE-323: allow 'nested' property in view JSON UI
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.13069a83.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.13069a83.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.13069a83.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.50fa5a4c.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.50fa5a4c.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.50fa5a4c.js.gz
  js/apps/system/_admin/aardvark/APP/react/src/views/views/View.types.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/SearchJSONSchema.ts
Labels: 1 Bug, 3 UI, cla-signed

#19843 further improve performance of `freeMemoryWhile`
  arangod/Cache/Cache.cpp
  arangod/Cache/PlainCache.cpp
  arangod/Cache/TransactionalCache.cpp
Labels: cla-signed

#19871 [BTS-1618] Prevent projection problems
  CHANGELOG
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  tests/js/server/aql/aql-projections.js
Labels: cla-signed

#19864 [BTS-1618] Empty AQL Query Result
  CHANGELOG
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  tests/js/server/aql/aql-projections.js
Labels: 1 Bug, cla-signed, 3.10

#19869 [BTS-1618] Prevent projection problems
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  tests/js/server/aql/aql-projections.js
Labels: cla-signed

#19848 BTS-1622: add possibility to configure the available memory and distribute it among the spawned instances
  js/client/modules/@arangodb/testsuites/endpoints.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/testing.js
Labels: 3 - Testing, cla-signed
