Repository arangodb/arangodb, pull requests merged in 2024-01, with the labels that each got.

#20392 Remove unnecessary move.
  tests/Aql/JoinStrategy/GenericAndTwoNonUniqueJoinTest.cpp
Labels: cla-signed

#20394 Make sure we finish all TransactionActors when resigning
  arangod/Replication2/StateMachines/Document/Actor/ApplyEntries.cpp
Labels: cla-signed

#20393 [CINFRA] Attempt to "fix" ReplicatedLog shutdown blockage
  arangod/Replication2/Storage/RocksDB/LogPersistor.cpp
  arangod/Replication2/Storage/RocksDB/LogPersistor.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  tests/Replication2/ReplicatedLog/Integration/StorageEngineMethodsTest.cpp
Labels: cla-signed

#20395 [CINFRA] Only DEBUG output expected error situation
  arangod/Cluster/CreateCollection.cpp
Labels: cla-signed

#20398 BTS-1728: don't hold mutex while co_awaiting
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
Labels: cla-signed

#20381 added `RANDOM()` AQL function as an alias for `RAND()`
  arangod/Aql/AqlFunctionFeature.cpp
  tests/js/client/aql/aql-functions-numeric.js
Labels: cla-signed

#20390 ZKD Index Estimates
  arangod/Aql/TraversalNode.cpp
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndex.h
  arangod/ClusterEngine/ClusterIndexFactory.cpp
  arangod/Graph/TraverserOptions.cpp
  arangod/Graph/TraverserOptions.h
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/Indexes/IndexFactory.cpp
  arangod/Indexes/IndexFactory.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndexFactory.cpp
  arangod/RocksDBEngine/RocksDBZkdIndex.cpp
  arangod/RocksDBEngine/RocksDBZkdIndex.h
  tests/js/client/aql/aql-optimizer-zkdindex-prefix-fields.js
  tests/js/client/aql/aql-optimizer-zkdindex-random.js
  tests/js/client/aql/aql-optimizer-zkdindex-unique.js
  tests/js/client/aql/aql-optimizer-zkdindex.js
Labels: cla-signed

#20374 Added REST API `/_api/key-generators`
  CHANGELOG
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/RestHandler/RestKeyGeneratorsHandler.cpp
  arangod/RestHandler/RestKeyGeneratorsHandler.h
  arangod/VocBase/KeyGenerator.cpp
  arangod/VocBase/KeyGenerator.h
  arangod/arangoserver.cmake
  tests/js/client/shell/shell-keygen.js
Labels: 9 Ready to Merge, cla-signed

#20399 fix non-deterministic behavior on Windows
  arangod/Aql/EnumerateListExecutor.cpp
  arangod/Aql/EnumerateListExecutor.h
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/RegisterPlan.cpp
  arangod/Aql/RegisterPlan.h
  arangod/Aql/VarInfoMap.h
  arangod/Aql/types.h
  tests/Aql/EnumerateListExecutorTest.cpp
Labels: cla-signed

#20403 Fix handling of cacheEnabled flag for replication2
  arangod/Agency/AgencyPaths.h
  arangod/Cluster/ClusterCollectionMethods.cpp
  arangod/Cluster/Utils/PlanCollectionEntryReplication2.cpp
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/Replication2/AgencyCollectionSpecification.cpp
  arangod/Replication2/AgencyCollectionSpecification.h
  arangod/Replication2/AgencyCollectionSpecificationInspectors.h
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  tests/Mocks/PhysicalCollectionMock.h
Labels: cla-signed

#20405 [ZKD] Sparse Property
  arangod/Indexes/IndexFactory.cpp
  arangod/RocksDBEngine/RocksDBZkdIndex.cpp
  tests/js/client/aql/aql-zkdindex-multi.js
  tests/js/client/aql/aql-zkdindex-prefix-fields.js
  tests/js/client/aql/aql-zkdindex-random.js
  tests/js/client/aql/aql-zkdindex-restricted.js
  tests/js/client/aql/aql-zkdindex-sparse.js
  tests/js/client/aql/aql-zkdindex-stored-values.js
  tests/js/client/aql/aql-zkdindex-unique.js
  tests/js/client/aql/aql-zkdindex.js
Labels: cla-signed

#20404 [CINFRA] Adapt Replication1 specific Test
  tests/js/client/shell/shell-replication-responses-cluster.js
Labels: cla-signed

#20162 Use the async future lock
  arangod/Cluster/ClusterMethods.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.h
  lib/Basics/FutureSharedLock.h
  lib/Futures/CMakeLists.txt
  lib/Futures/include/Futures/coro-helper.h
  tests/Basics/FutureSharedLockTest.cpp
  tests/js/client/server_parameters/detach-threads-noncluster.js
Labels: cla-signed

#20410 Don't schedule concurrent compactions for the same column family
  CHANGELOG
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
Labels: cla-signed

#20409 Fixes for Ubuntu/glibc-based build image for circleci
  .circleci/base_config.yml
  scripts/docker/build/linux/Dockerfile.arm64
  scripts/docker/build/linux/Dockerfile.x86-64
  scripts/docker/build/linux/latest-tag.sh
  scripts/docker/build/linux/scripts/create-sccache-hardlinks.sh
  scripts/docker/build/linux/static/enable_static_nss.pat
  scripts/docker/build/linux/static/rebuild_glibc.sh
  scripts/docker/build/linux/tools/clang
  scripts/docker/build/linux/tools/clang++
Labels: cla-signed

#20413 [ZKD] BugFix PR
  arangod/Indexes/IndexFactory.cpp
  arangod/RocksDBEngine/RocksDBZkdIndex.cpp
  arangod/RocksDBEngine/RocksDBZkdIndex.h
  arangod/VocBase/Methods/Indexes.cpp
  tests/js/client/aql/aql-zkdindex-prefix-fields.js
  tests/js/client/aql/aql-zkdindex-unique-cluster.js
  tests/js/client/aql/aql-zkdindex-unique.js
  tests/js/client/aql/aql-zkdindex.js
Labels: cla-signed

#20423 Rename ZKD to MDI
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndexFactory.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/Indexes/IndexFactory.cpp
  arangod/Indexes/IndexFactory.h
  arangod/RocksDBEngine/CMakeLists.txt
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBColumnFamilyManager.cpp
  arangod/RocksDBEngine/RocksDBColumnFamilyManager.h
  arangod/RocksDBEngine/RocksDBComparator.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndexFactory.cpp
  arangod/RocksDBEngine/RocksDBKey.cpp
  arangod/RocksDBEngine/RocksDBKey.h
  arangod/RocksDBEngine/RocksDBKeyBounds.cpp
  arangod/RocksDBEngine/RocksDBKeyBounds.h
  arangod/RocksDBEngine/RocksDBMultiDimIndex.cpp
  arangod/RocksDBEngine/RocksDBMultiDimIndex.h
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.h
  arangod/RocksDBEngine/RocksDBOptionsProvider.cpp
  arangod/RocksDBEngine/RocksDBTypes.cpp
  arangod/RocksDBEngine/RocksDBTypes.h
  arangod/RocksDBEngine/RocksDBValue.cpp
  arangod/RocksDBEngine/RocksDBValue.h
  arangod/Utils/SupportInfoBuilder.cpp
  tests/js/client/aql/aql-mdi-multi.js
  tests/js/client/aql/aql-mdi-prefix-fields.js
  tests/js/client/aql/aql-mdi-random.js
  tests/js/client/aql/aql-mdi-restricted.js
  tests/js/client/aql/aql-mdi-sparse.js
  tests/js/client/aql/aql-mdi-stored-values.js
  tests/js/client/aql/aql-mdi-unique-cluster.js
  tests/js/client/aql/aql-mdi-unique.js
  tests/js/client/aql/aql-mdi.js
  tests/js/client/server_parameters/test-telemetrics-true-auth.js
Labels: cla-signed

#20426 treat "zkd" and "mdi" indexes as equal when comparing 'em
  arangod/ClusterEngine/ClusterIndexFactory.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/IndexFactory.cpp
Labels: cla-signed

#20402 Update `--server.endpoint` description for endpoint schema aliases
  arangod/RestServer/EndpointFeature.cpp
Labels: 3 Documentation, cla-signed

#20412 Disabled Rep1 specific test suite for Rep2
  tests/js/client/shell/shell-index-cleanup-cluster.js
Labels: cla-signed

#20428 simplify scheduler code parts
  arangod/Scheduler/SupervisedScheduler.cpp
Labels: cla-signed

#20424 only acquire hot backup commit lock upon commit
  arangod/Aql/Query.cpp
  arangod/Cluster/ClusterTrxMethods.cpp
Labels: cla-signed

#20415 BTS-1727: Return proper EXIT_UPGRADE_REQUIRED in cluster mode
  CHANGELOG
  arangod/RestServer/UpgradeFeature.cpp
  arangod/VocBase/Methods/Upgrade.cpp
Labels: cla-signed

#20414 remove now-obsolete code comments
  arangod/Aql/TraversalExecutor.cpp
  arangod/Aql/TraversalExecutor.h
  arangod/Aql/TraversalNode.cpp
Labels: cla-signed

#20411 Implement SupervisedScheduler::detachThread [BTS-1670]
  CHANGELOG
  Documentation/Metrics/arangodb_scheduler_num_detached_threads.yaml
  Documentation/Metrics/arangodb_scheduler_num_worker_threads.yaml
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/Scheduler/Scheduler.cpp
  arangod/Scheduler/Scheduler.h
  arangod/Scheduler/SchedulerFeature.cpp
  arangod/Scheduler/SchedulerFeature.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  tests/Cluster/RebootTrackerTest.cpp
  tests/js/client/server_parameters/detach-threads-cluster.js
  tests/js/client/server_parameters/detach-threads-noncluster.js
Labels: cla-signed

#20420 Fix: avoid duplicate link metrics
  CHANGELOG
  arangod/IResearch/IResearchInvertedClusterIndex.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  arangod/Metrics/MetricsFeature.cpp
  tests/IResearch/IResearchLinkTest.cpp
Labels: cla-signed

#20436 Suppress alignment errors in rocksdb's crc32c.cc
  ubsan_arangodb_suppressions.txt
Labels: 9 Ready to Merge, cla-signed

#20438 Use actual address in output
  scripts/startLocalCluster.sh
Labels: cla-signed

#20433 [CINFRA-870] Fix test
  tests/js/client/shell/shell-one-shard.js
Labels: cinfra, cla-signed

#20311 FE-377: remove broken link from JSON editor
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/css/jsoneditor.css
Labels: 1 Bug, 3 UI, cla-signed

#20417 remove artificial limitation for `--rocksdb.max-background-jobs`
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: cla-signed

#20419 BTS-1727: Return proper EXIT_UPGRADE_REQUIRED in cluster mode
  CHANGELOG
  arangod/RestServer/UpgradeFeature.cpp
Labels: cla-signed

#20416 remove artificial limitation for `--rocksdb.max-background-jobs`
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: cla-signed

#20418 BTS-1727: Return proper EXIT_UPGRADE_REQUIRED in cluster mode
  CHANGELOG
  arangod/RestServer/UpgradeFeature.cpp
Labels: cla-signed

#20427 fix lock timeout
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: cla-signed

#18832 [FE-249] Remove frontend build artifacts
  .circleci/base_config.yml
  .github/CODEOWNERS
  .gitignore
  CMakeLists.txt
  CONTRIBUTING.md
  cmake/FindNodejs.cmake
  cmake/FindYarn.cmake
  cmake/frontend/aardvark.cmake
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/moment.min.js
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/src/App.js
  js/apps/system/_admin/aardvark/APP/react/src/views/query/editor/SavedQueryView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/runningQueries/RunningQueries.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/slowQueries/SlowQueryHistory.tsx
  js/apps/system/_admin/aardvark/APP/react/yarn.lock
  scripts/docker/build/linux/Dockerfile.arm64
  scripts/docker/build/linux/Dockerfile.x86-64
  scripts/docker/build/linux/Makefile
  scripts/docker/build/windows/arangodb-build-win.Dockerfile
Labels: 1 Feature, 3 Build, 3 UI, 9 Review Required, cla-signed

#20441 Keep zkd index type.
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndexFactory.cpp
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBIndex.cpp
  arangod/RocksDBEngine/RocksDBIndexFactory.cpp
  arangod/RocksDBEngine/RocksDBMultiDimIndex.cpp
  arangod/RocksDBEngine/RocksDBMultiDimIndex.h
  tests/js/client/aql/aql-mdi.js
Labels: cla-signed

#20437 Escape control characters in audit log query strings
  CHANGELOG
Labels: 9 Ready to Merge, cla-signed

#20443 rename a test file
  tests/js/client/shell/multi/shell-ttl-nocov.js
Labels: 9 Ready to Merge, cla-signed

#20432 simplify node setup code
  arangod/Aql/BindParameters.cpp
  arangod/Aql/ExecutionPlan.cpp
Labels: 9 Ready to Merge, cla-signed

#20425 Cleanup dump contexts in tests.
  tests/js/client/shell/api/dump-cluster.js
Labels: cla-signed

#20445 fix AQL query profile output with older arangod versions
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#20448 fix: .gitignore ignores the frontend source code
  .gitignore
  js/apps/system/_admin/aardvark/APP/react/build/.gitignore
Labels: cla-signed

#20039 [BTS-1660] Fix PATCH validation in some gharial API related graph operations
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  arangod/Graph/GraphOperations.h
  tests/js/client/shell/api/api-gharial-spec.js
Labels: DO_NOT_MERGE, cla-signed

#20449 add debug information when things go wrong
  arangod/Aql/RestAqlHandler.cpp
Labels: cla-signed

#20450 (temporarily) suppress UBSan warnings for immer library
  ubsan_arangodb_suppressions.txt
Labels: cla-signed

#20451 Simplify and fix cmake frontend build
  cmake/frontend/aardvark.cmake
Labels: cla-signed

#20446 more usages of StrCat
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionState.cpp
  arangod/StorageEngine/TransactionState.h
Labels: cla-signed

#20447 Get rid of getpwuid and friends to avoid nsswitch
  CHANGELOG
  arangod/RestServer/PrivilegeFeature.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/FileUtils.h
  lib/Logger/LoggerFeature.cpp
Labels: cla-signed

#20434 [CINFRA] Fix propagation of writeConcern to collections and groups in Replication2
  arangod/Cluster/AgencyCache.cpp
  arangod/Replication2/Supervision/CollectionGroupSupervision.cpp
  arangod/Sharding/ShardingInfo.cpp
  arangod/Sharding/ShardingInfo.h
  arangod/VocBase/LogicalCollection.cpp
  tests/js/client/shell/shell-collection-properties-propagation-cluster.js
Labels: cla-signed

#20457 Suppress yet one more UBSan issue in the immer library
  ubsan_arangodb_suppressions.txt
Labels: cla-signed

#20455 fix test that fails on Windows
  lib/ProgramOptions/ProgramOptions.cpp
Labels: cla-signed

#20452 Enable full debug info for PR builds
  CMakePresets.json
Labels: cla-signed

#20453 Get rid of initgroups avoid nsswitch
  arangod/RestServer/PrivilegeFeature.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/FileUtils.h
Labels: cla-signed

#20467 Get rid of initgroups avoid nsswitch, take 3
  3rdParty/README_maintainers.md
  3rdParty/date/src/tz.cpp
Labels: cla-signed

#20464 Fix gitignore setup for frontend build
  js/apps/system/_admin/aardvark/APP/react/.gitignore
  js/apps/system/_admin/aardvark/APP/react/build/.gitignore
Labels: cla-signed

#20456 only try to use suppressions file if it actually exists
  scripts/unittest
Labels: cla-signed

#20458 fix BTS-1731
  CHANGELOG
  arangod/StorageEngine/TransactionState.cpp
Labels: cla-signed

#20465 Bug fix/cinfra fix race link modify
  arangod/Cluster/DropIndex.cpp
  arangod/Cluster/DropIndex.h
  arangod/Cluster/EnsureIndex.cpp
  arangod/Cluster/EnsureIndex.h
  arangod/Cluster/Maintenance.cpp
Labels: cla-signed

#20474 Zkd External CF Name
  arangod/RocksDBEngine/RocksDBColumnFamilyManager.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: cla-signed

#20439 Prometheus labels should be snake_case
  arangod/IResearch/IResearchInvertedClusterIndex.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  tests/IResearch/IResearchLinkTest.cpp
Labels: cla-signed

#20476 lazily initialize dummyChildren global
  arangod/Agency/Node.cpp
  arangod/Agency/Node.h
Labels: cla-signed

#20478 [Bug-Fix] Do not copy UI's node_modules folder in V8
  CHANGELOG
  arangod/V8Server/V8DealerFeature.cpp
Labels: cla-signed

#20462 FE-420: persist filter & column visibility state
  js/apps/system/_admin/aardvark/APP/react/src/components/table/TableColumnSelector.tsx
  js/apps/system/_admin/aardvark/APP/react/src/components/table/TableControl.tsx
  js/apps/system/_admin/aardvark/APP/react/src/components/table/useSortableReactTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/listAnalyzers/AnalyzersTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/listIndices/CollectionIndicesTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/listCollections/CollectionsTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/listDatabases/DatabasesTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/listGraphs/GraphsTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/editor/SavedQueryView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/services/listServices/ServicesTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/users/listUsers/UsersTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/users/viewUser/CollectionsPermissionsTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/users/viewUser/UserPermissionsContext.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/users/viewUser/UserPermissionsTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/ViewsTable.tsx
Labels: 3 UI, cla-signed

#20460 fix BTS-1731
  CHANGELOG
  arangod/StorageEngine/TransactionState.cpp
Labels: 3 Transaction, cla-signed

#20396 bug-fix-3.11/FE-385: fix query import
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/collections/arangoQueries.js
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json
  js/apps/system/_admin/aardvark/APP/react/build/asset-manifest.json.gz
  js/apps/system/_admin/aardvark/APP/react/build/index.html
  js/apps/system/_admin/aardvark/APP/react/build/index.html.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1206e42b.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1206e42b.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.1206e42b.js.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.d4267b00.js.LICENSE.txt
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.d4267b00.js.LICENSE.txt.gz
  js/apps/system/_admin/aardvark/APP/react/build/static/js/main.d4267b00.js.gz
Labels: 3 UI, cla-signed

#20472 Validate that smartgraph attribute exists and is not changed
  CHANGELOG
  arangod/VocBase/LogicalCollection.h
  tests/js/server/dump/dump-setup-cluster.js
  tests/js/server/dump/dump-setup-common.inc
  tests/js/server/dump/dump-test.inc
Labels: 9 Ready to Merge, cla-signed

#20471 Validate that smartgraph attribute exists and is not changed
  CHANGELOG
  arangod/VocBase/LogicalCollection.h
  tests/js/server/dump/dump-setup-cluster.js
  tests/js/server/dump/dump-setup-common.inc
  tests/js/server/dump/dump-test.inc
Labels: 9 Ready to Merge, cla-signed

#20484 some cleanup for APM-828 after code review
  Documentation/Metrics/arangodb_collection_leader_reads_total.yaml
  Documentation/Metrics/arangodb_collection_leader_writes_total.yaml
  arangod/Metrics/MetricsFeature.cpp
  arangod/Network/Utils.cpp
  arangod/Network/Utils.h
  arangod/Pregel/PregelFeature.cpp
  arangod/RestHandler/RestAdminLogHandler.cpp
  arangod/RestHandler/RestMetricsHandler.cpp
  arangod/RestHandler/RestUsageMetricsHandler.cpp
  arangod/Utils/SupportInfoBuilder.cpp
  arangod/VocBase/Methods/Queries.cpp
Labels: cla-signed

#20480 [Bug-Fix] Do not copy UI's node_modules folder in ArangoShell (V8)
  CHANGELOG
  client-tools/Shell/V8ShellFeature.cpp
Labels: cla-signed

#20477 For replication2 activate failure points only on leaders
  arangod/IResearch/IResearchDataStore.cpp
Labels: cla-signed

#20283 remove afo code
  CONTRIBUTING.md
  arangod/Agency/ActiveFailoverJob.cpp
  arangod/Agency/ActiveFailoverJob.h
  arangod/Agency/AgencyFeature.cpp
  arangod/Agency/CMakeLists.txt
  arangod/Agency/Job.cpp
  arangod/Agency/JobContext.cpp
  arangod/Agency/Supervision.cpp
  arangod/Aql/Functions.cpp
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/HeartbeatThread.h
  arangod/Cluster/RestClusterHandler.cpp
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
  arangod/Cluster/v8-cluster.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/Replication/ReplicationFeature.cpp
  arangod/Replication/ReplicationFeature.h
  arangod/Replication/Syncer.cpp
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestHandler/RestWalAccessHandler.cpp
  arangod/RestServer/BootstrapFeature.cpp
  arangod/RestServer/TtlFeature.cpp
  arangod/RestServer/TtlFeature.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBEngine.h
  arangod/Utils/SupportInfoBuilder.cpp
  arangod/V8Server/FoxxFeature.cpp
  arangod/V8Server/v8-replication.cpp
  client-tools/Shell/TelemetricsHandler.cpp
  js/apps/system/_admin/aardvark/APP/aardvark.js
  js/apps/system/_admin/aardvark/APP/frontend/js/templates/replicationView.ejs
  js/apps/system/_admin/aardvark/APP/frontend/js/views/replicationView.js
  js/server/leader.js
  scripts/startActiveFailover.sh
  tests/Agency/ActiveFailoverTest.cpp
  tests/CMakeLists.txt
  tests/README.md
Labels: 3 ActiveFailover, cla-signed

#20483 Bugfix/tsan hotbackup bts 1734
  arangod/Cluster/ClusterInfo.cpp
  tsan_arangodb_suppressions.txt
Labels: cla-signed

#20491 Add multi delimiter analyser.
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  tests/js/client/shell/api/analyzer.js
Labels: cla-signed

#20492 Improve Batch Materialize
  arangod/Aql/IndexNode.h
  arangod/Aql/OptimizerRuleBatchMaterializeDocuments.cpp
  tests/js/client/aql/aql-index-batch-materialize.js
Labels: cla-signed

#20490 Temporarily disable search recovery/truncate tests, linked a ticket to fix them
  tests/js/client/recovery/search/view-arangosearch-link-populate-truncate-no-flushthread.js
  tests/js/client/recovery/search/view-arangosearch-link-populate-truncate.js
Labels: cla-signed

#20496 Suppress all data races coming from within V8 and improve build settings
  3rdParty/v8-build/CMakeLists.txt
  CMakeLists.txt
  tsan_arangodb_suppressions.txt
Labels: cla-signed

#19908 [CINFRA-852] Remove insert API from replicated logs
  arangod/Replication2/Methods.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.h
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.cpp
  arangod/Replication2/StateMachines/BlackHole/BlackHoleStateMachine.h
Labels: 9 Ready to Merge, cinfra, cla-signed

#20482 [CINFRA-873] Fix drop index locking order
  arangod/Cluster/DropIndex.cpp
  arangod/Cluster/DropIndex.h
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.h
  arangod/Replication2/StateMachines/Document/DocumentStateErrorHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.h
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.cpp
  arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.h
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.cpp
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.h
  arangod/Replication2/StateMachines/Document/ReplicatedOperationInspectors.h
  arangod/VocBase/Methods/Indexes.cpp
  arangod/VocBase/Methods/Indexes.h
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/ErrorHandlerTest.cpp
  tests/js/client/shell/transaction/shell-transaction.inc
Labels: 1 Bug, cinfra, cla-signed

#20505 Fixed issue BTS-1741
  CHANGELOG
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/common/shell/shell-index-stored-values.js
Labels: cla-signed

#20506 Fixed issue BTS-1741
  CHANGELOG
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/common/shell/shell-index-stored-values.js
Labels: cla-signed

#20504 add missing cluster support for REST compact handler
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterMethods.h
  arangod/RestHandler/RestCollectionHandler.cpp
Labels: cla-signed

#20508 Fixed BTS-1741
  CHANGELOG
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/client/shell/shell-index-stored-values.js
Labels: cla-signed

#20487 FE-416: show error when index creation job has failed on web UI
  js/apps/system/_admin/aardvark/APP/react/src/components/hooks/useJobSync.ts
Labels: 1 Bug, 3 UI, cla-signed

#20500 FE-349: show full error message when moving shards
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/shardsView.js
Labels: 1 Bug, 3 UI, cla-signed

#20498 FE-417: adjust margin for button overlap
  js/apps/system/_admin/aardvark/APP/frontend/scss/_notification.scss
Labels: 1 Bug, 3 UI, cla-signed

#20497 FE-394: fix index stat positioning on web UI
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesView.tsx
Labels: 1 Bug, 3 UI, cla-signed

#20502 FE-322: add readonly check to enable buttons on tables
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/react/src/components/table/ListHeader.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/AnalyzersView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/listCollections/CollectionsTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/listGraphs/GraphsListView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/services/ServicesView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/ViewsList.tsx
Labels: 1 Bug, 3 UI, cla-signed

#20511 [Bug-Fix] fix ui build
  js/apps/system/_admin/aardvark/APP/react/src/components/table/ListHeader.tsx
Labels: cla-signed

#20503 [CINFRA] Let Hotbackup remove ReplicatedLogs and CollectionGroups from current
  arangod/Cluster/ClusterInfo.cpp
Labels: cla-signed

#20507 Disable more Flaky View Recovery tests
  tests/js/client/recovery/search/view-search-alias-populate-truncate-no-flushthread.js
  tests/js/client/recovery/search/view-search-alias-populate-truncate.js
Labels: cla-signed

#20382 versioning support
  CHANGELOG
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/ModificationExecutorHelpers.cpp
  arangod/Aql/ModificationOptions.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/Transaction/Helpers.cpp
  arangod/Transaction/Helpers.h
  arangod/Transaction/Methods.cpp
  arangod/Utils/OperationOptions.cpp
  arangod/Utils/OperationOptions.h
  arangod/V8Server/v8-collection.cpp
  js/client/modules/@arangodb/arango-collection.js
  js/client/modules/@arangodb/arango-database.js
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/V8/v8-globals.cpp
  lib/V8/v8-globals.h
  tests/js/client/shell/shell-versioning.js
Labels: cla-signed

#20499 APM-828: add additional metrics
  CHANGELOG
  Documentation/Metrics/arangodb_collection_leader_reads_total.yaml
  Documentation/Metrics/arangodb_collection_leader_writes_total.yaml
  Documentation/Metrics/arangodb_collection_requests_bytes_read_total.yaml
  Documentation/Metrics/arangodb_collection_requests_bytes_written_total.yaml
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/IResearchViewExecutor.tpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
  arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
  arangod/Graph/SingleServerEdgeCursor.cpp
  arangod/Graph/TraverserCache.cpp
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/Indexes/IndexIterator.cpp
  arangod/Metrics/MetricsFeature.cpp
  arangod/Network/Utils.cpp
  arangod/Network/Utils.h
  arangod/Network/types.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/RocksDBEngine/RocksDBIterators.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/StorageEngine/PhysicalCollection.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
  tests/Graph/TraverserCacheTest.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-per-shard-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-per-shard-per-user-cluster.js
Labels: cla-signed

#20501 APM-828: add additional metrics
  CHANGELOG
  Documentation/Metrics/arangodb_collection_leader_reads_total.yaml
  Documentation/Metrics/arangodb_collection_leader_writes_total.yaml
  Documentation/Metrics/arangodb_collection_requests_bytes_read_total.yaml
  Documentation/Metrics/arangodb_collection_requests_bytes_written_total.yaml
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/IResearchViewExecutor.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/Graph/Cache/RefactoredTraverserCache.cpp
  arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
  arangod/Graph/SingleServerEdgeCursor.cpp
  arangod/Graph/TraverserCache.cpp
  arangod/Indexes/IndexIterator.cpp
  arangod/Metrics/MetricsFeature.cpp
  arangod/Network/Utils.cpp
  arangod/Network/Utils.h
  arangod/Network/types.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/RocksDBEngine/RocksDBIterators.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/StorageEngine/PhysicalCollection.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/Aql/SpliceSubqueryOptimizerRuleTest.cpp
  tests/Graph/TraverserCacheTest.cpp
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-per-shard-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-per-shard-per-user-cluster.js
Labels: cla-signed

#20493 Batch Materialize with Projections
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/ExecutionNode.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MaterializeExecutor.h
  arangod/Aql/OptimizerRuleBatchMaterializeDocuments.cpp
  js/client/modules/@arangodb/testutils/joinHelper.js
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/client/aql/aql-filter-projections.js
  tests/js/client/aql/aql-index-batch-materialize.js
  tests/js/client/aql/aql-index-choice.js
  tests/js/client/aql/aql-optimizer-index-only.js
  tests/js/client/aql/aql-optimizer-indexes-multi.js
  tests/js/client/aql/aql-queries-nested-joins.js
Labels: cla-signed

#19136 [APM-665] RocksDB memory tracking
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: cla-signed

#20512 lower memory usage high water mark multiplier for in-memory cache
  CHANGELOG
  arangod/Cache/CacheOptionsProvider.h
Labels: cla-signed

#20489 APM-828: add more metrics for bytes read/written
  CHANGELOG
  Documentation/Metrics/arangodb_collection_leader_reads_total.yaml
  Documentation/Metrics/arangodb_collection_leader_writes_total.yaml
  Documentation/Metrics/arangodb_collection_requests_bytes_read_total.yaml
  Documentation/Metrics/arangodb_collection_requests_bytes_written_total.yaml
  Documentation/Metrics/arangodb_dump_memory_usage.yaml
  Documentation/Metrics/arangodb_dump_ongoing.yaml
  Documentation/Metrics/arangodb_index_estimates_memory_usage.yaml
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/JoinExecutor.cpp
  arangod/Aql/MaterializeExecutor.cpp
  arangod/Aql/MultiGet.h
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/ClusterMethods.cpp
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/Graph/Cursors/RefactoredSingleServerEdgeCursor.cpp
  arangod/Graph/SingleServerEdgeCursor.cpp
  arangod/Graph/TraverserCache.cpp
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/Indexes/IndexIterator.cpp
  arangod/Metrics/MetricsFeature.cpp
  arangod/Network/Utils.cpp
  arangod/Network/Utils.h
  arangod/Network/types.h
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  arangod/RocksDBEngine/RocksDBIterators.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  arangod/StorageEngine/PhysicalCollection.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-per-shard-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-per-shard-per-user-cluster.js
Labels: cla-signed

#20038 [BTS-1661] Added new graph (vertex related) error code
  CHANGELOG
  arangod/Graph/GraphOperations.cpp
  arangod/Graph/GraphOperations.h
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
  lib/Rest/GeneralResponse.cpp
  tests/js/client/shell/api/api-gharial-spec.js
  tests/js/client/shell/api/multi/general-graph.js
Labels: 9 Review Required, cla-signed

#20515 CINFRA: Test fix: Wait for leadership to be established.
  tests/js/server/replication2/replication2-supervision-wait-for-sync-false.js
Labels: cla-signed

#20513 rather check for foxx than aardvark readyness
  js/client/modules/@arangodb/testutils/instance-manager.js
Labels: cla-signed

#20518 performance optimizations for APM-828
  Documentation/Metrics/arangodb_collection_requests_bytes_read_total.yaml
  Documentation/Metrics/arangodb_collection_requests_bytes_written_total.yaml
  arangod/Metrics/Builder.cpp
  arangod/Metrics/Builder.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
Labels: cla-signed

#20519 performance optimizations for APM-828
  Documentation/Metrics/arangodb_collection_requests_bytes_read_total.yaml
  Documentation/Metrics/arangodb_collection_requests_bytes_written_total.yaml
  arangod/Metrics/Builder.cpp
  arangod/Metrics/Builder.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
Labels: cla-signed

#20520 performance optimizations for APM-828
  Documentation/Metrics/arangodb_collection_requests_bytes_read_total.yaml
  Documentation/Metrics/arangodb_collection_requests_bytes_written_total.yaml
  arangod/Metrics/Builder.cpp
  arangod/Metrics/Builder.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
Labels: cla-signed

#20521 emit a proper error message when profiling on a DB-Server
  js/common/modules/@arangodb/aql/explainer.js
Labels: cla-signed

#20408 Back port index progress visibility
  CHANGELOG
  arangod/Cluster/Action.h
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/ActionBase.h
  arangod/Cluster/EnsureIndex.cpp
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Indexes.cpp
  arangod/VocBase/Methods/Indexes.h
  tests/Maintenance/MaintenanceFeatureMock.h
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/js/client/shell/shell-index.js
Labels: cla-signed

#20523 Update comment about DropShard aborting transactions
  arangod/Replication2/StateMachines/Document/Actor/ApplyEntries.cpp
Labels: 9 Ready to Merge, cinfra, cla-signed

#20534 do not expose hidden indexes by default
  CHANGELOG
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RestServer/TtlFeature.cpp
  tests/js/client/shell/shell-index.js
Labels: 3 API, cla-signed

#20533 Fix data race in actor framework
  lib/Actor/include/Actor/Actor.h
Labels: cla-signed

#20530 improvements for TTL index removal queries
  CHANGELOG
  arangod/RestServer/TtlFeature.cpp
  arangod/RestServer/TtlFeature.h
  tests/js/common/shell/shell-ttl.js
Labels: cla-signed

#20516 [CINFRA] Fail to create databases if automatic syncing is disabled
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/VocBase/Methods/Databases.cpp
  tests/js/client/restart/test-restart-replication2-syncer-thread-off.js
Labels: cinfra, cla-signed

#20537 Report the applied index on followers
  arangod/Replication2/ReplicatedLog/Components/LogFollower.cpp
  arangod/Replication2/ReplicatedLog/types.h
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/StateStatus.h
  lib/Basics/StaticStrings.h
  tests/js/server/replication2/replication2-replicated-state-document-store.js
Labels: cinfra, cla-signed

#20526  [Bug-Fix] Fix comparison between two GeoIndices
  arangod/Indexes/IndexFactory.cpp
Labels: cla-signed

#20525 [3.11] Index progress visibility
  CHANGELOG
  arangod/Cluster/Action.h
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/ActionBase.h
  arangod/Cluster/EnsureIndex.cpp
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/Indexes/Index.cpp
  arangod/Indexes/Index.h
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RestServer/TtlFeature.cpp
  arangod/RestServer/TtlFeature.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBBuilderIndex.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Indexes.cpp
  arangod/VocBase/Methods/Indexes.h
  tests/Maintenance/MaintenanceFeatureMock.h
  tests/Mocks/StorageEngineMock.cpp
  tests/Mocks/StorageEngineMock.h
  tests/js/client/shell/shell-index.js
  tests/js/common/shell/multi/shell-ttl.js
Labels: cla-signed

#20542 allow more optimization for specific COLLECT ops
  arangod/Aql/OptimizerRules.cpp
  tests/js/client/aql/aql-optimizer-collect-into.js
Labels: cla-signed

#20536 FE-425: adds missing Analyzer types on web UI - "multi_delimiter" & "wildcard"
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/Analyzer.types.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/AnalyzersHelpers.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/AnalyzerTypeForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/MultiDelimiterConfig.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/PipelineConfig.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/WildcardConfig.tsx
Labels: 3 UI, cla-signed

#20543 fix metric documentation
  Documentation/Metrics/arangodb_agency_callback_number.yaml
Labels: cla-signed

#20546 clean up more metrics
  Documentation/Metrics/arangodb_agency_cache_callback_number.yaml
  Documentation/Metrics/arangodb_agency_callback_registered_total.yaml
  Documentation/Metrics/arangodb_heartbeat_failures_total.yaml
  Documentation/Metrics/arangodb_heartbeat_send_time_msec.yaml
Labels: cla-signed

#20544 fix metric documentation
  Documentation/Metrics/arangodb_agency_callback_number.yaml
Labels: 3 Documentation, 9 Ready to Merge, 3 Metrics, cla-signed

#20541 Feature/index visibility
  CHANGELOG
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/EnsureIndex.cpp
  arangod/ClusterEngine/ClusterIndex.cpp
  arangod/ClusterEngine/ClusterIndex.h
  arangod/Indexes/Index.cpp
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RestServer/TtlFeature.cpp
  arangod/RestServer/TtlFeature.h
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  tests/js/client/shell/multi/shell-ttl-nocov.js
  tests/js/client/shell/shell-index-visibility.js
Labels: cla-signed

#20549 potentially fix UB
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/ClusterQuery.h
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/Utils/ExecContext.cpp
  arangod/Utils/ExecContext.h
Labels: cla-signed

#20547 potentially fix UB
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/ClusterQuery.h
  arangod/Aql/ExecutionBlockImpl.cpp
  arangod/Aql/ExecutionBlockImpl.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/Utils/ExecContext.cpp
  arangod/Utils/ExecContext.h
Labels: cla-signed

#20545 fix metric documentation
  Documentation/Metrics/arangodb_agency_callback_number.yaml
Labels: 3 Documentation, 9 Ready to Merge, 3 Metrics, cla-signed

#20555 fix inaccurate metrics description
  Documentation/Metrics/arangodb_agency_cache_callback_number.yaml
Labels: cla-signed

#20554 fix inaccurate metrics description
  Documentation/Metrics/arangodb_agency_cache_callback_number.yaml
Labels: 3 Documentation, 3 Metrics, cla-signed

#20550 [bug-fix] Fixed Cluster Failure Points while using authentication
  js/client/bootstrap/modules/internal.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
Labels: cla-signed

#20552 [Bug-Fix][BTS-1747] Windows CI do not produce cores (case: hardKills)
  lib/CrashHandler/CrashHandler.cpp
Labels: cla-signed

#20540 Fixed BTS-1751
  CHANGELOG
  arangod/Aql/Collection.cpp
  arangod/Aql/CollectionAccessingNode.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/ClusterEngine/ClusterSelectivityEstimates.cpp
  arangod/ClusterEngine/ClusterV8Functions.cpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/Pregel/IndexHelpers.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RestServer/TtlFeature.cpp
  arangod/RocksDBEngine/ReplicatedRocksDBTransactionCollection.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.cpp
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/SimpleRocksDBTransactionState.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/StorageEngine/PhysicalCollection.h
  arangod/Transaction/Methods.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Indexes.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  tests/Graph/GraphTestTools.cpp
  tests/Graph/GraphTestTools.h
  tests/IResearch/IResearchFeatureTest.cpp
  tests/IResearch/IResearchLinkTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewDBServerTest.cpp
  tests/IResearch/IResearchViewNodeTest.cpp
  tests/IResearch/IResearchViewTest.cpp
Labels: cla-signed

#20548 potentially fix UB
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/ClusterQuery.h
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  arangod/Utils/ExecContext.cpp
  arangod/Utils/ExecContext.h
  tests/js/common/shell/multi/shell-ttl-nocov.js
Labels: 9 Ready to Merge, cla-signed

#20567 allow changing writeConcern of dependent collections
  CHANGELOG
  arangod/VocBase/LogicalCollection.cpp
  tests/js/client/shell/shell-collection-properties-propagation-cluster.js
Labels: cla-signed

#20522 fix BTS-1733: prevent dropping a collection from a graph
  CHANGELOG
  arangod/Cluster/DropCollection.cpp
  arangod/Graph/GraphManager.cpp
  arangod/Graph/GraphOperations.cpp
  arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/V8Server/v8-collection.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  arangod/VocBase/Methods/UpgradeTasks.cpp
  js/common/bootstrap/errors.js
  js/server/modules/@arangodb/actions.js
  lib/Basics/errors.dat
  tests/js/client/aql/aql-general-graph.js
  tests/js/client/aql/aql-traversal-restrict-graph-collections-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-cluster.js
  tests/js/client/shell/api/multi/general-graph.js
  tests/js/client/shell/shell-general-graph.js
  tests/js/client/shell/shell-transactions.js
Labels: 9 Ready to Merge, cla-signed

#20560 increase test timeout
  tests/js/client/shell/multi/shell-ttl-nocov.js
Labels: cla-signed

#20563 fix a too general assertion
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  tests/js/client/shell/shell-dropped-followers-elcheapo-commit-cluster.js
Labels: 3 - Testing, cla-signed

#19227 Implement a crude bash completion for ./scripts/unittest
  CONTRIBUTING.md
  js/client/modules/@arangodb/testutils/testing.js
  js/client/modules/@arangodb/testutils/unittest.js
  scripts/buildUnittestBashCompletion.bash
  scripts/unittest
Labels: cla-signed

#20570 Fix potential deadlock when dropping indexes in replication2
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
Labels: cla-signed

#20573 Fix issue that prefetch tasks could flood the scheduler queue
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionBlockImpl.tpp
Labels: cla-signed

#20569 fix a too general assertion
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  tests/js/client/shell/shell-dropped-followers-elcheapo-commit-cluster.js
Labels: cla-signed

#20577 RocksDBEngine is only available on dbservers
  arangod/RestHandler/RestDumpHandler.cpp
  arangod/RestHandler/RestDumpHandler.h
  arangod/StorageEngine/EngineSelectorFeature.cpp
  arangod/VocBase/Methods/Databases.cpp
Labels: cla-signed

#20535 FE-320: Validate database name max-length in frontend
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/addDatabase/AddDatabaseModal.tsx
Labels: 3 UI, cla-signed

#20527 Added assertions to narrow down assertion in Search for RocksDBTicks
  arangod/IResearch/IResearchDataStore.cpp
  arangod/IResearch/IResearchDataStore.h
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  tests/js/client/recovery/search/view-arangosearch-link-populate-truncate-no-flushthread.js
  tests/js/client/recovery/search/view-arangosearch-link-populate-truncate.js
  tests/js/client/recovery/search/view-search-alias-populate-truncate-no-flushthread.js
  tests/js/client/recovery/search/view-search-alias-populate-truncate.js
Labels: cla-signed

#20576 [BTS-1766] Fix data race in search init
  arangod/IResearch/IResearchAnalyzerFeature.cpp
Labels: cla-signed
