Repository arangodb/arangodb, pull requests merged in 2024-10, with the labels that each got.

#21323 Register futures in async registry
  arangod/AsyncRegistryServer/Feature.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Statistics/StatisticsWorker.cpp
  lib/ApplicationFeatures/ApplicationServer.cpp
  lib/Async/Registry/promise.cpp
  lib/Async/Registry/promise.h
  lib/Async/Registry/registry.cpp
  lib/Async/Registry/registry.h
  lib/Async/Registry/thread_registry.cpp
  lib/Basics/FutureSharedLock.h
  lib/Futures/CMakeLists.txt
  lib/Futures/include/Futures/Future.h
  lib/Futures/include/Futures/Promise.h
  lib/Futures/include/Futures/SharedState.h
  lib/Futures/include/Futures/coro-helper.h
Labels: cla-signed

#21292 BTS-1950: geo index query stuck
  CHANGELOG
  arangod/RocksDBEngine/RocksDBGeoIndex.cpp
  tests/js/client/aql/aql-geo-misc.js
Labels: cla-signed

#16572 Remove HTTP Batch API and make arangobench --batch-size startup option obsolete
  CHANGELOG
  CONTRIBUTING.md
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/RestHandler/RestBatchHandler.cpp
  arangod/RestHandler/RestBatchHandler.h
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/RestHandler/RestVocbaseBaseHandler.h
  arangod/arangoserver.cmake
  client-tools/Benchmark/BenchFeature.cpp
  client-tools/Benchmark/BenchFeature.h
  client-tools/Benchmark/BenchmarkThread.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Rest/HttpRequest.h
  lib/Rest/HttpResponse.h
  tests/js/client/shell/api/multi/batch.js
Labels: 3 API, cla-signed

#21341 Fuerte Test stack-use-after-free
  tests/Fuerte/ConnectionFailuresTest.cpp
Labels: cla-signed

#21334 fix exit code
  client-tools/Shell/V8ShellFeature.cpp
Labels: cla-signed

#21343 QA-563: fix detection of exit code tests
  js/client/modules/@arangodb/testsuites/arangosh.js
Labels: 3 - Testing, cla-signed

#21344 fix detection of exit code tests (#21343)
  js/client/modules/@arangodb/testsuites/arangosh.js
Labels: 3 - Testing, cla-signed

#21310 QA-553: model tests after java tests
  js/client/modules/@arangodb/arango-transaction.js
  js/client/modules/@arangodb/testsuites/server_permissions.js
  tests/js/client/communication/test-cluster-multi-shard-transaction.js
  tests/js/client/server_parameters/test-streaming-max-transaction-size.js
  tests/js/client/shell/api/cursor.js
  tests/js/client/shell/api/multi/document-read.js
Labels: cla-signed

#21337 Promise Cleanup Thread
  arangod/AsyncRegistryServer/Feature.cpp
  arangod/AsyncRegistryServer/Feature.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Statistics/StatisticsWorker.cpp
  lib/ApplicationFeatures/ApplicationServer.cpp
  lib/Async/Registry/registry.h
  lib/Async/Registry/thread_registry.cpp
  lib/Async/Registry/thread_registry.h
  tests/Async/AsyncTest.cpp
Labels: cla-signed

#21348 ttl deletions are now retried. bind vars should not be moved anymore.
  CHANGELOG
  arangod/RestServer/TtlFeature.cpp
Labels: 3 Index, cla-signed

#21351 Add file descriptor data to telemetrics
  CHANGELOG
  arangod/RestServer/FileDescriptorsFeature.cpp
  arangod/RestServer/FileDescriptorsFeature.h
  arangod/Utils/SupportInfoBuilder.cpp
Labels: 3 Metrics, cla-signed

#21346 Cleanup/remove unneeded code
  client-tools/Shell/ClientFeature.cpp
  js/client/modules/@arangodb/testutils/agency.js
Labels: 3 ActiveFailover, 3 - Testing, cla-signed

#21352 Bug fix tsan garbage collection
  lib/Async/Registry/promise.h
  lib/Async/Registry/thread_registry.cpp
Labels: cla-signed

#21355 add param to disable makedata
  .circleci/base_config.yml
Labels: cla-signed

#21354 hotfix 3.12.2.2
  .circleci/config.yml
  CHANGELOG
  arangod/RestServer/FileDescriptorsFeature.cpp
  arangod/RestServer/FileDescriptorsFeature.h
  arangod/RestServer/TtlFeature.cpp
  arangod/Utils/SupportInfoBuilder.cpp
Labels: cla-signed

#21356 Fix compilation for new libstdc++.
  lib/Basics/ResourceUsage.h
Labels: cla-signed

#21359 Push Down Materialize + Max Projections
  arangod/Aql/Optimizer/Rule/OptimizerRulePushDownLateMaterialization.cpp
  tests/js/client/aql/aql-index-batch-materialize.js
Labels: cla-signed

#21362 ignore warning
  tests/js/client/recovery/check-warnings-exitzero.js
Labels: cla-signed

#21364 Add execution context to async
  arangod/Utils/ExecContext.h
  lib/Async/CMakeLists.txt
  lib/Async/include/Async/async.h
  lib/Async/include/Async/coro-utils.h
  lib/Futures/CMakeLists.txt
  tests/Async/AsyncTest.cpp
Labels: cla-signed

#21319 set san environment for rta as well
  .circleci/base_config.yml
  .circleci/config.yml
  .circleci/generate_config.py
  js/client/modules/@arangodb/testutils/san-file-handler.js
Labels: 3 - Testing, cla-signed

#21367 Docs: Adjust capitalization of UI elements in startup option description
  arangod/Cluster/ClusterFeature.cpp
Labels: cla-signed

#21368 more patient with instrumentation
  tests/js/client/communication/test-cluster-multi-shard-transaction.js
Labels: 3 - Testing, cla-signed

#21369 QA-570: get the last log tick from the leader, and wait untill the followers …
  js/client/modules/@arangodb/testsuites/rta_makedata.js
Labels: cla-signed

#21366 Fix sanitization of dumped data
  CHANGELOG
  arangod/RestHandler/RestDumpHandler.cpp
  arangod/RocksDBEngine/RocksDBDumpContext.cpp
  tests/test-definitions.txt
Labels: 1 Bug, cla-signed

#21371 Agency Potential Out of Bounds Access
  arangod/Agency/State.cpp
Labels: cla-signed

#21370 be more patient on windows too
  tests/js/client/communication/test-cluster-multi-shard-transaction.js
  tests/js/client/communication/test-communication-cluster.js
  tests/js/client/communication/test-kill.js
Labels: cla-signed

#21373 fix timeout handling of spawned processes
  js/client/modules/@arangodb/testutils/process-utils.js
Labels: 3 - Testing, cla-signed

#21372 we know the wintendo looses connectivity checks, ignore it.
  arangod/Scheduler/Scheduler.cpp
Labels: 4 Windows, cla-signed

#21376 Notify syncer threads to shut down.
  arangod/Cluster/ClusterInfo.cpp
Labels: cla-signed

#21378 Update source-location in async registry when suspending or returning asyn<T>
  lib/Async/Registry/promise.cpp
  lib/Async/Registry/promise.h
  lib/Async/include/Async/async.h
  tests/Async/AsyncTest.cpp
  tests/Async/AsyncTestLineNumbers.tpp
Labels: cla-signed

#21380 better messaging of state - try to catch missing waitpid
  .circleci/base_config.yml
  js/client/modules/@arangodb/testutils/client-tools.js
Labels: cla-signed

#21377 Drop Vocbase Specific Metrics [BTS-1972]
  arangod/Metrics/MetricsFeature.cpp
  arangod/Metrics/MetricsFeature.h
  arangod/RestServer/DatabaseFeature.cpp
  arangod/VocBase/VocbaseMetrics.cpp
  arangod/VocBase/VocbaseMetrics.h
  tests/js/client/shell/shell-write-concern-read-only-metric-cluster.js
Labels: cla-signed

#21381 Add suffix to dump tests with vpack
  tests/test-definitions.txt
Labels: 3 ImportExport, 3 - Testing, cla-signed

#21382 Bug fix/missing status external
  js/client/modules/@arangodb/testutils/client-tools.js
Labels: 3 - Testing, cla-signed

#21384 Call setLocale earlier in LanguageFeature [BTS-1792]
  CHANGELOG
  lib/ApplicationFeatures/LanguageFeature.cpp
  lib/ApplicationFeatures/LanguageFeature.h
Labels: cla-signed

#21383 we mustn't clean up if we bail out of here by assert
  js/client/modules/@arangodb/testsuites/recovery_cluster.js
Labels: cla-signed

#21386 if the startup throws, we need to catch and handle this.
  js/client/modules/@arangodb/testsuites/recovery.js
Labels: 3 - Testing, cla-signed

#21385 Call setLocale earlier in LanguageFeature [BTS-1792]
  CHANGELOG
  lib/ApplicationFeatures/LanguageFeature.cpp
  lib/ApplicationFeatures/LanguageFeature.h
Labels: cla-signed

#21387 Set waiter in future functions
  lib/Async/Registry/promise.h
  lib/Async/include/Async/async.h
  lib/Futures/include/Futures/Future.h
  lib/Futures/include/Futures/Promise.h
  lib/Futures/include/Futures/Utilities.h
  lib/Futures/include/Futures/coro-helper.h
  tests/Futures/FutureTest.cpp
Labels: cla-signed

#21350 [FE-450] Avoid unncessary scrollbars when license warning is visible
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/applicationDetailView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentsView.js
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/viewAnalyzer/SingleAnalyzerView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/viewIndex/CollectionIndexDetails.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/viewDatabase/SingleDatabaseView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/QueryViewWrap.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/queryGraph/QueryFullGraphView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/useNavbarHeight.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/ArangoSearchJSONEditor.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/ArangoSearchViewSettings.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/searchAliasView/SearchAliasViewSettings.tsx
Labels: 3 UI, 9 Ready to Merge, cla-signed

#21291 FE-446: primaryKeyCache and primarySortCache options missing for arangosearch Views and inverted indexes
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexFieldsDataEntry.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexPrimarySort.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexStoredValues.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/useCreateInvertedIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/useInvertedIndexJSONSchema.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/View.types.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/ArangoSearchViewForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/SearchJSONSchema.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/linksEditor/LinksDetails.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/linksEditor/useLinkModifiers.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/useArangoSearchFieldsData.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/AddNewViewForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/AdvancedAccordionItem.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/PrimarySortAccordionItem.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/StoredValuesAccordionItem.tsx
Labels: 3 UI, 9 Ready to Merge, 3 ArangoSearch, cla-signed

#21390 Add promise state to registry
  lib/Async/Registry/promise.h
  lib/Async/Registry/thread_registry.cpp
  lib/Async/include/Async/async.h
  lib/Futures/include/Futures/Promise.h
  lib/Futures/include/Futures/SharedState.h
  lib/Futures/include/Futures/coro-helper.h
  tests/Async/AsyncTest.cpp
  tests/Futures/CMakeLists.txt
  tests/Futures/FutureCoroutineTest.cpp
  tests/Futures/FutureTest.cpp
Labels: cla-signed

#21379 Cache in SingleServerProvider
  CHANGELOG
  arangod/Graph/Providers/SingleServerProvider.cpp
  arangod/Graph/Providers/SingleServerProvider.h
  tests/js/client/aql/aql-memory-limit.js
Labels: cla-signed

#21394 Bug fix/join late materialize doc lookup counter
  CHANGELOG
  arangod/Aql/Executor/JoinExecutor.cpp
  tests/js/client/aql/aql-index-join.js
Labels: cla-signed

#21396 increase size of SUT
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#21397 [Async Registry] Iterate over promise snapshot instead of promise ptr
  arangod/AsyncRegistryServer/RestHandler.cpp
  lib/Async/Registry/promise.h
  lib/Async/Registry/registry.h
  lib/Async/Registry/thread_registry.h
  tests/Async/AsyncTest.cpp
  tests/Async/AsyncTestLineNumbers.tpp
  tests/Async/Registry/RegistryTest.cpp
  tests/Async/Registry/ThreadRegistryTest.cpp
  tests/Futures/FutureCoroutineTest.cpp
  tests/Futures/FutureTest.cpp
Labels: cla-signed

#21404 Exclude prefixFields from being added twice.
  arangod/ClusterEngine/ClusterIndex.cpp
Labels: cla-signed

#21400 Feature 3.11/fix agency alive check trigger
  js/client/modules/@arangodb/testutils/agency.js
Labels: 3 - Testing

#21406 Set missing waiter for inner function of future continuations
  lib/Futures/include/Futures/Future.h
  tests/Futures/FutureTest.cpp
Labels: cla-signed

#21407 Rename async registry metrics
  CHANGELOG
  Documentation/Metrics/arangodb_async_active_functions.yaml
  Documentation/Metrics/arangodb_async_active_threads.yaml
  Documentation/Metrics/arangodb_async_functions_total.yaml
  Documentation/Metrics/arangodb_async_promises_total.yaml
  Documentation/Metrics/arangodb_async_ready_for_deletion_functions.yaml
  Documentation/Metrics/arangodb_async_ready_for_deletion_promises.yaml
  Documentation/Metrics/arangodb_async_registered_promises.yaml
  Documentation/Metrics/arangodb_async_registered_threads.yaml
  Documentation/Metrics/arangodb_async_running_threads.yaml
  Documentation/Metrics/arangodb_async_threads_total.yaml
  arangod/AsyncRegistryServer/Feature.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  lib/Async/Registry/Metrics.h
  lib/Async/Registry/thread_registry.cpp
Labels: cla-signed

#21408 Pretty print async-registry REST output
  arangod/AsyncRegistryServer/pretty_printer/README.md
  arangod/AsyncRegistryServer/pretty_printer/pretty_printer.py
Labels: cla-signed

#21389 log count so we can see whats happening
  tests/js/client/communication/test-cluster-multi-shard-transaction.js
Labels: 3 - Testing, cla-signed

#21403 Feature/bigger heap
  .circleci/base_config.yml
  .circleci/config.yml
  .circleci/generate_config.py
  scripts/test/arangosh.py
  scripts/test/async_client.py
  scripts/test/test_config.py
  scripts/test/test_launch_controller.py
  scripts/test/testing_runner.py
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#21409 fix logging string
  scripts/test/arangosh.py
  scripts/test/testing_runner.py
Labels: 3 - Testing, cla-signed

#21410 Feature/async registry improvements
  arangod/AsyncRegistryServer/Feature.cpp
  arangod/AsyncRegistryServer/RestHandler.h
Labels: cla-signed
