Repository arangodb/arangodb, pull requests merged in 2024-05, with the labels that each got.

#20874 Transactions reaching max size
  arangod/RocksDBEngine/Methods/RocksDBTrxBaseMethods.cpp
  tests/js/client/server_parameters/test-streaming-max-transaction-size.js
Labels: cla-signed

#20868 Adding parenthesis around error message
  arangod/VocBase/Properties/CreateCollectionBody.cpp
Labels: cla-signed

#20872 disable non-v8 build in the CI
  .circleci/generate_config.py
Labels: cla-signed

#20882 try to reduce memory usage of subquery chaos test
  js/common/modules/@arangodb/test-generators/subquery-chaos-test.js
  tests/js/client/aql/aql-subquery-chaos-nightly.js
Labels: cla-signed

#20883 try to fix restart test
  tests/js/client/restart/test-restart-replication2-syncer-thread-off.js
Labels: cla-signed

#20885 Maintenance Speedup + Small Refactoring
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
Labels: cla-signed

#20857 Remove superfluous AuthHeader
  arangod/Network/Utils.cpp
  arangod/Network/Utils.h
  arangod/RestHandler/RestAdminLogHandler.cpp
  arangod/RestHandler/RestMetricsHandler.cpp
  arangod/RestHandler/RestUsageMetricsHandler.cpp
  arangod/RestServer/TtlFeature.cpp
  arangod/Utils/SupportInfoBuilder.cpp
  arangod/VocBase/Methods/Queries.cpp
Labels: cla-signed

#20884 Improved the time required to create a new collection into a large database
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
Labels: performance, cla-signed

#20876 Docs: Clarify what at signs do in startup options
  client-tools/Shell/ClientFeature.cpp
Labels: cla-signed

#20890 fix potential "bad optional access" in the supervision
  arangod/Agency/Supervision.cpp
Labels: cla-signed

#20891 fix potential "bad optional access" in the supervision
  arangod/Agency/Supervision.cpp
Labels: cla-signed

#20870 add fixes for socket shutdown
  3rdParty/fuerte/include/fuerte/FuerteLogger.h
  3rdParty/fuerte/include/fuerte/connection.h
  3rdParty/fuerte/include/fuerte/loop.h
  3rdParty/fuerte/include/fuerte/types.h
  3rdParty/fuerte/src/AsioSockets.h
  3rdParty/fuerte/src/GeneralConnection.h
  3rdParty/fuerte/src/H1Connection.cpp
  3rdParty/fuerte/src/H2Connection.cpp
  CHANGELOG
  client-tools/Shell/V8ClientConnection.cpp
  lib/Logger/LoggerFeature.cpp
  scripts/startLocalCluster.sh
  tests/Fuerte/ConnectionFailuresTest.cpp
Labels: cla-signed

#20897 reduce amount of data in test
  tests/js/client/aql/aql-arangosearch-constrained-sort-optimization.inc
Labels: cla-signed

#20899 [3.11] Fix move assignments in boost asio
  3rdParty/boost/1.78.0/boost/asio/ssl/detail/engine.hpp
  3rdParty/boost/1.78.0/boost/asio/ssl/detail/impl/engine.ipp
  3rdParty/boost/1.78.0/boost/asio/ssl/detail/stream_core.hpp
Labels: cla-signed

#20900 fix protocol confusion
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/H2CommTask.h
  tests/js/client/shell/api-job-different-protocols.js
Labels: cla-signed

#20888 fix invalid vptr access
  arangod/Replication/InitialSyncer.cpp
Labels: cla-signed

#20896 try to fix restart test
  arangod/VocBase/Methods/Upgrade.cpp
  tests/js/client/restart/test-restart-replication2-syncer-thread-off.js
Labels: cla-signed

#20792 Feature/disable tests for coverage
  .circleci/base_config.yml
  js/client/modules/@arangodb/testutils/client-tools.js
  scripts/docker/build/linux/Dockerfile.x86-64
  tests/js/client/aql/aql-complex.js
  tests/js/client/aql/aql-view-arangosearch-parallelisation-nocov.js
  tests/js/client/shell/shell-index-visibility-nocov.js
  tests/js/client/shell/shell-med-queue-blocked-cluster-nocov.js
  tests/js/client/wal_cleanup/wal-cluster-nocov.js
Labels: 3 - Testing, cla-signed

#20902 fix potential issue during transaction manager shutdown
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Transaction/ManagerFeature.cpp
  arangod/Transaction/ManagerFeature.h
  lib/Logger/LogThread.cpp
Labels: cla-signed

#20911 retry query shutdown in case no connection can be established
  arangod/Aql/Query.cpp
Labels: cla-signed

#20913 retry query shutdown in case no connection can be established
  CHANGELOG
  arangod/Aql/Query.cpp
Labels: cla-signed

#20912 retry query shutdown in case no connection can be established
  CHANGELOG
  arangod/Aql/Query.cpp
Labels: cla-signed

#20894 FE-448: auto-repair collection JSON on save
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/documentView.js
Labels: 1 Bug, 3 UI, cla-signed

#20871 add fixes for socket shutdown
  3rdParty/boost/1.78.0/boost/asio/ssl/detail/engine.hpp
  3rdParty/boost/1.78.0/boost/asio/ssl/detail/impl/engine.ipp
  3rdParty/boost/1.78.0/boost/asio/ssl/detail/stream_core.hpp
  3rdParty/fuerte/include/fuerte/FuerteLogger.h
  3rdParty/fuerte/include/fuerte/connection.h
  3rdParty/fuerte/include/fuerte/loop.h
  3rdParty/fuerte/include/fuerte/types.h
  3rdParty/fuerte/src/AsioSockets.h
  3rdParty/fuerte/src/GeneralConnection.h
  3rdParty/fuerte/src/H1Connection.cpp
  3rdParty/fuerte/src/H2Connection.cpp
  CHANGELOG
  js/client/modules/@arangodb/testsuites/fuerte.js
  lib/Logger/LoggerFeature.cpp
  tests/Fuerte/CMakeLists.txt
  tests/Fuerte/ConnectionFailuresTest.cpp
  tests/Fuerte/ConnectionTest.h
  tests/Fuerte/main.cpp
  tests/test-definitions.txt
Labels: cla-signed

#20901 further fixes for socket shutdown
  3rdParty/boost/1.78.0/boost/asio/ssl/detail/engine.hpp
  3rdParty/boost/1.78.0/boost/asio/ssl/detail/impl/engine.ipp
  3rdParty/boost/1.78.0/boost/asio/ssl/detail/stream_core.hpp
  3rdParty/fuerte/include/fuerte/connection.h
  3rdParty/fuerte/include/fuerte/types.h
  3rdParty/fuerte/src/AsioSockets.h
  3rdParty/fuerte/src/GeneralConnection.h
  ARANGO-VERSION
  CHANGELOG
  CMakeLists.txt
  client-tools/Shell/V8ClientConnection.cpp
  js/apps/system/_admin/aardvark/APP/api-docs.json
  js/client/modules/@arangodb/testsuites/fuerte.js
  tests/Fuerte/ConnectionFailuresTest.cpp
  tests/Fuerte/ConnectionTest.h
  tests/Fuerte/main.cpp
  tests/test-definitions.txt
Labels: cla-signed

#20877 add fixes for socket shutdown
  3rdParty/fuerte/include/fuerte/FuerteLogger.h
  3rdParty/fuerte/include/fuerte/connection.h
  3rdParty/fuerte/include/fuerte/loop.h
  3rdParty/fuerte/include/fuerte/types.h
  3rdParty/fuerte/src/AsioSockets.h
  3rdParty/fuerte/src/GeneralConnection.h
  3rdParty/fuerte/src/H1Connection.cpp
  3rdParty/fuerte/src/H2Connection.cpp
  CHANGELOG
  js/client/modules/@arangodb/testsuites/fuerte.js
  lib/Logger/LoggerFeature.cpp
  tests/Fuerte/ConnectionFailuresTest.cpp
  tests/Fuerte/ConnectionTest.h
  tests/Fuerte/main.cpp
  tests/test-definitions.txt
Labels: cla-signed

#20925 prevent parallel index creation thread from hanging
  CHANGELOG
Labels: cla-signed

#20917 allow larger database ids (larger than UINT32_MAX)
  arangod/Cluster/HeartbeatThread.cpp
Labels: cla-signed

#20924 prevent parallel index creation thread from hanging
  CHANGELOG
Labels: cla-signed

#20922 remove artificial limit of 8 for the number of ClusterComm IO threads
  3rdParty/fuerte/src/loop.cpp
  arangod/Cluster/ClusterFeature.cpp
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/Network/ConnectionPool.cpp
  arangod/Network/ConnectionPool.h
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
Labels: cla-signed

#20921 fix a race between collection deletion and revision tree persistence
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: cla-signed

#20920 add code comments
  arangod/Cluster/HeartbeatThread.cpp
  tests/js/client/load-balancing/load-balancing-async-auth-cluster.js
  tests/js/client/load-balancing/load-balancing-async-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-cursor-auth-cluster.js
  tests/js/client/load-balancing/load-balancing-cursor-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-tasks-auth-cluster.js
  tests/js/client/load-balancing/load-balancing-tasks-noauth-cluster.js
  tests/js/client/load-balancing/load-balancing-transactions-auth-cluster.js
  tests/js/client/load-balancing/load-balancing-transactions-noauth-cluster.js
Labels: cla-signed

#20919 fix logical error in test assertion
  tests/Fuerte/ConnectionFailuresTest.cpp
Labels: cla-signed

#20926 fix a false positive report of Merkle tree differences
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: 3 - Testing, cla-signed

#20927 allow larger database ids (larger than UINT32_MAX)
  arangod/Cluster/HeartbeatThread.cpp
Labels: cla-signed

#20910 QA-536: move san file handling in its own class
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/process-utils.js
  js/client/modules/@arangodb/testutils/san-file-handler.js
Labels: cla-signed

#20929 Wait for ClusterInfo to catch up after creating a collection
  arangod/Cluster/ClusterCollectionMethods.cpp
Labels: cla-signed

#20739 small optimizations for AqlItemBlock::toVelocyPack()
  arangod/Aql/AqlItemBlock.cpp
  arangod/Aql/AqlItemBlock.h
  arangod/Aql/AqlValue.cpp
  arangod/Aql/Executor/RemoteExecutor.cpp
  arangod/Transaction/Methods.cpp
  lib/Basics/VelocyPackHelper.cpp
  lib/Basics/VelocyPackHelper.h
  lib/Rest/HttpResponse.cpp
Labels: cla-signed

#20928 Improved error messages returned by getLeader(s)ForShard
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Network/Utils.cpp
  lib/Basics/ReadLocker.h
Labels: cla-signed

#20898 QA-536: move san file handling in its own class
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/process-utils.js
  js/client/modules/@arangodb/testutils/san-file-handler.js
Labels: cla-signed

#20931 improve debug logging for hot backup locking
  arangod/Cluster/ClusterMethods.cpp
Labels: cla-signed

#20936 add debug information for spuriously failing test
  tests/js/client/shell/shell-index.js
Labels: 3 - Testing, cla-signed

#20934 fix test false positive about Merkle tree differences
  tests/js/client/chaos/test-deadlock-cluster.js
Labels: 3 - Testing, cla-signed

#20915 ConnectionPool without MetricsFeature
  arangod/Cluster/ClusterFeature.cpp
  arangod/Network/ConnectionPool.cpp
  arangod/Network/ConnectionPool.h
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
  arangod/RestServer/arangod.cpp
  tests/AsyncAgencyComm/AsyncAgencyCommTest.cpp
  tests/IResearch/IResearchAnalyzerFeatureTest.cpp
  tests/Mocks/Servers.cpp
  tests/Network/ConnectionPoolTest.cpp
  tests/Network/MethodsTest.cpp
Labels: cla-signed

#20932 Remove server dependency of Logger and Thread
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/GeneralServer/IoContext.cpp
  lib/Basics/Thread.cpp
  lib/Basics/Thread.h
  lib/Logger/LogThread.cpp
  lib/Logger/LogThread.h
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
  lib/Logger/LoggerFeature.cpp
  tests/main.cpp
Labels: cla-signed

#20935 improve debug logging for hot backup locking
  arangod/Cluster/ClusterMethods.cpp
Labels: cla-signed

#20940 Bug fix 3.11/hotbackup restore analyzers
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  tests/js/client/shell/shell-hotbackup-cluster-nonwindows.js
Labels: 1 Bug, cla-signed

#20878 FE-447: make query spotlight search case-insensitive
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/query/editor/QuerySpotlight.tsx
Labels: 1 Bug, 3 UI, cla-signed

#20933 fix false positive about Merkle tree differences
  tests/js/client/chaos/test-deadlock-cluster.js
Labels: cla-signed

#20938 honor `maxProjections` options for MaterializeNode projections
  arangod/Aql/ExecutionNode/DocumentProducingNode.cpp
  arangod/Aql/ExecutionNode/GraphNode.cpp
  arangod/Aql/ExecutionNode/GraphNode.h
  arangod/Aql/ExecutionNode/MaterializeRocksDBNode.cpp
  arangod/Aql/ExecutionNode/MaterializeRocksDBNode.h
  arangod/Aql/ExecutionNode/TraversalNode.cpp
  arangod/Aql/ExecutionNode/TraversalNode.h
  arangod/Aql/ExecutionNode/WindowNode.cpp
  arangod/Aql/ExecutionNode/WindowNode.h
  arangod/Aql/OptimizerRuleBatchMaterializeDocuments.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/js/client/aql/aql-projections.js
Labels: cla-signed

#20937 BTS-1868: fix TSan errors
  arangod/Auth/TokenCache.cpp
  arangod/Auth/UserManager.h
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/RestClusterHandler.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/GeneralServer/AuthenticationFeature.cpp
  arangod/GeneralServer/AuthenticationFeature.h
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/Network/ConnectionPool.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
  arangod/Replication/ReplicationApplierConfiguration.cpp
  arangod/Replication/Syncer.cpp
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestHandler/RestAuthHandler.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestShutdownHandler.cpp
  arangod/RestHandler/RestUsersHandler.cpp
  arangod/RestServer/BootstrapFeature.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/UpgradeFeature.cpp
  arangod/RestServer/VocbaseContext.cpp
  arangod/Transaction/Manager.cpp
  arangod/V8Server/v8-users.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  tests/IResearch/IResearchAnalyzerFeatureTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/RestHandler/RestAnalyzerHandlerTest.cpp
  tests/RestHandler/RestUsersHandlerTest.cpp
  tests/RestHandler/RestViewHandlerTest.cpp
  tests/V8Server/V8AnalyzersTest.cpp
  tests/V8Server/V8UsersTest.cpp
  tests/V8Server/V8ViewsTest.cpp
Labels: cla-signed

#20941 make latest indexes visible
  arangod/RestHandler/RestIndexHandler.cpp
Labels: cla-signed

#20939 BTS-1868: fix TSan errors
  arangod/Auth/TokenCache.cpp
  arangod/Auth/UserManager.h
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/RestClusterHandler.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/GeneralServer/AuthenticationFeature.cpp
  arangod/GeneralServer/AuthenticationFeature.h
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/GeneralServer/VstCommTask.cpp
  arangod/Network/ConnectionPool.cpp
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
  arangod/Replication/ReplicationApplierConfiguration.cpp
  arangod/Replication/Syncer.cpp
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestHandler/RestAuthHandler.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestShutdownHandler.cpp
  arangod/RestHandler/RestUsersHandler.cpp
  arangod/RestServer/BootstrapFeature.cpp
  arangod/RestServer/DatabaseFeature.cpp
  arangod/RestServer/UpgradeFeature.cpp
  arangod/RestServer/VocbaseContext.cpp
  arangod/Transaction/Manager.cpp
  arangod/V8Server/v8-users.cpp
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Databases.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  tests/IResearch/IResearchAnalyzerFeatureTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/RestHandler/RestAnalyzerHandlerTest.cpp
  tests/RestHandler/RestUsersHandlerTest.cpp
  tests/RestHandler/RestViewHandlerTest.cpp
  tests/V8Server/V8AnalyzersTest.cpp
  tests/V8Server/V8UsersTest.cpp
  tests/V8Server/V8ViewsTest.cpp
Labels: cla-signed

#20942 make latest indexes visible
  arangod/RestHandler/RestIndexHandler.cpp
Labels: cla-signed

#20943 skip fuerte timeout tests on Windows
  tests/Fuerte/ConnectionTimeoutsTest.cpp
Labels: 4 Windows, 3 - Testing, cla-signed

#20944 Remove artificial upper bounds for IO threads configuration
  CHANGELOG
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/Network/NetworkFeature.cpp
Labels: cla-signed

#20947 Bug fix 3.11/hotbackup community test
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  tests/js/client/shell/shell-hotbackup-cluster-nonwindows.js
Labels: 1 Bug, cla-signed

#20952 Fix potential race in collectRebalanceInformation
  CHANGELOG
  arangod/RestHandler/RestAdminClusterHandler.cpp
Labels: cla-signed

#20949 try to fix more shutdown errors
  arangod/Cluster/ClusterFeature.cpp
  arangod/Network/ConnectionPool.cpp
  arangod/Network/NetworkFeature.cpp
Labels: cla-signed

#20951 pass database name in callback guard
  arangod/Transaction/Manager.cpp
Labels: cla-signed

#20954 add assertions to detect nullptr derefs in ShardingInfo
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/Sharding/ShardingInfo.cpp
Labels: cla-signed

#20956 remove code from tests that checks for Linux platform
  tests/js/client/recovery/check-warnings-exitzero.js
  tests/js/client/shell/shell-arango-secure-installation-noncluster.js
  tests/js/server/recovery/crash-handler-assert-noinstr.js
  tests/js/server/recovery/crash-handler-terminate-active-noinstr.js
  tests/js/server/recovery/crash-handler-terminate-noinstr.js
Labels: cla-signed

#20955 turn an ADB_PROD_ASSERT into an exception
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Properties/ClusteringMutableProperties.cpp
  arangod/VocBase/vocbase.cpp
  tests/Mocks/Servers.cpp
  tests/js/client/shell/shell-one-shard.js
Labels: cla-signed

#20950 BugFix: hotbackup restore analyzers
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterMethods.cpp
  tests/js/client/shell/shell-hotbackup-cluster-nonwindows.js
Labels: cla-signed

#20960 OASIS-25823
  CHANGELOG
  arangod/Aql/Executor/IndexExecutor.cpp
  tests/js/client/aql/aql-index-batch-materialize.js
Labels: cla-signed

#20963 Add new API to reset log levels
  CHANGELOG
  arangod/RestHandler/RestAdminLogHandler.cpp
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
  tests/js/client/shell/multi/shell-admin-log.js
Labels: cla-signed

#20964 Add new API to reset log levels
  CHANGELOG
  arangod/RestHandler/RestAdminLogHandler.cpp
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
  tests/js/client/shell/multi/shell-admin-log.js
Labels: cla-signed

#20968 Bug fix 3.11.7.4/detach get responsible server
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: 3 Cluster, cla-signed

#20962 Feature 3.11/use posix spawn
  CHANGELOG
  lib/Basics/process-utils.cpp
Labels: cla-signed

#20961 Use posix_spawn instead of fork+exec
  CHANGELOG
  lib/Basics/process-utils.cpp
Labels: cla-signed

#20965 Use posix_spawn instead of fork+exec
  CHANGELOG
  lib/Basics/process-utils.cpp
Labels: cla-signed

#20974 improve error message for failed `posix_spawn` calls
  lib/Basics/process-utils.cpp
Labels: cla-signed

#20440 Add promtool and net-tools to test container
  .circleci/base_config.yml
  scripts/docker/test/arangodb-test.Dockerfile
  scripts/docker/test/build-manifest.sh
  tests/js/client/shell/shell-promtool-cluster.js
  tests/js/client/shell/shell-promtool.js
Labels: cla-signed

#20972 ENTRIES for AQL
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Function/ObjectFunctions.cpp
  arangod/Aql/Functions.h
  tests/js/client/aql/aql-functions.js
Labels: cla-signed

#20957 Limit hot backup progress reporting frequency
  CHANGELOG
Labels: cla-signed

#20976 BTS-1775: disable checking of view counts in chaos test
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: cla-signed

#20970 fix failing index test that queries in-progress indexes
  arangod/RestHandler/RestIndexHandler.cpp
Labels: cla-signed

#20958 Limit hot backup progress reporting frequency
  CHANGELOG
Labels: cla-signed

#20979 enable TCP_NODELAY on fuerte tcp connections
  3rdParty/fuerte/include/fuerte/FuerteLogger.h
  3rdParty/fuerte/src/AsioSockets.h
  arangod/Agency/AsyncAgencyComm.h
  arangod/Aql/Condition.cpp
  arangod/Aql/Executor/RemoteExecutor.cpp
  arangod/Aql/Executor/RemoteExecutor.h
  arangod/Network/ClusterUtils.h
  lib/Logger/LoggerFeature.cpp
Labels: cla-signed

#20980 Aardvark: Update list of known AQL functions for code highlighting
  js/apps/system/_admin/aardvark/APP/react/public/assets/src/mode-aql.js
Labels: 3 Documentation, 3 UI, cla-signed

#20959 try to fix more shutdown errors
  3rdParty/fuerte/include/fuerte/loop.h
  3rdParty/fuerte/src/loop.cpp
  arangod/Cluster/ClusterFeature.cpp
  arangod/Network/ConnectionPool.cpp
  arangod/Network/ConnectionPool.h
  arangod/Network/NetworkFeature.cpp
Labels: cla-signed
