Repository arangodb/arangodb, pull requests merged in 2024-02, with the labels that each got.

#20575 CINFRA: Per Shard Metrics for Replication2
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateHandlersFactory.h
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshot.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.cpp
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.cpp
  arangod/Replication2/StateMachines/Document/ReplicatedOperation.h
  arangod/Replication2/StateMachines/Document/ReplicatedOperationInspectors.h
  arangod/Transaction/Methods.cpp
  arangod/Transaction/Methods.h
  js/client/modules/@arangodb/test-helper.js
  js/common/modules/@arangodb/testutils/document-state-helper.js
  js/common/modules/@arangodb/testutils/replicated-logs-helper.js
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/DocumentStateMachineTest.h
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/ErrorHandlerTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/FollowerTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/LeaderTest.cpp
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/TransactionHandlerTest.cpp
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-cluster.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
Labels: cla-signed

#20422 [3.10] Fix: avoid duplicate link metrics
  CHANGELOG
  arangod/IResearch/IResearchInvertedIndex.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  arangod/Metrics/MetricsFeature.cpp
  tests/IResearch/IResearchLinkTest.cpp
Labels: cla-signed

#20539 Fixed BTS-1751
  CHANGELOG
  arangod/Aql/Collection.cpp
  arangod/Aql/CollectionAccessingNode.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/ClusterEngine/ClusterSelectivityEstimates.cpp
  arangod/ClusterEngine/ClusterV8Functions.cpp
  arangod/IResearch/IResearchAnalyzerFeature.cpp
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchLinkHelper.cpp
  arangod/IResearch/IResearchRocksDBRecoveryHelper.cpp
  arangod/Pregel/IndexHelpers.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RestServer/TtlFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBIncrementalSync.cpp
  arangod/RocksDBEngine/RocksDBIndexCacheRefillFeature.cpp
  arangod/RocksDBEngine/RocksDBMetadata.cpp
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  arangod/RocksDBEngine/RocksDBRecoveryManager.cpp
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
  arangod/RocksDBEngine/SimpleRocksDBTransactionState.cpp
  arangod/StorageEngine/PhysicalCollection.cpp
  arangod/StorageEngine/PhysicalCollection.h
  arangod/Transaction/Methods.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Indexes.cpp
  arangod/VocBase/Methods/UpgradeTasks.cpp
  tests/Graph/GraphTestTools.h
  tests/IResearch/IResearchFeatureTest.cpp
  tests/IResearch/IResearchLinkTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewDBServerTest.cpp
  tests/IResearch/IResearchViewNodeTest.cpp
  tests/IResearch/IResearchViewTest.cpp
Labels: 9 Ready to Merge, cla-signed

#20559 increase test timeout
  tests/js/common/shell/shell-ttl-nocov.js
Labels: 9 Ready to Merge, cla-signed

#20562 fix a too general assertion
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  tests/js/client/shell/shell-dropped-followers-elcheapo-commit-cluster.js
Labels: 9 Ready to Merge, 3 - Testing, cla-signed

#20580 [CINFRA] Handle shutdown gracefully
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
Labels: cinfra, cla-signed

#20551 FE-428: add null/undefined handling for rows in query table result
  js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryTableView.tsx
Labels: 1 Bug, 3 UI, cla-signed

#20571 FE-425: fix ngramSize input type for wildcard analyzer
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/forms/WildcardConfig.tsx
Labels: 1 Bug, 3 UI, cla-signed

#20566 [CINFRA] Collection Status
  arangod/Replication2/Methods.cpp
  arangod/Replication2/Methods.h
  arangod/RestHandler/RestLogHandler.cpp
  arangod/RestHandler/RestLogHandler.h
  tests/js/server/replication2/replication2-replicated-state-http-api-cluster.js
Labels: cinfra, cla-signed

#20583 Test Only Fix: ReplicationVersion in scripts/unittests
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/testing.js
Labels: cla-signed

#20572 FE-409: deletion success toast in views
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/applicationDetailView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/settingsView.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/userView.js
  js/apps/system/_admin/aardvark/APP/react/src/theme/ChakraCustomProvider.tsx
  js/apps/system/_admin/aardvark/APP/react/src/utils/useCustomHashMatch.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/addAnalyzer/AddAnalyzerModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/viewAnalyzer/DeleteAnalyzerModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/viewAnalyzer/SingleAnalyzerView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreateIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/useDeleteIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/viewIndex/CollectionIndexDetails.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/addDatabase/AddDatabaseModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/databases/viewDatabase/DeleteDatabaseModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/users/addUser/AddUserModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/editView/EditViewHeader.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/editView/SingleViewView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/editView/useFetchViewProperties.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/ViewsTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/useAddView.ts
Labels: 1 Bug, 3 UI, cla-signed

#20584 nightly fix startup
  tests/js/client/server_parameters/test-early-connections-noncluster.js
Labels: cla-signed

#20578 reduce cluster-internal traffic
  CHANGELOG
  arangod/Agency/AgencyComm.cpp
  arangod/Agency/Agent.cpp
  arangod/Agency/Agent.h
  arangod/Agency/AgentCallback.cpp
  arangod/Agency/AsyncAgencyComm.cpp
  arangod/Agency/AsyncAgencyComm.h
  arangod/Agency/RestAgencyPrivHandler.cpp
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/ServerState.cpp
  arangod/Cluster/ServerState.h
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/Network/Methods.cpp
  arangod/Network/Methods.h
  arangod/Network/Utils.cpp
  arangod/StorageEngine/HealthData.cpp
  arangod/StorageEngine/HealthData.h
  tests/CMakeLists.txt
  tests/Cluster/ServerStateTest.cpp
  tests/js/client/shell/multi/shell-http-headers-cluster.js
  tests/js/client/shell/multi/shell-http-headers-noncluster.js
Labels: cla-signed

#20582 Fixed check if a Shard is a leader for Replication2 in TTL BG thread
  arangod/RestServer/TtlFeature.cpp
  tests/js/client/shell/multi/shell-ttl-nocov.js
Labels: cla-signed

#20585 [CINFRA] Adjust replication2 test
  tests/js/client/restart/test-restart-replication2-syncer-thread-off.js
Labels: cinfra, cla-signed

#20421 [3.11] Fix: avoid duplicate link metrics
  CHANGELOG
  arangod/IResearch/IResearchInvertedClusterIndex.cpp
  arangod/IResearch/IResearchLink.cpp
  arangod/IResearch/IResearchLinkCoordinator.cpp
  arangod/IResearch/IResearchRocksDBInvertedIndex.cpp
  arangod/Metrics/MetricsFeature.cpp
  tests/IResearch/IResearchLinkTest.cpp
Labels: 3 Metrics, cla-signed

#20587 clean up some outdated documentation
  CONTRIBUTING.md
Labels: cla-signed

#20581 [CINFRA-885] Replicate CreateIndex while holding the exclusive collection lock
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateTransactionHandler.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
Labels: cinfra, cla-signed

#20590 fix wrong certificate path in startup scripts
  scripts/startActiveFailover.sh
  scripts/startLocalCluster.sh
  scripts/startStandAloneAgency.sh
Labels: 3 - Testing, cla-signed

#20591 fix wrong certificate path in startup scripts
  scripts/startLocalCluster.sh
  scripts/startStandAloneAgency.sh
Labels: cla-signed

#20593 [CINFRA] Metrics replication2 flaky test
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-per-user-cluster.js
Labels: cinfra, cla-signed

#20568 optional compression for cluster-internal traffic
  3rdParty/fuerte/include/fuerte/types.h
  3rdParty/fuerte/src/message.cpp
  3rdParty/fuerte/src/types.cpp
  CHANGELOG
  arangod/Agency/Agent.cpp
  arangod/Agency/AsyncAgencyComm.cpp
  arangod/Agency/Constituent.cpp
  arangod/Agency/Inception.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/Network/Methods.h
  arangod/Network/NetworkFeature.cpp
  arangod/Network/NetworkFeature.h
  etc/testing/arangod-common.conf
  lib/Basics/EncodingUtils.cpp
  lib/Basics/EncodingUtils.h
  lib/Basics/StaticStrings.cpp
  lib/Basics/StaticStrings.h
  lib/Basics/StringBuffer.h
  lib/Basics/StringBufferAdvanced.cpp
  lib/CMakeLists.txt
  lib/Rest/CommonDefines.h
  lib/Rest/GeneralResponse.h
  lib/Rest/HttpRequest.cpp
  lib/Rest/HttpResponse.cpp
  lib/Rest/HttpResponse.h
  lib/SimpleHttpClient/SimpleHttpClient.cpp
  lib/SimpleHttpClient/SimpleHttpResult.cpp
  tests/IResearch/RestHandlerMock.cpp
  tests/IResearch/RestHandlerMock.h
Labels: cla-signed

#20602 [CINFRA] Index Creation Error
  arangod/Replication2/StateMachines/Document/DocumentStateErrorHandler.cpp
  arangod/RocksDBEngine/RocksDBCollection.cpp
Labels: cinfra, cla-signed

#20597 [3.10] analyzers restored after hot restore
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  tests/js/server/dump/dump-cluster.js
Labels: 3 ImportExport, 3 ArangoSearch, cla-signed

#20596 [3.11] analyzers restored after hot restore
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  tests/js/server/dump/dump-cluster.js
Labels: 3 ImportExport, 3 ArangoSearch, cla-signed

#20594 Update test image to ubuntu 23.10
  .circleci/base_config.yml
  .circleci/build_test_image.yml
  .circleci/config.yml
  scripts/docker/test/arangodb-test.Dockerfile
  scripts/docker/test/build-image.sh
  scripts/docker/test/build-image_arm64.sh
  scripts/docker/test/build-image_x86-64.sh
  scripts/docker/test/build-manifest.sh
  scripts/docker/test/determine-tag.sh
Labels: cla-signed

#20595 improve debuggability of collection-counts test
  arangod/Agency/AddFollower.cpp
  arangod/Sharding/ShardDistributionReporter.cpp
  js/client/modules/@arangodb/test-helper.js
  js/client/modules/@arangodb/testutils/testing.js
  tests/js/client/shell/shell-collection-counts-cluster.js
Labels: cla-signed

#20600 enable debug logging for chaos tests
  tests/js/client/chaos/test-chaos-load-common.inc
Labels: cla-signed

#20598 analyzers restored after hot restore
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  tests/js/client/dump/dump-cluster.js
Labels: cla-signed

#20605 [BTS-1782] Fix view restore
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/Search.cpp
  arangod/IResearch/Search.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/VocBase/LogicalDataSource.cpp
  arangod/VocBase/LogicalDataSource.h
  arangod/VocBase/LogicalView.cpp
  arangod/VocBase/LogicalView.h
  tests/IResearch/IResearchLinkCoordinatorTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/RestHandler/RestUsersHandlerTest.cpp
  tests/RestHandler/RestViewHandlerTest.cpp
  tests/Utils/CollectionNameResolverTest.cpp
  tests/V8Server/V8UsersTest.cpp
  tests/V8Server/V8ViewsTest.cpp
  tests/VocBase/LogicalDataSourceTest.cpp
  tests/VocBase/LogicalViewTest.cpp
  tests/VocBase/VocbaseTest.cpp
Labels: 3 ImportExport, 3 ArangoSearch, cla-signed

#20606 BTS-1783
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: cla-signed

#20608 fix TSan errors from BTS-1778
  arangod/Aql/ExecutionBlockImpl.tpp
Labels: cla-signed

#20615 fix missing analyzers after hot restore
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  tests/js/server/dump/dump-cluster.js
Labels: 3 ImportExport, 3 ArangoSearch, cla-signed

#20603 CINFRA: Hot Restore BugFix Part 2
  arangod/Agency/AgencyStrings.h
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Replication2/ReplicatedLog/Supervision.cpp
Labels: cla-signed

#20611 Fix compilation of Replication2 unit tests on non-maintainer builds
  tests/Replication2/ReplicatedState/StateMachines/DocumentState/SnapshotTest.cpp
Labels: cla-signed

#20614 [BTS-1782] Fix view restore 3.11
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/Search.cpp
  arangod/IResearch/Search.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/VocBase/LogicalDataSource.cpp
  arangod/VocBase/LogicalDataSource.h
  arangod/VocBase/LogicalView.cpp
  arangod/VocBase/LogicalView.h
  tests/IResearch/IResearchLinkCoordinatorTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/RestHandler/RestUsersHandlerTest.cpp
  tests/RestHandler/RestViewHandlerTest.cpp
  tests/Utils/CollectionNameResolverTest.cpp
  tests/V8Server/V8UsersTest.cpp
  tests/V8Server/V8ViewsTest.cpp
  tests/VocBase/LogicalDataSourceTest.cpp
  tests/VocBase/LogicalViewTest.cpp
  tests/VocBase/VocbaseTest.cpp
Labels: 3 ImportExport, 3 ArangoSearch, cla-signed

#20613 [BTS-1782] Fix view restore 3.10
  arangod/IResearch/IResearchFeature.cpp
  arangod/IResearch/IResearchView.cpp
  arangod/IResearch/IResearchView.h
  arangod/IResearch/IResearchViewCoordinator.cpp
  arangod/IResearch/IResearchViewCoordinator.h
  arangod/IResearch/Search.cpp
  arangod/IResearch/Search.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/VocBase/LogicalDataSource.cpp
  arangod/VocBase/LogicalDataSource.h
  arangod/VocBase/LogicalView.cpp
  arangod/VocBase/LogicalView.h
  tests/IResearch/IResearchLinkCoordinatorTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/IResearch/IResearchViewTest.cpp
  tests/RestHandler/RestUsersHandlerTest.cpp
  tests/RestHandler/RestViewHandlerTest.cpp
  tests/Utils/CollectionNameResolverTest.cpp
  tests/V8Server/V8UsersTest.cpp
  tests/V8Server/V8ViewsTest.cpp
  tests/VocBase/LogicalDataSourceTest.cpp
  tests/VocBase/LogicalViewTest.cpp
  tests/VocBase/VocbaseTest.cpp
Labels: 3 ImportExport, 3 ArangoSearch, cla-signed

#20362 [3.11] Fix BTS-1636
  arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.cpp
  arangod/Graph/Enumerators/WeightedTwoSidedEnumerator.h
  arangod/Graph/PathManagement/PathValidator.cpp
  arangod/Graph/algorithm-aliases.h
  tests/Graph/GraphMockProviderInstances.cpp
  tests/Graph/WeightedShortestPathTest.cpp
  tests/js/server/aql/aql-graph-k-shortest-path.js
  tests/js/server/aql/aql-graph-shortest-path-regression.js
Labels: cla-signed

#20604 potential fix for arangosearch
  tests/js/client/shell/api/arangosearch-memory-metrics.inc
Labels: cla-signed

#20612 FE-426: Improve Foxx install timeout errors
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/foxxes.js
  js/server/modules/@arangodb/foxx/manager.js
Labels: 3 UI, 3 API, 3 Foxx, cla-signed

#20618 [CINFRA] Fix shutdown hanger
  arangod/ClusterEngine/ClusterCollection.cpp
  arangod/ClusterEngine/ClusterCollection.h
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateErrorHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.cpp
  arangod/Replication2/StateMachines/Document/DocumentStateShardHandler.h
  arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.cpp
  arangod/Replication2/StateMachines/Document/MaintenanceActionExecutor.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/StorageEngine/PhysicalCollection.h
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalCollection.h
  arangod/VocBase/Methods/Indexes.cpp
  arangod/VocBase/Methods/Indexes.h
  tests/Mocks/PhysicalCollectionMock.cpp
  tests/Mocks/PhysicalCollectionMock.h
  tests/Replication2/Mocks/DocumentStateMocks.h
Labels: cinfra, cla-signed

#20609 [3.11] BTS-1783
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
Labels: cla-signed

#20622 3.10: Update OpenSSL to 3.0.13 and OpenLDAP to 2.6.7
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#20623 3.11: Update OpenSSL to 3.0.13 and OpenLDAP to 2.6.7 (3.11)
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#20624 Remove unused stuff
  arangod/Aql/ExecutionNode.cpp
  arangod/Aql/SubqueryEndExecutionNode.cpp
  lib/Basics/LocalTaskQueue.cpp
  lib/Basics/LocalTaskQueue.h
  lib/Basics/gcd.h
  lib/CMakeLists.txt
  lib/Meta/static_assert_size.h
Labels: cla-signed

#20620 [BTS-1774] Fix potential nullptr access in StateHandleManager
  arangod/Replication2/ReplicatedLog/Components/StateHandleManager.cpp
  tests/Replication2/CMakeLists.txt
  tests/Replication2/Mocks/FollowerCommitManagerMock.h
  tests/Replication2/ReplicatedState/StateHandleManagerTest.cpp
Labels: cla-signed

#20625 [BTS-1789] Fix local expansion for join nodes
  arangod/Aql/QuerySnippet.cpp
  tests/js/client/aql/aql-index-join.js
Labels: cla-signed

#20627 Upgrade OpenSSL to 3.2.1
  .circleci/base_config.yml
  CHANGELOG
  VERSIONS
  scripts/docker/build/linux/Dockerfile.arm64
  scripts/docker/build/linux/Dockerfile.x86-64
  scripts/docker/build/linux/tools/build_v8_arm64.sh
  scripts/docker/build/linux/tools/install.sh
Labels: OpenSSL, cla-signed

#20630 Unify Projections Into Registers
  arangod/Aql/DocumentProducingHelper.cpp
  arangod/Aql/DocumentProducingHelper.h
  arangod/Aql/IndexExecutor.cpp
  arangod/Aql/IndexExecutor.h
  arangod/Aql/IndexNode.cpp
  arangod/Aql/IndexNode.h
  arangod/Aql/OptimizerRuleBatchMaterializeDocuments.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesJoin.cpp
  arangod/Aql/OptimizerUtils.cpp
  arangod/Aql/OptimizerUtils.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/Aql/IndexNodeTest.cpp
  tests/js/client/aql/aql-projections.js
  tests/js/client/shell/shell-index-stored-values.js
Labels: cla-signed

#20633 Fix testRestoreIndexesFulltextLengthZero
  arangod/Indexes/IndexFactory.cpp
  client-tools/Restore/RestoreFeature.cpp
  client-tools/Utils/ClientTaskQueue.h
Labels: cla-signed

#20632 Add sanitizer builds for CircleCI
  .circleci/base_config.yml
  .circleci/config.yml
  .circleci/generate_config.py
  CMakePresets.json
  scripts/test/arangosh.py
  scripts/test/site_config.py
  tests/js/client/recovery/collector-oom.js
  tests/js/client/recovery/disk-full-datafile.js
  tests/js/client/recovery/disk-full-no-collection-journal.js
  tests/js/client/recovery/insert-update-remove-distance.js
  tests/js/client/recovery/many-logs.js
  tests/js/client/recovery/multiple-logs.js
  tests/js/client/recovery/no-journal.js
  tests/js/client/recovery/no-shutdown-info-multiple-logs.js
  tests/js/client/recovery/no-shutdown-info-no-flush.js
  tests/js/client/recovery/resume-recovery-all.js
  tests/js/client/recovery/resume-recovery-other.js
  tests/js/client/recovery/resume-recovery.js
  tests/test-definitions.txt
Labels: cla-signed

#20638 Remove mentions of Windows in metrics and startup options
  Documentation/Metrics/arangodb_process_statistics_major_page_faults_total.yaml
  Documentation/Metrics/arangodb_process_statistics_minor_page_faults_total.yaml
  Documentation/Metrics/arangodb_process_statistics_virtual_memory_size.yaml
  arangod/RestServer/EndpointFeature.cpp
  arangod/Statistics/Descriptions.cpp
  arangod/Statistics/StatisticsFeature.cpp
  lib/Logger/LoggerFeature.cpp
  lib/Random/RandomFeature.cpp
Labels: cla-signed

#20639 also clean weights when result is cleaned up
  arangod/Graph/PathManagement/SingleProviderPathResult.cpp
Labels: cla-signed

#20626 [BTS-1786] Test only fix
  tests/js/client/aql/aql-view-arangosearch-ddl-combined.js
Labels: 3 - Testing, 3 ArangoSearch, cla-signed

#20640 add progress reporting for RocksDB .sst file checksum computation
  CHANGELOG
  arangod/RocksDBEngine/RocksDBChecksumEnv.cpp
  arangod/RocksDBEngine/RocksDBChecksumEnv.h
  lib/Basics/files.cpp
Labels: cla-signed

#20643 Reduce circleci workspace size
  .circleci/base_config.yml
Labels: cla-signed

#20628 [CINFRA] Ignore ParticipantGone
  arangod/Replication2/ReplicatedLog/Components/CompactionManager.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
Labels: cla-signed

#20645 CircleCI full nightly builds
  .circleci/base_config.yml
  .circleci/config.yml
  .circleci/generate_config.py
  js/client/modules/@arangodb/testsuites/resilience.js
  scripts/test/site_config.py
  tests/js/client/aql/aql-stresstest-nightly.js
  tests/js/client/resilience/move-view/moving-shards-with-arangosearch-view-cluster.js_DISABLED
  tests/test-definitions.txt
Labels: cla-signed

#20647 Refactor how sanitizer logs paths are maintained...
  .circleci/base_config.yml
  js/client/modules/@arangodb/testutils/instance.js
Labels: cla-signed

#20617 [FE-424] Tweak service install button positions
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/scss/_tiles.scss
Labels: 3 UI, cla-signed

#20619 Only allow to create replication2 database in MaintainerMode
  arangod/Cluster/ClusterInfo.cpp
  arangod/Replication2/Version.h
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/VocBase/VocbaseInfo.cpp
  arangod/VocBase/VocbaseInfo.h
  lib/Basics/FeatureFlags.cpp
Labels: DO_NOT_MERGE, cla-signed

#20653 fix sporadic query setup errors
  arangod/Aql/RestAqlHandler.cpp
  js/common/bootstrap/errors.js
  lib/Basics/errors.dat
Labels: cla-signed

#20634 FE-429: rename zkd to MDI, add support for MDI prefixed
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/src/views/analyzers/listAnalyzers/AnalyzersTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndex.types.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesContext.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesHelpers.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesView.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/AddIndexForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/MDIIndexForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/MDIPrefixedIndexForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreateMDIIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreatePrefixedMDIIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/useCreateZKDIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/useSupportedIndexTypes.tsx
  js/apps/system/_admin/aardvark/APP/react/yarn.lock
Labels: 1 Bug, 3 UI, cla-signed

#20641 FE-430: don't disable navigation bar on info tab
  js/apps/system/_admin/aardvark/APP/frontend/js/arango/arango.js
  js/apps/system/_admin/aardvark/APP/frontend/js/views/infoView.js
Labels: 1 Bug, 3 UI, cla-signed

#20607 Bug fix/coverage
  3rdParty/v8-build/CMakeLists.txt
  js/client/modules/@arangodb/testutils/process-utils.js
Labels: cla-signed

#20649 Improve sanitizer builds
  CONTRIBUTING.md
  js/client/modules/@arangodb/testutils/test-utils.js
  tests/js/client/aql/aql-graph-traverser-limit.js
  tests/js/client/aql/aql-graph-traverser-unusedVariable.js
  tests/js/client/aql/aql-index-cache-noinstr_or_noncluster.js
  tests/js/client/aql/aql-optimizer-index-only.js
  tests/js/client/aql/aql-optimizer-indexes-in-or.js
  tests/js/client/aql/aql-optimizer-keep.js
  tests/js/client/aql/aql-optimizer-produces-result.js
  tests/js/client/aql/aql-optimizer-query-stats.js
  tests/js/client/aql/aql-optimizer-rule-move-filters-into-enumerate.js
  tests/js/client/aql/aql-optimizer-rule-remove-sort-rand-limit.js
  tests/js/client/aql/aql-optimizer-rule-use-index-for-sort-noncluster.js
  tests/js/client/replication/aql/replication-aql.js
  tests/js/client/replication/sync/replication-sync-malarkey.inc
  tests/js/client/replication/sync/replication-sync.js
  tests/js/client/server_parameters/test-export-document-metrics-on-noncluster.js
  tests/js/client/shell/multi/shell-simple-query.js
  tests/js/client/shell/shell-cluster-collection.js
  tests/js/client/shell/shell-collection-cache-noncluster.js
  tests/js/client/shell/shell-community-sharding-compat-cluster.js
  tests/js/client/shell/shell-community-sharding-hash-cluster.js
  tests/js/client/shell/shell-ttl-nocov.js
  tests/test-definitions.txt
Labels: cla-signed

#20660 cleanup uses of getResponsibleServer
  arangod/Aql/Collection.cpp
  arangod/Aql/Collection.h
Labels: cla-signed

#20644 remove macOS support
  CMakeLists.txt
  Installation/MacOSX/Bundle/Info.plist.in
  Installation/MacOSX/Bundle/arangodb-cli.sh.in
  Installation/MacOSX/Bundle/icon.icns
  Installation/homebrew/upgrade.sh
  Installation/travisCI/after_failure.sh
  Installation/travisCI/after_script.sh
  Installation/travisCI/before_script.sh
  Installation/travisCI/build.sh
  arangod/Aql/Functions.cpp
  arangod/Aql/QueryOptions.cpp
  arangod/Cluster/ServerState.cpp
  arangod/RestHandler/RestSystemReportHandler.cpp
  arangod/RestServer/EnvironmentFeature.cpp
  arangod/RestServer/arangod.cpp
  lib/Basics/ArangoGlobalContext.cpp
  lib/Basics/Endian.h
  lib/Basics/FileDescriptors.cpp
  lib/Basics/FileUtils.cpp
  lib/Basics/Thread.cpp
  lib/Basics/files.cpp
  lib/Basics/operating-system.h
  lib/Basics/threads-posix.cpp
  lib/CMakeLists.txt
  lib/SimpleHttpClient/ClientConnection.cpp
  lib/SimpleHttpClient/SslClientConnection.cpp
  lib/V8/v8-environment.cpp
  tests/js/server/recovery/crash-handler-abort-noinstr.js
  tests/js/server/recovery/crash-handler-segfault-noinstr.js
  tests/test-definitions.txt
Labels: cla-signed

#20662 remove remainders of multi-platform support
  CMakeLists.txt
  CONTRIBUTING.md
  Installation/Jenkins/Jenkinsfile
  Installation/Jenkins/curl_time_machine.sh
  arangod/CMakeLists.txt
  arangod/GeneralServer/AuthenticationFeature.cpp
  arangod/Replication2/Storage/WAL/WalManager.cpp
  arangod/RestHandler/RestSystemReportHandler.cpp
  arangod/RestServer/CpuUsageFeature.cpp
  arangod/RestServer/DaemonFeature.cpp
  arangod/RestServer/EnvironmentFeature.cpp
  arangod/RestServer/FileDescriptorsFeature.cpp
  arangod/RestServer/MaxMapCountFeature.cpp
  arangod/RestServer/MaxMapCountFeature.h
  arangod/RestServer/arangod.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
  client-tools/Backup/CMakeLists.txt
  client-tools/Benchmark/CMakeLists.txt
  client-tools/Dump/CMakeLists.txt
  client-tools/Export/CMakeLists.txt
  client-tools/Import/CMakeLists.txt
  client-tools/Restore/CMakeLists.txt
  client-tools/Shell/CMakeLists.txt
  client-tools/VPack/CMakeLists.txt
  client-tools/VPack/VPackFeature.cpp
  lib/ApplicationFeatures/BumpFileDescriptorsFeature.cpp
  lib/ApplicationFeatures/FileSystemFeature.cpp
  lib/ApplicationFeatures/FileSystemFeature.h
  lib/Basics/Endian.h
  lib/Basics/FileUtils.cpp
  lib/Basics/files.cpp
  lib/Basics/files.h
  lib/CrashHandler/CrashHandler.cpp
  lib/Geo/GeoJson.cpp
  lib/ProgramOptions/Option.cpp
  lib/ProgramOptions/Option.h
  lib/ProgramOptions/ProgramOptions.cpp
  lib/SimpleHttpClient/SslClientConnection.cpp
Labels: cla-signed

#20672 Fixing Prerelease Incompatibility
  js/common/modules/@arangodb/foxx/store.js
Labels: cla-signed
