Repository arangodb/arangodb, pull requests merged in 2024-11, with the labels that each got.

#21411 log count so we can see whats happening (#21389)
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  tests/js/client/communication/test-cluster-multi-shard-transaction.js
Labels: 3 - Testing, cla-signed

#21416 Fix crash with async prefetch and UDF [BTS-2003]
  CHANGELOG
  arangod/Aql/ExecutionNode/CalculationNode.cpp
  tests/js/client/aql/aql-optimizer-rule-async-prefetch-cluster.js
  tests/js/client/aql/aql-optimizer-rule-async-prefetch-noncluster.js
  tests/js/client/shell/shell-aql-v8.js
Labels: cla-signed

#21419 Make sure that async registry REST handler is running more than once at the same time
  arangod/AsyncRegistryServer/CMakeLists.txt
  arangod/AsyncRegistryServer/Feature.cpp
  arangod/AsyncRegistryServer/Feature.h
  arangod/AsyncRegistryServer/RestHandler.cpp
  arangod/AsyncRegistryServer/RestHandler.h
  arangod/arangoserver.cmake
Labels: cla-signed

#21420 we may receive an undefined body and later on struggle over that.
  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
Labels: 3 Foxx, 3 - Testing, cla-signed

#21412 QA-575: unwrap line breaks when printing out errors in testfailures.txt for better readability
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/result-processing.js
  js/client/modules/@arangodb/testutils/testrunners.js
Labels: 3 - Testing, cla-signed

#21422 Remove details fetching to avoid key range counts
  js/apps/system/_admin/aardvark/APP/frontend/js/models/arangoCollectionModel.js
Labels: 1 Bug, cla-signed

#21424 allow longer timeouts for coverage runs
  js/client/modules/@arangodb/testutils/client-tools.js
  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
  tests/js/client/restart/test-soft-shutdown-cluster.js
Labels: 3 - Testing, cla-signed

#21423 QA-575: unwrap line breaks when printing out errors in testfailures.txt for better readability
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/result-processing.js
  js/client/modules/@arangodb/testutils/testrunners.js
Labels: 3 - Testing, cla-signed

#21425 Promise can have an async or sync waiter
  arangod/AsyncRegistryServer/RestHandler.cpp
  arangod/AsyncRegistryServer/pretty_printer/pretty_printer.py
  arangod/Scheduler/WorkStealingThreadPool.cpp
  lib/Async/Registry/promise.h
  lib/Async/include/Async/async.h
  lib/Futures/include/Futures/Future.h
  lib/Futures/include/Futures/Promise.h
  tests/Async/AsyncTest.cpp
  tests/Futures/FutureTest.cpp
Labels: cla-signed

#21428 Hot fix for synchronise shard race and arangodump malformed JSON with MDI
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/ClusterEngine/ClusterIndex.cpp
  client-tools/Dump/DumpFeature.cpp
  lib/Basics/VelocyPackHelper.cpp
Labels: 1 Bug, 3 Cluster, cla-signed

#21427 No SynchronizeShard when Resigned
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
Labels: cla-signed

#21430 QA-580: the old v8 doesn't have replaceAll
  js/client/modules/@arangodb/testutils/result-processing.js
Labels: 3 - Testing, cla-signed

#21421 QA-577: implement process + thread logging if the system goes into overload.
  scripts/test/launch_handler.py
  scripts/test/overload_thread.py
  scripts/test/site_config.py
  scripts/test/tools/killall.py
Labels: 3 - Testing, cla-signed

#21432 QA-579: Feature/rta abort without cleanup
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/client-tools.js
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: 3 - Testing, cla-signed

#21433 Refuse Sync Log Message Improvements
  arangod/Cluster/Maintenance.cpp
Labels: cla-signed

#21434 Feature 3.11/rta abort without cleanup
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/client-tools.js
  js/client/modules/@arangodb/testutils/testrunner.js
Labels: 3 - Testing, cla-signed

#21436 Bug fix/more time for agency
  js/client/modules/@arangodb/testutils/agency.js
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#21437 give more resources, prolongue timeouts
  js/client/modules/@arangodb/testutils/client-tools.js
  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed

#21439 Fix query cache / optimizer startup option flags
  arangod/RestServer/QueryRegistryFeature.cpp
Labels: 3 Documentation, 3 Core, cla-signed

#21440 Fix blockage occurring with MultipleRemoteModification
  CHANGELOG
  arangod/StorageEngine/TransactionState.cpp
Labels: cla-signed

#21441 Fix blockage occurring with MultipleRemoteModification [BTS-2012]
  CHANGELOG
  arangod/StorageEngine/TransactionState.h
Labels: cla-signed

#21444 Fix delay in maintenance if write hots directly after hotbackup restore [BTS-2014]
  CHANGELOG
  arangod/Cluster/FollowerInfo.cpp
Labels: cla-signed

#21447 Lost Subordinates Metric
  CHANGELOG
  Documentation/Metrics/arangodb_vocbase_transactions_lost_subordinates_total.yaml
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Methods.cpp
  arangod/VocBase/VocbaseMetrics.cpp
  arangod/VocBase/VocbaseMetrics.h
Labels: cla-signed

#21452 BTS-2018 UPDATE CHANGELOG
  CHANGELOG
Labels: cla-signed

#21454 [BTS-2017] Set remainsFollower=true for satellite collections.
  CHANGELOG
  arangod/Agency/CleanOutServer.cpp
  tests/Agency/CleanOutServerTest.cpp
  tests/Agency/CleanOutServerTest.json
Labels: cla-signed

#21456 Enable build image for vector index
  .circleci/base_config.yml
  .circleci/config.yml
Labels: cla-signed

#21450 Depending asyncronous operations are connected on call instead of just on await
  arangod/AsyncRegistryServer/RestHandler.cpp
  arangod/AsyncRegistryServer/pretty_printer/pretty_printer.py
  lib/Async/Registry/promise.cpp
  lib/Async/Registry/promise.h
  lib/Async/Registry/registry_variable.cpp
  lib/Async/Registry/registry_variable.h
  lib/Async/Registry/thread_registry.cpp
  lib/Async/Registry/thread_registry.h
  lib/Async/include/Async/async.h
  lib/Async/include/Async/coro-utils.h
  lib/Futures/include/Futures/Future.h
  lib/Futures/include/Futures/Promise.h
  lib/Futures/include/Futures/Utilities.h
  lib/Futures/include/Futures/coro-helper.h
  tests/Async/AsyncTest.cpp
  tests/Futures/FutureCoroutineTest.cpp
  tests/Futures/FutureTest.cpp
Labels: cla-signed

#21457 Fix tsan data race
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/AqlFunctionFeature.h
Labels: cla-signed

#21453 Fix data race
  lib/Async/Registry/registry.h
Labels: cla-signed

#21451 Bug fix 3.11/longer coverage timeouts
  tests/js/client/communication/test-communication-cluster.js
  tests/js/client/communication/test-kill.js
  tests/js/server/dump/dump-test.inc
Labels: 3 - Testing, cla-signed

#21458 Fix tsan data race in 3.11
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/AqlFunctionFeature.h
Labels: cla-signed

#21431 [3.11] No SynchronizeShard when Resigned [BTS-2013]
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  tests/js/client/shell/shell-move-shard-sync-fail-cluster.js
Labels: cla-signed

#21462 Upgrade OpenSSL to 3.4.0
  .circleci/base_config.yml
  .circleci/config.yml
  CHANGELOG
  VERSIONS
  scripts/docker/build/linux/Dockerfile.arm64
  scripts/docker/build/linux/Dockerfile.x86-64
  scripts/docker/build/linux/static/ubuntu.sources
Labels: OpenSSL, cla-signed

#21463 Upgrade OpenSSL to 3.4.0
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#21466 Bug fix 3.11/no cleanup on failure
  js/client/modules/@arangodb/testutils/client-tools.js
Labels: 3 - Testing, cla-signed

#21460 Improve readability of async registry output
  arangod/AsyncRegistryServer/RestHandler.cpp
  arangod/AsyncRegistryServer/pretty_printer/pretty_printer.py
  lib/Async/Registry/promise.cpp
  lib/Async/Registry/promise.h
  lib/Async/Registry/registry_variable.cpp
  lib/Async/Registry/thread_registry.cpp
  lib/Async/Registry/thread_registry.h
  lib/Basics/Thread.cpp
  lib/Basics/Thread.h
  lib/Futures/include/Futures/Future.h
  tests/Async/AsyncTest.cpp
  tests/Async/Registry/RegistryTest.cpp
  tests/Async/Registry/ThreadRegistryTest.cpp
  tests/Futures/FutureCoroutineTest.cpp
  tests/Futures/FutureTest.cpp
Labels: cla-signed

#21465 [BTS-2019] Missing Preconditions
  arangod/Agency/AddFollower.cpp
  arangod/Agency/FailedLeader.cpp
  arangod/Agency/MoveShard.cpp
  arangod/Agency/RemoveFollower.cpp
Labels: cla-signed

#21467 try to locate the minidump insite of the instance roots tmp folder
  js/client/modules/@arangodb/testutils/crash-utils.js
Labels: 3 - Testing

#21413 Bug-fix/ui-nitpicks
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexFieldsDataEntry.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexPrimarySort.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/InvertedIndexStoredValues.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/useCreateInvertedIndex.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/query/editor/useQuerySpotlightOptions.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/ArangoSearchViewForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/linksEditor/LinksDetails.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/AdvancedAccordionItem.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/PrimarySortAccordionItem.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/addNewViewForm/StoredValuesAccordionItem.tsx
Labels: cla-signed

#21468 Fix data race in async test
  lib/Async/include/Async/async.h
Labels: cla-signed

#21478 Don't instantiate query during explain
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryPlanCache.cpp
  arangod/Aql/QueryPlanCache.h
  arangod/V8Server/v8-vocbase.cpp
  tests/js/client/aql/aql-optimizer-rule-late-document-materialization-arangosearch.inc
Labels: cla-signed

#21476 send abort, de-silence long running tests
  js/client/modules/@arangodb/testutils/client-tools.js
  js/client/modules/@arangodb/testutils/test-utils.js
  scripts/test/async_client.py
  tests/js/client/aql/aql-subquery-chaos-nightly.js
  tests/js/client/communication/test-communication-cluster.js
  tests/js/client/communication/test-kill.js
  tests/js/client/dump/dump-test.inc
  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
  tests/js/client/recovery/search/view-search-alias-populate-remove.js
  tests/js/client/restart/test-restart-cluster.js
  tests/js/client/restart/test-soft-shutdown-cluster.js
  tests/test-definitions.txt
Labels: 3 - Testing, cla-signed
