Repository arangodb/arangodb, pull requests merged in 2024-09, with the labels that each got.

#21245 Refactor communication tests, adjust timeouts for coverage
  arangod/Cluster/v8-cluster.cpp
  js/client/modules/@arangodb/test-helper.js
  js/client/modules/@arangodb/testsuites/communication.js
  js/client/modules/@arangodb/testutils/client-tools.js
  js/client/modules/@arangodb/testutils/process-utils.js
  js/client/modules/@arangodb/testutils/san-file-handler.js
  js/client/modules/@arangodb/testutils/testing.js
  tests/js/client/aql/aql-complex.js
  tests/js/client/communication/test-communication.js
  tests/js/client/communication/test-kill.js
  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
  tests/js/client/restart/test-foxx-selfheal-cluster-nocov.js
  tests/js/client/restart/test-soft-shutdown-cluster-nocov.js
  tests/js/client/shell/multi/shell-aql-kill.js
  tests/js/client/shell/shell-index-background-nocov.js
  tests/js/client/shell/shell-index.js
  tests/js/client/shell/shell-replication-auto-repair-cluster.js
  tests/test-definitions.txt
Labels: cla-signed

#21285 as sugested by @jbajic in the backport PR, fix the syntax in the documentation
  utils/README.md
Labels: cla-signed

#21280 Filtering for fast object enumeration
  arangod/Aql/ExecutionNode/EnumerateListNode.cpp
  arangod/Aql/ExecutionNode/EnumerateListNode.h
  arangod/Aql/Executor/EnumerateListExecutor.cpp
  arangod/Aql/Executor/EnumerateListExecutor.h
  arangod/Aql/Optimizer/Rule/OptimizerRuleReplaceEntriesWithObjectIteration.cpp
  arangod/Aql/Optimizer/Rule/OptimizerRulesCluster.cpp
  arangod/Aql/OptimizerRules.cpp
  tests/Aql/Executor/EnumerateListExecutorTest.cpp
  tests/js/client/aql/aql-object-enumeration.js
Labels: cla-signed

#21290 Fix unstable tests around force-one-shard
  CHANGELOG
  arangod/Cluster/ClusterFeature.cpp
Labels: cla-signed

#21293 Fix circleci setup w.r.t. circleci branch
  .circleci/config.yml
  CHANGELOG
Labels: cla-signed

#21300 Paperwork for RocksDB fix
  3rdParty/README_maintainers.md
  CHANGELOG
Labels: cla-signed

#21302 Solve deadlock around SynchronizeShard
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/SynchronizeShard.cpp
Labels: cla-signed

#21303 Solve deadlock around dynamic metrics [BTS-1965]
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/IResearch/IResearchMetricStats.h
Labels: cla-signed

#21294 attempt to restart in place
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/agency.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: cla-signed

#21307 enable ui tests by default
  .circleci/base_config.yml
  .circleci/config.yml
Labels: 3 UI, 3 - Testing, cla-signed

#21305 Solve deadlock around SynchronizeShard [BTS-1965]
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/SynchronizeShard.cpp
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: cla-signed

#21289 set size of cluster machine to medium
  tests/test-definitions.txt
Labels: cla-signed

#21296 Bugfix: Enable async tests
  lib/Async/Registry/registry.h
  lib/Async/Registry/thread_registry.h
  tests/Async/AsyncTest.cpp
  tests/Async/CMakeLists.txt
  tests/Async/ExpectedTest.cpp
  tests/Async/Registry/RegistryTest.cpp
  tests/Async/Registry/ThreadRegistryTest.cpp
  tests/CMakeLists.txt
Labels: cla-signed

#21287 Add metrics to async registry
  Documentation/Metrics/arangodb_async_active_functions.yaml
  Documentation/Metrics/arangodb_async_active_threads.yaml
  Documentation/Metrics/arangodb_async_functions_total.yaml
  Documentation/Metrics/arangodb_async_ready_for_deletion_functions.yaml
  Documentation/Metrics/arangodb_async_registered_threads.yaml
  Documentation/Metrics/arangodb_async_threads_total.yaml
  arangod/AsyncRegistryServer/CMakeLists.txt
  arangod/AsyncRegistryServer/Feature.cpp
  arangod/AsyncRegistryServer/Feature.h
  arangod/CMakeLists.txt
  arangod/Metrics/CMakeLists.txt
  arangod/Metrics/GaugeCounterGuard.h
  arangod/Metrics/Metric.h
  arangod/RestServer/IOHeartbeatThread.h
  arangod/RestServer/arangod.cpp
  arangod/RestServer/arangod.h
  arangod/RestServer/arangod_includes.h
  arangod/arangoserver.cmake
  lib/Async/Registry/CMakeLists.txt
  lib/Async/Registry/Metrics.h
  lib/Async/Registry/registry.cpp
  lib/Async/Registry/registry.h
  lib/Async/Registry/thread_registry.cpp
  lib/Async/Registry/thread_registry.h
  tests/Async/Registry/ThreadRegistryTest.cpp
Labels: cla-signed

#21316 More diagnostics for agency inception failure [BTS-1971]
  arangod/Agency/Inception.cpp
Labels: cla-signed

#21317 Reset Locale in Tests
  tests/RestServer/LanguageFeatureTest.cpp
Labels: cla-signed

#21313 Optimize MDI Sparse Condition Matcher
  CHANGELOG
  arangod/Aql/Condition.cpp
  arangod/RocksDBEngine/RocksDBMultiDimIndex.cpp
  tests/js/client/aql/aql-mdi-prefix-fields.js
  tests/js/client/aql/aql-mdi-sparse.js
Labels: cla-signed

#21318 Update CODEOWNERS
  .github/CODEOWNERS
Labels: cla-signed

#21308 add handling for failures so we get propper result
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/instance-manager.js
Labels: cla-signed

#21295 EnumerateObject + Limit Tests
  tests/js/client/aql/aql-object-enumeration.js
Labels: cla-signed

#21326 remove errnous filter
  js/client/modules/@arangodb/testutils/test-utils.js
  tests/js/client/server_parameters/test-export-shard-usage-metrics-bytes-per-shard-cluster-fp.js
Labels: 3 - Testing, cla-signed

#21324 partially backport filter support
  CONTRIBUTING.md
  js/client/modules/@arangodb/testutils/test-utils.js
Labels: cla-signed

#21320 Refactor names in async registry
  arangod/AsyncRegistryServer/Feature.h
  arangod/AsyncRegistryServer/RestHandler.cpp
  lib/Async/Registry/promise.h
  lib/Async/Registry/registry.h
  lib/Async/Registry/registry_variable.cpp
  lib/Async/Registry/registry_variable.h
  lib/Async/Registry/thread_registry.cpp
  lib/Async/Registry/thread_registry.h
  lib/Async/include/Async/async.h
  tests/Async/AsyncTest.cpp
  tests/Async/Registry/RegistryTest.cpp
  tests/Async/Registry/ThreadRegistryTest.cpp
Labels: cla-signed

#21327 Upgrade OpenSSL to 3.3.2
  .circleci/base_config.yml
  CHANGELOG
  VERSIONS
  scripts/docker/build/linux/Dockerfile.arm64
  scripts/docker/build/linux/Dockerfile.x86-64
Labels: OpenSSL, cla-signed

#21328 Upgrade OpenSSL to 3.3.2 in 3.11
  CHANGELOG
  VERSIONS
Labels: cla-signed

#21314 Fix `IN_RANGE` on MDI index
  arangod/Aql/Condition.cpp
  tests/js/client/aql/aql-mdi.js
Labels: 1 Bug, cla-signed

#21301 Make initializer_list constexpr if possible
  arangod/Aql/ExecutionNode/SubqueryNode.cpp
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/IResearch/IResearchDocument.cpp
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: cla-signed

#21321 Fix thread registry beeing removed too early
  lib/Async/Registry/registry.cpp
  lib/Async/Registry/registry.h
  lib/Async/Registry/registry_variable.cpp
  lib/Async/Registry/thread_registry.cpp
  lib/Async/Registry/thread_registry.h
  tests/Async/Registry/RegistryTest.cpp
Labels: cla-signed

#21312 Do not bail out when extended names have inconsistent settings
  CHANGELOG
  arangod/Cluster/ServerState.cpp
Labels: cla-signed

#21322 Fix coroutine members beeing destroyed too late
  lib/Async/Registry/CMakeLists.txt
  lib/Async/Registry/promise.cpp
  lib/Async/Registry/promise.h
  lib/Async/Registry/thread_registry.cpp
  lib/Async/Registry/thread_registry.h
  lib/Async/include/Async/async.h
  tests/Async/AsyncTest.cpp
  tests/Async/Registry/RegistryTest.cpp
  tests/Async/Registry/ThreadRegistryTest.cpp
Labels: cla-signed

#21331 QA-561: Feature/test vpack dumping
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testutils/client-tools.js
  tests/js/client/dump/dump-check-dump-files-compressed.js
  tests/test-definitions.txt
Labels: 3 ImportExport, 3 - Testing, velocypack, cla-signed

#21283 FE-465: handle HiddenIndex type & "fields" object in collection index page
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/package.json
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesContext.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndicesHelpers.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/DeleteIndexModal.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/invertedIndex/FieldsDropdown.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/listIndices/CollectionIndexActionButtons.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/listIndices/CollectionIndicesTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/useFetchCollectionIndices.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/viewIndex/IndexStats.tsx
  js/apps/system/_admin/aardvark/APP/react/yarn.lock
Labels: cla-signed
