Repository arangodb/arangodb, pull requests merged in 2024-12, with the labels that each got.

#21475 Removes Quadratic Algorithm
  arangod/Agency/Job.cpp
Labels: 9 CLA available

#21481 be more verbose, fix check
  js/client/modules/@arangodb/testutils/crash-utils.js
Labels: 3 - Testing, cla-signed

#21482 Dump Projection Bug
  arangod/RocksDBEngine/RocksDBDumpContext.cpp
  tests/js/client/shell/api/dump-cluster.js
Labels: cla-signed

#21484 Fix use after free in cluster info
  arangod/Cluster/ClusterInfo.cpp
Labels: cla-signed

#21486 3.11 backport: Fix use-after-free in ClusterInfo SyncerThread
  arangod/Cluster/ClusterInfo.cpp
Labels: cla-signed

#21493 Fix remove server API [BTS-2040]
  CHANGELOG
  arangod/RestHandler/RestAdminClusterHandler.cpp
Labels: cla-signed

#21487 Do not clean up failed jobs before their parent is finished [BTS-2022]
  CHANGELOG
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  tests/Agency/SupervisionTest.cpp
Labels: cla-signed

#21494 move subquery chaos into its own testsuite
  js/client/modules/@arangodb/testsuites/chaos.js
  tests/js/client/chaos_subq/aql-subquery-chaos-nightly.js
  tests/test-definitions.txt
Labels: cla-signed

#21492 [3.11][BTS-2027] Removes Quadratic Algorithm
  arangod/Agency/Job.cpp
Labels: cla-signed

#21497 Small fix for corner case
  arangod/Agency/Supervision.cpp
Labels: cla-signed

#21496 disable if not full
  tests/test-definitions.txt
Labels: cla-signed

#21488 Do not clean up failed jobs before their parent is finished [BTS-2022]
  CHANGELOG
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  tests/Agency/SupervisionTest.cpp
Labels: cla-signed

#21500 give instrumented test execution more time to yield more runs
  tests/js/client/communication/test-kill.js
Labels: 3 - Testing, cla-signed

#21499 give instrumented test execution more time to yield more runs
  tests/js/client/communication/test-kill.js
Labels: 3 - Testing, cla-signed

#21501 Small fix for cleanup of finished and failed jobs
  arangod/Agency/Supervision.cpp
Labels: cla-signed

#21461 Additional fix to aql functions data race
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/IResearch/ApplicationServerHelper.cpp
  arangod/IResearch/ApplicationServerHelper.h
Labels: cla-signed

#21505 wait longer here too
  tests/js/client/communication/test-communication-cluster.js
Labels: cla-signed

#21507 Remove two unnecessary LOG_DEVEL commands
  arangod/Agency/Supervision.cpp
Labels: cla-signed

#21509 invoke heap cleanup, fix prints
  js/common/modules/@arangodb/test-generators/subquery-chaos-test.js
  tests/js/client/chaos_subq/aql-subquery-chaos-nightly.js
Labels: 3 - Testing, cla-signed

#21508 Fix expiration of servers in agency [BTS-2039]
  CHANGELOG
  arangod/Agency/AgencyFeature.cpp
  arangod/Agency/AgencyFeature.h
  arangod/Agency/AgentConfiguration.cpp
  arangod/Agency/AgentConfiguration.h
  arangod/Agency/Supervision.cpp
  arangod/Agency/Supervision.h
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterFeature.h
  arangod/Cluster/HeartbeatThread.cpp
  arangod/Cluster/HeartbeatThread.h
  tests/Agency/SupervisionTest.cpp
Labels: cla-signed

#21510 no WARN for regular execution.
  arangod/Pregel/Conductor/Conductor.cpp
  arangod/Pregel/GraphStore/GraphLoader.cpp
  arangod/Pregel/Worker/Worker.cpp
Labels: cla-signed

#21515 Fix UB in tests
  tests/Agency/SupervisionTest.cpp
Labels: cla-signed

#21512 longer timeouts for instrummented communication suite subshells
  js/client/modules/@arangodb/testutils/client-tools.js
Labels: 3 - Testing, cla-signed

#21522 Disallow KEEP with INTO var = expr.
  CHANGELOG
  arangod/Aql/grammar.y
Labels: cla-signed

#21518 Expire idle connections [BTS-2041] [BTS-2011]
  CHANGELOG
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Replication/DatabaseInitialSyncer.cpp
  arangod/Replication/DatabaseTailingSyncer.cpp
  arangod/Replication/DatabaseTailingSyncer.h
  arangod/Replication/ReplicationFeature.cpp
  lib/SimpleHttpClient/ConnectionCache.cpp
  lib/SimpleHttpClient/ConnectionCache.h
  tests/SimpleHttpClient/ConnectionCacheTest.cpp
Labels: cla-signed

#21526 Feature 3.11/timestamp in failures
  js/common/modules/jsunity.js
  js/common/modules/jsunity/jsunity.js
Labels: 3 - Testing, cla-signed

#21530 Fix CHANGELOG
  CHANGELOG
Labels: cla-signed

#21471 Fast VectorIndex Builder
  arangod/RocksDBEngine/RocksDBBuilderIndex.cpp
  arangod/RocksDBEngine/RocksDBVectorIndex.cpp
  arangod/RocksDBEngine/RocksDBVectorIndex.h
Labels: cla-signed

#21525 Collect Performance Improvement
  CHANGELOG
  arangod/Aql/Aggregator.cpp
  arangod/Aql/CollectOptions.cpp
  arangod/Aql/CollectOptions.h
  arangod/Aql/ExecutionNode/CollectNode.cpp
  arangod/Aql/ExecutionNode/CollectNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/SortElement.cpp
  arangod/Aql/SortElement.h
  tests/js/client/aql/aql-collect-output-aggregation-optimization-cluster.js
  tests/js/client/aql/aql-optimizer-collect-methods.js
  tests/js/client/aql/aql-optimizer-keep.js
  tests/js/client/aql/aql-optimizer-rule-use-index-for-sort-cluster.js
Labels: cla-signed

#21491 Add nProbe parameter to APPROX_NEAR functions
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/ExecutionNode/EnumerateNearVectorNode.cpp
  arangod/Aql/ExecutionNode/EnumerateNearVectorNode.h
  arangod/Aql/Executor/EnumerateNearVectorExecutor.cpp
  arangod/Aql/Executor/EnumerateNearVectorExecutor.h
  arangod/Aql/Optimizer/Rule/OptimizerRuleVectorIndex.cpp
  arangod/Indexes/VectorIndexDefinition.h
  arangod/RocksDBEngine/RocksDBVectorIndex.cpp
  arangod/RocksDBEngine/RocksDBVectorIndex.h
  js/common/modules/@arangodb/aql/explainer.js
  tests/js/client/aql/vector/aql-vector-create-and-remove.js
  tests/js/client/aql/vector/aql-vector-nprobe.js
Labels: 1 Feature, cla-signed

#21516 Fix vector index serialization
  CHANGELOG
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Indexes/Index.h
  arangod/RocksDBEngine/RocksDBVectorIndex.cpp
  arangod/VocBase/LogicalCollection.cpp
  arangod/VocBase/LogicalDataSource.cpp
  arangod/VocBase/LogicalDataSource.h
Labels: 1 Bug, cla-signed

#21531 Check connection coming out of connection cache
  CHANGELOG
  lib/Basics/socket-utils.h
  lib/SimpleHttpClient/ClientConnection.cpp
  lib/SimpleHttpClient/ClientConnection.h
  lib/SimpleHttpClient/ConnectionCache.cpp
  lib/SimpleHttpClient/GeneralClientConnection.h
  lib/SimpleHttpClient/SslClientConnection.cpp
  lib/SimpleHttpClient/SslClientConnection.h
Labels: cla-signed

#21502 Group sort optimization
  CHANGELOG
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionNode/SortNode.cpp
  arangod/Aql/ExecutionNode/SortNode.h
  arangod/Aql/Executor/CMakeLists.txt
  arangod/Aql/Executor/GroupedSortExecutor.cpp
  arangod/Aql/Executor/GroupedSortExecutor.h
  arangod/Aql/Executor/GroupedSortExecutorBackend.cpp
  arangod/Aql/Executor/GroupedSortExecutorBackend.h
  arangod/Aql/OptimizerRules.cpp
  js/common/modules/@arangodb/aql/explainer.js
  tests/Aql/Executor/GroupedSortExecutorTest.cpp
  tests/CMakeLists.txt
  tests/js/client/aql/aql-optimizer-indexes-group-sort.js
Labels: cla-signed

#21527 Separate info structs for sort executors
  arangod/Aql/ExecutionNode/SortNode.cpp
  arangod/Aql/Executor/ConstrainedSortExecutor.cpp
  arangod/Aql/Executor/ConstrainedSortExecutor.h
  arangod/Aql/Executor/SortExecutor.cpp
  arangod/Aql/Executor/SortExecutor.h
  tests/Aql/Executor/CalculationExecutorTest.cpp
  tests/Aql/Executor/CountCollectExecutorTest.cpp
  tests/Aql/Executor/DistinctCollectExecutorTest.cpp
  tests/Aql/Executor/EnumerateCollectionExecutorTest.cpp
  tests/Aql/Executor/EnumerateListExecutorTest.cpp
  tests/Aql/Executor/ExecutorTestHelper.h
  tests/Aql/Executor/FilterExecutorTest.cpp
  tests/Aql/Executor/GroupedSortExecutorTest.cpp
  tests/Aql/Executor/HashedCollectExecutorTest.cpp
  tests/Aql/Executor/NoResultsExecutorTest.cpp
  tests/Aql/Executor/ReturnExecutorTest.cpp
  tests/Aql/Executor/SortExecutorTest.cpp
  tests/Aql/Executor/SortedCollectExecutorTest.cpp
  tests/Aql/Executor/SubqueryStartExecutorTest.cpp
  tests/Aql/Executor/WindowExecutorTest.cpp
  tests/Aql/SplicedSubqueryIntegrationTest.cpp
Labels: cla-signed
