Repository arangodb/arangodb, pull requests merged in 2024-04, with the labels that each got.

#20799 add method to stringify RW lock state
  lib/Basics/ReadWriteLock.cpp
  lib/Basics/ReadWriteLock.h
  tests/Basics/ReadWriteLockTest.cpp
Labels: cla-signed

#20800 Log info message for requests with queue time >= 30s
  CHANGELOG
  arangod/GeneralServer/RestHandler.cpp
Labels: cla-signed

#20801 fix an invalid assertion during replication
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
Labels: cla-signed

#20804 Remove the detach thread code from transaction manager.
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RestHandler/RestVocbaseBaseHandler.cpp
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  lib/Basics/FutureSharedLock.h
  tests/Transaction/ManagerTest.cpp
Labels: cla-signed

#20806 obsolete now-unused startup option
  CHANGELOG
  arangod/Scheduler/Scheduler.cpp
  arangod/Scheduler/Scheduler.h
  arangod/Scheduler/SchedulerFeature.cpp
  arangod/Scheduler/SchedulerFeature.h
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Scheduler/SupervisedScheduler.h
  arangod/Transaction/Manager.cpp
  tests/Cluster/RebootTrackerTest.cpp
Labels: cla-signed

#20774 miscellaneous changes pulled out of another larger PR
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/AqlFunctionFeature.h
  arangod/Aql/BlocksWithClients.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/ExecutionNode/EnumerateCollectionNode.h
  arangod/Aql/ExecutionNode/ExecutionNode.cpp
  arangod/Aql/ExecutionNode/ExecutionNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/Expression.cpp
  arangod/Aql/Expression.h
  arangod/Aql/Function.cpp
  arangod/Aql/Function.h
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/IndexHint.h
  arangod/Aql/OptimizerRules.cpp
  arangod/Aql/OptimizerRulesReplaceFunctions.cpp
  arangod/Aql/QueryResult.h
  arangod/Aql/SortElement.cpp
  arangod/GeoIndex/Index.h
  arangod/RocksDBEngine/RocksDBOptimizerRules.cpp
  arangod/RocksDBEngine/RocksDBTtlIndex.cpp
  arangod/RocksDBEngine/RocksDBTtlIndex.h
  arangod/Transaction/Options.cpp
  arangod/Transaction/Options.h
  tests/Aql/RegisterPlanTest.cpp
  tests/js/client/aql/aql-arangosearch-constrained-sort-optimization.inc
  tests/js/client/aql/aql-graph-traverser-optimizeIn.js
  tests/js/client/aql/aql-optimizer-fulltext.js
  tests/js/client/aql/aql-optimizer-operators.js
  tests/js/client/aql/aql-parse.js
  tests/js/client/aql/aql-queries-simple.js
Labels: cla-signed

#20793 Change request lane priorities
  CHANGELOG
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/GeneralServer/RequestLane.h
  arangod/GeneralServer/RestHandler.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestCollectionHandler.h
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestCursorHandler.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestTransactionHandler.h
  arangod/StorageEngine/TransactionState.cpp
  arangod/StorageEngine/TransactionState.h
  js/client/modules/@arangodb/test-helper.js
  tests/js/client/shell/shell-transaction-commit-abort-overwhelm-cluster.js
Labels: cla-signed

#20802 Removed incorrect assertion in bindCollectionIncremental
  arangod/RocksDBEngine/RocksDBReplicationContext.cpp
Labels: 1 Bug, cla-signed

#20810 fix BTS-1840
  CHANGELOG
  arangod/Cluster/HeartbeatThread.cpp
Labels: cla-signed

#20805 add debug APIs
  CHANGELOG
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/Aql/QueryString.h
  arangod/Aql/RestAqlHandler.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestQueryHandler.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  arangod/V8Server/v8-vocbase.cpp
  tests/Transaction/ManagerTest.cpp
  tests/js/client/server_parameters/test-query-registry-contents-cluster.js
  tests/js/client/shell/test-trx-registry-contents-cluster.js
Labels: cla-signed

#20803 Trigger callbacks waiting on raft indexes in the ClusterInfo timely
  arangod/Cluster/AgencyCache.cpp
  arangod/Cluster/AgencyCache.h
  arangod/Cluster/AgencyCallbackRegistry.h
  arangod/Cluster/ClusterFeature.cpp
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/Cluster/DBServerAgencySync.cpp
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/Maintenance.h
  arangod/Replication2/StateMachines/Document/DocumentStateSnapshotHandler.cpp
  tests/IResearch/IResearchLinkCoordinatorTest.cpp
  tests/IResearch/IResearchViewCoordinatorTest.cpp
  tests/Maintenance/MaintenanceTest.cpp
  tests/Mocks/Servers.cpp
Labels: 1 Bug, cla-signed

#20790 Improve wait behavior during leader transfer
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
Labels: cla-signed

#20811 Async trx commit/abort
  arangod/Replication2/StateMachines/Document/DocumentLeaderState.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestTransactionHandler.h
  arangod/Scheduler/Scheduler.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  tests/Replication2/Mocks/DocumentStateMocks.h
  tests/RocksDBEngine/TransactionManagerTest.cpp
  tests/Transaction/ManagerTest.cpp
Labels: cla-signed

#20812 remove `_activeTrx` instance variable
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
Labels: cla-signed

#20807 rectify some 3rd party license information
  LICENSES-OTHER-COMPONENTS.md
Labels: cla-signed

#20816 BTS-1489: Race condition in AsioSocket shutdown when using SSL. (#20753)
  CHANGELOG
  arangod/GeneralServer/Acceptor.h
  arangod/GeneralServer/AcceptorTcp.cpp
  arangod/GeneralServer/AcceptorTcp.h
  arangod/GeneralServer/AcceptorUnixDomain.cpp
  arangod/GeneralServer/AcceptorUnixDomain.h
  arangod/GeneralServer/AsioSocket.h
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/GeneralCommTask.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/H2CommTask.h
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/HttpCommTask.h
  arangod/GeneralServer/VstCommTask.cpp
  arangod/GeneralServer/VstCommTask.h
Labels: cla-signed

#20818 work around log output limits in circleci?
  js/client/modules/@arangodb/testsuites/fuerte.js
  js/client/modules/@arangodb/testutils/instance.js
Labels: cla-signed

#20817 GetLeaderForShard Fix
  arangod/Cluster/ClusterInfo.cpp
  arangod/RestHandler/RestReplicationHandler.cpp
Labels: cla-signed

#20813 Use std::source_location, and make paths relative to the content root
  arangod/GeneralServer/RestHandler.cpp
  arangod/Replication2/Methods.cpp
  arangod/Replication2/ReplicatedLog/Components/AppendEntriesManager.cpp
  arangod/Replication2/ReplicatedLog/Components/CompactionManager.cpp
  arangod/Replication2/ReplicatedLog/Components/FollowerCommitManager.cpp
  arangod/Replication2/ReplicatedLog/Components/InMemoryLogManager.cpp
  arangod/Replication2/ReplicatedLog/LogLeader.cpp
  arangod/Replication2/ReplicatedState/FollowerStateManager.tpp
  arangod/Replication2/ReplicatedState/ReplicatedState.tpp
  arangod/Replication2/ReplicatedState/StreamProxy.tpp
  arangod/VocBase/VocBaseLogManager.cpp
  lib/Basics/Exceptions.cpp
  lib/Basics/Exceptions.h
  lib/Basics/FutureSharedLock.h
  lib/Basics/SourceLocation.cpp
  lib/Basics/SourceLocation.h
  tests/Basics/CMakeLists.txt
  tests/Basics/SourceLocationTest.cpp
  tests/Replication2/Mocks/FakeFollower.cpp
Labels: cla-signed

#20814 obsolete 3.11 feature flag
  arangod/RestServer/QueryRegistryFeature.cpp
Labels: cla-signed

#20823 make optimizer rule `async-prefetch` unavailable in 3.11.
  arangod/Aql/OptimizerRulesFeature.cpp
Labels: cla-signed

#20824 remove obsolete check for new versions from web interface
  js/apps/system/_admin/aardvark/APP/frontend/js/routers/versionCheck.js
Labels: cla-signed

#20825 fix BTS-1848: Issue with Collection Names Containing Non-ASCII Characters in Web UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/addCollection/AddCollectionModal.tsx
Labels: cla-signed

#20809 Docs: Updated compile instructions for 3.12+
  CONTRIBUTING.md
Labels: cla-signed

#20768 AsyncNode should not trigger wakeup for WAITING result
  CHANGELOG
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/Executor/AsyncExecutor.cpp
  arangod/Aql/Executor/AsyncExecutor.h
  arangod/Aql/SharedQueryState.h
  tests/Aql/Executor/AqlExecutorTestCase.cpp
  tests/Aql/Executor/AqlExecutorTestCase.h
  tests/Aql/Executor/AsyncExecutorTest.cpp
  tests/Aql/Executor/ExecutorTestHelper.h
  tests/Aql/WaitingExecutionBlockMock.cpp
  tests/Aql/WaitingExecutionBlockMock.h
Labels: cla-signed

#20831 ExecuteAsync for RestHandlers
  arangod/GeneralServer/RestHandler.cpp
  arangod/GeneralServer/RestHandler.h
  arangod/RestHandler/RestSupervisionStateHandler.cpp
  arangod/RestHandler/RestSupervisionStateHandler.h
Labels: cla-signed

#20754 Feature/split client tools
  CONTRIBUTING.md
  js/client/modules/@arangodb/README.md
  js/client/modules/@arangodb/testsuites/arangobench.js
  js/client/modules/@arangodb/testsuites/arangosh.js
  js/client/modules/@arangodb/testsuites/backup.js
  js/client/modules/@arangodb/testsuites/dump.js
  js/client/modules/@arangodb/testsuites/foxxmanager.js
  js/client/modules/@arangodb/testsuites/importing.js
  js/client/modules/@arangodb/testsuites/queryCacheAuthorization.js
  js/client/modules/@arangodb/testsuites/readOnly.js
  js/client/modules/@arangodb/testsuites/recovery.js
  js/client/modules/@arangodb/testsuites/recovery_cluster_server.js
  js/client/modules/@arangodb/testsuites/replication.js
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testsuites/upgrade.js
  js/client/modules/@arangodb/testutils/client-tools.js
  js/client/modules/@arangodb/testutils/process-utils.js
  js/client/modules/@arangodb/testutils/test-utils.js
Labels: cla-signed

#20828 Fix filename handling in offline .sst file verification
  arangod/RestServer/ServerFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  tests/js/client/shell/shell-verify-sst-noncluster.js
Labels: cla-signed

#20770 improve debug facilities for shard synchronization, transactions and locks
  arangod/Aql/EngineInfoContainerDBServerServerBased.cpp
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/QueryRegistry.h
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/SynchronizeShard.cpp
  arangod/GeneralServer/RestHandler.cpp
  arangod/RestHandler/RestQueryHandler.cpp
  arangod/RestHandler/RestQueryHandler.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestTransactionHandler.h
  arangod/RestServer/QueryRegistryFeature.cpp
  arangod/RestServer/QueryRegistryFeature.h
  arangod/RocksDBEngine/RocksDBMetaCollection.cpp
  arangod/RocksDBEngine/RocksDBMetaCollection.h
  arangod/RocksDBEngine/RocksDBTransactionCollection.cpp
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Manager.h
  arangod/V8Server/v8-vocbase.cpp
  lib/Basics/ReadWriteLock.cpp
  lib/Basics/ReadWriteLock.h
  tests/Basics/ReadWriteLockTest.cpp
  tests/Transaction/ManagerTest.cpp
  tests/js/client/server_parameters/test-query-registry-contents-cluster.js
  tests/js/client/server_parameters/test-query-registry-contents-off-cluster.js
  tests/js/client/shell/test-trx-registry-contents-cluster.js
Labels: cla-signed

#20829 Fix filename handling in offline .sst file verification
  arangod/RestServer/ServerFeature.cpp
  arangod/RocksDBEngine/RocksDBEngine.cpp
  tests/js/client/shell/shell-verify-sst-noncluster.js
Labels: cla-signed

#20820 Make AQL query optimizer create less query execution plan permutations
  CHANGELOG
  arangod/Aql/CollectOptions.cpp
  arangod/Aql/CollectOptions.h
  arangod/Aql/ExecutionNode/CollectNode.cpp
  arangod/Aql/ExecutionNode/CollectNode.h
  arangod/Aql/ExecutionNode/ExecutionNode.cpp
  arangod/Aql/ExecutionNode/SortNode.cpp
  arangod/Aql/ExecutionNode/SortNode.h
  arangod/Aql/ExecutionPlan.cpp
  arangod/Aql/IResearchViewOptimizerRules.cpp
  arangod/Aql/Optimizer.cpp
  arangod/Aql/Optimizer.h
  arangod/Aql/OptimizerRules.cpp
  tests/js/client/aql/aql-optimizer-collect-methods.js
  tests/js/client/aql/aql-optimizer-rule-remove-collect-variables.js
  tests/js/client/aql/aql-optimizer-rule-remove-redundant-sorts.js
  tests/js/client/aql/aql-profiler.js
Labels: cla-signed

#20839 make upgrade tasks return their results
  arangod/IResearch/IResearchFeature.cpp
  arangod/VocBase/Methods/Upgrade.cpp
  arangod/VocBase/Methods/Upgrade.h
  arangod/VocBase/Methods/UpgradeTasks.cpp
  arangod/VocBase/Methods/UpgradeTasks.h
Labels: cla-signed

#20844 [3.11]: Make ArangoLanguageFeature unit test independent from system locale
  tests/RestServer/LanguageFeatureTest.cpp
Labels: cla-signed

#20849 [BTS-1856][3.11] Query: Protect access on member _execStats
  CHANGELOG
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/RestAqlHandler.cpp
Labels: cla-signed

#20833 [3.11] AsyncNode must not forward waiting result
  CHANGELOG
  arangod/Aql/AsyncExecutor.cpp
  arangod/Aql/AsyncExecutor.h
  arangod/Aql/SharedQueryState.h
  tests/Aql/AqlExecutorTestCase.cpp
  tests/Aql/AqlExecutorTestCase.h
  tests/Aql/AsyncExecutorTest.cpp
  tests/Aql/ExecutorTestHelper.h
  tests/Aql/WaitingExecutionBlockMock.cpp
  tests/Aql/WaitingExecutionBlockMock.h
Labels: cla-signed

#20815 BTS-1489: Race condition in AsioSocket shutdown when using SSL.
  CHANGELOG
  arangod/GeneralServer/Acceptor.h
  arangod/GeneralServer/AcceptorTcp.cpp
  arangod/GeneralServer/AcceptorTcp.h
  arangod/GeneralServer/AcceptorUnixDomain.cpp
  arangod/GeneralServer/AcceptorUnixDomain.h
  arangod/GeneralServer/AsioSocket.h
  arangod/GeneralServer/GeneralCommTask.cpp
  arangod/GeneralServer/GeneralCommTask.h
  arangod/GeneralServer/H2CommTask.cpp
  arangod/GeneralServer/H2CommTask.h
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/HttpCommTask.h
  arangod/GeneralServer/VstCommTask.cpp
  arangod/GeneralServer/VstCommTask.h
Labels: cla-signed

#20852 [3.11] Detach Thread getResponsibleServer
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
Labels: cla-signed

#20856 allow to disable fast lock round for transactions
  CHANGELOG
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Options.cpp
  arangod/Transaction/Options.h
  arangod/VocBase/Methods/Transactions.cpp
  tests/Network/ConnectionPoolTest.cpp
  tests/js/client/shell/shell-transaction-commit-abort-overwhelm-cluster.js
Labels: cla-signed

#20854 delete unused unfinished test code
  js/client/modules/@arangodb/testsuites/license.js
Labels: 3 - Testing, cla-signed

#20855 improve output of debugging APIs
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/QueryRegistry.cpp
  arangod/Aql/RestAqlHandler.cpp
  arangod/Aql/RestAqlHandler.h
  arangod/Transaction/Manager.cpp
  lib/Logger/LogContext.h
  lib/Logger/LogStructuredParamsAllowList.h
  lib/Logger/LoggerFeature.cpp
  tests/js/client/server_parameters/test-query-registry-contents-cluster.js
  tests/js/client/shell/test-trx-registry-contents-cluster.js
Labels: cla-signed

#20859 Remove an incorrect assertion that causes spurious test failures
  tests/Aql/Executor/AsyncExecutorTest.cpp
Labels: cla-signed

#20861 fix ASan errors in test
  arangod/RocksDBEngine/RocksDBEngine.cpp
  arangod/Scheduler/SupervisedScheduler.cpp
  arangod/Transaction/ManagerFeature.cpp
  lib/Logger/LogThread.cpp
Labels: cla-signed

#20860 Added metric `arangodb_logger_messages_dropped_total`
  CHANGELOG
  Documentation/Metrics/arangodb_logger_messages_dropped_total.yaml
  arangod/RestServer/LogBufferFeature.cpp
  arangod/RestServer/LogBufferFeature.h
  lib/Logger/LogThread.cpp
  lib/Logger/LogThread.h
  lib/Logger/Logger.cpp
  lib/Logger/Logger.h
  lib/Logger/LoggerFeature.h
  tests/js/client/server_parameters/log-dropped-messages-noncluster.js
Labels: cla-signed

#20796 FE-432: allow row clicks on all UI tables
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/listIndices/CollectionIndicesTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/listCollections/CollectionsTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/graphV2/listGraphs/GraphsTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/services/listServices/ServicesTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/users/listUsers/UsersTable.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/viewsList/ViewsTable.tsx
Labels: 1 Bug, 3 UI, cla-signed

#20862 try to improve non-deterministic test
  tests/IResearch/IResearchLinkTest.cpp
Labels: cla-signed

#20851 [BTS-1856][DEVEL] Query: Protect access on member _execStats
  CHANGELOG
  arangod/Aql/ClusterQuery.cpp
  arangod/Aql/ExecutionEngine.cpp
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  arangod/Aql/RestAqlHandler.cpp
Labels: cla-signed

#20867 only run the mixed in the 'single' run; split runs to give cluster la…
  tests/test-definitions.txt
Labels: 3 ImportExport, 3 - Testing, cla-signed

#20866 remove unused copy of xxhash
  3rdParty/fuerte/src/xxhash.h
Labels: cla-signed

#20863 EF-71: make maximum cache value size configurable
  CHANGELOG
  arangod/Cache/Cache.cpp
  arangod/Cache/Cache.h
  arangod/Cache/CacheManagerFeature.cpp
  arangod/Cache/CacheOptionsFeature.cpp
  arangod/Cache/CacheOptionsProvider.h
  arangod/Cache/Manager.cpp
  arangod/Cache/Manager.h
  arangod/RocksDBEngine/RocksDBCollection.cpp
  arangod/RocksDBEngine/RocksDBCollection.h
  arangod/RocksDBEngine/RocksDBEdgeIndex.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.cpp
  arangod/RocksDBEngine/RocksDBPrimaryIndex.h
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/client/server_parameters/max-cache-value-size.js
Labels: cla-signed

#20771 Prioritize requests for transaction commits / aborts
  CHANGELOG
  arangod/Aql/RestAqlHandler.cpp
  arangod/Cluster/ClusterTrxMethods.cpp
  arangod/GeneralServer/RequestLane.h
  arangod/GeneralServer/RestHandler.cpp
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestCollectionHandler.h
  arangod/RestHandler/RestCursorHandler.cpp
  arangod/RestHandler/RestCursorHandler.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestTransactionHandler.h
  arangod/Transaction/Manager.cpp
  arangod/Transaction/Options.cpp
  arangod/Transaction/Options.h
  arangod/VocBase/Methods/Transactions.cpp
  js/client/modules/@arangodb/test-helper.js
  tests/js/client/shell/shell-transaction-commit-abort-overwhelm-cluster.js
Labels: cla-signed

#20881 Use the network feature in the remote executor.
  arangod/Aql/Executor/RemoteExecutor.cpp
  arangod/Aql/Executor/RemoteExecutor.h
Labels: cla-signed
