Repository arangodb/arangodb, pull requests merged in 2025-05, with the labels that each got.

#21742 Add more visibility to catch sleeping barber
  CHANGELOG
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionBlockImpl.tpp
Labels: cla-signed

#21698 Fix duplicate collection names [BTS-2111]
  CHANGELOG
  arangod/Cluster/ClusterInfo.cpp
  arangod/Cluster/ClusterInfo.h
  arangod/IResearch/IResearchInvertedIndex.cpp
  tests/IResearch/IResearchFeatureTest.cpp
  tests/js/client/shell/shell-duplicate-collection-names-cluster.js
Labels: cla-signed

#21749 Stabilize test for ASAN using larger timeout, take2
  tests/js/client/shell/shell-duplicate-collection-names-cluster.js
Labels: cla-signed

#21738 Fix data race in AgencyCache::applyTestTransaction
  tests/Mocks/Servers.cpp
Labels: cla-signed

#21747 Fix exec context in future coroutines
  lib/Async/include/Async/async.h
  lib/Async/include/Async/context.h
  lib/Futures/include/Futures/coro-helper.h
  tests/Futures/CMakeLists.txt
  tests/Futures/FutureCoroutineTest.cpp
Labels: cla-signed

#21748 add the possibility to specify arangosh and testing.js arguments while launching the pipeline
  .circleci/base_config.yml
  .circleci/config.yml
  .circleci/generate_config.py
Labels: 3 - Testing, cla-signed

#21704 Fix creation of distributeShardsLike collections [BTS-2093, BTS-2106]
  CHANGELOG
  arangod/Agency/MoveShard.cpp
  arangod/Cluster/ClusterCollectionMethods.cpp
  arangod/Cluster/CreateCollection.cpp
  arangod/Cluster/TakeoverShardLeadership.cpp
  arangod/Cluster/Utils/PlanCollectionEntry.h
  arangod/Cluster/Utils/PlanCollectionToAgencyWriter.h
  tests/js/client/shell/shell-move-shard-collection-creation-cluster.js
Labels: cla-signed

#21753 Handle corrupt URLs in HTTP requests gracefully [BTS-2112]
  CHANGELOG
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/HttpCommTask.h
Labels: cla-signed

#21754 Stabilize write concern test
  CHANGELOG
  tests/js/client/shell/shell-write-concern-read-only-metric-cluster.js
Labels: cla-signed

#21737 Improve vector index error message
  CHANGELOG
  arangod/Aql/Function/VectorFunctions.cpp
Labels: cla-signed

#21752 hide credentials from tests
  scripts/test/site_config.py
Labels: 3 - Testing, cla-signed

#21760 [3.11] Fix data race in connection cache
  lib/SimpleHttpClient/ConnectionCache.cpp
  lib/SimpleHttpClient/ConnectionCache.h
Labels: cla-signed

#21761 optimise wait and detach
  CHANGELOG
  arangod/Aql/ModificationExecutorHelpers.cpp
  lib/Futures/include/Futures/Future.h
Labels: cla-signed

#21764 Bug fix/fix non maintainer mode
  .circleci/generate_config.py
  arangod/RestServer/arangod.h
  client-tools/Shell/arangosh.h
  client-tools/Utils/ArangoClient.h
  client-tools/VPack/arangovpack.h
Labels: 3 Build, cla-signed

#21730 Adapt CHANGELOG for BTS-2086
  CHANGELOG
Labels: cla-signed

#21766 don't let libc abort it
  js/client/modules/@arangodb/testutils/instance.js
  lib/Basics/PhysicalMemory.cpp
Labels: cla-signed

#21750 Refactor rest handlers into coroutines
  arangod/Agency/RestAgencyHandler.cpp
  arangod/Agency/RestAgencyHandler.h
  arangod/GeneralServer/RestHandler.h
  arangod/RestHandler/RestAdminClusterHandler.cpp
  arangod/RestHandler/RestAdminClusterHandler.h
  arangod/RestHandler/RestAdminLogHandler.cpp
  arangod/RestHandler/RestAdminLogHandler.h
  arangod/RestHandler/RestDocumentHandler.cpp
  arangod/RestHandler/RestDocumentHandler.h
  arangod/RestHandler/RestGraphHandler.cpp
  arangod/RestHandler/RestGraphHandler.h
  arangod/RestHandler/RestImportHandler.cpp
  arangod/RestHandler/RestImportHandler.h
  arangod/RestHandler/RestLogHandler.cpp
  arangod/RestHandler/RestLogHandler.h
  arangod/RestHandler/RestLogInternalHandler.cpp
  arangod/RestHandler/RestLogInternalHandler.h
  arangod/RestHandler/RestMetricsHandler.cpp
  arangod/RestHandler/RestMetricsHandler.h
  arangod/RestHandler/RestReplicationHandler.cpp
  arangod/RestHandler/RestReplicationHandler.h
  arangod/RestHandler/RestTransactionHandler.cpp
  arangod/RestHandler/RestTransactionHandler.h
  arangod/RestHandler/RestUsageMetricsHandler.cpp
  arangod/RestHandler/RestUsageMetricsHandler.h
Labels: cla-signed

#21768 Rename AsyncRegistryServer/ to SystemMonitor/AsyncRegistry
  arangod/AsyncRegistryServer/PrettyPrinter/.gdbinit
  arangod/AsyncRegistryServer/Stacktrace/CMakeLists.txt
  arangod/CMakeLists.txt
  arangod/GeneralServer/GeneralServerFeature.cpp
  arangod/RestServer/arangod_includes.h
  arangod/SystemMonitor/AsyncRegistry/CMakeLists.txt
  arangod/SystemMonitor/AsyncRegistry/Feature.cpp
  arangod/SystemMonitor/AsyncRegistry/Feature.h
  arangod/SystemMonitor/AsyncRegistry/Metrics.cpp
  arangod/SystemMonitor/AsyncRegistry/Metrics.h
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/.gdbinit
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/README.md
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/__init__.py
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/asyncregistry/__init__.py
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/asyncregistry/gdb_data.py
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/asyncregistry/gdb_forest.py
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/asyncregistry/gdb_printer.py
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/asyncregistry/stacktrace.py
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/pretty-printer.py
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/tests/__init__.py
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/tests/test_forest.py
  arangod/SystemMonitor/AsyncRegistry/RestHandler.cpp
  arangod/SystemMonitor/AsyncRegistry/RestHandler.h
  arangod/SystemMonitor/CMakeLists.txt
  lib/Containers/CMakeLists.txt
  lib/Containers/Forest/CMakeLists.txt
  lib/Containers/Forest/depth_first.h
  lib/Containers/Forest/forest.h
  tests/AsyncRegistryServer/CMakeLists.txt
  tests/CMakeLists.txt
  tests/Containers/CMakeLists.txt
  tests/Containers/ForestTest.cpp
Labels: cla-signed

#21779 Get rid of use-after-free in async registry
  lib/TaskMonitoring/include/TaskMonitoring/task.h
  lib/TaskMonitoring/task.cpp
  tests/TaskMonitoring/TaskRegistryTest.cpp
Labels: cla-signed

#21778 Fix LogContext memory leak
  CHANGELOG
  lib/Logger/LogContext.cpp
  lib/Logger/LogContext.h
  lsan_arangodb_suppressions.txt
Labels: cla-signed

#21774 More visibility to catch a sleeper
  CHANGELOG
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionBlockImpl.tpp
Labels: cla-signed

#21780 Fix matching multiple --testCase options
  js/common/modules/jsunity.js
Labels: cla-signed

#21759 Feature/fresh lz4 1
  CHANGELOG
Labels: cla-signed

#21763 make sure the fuzzer uses its own clones of the connection, and not the application flow ones
  client-tools/Shell/V8ClientConnection.cpp
  client-tools/Shell/V8ClientConnection.h
  tests/js/client/fuzz/http-fuzz-fp.js
Labels: 3 - Testing, cla-signed

#21784 track the progress on the index buildup
  tests/js/client/shell/shell-index-visibility-nocov-fp.js
Labels: 3 - Testing, cla-signed

#21720 Add tests for async registry pretty printer
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/README.md
  arangod/SystemMonitor/AsyncRegistry/PrettyPrinter/src/asyncregistry/stacktrace.py
  tests/CMakeLists.txt
  tests/SystemMonitor/AsyncRegistry/CMakeLists.txt
  tests/SystemMonitor/AsyncRegistry/PrettyPrinter/CMakeLists.txt
  tests/SystemMonitor/AsyncRegistry/PrettyPrinter/gdb_integration/CMakeLists.txt
  tests/SystemMonitor/AsyncRegistry/PrettyPrinter/gdb_integration/async_registry_gdb_pretty_printer_test.cpp
  tests/SystemMonitor/AsyncRegistry/PrettyPrinter/gdb_integration/test.gdbscript
  tests/SystemMonitor/AsyncRegistry/PrettyPrinter/unittests/CMakeLists.txt
  tests/SystemMonitor/AsyncRegistry/PrettyPrinter/unittests/tests/__init__.py
  tests/SystemMonitor/AsyncRegistry/PrettyPrinter/unittests/tests/test_forest.py
  tests/SystemMonitor/AsyncRegistry/PrettyPrinter/unittests/tests/test_stacktrace.py
  tests/SystemMonitor/CMakeLists.txt
Labels: cla-signed

#21786 store connection and disconnect from the ones to be replaced by non-cacheables
  client-tools/Shell/V8ClientConnection.cpp
  tests/js/client/fuzz/http-fuzz-fp.js
Labels: 3 - Testing, cla-signed
