Repository arangodb/arangodb, pull requests merged in 2025-04, with the labels that each got.

#21696 Remove overeager assertion
  CHANGELOG
  arangod/Aql/RestAqlHandler.cpp
Labels: cla-signed

#21702 Bug fix 3.11/busy wait and detach
  ARANGO-VERSION
  CHANGELOG
  arangod/Aql/ModificationExecutorHelpers.cpp
Labels: cla-signed

#21705 only set value on the structure if we actually have that instrumentation
  js/client/modules/@arangodb/testutils/san-file-handler.js
Labels: 3 - Testing, cla-signed

#21701 Docs: Adjust descriptions of `--ssl.keyfile` startup option
  arangod/GeneralServer/SslServerFeature.cpp
Labels: 3 Documentation, cla-signed

#21695 Rename `diskusage` to `diskUsage` in license API
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
  js/common/modules/@arangodb/common.js
Labels: 1 Bug, 3 API, cla-signed

#21707 Update `ERROR_ONLY_ENTERPRISE` description for 3.12.5+
  lib/Basics/errors.dat
Labels: 3 Documentation, cla-signed

#21713 Set golang version and rclone-arangodb revision for rclone release
  CHANGELOG
  VERSIONS
Labels: 3 Packaging, cla-signed

#21715 [3.12.4] Fix crash during async prefetch
  CHANGELOG
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionEngine.cpp
  scripts/test/arangosh.py
  tests/js/client/aql/aql-optimizer-rule-async-prefetch-noncluster-fp.js
Labels: 9 Ready to Merge, cla-signed

#21717 CircleCI: update rclone usage (after it was removed from oskar)
  .circleci/base_config.yml
Labels: 3 - Testing, cla-signed

#21718 disable vector index on ARM for now, faiss is known to be crashy now.
  js/client/modules/@arangodb/testutils/client-tools.js
  tests/js/client/aql/vector/aql-vector-agency-wrong-definition-cluster.js
  tests/js/client/aql/vector/aql-vector-create-and-remove.js
  tests/js/client/aql/vector/aql-vector-full-count.js
  tests/js/client/aql/vector/aql-vector-nprobe.js
  tests/js/client/aql/vector/aql-vector.js
Labels: 3 Index, 3 - Testing, cla-signed

#21678 Fix selectivity estimate based optimizer rule in cluster
  arangod/Aql/Optimizer/Rule/OptimizerRuleCollectWithIndex.cpp
  arangod/RocksDBEngine/RocksDBVPackIndex.cpp
  tests/js/client/aql/aql-index-collect.js
Labels: cla-signed

#21726 Upgrade OpenSSL to 3.5.0 (3.11)
  CHANGELOG
  VERSIONS
Labels: 3 Build, OpenSSL, cla-signed

#21725 Upgrade OpenSSL to 3.5.0
  .circleci/base_config.yml
  .circleci/config.yml
  CHANGELOG
  VERSIONS
Labels: 3 Build, OpenSSL, cla-signed

#21719 Add dependencies for building locally
  CONTRIBUTING.md
Labels: cla-signed

#21709 Fix crash during async prefetch
  CHANGELOG
  arangod/Aql/ExecutionBlock.cpp
  arangod/Aql/ExecutionBlock.h
  arangod/Aql/ExecutionBlockImpl.h
  arangod/Aql/ExecutionBlockImpl.tpp
  arangod/Aql/ExecutionEngine.cpp
  tests/js/client/aql/aql-optimizer-rule-async-prefetch-noncluster-fp.js
Labels: cla-signed

#21677 Make RestCollectionHandler and RestIndexHandler async
  arangod/RestHandler/RestCollectionHandler.cpp
  arangod/RestHandler/RestCollectionHandler.h
  arangod/RestHandler/RestIndexHandler.cpp
  arangod/RestHandler/RestIndexHandler.h
  arangod/VocBase/Methods/Collections.cpp
  arangod/VocBase/Methods/Collections.h
  lib/Async/include/Async/async.h
  tests/Async/AsyncTest.cpp
Labels: cla-signed

#21729 optionally choose pre-packaged node modules
  .circleci/base_config.yml
  .circleci/config.yml
  CMakeLists.txt
  cmake/frontend/aardvark.cmake
  scripts/docker/build/linux/Dockerfile.arm64
  scripts/docker/build/linux/Dockerfile.x86-64
  scripts/docker/build/linux/tools/install.sh
Labels: 3 Build, 3 UI, cla-signed

#21732 Sleeping barber in SharedQueryState
  .circleci/base_config.yml
  .circleci/config.yml
  CHANGELOG
  arangod/Aql/SharedQueryState.cpp
  arangod/Aql/SharedQueryState.h
  js/client/modules/@arangodb/testutils/client-tools.js
  tests/js/client/aql/vector/aql-vector-create-and-remove.js
  tests/js/client/aql/vector/aql-vector-full-count.js
  tests/js/client/aql/vector/aql-vector-nprobe.js
  tests/js/client/aql/vector/aql-vector.js
Labels: 1 Bug, 3 AQL, cla-signed
