Repository arangodb/arangodb, pull requests merged in 2025-02, with the labels that each got.

#21580 Update compiler to clang-19
  .circleci/base_config.yml
  .circleci/config.yml
  CHANGELOG
  VERSIONS
  scripts/docker/build/linux/Dockerfile.arm64
  scripts/docker/build/linux/Dockerfile.x86-64
  scripts/docker/build/linux/scripts/create-sccache-hardlinks.sh
  scripts/docker/build/linux/static/llvm.sources
  scripts/docker/build/linux/static/ubuntu.sources
  scripts/docker/build/linux/tools/install.sh
Labels: 3 Build, cla-signed

#21581 Chore 3.11/openldap 2.6.9
  CHANGELOG
Labels: 3 Build, cla-signed

#21586 make sure that the client request timeout is handled via the central option
  js/client/modules/@arangodb/testutils/client-tools.js
Labels: 3 - Testing, cla-signed

#21583 [3.11] [BTS-2074] Fix load balancing Foxx test
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/foxxes.js
Labels: 1 Bug, 3 UI, cla-signed

#21590 increase non-instrumented timeout
  js/client/modules/@arangodb/testutils/client-tools.js
Labels: 3 - Testing, cla-signed

#21588 more idle stacks (#21584)
  js/client/modules/@arangodb/testutils/filter_gdb_stacks.json
Labels: 3 - Testing, cla-signed

#21582 [BTS-2074] Fix load balancing Foxx test
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/foxxes.js
Labels: 1 Bug, 3 UI, cla-signed

#21589 make sure that the client request timeout is handled via the central option
  js/client/modules/@arangodb/testutils/client-tools.js
Labels: 3 - Testing, cla-signed

#21585 Web interface: Make Try it out button in Swagger UI stand out more
  js/server/assets/swagger/index.css
Labels: 3 Documentation, 3 UI, cla-signed

#21569 Use archer to ignore errors in openmp
  .circleci/base_config.yml
  scripts/docker/test/arangodb-test.Dockerfile
  scripts/docker/test/llvm.sources
  utils/llvm-symbolizer-server.py
Labels: 3 Index, 3 - Testing, TSan, cla-signed

#21591 Web interface: Make Try out button in Swagger UI stand out more (#21585)
  js/server/assets/swagger/index.css
Labels: 3 Documentation, 3 UI, cla-signed

#21592 more time for coverage
  tests/js/client/shell/shell-admin-cluster-rebalance.js
Labels: 3 - Testing, cla-signed

#21595 Fix unstable network pool test
  CHANGELOG
  tests/Network/ConnectionPoolTest.cpp
Labels: cla-signed

#21594 Bug fix/stretch timout coverage
  tests/js/client/shell/shell-replication-auto-repair-cluster.js
  tests/js/common/shell/shell-index.js
Labels: 3 - Testing, cla-signed

#21593 also assert that we don't have that string
  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
Labels: 3 - Testing, cla-signed

#21587 Keep LogContext during thread handovers
  arangod/Cluster/AgencyCallbackRegistry.h
  arangod/Network/NetworkFeature.cpp
  arangod/Replication2/ReplicatedLog/WaitForBag.cpp
  arangod/Replication2/ReplicatedLog/WaitForBag.h
  arangod/Scheduler/Scheduler.h
  lib/Async/include/Async/async.h
  lib/Logger/LogContext.cpp
  lib/Logger/LogContext.h
  tests/Logger/LogContextTest.cpp
Labels: cla-signed

#21540 Improve geo index performance in the cluster [BTS_2046]
  CHANGELOG
  arangod/Aql/OptimizerRules.cpp
  tests/js/server/aql/aql-geo-cluster.js
Labels: cla-signed

#21598 Deactivate cluster overwhelm on agents [BTS-2077]
  CHANGELOG
  arangod/Scheduler/SchedulerFeature.cpp
Labels: cla-signed

#21596 [BTS-2074] Forward response body as-is
  js/apps/system/_admin/aardvark/APP/foxxes.js
  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
Labels: 1 Bug, 3 UI, 3 Foxx, cla-signed

#21600 Deactivate cluster overwhelm on agents [BTS-2077]
  CHANGELOG
  arangod/Scheduler/SchedulerFeature.cpp
Labels: cla-signed

#21601 forward the deadline into sub-shell arangoshs
  client-tools/Shell/V8ShellFeature.cpp
  client-tools/Shell/V8ShellFeature.h
  client-tools/Shell/v8-deadline.cpp
  js/client/modules/@arangodb/testutils/testrunners.js
  lib/V8/v8-deadline.h
  lib/V8/v8-no-deadline.cpp
Labels: 3 - Testing, cla-signed

#21604 [BTS-2074] [3.11] Forward response body as-is
  js/apps/system/_admin/aardvark/APP/foxxes.js
  tests/js/client/load-balancing/load-balancing-foxx-installation-noauth-cluster.js
Labels: 1 Bug, 3 UI, 3 Foxx, cla-signed

#21603 fix timeout
  client-tools/Shell/V8ShellFeature.cpp
  client-tools/Shell/v8-deadline.cpp
  js/client/modules/@arangodb/test-helper.js
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/agency.js
  js/client/modules/@arangodb/testutils/testrunners.js
Labels: 3 - Testing, cla-signed

#21602 Feature 3.11/execution deadline cli trigger
  client-tools/Shell/V8ShellFeature.cpp
  client-tools/Shell/V8ShellFeature.h
  client-tools/Shell/v8-deadline.cpp
  js/client/modules/@arangodb/test-helper.js
  js/client/modules/@arangodb/testsuites/rta_makedata.js
  js/client/modules/@arangodb/testutils/agency.js
  js/client/modules/@arangodb/testutils/testrunners.js
  lib/V8/v8-deadline.h
  lib/V8/v8-no-deadline.cpp
Labels: 3 - Testing, cla-signed

#21606 Docs: Improve the descriptions of a few startup options
  client-tools/Dump/DumpFeature.cpp
  client-tools/Export/ExportFeature.cpp
  client-tools/Import/ImportFeature.cpp
  lib/Logger/LoggerFeature.cpp
Labels: 3 Documentation, cla-signed

#21608 Another try to stabilize NetworkConnectionPool test
  tests/Network/ConnectionPoolTest.cpp
Labels: cla-signed

#21555 Bug fix/forward port test precision
  tests/js/client/shell/shell-index-visibility-nocov-fp.js
Labels: 3 - Testing, cla-signed

#21610 FE-515 - fix to ensure unique keys to prevent incorrect react reconciliation (Query Editor UI > Query results)
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/query/QueryContextProvider.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/CancelQueryButton.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryExecuteResult.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryProfileResult.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryResultError.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryResultLoading.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/QueryResults.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/queryResults/RemoveResultButton.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/useQueryExecutors.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/query/useQueryResultHandlers.tsx
Labels: cla-signed

#21612 Update `startLocalCluster.sh` to start with vector index
  scripts/startLocalCluster.sh
Labels: cla-signed

#21618 print out the loop count as well
  tests/js/client/shell/shell-index-visibility-nocov-fp.js
Labels: 3 - Testing, cla-signed

#21611 Disable the creation of vector index with 0 nLists
  CHANGELOG
  arangod/Indexes/VectorIndexDefinition.h
  tests/js/client/aql/vector/aql-vector-create-and-remove.js
Labels: 3 Index, cla-signed

#21614 [3.11] [BTS-2078] Fix race between start&detach thread
  arangod/Scheduler/SupervisedScheduler.cpp
  lib/Basics/Thread.h
  tests/CMakeLists.txt
  tests/Scheduler/SupervisedScheduler.cpp
Labels: TSan, cla-signed

#21619 Added missing 'to_string' implementation
  arangod/Aql/AqlCall.cpp
Labels: cla-signed

#21629 Upgrade OpenSSL to 3.4.1
  CHANGELOG
  VERSIONS
Labels: OpenSSL, cla-signed

#21630 Upgrade OpenSSL to 3.4.1
  .circleci/base_config.yml
  .circleci/config.yml
  CHANGELOG
  VERSIONS
Labels: cla-signed

#21631 FE-497 - fix query options input parsing
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/query/editor/QueryOptionsTab.tsx
Labels: cla-signed

#21632 Do periodic compactions more often
  CHANGELOG
  arangod/RocksDBEngine/RocksDBOptionFeature.cpp
Labels: cla-signed

#21634 Fix libicu64, this time properly
  3rdParty/icu-legacy/CMakeLists.txt
Labels: cla-signed

#21633 Fix flaky vector test
  tests/js/client/aql/vector/aql-vector-create-and-remove.js
Labels: 3 Index, 3 - Testing, cla-signed

#21620 The agency supervision clears finished jobs too quickly
  CHANGELOG
  arangod/Agency/Supervision.cpp
  tests/Agency/SupervisionTest.cpp
Labels: 1 Bug, 3 Cluster, cla-signed

#18876 ArangoSearch: Add update consistency test scenarios
  tests/js/client/shell/arangosearch-update-consistency-aliasview.js
  tests/js/client/shell/arangosearch-update-consistency-view.js
  tests/js/client/shell/arangosearch-update-consistency.js
Labels: 3 - Testing, 3 ArangoSearch, cla-signed

#21627 [3.11] The agency supervision clears finished jobs too quickly
  CHANGELOG
  arangod/Agency/Supervision.cpp
  tests/Agency/SupervisionTest.cpp
Labels: 1 Bug, 3 Cluster, cla-signed

#21640 cig backport
  CHANGELOG
  arangod/Aql/SharedQueryState.cpp
  arangod/Aql/SharedQueryState.h
Labels: 1 Bug, 3 AQL, cla-signed

#21637 moved FAISS to arangod/CMakeLists.txt
  3rdParty/CMakeLists.txt
  3rdParty/README_maintainers.md
  CHANGELOG
  CMakeLists.txt
  arangod/CMakeLists.txt
  tests/CMakeLists.txt
Labels: 3 Build, cla-signed

#21645 cig backport
  CHANGELOG
  arangod/Aql/SharedQueryState.cpp
  arangod/Aql/SharedQueryState.h
Labels: 1 Bug, 3 AQL, cla-signed

#21643 Fix query logging with query cache
  CHANGELOG
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
  tests/js/client/server_parameters/test-query-logging-with-cache-noncluster.js
  tests/js/client/server_parameters/test-query-logging-with-cache.js
Labels: cla-signed

#21644 Remove omp dependancy from client tools
  client-tools/Backup/CMakeLists.txt
  client-tools/Benchmark/CMakeLists.txt
  client-tools/Dump/CMakeLists.txt
  client-tools/Export/CMakeLists.txt
  client-tools/Import/CMakeLists.txt
  client-tools/Restore/CMakeLists.txt
  client-tools/Utils/CMakeLists.txt
  client-tools/VPack/CMakeLists.txt
  lib/CMakeLists.txt
Labels: cla-signed

#21648 do not install headers
  CMakeLists.txt
Labels: 3 Packaging, cla-signed

#21646 Fix index api shortly after successful creation [BTS-2044]
  CHANGELOG
  arangod/RestHandler/RestIndexHandler.cpp
Labels: cla-signed
