Repository arangodb/arangodb, pull requests merged in 2025-07, with the labels that each got.

#21829 BTS-2139: Accept `z` in GEO position definition
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Function/GeoFunctions.cpp
  lib/Geo/GeoJson.cpp
  tests/Geo/GeoJsonTest.cpp
  tests/js/client/aql/aql-geo-distance-range.js
Labels: cla-signed

#21824 FE-664 | Added innerProduct metric in vector index form
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/CollectionIndex.types.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/collections/indices/addIndex/vectorIndex/useCreateVectorIndex.ts
Labels: cla-signed

#21838 Handle corrupt HTTP/1.1 headers more gracefully
  CHANGELOG
  arangod/GeneralServer/HttpCommTask.cpp
  arangod/GeneralServer/HttpCommTask.h
Labels: cla-signed

#21837 Polish api/aql recording stuff
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestServer/ApiRecordingFeature.cpp
  arangod/RestServer/ApiRecordingFeature.h
  lib/Logger/LoggerFeature.cpp
  tests/js/client/shell/recording.js
Labels: cla-signed

#21790 QA-609: Add a way to generate driver tests in regular ci flows
  .circleci/base_config.yml
  .circleci/build_test_image.yml
  .circleci/config.yml
  .circleci/generate_config.py
  js/client/modules/@arangodb/testsuites/go.js
  js/client/modules/@arangodb/testsuites/java.js
  js/client/modules/@arangodb/testsuites/js.js
  js/client/modules/@arangodb/testsuites/permissions_client.js
  js/client/modules/@arangodb/testutils/instance-manager.js
  js/client/modules/@arangodb/testutils/instance.js
  js/client/modules/@arangodb/testutils/result-processing.js
  js/client/modules/@arangodb/testutils/sutcheckers/transactions.js
  scripts/docker/build-image.sh
  scripts/docker/build-manifest.sh
  scripts/docker/determine-tag.sh
  scripts/docker/go-test/Dockerfile
  scripts/docker/java-test/Dockerfile
  scripts/docker/js-test/Dockerfile
  scripts/docker/test/Dockerfile
  scripts/docker/test/build-image.sh
  scripts/test/site_config.py
  scripts/test/test_config.py
  scripts/test/test_launch_controller.py
  tests/arangojs-test-definitions.txt
  tests/go-test-definitions.txt
  tests/java-test-definitions.txt
  tests/js/client/permissions/filesystem.js
  tests/js/client/shell/shell-transactions.js
Labels: 3 - Testing, cla-signed

#21832 list the used ports all through out the fuzzing
  js/client/modules/@arangodb/testutils/instance-manager.js
  tests/js/client/fuzz/http-fuzz-fp.js
Labels: 3 - Testing, cla-signed

#21839 Fix bug in AQL function PERCENTILE [BTS-2169]
  CHANGELOG
  arangod/Aql/Function/StatisticsFunctions.cpp
  tests/js/client/aql/aql-functions.js
Labels: cla-signed

#21819 Bug fix/improve visualizer performance
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/aardvark.js
  tests/js/client/shell/api/aardvark-graphvisualizer.js
Labels: cla-signed

#21849 longer timeout for instrumented runs
  tests/js/client/shell/shell-in-background-failures-noncluster-fp.js
Labels: 3 - Testing, cla-signed

#21846 Extend logging for vector cosine test
  tests/js/client/aql/vector/aql-vector.js
Labels: cla-signed

#21851 Fix TSAN error in trackExecutionStart and trackExecutionEnd
  arangod/Aql/Query.cpp
  arangod/Aql/Query.h
Labels: cla-signed

#21855 longer timeouts for coverage
  tests/js/client/resilience/move/moving-shards-cluster.inc
Labels: cla-signed

#21860 Add switch --database.auto-upgrade-full-compaction
  CHANGELOG
  arangod/RestServer/UpgradeFeature.cpp
  arangod/RestServer/UpgradeFeature.h
  lib/Basics/exitcodes.dat
Labels: cla-signed

#21872 even longer sleeps for coverage
  tests/js/client/resilience/move/moving-shards-cluster.inc
Labels: 3 - Testing, cla-signed

#21877 adjust counters
  lib/V8/v8-utils.cpp
Labels: 3 - Testing, cla-signed

#21875 Fix flaky test `acquire_endpoint`
  tests/Mocks/MockTcpDummyServer.h
  tests/Network/ConnectionPoolTest.cpp
Labels: 3 - Testing, cla-signed

#21876 Hotfix: bts-2152 fix overfetch input on parallel traversals
  CHANGELOG
  arangod/Aql/BlocksWithClients.cpp
  arangod/Aql/BlocksWithClients.h
  arangod/Aql/DistributeClientBlock.cpp
  arangod/Aql/DistributeClientBlock.h
  arangod/Aql/Executor/ScatterExecutor.cpp
  arangod/Aql/Executor/ScatterExecutor.h
  tests/Aql/Executor/AsyncExecutorTest.cpp
  tests/Aql/WaitingExecutionBlockMock.cpp
  tests/Aql/WaitingExecutionBlockMock.h
  tests/Mocks/MockTcpDummyServer.h
  tests/Network/ConnectionPoolTest.cpp
Labels: 3 Graph, cla-signed

#21859 Fix geo point definition to accept z value
  CHANGELOG
  arangod/Aql/AqlFunctionFeature.cpp
  arangod/Aql/Functions.cpp
  lib/Geo/GeoJson.cpp
  tests/Geo/GeoJsonTest.cpp
  tests/js/common/aql/aql-geo-distance-range.js
Labels: cla-signed

#21868 Fix BTS-2182 filters not pushed in Traversal node
  CHANGELOG
  arangod/Aql/Condition.cpp
  scripts/startLocalCluster.sh
  tests/js/client/aql/aql-optimizer-rule-remove-filter-covered-by-traversal-spec.js
Labels: cla-signed

#21891 Fix miscounting bug for scheduled SynchronizeShard jobs [BTS-2202]
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
Labels: 1 Bug, 3 Cluster, cla-signed

#21894 Fix miscounting bug for scheduled SynchronizeShard jobs [BTS-2202]
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
Labels: 1 Bug, 3 Cluster, cla-signed

#21895 Revert an accidental change in a debug script
  scripts/startLocalCluster.sh
Labels: cla-signed

#21890 [BTS-2201] Don't apply index-collect optimizer rule to empty collection
  CHANGELOG
  arangod/Aql/Executor/IndexAggregateScanExecutor.cpp
  arangod/Aql/Executor/IndexAggregateScanExecutor.h
  tests/js/client/aql/aql-index-collect.js
Labels: 1 Bug, 3 Optimizer, cla-signed
