Repository arangodb/arangodb, pull requests merged in 2025-03, with the labels that each got.

#21654 Fix index api shortly after successful creation
  CHANGELOG
  arangod/RestHandler/RestIndexHandler.cpp
Labels: cla-signed

#21647 Fix vector index comparison in maintance
  CHANGELOG
  arangod/Indexes/IndexFactory.cpp
  tests/js/client/aql/vector/aql-vector-agency-wrong-definition-cluster.js
Labels: 3 Cluster, 3 Index, cla-signed

#21655 Fixes a bug with unintentional double-log-line spam.
  CHANGELOG
  lib/Logger/LoggerFeature.cpp
Labels: cla-signed

#21652 FE-528: adds diskusage license info to UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
  js/apps/system/_admin/aardvark/APP/frontend/scss/_alert.scss
Labels: cla-signed

#21649 Fix index api shortly after successful creation [BTS-2044]
  CHANGELOG
  arangod/RestHandler/RestIndexHandler.cpp
Labels: cla-signed

#21660 add cgroups v2 memory limit detection
  scripts/test/arangosh.py
Labels: cla-signed

#21662 FE-503 - fix losing bind params when resizing query editor
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/views/query/editor/QueryEditorPane.tsx
Labels: cla-signed

#21570 Async registry gdb pretty print
  arangod/AsyncRegistryServer/PrettyPrinter/.gdbinit
  arangod/AsyncRegistryServer/PrettyPrinter/README.md
  arangod/AsyncRegistryServer/PrettyPrinter/__init__.py
  arangod/AsyncRegistryServer/PrettyPrinter/src/asyncregistry/__init__.py
  arangod/AsyncRegistryServer/PrettyPrinter/src/asyncregistry/gdb_data.py
  arangod/AsyncRegistryServer/PrettyPrinter/src/asyncregistry/gdb_forest.py
  arangod/AsyncRegistryServer/PrettyPrinter/src/asyncregistry/gdb_printer.py
  arangod/AsyncRegistryServer/PrettyPrinter/src/asyncregistry/stacktrace.py
  arangod/AsyncRegistryServer/PrettyPrinter/src/pretty-printer.py
  arangod/AsyncRegistryServer/PrettyPrinter/src/tests/__init__.py
  arangod/AsyncRegistryServer/PrettyPrinter/src/tests/test_forest.py
Labels: cla-signed

#21571 Update metrics, improve async registry documentation and some refactoring
  Documentation/Metrics/arangodb_async_existing_promises.yaml
  Documentation/Metrics/arangodb_async_existing_thread_registries.yaml
  Documentation/Metrics/arangodb_async_promises_total.yaml
  Documentation/Metrics/arangodb_async_ready_for_deletion_promises.yaml
  Documentation/Metrics/arangodb_async_registered_promises.yaml
  Documentation/Metrics/arangodb_async_registered_threads.yaml
  Documentation/Metrics/arangodb_async_running_threads.yaml
  Documentation/Metrics/arangodb_async_thread_registries_total.yaml
  Documentation/Metrics/arangodb_async_threads_total.yaml
  arangod/AsyncRegistryServer/CMakeLists.txt
  arangod/AsyncRegistryServer/Feature.cpp
  arangod/AsyncRegistryServer/RestHandler.cpp
  arangod/AsyncRegistryServer/Stacktrace/CMakeLists.txt
  arangod/AsyncRegistryServer/Stacktrace/depth_first.h
  arangod/AsyncRegistryServer/Stacktrace/forest.h
  lib/Async/Registry/Metrics.h
  lib/Async/Registry/registry.cpp
  lib/Async/Registry/registry.h
  lib/Async/Registry/registry_variable.cpp
  lib/Async/Registry/thread_registry.cpp
  lib/Async/Registry/thread_registry.h
  tests/AsyncRegistryServer/CMakeLists.txt
  tests/AsyncRegistryServer/StacktraceTest.cpp
Labels: cla-signed

#21609 FE-482 - fix multiple issues with search view UI
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/react/src/components/jsonEditor/ControlledJSONEditor.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/View.types.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/ArangoSearchJSONEditor.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/ArangoSearchViewForm.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/SearchJSONSchema.ts
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/linksEditor/AnalyzersDropdown.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/linksEditor/FieldsDropdown.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/linksEditor/LinksDetails.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/arangoSearchView/linksEditor/LinksDropdown.tsx
  js/apps/system/_admin/aardvark/APP/react/src/views/views/editView/EditViewContext.tsx
Labels: cla-signed

#21667 if we don't waitpid, we leave zombies. Don't do that.
  js/client/modules/@arangodb/test-helper.js
Labels: cla-signed

#21666 if we don't waitpid, we leave zombies. Don't do that.
  js/client/modules/@arangodb/test-helper.js
Labels: 3 - Testing, cla-signed

#21665 FE-538: fix frontend build warnings
  CHANGELOG
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/dygraph-combined.min.js
  js/apps/system/_admin/aardvark/APP/frontend/js/lib/wheelnav.min.js
  js/apps/system/_admin/aardvark/APP/react/yarn.lock
Labels: cla-signed

#21670 circle ci doesn't allow us to attach a GDB. Hence we need to SIG_ABRT processes
  js/client/modules/@arangodb/testutils/crash-utils.js
  scripts/test/test_config.py
Labels: 3 - Testing, cla-signed

#21671 Bug fix 3.11/circle ci dont gdb attach
  js/client/modules/@arangodb/testutils/crash-utils.js
  scripts/test/test_config.py
Labels: 3 - Testing

#21664 Fix priority inversion in Maintenance [BTS-2100]
  CHANGELOG
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/SynchronizeShard.cpp
  arangod/Cluster/SynchronizeShard.h
Labels: cla-signed

#21668 Simplify maintenance by removing unused features
  CHANGELOG
  arangod/Cluster/Action.cpp
  arangod/Cluster/Action.h
  arangod/Cluster/ActionBase.cpp
  arangod/Cluster/ActionDescription.h
  arangod/Cluster/Maintenance.cpp
  arangod/Cluster/MaintenanceFeature.cpp
  arangod/Cluster/MaintenanceFeature.h
  arangod/Cluster/MaintenanceWorker.cpp
  tests/Maintenance/MaintenanceFeatureMock.h
  tests/Maintenance/MaintenanceFeatureTest.cpp
Labels: cla-signed

#21676 fix: missing semicolon
  js/apps/system/_admin/aardvark/APP/frontend/js/views/navigationView.js
Labels: cla-signed

#21675 Fix TSAN issue in LogicalCollection [BTS-2103]
  CHANGELOG
  arangod/VocBase/vocbase.cpp
Labels: cla-signed

#21679 abort fuzzing if we loose the connection to the arangod
  client-tools/Shell/V8ClientConnection.cpp
Labels: 3 - Testing, cla-signed

#21680 abort fuzzing if we loose the connection to the arangod
  client-tools/Shell/V8ClientConnection.cpp
Labels: 3 - Testing, cla-signed

#21681 Fix TSAN issue in LogicalCollection
  CHANGELOG
  arangod/VocBase/vocbase.cpp
Labels: cla-signed

#21642 Add visibility for recent API calls
  CHANGELOG
  Documentation/Metrics/arangodb_api_recording_call_time.yaml
  arangod/Aql/ExecutionEngine.cpp
  arangod/GeneralServer/CommTask.cpp
  arangod/GeneralServer/CommTask.h
  arangod/GeneralServer/GeneralServer.h
  arangod/RestHandler/RestAdminServerHandler.cpp
  arangod/RestHandler/RestAdminServerHandler.h
  arangod/RestServer/ApiRecordingFeature.cpp
  arangod/RestServer/ApiRecordingFeature.h
  arangod/RestServer/arangod.h
  arangod/RestServer/arangod_includes.h
  arangod/arangoserver.cmake
  lib/ApplicationFeatures/ApplicationServer.h
  lib/Containers/AtomicList.h
  lib/Containers/BoundedList.h
  lib/Containers/ResourceManager.h
  lib/Rest/CommonDefines.h
  tests/Basics/AtomicListTest.cpp
  tests/Basics/CMakeLists.txt
Labels: cla-signed

#21682 Fix datarace in tcp acceptor
  arangod/GeneralServer/Acceptor.cpp
  arangod/GeneralServer/Acceptor.h
  arangod/GeneralServer/AcceptorTcp.cpp
  arangod/GeneralServer/AcceptorTcp.h
  arangod/GeneralServer/AcceptorUnixDomain.cpp
  arangod/GeneralServer/AcceptorUnixDomain.h
  arangod/GeneralServer/GeneralServer.cpp
  arangod/GeneralServer/GeneralServer.h
Labels: TSan, cla-signed

#21684 Backport: Fix datarace in tcp acceptor
  arangod/GeneralServer/Acceptor.cpp
  arangod/GeneralServer/Acceptor.h
  arangod/GeneralServer/AcceptorTcp.cpp
  arangod/GeneralServer/AcceptorTcp.h
  arangod/GeneralServer/AcceptorUnixDomain.cpp
  arangod/GeneralServer/AcceptorUnixDomain.h
  arangod/GeneralServer/GeneralServer.cpp
  arangod/GeneralServer/GeneralServer.h
Labels: TSan, cla-signed

#21686 Feature/no subshell arangosh in dump tests
  js/client/modules/@arangodb/testsuites/dump.js
  tests/js/client/dump/check-foxx.js
  tests/js/client/dump/dump-test.inc
Labels: 3 ImportExport, 3 - Testing, cla-signed

#21687 Feature/no subshell arangosh in dump tests (#21686)
  js/client/modules/@arangodb/testsuites/dump.js
  tests/js/server/dump/check-foxx.js
  tests/js/server/dump/dump-test.inc
Labels: 3 ImportExport, 3 - Testing, cla-signed

#21688 save binaries if we don't have coredumps
  scripts/test/testing_runner.py
Labels: 3 - Testing, cla-signed
